import type{AdmissionState,AssuranceEvaluationInput,OperationOptions,Result,ValidationCategory}from'./types.js';
import{digestValue,isSha256,ok,sortedUnique,validId}from'./utils.js';
export interface TrustedAssuranceOperationOptions extends OperationOptions{readonly trustedRiskProfileDigests:readonly string[];readonly trustedUpstreamContextBindingDigests:readonly string[];readonly trustedValidationBindingDigests:readonly string[];}
export interface AssuranceCategoryEvidenceBinding{readonly category:ValidationCategory;readonly evidenceDigests:readonly string[];}
export interface AssuranceValidationBinding{readonly owner:'EXTERNAL_CANONICAL';readonly projectId:string;readonly lineageId:string;readonly candidateSemanticDigest:string;readonly configDigest:string;readonly runtimeDigest:string;readonly toolchainDigest:string;readonly policyDigest:string;readonly categoryEvidence:readonly AssuranceCategoryEvidenceBinding[];readonly platformIds:readonly string[];readonly reachedLadderLevel:0|1|2|3|4|5;readonly materializationState:'COMPLETE'|'INDETERMINATE'|'TRUNCATED';readonly truncated:boolean;readonly indeterminate:boolean;readonly findingSetDigest:string;readonly bindingDigest:string;}
export interface AssuranceUpstreamContextBinding{readonly owner:'EXTERNAL_CANONICAL';readonly projectId:string;readonly lineageId:string;readonly candidateSemanticDigest:string;readonly configDigest:string;readonly runtimeDigest:string;readonly toolchainDigest:string;readonly policyDigest:string;readonly riskProfileDigest:string;readonly dodDigest:string;readonly dodCriterionIds:readonly string[];readonly evidenceHandoffDigest:string;readonly proofHandoffDigest:string;readonly hedsHandoffDigest:string;readonly validationBindingDigest:string;readonly bindingDigest:string;}
export type BoundAssuranceEvaluationInput=AssuranceEvaluationInput&{readonly upstreamContextBinding:AssuranceUpstreamContextBinding;readonly validationBinding:AssuranceValidationBinding};
function trusted(value:string,values:readonly string[]){return isSha256(value)&&values.length>0&&values.every(isSha256)&&values.includes(value);}
export function verifyTrustedRiskProfileDigest(profileDigest:string,options:TrustedAssuranceOperationOptions):Result<boolean>{return ok(trusted(profileDigest,options.trustedRiskProfileDigests));}
export function verifyAssuranceValidationBinding(binding:AssuranceValidationBinding,options:TrustedAssuranceOperationOptions):Result<boolean>{if(binding.owner!=='EXTERNAL_CANONICAL'||!validId(binding.projectId)||!validId(binding.lineageId)||![binding.candidateSemanticDigest,binding.configDigest,binding.runtimeDigest,binding.toolchainDigest,binding.policyDigest,binding.findingSetDigest,binding.bindingDigest].every(isSha256)||binding.platformIds.some(x=>!validId(x)))return ok(false);const categoryEvidence=[...binding.categoryEvidence].map(x=>({category:x.category,evidenceDigests:sortedUnique(x.evidenceDigests)})).sort((a,b)=>a.category<b.category?-1:a.category>b.category?1:0);if(categoryEvidence.some(x=>x.evidenceDigests.length===0||x.evidenceDigests.some(d=>!isSha256(d))))return ok(false);const seen=new Set<string>();for(const x of categoryEvidence){if(seen.has(x.category))return ok(false);seen.add(x.category);}const body={owner:binding.owner,projectId:binding.projectId,lineageId:binding.lineageId,candidateSemanticDigest:binding.candidateSemanticDigest,configDigest:binding.configDigest,runtimeDigest:binding.runtimeDigest,toolchainDigest:binding.toolchainDigest,policyDigest:binding.policyDigest,categoryEvidence,platformIds:sortedUnique(binding.platformIds),reachedLadderLevel:binding.reachedLadderLevel,materializationState:binding.materializationState,truncated:binding.truncated,indeterminate:binding.indeterminate,findingSetDigest:binding.findingSetDigest},d=digestValue(options,'M27_VALIDATION_BINDING_V1',body);return d.ok?ok(d.value===binding.bindingDigest&&trusted(binding.bindingDigest,options.trustedValidationBindingDigests)):d;}
export function verifyAssuranceUpstreamContextBinding(binding:AssuranceUpstreamContextBinding,options:TrustedAssuranceOperationOptions):Result<boolean>{if(binding.owner!=='EXTERNAL_CANONICAL'||!validId(binding.projectId)||!validId(binding.lineageId)||binding.dodCriterionIds.some(x=>!validId(x))||![binding.candidateSemanticDigest,binding.configDigest,binding.runtimeDigest,binding.toolchainDigest,binding.policyDigest,binding.riskProfileDigest,binding.dodDigest,binding.evidenceHandoffDigest,binding.proofHandoffDigest,binding.hedsHandoffDigest,binding.validationBindingDigest,binding.bindingDigest].every(isSha256))return ok(false);const body={owner:binding.owner,projectId:binding.projectId,lineageId:binding.lineageId,candidateSemanticDigest:binding.candidateSemanticDigest,configDigest:binding.configDigest,runtimeDigest:binding.runtimeDigest,toolchainDigest:binding.toolchainDigest,policyDigest:binding.policyDigest,riskProfileDigest:binding.riskProfileDigest,dodDigest:binding.dodDigest,dodCriterionIds:sortedUnique(binding.dodCriterionIds),evidenceHandoffDigest:binding.evidenceHandoffDigest,proofHandoffDigest:binding.proofHandoffDigest,hedsHandoffDigest:binding.hedsHandoffDigest,validationBindingDigest:binding.validationBindingDigest},d=digestValue(options,'M27_UPSTREAM_CONTEXT_BINDING_V1',body);return d.ok?ok(d.value===binding.bindingDigest&&trusted(binding.bindingDigest,options.trustedUpstreamContextBindingDigests)):d;}
