import type{DownstreamProofHandoff}from'@gef-bootstrap/proof-graph';
import type{DownstreamHedsHandoff}from'@gef-bootstrap/heds-delta-review';
import type{AssuranceClass,AssuranceClassification,AssuranceIntentCapsule,AssuranceObligation,AssuranceRequirementProfile,DodAssuranceBinding,HedsHandoffGate,ObligationBindingGate,OperationOptions,PolicyCompatibilityGate,ProofHandoffGate,RequirementClosureEntry,RequirementClosureSnapshot,Result,ValidationCategory}from'./types.js';
import{classRank,compareCodePoint,deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,validId}from'./utils.js';

const CLASS_CATEGORIES:Record<AssuranceClass,readonly ValidationCategory[]>={
STANDARD:['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT'],
STANDARD_PLUS:['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT','INTEGRATION'],
ELEVATED:['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT','INTEGRATION','E2E','PLATFORM_RUNTIME','RECOVERY_INTEGRITY'],
HIGH_ASSURANCE:['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT','INTEGRATION','E2E','PLATFORM_RUNTIME','RECOVERY_INTEGRITY','SECURITY','EXACT_CANDIDATE_SWEEP','BOUNDED_CANCELLABLE'],
MAX_ASSURANCE:['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT','INTEGRATION','E2E','PLATFORM_RUNTIME','RECOVERY_INTEGRITY','SECURITY','EXACT_CANDIDATE_SWEEP','BOUNDED_CANCELLABLE','INDEPENDENT_REVIEW','STARTUP_PURITY']};
const LADDER:Record<AssuranceClass,0|1|2|3|4|5>={STANDARD:1,STANDARD_PLUS:2,ELEVATED:3,HIGH_ASSURANCE:5,MAX_ASSURANCE:5};
const OWNER:Record<ValidationCategory,string>={SOURCE_CONTEXT:'M14_CONTEXT',EVIDENCE:'M24_EVIDENCE',PROOF:'M25_PROOF',SEMANTIC_REVIEW:'M26_HEDS',STATIC:'EXECUTOR_VALIDATION',UNIT_COMPONENT:'M28_TEST_IMPACT',INTEGRATION:'M28_TEST_IMPACT',E2E:'M28_TEST_IMPACT',PLATFORM_RUNTIME:'M28_TEST_IMPACT',SECURITY:'M34_M35_M58_SECURITY',RECOVERY_INTEGRITY:'M36_M37_RELIABILITY',EXACT_CANDIDATE_SWEEP:'M27_ASSURANCE',INDEPENDENT_REVIEW:'REVIEW_AUTHORITY',STARTUP_PURITY:'M27_ASSURANCE',BOUNDED_CANCELLABLE:'M27_ASSURANCE'};
function obligationFor(category:ValidationCategory,options:OperationOptions):Result<AssuranceObligation>{const obligationId=`M27:${category}`,ownerId=OWNER[category],acceptanceRuleId=`RULE:${category}:CURRENT_ACCEPTED`,body={obligationId,category,ownerId,mandatory:true,acceptanceRuleId,replacesObligationId:null};const d=digestValue(options,'ARM27_OBLIGATION',body);return d.ok?ok(deepFreeze({...body,obligationDigest:d.value})):d;}
export function compileAssuranceRequirementProfile(intent:AssuranceIntentCapsule,classification:AssuranceClassification,options:OperationOptions):Result<AssuranceRequirementProfile>{const categories=CLASS_CATEGORIES[classification.effectiveClass],obligations:AssuranceObligation[]=[];for(const category of categories){const o=obligationFor(category,options);if(!o.ok)return o;obligations.push(o.value);}obligations.sort((a,b)=>compareCodePoint(a.obligationId,b.obligationId));const body={projectId:intent.projectId,lineageId:intent.lineageId,workOrderId:intent.workOrderId,candidateSemanticDigest:intent.candidateSemanticDigest,policyDigest:intent.policyDigest,assuranceClass:classification.effectiveClass,obligations,requiredCategories:[...categories].sort(compareCodePoint),ladderFloor:LADDER[classification.effectiveClass],exactCandidateSweepRequired:classRank(classification.effectiveClass)>=classRank('HIGH_ASSURANCE'),independentReviewRequired:classification.effectiveClass==='MAX_ASSURANCE'};const d=digestValue(options,'APM27',body);return d.ok?ok(deepFreeze({...body,profileDigest:d.value})):d;}
export function verifyAssuranceRequirementProfile(profile:AssuranceRequirementProfile,intent:AssuranceIntentCapsule,classification:AssuranceClassification,options:OperationOptions):Result<boolean>{const rebuilt=compileAssuranceRequirementProfile(intent,classification,options);return rebuilt.ok?ok(rebuilt.value.profileDigest===profile.profileDigest):rebuilt;}
export function createObligationBindingGate(profile:AssuranceRequirementProfile,options:OperationOptions):Result<ObligationBindingGate>{const byId=new Map<string,string>(),conflicts=new Set<string>(),missing:string[]=[];for(const o of profile.obligations){if(!validId(o.obligationId)||!validId(o.ownerId)||!validId(o.acceptanceRuleId)||!isSha256(o.obligationDigest))return fail('OBG27_OBLIGATION_INVALID','Assurance obligation is malformed.',o.obligationId);if(!o.ownerId.trim())missing.push(o.obligationId);const prior=byId.get(o.obligationId);if(prior&&prior!==o.obligationDigest)conflicts.add(o.obligationId);else byId.set(o.obligationId,o.obligationDigest);}const valid=conflicts.size===0&&missing.length===0;const body={valid,conflictingObligationIds:sortedUnique([...conflicts]),missingOwnerObligationIds:sortedUnique(missing)};const d=digestValue(options,'OBG27',body);return d.ok?ok(deepFreeze({...body,gateDigest:d.value})):d;}
export function createPolicyCompatibilityGate(expectedPolicyDigest:string,observedPolicyDigests:readonly string[],options:OperationOptions):Result<PolicyCompatibilityGate>{if(!isSha256(expectedPolicyDigest)||observedPolicyDigests.length===0||observedPolicyDigests.some(x=>!isSha256(x)))return fail('PCG27_POLICY_INVALID','Policy compatibility requires SHA-256 policy identities.');const observed=sortedUnique(observedPolicyDigests),stale=observed.some(x=>x!==expectedPolicyDigest),conflict=observed.length>1,valid=!stale&&!conflict;const body={valid,expectedPolicyDigest,observedPolicyDigests:observed,stale,conflict};const d=digestValue(options,'PCG27',body);return d.ok?ok(deepFreeze({...body,gateDigest:d.value})):d;}
export function createDodAssuranceBinding(profile:AssuranceRequirementProfile,dodDigest:string,criterionIds:readonly string[],options:OperationOptions):Result<DodAssuranceBinding>{if(!isSha256(dodDigest)||criterionIds.some(x=>!validId(x)))return fail('DAB27_INPUT_INVALID','DoD binding requires canonical digest and criterion IDs.');const body={profileDigest:profile.profileDigest,dodDigest,criterionIds:sortedUnique(criterionIds)};const d=digestValue(options,'DAB27',body);return d.ok?ok(deepFreeze({...body,bindingDigest:d.value})):d;}

function proofHandoffBody(h:DownstreamProofHandoff){return{owner:h.owner,consumer:h.consumer,snapshotDigest:h.snapshotDigest,proofStates:[...h.proofStates].sort((a,b)=>compareCodePoint(a.claimId,b.claimId)),selectedSupportIds:sortedUnique(h.selectedSupportIds),proofFingerprintDigests:sortedUnique(h.proofFingerprintDigests),invalidationVectorDigest:h.invalidationVectorDigest,unresolvedClaimIds:sortedUnique(h.unresolvedClaimIds),mayPerformDeltaReview:false as const,mayDecideAssurance:false as const,mayMutateDod:false as const,mayCalculateProgress:false as const,mayPromoteCheckpoint:false as const};}
export function createProofHandoffGate(handoff:DownstreamProofHandoff|null,currentSnapshotDigest:string|null,options:OperationOptions):Result<ProofHandoffGate>{if(handoff===null){const body={valid:false,current:false,handoffDigest:null,snapshotDigest:null,unresolvedClaimIds:[] as string[]};const d=digestValue(options,'PHG27',body);return d.ok?ok(deepFreeze({...body,gateDigest:d.value})):d;}if(handoff.owner!=='M25_PROOF'||handoff.consumer!=='M27_ASSURANCE'||!isSha256(handoff.snapshotDigest)||!isSha256(handoff.handoffDigest))return fail('PHG27_HANDOFF_INVALID','M27 requires M25 proof handoff for M27_ASSURANCE.');const hd=digestValue(options,'DPH25',proofHandoffBody(handoff));if(!hd.ok)return hd;const integrityValid=hd.value===handoff.handoffDigest,current=currentSnapshotDigest!==null&&currentSnapshotDigest===handoff.snapshotDigest,valid=integrityValid&&current;const body={valid,current,handoffDigest:handoff.handoffDigest,snapshotDigest:handoff.snapshotDigest,unresolvedClaimIds:sortedUnique(handoff.unresolvedClaimIds)};const d=digestValue(options,'PHG27',body);return d.ok?ok(deepFreeze({...body,gateDigest:d.value})):d;}
function hedsHandoffBody(h:DownstreamHedsHandoff){return{owner:h.owner,consumer:h.consumer,verdictDigest:h.verdictDigest,semanticDigest:h.semanticDigest,verdict:h.verdict,sourceManifestDigest:h.sourceManifestDigest,inventoryDigest:h.inventoryDigest,frontierDigest:h.frontierDigest,gateSetDigest:h.gateSetDigest,impactedSubjectIds:sortedUnique(h.impactedSubjectIds),blockingFindingDigests:sortedUnique(h.blockingFindingDigests),reviewPolicyDigest:h.reviewPolicyDigest,mayDecideAssurance:false as const,maySelectTests:false as const,mayOperateGit:false as const,mayPromoteCheckpoint:false as const};}
export function createHedsHandoffGate(handoff:DownstreamHedsHandoff|null,currentVerdictDigest:string|null,options:OperationOptions):Result<HedsHandoffGate>{if(handoff===null){const body={valid:false,current:false,handoffDigest:null,verdict:null,blockingFindingDigests:[] as string[]};const d=digestValue(options,'HHG27',body);return d.ok?ok(deepFreeze({...body,gateDigest:d.value})):d;}if(handoff.owner!=='M26_HEDS'||handoff.consumer!=='M27_ASSURANCE'||!isSha256(handoff.handoffDigest)||!isSha256(handoff.verdictDigest))return fail('HHG27_HANDOFF_INVALID','M27 requires M26 HEDS handoff for M27_ASSURANCE.');const hd=digestValue(options,'DHH26',hedsHandoffBody(handoff));if(!hd.ok)return hd;const integrityValid=hd.value===handoff.handoffDigest,current=currentVerdictDigest!==null&&currentVerdictDigest===handoff.verdictDigest,valid=integrityValid&&current;const body={valid,current,handoffDigest:handoff.handoffDigest,verdict:handoff.verdict,blockingFindingDigests:sortedUnique(handoff.blockingFindingDigests)};const d=digestValue(options,'HHG27',body);return d.ok?ok(deepFreeze({...body,gateDigest:d.value})):d;}
export function createRequirementClosureSnapshot(profile:AssuranceRequirementProfile,entries:readonly RequirementClosureEntry[],options:OperationOptions):Result<RequirementClosureSnapshot>{const byId=new Map(entries.map(e=>[e.obligationId,e])),canonical:RequirementClosureEntry[]=[];for(const o of profile.obligations){const found=byId.get(o.obligationId);if(found)canonical.push(found);else{const body={obligationId:o.obligationId,state:'INDETERMINATE' as const,sourceDigests:[] as string[],reasonCodes:['MISSING_ADMISSION_FACT']};const d=digestValue(options,'RCS27_ENTRY',body);if(!d.ok)return d;canonical.push(deepFreeze({...body,entryDigest:d.value}));}}canonical.sort((a,b)=>compareCodePoint(a.obligationId,b.obligationId));const requiredCount=profile.obligations.filter(o=>o.mandatory).length,satisfiedCount=canonical.filter(e=>e.state==='SATISFIED'||e.state==='NOT_APPLICABLE').length,blockedCount=canonical.filter(e=>e.state==='BLOCKED'||e.state==='CONFLICT').length,unresolvedCount=requiredCount-satisfiedCount;const body={profileDigest:profile.profileDigest,entries:canonical,requiredCount,satisfiedCount,unresolvedCount,blockedCount};const d=digestValue(options,'RCS27',body);return d.ok?ok(deepFreeze({...body,snapshotDigest:d.value})):d;}
