import type{AssuranceEvaluation,AssuranceExecutionPlan,AssuranceGateReceipt,AssuranceGateSet,AssuranceGateState,AssuranceRequirementProfile,OperationOptions,RequirementClosureEntry,Result,ValidationCategory}from'./types.js';
import type{BoundAssuranceEvaluationInput,TrustedAssuranceOperationOptions}from'./context-binding.js';
import{deepFreeze,digestValue,fail,ok,sortedUnique}from'./utils.js';
import{classifyAssurance,createAssuranceBudgetGuard,createAssuranceClassificationGate,createFullContextEscalation}from'./s01-classification.js';
import{compileAssuranceRequirementProfile,createDodAssuranceBinding,createHedsHandoffGate,createObligationBindingGate,createPolicyCompatibilityGate,createProofHandoffGate,createRequirementClosureSnapshot}from'./s02-requirements.js';
import{createAssuranceEvidenceReceipt,createBlockingSeverityGate,createContextAdmissionGate,createEvidenceAdmissionGate,createEvidenceCoverageGate,createHedsSemanticGate,createProofSufficiencyGate,createUncertaintyAmplificationGate,makeClosureEntry}from'./s03-admission.js';

function createGate(gateId:string,state:AssuranceGateState,reasonCodes:readonly string[],options:OperationOptions):Result<AssuranceGateReceipt>{const body={gateId,state,reasonCodes:sortedUnique(reasonCodes)};const d=digestValue(options,gateId,body);return d.ok?ok(deepFreeze({...body,receiptDigest:d.value})):d;}
export function createAssuranceExecutionPlan(profile:AssuranceRequirementProfile,options:OperationOptions):Result<AssuranceExecutionPlan>{const orderedCategories=[...profile.requiredCategories],parallelGroups:ValidationCategory[][]=[];const validationGroup=orderedCategories.filter(x=>['STATIC','UNIT_COMPONENT','INTEGRATION','E2E','PLATFORM_RUNTIME','SECURITY','RECOVERY_INTEGRITY','STARTUP_PURITY','BOUNDED_CANCELLABLE'].includes(x));if(validationGroup.length>0)parallelGroups.push(validationGroup);const body={profileDigest:profile.profileDigest,orderedCategories,parallelGroups,ladderFloor:profile.ladderFloor,exactCandidateSweepRequired:profile.exactCandidateSweepRequired};const d=digestValue(options,'AEP27',body);return d.ok?ok(deepFreeze({...body,planDigest:d.value})):d;}
function categoryEvidence(input:BoundAssuranceEvaluationInput,category:ValidationCategory){return input.validationBinding.categoryEvidence.find(x=>x.category===category)?.evidenceDigests??[];}
function admittedCategory(input:BoundAssuranceEvaluationInput,category:ValidationCategory,accepted:Set<string>){const evidence=categoryEvidence(input,category);return evidence.length>0&&evidence.every(x=>accepted.has(x));}
function categorySatisfied(category:ValidationCategory,input:BoundAssuranceEvaluationInput,proofState:AssuranceGateState,hedsState:AssuranceGateState,evidenceAccepted:readonly string[],contextState:AssuranceGateState):{state:RequirementClosureEntry['state'];sources:string[];reasons:string[]}{const accepted=new Set(evidenceAccepted),sources=[...categoryEvidence(input,category)],admitted=admittedCategory(input,category,accepted);switch(category){case'SOURCE_CONTEXT':return contextState==='PASS'?{state:'SATISFIED',sources:[],reasons:['CONTEXT_CURRENT']}:{state:contextState==='BLOCKED'?'BLOCKED':'INDETERMINATE',sources:[],reasons:['CONTEXT_NOT_CURRENT']};case'EVIDENCE':return evidenceAccepted.length>0?{state:'SATISFIED',sources:[...evidenceAccepted],reasons:['EVIDENCE_CURRENT']}:{state:'INDETERMINATE',sources:[],reasons:['EVIDENCE_NOT_CURRENT']};case'PROOF':return proofState==='PASS'?{state:'SATISFIED',sources:[],reasons:['PROOF_CURRENT']}:{state:proofState==='BLOCKED'?'BLOCKED':'INDETERMINATE',sources:[],reasons:['PROOF_NOT_CLOSED']};case'SEMANTIC_REVIEW':return hedsState==='PASS'?{state:'SATISFIED',sources:[],reasons:['HEDS_APPROVED']}:{state:hedsState==='FAIL'?'UNSATISFIED':hedsState==='BLOCKED'?'BLOCKED':'INDETERMINATE',sources:[],reasons:['HEDS_NOT_APPROVED']};case'PLATFORM_RUNTIME':return admitted&&input.validationBinding.platformIds.length>0?{state:'SATISFIED',sources,reasons:['PLATFORM_RUNTIME_EVIDENCE_ACCEPTED']}:{state:'UNSATISFIED',sources:[],reasons:['PLATFORM_RUNTIME_EVIDENCE_REQUIRED']};case'EXACT_CANDIDATE_SWEEP':return admitted?{state:'SATISFIED',sources,reasons:['EXACT_CANDIDATE_EVIDENCE_ACCEPTED']}:{state:'UNSATISFIED',sources:[],reasons:['EXACT_CANDIDATE_EVIDENCE_REQUIRED']};default:return admitted?{state:'SATISFIED',sources,reasons:['VALIDATION_EVIDENCE_ACCEPTED']}:{state:'UNSATISFIED',sources:[],reasons:['VALIDATION_EVIDENCE_REQUIRED']};}}
function admissionStateToGate(state:RequirementClosureEntry['state']):AssuranceGateState{return state==='SATISFIED'||state==='NOT_APPLICABLE'?'PASS':state==='BLOCKED'||state==='CONFLICT'?'BLOCKED':state==='UNSATISFIED'?'FAIL':'INDETERMINATE';}
function precedence(states:readonly AssuranceGateState[]):AssuranceGateState{if(states.includes('TRUNCATED'))return'TRUNCATED';if(states.includes('BLOCKED'))return'BLOCKED';if(states.includes('INDETERMINATE'))return'INDETERMINATE';if(states.includes('FAIL'))return'FAIL';return'PASS';}
export function evaluateAssurance(input:BoundAssuranceEvaluationInput,options:TrustedAssuranceOperationOptions):Result<AssuranceEvaluation>{
if(input.upstreamContextBinding.riskProfileDigest!==input.riskProfile.profileDigest)return fail('CAG27_RISK_BINDING_MISMATCH','Trusted upstream context does not bind the supplied risk profile.');
if(input.upstreamContextBinding.dodDigest!==input.dodDigest||JSON.stringify(sortedUnique(input.upstreamContextBinding.dodCriterionIds))!==JSON.stringify(sortedUnique(input.dodCriterionIds)))return fail('CAG27_DOD_BINDING_MISMATCH','Trusted upstream context does not bind the supplied DoD identity.');
const findingSet=digestValue(options,'ASSURANCE_FINDING_SET27',{findingDigests:sortedUnique(input.findings.map(f=>f.findingDigest))});if(!findingSet.ok)return findingSet;if(findingSet.value!==input.validationBinding.findingSetDigest)return fail('CAG27_FINDING_SET_MISMATCH','Trusted validation binding does not bind the supplied assurance finding set.');
const classification=classifyAssurance(input.intent,input.riskProfile,options);if(!classification.ok)return classification;
const classificationGate=createAssuranceClassificationGate(input.intent,input.riskProfile,classification.value,options);if(!classificationGate.ok)return classificationGate;if(!classificationGate.value.valid)return fail('ACG27_REJECTED','Classification gate rejected assurance context.');
const budgetGuard=createAssuranceBudgetGuard(classification.value,input.budget,options);if(!budgetGuard.ok)return budgetGuard;const contextEscalation=createFullContextEscalation(classification.value,options);if(!contextEscalation.ok)return contextEscalation;
const profile=compileAssuranceRequirementProfile(input.intent,classification.value,options);if(!profile.ok)return profile;const obligationGate=createObligationBindingGate(profile.value,options);if(!obligationGate.ok)return obligationGate;const policyGate=createPolicyCompatibilityGate(input.intent.policyDigest,[input.currentPolicyDigest],options);if(!policyGate.ok)return policyGate;const dod=createDodAssuranceBinding(profile.value,input.dodDigest,input.dodCriterionIds,options);if(!dod.ok)return dod;
const evidence=createEvidenceAdmissionGate(input.evidenceHandoff,input.currentEvidenceManifestDigest,options);if(!evidence.ok)return evidence;const proofHandoff=createProofHandoffGate(input.proofHandoff,input.currentProofSnapshotDigest,options);if(!proofHandoff.ok)return proofHandoff;const hedsHandoff=createHedsHandoffGate(input.hedsHandoff,input.currentHedsVerdictDigest,options);if(!hedsHandoff.ok)return hedsHandoff;const proof=createProofSufficiencyGate(proofHandoff.value,options);if(!proof.ok)return proof;const heds=createHedsSemanticGate(hedsHandoff.value,options);if(!heds.ok)return heds;const blocking=createBlockingSeverityGate(input.findings,options);if(!blocking.ok)return blocking;const context=createContextAdmissionGate(input.intent,profile.value,input.currentPolicyDigest,evidence.value,proofHandoff.value,hedsHandoff.value,input.upstreamContextBinding,input.validationBinding,options);if(!context.ok)return context;const uncertainty=createUncertaintyAmplificationGate(evidence.value,proof.value,heds.value,true,options);if(!uncertainty.ok)return uncertainty;
const admittedEvidence=evidence.value.valid&&evidence.value.current?evidence.value.acceptedEvidenceDigests:[];const entries:RequirementClosureEntry[]=[];for(const o of profile.value.obligations){const x=categorySatisfied(o.category,input,proof.value.state,heds.value.state,admittedEvidence,context.value.state),entry=makeClosureEntry(o.obligationId,x.state,x.sources,x.reasons,options);if(!entry.ok)return entry;entries.push(entry.value);}const closure=createRequirementClosureSnapshot(profile.value,entries,options);if(!closure.ok)return closure;const coverage=createEvidenceCoverageGate(profile.value,entries,options);if(!coverage.ok)return coverage;const evidenceReceipt=createAssuranceEvidenceReceipt(profile.value,evidence.value,proof.value,heds.value,options);if(!evidenceReceipt.ok)return evidenceReceipt;const plan=createAssuranceExecutionPlan(profile.value,options);if(!plan.ok)return plan;
const accepted=new Set(admittedEvidence),ladderState:AssuranceGateState=input.validationBinding.reachedLadderLevel>=profile.value.ladderFloor?'PASS':'FAIL',ladder=createGate('LFG27',ladderState,ladderState==='PASS'?['LADDER_FLOOR_MET']:['LADDER_FLOOR_NOT_MET'],options);if(!ladder.ok)return ladder;
const exactRequired=profile.value.exactCandidateSweepRequired,exactOk=!exactRequired||admittedCategory(input,'EXACT_CANDIDATE_SWEEP',accepted),exact=createGate('EHF27',exactOk?'PASS':'FAIL',exactOk?['EXACT_CANDIDATE_OK']:['EXACT_CANDIDATE_EVIDENCE_MISSING'],options);if(!exact.ok)return exact;
const platformRequired=profile.value.requiredCategories.includes('PLATFORM_RUNTIME'),platformOk=!platformRequired||(admittedCategory(input,'PLATFORM_RUNTIME',accepted)&&input.validationBinding.platformIds.length>0),runtime=createGate('RPG27',platformOk?'PASS':'FAIL',platformOk?['RUNTIME_PLATFORM_OK']:['RUNTIME_PLATFORM_EVIDENCE_MISSING'],options);if(!runtime.ok)return runtime;
const securityRequired=profile.value.requiredCategories.includes('SECURITY'),securityOk=!securityRequired||admittedCategory(input,'SECURITY',accepted),security=createGate('SAG27',securityOk?'PASS':'FAIL',securityOk?['SECURITY_OBLIGATION_OK']:['SECURITY_EVIDENCE_MISSING'],options);if(!security.ok)return security;
const freshnessState:AssuranceGateState=policyGate.value.valid&&context.value.state==='PASS'&&evidence.value.current&&proofHandoff.value.current&&hedsHandoff.value.current?'PASS':context.value.state==='BLOCKED'?'BLOCKED':'INDETERMINATE',freshness=createGate('CFG27',freshnessState,freshnessState==='PASS'?['ALL_CURRENT']:['CURRENT_TRUTH_REQUIRED'],options);if(!freshness.ok)return freshness;
const materializationState:AssuranceGateState=input.validationBinding.materializationState==='TRUNCATED'||input.validationBinding.truncated?'TRUNCATED':input.validationBinding.materializationState==='INDETERMINATE'||input.validationBinding.indeterminate?'INDETERMINATE':'PASS',materialization=createGate('BMG27',materializationState,materializationState==='PASS'?['MATERIALIZATION_COMPLETE']:['MATERIALIZATION_NOT_COMPLETE'],options);if(!materialization.ok)return materialization;
const coverageReceipt=createGate('ECG27',coverage.value.state,coverage.value.state==='PASS'?['ALL_OBLIGATIONS_CLOSED']:['ASSURANCE_OBLIGATIONS_OPEN'],options);if(!coverageReceipt.ok)return coverageReceipt;const blockingReceipt=createGate('BSG27',blocking.value.state,blocking.value.state==='PASS'?['NO_BLOCKING_FINDINGS']:['BLOCKING_FINDINGS_PRESENT'],options);if(!blockingReceipt.ok)return blockingReceipt;
const admissionState=precedence([classification.value.state==='RESOLVED'?'PASS':'INDETERMINATE',obligationGate.value.valid?'PASS':'BLOCKED',policyGate.value.valid?'PASS':policyGate.value.conflict?'BLOCKED':'INDETERMINATE',...entries.map(e=>admissionStateToGate(e.state)),ladder.value.state,exact.value.state,runtime.value.state,security.value.state,freshness.value.state,materialization.value.state,coverageReceipt.value.state,blockingReceipt.value.state]),admission=createGate('VAG27',admissionState,admissionState==='PASS'?['ASSURANCE_ADMISSIBLE']:[`ASSURANCE_${admissionState}`],options);if(!admission.ok)return admission;
const gateBody={ladderFloor:ladder.value,exactHead:exact.value,runtimePlatform:runtime.value,security:security.value,contextFreshness:freshness.value,budgetMaterialization:materialization.value,evidenceCoverage:coverageReceipt.value,blockingSeverity:blockingReceipt.value,verdictAdmission:admission.value};const gd=digestValue(options,'ASSURANCE_GATE_SET27',{...gateBody,upstreamContextBindingDigest:input.upstreamContextBinding.bindingDigest,validationBindingDigest:input.validationBinding.bindingDigest,contextAdmissionGateDigest:context.value.gateDigest});if(!gd.ok)return gd;const gates:AssuranceGateSet=deepFreeze({...gateBody,gateSetDigest:gd.value});const ed=digestValue(options,'ASSURANCE_EVALUATION27',{classificationDigest:classification.value.classificationDigest,profileDigest:profile.value.profileDigest,closureDigest:closure.value.snapshotDigest,evidenceReceiptDigest:evidenceReceipt.value.receiptDigest,planDigest:plan.value.planDigest,gateSetDigest:gates.gateSetDigest,budgetGuardDigest:budgetGuard.value.guardDigest,contextEscalationDigest:contextEscalation.value.escalationDigest,dodBindingDigest:dod.value.bindingDigest,uncertaintyDigest:uncertainty.value.gateDigest,upstreamContextBindingDigest:input.upstreamContextBinding.bindingDigest,validationBindingDigest:input.validationBinding.bindingDigest,contextAdmissionGateDigest:context.value.gateDigest});return ed.ok?ok(deepFreeze({classification:classification.value,profile:profile.value,closure:closure.value,evidenceReceipt:evidenceReceipt.value,executionPlan:plan.value,gates,evaluationDigest:ed.value})):ed;}
