import type{DownstreamProofContextHandoff}from'@gef-bootstrap/evidence-engine';
import type{DownstreamProofHandoff}from'@gef-bootstrap/proof-graph';
import type{DownstreamHedsHandoff}from'@gef-bootstrap/heds-delta-review';

export type AssuranceClass='STANDARD'|'STANDARD_PLUS'|'ELEVATED'|'HIGH_ASSURANCE'|'MAX_ASSURANCE';
export type AssuranceVerdict='ASSURED'|'CORRECTION_REQUIRED'|'BLOCKED'|'INDETERMINATE'|'TRUNCATED';
export type AssuranceGateState='PASS'|'FAIL'|'BLOCKED'|'INDETERMINATE'|'TRUNCATED';
export type AdmissionState='SATISFIED'|'UNSATISFIED'|'BLOCKED'|'STALE'|'CONFLICT'|'INDETERMINATE'|'NOT_APPLICABLE';
export type RiskTruthState='KNOWN'|'UNKNOWN'|'CONFLICT';
export type RiskLevel='NONE'|'LOW'|'MATERIAL'|'HIGH'|'CRITICAL';
export type RiskKind='ASSURANCE_AUTHORITY'|'EVIDENCE_ROOT'|'PROOF_ROOT'|'SECURITY_BOUNDARY'|'SECRETS'|'SIGNING'|'MONEY'|'PRIVILEGED_AUTHORIZATION'|'DESTRUCTIVE_IRREVERSIBLE'|'CRITICAL_DATA_INTEGRITY'|'RECOVERY_SENSITIVE'|'CROSS_BOUNDARY_STATE'|'RELEASE_SIGNIFICANCE'|'PUBLIC_CONTRACT'|'UNCERTAINTY';
export type ValidationCategory='SOURCE_CONTEXT'|'EVIDENCE'|'PROOF'|'SEMANTIC_REVIEW'|'STATIC'|'UNIT_COMPONENT'|'INTEGRATION'|'E2E'|'PLATFORM_RUNTIME'|'SECURITY'|'RECOVERY_INTEGRITY'|'EXACT_CANDIDATE_SWEEP'|'INDEPENDENT_REVIEW'|'STARTUP_PURITY'|'BOUNDED_CANCELLABLE';
export type FindingSeverity='CRITICAL'|'HIGH'|'MEDIUM'|'LOW'|'INFO';
export type FindingState='OPEN'|'RESOLVED'|'SUPERSEDED'|'INDETERMINATE';
export type ReplayState='CLEAR'|'CONFLICT'|'TRUNCATED';

export interface DigestPort{readonly algorithm:'sha256';digest(input:string):string;}
export interface CancellationPort{isCancelled():boolean;}
export interface OperationOptions{readonly digest:DigestPort;readonly cancellation?:CancellationPort|undefined;readonly maxUnits?:number|undefined;readonly maxHistory?:number|undefined;}
export interface Diagnostic{readonly code:string;readonly message:string;readonly subject?:string|undefined;}
export type Result<T>={readonly ok:true;readonly value:T}|{readonly ok:false;readonly diagnostics:readonly Diagnostic[]};

export interface AssuranceIntentInput{readonly intentId:string;readonly projectId:string;readonly lineageId:string;readonly workOrderId:string;readonly candidateId:string;readonly candidateSemanticDigest:string;readonly configDigest:string;readonly runtimeDigest:string;readonly toolchainDigest:string;readonly requestedClass:AssuranceClass;readonly purpose:string;readonly policyDigest:string;}
export interface AssuranceIntentCapsule extends AssuranceIntentInput{readonly intentDigest:string;}
export interface AssuranceAuthorityBoundary{readonly intentDigest:string;readonly authority:'ASSURANCE_CLASS_REQUIREMENT_VERDICT_ONLY';readonly mayValidateEvidence:false;readonly mayDecideProof:false;readonly mayPerformSemanticReview:false;readonly maySelectTests:false;readonly mayOperateGit:false;readonly mayOperateCi:false;readonly mayPromoteCheckpoint:false;readonly mayCalculateProgress:false;readonly mayComputeProjectStatus:false;readonly mayRelease:false;readonly boundaryDigest:string;}
export interface AssuranceRiskSignal{readonly signalId:string;readonly kind:RiskKind;readonly ownerId:string;readonly truthState:RiskTruthState;readonly level:RiskLevel;readonly semanticDigest:string;}
export interface AssuranceRiskProfile{readonly projectId:string;readonly lineageId:string;readonly candidateSemanticDigest:string;readonly policyDigest:string;readonly signals:readonly AssuranceRiskSignal[];readonly complete:boolean;readonly conflictingSignalIds:readonly string[];readonly profileDigest:string;}
export interface AssuranceClassification{readonly state:'RESOLVED'|'INDETERMINATE'|'CONFLICT';readonly derivedFloor:AssuranceClass;readonly effectiveClass:AssuranceClass;readonly requestedClass:AssuranceClass;readonly fullContextRequired:boolean;readonly highSignalIds:readonly string[];readonly reasonCodes:readonly string[];readonly classificationDigest:string;}
export interface AssuranceBudget{readonly tokenBudget:number|null;readonly searchBudget:number|null;readonly fileBudget:number|null;readonly testBudget:number|null;readonly latencyBudgetMs:number|null;}
export interface AssuranceBudgetGuard{readonly classificationDigest:string;readonly downgradeAttempted:boolean;readonly assurancePreserved:boolean;readonly guardDigest:string;}
export interface FullContextEscalation{readonly required:boolean;readonly minimumContextMode:'BOUNDED'|'EXPANDED'|'FULL';readonly reasonCodes:readonly string[];readonly escalationDigest:string;}
export interface AssuranceClassificationGate{readonly valid:boolean;readonly intentDigest:string;readonly riskProfileDigest:string;readonly classificationDigest:string;readonly policyDigest:string;readonly gateDigest:string;}

export interface AssuranceObligation{readonly obligationId:string;readonly category:ValidationCategory;readonly ownerId:string;readonly mandatory:boolean;readonly acceptanceRuleId:string;readonly replacesObligationId:string|null;readonly obligationDigest:string;}
export interface AssuranceRequirementProfile{readonly projectId:string;readonly lineageId:string;readonly workOrderId:string;readonly candidateSemanticDigest:string;readonly policyDigest:string;readonly assuranceClass:AssuranceClass;readonly obligations:readonly AssuranceObligation[];readonly requiredCategories:readonly ValidationCategory[];readonly ladderFloor:0|1|2|3|4|5;readonly exactCandidateSweepRequired:boolean;readonly independentReviewRequired:boolean;readonly profileDigest:string;}
export interface ObligationBindingGate{readonly valid:boolean;readonly conflictingObligationIds:readonly string[];readonly missingOwnerObligationIds:readonly string[];readonly gateDigest:string;}
export interface PolicyCompatibilityGate{readonly valid:boolean;readonly expectedPolicyDigest:string;readonly observedPolicyDigests:readonly string[];readonly stale:boolean;readonly conflict:boolean;readonly gateDigest:string;}
export interface DodAssuranceBinding{readonly profileDigest:string;readonly dodDigest:string;readonly criterionIds:readonly string[];readonly bindingDigest:string;}
export interface ProofHandoffGate{readonly valid:boolean;readonly current:boolean;readonly handoffDigest:string|null;readonly snapshotDigest:string|null;readonly unresolvedClaimIds:readonly string[];readonly gateDigest:string;}
export interface HedsHandoffGate{readonly valid:boolean;readonly current:boolean;readonly handoffDigest:string|null;readonly verdict:'APPROVED'|'CORRECTION_REQUIRED'|'BLOCKED'|'INDETERMINATE'|'TRUNCATED'|null;readonly blockingFindingDigests:readonly string[];readonly gateDigest:string;}
export interface RequirementClosureEntry{readonly obligationId:string;readonly state:AdmissionState;readonly sourceDigests:readonly string[];readonly reasonCodes:readonly string[];readonly entryDigest:string;}
export interface RequirementClosureSnapshot{readonly profileDigest:string;readonly entries:readonly RequirementClosureEntry[];readonly requiredCount:number;readonly satisfiedCount:number;readonly unresolvedCount:number;readonly blockedCount:number;readonly snapshotDigest:string;}

export interface EvidenceAdmissionGate{readonly valid:boolean;readonly current:boolean;readonly handoffDigest:string|null;readonly acceptedEvidenceDigests:readonly string[];readonly rejectedEvidenceDigests:readonly string[];readonly staleEvidenceDigests:readonly string[];readonly conflictEvidenceDigests:readonly string[];readonly unresolvedClaimIds:readonly string[];readonly gateDigest:string;}
export interface ProofSufficiencyGate{readonly state:AssuranceGateState;readonly unresolvedClaimIds:readonly string[];readonly gateDigest:string;}
export interface HedsSemanticGate{readonly state:AssuranceGateState;readonly blockingFindingDigests:readonly string[];readonly gateDigest:string;}
export interface EvidenceCoverageGate{readonly state:AssuranceGateState;readonly missingObligationIds:readonly string[];readonly gateDigest:string;}
export interface UncertaintyAmplificationGate{readonly widened:boolean;readonly addedCategoryRequirements:readonly ValidationCategory[];readonly reasonCodes:readonly string[];readonly gateDigest:string;}
export interface AssuranceFinding{readonly findingId:string;readonly severity:FindingSeverity;readonly state:FindingState;readonly ownerId:string;readonly ruleId:string;readonly sourceDigest:string;readonly supersedesFindingDigest:string|null;readonly findingDigest:string;}
export interface BlockingSeverityGate{readonly state:AssuranceGateState;readonly blockingFindingDigests:readonly string[];readonly gateDigest:string;}
export interface ContextAdmissionGate{readonly state:AssuranceGateState;readonly mismatchDimensions:readonly string[];readonly gateDigest:string;}
export interface AssuranceEvidenceReceipt{readonly profileDigest:string;readonly evidenceGateDigest:string;readonly proofGateDigest:string;readonly hedsGateDigest:string;readonly admittedSourceDigests:readonly string[];readonly rejectedSourceDigests:readonly string[];readonly staleSourceDigests:readonly string[];readonly conflictSourceDigests:readonly string[];readonly unresolvedIds:readonly string[];readonly receiptDigest:string;}

export interface AssuranceExecutionPlan{readonly profileDigest:string;readonly orderedCategories:readonly ValidationCategory[];readonly parallelGroups:readonly (readonly ValidationCategory[])[];readonly ladderFloor:0|1|2|3|4|5;readonly exactCandidateSweepRequired:boolean;readonly planDigest:string;}
export interface AssuranceValidationObservation{readonly reachedLadderLevel:0|1|2|3|4|5;readonly completedCategories:readonly ValidationCategory[];readonly acceptedEvidenceDigests:readonly string[];readonly exactCandidateSemanticDigest:string|null;readonly configDigest:string|null;readonly runtimeDigest:string|null;readonly toolchainDigest:string|null;readonly platformIds:readonly string[];readonly securitySatisfied:boolean;readonly independentReviewSatisfied:boolean;readonly truncated:boolean;readonly indeterminate:boolean;}
export interface AssuranceGateReceipt{readonly gateId:string;readonly state:AssuranceGateState;readonly reasonCodes:readonly string[];readonly receiptDigest:string;}
export interface AssuranceGateSet{readonly ladderFloor:AssuranceGateReceipt;readonly exactHead:AssuranceGateReceipt;readonly runtimePlatform:AssuranceGateReceipt;readonly security:AssuranceGateReceipt;readonly contextFreshness:AssuranceGateReceipt;readonly budgetMaterialization:AssuranceGateReceipt;readonly evidenceCoverage:AssuranceGateReceipt;readonly blockingSeverity:AssuranceGateReceipt;readonly verdictAdmission:AssuranceGateReceipt;readonly gateSetDigest:string;}

export interface AssuranceEvaluationInput{readonly intent:AssuranceIntentCapsule;readonly riskProfile:AssuranceRiskProfile;readonly currentPolicyDigest:string;readonly budget:AssuranceBudget;readonly dodDigest:string;readonly dodCriterionIds:readonly string[];readonly evidenceHandoff:DownstreamProofContextHandoff|null;readonly currentEvidenceManifestDigest:string|null;readonly proofHandoff:DownstreamProofHandoff|null;readonly currentProofSnapshotDigest:string|null;readonly hedsHandoff:DownstreamHedsHandoff|null;readonly currentHedsVerdictDigest:string|null;readonly findings:readonly AssuranceFinding[];readonly validation:AssuranceValidationObservation;readonly materializationState:'COMPLETE'|'INDETERMINATE'|'TRUNCATED';}
export interface AssuranceEvaluation{readonly classification:AssuranceClassification;readonly profile:AssuranceRequirementProfile;readonly closure:RequirementClosureSnapshot;readonly evidenceReceipt:AssuranceEvidenceReceipt;readonly executionPlan:AssuranceExecutionPlan;readonly gates:AssuranceGateSet;readonly evaluationDigest:string;}

export interface AssuranceVerdictCapsule{readonly verdictId:string;readonly projectId:string;readonly lineageId:string;readonly workOrderId:string;readonly candidateSemanticDigest:string;readonly configDigest:string;readonly runtimeDigest:string;readonly toolchainDigest:string;readonly policyDigest:string;readonly assuranceClass:AssuranceClass;readonly profileDigest:string;readonly gateSetDigest:string;readonly evidenceReceiptDigest:string;readonly findingDigests:readonly string[];readonly reasonCodes:readonly string[];readonly verdict:AssuranceVerdict;readonly predecessorVerdictDigest:string|null;readonly semanticDigest:string;readonly verdictDigest:string;}
export interface AssuranceIntegrityReceipt{readonly verdictDigest:string;readonly recomputedSemanticDigest:string;readonly expectedVerdict:AssuranceVerdict;readonly valid:boolean;readonly receiptDigest:string;}
export interface AssuranceTransitionReceipt{readonly predecessorVerdictDigest:string|null;readonly successorVerdictDigest:string;readonly changedDimensions:readonly string[];readonly reasonCodes:readonly string[];readonly receiptDigest:string;}
export interface AssuranceReplayGuard{readonly state:ReplayState;readonly acceptedVerdictDigests:readonly string[];readonly duplicateVerdictDigests:readonly string[];readonly conflictingVerdictIds:readonly string[];readonly historyTruncated:boolean;readonly processedCount:number;readonly totalCount:number;readonly guardDigest:string;}
export interface AssuranceSplitBrainWitness{readonly predecessorVerdictDigest:string;readonly successorSemanticDigests:readonly string[];readonly splitBrain:boolean;readonly witnessDigest:string;}
export interface AssuranceReopenWitness{readonly predecessorVerdictDigest:string;readonly successorCandidateSemanticDigest:string;readonly ownerId:string;readonly authorizationDigest:string;readonly reasonCodes:readonly string[];readonly witnessDigest:string;}
export interface DownstreamAssuranceHandoff{readonly owner:'M27_ASSURANCE';readonly consumer:'M28_TEST_IMPACT'|'GOVERNANCE'|'RELEASE';readonly verdictDigest:string;readonly semanticDigest:string;readonly verdict:AssuranceVerdict;readonly assuranceClass:AssuranceClass;readonly profileDigest:string;readonly gateSetDigest:string;readonly candidateSemanticDigest:string;readonly configDigest:string;readonly runtimeDigest:string;readonly toolchainDigest:string;readonly blockingFindingDigests:readonly string[];readonly maySelectTests:false;readonly mayOperateGit:false;readonly mayOperateCi:false;readonly mayPromoteCheckpoint:false;readonly mayCalculateProgress:false;readonly mayComputeProjectStatus:false;readonly mayRelease:false;readonly handoffDigest:string;}
