import type{ArtifactGateEvaluationInput,GateEvaluationInput,GateReceipt,GateState,OperationOptions,Result,ReviewGateSet,SemanticFinding}from'./types.js';
import{deepFreeze,digestValue,fail,ok,sortedUnique}from'./utils.js';
import{createCrossLineageWitness,createDeltaChangeInventory,createHedsIntent}from'./s01-delta.js';
import{createAuthorityConsistencyGate,createDependencyProjection,createSourceBindingGate,createSourceCoverageManifest,createValidityContextGate,verifyM25ProofHandoff}from'./s02-source.js';
import{createImpactFrontier,createOwnershipReviewFilter,createReviewCandidateIndex,createSemanticDeltaMatrix}from'./s03-review.js';
import{createHedsFindingRegister}from'./s05-finding.js';

function receipt(gateId:string,state:GateState,reasons:readonly string[],reviewPolicyDigest:string|null,options:OperationOptions):Result<GateReceipt>{const body={gateId,state,reviewPolicyDigest,reasonCodes:sortedUnique(reasons)};const d=digestValue(options,gateId,body);return d.ok?ok(deepFreeze({...body,receiptDigest:d.value})):d;}
function blockingFindings(findings:readonly SemanticFinding[]){return findings.filter(f=>(f.severity==='CRITICAL'||f.severity==='HIGH')&&(f.state==='OPEN'||f.state==='INDETERMINATE'));}
function overallState(states:readonly GateState[]):GateState{if(states.includes('TRUNCATED'))return'TRUNCATED';if(states.includes('BLOCKED'))return'BLOCKED';if(states.includes('INDETERMINATE'))return'INDETERMINATE';if(states.includes('FAIL'))return'FAIL';return'PASS';}
type Receipts=Pick<ReviewGateSet,'baselineContinuity'|'sourceCompleteness'|'proofInvalidation'|'findingClosure'|'zeroHighCritical'|'authorityAmbiguity'|'budgetMaterialization'|'verdictAdmission'>;
type Bindings=Omit<ReviewGateSet,keyof Receipts|'gateSetDigest'>;
function finalize(receipts:Receipts,bindings:Bindings,options:OperationOptions):Result<ReviewGateSet>{const body={...receipts,...bindings};const d=digestValue(options,'M26_GATE_SET',body);return d.ok?ok(deepFreeze({...body,gateSetDigest:d.value})):d;}
const nullBindings:Bindings={artifactBound:false,sourceManifestDigest:null,reviewPolicyDigest:null,validityContextGateDigest:null,proofBindingGateDigest:null,dependencyProjectionDigest:null,findingRegisterDigest:null,inventoryDigest:null,matrixDigest:null,frontierDigest:null,candidateIndexDigest:null,ownershipFilterDigest:null,predecessorVerdictDigest:null};

/** Diagnostic-only precedence surface. It cannot mint HVC26. */
export function evaluateReviewGates(input:GateEvaluationInput,options:OperationOptions):Result<ReviewGateSet>{const b=receipt('BCG26',input.baselineContinuity?'PASS':'BLOCKED',input.baselineContinuity?[]:['BASELINE_CONTINUITY_INVALID'],null,options);if(!b.ok)return b;const s=receipt('SCG26',input.sourceCoverageSufficient?'PASS':'INDETERMINATE',input.sourceCoverageSufficient?[]:['SOURCE_COVERAGE_INSUFFICIENT'],null,options);if(!s.ok)return s;const p=receipt('PIG26',input.allInvalidatedProofItemsReviewed?'PASS':'FAIL',input.allInvalidatedProofItemsReviewed?[]:['INVALIDATED_PROOF_ITEM_UNREVIEWED'],null,options);if(!p.ok)return p;const f=receipt('FCG26',input.findingClosureValid?'PASS':'FAIL',input.findingClosureValid?[]:['FINDING_CLOSURE_INVALID'],null,options);if(!f.ok)return f;const high=blockingFindings(input.findings),z=receipt('ZHG26',high.length===0?'PASS':'FAIL',high.map(x=>`${x.severity}:${x.findingId}`),null,options);if(!z.ok)return z;const a=receipt('AAG26',input.authorityConflict?'BLOCKED':'PASS',input.authorityConflict?['AUTHORITY_OR_AMBIGUITY_CONFLICT']:[],null,options);if(!a.ok)return a;const budgetState:GateState=input.truncated?'TRUNCATED':input.indeterminate?'INDETERMINATE':'PASS',m=receipt('BMG26',budgetState,budgetState==='TRUNCATED'?['REVIEW_TRUNCATED']:budgetState==='INDETERMINATE'?['MANDATORY_REVIEW_TRUTH_INDETERMINATE']:[],null,options);if(!m.ok)return m;const vState=overallState([b.value.state,s.value.state,p.value.state,f.value.state,z.value.state,a.value.state,m.value.state]),v=receipt('VAG26',vState,vState==='PASS'?[]:[`PRECONDITION_${vState}`],null,options);if(!v.ok)return v;return finalize({baselineContinuity:b.value,sourceCompleteness:s.value,proofInvalidation:p.value,findingClosure:f.value,zeroHighCritical:z.value,authorityAmbiguity:a.value,budgetMaterialization:m.value,verdictAdmission:v.value},nullBindings,options);}

export function evaluateArtifactReview(input:ArtifactGateEvaluationInput,options:OperationOptions){
 const intentCheck=createHedsIntent(input.intent,options);if(!intentCheck.ok)return intentCheck;if(intentCheck.value.intentDigest!==input.intent.intentDigest)return fail('VAG26_INTENT_TAMPERED','HEDS intent does not match its canonical digest.');const policy=input.intent.reviewPolicyDigest;
 const manifest=createSourceCoverageManifest(input.intent.projectId,input.intent.lineageId,input.baselineSources,input.candidateSources,input.baselineCoverage,input.candidateCoverage,input.dependencyKnowledgeComplete,options);if(!manifest.ok)return manifest;
 const sourceBinding=createSourceBindingGate(input.candidateSources,input.currentSourceIdentities,options);if(!sourceBinding.ok)return sourceBinding;
 const validity=createValidityContextGate(input.intent,input.baseline,input.candidate,manifest.value,sourceBinding.value,options);if(!validity.ok)return validity;
 const lineage=createCrossLineageWitness(input.baseline,input.candidate,options);if(!lineage.ok)return lineage;
 const authority=createAuthorityConsistencyGate(input.candidateSources,options);if(!authority.ok)return authority;
 const dependency=createDependencyProjection([...input.baselineSources,...input.candidateSources],input.dependencyKnowledgeComplete,options,input.knownExternalDependencyDigests);if(!dependency.ok)return dependency;
 const proof=verifyM25ProofHandoff(input.proofHandoff,options);if(!proof.ok)return proof;
 const coverageComplete=input.baselineCoverage==='COMPLETE'&&input.candidateCoverage==='COMPLETE';
 const inventory=createDeltaChangeInventory(input.baseline,input.candidate,input.baselineSources,input.candidateSources,coverageComplete,options);if(!inventory.ok)return inventory;
 const matrix=createSemanticDeltaMatrix(inventory.value,proof.value,options);if(!matrix.ok)return matrix;
 const frontier=createImpactFrontier(matrix.value,inventory.value,dependency.value,input.allKnownSubjectIds,options);if(!frontier.ok)return frontier;
 const ownership=createOwnershipReviewFilter(inventory.value,input.baselineSources,input.candidateSources,options);if(!ownership.ok)return ownership;
 const candidates=createReviewCandidateIndex(inventory.value,frontier.value,input.candidateSources,proof.value,options);if(!candidates.ok)return candidates;
 const findingRegister=createHedsFindingRegister(input.findings,input.priorFindings,options);if(!findingRegister.ok)return findingRegister;

 const prior=input.priorVerdict,priorOk=prior===null||(prior.projectId===input.intent.projectId&&prior.lineageId===input.intent.lineageId&&prior.candidateIdentityDigest===input.baseline.semanticDigest),baselineOk=lineage.value.comparisonAdmissible&&validity.value.valid&&priorOk,bReasons:string[]=[];if(!lineage.value.comparisonAdmissible)bReasons.push('CROSS_LINEAGE');if(!validity.value.valid)bReasons.push('VALIDITY_CONTEXT_INVALID');if(!priorOk)bReasons.push('PRIOR_VERDICT_BRANCH_MIX');const b=receipt('BCG26',baselineOk?'PASS':'BLOCKED',bReasons,policy,options);if(!b.ok)return b;

 const sourceOk=coverageComplete&&manifest.value.dependencyKnowledgeComplete&&dependency.value.complete&&sourceBinding.value.valid&&validity.value.valid,sReasons:string[]=[];if(!coverageComplete)sReasons.push('SOURCE_COVERAGE_INSUFFICIENT');if(!manifest.value.dependencyKnowledgeComplete||!dependency.value.complete)sReasons.push('DEPENDENCY_KNOWLEDGE_INCOMPLETE');if(dependency.value.unknownDependencyDigests.length)sReasons.push('ORPHAN_DEPENDENCY');if(!sourceBinding.value.valid)sReasons.push('CURRENT_SOURCE_BINDING_INVALID');if(!validity.value.valid)sReasons.push('VALIDITY_CONTEXT_INVALID');const s=receipt('SCG26',sourceOk?'PASS':'INDETERMINATE',sReasons,policy,options);if(!s.ok)return s;

 const proofOk=proof.value.valid&&matrix.value.proofBindingGateDigest===proof.value.gateDigest&&proof.value.unresolvedClaimIds.length===0,pReasons:string[]=[];if(!proof.value.valid)pReasons.push('PROOF_BINDING_INVALID');if(matrix.value.proofBindingGateDigest!==proof.value.gateDigest)pReasons.push('PROOF_MATRIX_BINDING_MISMATCH');if(proof.value.unresolvedClaimIds.length>0)pReasons.push('M25_UNRESOLVED_PROOF_CLAIMS');const p=receipt('PIG26',proofOk?'PASS':'FAIL',pReasons,policy,options);if(!p.ok)return p;

 const currentDigests=sortedUnique(input.findings.map(f=>f.findingDigest)),registerDigests=sortedUnique(findingRegister.value.currentFindingDigests),findingClosureValid=JSON.stringify(currentDigests)===JSON.stringify(registerDigests),f=receipt('FCG26',findingClosureValid?'PASS':'FAIL',findingClosureValid?[]:['FINDING_REGISTER_MISMATCH'],policy,options);if(!f.ok)return f;const high=blockingFindings(input.findings),z=receipt('ZHG26',high.length===0?'PASS':'FAIL',high.map(x=>`${x.severity}:${x.findingId}`),policy,options);if(!z.ok)return z;

 const expectedRouted=sortedUnique(inventory.value.entries.filter(e=>e.changeClass!=='UNCHANGED').map(e=>e.subjectId)),actualRouted=sortedUnique(ownership.value.routes.map(r=>r.subjectId)),routingMismatch=JSON.stringify(expectedRouted)!==JSON.stringify(actualRouted),authorityConflict=!authority.value.valid||!validity.value.valid||ownership.value.unresolvedSubjectIds.length>0||routingMismatch,aReasons:string[]=[];if(!authority.value.valid)aReasons.push('SOURCE_AUTHORITY_CONFLICT');if(!validity.value.valid)aReasons.push('VALIDITY_CONTEXT_INVALID');if(ownership.value.unresolvedSubjectIds.length)aReasons.push('UNRESOLVED_OWNER_ROUTE');if(routingMismatch)aReasons.push('OWNERSHIP_ROUTE_MISMATCH');const a=receipt('AAG26',authorityConflict?'BLOCKED':'PASS',aReasons,policy,options);if(!a.ok)return a;

 const candidateExpected=sortedUnique(frontier.value.transitivelyImpactedSubjectIds),candidateActual=sortedUnique(candidates.value.candidates.map(c=>c.subjectId)),materialCoherent=JSON.stringify(candidateExpected)===JSON.stringify(candidateActual);let materialState:GateState=input.materializationState==='TRUNCATED'?'TRUNCATED':input.materializationState==='INDETERMINATE'?'INDETERMINATE':'PASS';if(!materialCoherent&&materialState==='PASS')materialState='INDETERMINATE';const m=receipt('BMG26',materialState,materialState==='PASS'?[]:[materialState==='TRUNCATED'?'REVIEW_TRUNCATED':'REVIEW_MATERIALIZATION_INDETERMINATE'],policy,options);if(!m.ok)return m;
 const vState=overallState([b.value.state,s.value.state,p.value.state,f.value.state,z.value.state,a.value.state,m.value.state]),v=receipt('VAG26',vState,vState==='PASS'?[]:[`PRECONDITION_${vState}`],policy,options);if(!v.ok)return v;
 const bindings:Bindings={artifactBound:true,sourceManifestDigest:manifest.value.manifestDigest,reviewPolicyDigest:policy,validityContextGateDigest:validity.value.gateDigest,proofBindingGateDigest:proof.value.gateDigest,dependencyProjectionDigest:dependency.value.projectionDigest,findingRegisterDigest:findingRegister.value.registerDigest,inventoryDigest:inventory.value.inventoryDigest,matrixDigest:matrix.value.matrixDigest,frontierDigest:frontier.value.frontierDigest,candidateIndexDigest:candidates.value.indexDigest,ownershipFilterDigest:ownership.value.filterDigest,predecessorVerdictDigest:prior?.verdictDigest??null};
 const gates=finalize({baselineContinuity:b.value,sourceCompleteness:s.value,proofInvalidation:p.value,findingClosure:f.value,zeroHighCritical:z.value,authorityAmbiguity:a.value,budgetMaterialization:m.value,verdictAdmission:v.value},bindings,options);if(!gates.ok)return gates;
 return ok(deepFreeze({manifest:manifest.value,sourceBinding:sourceBinding.value,validity:validity.value,lineage:lineage.value,authority:authority.value,dependency:dependency.value,proof:proof.value,inventory:inventory.value,matrix:matrix.value,frontier:frontier.value,ownership:ownership.value,candidates:candidates.value,findingRegister:findingRegister.value,gates:gates.value}));
}
export function evaluateArtifactReviewGates(input:ArtifactGateEvaluationInput,options:OperationOptions):Result<ReviewGateSet>{const r=evaluateArtifactReview(input,options);return r.ok?ok(r.value.gates):r;}
