import type{ArtifactGateEvaluationInput,GateEvaluationInput,GateReceipt,GateState,OperationOptions,Result,ReviewGateSet,SemanticFinding}from'./types.js';
import{deepFreeze,digestValue,fail,ok,sortedUnique}from'./utils.js';

function receipt(gateId:string,state:GateState,reasons:readonly string[],reviewPolicyDigest:string|null,options:OperationOptions):Result<GateReceipt>{const body={gateId,state,reviewPolicyDigest,reasonCodes:sortedUnique(reasons)};const d=digestValue(options,gateId,body);return d.ok?ok(deepFreeze({...body,receiptDigest:d.value})):d;}
function blockingFindings(findings:readonly SemanticFinding[]){return findings.filter(f=>(f.severity==='CRITICAL'||f.severity==='HIGH')&&(f.state==='OPEN'||f.state==='INDETERMINATE'));}
function overallState(states:readonly GateState[]):GateState{if(states.includes('TRUNCATED'))return'TRUNCATED';if(states.includes('BLOCKED'))return'BLOCKED';if(states.includes('INDETERMINATE'))return'INDETERMINATE';if(states.includes('FAIL'))return'FAIL';return'PASS';}
function finalize(receipts:Omit<ReviewGateSet,'artifactBound'|'sourceManifestDigest'|'reviewPolicyDigest'|'validityContextGateDigest'|'proofBindingGateDigest'|'findingRegisterDigest'|'matrixDigest'|'candidateIndexDigest'|'ownershipFilterDigest'|'gateSetDigest'>,bindings:{artifactBound:boolean;sourceManifestDigest:string|null;reviewPolicyDigest:string|null;validityContextGateDigest:string|null;proofBindingGateDigest:string|null;findingRegisterDigest:string|null;matrixDigest:string|null;candidateIndexDigest:string|null;ownershipFilterDigest:string|null},options:OperationOptions):Result<ReviewGateSet>{const body={...receipts,...bindings};const d=digestValue(options,'M26_GATE_SET',body);return d.ok?ok(deepFreeze({...body,gateSetDigest:d.value})):d;}

/** Legacy diagnostic gate evaluator. It can inspect gate precedence but is deliberately not admissible to HVC26. */
export function evaluateReviewGates(input:GateEvaluationInput,options:OperationOptions):Result<ReviewGateSet>{
 const b=receipt('BCG26',input.baselineContinuity?'PASS':'BLOCKED',input.baselineContinuity?[]:['BASELINE_CONTINUITY_INVALID'],null,options);if(!b.ok)return b;const s=receipt('SCG26',input.sourceCoverageSufficient?'PASS':'INDETERMINATE',input.sourceCoverageSufficient?[]:['SOURCE_COVERAGE_INSUFFICIENT'],null,options);if(!s.ok)return s;const p=receipt('PIG26',input.allInvalidatedProofItemsReviewed?'PASS':'FAIL',input.allInvalidatedProofItemsReviewed?[]:['INVALIDATED_PROOF_ITEM_UNREVIEWED'],null,options);if(!p.ok)return p;const f=receipt('FCG26',input.findingClosureValid?'PASS':'FAIL',input.findingClosureValid?[]:['FINDING_CLOSURE_INVALID'],null,options);if(!f.ok)return f;const high=blockingFindings(input.findings);const z=receipt('ZHG26',high.length===0?'PASS':'FAIL',high.map(x=>`${x.severity}:${x.findingId}`),null,options);if(!z.ok)return z;const a=receipt('AAG26',input.authorityConflict?'BLOCKED':'PASS',input.authorityConflict?['AUTHORITY_OR_AMBIGUITY_CONFLICT']:[],null,options);if(!a.ok)return a;const budgetState:GateState=input.truncated?'TRUNCATED':input.indeterminate?'INDETERMINATE':'PASS';const m=receipt('BMG26',budgetState,budgetState==='TRUNCATED'?['REVIEW_TRUNCATED']:budgetState==='INDETERMINATE'?['MANDATORY_REVIEW_TRUTH_INDETERMINATE']:[],null,options);if(!m.ok)return m;const vState=overallState([b.value.state,s.value.state,p.value.state,f.value.state,z.value.state,a.value.state,m.value.state]);const v=receipt('VAG26',vState,vState==='PASS'?[]:[`PRECONDITION_${vState}`],null,options);if(!v.ok)return v;return finalize({baselineContinuity:b.value,sourceCompleteness:s.value,proofInvalidation:p.value,findingClosure:f.value,zeroHighCritical:z.value,authorityAmbiguity:a.value,budgetMaterialization:m.value,verdictAdmission:v.value},{artifactBound:false,sourceManifestDigest:null,reviewPolicyDigest:null,validityContextGateDigest:null,proofBindingGateDigest:null,findingRegisterDigest:null,matrixDigest:null,candidateIndexDigest:null,ownershipFilterDigest:null},options);
}

export function evaluateArtifactReviewGates(input:ArtifactGateEvaluationInput,options:OperationOptions):Result<ReviewGateSet>{
 const policy=input.intent.reviewPolicyDigest;if(!/^sha256:[0-9a-f]{64}$/.test(policy))return fail('VAG26_POLICY_INVALID','Review policy digest is invalid.');
 const baselineOk=input.lineageWitness.comparisonAdmissible&&input.validityContext.valid&&input.validityContext.intentDigest===input.intent.intentDigest;const b=receipt('BCG26',baselineOk?'PASS':'BLOCKED',baselineOk?[]:['BASELINE_CONTINUITY_INVALID'],policy,options);if(!b.ok)return b;
 const sourceOk=input.sourceManifest.baselineCoverage==='COMPLETE'&&input.sourceManifest.candidateCoverage==='COMPLETE'&&input.sourceManifest.dependencyKnowledgeComplete&&input.sourceBinding.valid&&input.validityContext.valid;const sourceReasons:string[]=[];if(input.sourceManifest.baselineCoverage!=='COMPLETE'||input.sourceManifest.candidateCoverage!=='COMPLETE')sourceReasons.push('SOURCE_COVERAGE_INSUFFICIENT');if(!input.sourceManifest.dependencyKnowledgeComplete)sourceReasons.push('DEPENDENCY_KNOWLEDGE_INCOMPLETE');if(!input.sourceBinding.valid)sourceReasons.push('CURRENT_SOURCE_BINDING_INVALID');if(!input.validityContext.valid)sourceReasons.push('VALIDITY_CONTEXT_INVALID');const s=receipt('SCG26',sourceOk?'PASS':'INDETERMINATE',sourceReasons,policy,options);if(!s.ok)return s;
 const candidateSubjects=new Set(input.candidateIndex.candidates.map(c=>c.subjectId));const invalidated=input.matrix.rows.filter(r=>r.proofInvalidated).map(r=>r.subjectId);const proofOk=input.proofBinding.valid&&invalidated.every(id=>candidateSubjects.has(id));const p=receipt('PIG26',proofOk?'PASS':'FAIL',proofOk?[]:['INVALIDATED_PROOF_ITEM_UNREVIEWED_OR_PROOF_BINDING_INVALID'],policy,options);if(!p.ok)return p;
 const currentDigests=sortedUnique(input.findings.map(f=>f.findingDigest));const registerDigests=sortedUnique(input.findingRegister.currentFindingDigests);const findingClosureValid=JSON.stringify(currentDigests)===JSON.stringify(registerDigests);const f=receipt('FCG26',findingClosureValid?'PASS':'FAIL',findingClosureValid?[]:['FINDING_REGISTER_MISMATCH'],policy,options);if(!f.ok)return f;
 const high=blockingFindings(input.findings);const z=receipt('ZHG26',high.length===0?'PASS':'FAIL',high.map(x=>`${x.severity}:${x.findingId}`),policy,options);if(!z.ok)return z;
 const authorityConflict=!input.authorityGate.valid||input.mixWitness.mixed||input.ownershipFilter.unresolvedSubjectIds.length>0;const aReasons:string[]=[];if(!input.authorityGate.valid)aReasons.push('SOURCE_AUTHORITY_CONFLICT');if(input.mixWitness.mixed)aReasons.push('MIX_AND_MATCH_CONFLICT');if(input.ownershipFilter.unresolvedSubjectIds.length>0)aReasons.push('UNRESOLVED_OWNER_ROUTE');const a=receipt('AAG26',authorityConflict?'BLOCKED':'PASS',aReasons,policy,options);if(!a.ok)return a;
 const materialState:GateState=input.materializationState==='TRUNCATED'?'TRUNCATED':input.materializationState==='INDETERMINATE'?'INDETERMINATE':'PASS';const m=receipt('BMG26',materialState,materialState==='PASS'?[]:[materialState==='TRUNCATED'?'REVIEW_TRUNCATED':'MANDATORY_REVIEW_TRUTH_INDETERMINATE'],policy,options);if(!m.ok)return m;
 const vState=overallState([b.value.state,s.value.state,p.value.state,f.value.state,z.value.state,a.value.state,m.value.state]);const v=receipt('VAG26',vState,vState==='PASS'?[]:[`PRECONDITION_${vState}`],policy,options);if(!v.ok)return v;
 return finalize({baselineContinuity:b.value,sourceCompleteness:s.value,proofInvalidation:p.value,findingClosure:f.value,zeroHighCritical:z.value,authorityAmbiguity:a.value,budgetMaterialization:m.value,verdictAdmission:v.value},{artifactBound:true,sourceManifestDigest:input.sourceManifest.manifestDigest,reviewPolicyDigest:policy,validityContextGateDigest:input.validityContext.gateDigest,proofBindingGateDigest:input.proofBinding.gateDigest,findingRegisterDigest:input.findingRegister.registerDigest,matrixDigest:input.matrix.matrixDigest,candidateIndexDigest:input.candidateIndex.indexDigest,ownershipFilterDigest:input.ownershipFilter.filterDigest},options);
}
