import type{DownstreamHedsHandoff,HedsFindingRegister,HedsIntegrityReceipt,HedsReplayGuard,HedsSplitBrainWitness,HedsTransitionReceipt,HedsVerdict,HedsVerdictCapsule,OperationOptions,ReplayState,Result,ReviewGateSet,SemanticFinding}from'./types.js';
import{allSha,compareCodePoint,deepFreeze,digestValue,fail,ok,sortedUnique,validId}from'./utils.js';

function verdictFromGates(gates:ReviewGateSet):HedsVerdict{switch(gates.verdictAdmission.state){case'PASS':return'APPROVED';case'FAIL':return'CORRECTION_REQUIRED';case'BLOCKED':return'BLOCKED';case'INDETERMINATE':return'INDETERMINATE';case'TRUNCATED':return'TRUNCATED';}}
function semanticBody(verdictId:string,projectId:string,lineageId:string,baselineIdentityDigest:string,candidateIdentityDigest:string,reviewPolicyDigest:string,inventoryDigest:string,frontierDigest:string,gates:ReviewGateSet,findings:readonly SemanticFinding[]){return{verdictId,projectId,lineageId,baselineIdentityDigest,candidateIdentityDigest,reviewPolicyDigest,inventoryDigest,frontierDigest,gateSetDigest:gates.gateSetDigest,findingDigests:sortedUnique(findings.map(f=>f.findingDigest)),verdict:verdictFromGates(gates)};}

export function createHedsVerdictCapsule(verdictId:string,projectId:string,lineageId:string,baselineIdentityDigest:string,candidateIdentityDigest:string,reviewPolicyDigest:string,inventoryDigest:string,frontierDigest:string,gates:ReviewGateSet,findings:readonly SemanticFinding[],options:OperationOptions):Result<HedsVerdictCapsule>{
 if(![verdictId,projectId,lineageId].every(validId)||!allSha([baselineIdentityDigest,candidateIdentityDigest,reviewPolicyDigest,inventoryDigest,frontierDigest,gates.gateSetDigest,...findings.map(f=>f.findingDigest)]))return fail('HVC26_INPUT_INVALID','HEDS verdict bindings are invalid.',verdictId);
 const body=semanticBody(verdictId,projectId,lineageId,baselineIdentityDigest,candidateIdentityDigest,reviewPolicyDigest,inventoryDigest,frontierDigest,gates,findings);const s=digestValue(options,'HSD26',body);if(!s.ok)return s;const d=digestValue(options,'HVC26',{...body,semanticDigest:s.value});return d.ok?ok(deepFreeze({...body,semanticDigest:s.value,verdictDigest:d.value})):d;
}

export function verifyHedsVerdictCapsule(capsule:HedsVerdictCapsule,gates:ReviewGateSet,findings:readonly SemanticFinding[],options:OperationOptions):Result<HedsIntegrityReceipt>{
 const body=semanticBody(capsule.verdictId,capsule.projectId,capsule.lineageId,capsule.baselineIdentityDigest,capsule.candidateIdentityDigest,capsule.reviewPolicyDigest,capsule.inventoryDigest,capsule.frontierDigest,gates,findings);const s=digestValue(options,'HSD26',body);if(!s.ok)return s;const d=digestValue(options,'HVC26',{...body,semanticDigest:s.value});if(!d.ok)return d;const expectedVerdict=verdictFromGates(gates);const valid=s.value===capsule.semanticDigest&&d.value===capsule.verdictDigest&&expectedVerdict===capsule.verdict&&capsule.gateSetDigest===gates.gateSetDigest&&JSON.stringify(sortedUnique(findings.map(f=>f.findingDigest)))===JSON.stringify(capsule.findingDigests);const rb={verdictDigest:capsule.verdictDigest,recomputedSemanticDigest:s.value,expectedVerdict,valid};const r=digestValue(options,'HIR26',rb);return r.ok?ok(deepFreeze({...rb,receiptDigest:r.value})):r;
}

export function createHedsFindingRegister(current:readonly SemanticFinding[],retainedFindingDigests:readonly string[],options:OperationOptions):Result<HedsFindingRegister>{
 if(!allSha(retainedFindingDigests))return fail('HFR26_RETAINED_INVALID','Retained finding digest is invalid.');const ids=new Map<string,string>();for(const f of current){const prior=ids.get(f.findingId);if(prior&&prior!==f.findingDigest)return fail('HFR26_FINDING_CONFLICT','Same finding ID has divergent semantics.',f.findingId);ids.set(f.findingId,f.findingDigest);}
 const body={currentFindingDigests:sortedUnique(current.map(f=>f.findingDigest)),retainedFindingDigests:sortedUnique(retainedFindingDigests)};const d=digestValue(options,'HFR26',body);return d.ok?ok(deepFreeze({...body,registerDigest:d.value})):d;
}

export function createHedsTransitionReceipt(predecessor:HedsVerdictCapsule|null,successor:HedsVerdictCapsule,changedFindings:readonly SemanticFinding[],changedSubjectIds:readonly string[],reasonCodes:readonly string[],options:OperationOptions):Result<HedsTransitionReceipt>{
 if(changedSubjectIds.some(x=>!validId(x))||reasonCodes.some(x=>!validId(x)))return fail('HTR26_ID_INVALID','Transition subject/reason identifier is invalid.');if(predecessor&&predecessor.projectId!==successor.projectId)return fail('HTR26_PROJECT_MISMATCH','Verdict transition crosses projects.');if(predecessor&&predecessor.lineageId!==successor.lineageId)return fail('HTR26_LINEAGE_MISMATCH','Verdict transition crosses lineages.');
 const body={predecessorVerdictDigest:predecessor?.verdictDigest??null,successorVerdictDigest:successor.verdictDigest,changedFindingDigests:sortedUnique(changedFindings.map(f=>f.findingDigest)),changedSubjectIds:sortedUnique(changedSubjectIds),reasonCodes:sortedUnique(reasonCodes)};const d=digestValue(options,'HTR26',body);return d.ok?ok(deepFreeze({...body,receiptDigest:d.value})):d;
}

export function createHedsReplayGuard(history:readonly HedsVerdictCapsule[],options:OperationOptions):Result<HedsReplayGuard>{
 const limit=Math.max(1,Math.min(options.maxHistory??4096,65536));const totalCount=history.length;const processed=history.slice(0,limit);const byDigest=new Set<string>(),byId=new Map<string,string>(),accepted:string[]=[],duplicates:string[]=[],conflicts=new Set<string>();
 for(const v of processed){if(byDigest.has(v.verdictDigest)){duplicates.push(v.verdictDigest);continue;}byDigest.add(v.verdictDigest);accepted.push(v.verdictDigest);const prior=byId.get(v.verdictId);if(prior&&prior!==v.semanticDigest)conflicts.add(v.verdictId);else byId.set(v.verdictId,v.semanticDigest);}
 const historyTruncated=totalCount>processed.length;let state:ReplayState=conflicts.size>0?'CONFLICT':historyTruncated?'TRUNCATED':'CLEAR';const body={state,acceptedVerdictDigests:sortedUnique(accepted),duplicateVerdictDigests:sortedUnique(duplicates),conflictingVerdictIds:sortedUnique([...conflicts]),historyTruncated,processedCount:processed.length,totalCount};const d=digestValue(options,'HRG26',body);return d.ok?ok(deepFreeze({...body,guardDigest:d.value})):d;
}

export function createHedsSplitBrainWitness(predecessorVerdictDigest:string,successors:readonly HedsVerdictCapsule[],options:OperationOptions):Result<HedsSplitBrainWitness>{
 if(!allSha([predecessorVerdictDigest]))return fail('HSW26_PREDECESSOR_INVALID','Predecessor verdict digest is invalid.');const successorSemanticDigests=sortedUnique(successors.map(v=>v.semanticDigest));const splitBrain=successorSemanticDigests.length>1;const body={predecessorVerdictDigest,successorSemanticDigests,splitBrain};const d=digestValue(options,'HSW26',body);return d.ok?ok(deepFreeze({...body,witnessDigest:d.value})):d;
}

export function createDownstreamHedsHandoff(capsule:HedsVerdictCapsule,gates:ReviewGateSet,findings:readonly SemanticFinding[],impactedSubjectIds:readonly string[],consumer:DownstreamHedsHandoff['consumer'],options:OperationOptions):Result<DownstreamHedsHandoff>{
 if(impactedSubjectIds.some(x=>!validId(x)))return fail('DHH26_SUBJECT_INVALID','Impacted subject identifier is invalid.');const verified=verifyHedsVerdictCapsule(capsule,gates,findings,options);if(!verified.ok)return verified;if(!verified.value.valid)return fail('DHH26_VERDICT_INVALID','Downstream handoff requires verified HEDS verdict.');
 const blocking=findings.filter(f=>(f.severity==='CRITICAL'||f.severity==='HIGH')&&(f.state==='OPEN'||f.state==='INDETERMINATE')).map(f=>f.findingDigest);const body={owner:'M26_HEDS' as const,consumer,verdictDigest:capsule.verdictDigest,semanticDigest:capsule.semanticDigest,verdict:capsule.verdict,impactedSubjectIds:sortedUnique(impactedSubjectIds),blockingFindingDigests:sortedUnique(blocking),reviewPolicyDigest:capsule.reviewPolicyDigest,mayDecideAssurance:false as const,maySelectTests:false as const,mayOperateGit:false as const,mayPromoteCheckpoint:false as const};const d=digestValue(options,'DHH26',body);return d.ok?ok(deepFreeze({...body,handoffDigest:d.value})):d;
}
