import type{AuthorityRoot,AuthorityRootInput,AuthorityRootSet,EvidenceAuthorityBoundary,EvidenceBindingLedger,EvidenceClaimMapping,EvidenceClaimMappingEntry,EvidenceIntentCapsule,EvidenceIntentInput,EvidenceKind,EvidencePrivacyMembrane as Never,EvidenceReference,MachineEvidenceItem,MachineEvidenceItemInput,MachineEvidenceManifest,OperationOptions,PrivacyDecision,ProducerAuthorityDecision,ProducerAuthorityEntry,ProducerAuthorityEntryInput,Result,SourceAuthorityIndex,SubjectStateBinding,SubjectStateBindingInput}from'./types.js';
import{EVIDENCE_KINDS,Guard,compareCodePoint,deepFreeze,digestValue,everySha,fail,isEvidenceKind,isSha256,ok,scopeAllows,sortedUnique,stableStringify,validId,validPortableRef}from'./utils.js';

type _Never=Never;
const ROOT_CLASSES=new Set(['CHECKPOINT','DECISION','POLICY','CONTRACT','MODULE_GOVERNANCE','EXTERNAL_CANONICAL']);
const ROOT_OWNERS=new Set(['M11_DECISION','M16_POLICY','M17_CHECKPOINT','MODULE_GOVERNANCE','EXTERNAL_CANONICAL']);
const claimPrefixValid=(v:string)=>v==='*'||/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,191}$/.test(v);
const externalIdentityValid=(v:SubjectStateBindingInput['headRevision'])=>v===null||(typeof v.value==='string'&&v.value.length>0&&v.value.length<=256&&typeof v.domain==='string'&&typeof v.algorithm!=='undefined'&&(v.algorithm===null||v.algorithm.length>0));
const prefixWithin=(root:string,child:string)=>root==='*'||child===root||child.startsWith(`${root}:`)||child.startsWith(`${root}/`);

export function createEvidenceIntentCapsule(input:EvidenceIntentInput,options:OperationOptions):Result<EvidenceIntentCapsule>{
 if(!validId(input.intentId)||!validId(input.projectId)||!validId(input.lineageId)||!validId(input.subjectKind)||!validId(input.subjectId))return fail('EIC24_ID_INVALID','Evidence intent identifiers are invalid.');
 if(input.claimIds.length===0||input.claimIds.some(x=>!validId(x))||input.requestedKinds.length===0||input.requestedKinds.some(x=>!isEvidenceKind(x)))return fail('EIC24_SCOPE_INVALID','Evidence intent requires valid claims and evidence kinds.');
 const body={intentId:input.intentId,projectId:input.projectId,lineageId:input.lineageId,subjectKind:input.subjectKind,subjectId:input.subjectId,claimIds:sortedUnique(input.claimIds),requestedKinds:[...new Set(input.requestedKinds)].sort(compareCodePoint)};
 const d=digestValue(options,'EIC24',body);if(!d.ok)return d;return ok(deepFreeze({...body,intentDigest:d.value}));
}
export function verifyEvidenceIntentCapsule(value:EvidenceIntentCapsule,options:OperationOptions):Result<boolean>{const rebuilt=createEvidenceIntentCapsule(value,options);return rebuilt.ok?ok(rebuilt.value.intentDigest===value.intentDigest):rebuilt;}

export function createEvidenceAuthorityBoundary(intent:EvidenceIntentCapsule,options:OperationOptions):Result<EvidenceAuthorityBoundary>{const v=verifyEvidenceIntentCapsule(intent,options);if(!v.ok||!v.value)return v.ok?fail('EAB24_INTENT_INVALID','Authority boundary requires verified intent.'):v;const body={intentDigest:intent.intentDigest,authority:'EVIDENCE_VALIDATION_AND_ACCEPTANCE_ONLY' as const,mayCreateProducerTruth:false as const,mayEvaluateDod:false as const,mayCalculateProgress:false as const,mayComputeProjectStatus:false as const,mayComputeProof:false as const,mayDecideAssurance:false as const,mayPromoteCheckpoint:false as const};const d=digestValue(options,'EAB24',body);if(!d.ok)return d;return ok(deepFreeze({...body,boundaryDigest:d.value}));}

export function createAuthorityRoot(input:AuthorityRootInput,options:OperationOptions):Result<AuthorityRoot>{
 if(!validId(input.rootId)||!validId(input.projectId)||input.lineageId!==null&&!validId(input.lineageId)||!ROOT_CLASSES.has(input.rootClass)||!ROOT_OWNERS.has(input.owner)||!isSha256(input.semanticIdentity)||!isSha256(input.validityBindingDigest)||!validPortableRef(input.sourceRef))return fail('SAI24_ROOT_INVALID','Authority root identity/binding is invalid.',input.rootId);
 if(input.allowedProducerIds.length===0||input.allowedProducerIds.some(x=>x!=='*'&&!validId(x))||input.allowedEvidenceKinds.length===0||input.allowedEvidenceKinds.some(x=>!isEvidenceKind(x))||input.allowedClaimPrefixes.length===0||input.allowedClaimPrefixes.some(x=>!claimPrefixValid(x)))return fail('SAI24_ROOT_SCOPE_INVALID','Authority root must have explicit valid producer/kind/claim scope.',input.rootId);
 const body={rootId:input.rootId,rootClass:input.rootClass,owner:input.owner,projectId:input.projectId,lineageId:input.lineageId,semanticIdentity:input.semanticIdentity,validityBindingDigest:input.validityBindingDigest,sourceRef:input.sourceRef,allowedProducerIds:sortedUnique(input.allowedProducerIds),allowedEvidenceKinds:[...new Set(input.allowedEvidenceKinds)].sort(compareCodePoint),allowedClaimPrefixes:sortedUnique(input.allowedClaimPrefixes)};const d=digestValue(options,'SAI24_ROOT',body);if(!d.ok)return d;return ok(deepFreeze({...body,rootDigest:d.value}));
}
export function verifyAuthorityRoot(value:AuthorityRoot,options:OperationOptions):Result<boolean>{const rebuilt=createAuthorityRoot(value,options);return rebuilt.ok?ok(rebuilt.value.rootDigest===value.rootDigest):rebuilt;}

export function createAuthorityRootSet(projectId:string,lineageId:string,inputs:readonly AuthorityRoot[],options:OperationOptions):Result<AuthorityRootSet>{
 const guard=new Guard(options);if(!validId(projectId)||!validId(lineageId)||inputs.length===0)return fail('SAI24_ROOT_SET_INVALID','Authority root set requires project, lineage and at least one root.');
 const byId=new Map<string,AuthorityRoot[]>();for(const r of inputs){const step=guard.step(r.rootId);if(!step.ok)return step;const v=verifyAuthorityRoot(r,options);if(!v.ok||!v.value)return v.ok?fail('SAI24_ROOT_TAMPERED','Authority root failed verification.',r.rootId):v;if(r.projectId!==projectId||r.lineageId!==null&&r.lineageId!==lineageId)return fail('SAI24_ROOT_LINEAGE_MISMATCH','Authority root crosses project/lineage.',r.rootId);const list=byId.get(r.rootId)??[];list.push(r);byId.set(r.rootId,list);}
 const duplicates:string[]=[];const conflicts:string[]=[];const roots:AuthorityRoot[]=[];for(const[id,list]of[...byId.entries()].sort(([a],[b])=>compareCodePoint(a,b))){const unique=new Map(list.map(r=>[r.rootDigest,r]));if(unique.size===1){const only=[...unique.values()][0];if(only)roots.push(only);if(list.length>1)duplicates.push(only?.rootDigest??'');}else{conflicts.push(id);for(const r of unique.values())roots.push(r);}}
 roots.sort((a,b)=>compareCodePoint(a.rootDigest,b.rootDigest));const body={projectId,lineageId,roots,duplicateRootDigests:sortedUnique(duplicates.filter(Boolean)),conflictingRootIds:sortedUnique(conflicts)};const d=digestValue(options,'SAI24_ROOT_SET',body);if(!d.ok)return d;return ok(deepFreeze({...body,rootSetDigest:d.value}));
}
export function verifyAuthorityRootSet(value:AuthorityRootSet,options:OperationOptions):Result<boolean>{const rebuilt=createAuthorityRootSet(value.projectId,value.lineageId,value.roots,options);if(!rebuilt.ok)return rebuilt;return ok(rebuilt.value.rootSetDigest===value.rootSetDigest&&stableStringify(rebuilt.value.conflictingRootIds)===stableStringify(value.conflictingRootIds));}

export function createProducerAuthorityEntry(input:ProducerAuthorityEntryInput,rootSet:AuthorityRootSet,options:OperationOptions):Result<ProducerAuthorityEntry>{
 if(!validId(input.authorityId)||!validId(input.producerId)||!validId(input.rootId)||!isSha256(input.sourceIdentityDigest)||input.evidenceKinds.length===0||input.evidenceKinds.some(x=>!isEvidenceKind(x))||input.claimPrefixes.length===0||input.claimPrefixes.some(x=>!claimPrefixValid(x)))return fail('SAI24_ENTRY_INVALID','Producer authority entry is invalid.',input.authorityId);
 if(rootSet.conflictingRootIds.includes(input.rootId))return fail('SAI24_ROOT_CONFLICT','Conflicting authority root cannot authorize producer.',input.rootId);
 const root=rootSet.roots.find(r=>r.rootId===input.rootId);if(!root)return fail('SAI24_ROOT_MISSING','Producer entry references unknown root.',input.rootId);
 if(!root.allowedProducerIds.includes('*')&&!root.allowedProducerIds.includes(input.producerId))return fail('SAI24_PRODUCER_SCOPE_ESCALATION','Producer exceeds root scope.',input.producerId);
 if(input.evidenceKinds.some(k=>!root.allowedEvidenceKinds.includes(k)))return fail('SAI24_KIND_SCOPE_ESCALATION','Evidence kind exceeds root scope.',input.authorityId);
 if(input.claimPrefixes.some(p=>!root.allowedClaimPrefixes.some(r=>prefixWithin(r,p))))return fail('SAI24_CLAIM_SCOPE_ESCALATION','Claim scope exceeds root scope.',input.authorityId);
 const body={authorityId:input.authorityId,producerId:input.producerId,rootId:input.rootId,evidenceKinds:[...new Set(input.evidenceKinds)].sort(compareCodePoint),claimPrefixes:sortedUnique(input.claimPrefixes),sourceIdentityDigest:input.sourceIdentityDigest,rootDigest:root.rootDigest};const d=digestValue(options,'SAI24_ENTRY',body);if(!d.ok)return d;return ok(deepFreeze({...body,authorityDigest:d.value}));
}
export function verifyProducerAuthorityEntry(value:ProducerAuthorityEntry,rootSet:AuthorityRootSet,options:OperationOptions):Result<boolean>{const rebuilt=createProducerAuthorityEntry(value,rootSet,options);return rebuilt.ok?ok(rebuilt.value.authorityDigest===value.authorityDigest):rebuilt;}

export function createSourceAuthorityIndex(rootSet:AuthorityRootSet,entries:readonly ProducerAuthorityEntry[],options:OperationOptions):Result<SourceAuthorityIndex>{
 const roots=verifyAuthorityRootSet(rootSet,options);if(!roots.ok||!roots.value)return roots.ok?fail('SAI24_ROOT_SET_TAMPERED','Authority index requires verified root set.'):roots;const guard=new Guard(options);const byId=new Map<string,ProducerAuthorityEntry[]>();for(const e of entries){const step=guard.step(e.authorityId);if(!step.ok)return step;const v=verifyProducerAuthorityEntry(e,rootSet,options);if(!v.ok||!v.value)return v.ok?fail('SAI24_ENTRY_TAMPERED','Authority entry failed verification.',e.authorityId):v;const list=byId.get(e.authorityId)??[];list.push(e);byId.set(e.authorityId,list);}
 const duplicates:string[]=[];const conflicts:string[]=[];const kept:ProducerAuthorityEntry[]=[];for(const[id,list]of[...byId.entries()].sort(([a],[b])=>compareCodePoint(a,b))){const unique=new Map(list.map(e=>[e.authorityDigest,e]));if(unique.size===1){const only=[...unique.values()][0];if(only)kept.push(only);if(list.length>1)duplicates.push(only?.authorityDigest??'');}else{conflicts.push(id);for(const e of unique.values())kept.push(e);}}
 kept.sort((a,b)=>compareCodePoint(a.authorityDigest,b.authorityDigest));const body={projectId:rootSet.projectId,lineageId:rootSet.lineageId,rootSetDigest:rootSet.rootSetDigest,entries:kept,duplicateAuthorityDigests:sortedUnique(duplicates.filter(Boolean)),conflictingAuthorityIds:sortedUnique(conflicts)};const d=digestValue(options,'SAI24',body);if(!d.ok)return d;return ok(deepFreeze({...body,indexDigest:d.value}));
}
export function verifySourceAuthorityIndex(value:SourceAuthorityIndex,rootSet:AuthorityRootSet,options:OperationOptions):Result<boolean>{if(value.rootSetDigest!==rootSet.rootSetDigest||value.projectId!==rootSet.projectId||value.lineageId!==rootSet.lineageId)return ok(false);const rebuilt=createSourceAuthorityIndex(rootSet,value.entries,options);return rebuilt.ok?ok(rebuilt.value.indexDigest===value.indexDigest&&stableStringify(rebuilt.value.conflictingAuthorityIds)===stableStringify(value.conflictingAuthorityIds)):rebuilt;}

export function authorizeProducer(index:SourceAuthorityIndex,rootSet:AuthorityRootSet,producerId:string,kind:EvidenceKind,claimIds:readonly string[],options:OperationOptions):Result<ProducerAuthorityDecision>{
 const iv=verifySourceAuthorityIndex(index,rootSet,options);if(!iv.ok||!iv.value)return iv.ok?fail('SAI24_INDEX_TAMPERED','Producer authorization requires verified index.'):iv;if(!validId(producerId)||!isEvidenceKind(kind)||claimIds.length===0||claimIds.some(x=>!validId(x)))return fail('SAI24_AUTH_QUERY_INVALID','Producer authorization query is invalid.');
 const candidates=index.entries.filter(e=>e.producerId===producerId&&e.evidenceKinds.includes(kind)&&claimIds.every(c=>e.claimPrefixes.some(p=>scopeAllows([p],c))));const conflicting=candidates.some(e=>index.conflictingAuthorityIds.includes(e.authorityId))||candidates.some(e=>rootSet.conflictingRootIds.includes(e.rootId));const matched=candidates.map(e=>e.authorityDigest).sort(compareCodePoint);const authorized=matched.length>0&&!conflicting;const reasons=authorized?['PRODUCER_AUTHORIZED']:conflicting?['AUTHORITY_CONFLICT']:['PRODUCER_OR_SCOPE_NOT_AUTHORIZED'];const body={producerId,evidenceKind:kind,claimIds:sortedUnique(claimIds),authorized,conflict:conflicting,matchedAuthorityDigests:matched,reasonCodes:reasons};const d=digestValue(options,'SAI24_DECISION',body);if(!d.ok)return d;return ok(deepFreeze({...body,decisionDigest:d.value}));
}

export function createSubjectStateBinding(input:SubjectStateBindingInput,options:OperationOptions):Result<SubjectStateBinding>{
 if(!validId(input.projectId)||!validId(input.lineageId)||!validId(input.subjectKind)||!validId(input.subjectId)||input.moduleId!==null&&!validId(input.moduleId)||input.workOrderId!==null&&!validId(input.workOrderId))return fail('SSB24_ID_INVALID','Subject binding identifiers are invalid.');
 if(!everySha([input.checkpointDigest,input.policyDigest,...input.dependencyDigests])||[input.baseRevision,input.headRevision,input.treeRevision,input.runtimeIdentity,input.platformIdentity].some(v=>!externalIdentityValid(v)))return fail('SSB24_BINDING_INVALID','Subject binding contains invalid exact-state identity.');
 const body={projectId:input.projectId,lineageId:input.lineageId,subjectKind:input.subjectKind,subjectId:input.subjectId,moduleId:input.moduleId,workOrderId:input.workOrderId,checkpointDigest:input.checkpointDigest,baseRevision:input.baseRevision,headRevision:input.headRevision,treeRevision:input.treeRevision,runtimeIdentity:input.runtimeIdentity,platformIdentity:input.platformIdentity,policyDigest:input.policyDigest,dependencyDigests:sortedUnique(input.dependencyDigests)};const d=digestValue(options,'SSB24',body);if(!d.ok)return d;return ok(deepFreeze({...body,bindingDigest:d.value}));
}
export function verifySubjectStateBinding(value:SubjectStateBinding,options:OperationOptions):Result<boolean>{const rebuilt=createSubjectStateBinding(value,options);return rebuilt.ok?ok(rebuilt.value.bindingDigest===value.bindingDigest):rebuilt;}

export function applyEvidencePrivacyMembrane(refs:readonly EvidenceReference[],options:OperationOptions):Result<PrivacyDecision>{const rejected:string[]=[];const reasons:string[]=[];for(const r of refs){if(!validPortableRef(r.refId)||!['OPAQUE','PUBLIC_URI_ID','ARTIFACT_ID'].includes(r.kind)||!isSha256(r.contentDigest)){rejected.push(r.refId);reasons.push('NON_PORTABLE_OR_INVALID_REFERENCE');}}const body={safe:rejected.length===0,rejectedRefIds:sortedUnique(rejected),reasonCodes:sortedUnique(reasons)};const d=digestValue(options,'EPM24',body);if(!d.ok)return d;return ok(deepFreeze({...body,decisionDigest:d.value}));}

function itemBody(input:MachineEvidenceItemInput){return{evidenceId:input.evidenceId,kind:input.kind,producerId:input.producerId,subject:input.subject,observation:input.observation,sourceIdentityDigest:input.sourceIdentityDigest,validityBindingDigest:input.validityBindingDigest,claimIds:sortedUnique(input.claimIds),refs:[...input.refs].sort((a,b)=>compareCodePoint(a.refId,b.refId))};}
export function createMachineEvidenceItem(input:MachineEvidenceItemInput,options:OperationOptions):Result<MachineEvidenceItem>{const sv=verifySubjectStateBinding(input.subject,options);if(!sv.ok||!sv.value)return sv.ok?fail('MEM24_SUBJECT_TAMPERED','Evidence item requires verified subject binding.',input.evidenceId):sv;if(!validId(input.evidenceId)||!validId(input.producerId)||!isEvidenceKind(input.kind)||!['PASS','FAIL','INCONCLUSIVE','NOT_APPLICABLE'].includes(input.observation)||!isSha256(input.sourceIdentityDigest)||!isSha256(input.validityBindingDigest)||input.claimIds.length===0||input.claimIds.some(x=>!validId(x)))return fail('MEM24_ITEM_INVALID','Evidence item fields are invalid.',input.evidenceId);const privacy=applyEvidencePrivacyMembrane(input.refs,options);if(!privacy.ok)return privacy;if(!privacy.value.safe)return fail('EPM24_PRIVACY_REJECTED','Evidence item contains non-portable/raw reference material.',input.evidenceId);const body=itemBody(input);const d=digestValue(options,'MEM24_ITEM',body);if(!d.ok)return d;return ok(deepFreeze({...body,semanticDigest:d.value}));}
export function verifyMachineEvidenceItem(value:MachineEvidenceItem,options:OperationOptions):Result<boolean>{const rebuilt=createMachineEvidenceItem(value,options);return rebuilt.ok?ok(rebuilt.value.semanticDigest===value.semanticDigest):rebuilt;}

export function createEvidenceClaimMapping(items:readonly MachineEvidenceItem[],options:OperationOptions):Result<EvidenceClaimMapping>{const m=new Map<string,string[]>();for(const item of items)for(const claim of item.claimIds){const a=m.get(claim)??[];a.push(item.semanticDigest);m.set(claim,a);}const entries:EvidenceClaimMappingEntry[]=[...m.entries()].sort(([a],[b])=>compareCodePoint(a,b)).map(([claimId,digests])=>({claimId,evidenceDigests:sortedUnique(digests)}));const d=digestValue(options,'ECM24',{entries});if(!d.ok)return d;return ok(deepFreeze({entries,mappingDigest:d.value}));}

export function createEvidenceBindingLedger(items:readonly MachineEvidenceItem[],options:OperationOptions):Result<EvidenceBindingLedger>{const byId=new Map<string,MachineEvidenceItem[]>();for(const i of items){const a=byId.get(i.evidenceId)??[];a.push(i);byId.set(i.evidenceId,a);}const accepted:string[]=[];const duplicates:string[]=[];const conflicts:string[]=[];for(const[id,list]of byId){const unique=sortedUnique(list.map(x=>x.semanticDigest));accepted.push(...unique);if(unique.length===1&&list.length>1)duplicates.push(unique[0]??'');if(unique.length>1)conflicts.push(id);}const body={acceptedItemDigests:sortedUnique(accepted),duplicateItemDigests:sortedUnique(duplicates.filter(Boolean)),conflictingEvidenceIds:sortedUnique(conflicts)};const d=digestValue(options,'EBL24',body);if(!d.ok)return d;return ok(deepFreeze({...body,ledgerDigest:d.value}));}

export function createMachineEvidenceManifest(rootSet:AuthorityRootSet,index:SourceAuthorityIndex,items:readonly MachineEvidenceItem[],options:OperationOptions):Result<MachineEvidenceManifest>{const rv=verifyAuthorityRootSet(rootSet,options);if(!rv.ok||!rv.value)return rv.ok?fail('MEM24_ROOT_SET_TAMPERED','Manifest requires verified authority root set.'):rv;const iv=verifySourceAuthorityIndex(index,rootSet,options);if(!iv.ok||!iv.value)return iv.ok?fail('MEM24_AUTH_INDEX_TAMPERED','Manifest requires verified authority index.'):iv;if(items.length===0)return fail('MEM24_EMPTY','Machine evidence manifest cannot be empty.');const guard=new Guard(options);for(const i of items){const s=guard.step(i.evidenceId);if(!s.ok)return s;const v=verifyMachineEvidenceItem(i,options);if(!v.ok||!v.value)return v.ok?fail('MEM24_ITEM_TAMPERED','Manifest item failed verification.',i.evidenceId):v;if(i.subject.projectId!==rootSet.projectId||i.subject.lineageId!==rootSet.lineageId)return fail('MEM24_ITEM_LINEAGE_MISMATCH','Manifest item crosses root-set project/lineage.',i.evidenceId);}const mapping=createEvidenceClaimMapping(items,options);if(!mapping.ok)return mapping;const ledger=createEvidenceBindingLedger(items,options);if(!ledger.ok)return ledger;const sorted=[...items].sort((a,b)=>compareCodePoint(a.semanticDigest,b.semanticDigest));const body={projectId:rootSet.projectId,lineageId:rootSet.lineageId,rootSetDigest:rootSet.rootSetDigest,authorityIndexDigest:index.indexDigest,items:sorted,itemDigests:sorted.map(x=>x.semanticDigest),claimMapping:mapping.value,bindingLedger:ledger.value};const d=digestValue(options,'MEM24',body);if(!d.ok)return d;return ok(deepFreeze({...body,manifestDigest:d.value}));}
export function verifyMachineEvidenceManifest(value:MachineEvidenceManifest,rootSet:AuthorityRootSet,index:SourceAuthorityIndex,options:OperationOptions):Result<boolean>{if(value.rootSetDigest!==rootSet.rootSetDigest||value.authorityIndexDigest!==index.indexDigest)return ok(false);const rebuilt=createMachineEvidenceManifest(rootSet,index,value.items,options);return rebuilt.ok?ok(rebuilt.value.manifestDigest===value.manifestDigest):rebuilt;}
