import type{EvidenceAcceptanceReceipt,EvidenceConflictReceipt,EvidenceDecisionReceipt,EvidenceInvalidationReceipt,EvidenceReceiptSet,EvidenceRejectionReceipt,EvidenceStalenessReceipt,EvidenceValidationReceipt,MachineEvidenceItem,OperationOptions,ReceiptReplayGuard,Result,ValidationState,EvidenceFreshnessGate,ProducerChainEnvelope,BindingIntegrityCertificate,PrivacyDecision,ProducerAuthorityDecision,EvidenceDependencyEntry,ReceiptSetState,ReplayGuardState}from'./types.js';
import{Guard,compareCodePoint,deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,validId}from'./utils.js';
import{verifyMachineEvidenceItem}from'./s01-manifest.js';

export function createEvidenceValidationReceipt(item:MachineEvidenceItem,manifestDigest:string,authority:ProducerAuthorityDecision,chain:ProducerChainEnvelope,certificate:BindingIntegrityCertificate,privacy:PrivacyDecision,state:ValidationState,reasonCodes:readonly string[],options:OperationOptions):Result<EvidenceValidationReceipt>{const iv=verifyMachineEvidenceItem(item,options);if(!iv.ok||!iv.value)return iv.ok?fail('EVR24_ITEM_TAMPERED','Validation receipt requires verified evidence item.',item.evidenceId):iv;if(!isSha256(manifestDigest)||chain.evidenceId!==item.evidenceId||certificate.evidenceId!==item.evidenceId||authority.producerId!==item.producerId||reasonCodes.some(x=>!validId(x)))return fail('EVR24_BINDING_INVALID','Validation receipt inputs are not coherently bound.',item.evidenceId);const body={evidenceId:item.evidenceId,itemDigest:item.semanticDigest,manifestDigest,authorityDecisionDigest:authority.decisionDigest,producerChainDigest:chain.chainDigest,bindingCertificateDigest:certificate.certificateDigest,privacyDecisionDigest:privacy.decisionDigest,state,reasonCodes:sortedUnique(reasonCodes)};const d=digestValue(options,'EVR24',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
export function verifyEvidenceValidationReceipt(value:EvidenceValidationReceipt,item:MachineEvidenceItem,manifestDigest:string,authority:ProducerAuthorityDecision,chain:ProducerChainEnvelope,certificate:BindingIntegrityCertificate,privacy:PrivacyDecision,options:OperationOptions):Result<boolean>{const r=createEvidenceValidationReceipt(item,manifestDigest,authority,chain,certificate,privacy,value.state,value.reasonCodes,options);return r.ok?ok(r.value.receiptDigest===value.receiptDigest):r;}

export function createEvidenceAcceptanceReceipt(item:MachineEvidenceItem,validation:EvidenceValidationReceipt,freshness:EvidenceFreshnessGate,options:OperationOptions):Result<EvidenceAcceptanceReceipt>{if(validation.evidenceId!==item.evidenceId||validation.itemDigest!==item.semanticDigest||validation.state!=='VALID'||freshness.evidenceId!==item.evidenceId||freshness.state!=='CURRENT'||item.observation!=='PASS')return fail('EAR24_ACCEPTANCE_PRECONDITION','Evidence acceptance requires VALID + CURRENT + PASS on the same item.',item.evidenceId);const body={evidenceId:item.evidenceId,state:'ACCEPTED' as const,validationReceiptDigest:validation.receiptDigest,freshnessGateDigest:freshness.gateDigest,sourceIdentityDigest:item.sourceIdentityDigest,validityBindingDigest:item.validityBindingDigest,claimIds:sortedUnique(item.claimIds)};const d=digestValue(options,'EAR24',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
export function verifyEvidenceAcceptanceReceipt(value:EvidenceAcceptanceReceipt,item:MachineEvidenceItem,validation:EvidenceValidationReceipt,freshness:EvidenceFreshnessGate,options:OperationOptions):Result<boolean>{const r=createEvidenceAcceptanceReceipt(item,validation,freshness,options);return r.ok?ok(r.value.receiptDigest===value.receiptDigest):r;}

export function createEvidenceRejectionReceipt(evidenceId:string,validation:EvidenceValidationReceipt,reasonCodes:readonly string[],options:OperationOptions):Result<EvidenceRejectionReceipt>{if(!validId(evidenceId)||validation.evidenceId!==evidenceId||validation.state==='VALID'||reasonCodes.length===0||reasonCodes.some(x=>!validId(x)))return fail('ERR24_REJECTION_INVALID','Evidence rejection receipt requires non-VALID bound validation and reasons.',evidenceId);const body={evidenceId,state:'REJECTED' as const,validationReceiptDigest:validation.receiptDigest,reasonCodes:sortedUnique(reasonCodes)};const d=digestValue(options,'ERR24',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
export function verifyEvidenceRejectionReceipt(value:EvidenceRejectionReceipt,validation:EvidenceValidationReceipt,options:OperationOptions):Result<boolean>{const r=createEvidenceRejectionReceipt(value.evidenceId,validation,value.reasonCodes,options);return r.ok?ok(r.value.receiptDigest===value.receiptDigest):r;}

export function createEvidenceStalenessReceipt(evidenceId:string,priorAcceptanceReceiptDigest:string|null,freshness:EvidenceFreshnessGate,options:OperationOptions):Result<EvidenceStalenessReceipt>{if(!validId(evidenceId)||freshness.evidenceId!==evidenceId||freshness.state!=='STALE'||priorAcceptanceReceiptDigest!==null&&!isSha256(priorAcceptanceReceiptDigest))return fail('ESR24_STALENESS_INVALID','Staleness receipt requires a STALE freshness gate.',evidenceId);const body={evidenceId,state:'STALE' as const,priorAcceptanceReceiptDigest,freshnessGateDigest:freshness.gateDigest,staleSubjects:sortedUnique(freshness.staleSubjects)};const d=digestValue(options,'ESR24',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
export function verifyEvidenceStalenessReceipt(value:EvidenceStalenessReceipt,freshness:EvidenceFreshnessGate,options:OperationOptions):Result<boolean>{const r=createEvidenceStalenessReceipt(value.evidenceId,value.priorAcceptanceReceiptDigest,freshness,options);return r.ok?ok(r.value.receiptDigest===value.receiptDigest):r;}

export function createEvidenceConflictReceipt(evidenceId:string,sourceReceiptDigests:readonly string[],conflictSubjects:readonly string[],options:OperationOptions):Result<EvidenceConflictReceipt>{if(!validId(evidenceId)||sourceReceiptDigests.length<2||sourceReceiptDigests.some(x=>!isSha256(x))||conflictSubjects.length===0||conflictSubjects.some(x=>!validId(x)))return fail('ECR24_CONFLICT_INVALID','Conflict receipt requires multiple valid source receipts and subjects.',evidenceId);const body={evidenceId,state:'CONFLICT' as const,sourceReceiptDigests:sortedUnique(sourceReceiptDigests),conflictSubjects:sortedUnique(conflictSubjects)};if(body.sourceReceiptDigests.length<2)return fail('ECR24_CONFLICT_INSUFFICIENT','Conflict receipt requires distinct source receipts.',evidenceId);const d=digestValue(options,'ECR24',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
export function verifyEvidenceConflictReceipt(value:EvidenceConflictReceipt,options:OperationOptions):Result<boolean>{const r=createEvidenceConflictReceipt(value.evidenceId,value.sourceReceiptDigests,value.conflictSubjects,options);return r.ok?ok(r.value.receiptDigest===value.receiptDigest):r;}

function stateOf(r:EvidenceDecisionReceipt){return r.state;}
export function verifyEvidenceDecisionReceipt(value:EvidenceDecisionReceipt,options:OperationOptions):Result<boolean>{if(value.state==='CONFLICT')return verifyEvidenceConflictReceipt(value,options);const d=digestValue(options,value.state==='ACCEPTED'?'EAR24':value.state==='REJECTED'?'ERR24':'ESR24',(()=>{const{receiptDigest,...rest}=value;return rest;})());return d.ok?ok(d.value===value.receiptDigest):d;}

export function createEvidenceReceiptSet(receipts:readonly EvidenceDecisionReceipt[],options:OperationOptions):Result<EvidenceReceiptSet>{if(receipts.length===0)return fail('ERS24_EMPTY','Receipt set cannot be empty.');const max=Math.max(1,Math.min(options.maxHistory??receipts.length,131072));const processed=receipts.slice(0,max);const guard=new Guard({...options,maxUnits:max});for(const r of processed){const s=guard.step(r.evidenceId);if(!s.ok)return s;const v=verifyEvidenceDecisionReceipt(r,options);if(!v.ok||!v.value)return v.ok?fail('ERS24_RECEIPT_TAMPERED','Receipt set contains tampered receipt.',r.evidenceId):v;}const statesById=new Map<string,Set<string>>();for(const r of processed){const s=statesById.get(r.evidenceId)??new Set<string>();s.add(stateOf(r));statesById.set(r.evidenceId,s);}const conflict=[...statesById.values()].some(x=>x.size>1);const truncated=processed.length<receipts.length;const state:ReceiptSetState=conflict?'CONFLICT':truncated?'TRUNCATED':'COMPLETE';const body={receiptDigests:sortedUnique(processed.map(r=>r.receiptDigest)),evidenceIds:sortedUnique(processed.map(r=>r.evidenceId)),state,historyTruncated:truncated,processedCount:processed.length,totalCount:receipts.length};const d=digestValue(options,'ERS24',body);if(!d.ok)return d;return ok(deepFreeze({...body,setDigest:d.value}));}

export function createReceiptReplayGuard(receipts:readonly EvidenceDecisionReceipt[],options:OperationOptions):Result<ReceiptReplayGuard>{if(receipts.length===0)return fail('RPG24_EMPTY','Replay guard requires receipt history.');const max=Math.max(1,Math.min(options.maxHistory??receipts.length,131072));const processed=receipts.slice(0,max);const byDigest=new Map<string,number>();const byId=new Map<string,Set<string>>();for(const r of processed){const v=verifyEvidenceDecisionReceipt(r,options);if(!v.ok||!v.value)return v.ok?fail('RPG24_RECEIPT_TAMPERED','Replay guard rejected tampered receipt.',r.evidenceId):v;byDigest.set(r.receiptDigest,(byDigest.get(r.receiptDigest)??0)+1);const s=byId.get(r.evidenceId)??new Set<string>();s.add(stateOf(r));byId.set(r.evidenceId,s);}const duplicates=[...byDigest.entries()].filter(([,n])=>n>1).map(([d])=>d).sort(compareCodePoint);const conflicts=[...byId.entries()].filter(([,s])=>s.size>1).map(([id])=>id).sort(compareCodePoint);const truncated=processed.length<receipts.length;const state:ReplayGuardState=conflicts.length>0?'CONFLICT':truncated?'TRUNCATED':'CLEAR';const body={state,acceptedReceiptDigests:sortedUnique(processed.map(r=>r.receiptDigest)),duplicateReceiptDigests:duplicates,conflictingEvidenceIds:conflicts,historyTruncated:truncated,processedCount:processed.length,totalCount:receipts.length};const d=digestValue(options,'RPG24',body);if(!d.ok)return d;return ok(deepFreeze({...body,guardDigest:d.value}));}

export function createEvidenceInvalidationReceipt(invalidationId:string,changedDependencyDigests:readonly string[],entries:readonly EvidenceDependencyEntry[],priorReceipts:readonly EvidenceDecisionReceipt[],completeKnowledge:boolean,options:OperationOptions):Result<EvidenceInvalidationReceipt>{if(!validId(invalidationId)||changedDependencyDigests.length===0||changedDependencyDigests.some(x=>!isSha256(x)))return fail('EIR24_INVALIDATION_INVALID','Invalidation requires stable ID and changed dependency digests.',invalidationId);const changed=new Set(changedDependencyDigests);const allEvidence=sortedUnique(entries.map(e=>e.evidenceId));const direct=entries.filter(e=>e.dependencyDigests.some(d=>changed.has(d))).map(e=>e.evidenceId);const affectedEvidenceIds=completeKnowledge?sortedUnique(direct):allEvidence;const affectedSet=new Set(affectedEvidenceIds);const affectedClaimIds=sortedUnique(entries.filter(e=>affectedSet.has(e.evidenceId)).flatMap(e=>[...e.claimIds]));const widened=!completeKnowledge;const priorReceiptDigests=sortedUnique(priorReceipts.filter(r=>affectedSet.has(r.evidenceId)).map(r=>r.receiptDigest));const body={invalidationId,changedDependencyDigests:sortedUnique(changedDependencyDigests),affectedEvidenceIds,affectedClaimIds,widened,priorReceiptDigests};const d=digestValue(options,'EIR24',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
