import type{BindingIntegrityCertificate,CompatibilityWitness,CompatibilityWitnessInput,CrossBoundaryDecision,DigestAlgorithmBoundary,EvidenceSemanticDigest,ExternalIdentity,IdentityDescriptor,MachineEvidenceItem,MixAndMatchSpliceWitness,OperationOptions,ProducerAuthorityDecision,ProducerChainEnvelope,Result,SourceAuthorityIndex,SubjectStateBinding,ExactRevisionBinding,AuthorityRootSet}from'./types.js';
import type{TrustedOperationOptions}from'./s00-trust.js';
import{compareCodePoint,deepFreeze,digestValue,fail,isSha256,ok,sameSet,sortedUnique,validId}from'./utils.js';
import{verifyMachineEvidenceItem,verifySourceAuthorityIndex}from'./s01-manifest.js';
import{verifySubjectIdentityDomains,verifySubjectStateBinding,verifyTrustedAuthorityRootSet}from'./s00-trust.js';

function extKey(v:ExternalIdentity|null){return v===null?'null':`${v.domain}:${v.algorithm??'opaque'}:${v.value}`;}
function mismatch(a:SubjectStateBinding,b:SubjectStateBinding){const out:string[]=[];if(a.projectId!==b.projectId)out.push('projectId');if(a.lineageId!==b.lineageId)out.push('lineageId');if(a.subjectKind!==b.subjectKind)out.push('subjectKind');if(a.subjectId!==b.subjectId)out.push('subjectId');if(a.moduleId!==b.moduleId)out.push('moduleId');if(a.workOrderId!==b.workOrderId)out.push('workOrderId');if(a.checkpointDigest!==b.checkpointDigest)out.push('checkpointDigest');if(extKey(a.baseRevision)!==extKey(b.baseRevision))out.push('baseRevision');if(extKey(a.headRevision)!==extKey(b.headRevision))out.push('headRevision');if(extKey(a.treeRevision)!==extKey(b.treeRevision))out.push('treeRevision');if(extKey(a.runtimeIdentity)!==extKey(b.runtimeIdentity))out.push('runtimeIdentity');if(extKey(a.platformIdentity)!==extKey(b.platformIdentity))out.push('platformIdentity');if(a.policyDigest!==b.policyDigest)out.push('policyDigest');if(!sameSet(a.dependencyDigests,b.dependencyDigests))out.push('dependencyDigests');return out.sort(compareCodePoint);}

export function createEvidenceSemanticDigest(item:MachineEvidenceItem,options:OperationOptions):Result<EvidenceSemanticDigest>{const v=verifyMachineEvidenceItem(item,options);if(!v.ok||!v.value)return v.ok?fail('ESD24_ITEM_TAMPERED','Semantic digest requires a verified evidence item.',item.evidenceId):v;return ok(deepFreeze({evidenceId:item.evidenceId,semanticDigest:item.semanticDigest}));}

export function createExactRevisionBinding(subject:SubjectStateBinding,options:OperationOptions):Result<ExactRevisionBinding>{const v=verifySubjectStateBinding(subject,options);if(!v.ok||!v.value)return v.ok?fail('XRB24_SUBJECT_TAMPERED','Exact revision binding requires verified subject.'):v;const body={subjectBindingDigest:subject.bindingDigest,baseRevision:subject.baseRevision,headRevision:subject.headRevision,treeRevision:subject.treeRevision};const d=digestValue(options,'XRB24',body);if(!d.ok)return d;return ok(deepFreeze({...body,revisionDigest:d.value}));}

export function createDigestAlgorithmBoundary(descriptor:IdentityDescriptor,options:OperationOptions):Result<DigestAlgorithmBoundary>{let valid=false;let reasonCode='IDENTITY_DOMAIN_INVALID';if(descriptor.domain==='M24_SEMANTIC'){valid=descriptor.algorithm==='sha256'&&isSha256(descriptor.value);reasonCode=valid?'M24_SHA256_VALID':'M24_SHA256_REQUIRED';}else{valid=descriptor.value.length>0&&descriptor.value.length<=512&&descriptor.algorithm!=='sha256-domain-separated';reasonCode=valid?'EXTERNAL_IDENTITY_OPAQUE':'EXTERNAL_IDENTITY_INVALID';}const body={descriptor,valid,reasonCode};const d=digestValue(options,'DAB24',body);if(!d.ok)return d;return ok(deepFreeze({...body,boundaryDigest:d.value}));}

export function createCompatibilityWitness(input:CompatibilityWitnessInput,options:OperationOptions):Result<CompatibilityWitness>{if(!validId(input.witnessId)||input.owner!=='EXTERNAL_CANONICAL'||!validId(input.projectId)||!validId(input.lineageId)||!isSha256(input.fromBindingDigest)||!isSha256(input.toBindingDigest)||!isSha256(input.authorizationDigest)||input.claimIds.length===0||input.claimIds.some(x=>!validId(x)))return fail('CBB24_WITNESS_INVALID','Compatibility witness is invalid.',input.witnessId);if(input.fromBindingDigest===input.toBindingDigest)return fail('CBB24_WITNESS_REDUNDANT','Compatibility witness cannot translate identical bindings.',input.witnessId);const body={witnessId:input.witnessId,owner:input.owner,projectId:input.projectId,lineageId:input.lineageId,fromBindingDigest:input.fromBindingDigest,toBindingDigest:input.toBindingDigest,claimIds:sortedUnique(input.claimIds),authorizationDigest:input.authorizationDigest};const d=digestValue(options,'CBB24',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}
export function verifyCompatibilityWitness(value:CompatibilityWitness,options:OperationOptions):Result<boolean>{const r=createCompatibilityWitness(value,options);return r.ok?ok(r.value.witnessDigest===value.witnessDigest):r;}
export function verifyTrustedCompatibilityWitness(value:CompatibilityWitness,options:TrustedOperationOptions):Result<boolean>{const structural=verifyCompatibilityWitness(value,options);if(!structural.ok||!structural.value)return structural.ok?fail('CBB24_WITNESS_TAMPERED','Compatibility witness failed structural verification.',value.witnessId):structural;const trusted=sortedUnique(options.trustedCompatibilityAuthorizationDigests??[]);if(trusted.length===0||trusted.some(x=>!isSha256(x)))return fail('CBB24_TRUST_ANCHOR_MISSING','Compatibility translation requires externally injected trusted authorization digests.',value.witnessId);if(!trusted.includes(value.authorizationDigest))return fail('CBB24_AUTHORIZATION_NOT_TRUSTED','Compatibility witness authorization is not externally trusted.',value.witnessId);return ok(true);}

export function createBindingIntegrityCertificate(item:MachineEvidenceItem,current:SubjectStateBinding,witness:CompatibilityWitness|null,options:OperationOptions):Result<BindingIntegrityCertificate>{const iv=verifyMachineEvidenceItem(item,options),cv=verifySubjectStateBinding(current,options),itemDomains=verifySubjectIdentityDomains(item.subject);if(!iv.ok||!iv.value)return iv.ok?fail('BIC24_ITEM_TAMPERED','Binding certificate requires verified evidence item.',item.evidenceId):iv;if(!cv.ok||!cv.value)return cv.ok?fail('BIC24_CURRENT_SUBJECT_TAMPERED','Binding certificate requires verified current subject.',item.evidenceId):cv;if(!itemDomains.ok||!itemDomains.value)return itemDomains.ok?fail('BIC24_ITEM_DOMAIN_INVALID','Evidence item subject identity domains are invalid.',item.evidenceId):itemDomains;const mismatchedDimensions=mismatch(item.subject,current);const exact=mismatchedDimensions.length===0;let translated=false;let witnessDigest:string|null=null;if(!exact&&witness){const wv=verifyCompatibilityWitness(witness,options);if(!wv.ok||!wv.value)return wv.ok?fail('BIC24_WITNESS_TAMPERED','Compatibility witness failed structural verification.',witness.witnessId):wv;translated=witness.projectId===current.projectId&&witness.lineageId===current.lineageId&&witness.fromBindingDigest===item.subject.bindingDigest&&witness.toBindingDigest===current.bindingDigest&&item.claimIds.every(c=>witness.claimIds.includes(c));if(translated)witnessDigest=witness.witnessDigest;}const body={evidenceId:item.evidenceId,evidenceSubjectBindingDigest:item.subject.bindingDigest,currentSubjectBindingDigest:current.bindingDigest,exact,translated,compatibilityWitnessDigest:witnessDigest,mismatchedDimensions};const d=digestValue(options,'BIC24',body);if(!d.ok)return d;return ok(deepFreeze({...body,certificateDigest:d.value}));}

export function createMixAndMatchSpliceWitness(items:readonly MachineEvidenceItem[],options:OperationOptions):Result<MixAndMatchSpliceWitness>{if(items.length===0)return fail('MSW24_EMPTY','Splice witness requires at least one evidence item.');for(const i of items){const v=verifyMachineEvidenceItem(i,options);if(!v.ok||!v.value)return v.ok?fail('MSW24_ITEM_TAMPERED','Splice witness requires verified evidence items.',i.evidenceId):v;}const projects=new Set(items.map(x=>x.subject.projectId)),lineages=new Set(items.map(x=>x.subject.lineageId)),subjects=new Set(items.map(x=>`${x.subject.subjectKind}:${x.subject.subjectId}`));const body={itemDigests:sortedUnique(items.map(x=>x.semanticDigest)),mixedProject:projects.size>1,mixedLineage:lineages.size>1,mixedSubject:subjects.size>1,spliceDetected:projects.size>1||lineages.size>1||subjects.size>1};const d=digestValue(options,'MSW24',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}

export function createProducerChainEnvelope(item:MachineEvidenceItem,decision:ProducerAuthorityDecision,rootSet:AuthorityRootSet,index:SourceAuthorityIndex,options:TrustedOperationOptions):Result<ProducerChainEnvelope>{const rv=verifyTrustedAuthorityRootSet(rootSet,options),iv=verifySourceAuthorityIndex(index,rootSet,options),ev=verifyMachineEvidenceItem(item,options);if(!rv.ok||!rv.value)return rv.ok?fail('PCE24_ROOT_SET_NOT_TRUSTED','Producer chain requires trusted root set.',item.evidenceId):rv;if(!iv.ok||!iv.value)return iv.ok?fail('PCE24_INDEX_TAMPERED','Producer chain requires verified authority index.',item.evidenceId):iv;if(!ev.ok||!ev.value)return ev.ok?fail('PCE24_ITEM_TAMPERED','Producer chain requires verified evidence item.',item.evidenceId):ev;if(decision.producerId!==item.producerId||decision.evidenceKind!==item.kind||!sameSet(decision.claimIds,item.claimIds)||!decision.authorized||decision.conflict)return fail('PCE24_DECISION_MISMATCH','Producer chain requires a non-conflicting authorized decision bound to the evidence item.',item.evidenceId);const body={evidenceId:item.evidenceId,rootSetDigest:rootSet.rootSetDigest,authorityIndexDigest:index.indexDigest,authorityDecisionDigest:decision.decisionDigest,sourceIdentityDigest:item.sourceIdentityDigest,itemDigest:item.semanticDigest};const d=digestValue(options,'PCE24',body);if(!d.ok)return d;return ok(deepFreeze({...body,chainDigest:d.value}));}

export function createCrossBoundaryDecision(item:MachineEvidenceItem,current:SubjectStateBinding,witness:CompatibilityWitness|null,options:TrustedOperationOptions):Result<CrossBoundaryDecision>{const cert=createBindingIntegrityCertificate(item,current,witness,options);if(!cert.ok)return cert;let allowed=cert.value.exact;if(cert.value.translated){if(!witness)return fail('CBB24_WITNESS_MISSING','Translated binding requires compatibility witness.',item.evidenceId);const trusted=verifyTrustedCompatibilityWitness(witness,options);if(!trusted.ok||!trusted.value)return trusted.ok?fail('CBB24_WITNESS_NOT_TRUSTED','Compatibility translation is not authorized.',witness.witnessId):trusted;allowed=true;}const body={evidenceId:item.evidenceId,allowed,compatibilityWitnessDigest:allowed&&!cert.value.exact?cert.value.compatibilityWitnessDigest:null,reasonCodes:allowed?[cert.value.exact?'EXACT_BINDING':'AUTHORIZED_COMPATIBILITY_TRANSLATION']:['CROSS_BOUNDARY_REUSE_REJECTED']};const d=digestValue(options,'XSB24',body);if(!d.ok)return d;return ok(deepFreeze({...body,decisionDigest:d.value}));}
