import type{OperationOptions,Result,SelectionPlan,TestImpactHandoff,TestImpactResult,Uncertainty,ValidationLevel,ValidationWave}from'./types.js';import{digest,maxLevel,ok,unique}from'./utils.js';
export function widenForUncertainty(level:ValidationLevel,u:Uncertainty):ValidationLevel{if(u==='BOUNDARY')return maxLevel(level,'L3');if(['SYSTEMIC','CONFLICT','UNKNOWN','TRUNCATED'].includes(u))return maxLevel(level,'L4');return level;}
export function dynamicTestSurface(dynamicIds:readonly string[]){return{uncertainty:dynamicIds.length?'SYSTEMIC' as const:'NONE' as const,subjects:unique(dynamicIds)};}
export function validateContext(expected:Record<string,string>,actual:Record<string,string>){for(const k of Object.keys(expected).sort())if(expected[k]!==actual[k])return{valid:false,reason:`CONTEXT_MISMATCH:${k}`};return{valid:true,reason:'CONTEXT_MATCH'};}
export function exactCandidateHandoff(input:{candidateDigest:string;policyDigest:string;profileDigest:string;mapDigest:string;selectedSetDigest:string;configDigest:string;runtimeDigest:string;toolchainDigest:string;platform:string;uncertainty:Uncertainty},options:OperationOptions){return digest(options,'EH28',input);}
export function specifyValidationWaves(groups:readonly{tests:readonly string[];after?:readonly string[];exclusiveResources?:readonly string[]}[],options:OperationOptions):Result<readonly ValidationWave[]>{const waves:ValidationWave[]=[];for(const g of groups){const body={tests:unique(g.tests),after:unique(g.after??[]),exclusiveResources:unique(g.exclusiveResources??[])};const d=digest(options,'VWS28',body);if(!d.ok)return d;waves.push({id:d.value,...body});}return ok(waves);}
export function createTestImpactResult(input:{selection:SelectionPlan;reusableTests?:readonly string[];unresolved?:readonly string[];waves?:readonly ValidationWave[];state?:TestImpactResult['state']},options:OperationOptions):Result<TestImpactResult>{const unresolved=unique(input.unresolved??[]),reusableTests=unique(input.reusableTests??[]),waves=input.waves??[];const state=input.state??(input.selection.uncertainty==='TRUNCATED'?'TRUNCATED':input.selection.uncertainty==='NONE'?'READY':'WIDENED');const body={state,selection:input.selection,reusableTests,unresolved,waves};const d=digest(options,'TIR28',body);return d.ok?ok({...body,digest:d.value}):d;}
export function createTestImpactHandoff(consumerId:string,candidateDigest:string,result:TestImpactResult,options:OperationOptions):Result<TestImpactHandoff>{const body={consumerId,candidateDigest,resultDigest:result.digest,authority:'READ_ONLY_TEST_IMPACT' as const};const d=digest(options,'TIH28',body);return d.ok?ok({...body,digest:d.value}):d;}
export const deniesMutationAuthority=(h:TestImpactHandoff)=>h.authority==='READ_ONLY_TEST_IMPACT';
