import { createHash } from 'node:crypto';
const cmp=(a,b)=>a<b?-1:a>b?1:0; const stable=x=>JSON.stringify(x,Object.keys(x).sort());
export const digest=x=>createHash('sha256').update(typeof x==='string'?x:stable(x)).digest('hex');
export function repositoryState(s={}){const required=['repo','head','branch'];for(const k of required)if(!s[k])return {state:'BLOCKED',reason:`MISSING_${k.toUpperCase()}`};const dirty=!!(s.modified?.length||s.staged?.length||s.untracked?.length);const conflict=!!(s.conflicted?.length||s.operation);return {state:conflict?'BLOCKED':dirty?'DIRTY':'CLEAN',dirty,conflict,digest:digest(s)};}
export function branchPlan(state,target,{protectedBranches=['main','master'],force=false}={}){if(state.state==='BLOCKED')return {allowed:false,reason:'REPOSITORY_BLOCKED'};if(protectedBranches.includes(target)&&force)return {allowed:false,reason:'PROTECTED_BRANCH_FORCE_DENIED'};if(state.dirty)return {allowed:false,reason:'DIRTY_TREE'};return {allowed:true,target,expectedHead:state.head};}
export function commitPlan(state,message,paths=[]){if(state.state==='BLOCKED'||state.dirty)return {allowed:false,reason:'UNSAFE_STATE'};if(!message?.trim()||!paths.length)return {allowed:false,reason:'EMPTY_COMMIT_PLAN'};return {allowed:true,parent:state.head,message:message.trim(),paths:[...new Set(paths)].sort(cmp),receipt:digest({parent:state.head,message,paths:[...new Set(paths)].sort(cmp)})};}
export function githubBootstrap(current={},desired={}){const set=(desired.labels||[]).map(String).filter(Boolean).sort(cmp);const have=new Set((current.labels||[]).map(String));return {metadata:desired.metadata||{},labelsToAdd:set.filter(x=>!have.has(x)),preservedUnknown:[...have].filter(x=>!set.includes(x)).sort(cmp),templates:desired.templates||{},idempotencyKey:digest(desired)};}
export function governance(policy={},observed={}){const required=[...new Set(policy.requiredChecks||[])].sort(cmp);const missing=required.filter(x=>observed.checks?.[x]!=='success');const stale=!!(observed.reviewedHead&&observed.head&&observed.reviewedHead!==observed.head);const findings=(observed.findings||[]).filter(x=>['HIGH','CRITICAL'].includes(x.severity)&&!x.resolved);return {authorized:!missing.length&&!stale&&!findings.length,missing,stale,blockingFindings:findings.length,mergeMethod:policy.mergeMethod||'squash'};}
export function ciPlan({head,tests=[],platforms=['ubuntu-latest'],requiredChecks=[]}={}){if(!head)return {state:'BLOCKED',reason:'MISSING_HEAD'};return {state:'READY',head,tests:[...new Set(tests)].sort(cmp),platforms:[...new Set(platforms)].sort(cmp),requiredChecks:[...new Set(requiredChecks)].sort(cmp),receipt:digest({head,tests:[...new Set(tests)].sort(cmp),platforms:[...new Set(platforms)].sort(cmp),requiredChecks:[...new Set(requiredChecks)].sort(cmp)})};}
export function aggregateChecks(plan,observedHead,checks={}){if(plan.head!==observedHead)return {accepted:false,reason:'STALE_HEAD'};const missing=plan.requiredChecks.filter(x=>checks[x]!=='success');return {accepted:missing.length===0,reason:missing.length?'REQUIRED_CHECKS_INCOMPLETE':'ACCEPTED',missing};}
const semver=/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z.-]+))?$/;
export function releasePlan({version,previous,head,tagTarget,ciAccepted=false,findings=[]}={}){if(!semver.test(version||''))return {authorized:false,reason:'INVALID_SEMVER'};if(previous&&semver.test(previous)){const a=previous.split('.').map(Number),b=version.split('.').map(Number);if(b[0]<a[0]||(b[0]===a[0]&&b[1]<a[1])||(b[0]===a[0]&&b[1]===a[1]&&b[2]<=a[2]))return {authorized:false,reason:'VERSION_NOT_ADVANCING'};}if(tagTarget&&tagTarget!==head)return {authorized:false,reason:'TAG_HEAD_MISMATCH'};if(!ciAccepted)return {authorized:false,reason:'CI_NOT_ACCEPTED'};if(findings.some(x=>['HIGH','CRITICAL'].includes(x.severity)&&!x.resolved))return {authorized:false,reason:'BLOCKING_FINDINGS'};return {authorized:true,version,tag:`v${version}`,head,rollback:{target:previous||null,source:head},receipt:digest({version,head})};}
export const AREA_H_MODULES=Object.freeze({M29:{weight:20},M30:{weight:17},M31:{weight:18},M32:{weight:17},M33:{weight:19}});