import { createHash } from 'node:crypto';
const stable=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a<b?-1:a>b?1:0)):x);
export const digest=(domain,value)=>createHash('sha256').update(`${domain}\0${stable(value)}`).digest('hex');
export function detectUgas(receipt){if(!receipt)return {state:'ABSENT'};if(receipt.state!=='AVAILABLE'||!receipt.providerId||!receipt.contractVersion||!receipt.provenanceDigest)return {state:'INDETERMINATE'};return {state:'AVAILABLE',providerId:receipt.providerId,contractVersion:receipt.contractVersion,capabilities:[...(receipt.capabilities??[])].sort()};}
export function createRegistry(adapters){const seen=new Set();const ordered=[...adapters].sort((a,b)=>a.id.localeCompare(b.id));for(const a of ordered){const key=`${a.id}@${String(a.version).split('.')[0]}`;if(seen.has(key))throw new Error('ADAPTER_CONFLICT');seen.add(key);}return Object.freeze({adapters:Object.freeze(ordered),digest:digest('GEF/ARX42',ordered)});}
export function negotiate(adapter,capability){return adapter?.capabilities?.includes(capability)?'COMPATIBLE':'INCOMPATIBLE';}
export function eventEnvelope(input){const attrs=Object.fromEntries(Object.entries(input.attributes??{}).filter(([k])=>!/(secret|token|password|prompt|response)/i.test(k)));return Object.freeze({...input,attributes:attrs});}
export function appendAudit(ledger,event){const previousDigest=ledger.at(-1)?.digest??'GENESIS';const body={...event,previousDigest};return [...ledger,Object.freeze({...body,digest:digest('GEF/ALE44',body)})];}
export function verifyAudit(ledger){let prev='GENESIS';for(const e of ledger){const {digest:got,...body}=e;if(body.previousDigest!==prev||digest('GEF/ALE44',body)!==got)return 'INVALID';prev=got;}return 'VALID';}
export function compareBenchmark(before,after){for(const k of ['workload','assurance','environment'])if(before[k]!==after[k])return {state:'NOT_COMPARABLE'};if(!Number.isFinite(before.value)||!Number.isFinite(after.value))return {state:'INDETERMINATE'};const delta=(after.value-before.value)/before.value;return {state:Math.abs(delta)<0.02?'STABLE':delta<0?'IMPROVED':'REGRESSED',delta};}
export function jsonArtifact(kind,value,meta={}){const content=stable(value);return {kind,version:meta.version??'1.0.0',content,digest:digest('GEF/JAC46',value),provenance:meta.provenance??null};}
export function operatorStatus(state){return {state:state.state,progress:state.progress,evidence:state.evidence??[],stale:Boolean(state.stale),optional:Boolean(state.optional)};}
export function safeAdapterInvoke(registry,id,capability,input,{budget=1,cancelled=false}={}){if(cancelled)return {ok:false,code:'CANCELLED'};if(budget<=0)return {ok:false,code:'BUDGET_EXCEEDED'};const a=registry.adapters.find(x=>x.id===id);if(!a||negotiate(a,capability)!=='COMPATIBLE')return {ok:false,code:'CAPABILITY_DENIED'};try{return {ok:true,value:a.invoke(capability,input)}}catch{return {ok:false,code:'PROVIDER_FAILURE'}}}
