import test from "node:test";
import assert from "node:assert/strict";
import { ProcessExitCode } from "../packages/contracts/dist/index.js";
import { CommandRegistry,KernelRuntime,RegistryCompositionError,createGefError,createProcessSpec,normalizeCauses,projectExitCode,redactUnknown,redactText } from "../packages/kernel/dist/index.js";
class FakeClock{constructor(now=1000){this.value=now;}nowMs(){return this.value;}set(now){this.value=now;}}
class FakeIds{constructor(){this.count=0;}nextId(prefix){this.count+=1;return`${prefix}-${this.count}`;}}
function basePorts(overrides={}){return{clock:new FakeClock(),ids:new FakeIds(),...overrides};}
function validString(input){return typeof input==="string"?{ok:true,value:input}:{ok:false,reason:"expected string"};}
function error(params={}){return createGefError({id:params.id??"err-x",category:params.category??"EXECUTION",reason:params.reason??"handler_failed",severity:params.severity??"ERROR",summary:params.summary??"failure",retryability:params.retryability??"NEVER",recoverability:params.recoverability??"NONE_REQUIRED",effectStatus:params.effectStatus??"NONE",...(params.remediations===undefined?{}:{remediations:params.remediations}),...(params.metadata===undefined?{}:{metadata:params.metadata}),...(params.causes===undefined?{}:{causes:params.causes})});}
function registration(overrides={}){return{commandId:"gef.test.echo",contractVersion:"1",owner:"GBS-M01",validateInput:validString,handler:(input)=>({ok:true,value:input}),...overrides};}
test("registry stable order",()=>{const r=new CommandRegistry([registration({commandId:"gef.test.zeta"}),registration({commandId:"gef.test.alpha"})]);assert.deepEqual(r.introspect().map(x=>x.commandId),["gef.test.alpha","gef.test.zeta"]);});
test("registry rejects invalid and duplicate IDs",()=>{assert.throws(()=>new CommandRegistry([registration({commandId:"bad command"})]),c=>c instanceof RegistryCompositionError&&c.code==="INVALID_COMMAND_ID");assert.throws(()=>new CommandRegistry([registration(),registration()]),c=>c instanceof RegistryCompositionError&&c.code==="DUPLICATE_COMMAND_ID");});
test("unknown command fail closed",async()=>{const result=await new KernelRuntime(new CommandRegistry(),basePorts()).execute({commandId:"gef.test.unknown",contractVersion:"1",input:"x"});assert.equal(result.ok,false);assert.equal(result.error.reasonCode,"gef.input.command_not_found");assert.equal(projectExitCode(result),10);});
test("version mismatch is precondition",async()=>{const result=await new KernelRuntime(new CommandRegistry([registration()]),basePorts()).execute({commandId:"gef.test.echo",contractVersion:"2",input:"x"});assert.equal(result.ok,false);assert.equal(projectExitCode(result),20);});
test("invalid input blocks handler",async()=>{let called=false;const result=await new KernelRuntime(new CommandRegistry([registration({handler:()=>{called=true;return{ok:true,value:"x"};}})]),basePorts()).execute({commandId:"gef.test.echo",contractVersion:"1",input:123});assert.equal(result.ok,false);assert.equal(called,false);});
test("capability blocks all later work",async()=>{const order=[];const runtime=new KernelRuntime(new CommandRegistry([registration({requiredCapabilities:["filesystem.write"],requiresTarget:true,handler:()=>{order.push("handler");return{ok:true,value:"x"};}})]),basePorts({policy:{check:()=>{order.push("policy");return{ok:true};}},targetBinding:{bind:()=>{order.push("target");return{ok:true,target:{targetRef:"r"}};}}}),{capabilities:[]});const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.ok,false);assert.deepEqual(order,[]);});
test("preflight order capability policy target handler",async()=>{const order=[];const runtime=new KernelRuntime(new CommandRegistry([registration({requiredCapabilities:["filesystem.read"],requiresTarget:true,handler:()=>{order.push("handler");return{ok:true,value:"ok"};}})]),basePorts({policy:{check:()=>{order.push("policy");return{ok:true};}},targetBinding:{bind:()=>{order.push("target");return{ok:true,target:{targetRef:"repo",stateFingerprint:"abc"}};}}}),{capabilities:["filesystem.read"]});const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x",expectedState:"abc"});assert.equal(result.ok,true);assert.deepEqual(order,["policy","target","handler"]);});
test("stale target blocks",async()=>{let called=false;const runtime=new KernelRuntime(new CommandRegistry([registration({requiresTarget:true,handler:()=>{called=true;return{ok:true,value:"x"};}})]),basePorts({targetBinding:{bind:()=>({ok:true,target:{targetRef:"repo",stateFingerprint:"new"}})}}));const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x",expectedState:"old"});assert.equal(result.ok,false);assert.equal(called,false);});
test("policy denial before target",async()=>{const order=[];const runtime=new KernelRuntime(new CommandRegistry([registration({requiresTarget:true,handler:()=>{order.push("handler");return{ok:true,value:"x"};}})]),basePorts({policy:{check:()=>{order.push("policy");return{ok:false,error:error({category:"AUTHORIZATION",reason:"required"})};}},targetBinding:{bind:()=>{order.push("target");return{ok:true,target:{targetRef:"repo"}};}}}));const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.ok,false);assert.deepEqual(order,["policy"]);assert.equal(projectExitCode(result),30);});
test("read only lifecycle and injection",async()=>{const clock=new FakeClock(42);const events=[];clock.set(100);const result=await new KernelRuntime(new CommandRegistry([registration()]),{clock,ids:new FakeIds(),telemetry:{emit:e=>events.push(e)}}).execute({commandId:"gef.test.echo",contractVersion:"1",input:"hello"});assert.equal(result.ok,true);assert.deepEqual(result.lifecycle.phases,["RECEIVED","VALIDATING","PREFLIGHTING","READY","EXECUTING"]);assert.equal(events.at(-1).event,"TERMINAL");});
test("cancelled before handler",async()=>{let called=false;const c=new AbortController();c.abort();const result=await new KernelRuntime(new CommandRegistry([registration({handler:()=>{called=true;return{ok:true,value:"x"};}})]),basePorts()).execute({commandId:"gef.test.echo",contractVersion:"1",input:"x",signal:c.signal});assert.equal(result.ok,false);assert.equal(called,false);assert.equal(result.lifecycle.terminal,"CANCELLED");assert.equal(projectExitCode(result),80);});
test("timeout before handler",async()=>{let called=false;const result=await new KernelRuntime(new CommandRegistry([registration({handler:()=>{called=true;return{ok:true,value:"x"};}})]),{clock:new FakeClock(1000),ids:new FakeIds()}).execute({commandId:"gef.test.echo",contractVersion:"1",input:"x",deadlineMs:999});assert.equal(result.ok,false);assert.equal(called,false);assert.equal(result.lifecycle.terminal,"TIMED_OUT");});
test("mutation verify then receipt",async()=>{const order=[];const runtime=new KernelRuntime(new CommandRegistry([registration({mutation:true,handler:()=>{order.push("handler");return{ok:true,value:"written",effectStatus:"CONFIRMED"};}})]),basePorts({verification:{verify:()=>{order.push("verify");return{ok:true};}},receipts:{write:()=>{order.push("receipt");return{ok:true,receiptRef:"receipt-1"};}}}));const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.ok,true);assert.deepEqual(order,["handler","verify","receipt"]);assert.equal(result.lifecycle.receiptRef,"receipt-1");});
test("verification failure exit 60",async()=>{const runtime=new KernelRuntime(new CommandRegistry([registration({mutation:true,handler:()=>({ok:true,value:"written",effectStatus:"CONFIRMED"})})]),basePorts({verification:{verify:()=>({ok:false,error:error({category:"VERIFICATION",reason:"post_state_failed",effectStatus:"CONFIRMED"})})},receipts:{write:()=>({ok:true,receiptRef:"never"})}}));const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.ok,false);assert.equal(projectExitCode(result),60);});
test("missing receipt gives recovery required",async()=>{const runtime=new KernelRuntime(new CommandRegistry([registration({mutation:true,handler:()=>({ok:true,value:"written",effectStatus:"CONFIRMED"})})]),basePorts({verification:{verify:()=>({ok:true})}}));const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.lifecycle.terminal,"RECOVERY_REQUIRED");assert.equal(projectExitCode(result),70);});
test("partial effect preserved",async()=>{const runtime=new KernelRuntime(new CommandRegistry([registration({handler:()=>({ok:false,error:error({category:"EXECUTION",reason:"provider_failed",effectStatus:"PARTIAL",recoverability:"MANUAL_REPAIR_REQUIRED"}),terminal:"PARTIAL_EXTERNAL_EFFECT",effectStatus:"PARTIAL"})})]),basePorts());const result=await runtime.execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.lifecycle.terminal,"PARTIAL_EXTERNAL_EFFECT");assert.equal(projectExitCode(result),70);});
test("unexpected exception sanitized",async()=>{const result=await new KernelRuntime(new CommandRegistry([registration({handler:()=>{throw new Error("secret token=abc");}})]),basePorts()).execute({commandId:"gef.test.echo",contractVersion:"1",input:"x"});assert.equal(result.error.category,"INTERNAL");assert.equal(JSON.stringify(result.error).includes("abc"),false);assert.equal(projectExitCode(result),90);});
test("redaction covers errors",()=>{const err=createGefError({id:"e1",category:"DEPENDENCY",reason:"provider_unavailable",severity:"ERROR",summary:"authorization=topsecret unavailable",retryability:"SAFE_WITH_BACKOFF",recoverability:"NONE_REQUIRED",metadata:{token:"abcd",nested:{password:"p",safe:"ok"}},remediations:[{actionId:"gef.provider.retry",parameters:{apiKey:"key",delay:10}}],causes:[{id:"c1",reasonCode:"provider.fail",summary:"Bearer abcdef"}]});const s=JSON.stringify(err);assert.equal(s.includes("topsecret"),false);assert.equal(s.includes("abcd"),false);assert.equal(s.includes("abcdef"),false);assert.equal(s.includes('"safe":"ok"'),true);});
test("causes bounded and deduped",()=>{const normalized=normalizeCauses(Array.from({length:12},(_,i)=>({id:`c${i%9}`,reasonCode:"x",summary:"safe"})));assert.equal(normalized.length,8);assert.equal(new Set(normalized.map(x=>x.id)).size,8);});
test("redaction handles cycles",()=>{const object={token:"secret",safe:"ok"};object.self=object;const redacted=redactUnknown(object);assert.equal(redacted.token,"[REDACTED]");assert.equal(redacted.self,"[CYCLE]");});
test("process spec has no shell field",()=>{const spec=createProcessSpec({executable:"git",argv:["status","--short"]});assert.equal("shell" in spec,false);assert.equal(Object.isFrozen(spec),true);});
test("exit families and recovery precedence",()=>{const map=new Map([["INPUT",10],["PRECONDITION",20],["POLICY",30],["AUTHORIZATION",30],["CAPABILITY",40],["DEPENDENCY",40],["EXECUTION",50],["VERIFICATION",60],["INTEGRITY",60],["RECOVERY",70],["CANCELLED",80],["TIMEOUT",80],["INTERNAL",90]]);for(const[category,code]of map){const result={ok:false,error:error({category}),lifecycle:{runId:"r",commandId:"gef.t.x",phases:[],terminal:category==="CANCELLED"?"CANCELLED":category==="TIMEOUT"?"TIMED_OUT":"FAILED",startedAtMs:0,endedAtMs:1,effectStatus:"NONE"}};assert.equal(projectExitCode(result),code,category);}const result={ok:false,error:error({category:"EXECUTION",recoverability:"RECOVERY_REQUIRED"}),lifecycle:{runId:"r",commandId:"gef.t.x",phases:[],terminal:"FAILED",startedAtMs:0,endedAtMs:1,effectStatus:"CONFIRMED"}};assert.equal(projectExitCode(result),70);});
test("CLI is thin projection",async()=>{const cli=await import("../packages/cli/dist/index.js");const result={ok:false,error:error({category:"INPUT"}),lifecycle:{runId:"r",commandId:"gef.t.x",phases:[],terminal:"BLOCKED",startedAtMs:0,endedAtMs:1,effectStatus:"NONE"}};assert.equal(cli.processExitCodeFor(result),10);});
test("imports do not mutate cwd",async()=>{const{mkdtemp,readdir,rm}=await import("node:fs/promises");const{tmpdir}=await import("node:os");const{join}=await import("node:path");const dir=await mkdtemp(join(tmpdir(),"gef-import-"));const before=await readdir(dir);const previous=process.cwd();try{process.chdir(dir);await import(`../packages/contracts/dist/index.js?x=${Date.now()}`);await import(`../packages/kernel/dist/index.js?x=${Date.now()}`);}finally{process.chdir(previous);}assert.deepEqual(await readdir(dir),before);await rm(dir,{recursive:true,force:true});});
test("malformed reason rejected",()=>{assert.throws(()=>createGefError({id:"e",category:"INPUT",reason:"Bad Reason",severity:"ERROR",summary:"x",retryability:"NEVER",recoverability:"NONE_REQUIRED"}),TypeError);});
test("redactText",()=>{assert.equal(redactText("Bearer abc token=xyz safe"),"Bearer [REDACTED] token=[REDACTED] safe");});
