import assert from "node:assert/strict";
import test from "node:test";
import { BUILTIN_PROFILES, TYPESCRIPT_NODE_SEMANTICS, PYTHON_SEMANTICS, WEB_APP_SEMANTICS, builtinRegistry, composeProfile, createProfileRegistry, profileSemanticDigest, projectProfileBindings, selectProfile, validateProfile } from "../packages/project-profiles/dist/index.js";

const base=(id,extra={})=>({schemaVersion:1,profileContractVersion:"1",profileId:id,profileVersion:"1.0.0",profileKind:"GENERIC",...extra});

test("built-ins are exact and immutable",()=>{assert.deepEqual(Object.keys(BUILTIN_PROFILES).sort(),["generic","python","typescript-node","web-app"]);assert.equal(BUILTIN_PROFILES["typescript-node"].semantics,TYPESCRIPT_NODE_SEMANTICS);assert.equal(BUILTIN_PROFILES.python.semantics,PYTHON_SEMANTICS);assert.equal(BUILTIN_PROFILES["web-app"].semantics,WEB_APP_SEMANTICS);assert(Object.isFrozen(BUILTIN_PROFILES.generic));});

test("generic default and explicit selection are exact",()=>{const rr=builtinRegistry();assert(rr.ok);const d=selectProfile({mode:"DEFAULT_GENERIC"},rr.value);assert(d.ok);assert.equal(d.value.profile.profileId,"generic");const miss=selectProfile({mode:"EXPLICIT_PROFILE",profileId:"missing"},rr.value);assert(!miss.ok);assert.equal(miss.error.code,"PROFILE_NOT_FOUND");const bad=selectProfile({mode:"DEFAULT_GENERIC",profileId:"python"},rr.value);assert(!bad.ok);});

test("built-ins cannot be shadowed",()=>{const r=createProfileRegistry([base("generic")]);assert(!r.ok);assert.equal(r.error.code,"PROFILE_AMBIGUOUS");});

test("strict shape rejects unknown and prototype-sensitive structure",()=>{const unknown=validateProfile({...base("custom"),surprise:true});assert(!unknown.ok);const polluted=Object.create({evil:true});Object.assign(polluted,base("custom"));assert(!validateProfile(polluted).ok);});

test("typed bindings reject coercion and valueClass authority",()=>{const p=base("custom",{templateBindings:[{bindingId:"core",templateId:"generic",templateVersion:"1.0.0",variableBindings:[{variableId:"feature.enabled",valueType:"BOOLEAN",value:"true"}]}]});assert(!validateProfile(p).ok);const v=base("custom",{templateBindings:[{bindingId:"core",templateId:"generic",templateVersion:"1.0.0",variableBindings:[{variableId:"feature.enabled",valueType:"BOOLEAN",value:true,valueClass:"PLAIN"}]}]});assert(!validateProfile(v).ok);});

test("semantic digest ignores binding ordering and display metadata",()=>{const a=base("custom",{displayMetadata:{name:"A"},templateBindings:[{bindingId:"b",templateId:"b",templateVersion:"1.0.0"},{bindingId:"a",templateId:"a",templateVersion:"1.0.0"}]});const b=base("custom",{displayMetadata:{name:"B"},templateBindings:[{bindingId:"a",templateId:"a",templateVersion:"1.0.0"},{bindingId:"b",templateId:"b",templateVersion:"1.0.0"}]});const av=validateProfile(a),bv=validateProfile(b);assert(av.ok&&bv.ok);assert.equal(av.value.nativeProfileSemanticDigest,bv.value.nativeProfileSemanticDigest);});

test("expectations fail closed",()=>{const rr=builtinRegistry();assert(rr.ok);const snap=rr.value.get("python");assert(snap);assert(!selectProfile({mode:"EXPLICIT_PROFILE",profileId:"python",expectedProfileVersion:"9.9.9"},rr.value).ok);assert(!selectProfile({mode:"EXPLICIT_PROFILE",profileId:"python",expectedProfileDigest:"fnv1a64-v1:0000000000000000"},rr.value).ok);});

test("single-parent composition preserves child and projects typed bindings",()=>{const parent0=base("parent",{templateBindings:[{bindingId:"base",templateId:"base-template",templateVersion:"1.0.0",variableBindings:[{variableId:"feature.enabled",valueType:"BOOLEAN",value:true}]}]});const pv=validateProfile(parent0);assert(pv.ok);const child0=base("child",{parentProfile:{profileId:"parent",profileVersion:"1.0.0",profileSemanticDigest:pv.value.nativeProfileSemanticDigest},templateBindings:[{bindingId:"child",templateId:"child-template",templateVersion:"1.0.0",variableBindings:[{variableId:"name",valueType:"STRING",value:"demo"}]}]});const reg=createProfileRegistry([parent0,child0]);assert(reg.ok);const child=reg.value.get("child");assert(child);const c=composeProfile(child,reg.value);assert(c.ok);assert.equal(c.value.profile.profileId,"child");assert.deepEqual(c.value.effectiveTemplateBindings.map(x=>x.bindingId),["base","child"]);const projected=projectProfileBindings(c.value,"child");assert(projected.ok);assert.deepEqual(projected.value,[{variableId:"name",valueType:"STRING",value:"demo"}]);assert(Object.isFrozen(c.value));});

test("parent mismatch, direct cycle and transitive cycle fail",()=>{const p=base("p");const pv=validateProfile(p);assert(pv.ok);const bad=base("c",{parentProfile:{profileId:"p",profileVersion:"1.0.0",profileSemanticDigest:"fnv1a64-v1:0000000000000000"}});const r=createProfileRegistry([p,bad]);assert(r.ok);const c=r.value.get("c");assert(c);assert.equal(composeProfile(c,r.value).error.code,"PROFILE_PARENT_EXPECTATION_MISMATCH");
const self=base("self");const sv=validateProfile(self);assert(sv.ok);const self2=base("self",{parentProfile:{profileId:"self",profileVersion:"1.0.0",profileSemanticDigest:sv.value.nativeProfileSemanticDigest}});const selfv=validateProfile(self2);assert(selfv.ok);const fake=new Map([["self",selfv.value]]);const cyc=composeProfile(selfv.value,fake);assert(!cyc.ok);
});

test("inheritance binding conflicts fail and exact duplicates deduplicate",()=>{const parent=base("parent",{templateBindings:[{bindingId:"x",templateId:"t",templateVersion:"1.0.0",variableBindings:[{variableId:"v",valueType:"STRING",value:"a"}]}]});const pv=validateProfile(parent);assert(pv.ok);const child=base("child",{parentProfile:{profileId:"parent",profileVersion:"1.0.0",profileSemanticDigest:pv.value.nativeProfileSemanticDigest},templateBindings:[{bindingId:"x",templateId:"t",templateVersion:"1.0.0",variableBindings:[{variableId:"v",valueType:"STRING",value:"b"}]}]});let reg=createProfileRegistry([parent,child]);assert(reg.ok);let cs=reg.value.get("child");assert(cs);assert.equal(composeProfile(cs,reg.value).error.code,"PROFILE_INHERITANCE_BINDING_CONFLICT");const child2=base("child2",{parentProfile:{profileId:"parent",profileVersion:"1.0.0",profileSemanticDigest:pv.value.nativeProfileSemanticDigest},templateBindings:parent.templateBindings});reg=createProfileRegistry([parent,child2]);assert(reg.ok);cs=reg.value.get("child2");assert(cs);const composed=composeProfile(cs,reg.value);assert(composed.ok);assert.equal(composed.value.effectiveTemplateBindings.length,1);});

test("depth and cancellation budgets fail typed",()=>{const p=validateProfile(base("p"));assert(p.ok);const c0=base("c",{parentProfile:{profileId:"p",profileVersion:"1.0.0",profileSemanticDigest:p.value.nativeProfileSemanticDigest}});const reg=createProfileRegistry([base("p"),c0]);assert(reg.ok);const c=reg.value.get("c");assert(c);const depth=composeProfile(c,reg.value,{budgets:{maxDepth:0}});assert(!depth.ok);assert.equal(depth.error.code,"PROFILE_INHERITANCE_DEPTH_EXCEEDED");const ac=new AbortController();ac.abort();assert.equal(validateProfile(base("cancelled"),{signal:ac.signal}).error.code,"PROFILE_CANCELLED");});

test("native digest changes on semantic parent binding but not operational provenance",()=>{const a=base("x");const b=base("x",{displayMetadata:{source:"elsewhere"}});assert.equal(profileSemanticDigest(a),profileSemanticDigest(b));});
