import test from "node:test";
import assert from "node:assert/strict";
import {
  DECISION_SYSTEM_SCHEMA_VERSION, validateDecisionLedger, assertValidDecisionLedger,
  decisionLedgerIndex, decisionCapsule, decisionIdentitySealInput, adrIntegrityEnvelope, adrDeltaLens,
  validateDecisionLineage, supersessionClosure, effectiveDecision, decisionConflicts, decisionShadowSet,
  conflictIsolation, decisionFreezeCandidate, decisionStalenessVector, frozenSnapshotGuard, frozenDecisionReceiptSeed
} from "../packages/decision-system/dist/public.js";

const d1={decisionId:"D1",domain:"ARCHITECTURE",subjectKey:"storage",statement:"Use files",rationale:"baseline",owner:"architecture",status:"SUPERSEDED",sourceRefs:[{id:"arch",fingerprint:"a"}],adrIds:["ADR1"],supersedesDecisionIds:[],consequences:["simple"]};
const d2={decisionId:"D2",domain:"ARCHITECTURE",subjectKey:"storage",statement:"Use files plus derived index",rationale:"lookup",owner:"architecture",status:"FROZEN",sourceRefs:[{id:"arch",fingerprint:"b"}],adrIds:["ADR2"],supersedesDecisionIds:["D1"],consequences:["derived-not-canonical"]};
const a1={adrId:"ADR1",title:"Initial storage",status:"SUPERSEDED",context:"baseline",decision:"files",consequences:["simple"],decisionIds:["D1"],sourceRefs:[],supersedesAdrIds:[],supersededByAdrIds:["ADR2"]};
const a2={adrId:"ADR2",title:"Derived index",status:"ACCEPTED",context:"lookup",decision:"derived index",consequences:["rebuildable"],decisionIds:["D2"],sourceRefs:[],supersedesAdrIds:["ADR1"],supersededByAdrIds:[]};
function ledger(overrides={}){return {schemaVersion:DECISION_SYSTEM_SCHEMA_VERSION,ledgerId:"gef-decisions",decisions:[structuredClone(d1),structuredClone(d2)],adrs:[structuredClone(a1),structuredClone(a2)],lineageCoverage:"COMPLETE",...overrides};}

test("valid decision ledger produces immutable snapshot",()=>{const l=assertValidDecisionLedger(ledger());assert.equal(Object.isFrozen(l),true);assert.equal(validateDecisionLedger(l).ok,true);});
test("unsupported schema and prototype-hostile IDs fail closed",()=>{const x=ledger();x.schemaVersion="9";x.decisions[0].decisionId="__proto__";const r=validateDecisionLedger(x);assert.equal(r.ok,false);assert.ok(r.diagnostics.some(d=>d.code==="UNSUPPORTED_SCHEMA_VERSION"));assert.ok(r.diagnostics.some(d=>d.code==="DUPLICATE_OR_INVALID_DECISION_ID"));});
test("bidirectional ADR mismatch is diagnosed",()=>{const x=ledger();x.adrs[1].decisionIds=[];const r=validateDecisionLedger(x);assert.equal(r.ok,false);assert.ok(r.diagnostics.some(d=>d.code==="ADR_LINK_MISMATCH"));});
test("cross-subject supersession fails",()=>{const x=ledger();x.decisions[0].subjectKey="other";const r=validateDecisionLedger(x);assert.equal(r.ok,false);assert.ok(r.diagnostics.some(d=>d.code==="SUBJECT_MISMATCH_SUPERSESSION"));});
test("ledger index and decision digest projections are deterministic",()=>{const l=assertValidDecisionLedger(ledger());assert.equal(decisionLedgerIndex(l).length,1);assert.equal(decisionCapsule(l,"D2").decisionId,"D2");assert.equal(decisionIdentitySealInput(l,"D2"),decisionIdentitySealInput(l,"D2"));});
test("ADR envelope and delta lens expose semantic changes",()=>{const l=assertValidDecisionLedger(ledger());assert.equal(adrIntegrityEnvelope(l,"ADR2").decisionIds[0],"D2");const changed={...a2,decision:"different"};assert.equal(adrDeltaLens(a2,changed).decisionChanged,true);});
test("explicit supersession lineage resolves current frozen leaf without recency",()=>{const l=assertValidDecisionLedger(ledger());assert.equal(validateDecisionLineage(l).ok,true);assert.deepEqual(supersessionClosure(l,"D2").decisionIds,["D1"]);const r=effectiveDecision(l,"ARCHITECTURE","storage");assert.equal(r.status,"RESOLVED");assert.equal(r.decisionId,"D2");});
test("lineage cycles fail closed",()=>{const x=ledger();x.decisions[0].supersedesDecisionIds=["D2"];x.decisions[0].status="FROZEN";const l={...x};const r=validateDecisionLineage(l);assert.equal(r.ok,false);assert.equal(r.code,"LINEAGE_CYCLE");});
test("parallel frozen leaves are conflicts and no winner is selected",()=>{const x=ledger();x.decisions.push({...structuredClone(d2),decisionId:"D3",adrIds:[],supersedesDecisionIds:[]});x.adrs=x.adrs.filter(a=>a.adrId!=="ADR2");x.decisions[1].adrIds=[];const l=assertValidDecisionLedger(x);const r=effectiveDecision(l,"ARCHITECTURE","storage");assert.equal(r.status,"CONFLICT");assert.deepEqual(r.decisionIds,["D2","D3"]);assert.equal(decisionConflicts(l).length,1);});
test("incomplete lineage coverage yields UNKNOWN and conservative isolation",()=>{const l=assertValidDecisionLedger(ledger({lineageCoverage:"INCOMPLETE"}));assert.equal(effectiveDecision(l,"ARCHITECTURE","storage").status,"UNKNOWN");assert.equal(supersessionClosure(l,"D2").status,"UNKNOWN_COVERAGE");assert.equal(conflictIsolation(l,"ARCHITECTURE","storage").status,"CONSERVATIVE_WIDENING_REQUIRED");});
test("shadow set exposes superseded history",()=>{const l=assertValidDecisionLedger(ledger());assert.deepEqual(decisionShadowSet(l,"ARCHITECTURE","storage"),["D1"]);});
test("freeze candidate and receipt have decision-only authority",()=>{const l=assertValidDecisionLedger(ledger());assert.equal(decisionFreezeCandidate(l,"D2").ready,true);const r=frozenDecisionReceiptSeed(l,"D2");assert.equal(r.authorityNotice,"DECISION_ELIGIBILITY_ONLY");assert.equal(r.freezeReadiness,"READY_CANDIDATE");assert.equal("moduleDone" in r,false);});
test("staleness vector is narrow with complete coverage",()=>{const l=assertValidDecisionLedger(ledger());const r=decisionStalenessVector(l,"arch");assert.deepEqual(r.affectedDecisionIds,["D1","D2"]);assert.equal(r.status,"EXACT");});
test("frozen snapshot guard rejects semantic in-place mutation",()=>{const before={...structuredClone(d2),status:"FROZEN"};const after={...structuredClone(before),statement:"mutated"};assert.equal(frozenSnapshotGuard(before,after).valid,false);assert.equal(frozenSnapshotGuard(before,structuredClone(before)).valid,true);});
test("lineage traversal budget and cancellation are explicit",()=>{const l=assertValidDecisionLedger(ledger());assert.equal(validateDecisionLineage(l,{maxNodes:1}).code,"BUDGET_EXCEEDED");assert.equal(validateDecisionLineage(l,{isCancelled:()=>true}).code,"CANCELLED");});
