import test from "node:test";
import assert from "node:assert/strict";
import {
  SCOPE_DOD_ENGINE_SCHEMA_VERSION, validateWorkCandidate, classifyWorkCandidate, admissionForClassification,
  reclassificationDelta, validateDodCriteria, evaluateDefinitionOfDone, detectDodCriterionDrift,
  createScopeSnapshot, scopeSnapshotSealInput, detectScopeDrift
} from "../packages/scope-dod-engine/dist/public.js";

const ref=(id="scope",kind="SCOPE")=>({id,kind,fingerprint:`${id}-v1`});
const evidence=(overrides={})=>({requiredByCurrentScope:false,requiredByCurrentDod:false,requiredByCurrentRequirement:false,requiredByFrozenArchitecture:false,requiredByAcceptedDecision:false,valuableButNonBlocking:false,scheduledForLater:false,conflictsWithScope:false,ownershipBoundaryConflict:false,sourceRefs:[],...overrides});
const candidate=(overrides={})=>({schemaVersion:SCOPE_DOD_ENGINE_SCHEMA_VERSION,candidateId:"C1",title:"Candidate",rationale:"governed",evidence:evidence(),...overrides});
const criterion=(overrides={})=>({criterionId:"D1",required:true,applicable:true,status:"SATISFIED",sourceRefs:[ref("dod","DOD")],evidenceRefs:["EV1"],...overrides});
const snapshot=(id,items)=>({schemaVersion:SCOPE_DOD_ENGINE_SCHEMA_VERSION,snapshotId:id,sourceRefs:[ref()],items});

test("candidate validator rejects unsupported schema and hostile IDs",()=>{const x=candidate({schemaVersion:"9",candidateId:"__proto__"});const r=validateWorkCandidate(x);assert.equal(r.ok,false);assert.ok(r.diagnostics.some(d=>d.code==="UNSUPPORTED_SCHEMA_VERSION"));assert.ok(r.diagnostics.some(d=>d.code==="INVALID_CANDIDATE_ID"));});
test("current canonical obligation classifies NECESSARY only with authority",()=>{const x=candidate({evidence:evidence({requiredByCurrentDod:true,sourceRefs:[ref("dod","DOD")]})});const r=classifyWorkCandidate(x);assert.equal(r.status,"CLASSIFIED");assert.equal(r.classification,"NECESSARY");assert.equal(Object.isFrozen(r),true);});
test("required candidate without authority fails closed",()=>{const x=candidate({evidence:evidence({requiredByCurrentScope:true})});const r=classifyWorkCandidate(x);assert.equal(r.status,"UNRESOLVED");assert.ok(r.diagnostics.some(d=>d.code==="MISSING_NECESSARY_AUTHORITY"));});
test("required plus forbidden evidence never guesses a winner",()=>{const x=candidate({evidence:evidence({requiredByCurrentScope:true,conflictsWithScope:true,sourceRefs:[ref()]})});const r=classifyWorkCandidate(x);assert.equal(r.status,"UNRESOLVED");assert.equal(r.diagnostics[0].code,"AUTHORITY_CONFLICT");});
test("important future and out of scope classifications stay distinct",()=>{assert.equal(classifyWorkCandidate(candidate({evidence:evidence({valuableButNonBlocking:true})})).classification,"IMPORTANT");assert.equal(classifyWorkCandidate(candidate({evidence:evidence({scheduledForLater:true})})).classification,"FUTURE");assert.equal(classifyWorkCandidate(candidate({evidence:evidence({ownershipBoundaryConflict:true,sourceRefs:[ref()]})})).classification,"OUT_OF_SCOPE");});
test("only NECESSARY is automatically admission eligible",()=>{assert.equal(admissionForClassification("NECESSARY"),"AUTO_ADMIT_ELIGIBLE");assert.equal(admissionForClassification("IMPORTANT"),"HOLD_FOR_EXPLICIT_APPROVAL");assert.equal(admissionForClassification("FUTURE"),"DEFER_TO_FUTURE_OWNER");assert.equal(admissionForClassification("OUT_OF_SCOPE"),"REJECT_CURRENT_SCOPE");});
test("reclassification delta exposes expansion and erosion",()=>{assert.equal(reclassificationDelta("IMPORTANT","NECESSARY").scopeExpansion,true);assert.equal(reclassificationDelta("NECESSARY","FUTURE").necessaryErosion,true);assert.equal(reclassificationDelta("IMPORTANT","IMPORTANT").explicitGovernanceRequired,false);});
test("required DoD criterion needs evidence",()=>{const bad=[criterion({evidenceRefs:[]})];const v=validateDodCriteria(bad);assert.equal(v.ok,false);assert.ok(v.diagnostics.some(d=>d.code==="MISSING_REQUIRED_EVIDENCE"));assert.equal(evaluateDefinitionOfDone(bad).complete,false);});
test("DoD evaluator completes only required applicable satisfied evidence-bound criteria",()=>{const r=evaluateDefinitionOfDone([criterion(),criterion({criterionId:"D2",required:false,status:"UNSATISFIED",evidenceRefs:[]})]);assert.equal(r.complete,true);assert.equal(r.requiredApplicableCount,1);assert.equal(r.satisfiedRequiredCount,1);assert.equal(r.authorityNotice,"DOD_EVALUATION_ONLY");});
test("DoD blocked and invalid applicability states fail closed",()=>{assert.equal(evaluateDefinitionOfDone([criterion({status:"BLOCKED",evidenceRefs:[]})]).complete,false);const invalid=[criterion({applicable:false,status:"SATISFIED",evidenceRefs:[],nonApplicableRationale:"not used"})];assert.equal(validateDodCriteria(invalid).ok,false);});
test("explicit NOT_APPLICABLE requires rationale and remains visible",()=>{const valid=[criterion({applicable:false,status:"NOT_APPLICABLE",evidenceRefs:[],nonApplicableRationale:"platform does not expose feature"})];assert.equal(validateDodCriteria(valid).ok,true);assert.equal(evaluateDefinitionOfDone(valid).complete,true);const invalid=[criterion({applicable:false,status:"NOT_APPLICABLE",evidenceRefs:[]})];assert.equal(validateDodCriteria(invalid).ok,false);});
test("duplicate DoD criteria fail closed",()=>{const x=[criterion(),criterion()];const r=validateDodCriteria(x);assert.equal(r.ok,false);assert.ok(r.diagnostics.some(d=>d.code==="DUPLICATE_OR_INVALID_DOD_ID"));});
test("DoD criterion drift detects denominator erosion and new obligations",()=>{const base=[criterion(),criterion({criterionId:"D2",required:false,status:"UNSATISFIED",evidenceRefs:[]})];const next=[criterion({criterionId:"D2",required:true})];const r=detectDodCriterionDrift(base,next);assert.equal(r.blocking,true);assert.ok(r.findings.some(f=>f.kind==="REMOVED"&&f.criterionId==="D1"));assert.ok(r.findings.some(f=>f.kind==="REQUIRED_CHANGED"&&f.criterionId==="D2"));});
test("scope snapshot is stable sorted immutable and seal-ready",()=>{const s=createScopeSnapshot(snapshot("S1",[{itemId:"B",classification:"IMPORTANT",authorizationRefs:[]},{itemId:"A",classification:"NECESSARY",authorizationRefs:[ref()]}]));assert.deepEqual(s.items.map(x=>x.itemId),["A","B"]);assert.equal(Object.isFrozen(s.items),true);assert.equal(scopeSnapshotSealInput(s),scopeSnapshotSealInput(s));});
test("unauthorized scope addition and required removal are blocking",()=>{const base=snapshot("BASE",[{itemId:"A",classification:"NECESSARY",authorizationRefs:[ref()]}]);const next=snapshot("NEXT",[{itemId:"B",classification:"IMPORTANT",authorizationRefs:[]}]);const r=detectScopeDrift(base,next);assert.equal(r.blocking,true);assert.ok(r.findings.some(f=>f.code==="REQUIRED_SCOPE_REMOVAL"));assert.ok(r.findings.some(f=>f.code==="UNAUTHORIZED_EXPANSION"));});
test("unauthorized upclassification and necessary downclassification are blocking",()=>{const base=snapshot("BASE",[{itemId:"A",classification:"IMPORTANT",authorizationRefs:[]},{itemId:"B",classification:"NECESSARY",authorizationRefs:[ref()]}]);const next=snapshot("NEXT",[{itemId:"A",classification:"NECESSARY",authorizationRefs:[]},{itemId:"B",classification:"FUTURE",authorizationRefs:[]}]);const r=detectScopeDrift(base,next);assert.ok(r.findings.some(f=>f.code==="UNAUTHORIZED_UPCLASSIFICATION"));assert.ok(r.findings.some(f=>f.code==="REQUIRED_DOWNCLASSIFICATION"));});
test("authorized changes stay visible and nonblocking",()=>{const base=snapshot("BASE",[{itemId:"A",classification:"IMPORTANT",authorizationRefs:[]}]);const next=snapshot("NEXT",[{itemId:"A",classification:"NECESSARY",authorizationRefs:[ref("ADR-1","DECISION")]},{itemId:"B",classification:"IMPORTANT",authorizationRefs:[ref("ADR-2","DECISION")]}]);const r=detectScopeDrift(base,next);assert.equal(r.blocking,false);assert.ok(r.findings.some(f=>f.code==="AUTHORIZED_RECLASSIFICATION"));assert.ok(r.findings.some(f=>f.code==="AUTHORIZED_ADDITION"));});
test("OUT_OF_SCOPE presence is blocking even when explicitly recorded",()=>{const base=snapshot("BASE",[]);const next=snapshot("NEXT",[{itemId:"X",classification:"OUT_OF_SCOPE",authorizationRefs:[ref("scope","SCOPE")]}]);const r=detectScopeDrift(base,next);assert.equal(r.blocking,true);assert.equal(r.findings[0].code,"OUT_OF_SCOPE_PRESENCE");assert.equal(r.authorityNotice,"DETECTION_ONLY");});
