import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {buildBootstrapSeedGraph,reconcileBrownfieldTruth,validateLegacyCompatibilityMembrane,validateCompatibilityBridge,planAdoptionSlice,buildProgressiveGovernanceEnvelope,buildGovernanceMaturityVector,buildAdoptionReceipt,evaluateReceiptValidity,detectAdoptionRegression,buildGovernanceDeltaReceipt,buildAdoptionProofSpine,computeProofInvalidation,evaluateDestructivePromotion} from '../packages/adoption-engine/dist/public.js';
const digest={algorithm:'sha256',digest:v=>createHash('sha256').update(v).digest('hex')};const opts={digest};
const seed=(id,x={})=>({id,semanticClass:id.toUpperCase(),sourceOwner:'M09',creationMode:'CREATE_FROM_EXPLICIT_INPUT',profileIdentity:'generic',profileDigest:'sha256:p',mutationOwner:'M05',postconditionChecks:['exists'],...x});
const vm=s=>buildGovernanceMaturityVector('proj-1',s,opts).value;
const baseReceipt=(m=vm([{domain:'SCOPE',maturity:'GOVERNED_CANONICAL'}]),x={})=>({projectId:'proj-1',policyVersion:'m13-v1',mode:'BROWNFIELD_INCREMENTAL',intentCapsuleIdentity:'i',sourcePackIdentity:'s',profileIdentity:'generic',profileDigest:'p',maturityVectorIdentity:m.semanticIdentity,maturityVector:m,normalizationFrontier:{projectId:'proj-1',domains:[{domain:'SCOPE',state:'GEF_CANONICAL'}]},bridgeIds:['b1'],membraneIds:[],sourceFingerprints:[{id:'b1',fingerprint:'f1'}],driftSummary:[],quarantineSummary:[],completedIncrementIds:['inc1'],blockers:[],safetyEnvelopeIdentity:'ase',capabilityUnlocks:[{capability:'context',unlocked:true,reasons:[]}],governedDomains:['SCOPE'],ungovernedDomains:[],blockedDomains:[],...x});

test('bootstrap graph enforces frozen bindings',()=>{const n=[seed('scope',{dependencies:['constitution']}),seed('constitution')];assert.deepEqual(buildBootstrapSeedGraph(n,opts).value.order,['constitution','scope']);assert.equal(buildBootstrapSeedGraph([seed('x',{mutationOwner:'M13'})],opts).ok,false);assert.equal(buildBootstrapSeedGraph(n,{digest,maxNodes:1}).ok,false);});

test('brownfield truth and compatibility are explicit',()=>{assert.equal(reconcileBrownfieldTruth({domain:'ARCH',observedTruth:{a:1},normativeTruth:{a:2},bindingEvidence:['code'],driftClass:'ARCHITECTURAL_DRIFT'}).value.resolutionState,'UNRESOLVED');assert.equal(reconcileBrownfieldTruth({domain:'SCOPE',observedTruth:'x',bindingEvidence:[]}).ok,false);const alias={id:'m1',legacySourceIdentity:'l',semanticClass:'SCOPE',mappingType:'ALIAS',lossy:false,sourceFingerprint:'f',owner:'M13'};assert.equal(validateLegacyCompatibilityMembrane(alias).ok,false);const bridge={id:'b1',sourceIdentity:'l',targetSemanticClass:'SCOPE',mappingVersion:'1',direction:'READ_ONLY',lossy:true,conflictBehavior:'FAIL',invalidationFingerprint:'f',owner:'M13',reviewTrigger:'fingerprint'};assert.equal(validateCompatibilityBridge(bridge).ok,false);});

test('slice preserves minimum scope and safety binding',()=>{const slice=planAdoptionSlice({targets:['EXEC'],dependencies:[{domain:'EXEC',dependsOn:['SCOPE']}],governedDomains:[],requiredMappings:['legacy-scope'],safetyEnvelopeIdentity:'ase'},opts).value;assert.deepEqual(slice.requiredDomains,['EXEC','SCOPE']);assert.equal(buildProgressiveGovernanceEnvelope({projectId:'proj-1',slice,governedDomains:[],safetyEnvelopeIdentity:'other',requiredChecks:['test'],rollbackPlanRef:'rb'},opts).ok,false);});

test('proof and delta remain bounded/evidence-bound',()=>{const spine=buildAdoptionProofSpine([{id:'r',payloadDigest:'a'},{id:'c',payloadDigest:'b',dependencies:['r']},{id:'o',payloadDigest:'c'}],opts).value;assert.deepEqual(computeProofInvalidation(spine,['r']),['c','r']);assert.deepEqual(computeProofInvalidation(spine,['r'],true),['c','o','r']);const d={projectId:'proj-1',beforeIdentity:'a',afterIdentity:'b',frontierMoved:[],bridgesAdded:[],bridgesRetired:[],driftChanges:[],quarantineChanges:[],capabilitiesUnlocked:[],capabilitiesInvalidated:[],evidenceBindings:[]};assert.equal(buildGovernanceDeltaReceipt(d,opts).ok,false);});

test('receipt and regression sentinel are capability/domain scoped',()=>{const proof=[{id:'i',payloadDigest:'x'}];const prev=buildAdoptionReceipt(baseReceipt(),proof,opts).value;assert.equal(evaluateReceiptValidity(prev,{projectId:'proj-1',sourcePackIdentity:'s',profileIdentity:'generic',profileDigest:'p',policyVersion:'m13-v1',sourceFingerprints:[{id:'b1',fingerprint:'f1'}]}),'VALID');const m=vm([{domain:'SCOPE',maturity:'OBSERVED'}]);const cur=buildAdoptionReceipt(baseReceipt(m,{normalizationFrontier:{projectId:'proj-1',domains:[{domain:'SCOPE',state:'DUAL_BOUND'}]},sourceFingerprints:[{id:'b1',fingerprint:'f2'}],governedDomains:[],ungovernedDomains:['SCOPE'],capabilityUnlocks:[{capability:'context',unlocked:false,reasons:['SCOPE']}],driftSummary:[{domain:'SCOPE',driftClass:'CONFLICTING_INTENT',severity:'HIGH'}]}),proof,opts).value;const codes=new Set(detectAdoptionRegression(prev,cur).map(x=>x.code));for(const c of ['CANONICAL_DOMAIN_REGRESSION','GOVERNANCE_MATURITY_DOWNGRADE','GOVERNANCE_DOMAIN_REGRESSION','CAPABILITY_REGRESSION','LEGACY_BINDING_STALE','LEGACY_AUTHORITY_CONFLICT_REGRESSION'])assert.ok(codes.has(c));assert.equal(evaluateDestructivePromotion('IRREVERSIBILITY_UNKNOWN').ok,false);});