import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {createAdoptionIntentCapsule,validateAdoptionTransition,buildGovernanceMaturityVector,validateAdoptionSafetyEnvelope,assessNewProject,buildBootstrapSeedGraph,evaluateMinimalGovernanceKernel,reconcileBrownfieldTruth,validateLegacyCompatibilityMembrane,validateCompatibilityBridge,validateDriftResolution,planAdoptionSlice,createLegacyDebtRecord,validateNormalizationTransition,buildNormalizationFrontier,probeSemanticEquivalence,enforceNormalizationBudget,classifyReversibility,evaluateCapabilityUnlock,buildAdoptionProofSpine,computeProofInvalidation,buildGovernanceDeltaReceipt,buildAdoptionReceipt,evaluateReceiptValidity,detectAdoptionRegression,projectBootstrapProvenance} from '../packages/adoption-engine/dist/public.js';
const digest={algorithm:'sha256',digest(input){return createHash('sha256').update(input).digest('hex')}};const opts={digest};
const baseIntent={projectId:'proj-1',mode:'BROWNFIELD_INCREMENTAL',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',policyVersion:'m13-v1',requestedDomains:['SCOPE','DECISION'],excludedDomains:['UI'],riskClass:'ELEVATED'};

test('intent capsule is deterministic set-order invariant and rejects runtime enum forgery',()=>{const a=createAdoptionIntentCapsule(baseIntent,opts);const b=createAdoptionIntentCapsule({...baseIntent,requestedDomains:['DECISION','SCOPE']},opts);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(a.value.semanticIdentity,b.value.semanticIdentity);assert.ok(Object.isFrozen(a.value));const forged=createAdoptionIntentCapsule({...baseIntent,mode:'LATEST_MAGIC'},opts);assert.equal(forged.ok,false);assert.equal(forged.diagnostics[0].code,'ADOPTION_MODE_UNSUPPORTED');});
test('governed migration requires decision and overlapping domains fail',()=>{const m=createAdoptionIntentCapsule({...baseIntent,mode:'BROWNFIELD_GOVERNED_MIGRATION'},opts);assert.equal(m.ok,false);assert.equal(m.diagnostics[0].code,'REQUIRED_DECISION_MISSING');const o=createAdoptionIntentCapsule({...baseIntent,excludedDomains:['SCOPE']},opts);assert.equal(o.ok,false);assert.equal(o.diagnostics[0].code,'ADOPTION_DOMAIN_CONFLICT');});
test('adoption transitions fail closed',()=>{assert.equal(validateAdoptionTransition('UNASSESSED','OBSERVED').ok,true);const r=validateAdoptionTransition('UNASSESSED','GOVERNED');assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'UNSUPPORTED_GOVERNANCE_TRANSITION');});
test('maturity vector deterministic and rejects duplicate or forged states',()=>{const a=buildGovernanceMaturityVector('proj-1',[{domain:'SCOPE',maturity:'GOVERNED_CANONICAL'},{domain:'DECISION',maturity:'MAPPED'}],opts);const b=buildGovernanceMaturityVector('proj-1',[{domain:'DECISION',maturity:'MAPPED'},{domain:'SCOPE',maturity:'GOVERNED_CANONICAL'}],opts);assert.equal(a.value.semanticIdentity,b.value.semanticIdentity);assert.equal(buildGovernanceMaturityVector('proj-1',[{domain:'SCOPE',maturity:'OBSERVED'},{domain:'SCOPE',maturity:'MAPPED'}],opts).ok,false);assert.equal(buildGovernanceMaturityVector('proj-1',[{domain:'X',maturity:'MAGIC'}],opts).diagnostics[0].code,'GOVERNANCE_MATURITY_UNSUPPORTED');});
test('safety envelope detects contradictory surfaces',()=>{const r=validateAdoptionSafetyEnvelope({allowedMutationSurfaces:['docs'],forbiddenSurfaces:['docs'],reversibleOperations:[],preconditions:[],requiredChecks:[],abortConditions:[],rollbackOwner:'M05',maxUnresolvedSeverity:'MEDIUM'});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'MUTATION_SURFACE_CONFLICT');});
test('new project assessment never infers newness from sparsity',()=>{assert.equal(assessNewProject({explicitNewProjectIntent:true,conflictingCanonicalSystem:false,retainedHistory:false,existingReleaseEvidence:false,remoteProjectEvidence:false}),'TRUE_NEW');assert.equal(assessNewProject({explicitNewProjectIntent:false,conflictingCanonicalSystem:false,retainedHistory:false,existingReleaseEvidence:false,remoteProjectEvidence:false}),'NEWNESS_UNCERTAIN');assert.equal(assessNewProject({explicitNewProjectIntent:true,conflictingCanonicalSystem:false,retainedHistory:true,existingReleaseEvidence:false,remoteProjectEvidence:false}),'NEWNESS_UNCERTAIN');});
test('seed graph deterministic cycle-safe bounded cancellable',()=>{const nodes=[{id:'scope',semanticClass:'SCOPE',creationMode:'CREATE_FROM_EXPLICIT_INPUT',dependencies:['constitution']},{id:'constitution',semanticClass:'CONSTITUTION_GOVERNANCE',creationMode:'CREATE_FROM_EXPLICIT_INPUT'}];const a=buildBootstrapSeedGraph(nodes,opts),b=buildBootstrapSeedGraph([...nodes].reverse(),opts);assert.equal(a.ok,true);assert.deepEqual(a.value.order,b.value.order);assert.deepEqual(a.value.order,['constitution','scope']);const cyc=buildBootstrapSeedGraph([{id:'a',semanticClass:'A',creationMode:'CREATE_FROM_EXPLICIT_INPUT',dependencies:['b']},{id:'b',semanticClass:'B',creationMode:'CREATE_FROM_EXPLICIT_INPUT',dependencies:['a']}],opts);assert.equal(cyc.diagnostics[0].code,'SEED_GRAPH_CYCLE');assert.equal(buildBootstrapSeedGraph(nodes,{digest,maxNodes:1}).diagnostics[0].code,'NODE_BUDGET_EXCEEDED');assert.equal(buildBootstrapSeedGraph(nodes,{digest,cancellation:{isCancelled(){return true}}}).diagnostics[0].code,'CANCELLED');});
test('minimal governance kernel exposes incompleteness',()=>{const p=evaluateMinimalGovernanceKernel(['PROJECT_IDENTITY','CONSTITUTION_GOVERNANCE']);assert.equal(p.complete,false);assert.ok(p.missing.includes('DECISIONS'));assert.equal(evaluateMinimalGovernanceKernel(['PROJECT_IDENTITY','CONSTITUTION_GOVERNANCE','CURRENT_CHECKPOINT','DECISIONS','SCOPE','COMPLETION_DEFINITION','EXECUTION_GOVERNANCE']).complete,true);});
test('brownfield reconciler preserves truths and refuses guessed drift classification',()=>{const pair=reconcileBrownfieldTruth({domain:'ARCHITECTURE',observed:{runtime:'legacy'},normative:{runtime:'target'},driftClass:'ARCHITECTURAL_DRIFT',evidenceRefs:['code','architecture']});assert.equal(pair.ok,true);assert.equal(pair.value.driftClass,'ARCHITECTURAL_DRIFT');assert.deepEqual(pair.value.observed,{runtime:'legacy'});const unknown=reconcileBrownfieldTruth({domain:'SCOPE',observed:'x',evidenceRefs:[]});assert.equal(unknown.value.driftClass,'INTENT_UNKNOWN');const guessed=reconcileBrownfieldTruth({domain:'SCOPE',observed:{a:1},normative:{a:2}});assert.equal(guessed.ok,false);assert.equal(guessed.diagnostics[0].code,'BROWNFIELD_DRIFT_CLASS_REQUIRED');const equivalent=reconcileBrownfieldTruth({domain:'SCOPE',observed:{a:1,b:2},normative:{b:2,a:1}});assert.equal(equivalent.value.driftClass,'DRIFT_NONE');});
test('lossy mappings and bridges require approval',()=>{const m={id:'m1',legacySourceIdentity:'legacy',semanticClass:'SCOPE',mappingType:'ALIAS',lossy:true,sourceFingerprint:'fp',owner:'M13'};assert.equal(validateLegacyCompatibilityMembrane(m).diagnostics[0].code,'LOSSY_MAPPING_UNAPPROVED');assert.equal(validateLegacyCompatibilityMembrane({...m,approvalRef:'D-1'}).ok,true);const b={id:'b1',sourceIdentity:'legacy',targetSemanticClass:'SCOPE',mappingVersion:'1',direction:'READ_ONLY',lossy:true,conflictBehavior:'FAIL',invalidationFingerprint:'fp',owner:'M13'};assert.equal(validateCompatibilityBridge(b).ok,false);assert.equal(validateCompatibilityBridge({...b,approvalRef:'D-1'}).ok,true);});
test('intent-changing drift resolution requires decision authority',()=>{assert.equal(validateDriftResolution('DEFER_QUARANTINED').ok,true);assert.equal(validateDriftResolution('ACCEPT_OBSERVED_AS_NORMATIVE').diagnostics[0].code,'DRIFT_RESOLUTION_DECISION_REQUIRED');});
test('adoption slice computes only dependency closure',()=>{const r=planAdoptionSlice({targets:['EXECUTION'],dependencies:[{domain:'EXECUTION',dependsOn:['SCOPE','DECISION']},{domain:'SCOPE',dependsOn:['IDENTITY']}],governedDomains:['IDENTITY'],optionalCleanup:['rename-old-folder']},opts);assert.deepEqual(r.value.requiredDomains,['DECISION','EXECUTION','SCOPE']);assert.deepEqual(r.value.optionalCleanup,['rename-old-folder']);});
test('legacy debt remains visible',()=>{const r=createLegacyDebtRecord({id:'debt1',domain:'CI',sourceBinding:'legacy-ci',driftClass:'GOVERNANCE_DRIFT',severity:'HIGH',reason:'outside current slice',affectedCapabilities:['release'],promotionBlocker:true});assert.equal(r.value.promotionBlocker,true);});
test('normalization frontier and semantic equivalence fail closed',()=>{assert.equal(validateNormalizationTransition('LEGACY_UNMAPPED','LEGACY_MAPPED').ok,true);assert.equal(validateNormalizationTransition('LEGACY_UNMAPPED','GEF_CANONICAL').ok,false);assert.equal(buildNormalizationFrontier('proj-1',[{domain:'SCOPE',state:'DUAL_BOUND'},{domain:'DECISION',state:'GEF_CANONICAL'}]).ok,true);assert.equal(probeSemanticEquivalence({a:{x:1,y:2}},{a:{y:2,x:1}},['a']),'EQUIVALENT');assert.equal(probeSemanticEquivalence({a:1},{a:2},['a']),'NON_EQUIVALENT');assert.equal(probeSemanticEquivalence({a:1},{},['a']),'INDETERMINATE');assert.equal(probeSemanticEquivalence({a:1},{a:1},['a'],false),'UNSUPPORTED_MAPPING');});
test('normalization budget and reversibility explicit',()=>{assert.equal(enforceNormalizationBudget({domains:2,mappings:2,migrations:0,dependencyExpansion:1},{maxDomains:1,maxMappings:3,maxMigrations:1,maxDependencyExpansion:2}).diagnostics[0].code,'NORMALIZATION_BUDGET_EXCEEDED');assert.equal(classifyReversibility('UNKNOWN'),'IRREVERSIBILITY_UNKNOWN');});
test('capability unlock domain-scoped and partial stays partial',()=>{const v=buildGovernanceMaturityVector('proj-1',[{domain:'SCOPE',maturity:'GOVERNED_CANONICAL'},{domain:'DECISION',maturity:'MAPPED'}],opts).value;assert.equal(evaluateCapabilityUnlock({capability:'context',domains:[{domain:'SCOPE',minimum:'MAPPED'}]},v).unlocked,true);assert.equal(evaluateCapabilityUnlock({capability:'execution',domains:[{domain:'DECISION',minimum:'GOVERNED_CANONICAL'}]},v).unlocked,false);});
test('proof spine deterministic with selective and conservative invalidation',()=>{const nodes=[{id:'root',payloadDigest:'sha256:a'},{id:'child',payloadDigest:'sha256:b',dependencies:['root']},{id:'other',payloadDigest:'sha256:c'}];const s=buildAdoptionProofSpine(nodes,opts);assert.equal(s.ok,true);assert.deepEqual(computeProofInvalidation(s.value,['root']),['child','root']);assert.deepEqual(computeProofInvalidation(s.value,['root'],true),['child','other','root']);});
test('governance delta and provenance deterministic',()=>{const input={projectId:'proj-1',beforeIdentity:'a',afterIdentity:'b',frontierMoved:['SCOPE'],bridgesAdded:['x'],bridgesRetired:[],driftChanges:[],quarantineChanges:[],capabilitiesUnlocked:['context'],capabilitiesInvalidated:[]};assert.equal(buildGovernanceDeltaReceipt(input,opts).value.semanticIdentity,buildGovernanceDeltaReceipt({...input,frontierMoved:[...input.frontierMoved].reverse()},opts).value.semanticIdentity);assert.match(projectBootstrapProvenance({artifactId:'scope',sourceRefs:['b','a'],semanticOwner:'M13',payloadIdentity:'sha256:x',validationState:'VALID'},opts).value.generatedDigest,/^sha256:/);});
function receiptInput(capabilityUnlocks=[{capability:'context',unlocked:true,reasons:[]}]){return {projectId:'proj-1',policyVersion:'m13-v1',mode:'BROWNFIELD_INCREMENTAL',intentCapsuleIdentity:'sha256:intent',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',maturityVectorIdentity:'sha256:gmv',normalizationFrontier:{projectId:'proj-1',domains:[{domain:'SCOPE',state:'GEF_CANONICAL'}]},bridgeIds:[],membraneIds:[],driftSummary:[],quarantineIds:[],completedIncrementIds:['inc1'],blockers:[],safetyEnvelopeIdentity:'sha256:ase',capabilityUnlocks};}
const currentBindings={projectId:'proj-1',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',policyVersion:'m13-v1'};
test('adoption receipt deterministic and partial never full',()=>{const proof=[{id:'intent',payloadDigest:'sha256:intent'}];const valid=buildAdoptionReceipt(receiptInput(),proof,opts);assert.equal(valid.value.validity,'VALID');const partial=buildAdoptionReceipt(receiptInput([{capability:'context',unlocked:false,reasons:['SCOPE:MISSING']}]),proof,opts);assert.equal(partial.value.validity,'PARTIAL');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,projectId:'other'}),'PROJECT_MISMATCH');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,sourcePackIdentity:'changed'}),'SOURCE_PACK_MISMATCH');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,profileDigest:'changed'}),'STALE');});
test('receipt rejects secret-like payload and regression sentinel detects loss',()=>{const proof=[{id:'intent',payloadDigest:'sha256:intent'}];const previous=buildAdoptionReceipt(receiptInput(),proof,opts).value;const current=buildAdoptionReceipt({...receiptInput([{capability:'context',unlocked:false,reasons:['blocked']}]),normalizationFrontier:{projectId:'proj-1',domains:[{domain:'SCOPE',state:'DUAL_BOUND'}]}},proof,opts).value;const r=detectAdoptionRegression(previous,current);assert.ok(r.some(x=>x.code==='CANONICAL_DOMAIN_REGRESSION'));assert.ok(r.some(x=>x.code==='CAPABILITY_REGRESSION'));const secret=buildAdoptionReceipt({...receiptInput(),password:'hidden'},proof,opts);assert.equal(secret.ok,false);assert.equal(secret.diagnostics[0].code,'RECEIPT_SECRET_MATERIAL_FORBIDDEN');});
