import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  createAdoptionIntentCapsule, validateAdoptionIntentCapsule, invalidateAdoptionAdmission,
  validateAdoptionTransition, buildGovernanceMaturityVector, validateAdoptionSafetyEnvelope,
  assessNewProject, buildBootstrapSeedGraph, evaluateMinimalGovernanceKernel,
  reconcileBrownfieldTruth, validateLegacyCompatibilityMembrane, validateCompatibilityBridge,
  validateLegacyBindingFreshness, validateDriftResolution, planAdoptionSlice,
  buildProgressiveGovernanceEnvelope, createLegacyDebtRecord, buildLegacyDebtQuarantine,
  validateNormalizationTransition, buildNormalizationFrontier, probeSemanticEquivalence,
  enforceNormalizationBudget, classifyReversibility, evaluateDestructivePromotion,
  evaluateCapabilityUnlock, buildAdoptionProofSpine, computeProofInvalidation,
  buildGovernanceDeltaReceipt, buildAdoptionReceipt, evaluateReceiptValidity,
  detectAdoptionRegression, projectBootstrapProvenance
} from '../packages/adoption-engine/dist/public.js';

const digest={algorithm:'sha256',digest(input){return createHash('sha256').update(input).digest('hex')}};
const opts={digest};
const baseIntent={projectId:'proj-1',mode:'BROWNFIELD_INCREMENTAL',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',policyVersion:'m13-v1',requestedDomains:['SCOPE','DECISION'],excludedDomains:['UI'],riskClass:'ELEVATED'};

test('intent capsule deterministic and mode is explicit/fail-closed',()=>{
  const a=createAdoptionIntentCapsule(baseIntent,opts); const b=createAdoptionIntentCapsule({...baseIntent,requestedDomains:['DECISION','SCOPE']},opts);
  assert.equal(a.ok,true); assert.equal(b.ok,true); assert.equal(a.value.semanticIdentity,b.value.semanticIdentity); assert.ok(Object.isFrozen(a.value));
  assert.equal(createAdoptionIntentCapsule({...baseIntent,mode:undefined},opts).diagnostics[0].code,'ADOPTION_MODE_MISSING');
  assert.equal(createAdoptionIntentCapsule({...baseIntent,mode:'LATEST_MAGIC'},opts).diagnostics[0].code,'ADOPTION_MODE_UNSUPPORTED');
});

test('intent capsule validation rejects exact project/source/profile/policy mismatch and tampering',()=>{
  const capsule=createAdoptionIntentCapsule(baseIntent,opts).value; const current={projectId:'proj-1',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',policyVersion:'m13-v1'};
  assert.equal(validateAdoptionIntentCapsule(capsule,current,opts).ok,true);
  assert.equal(validateAdoptionIntentCapsule(capsule,{...current,projectId:'other'},opts).diagnostics[0].code,'PROJECT_BINDING_MISMATCH');
  assert.equal(validateAdoptionIntentCapsule(capsule,{...current,sourcePackIdentity:'other'},opts).diagnostics[0].code,'SOURCE_PACK_STALE');
  assert.equal(validateAdoptionIntentCapsule(capsule,{...current,profileDigest:'other'},opts).diagnostics[0].code,'PROFILE_BINDING_STALE');
  assert.equal(validateAdoptionIntentCapsule(capsule,{...current,policyVersion:'other'},opts).diagnostics[0].code,'POLICY_VERSION_UNSUPPORTED');
  assert.equal(validateAdoptionIntentCapsule({...capsule,requestedDomains:['TAMPERED']},current,opts).diagnostics[0].code,'ADOPTION_INTENT_INTEGRITY_MISMATCH');
});

test('governed migration requires decision and adoption transitions/invalidation are explicit',()=>{
  assert.equal(createAdoptionIntentCapsule({...baseIntent,mode:'BROWNFIELD_GOVERNED_MIGRATION'},opts).diagnostics[0].code,'REQUIRED_DECISION_MISSING');
  assert.equal(createAdoptionIntentCapsule({...baseIntent,excludedDomains:['SCOPE']},opts).diagnostics[0].code,'ADOPTION_DOMAIN_CONFLICT');
  assert.equal(validateAdoptionTransition('UNASSESSED','OBSERVED').ok,true); assert.equal(validateAdoptionTransition('UNASSESSED','GOVERNED').diagnostics[0].code,'UNSUPPORTED_GOVERNANCE_TRANSITION');
  assert.equal(invalidateAdoptionAdmission('SOURCE_FINGERPRINT_CHANGED').nextState,'OBSERVED'); assert.equal(invalidateAdoptionAdmission('PROJECT_BINDING_CHANGED',true).nextState,'BLOCKED');
});

test('maturity vector deterministic, partial by domain, and rejects forged states',()=>{
  const a=buildGovernanceMaturityVector('proj-1',[{domain:'SCOPE',maturity:'GOVERNED_CANONICAL'},{domain:'DECISION',maturity:'MAPPED'}],opts); const b=buildGovernanceMaturityVector('proj-1',[{domain:'DECISION',maturity:'MAPPED'},{domain:'SCOPE',maturity:'GOVERNED_CANONICAL'}],opts);
  assert.equal(a.value.semanticIdentity,b.value.semanticIdentity); assert.equal(buildGovernanceMaturityVector('proj-1',[{domain:'SCOPE',maturity:'OBSERVED'},{domain:'SCOPE',maturity:'MAPPED'}],opts).ok,false); assert.equal(buildGovernanceMaturityVector('proj-1',[{domain:'X',maturity:'MAGIC'}],opts).diagnostics[0].code,'GOVERNANCE_MATURITY_UNSUPPORTED');
  assert.equal(evaluateCapabilityUnlock({capability:'context',domains:[{domain:'SCOPE',minimum:'MAPPED'}]},a.value).unlocked,true); assert.equal(evaluateCapabilityUnlock({capability:'execution',domains:[{domain:'DECISION',minimum:'GOVERNED_CANONICAL'}]},a.value).unlocked,false);
});

test('safety envelope detects contradictory surfaces',()=>{const r=validateAdoptionSafetyEnvelope({allowedMutationSurfaces:['docs'],forbiddenSurfaces:['docs'],reversibleOperations:[],preconditions:[],requiredChecks:[],abortConditions:[],rollbackOwner:'M05',maxUnresolvedSeverity:'MEDIUM'});assert.equal(r.diagnostics[0].code,'MUTATION_SURFACE_CONFLICT');});

test('new project assessment never infers newness from sparsity',()=>{assert.equal(assessNewProject({explicitNewProjectIntent:true,conflictingCanonicalSystem:false,retainedHistory:false,existingReleaseEvidence:false,remoteProjectEvidence:false}),'TRUE_NEW');assert.equal(assessNewProject({explicitNewProjectIntent:false,conflictingCanonicalSystem:false,retainedHistory:false,existingReleaseEvidence:false,remoteProjectEvidence:false}),'NEWNESS_UNCERTAIN');assert.equal(assessNewProject({explicitNewProjectIntent:true,conflictingCanonicalSystem:false,retainedHistory:true,existingReleaseEvidence:false,remoteProjectEvidence:false}),'NEWNESS_UNCERTAIN');});

test('seed graph deterministic cycle-safe bounded cancellable',()=>{const nodes=[{id:'scope',semanticClass:'SCOPE',creationMode:'CREATE_FROM_EXPLICIT_INPUT',dependencies:['constitution']},{id:'constitution',semanticClass:'CONSTITUTION_GOVERNANCE',creationMode:'CREATE_FROM_EXPLICIT_INPUT'}];const a=buildBootstrapSeedGraph(nodes,opts),b=buildBootstrapSeedGraph([...nodes].reverse(),opts);assert.deepEqual(a.value.order,b.value.order);assert.deepEqual(a.value.order,['constitution','scope']);assert.equal(buildBootstrapSeedGraph([{id:'a',semanticClass:'A',creationMode:'CREATE_FROM_EXPLICIT_INPUT',dependencies:['b']},{id:'b',semanticClass:'B',creationMode:'CREATE_FROM_EXPLICIT_INPUT',dependencies:['a']}],opts).diagnostics[0].code,'SEED_GRAPH_CYCLE');assert.equal(buildBootstrapSeedGraph(nodes,{digest,maxNodes:1}).diagnostics[0].code,'NODE_BUDGET_EXCEEDED');assert.equal(buildBootstrapSeedGraph(nodes,{digest,cancellation:{isCancelled(){return true}}}).diagnostics[0].code,'CANCELLED');});

test('minimal governance kernel exposes incompleteness',()=>{assert.equal(evaluateMinimalGovernanceKernel(['PROJECT_IDENTITY','CONSTITUTION_GOVERNANCE']).complete,false);assert.equal(evaluateMinimalGovernanceKernel(['PROJECT_IDENTITY','CONSTITUTION_GOVERNANCE','CURRENT_CHECKPOINT','DECISIONS','SCOPE','COMPLETION_DEFINITION','EXECUTION_GOVERNANCE']).complete,true);});

test('brownfield truth separates descriptive/normative truth and covers frozen drift classes',()=>{for(const driftClass of ['DOCUMENTATION_DRIFT','IMPLEMENTATION_DRIFT','TEST_DRIFT','GOVERNANCE_DRIFT','ARCHITECTURAL_DRIFT','CONFLICTING_INTENT'])assert.equal(reconcileBrownfieldTruth({domain:'X',observed:{v:1},normative:{v:2},driftClass,evidenceRefs:['norm','obs']}).value.driftClass,driftClass);assert.equal(reconcileBrownfieldTruth({domain:'X',observed:{v:1},normative:{v:1}}).value.driftClass,'DRIFT_NONE');assert.equal(reconcileBrownfieldTruth({domain:'X',observed:{v:1}}).value.driftClass,'INTENT_UNKNOWN');assert.equal(reconcileBrownfieldTruth({domain:'X',observed:{v:1},normative:{v:2},legacyAcceptanceRef:'D-1'}).value.driftClass,'LEGACY_ACCEPTED');assert.equal(reconcileBrownfieldTruth({domain:'X',observed:{v:1},normative:{v:2}}).diagnostics[0].code,'BROWNFIELD_DRIFT_CLASS_REQUIRED');});

test('legacy membranes and bridges require approval, forbid mutation authority and detect staleness',()=>{const m={id:'m1',legacySourceIdentity:'legacy',semanticClass:'SCOPE',mappingType:'ALIAS',lossy:true,sourceFingerprint:'fp',owner:'M13'};assert.equal(validateLegacyCompatibilityMembrane(m).diagnostics[0].code,'LOSSY_MAPPING_UNAPPROVED');assert.equal(validateLegacyCompatibilityMembrane({...m,approvalRef:'D-1'}).value.mutationPermission,'NONE');assert.equal(validateLegacyCompatibilityMembrane({...m,lossy:false,mutationPermission:'WRITE'}).diagnostics[0].code,'LEGACY_MAPPING_MUTATION_FORBIDDEN');const b={id:'b1',sourceIdentity:'legacy',targetSemanticClass:'SCOPE',mappingVersion:'1',direction:'READ_ONLY',lossy:true,conflictBehavior:'FAIL',invalidationFingerprint:'fp',owner:'M13'};assert.equal(validateCompatibilityBridge(b).diagnostics[0].code,'LOSSY_MAPPING_UNAPPROVED');assert.equal(validateCompatibilityBridge({...b,approvalRef:'D-1'}).ok,true);assert.equal(validateLegacyBindingFreshness({kind:'MEMBRANE',id:'m1',expectedFingerprint:'fp',currentFingerprint:'changed'}).diagnostics[0].code,'LEGACY_ALIAS_STALE');assert.equal(validateLegacyBindingFreshness({kind:'BRIDGE',id:'b1',expectedFingerprint:'fp',currentFingerprint:'changed'}).diagnostics[0].code,'COMPATIBILITY_BRIDGE_STALE');});

test('intent-changing drift resolution requires decision authority',()=>{assert.equal(validateDriftResolution('DEFER_QUARANTINED').ok,true);assert.equal(validateDriftResolution('ACCEPT_OBSERVED_AS_NORMATIVE').diagnostics[0].code,'DRIFT_RESOLUTION_DECISION_REQUIRED');});

test('adoption slice only includes dependency closure, enforces graph budgets, and PGE excludes cleanup',()=>{const input={targets:['EXECUTION'],dependencies:[{domain:'EXECUTION',dependsOn:['SCOPE','DECISION']},{domain:'SCOPE',dependsOn:['IDENTITY']}],governedDomains:['IDENTITY'],optionalCleanup:['rename-old-folder']};const slice=planAdoptionSlice(input,opts);assert.deepEqual(slice.value.requiredDomains,['DECISION','EXECUTION','SCOPE']);assert.deepEqual(slice.value.optionalCleanup,['rename-old-folder']);assert.equal(planAdoptionSlice(input,{digest,maxNodes:2}).diagnostics[0].code,'NODE_BUDGET_EXCEEDED');const pge=buildProgressiveGovernanceEnvelope({projectId:'proj-1',slice:slice.value,governedDomains:['IDENTITY'],safetyEnvelopeIdentity:'sha256:ase',requiredChecks:['test','lint'],rollbackPlanRef:'rollback-1'},opts);assert.equal(pge.ok,true);assert.equal('optionalCleanup' in pge.value,false);assert.match(pge.value.semanticIdentity,/^sha256:/);});

test('legacy debt quarantine persists deterministic debt projection',()=>{const record={id:'debt1',domain:'CI',sourceBinding:'legacy-ci',driftClass:'GOVERNANCE_DRIFT',severity:'HIGH',reason:'outside current slice',affectedCapabilities:['release'],promotionBlocker:true,invalidationCondition:'legacy CI retired'};assert.equal(createLegacyDebtRecord(record).value.promotionBlocker,true);const a=buildLegacyDebtQuarantine('proj-1',[record],opts),b=buildLegacyDebtQuarantine('proj-1',[{...record,affectedCapabilities:['release']}],opts);assert.equal(a.value.semanticIdentity,b.value.semanticIdentity);assert.equal(a.value.records.length,1);});

test('frontier dual-binding and semantic equivalence are explicit/fail-closed',()=>{assert.equal(validateNormalizationTransition('LEGACY_UNMAPPED','LEGACY_MAPPED').ok,true);assert.equal(validateNormalizationTransition('LEGACY_UNMAPPED','GEF_CANONICAL').ok,false);assert.equal(buildNormalizationFrontier('proj-1',[{domain:'SCOPE',state:'DUAL_BOUND'},{domain:'DECISION',state:'GEF_CANONICAL'}]).ok,true);assert.equal(probeSemanticEquivalence({a:{x:1,y:2}},{a:{y:2,x:1}},['a']),'EQUIVALENT');assert.equal(probeSemanticEquivalence({a:1},{a:2},['a']),'NON_EQUIVALENT');assert.equal(probeSemanticEquivalence({a:1},{},['a']),'INDETERMINATE');assert.equal(probeSemanticEquivalence({a:1},{a:1},['a'],false),'UNSUPPORTED_MAPPING');});

test('normalization budget and reversibility guard block unknown destructive promotion',()=>{assert.equal(enforceNormalizationBudget({domains:2,mappings:2,migrations:0,dependencyExpansion:1},{maxDomains:1,maxMappings:3,maxMigrations:1,maxDependencyExpansion:2}).diagnostics[0].code,'NORMALIZATION_BUDGET_EXCEEDED');assert.equal(classifyReversibility('UNKNOWN'),'IRREVERSIBILITY_UNKNOWN');assert.equal(evaluateDestructivePromotion('IRREVERSIBILITY_UNKNOWN').diagnostics[0].code,'IRREVERSIBILITY_BLOCKS_PROMOTION');assert.equal(evaluateDestructivePromotion('REQUIRES_MIGRATION_ROLLBACK').diagnostics[0].code,'MIGRATION_ROLLBACK_EVIDENCE_REQUIRED');assert.equal(evaluateDestructivePromotion('REQUIRES_MIGRATION_ROLLBACK',true).ok,true);});

test('proof spine deterministic, cycle-safe, bounded, cancellable and selectively invalidated',()=>{const nodes=[{id:'root',payloadDigest:'sha256:a'},{id:'child',payloadDigest:'sha256:b',dependencies:['root']},{id:'other',payloadDigest:'sha256:c'}];const s=buildAdoptionProofSpine(nodes,opts);assert.equal(s.ok,true);assert.deepEqual(computeProofInvalidation(s.value,['root']),['child','root']);assert.deepEqual(computeProofInvalidation(s.value,['root'],true),['child','other','root']);assert.equal(buildAdoptionProofSpine(nodes,{digest,maxNodes:2}).diagnostics[0].code,'NODE_BUDGET_EXCEEDED');assert.equal(buildAdoptionProofSpine(nodes,{digest,cancellation:{isCancelled(){return true}}}).diagnostics[0].code,'CANCELLED');assert.equal(buildAdoptionProofSpine([{id:'a',payloadDigest:'x',dependencies:['b']},{id:'b',payloadDigest:'y',dependencies:['a']}],opts).diagnostics[0].code,'PROOF_SPINE_CYCLE');});

test('governance delta and provenance are deterministic',()=>{const input={projectId:'proj-1',beforeIdentity:'a',afterIdentity:'b',frontierMoved:['SCOPE'],bridgesAdded:['x'],bridgesRetired:[],driftChanges:[],quarantineChanges:[],capabilitiesUnlocked:['context'],capabilitiesInvalidated:[]};assert.equal(buildGovernanceDeltaReceipt(input,opts).value.semanticIdentity,buildGovernanceDeltaReceipt({...input,frontierMoved:[...input.frontierMoved].reverse()},opts).value.semanticIdentity);assert.match(projectBootstrapProvenance({artifactId:'scope',sourceRefs:['b','a'],semanticOwner:'M13',payloadIdentity:'sha256:x',validationState:'VALID'},opts).value.generatedDigest,/^sha256:/);});

function receiptInput(overrides={}){return {projectId:'proj-1',policyVersion:'m13-v1',mode:'BROWNFIELD_INCREMENTAL',intentCapsuleIdentity:'sha256:intent',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',maturityVectorIdentity:'sha256:gmv',normalizationFrontier:{projectId:'proj-1',domains:[{domain:'SCOPE',state:'GEF_CANONICAL'}]},bridgeIds:['bridge-1'],membraneIds:[],sourceFingerprints:[{id:'bridge-1',fingerprint:'fp1'}],driftSummary:[],quarantineIds:[],completedIncrementIds:['inc1'],blockers:[],safetyEnvelopeIdentity:'sha256:ase',capabilityUnlocks:[{capability:'context',unlocked:true,reasons:[]}],governedDomains:['SCOPE'],ungovernedDomains:[],blockedDomains:[],...overrides};}
const currentBindings={projectId:'proj-1',sourcePackIdentity:'sha256:source',profileIdentity:'generic',profileDigest:'sha256:profile',policyVersion:'m13-v1',sourceFingerprints:[{id:'bridge-1',fingerprint:'fp1'}]};

test('adoption receipt deterministic, partial never collapses full, and validity states bind current truth',()=>{const proof=[{id:'intent',payloadDigest:'sha256:intent'}];const valid=buildAdoptionReceipt(receiptInput(),proof,opts);assert.equal(valid.value.validity,'VALID');const partial=buildAdoptionReceipt(receiptInput({ungovernedDomains:['DECISION'],nextSafeSlice:{targetDomains:['DECISION'],requiredDomains:['DECISION'],blockedDomains:[],optionalCleanup:[]}}),proof,opts);assert.equal(partial.value.validity,'PARTIAL');const blocked=buildAdoptionReceipt(receiptInput({blockers:['HIGH_DRIFT']}),proof,opts);assert.equal(blocked.value.validity,'BLOCKED');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,projectId:'other'}),'PROJECT_MISMATCH');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,sourcePackIdentity:'changed'}),'SOURCE_PACK_MISMATCH');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,policyVersion:'changed'}),'POLICY_VERSION_UNSUPPORTED');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,profileDigest:'changed'}),'STALE');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,sourceFingerprints:[]}),'INDETERMINATE');assert.equal(evaluateReceiptValidity(valid.value,{...currentBindings,sourceFingerprints:[{id:'bridge-1',fingerprint:'changed'}]}),'STALE');assert.equal(buildAdoptionReceipt(receiptInput({sourceFingerprints:[]}),proof,opts).diagnostics[0].code,'ADOPTION_RECEIPT_FINGERPRINTS_MISSING');});

test('regression sentinel catches canonical, capability, governance and fingerprint regressions; receipts reject secrets',()=>{const proof=[{id:'intent',payloadDigest:'sha256:intent'}];const previous=buildAdoptionReceipt(receiptInput(),proof,opts).value;const current=buildAdoptionReceipt(receiptInput({normalizationFrontier:{projectId:'proj-1',domains:[{domain:'SCOPE',state:'DUAL_BOUND'}]},capabilityUnlocks:[{capability:'context',unlocked:false,reasons:['blocked']}],governedDomains:[],ungovernedDomains:['SCOPE'],sourceFingerprints:[{id:'bridge-1',fingerprint:'changed'}]}),proof,opts).value;const codes=new Set(detectAdoptionRegression(previous,current).map(r=>r.code));for(const code of ['CANONICAL_DOMAIN_REGRESSION','CAPABILITY_REGRESSION','GOVERNANCE_DOMAIN_REGRESSION','LEGACY_BINDING_STALE'])assert.ok(codes.has(code));assert.equal(buildAdoptionReceipt({...receiptInput(),password:'hidden'},proof,opts).diagnostics[0].code,'RECEIPT_SECRET_MATERIAL_FORBIDDEN');});
