import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  createPolicyAuthorityCapsule, guardrailDecisionAlgebra, buildPolicyDomainLattice, createExceptionWarrant,
  buildPolicyProvenanceChain, buildApplicabilityWitnessSet, buildObligationCompositionGraph,
  conflictPreservingPolicyJoin, evaluatePolicies, checkExceptionBlastRadius, enforceGuardrailMembrane,
  issueMutationCapabilityLease, checkPolicyToctou, failClosedDegradation, computePolicySemanticFingerprint,
  buildGuardrailCoverageMap, buildExceptionDebtRegister, createPolicyRegressionSnapshot, detectPolicyRegression,
  buildContinuityPolicyBinding,
} from '../packages/policy-guardrail-engine/dist/public.js';

const digest={algorithm:'sha256',digest:value=>createHash('sha256').update(value).digest('hex')};
const opts={digest};
function obligation(id='ob-write',effect='REQUIRE',deps=[]){return{obligationId:id,domain:'SOURCE',action:'write-reviewed',effect,dependsOn:deps};}
function policy(id='p1',overrides={}){const r=createPolicyAuthorityCapsule({policyId:id,version:'1',owner:'security',authorityRef:`auth:${id}`,precedenceDomain:'SECURITY',domains:['SOURCE'],appliesToOperations:['write'],appliesToNodeIds:['n1'],requiredFacts:[],denyOperations:[],obligations:[obligation()],evidenceRefs:['sec-policy'],reviewTrigger:'on-change',status:'ACTIVE',...overrides},opts);assert.equal(r.ok,true);return r.value;}
function warrant(p,overrides={}){const r=createExceptionWarrant({warrantId:'w1',approvalRef:'approval:1',policyDigestBindings:[p.semanticDigest],policyIds:[p.policyId],obligationIds:['ob-write'],domains:['SOURCE'],nodeIds:['n1'],operations:['write'],permittedEffects:['WAIVE_OBLIGATION'],compensatingControls:['manual-review'],reviewTrigger:'next-checkpoint',status:'ACTIVE',...overrides},opts);assert.equal(r.ok,true);return r.value;}
function op(overrides={}){return{nodeId:'n1',operation:'write',domains:['SOURCE'],...overrides};}
function node(overrides={}){return{instructionId:'n1',objective:'write',targetFiles:['src/a.ts'],dependsOn:[],mutationDomains:['SOURCE'],validationIds:['v1'],provenanceRefs:['a'],preconditions:['policy-valid'],mutationSpec:'write',evidenceOutputs:['ev'],rollbackPlan:'revert',wave:0,critical:true,rollbackHook:'revert',readinessRef:'rrp:n1',...overrides};}
function evalOne(p=policy(),extra={}){return evaluatePolicies({policies:[p],operation:op(),mandatoryDomains:['SOURCE'],facts:{},exceptionWarrants:[],...extra},opts);}

test('PAC deterministic and domain lattice remains domain-scoped',()=>{const a=policy('p1');const b=policy('p1');assert.equal(a.semanticDigest,b.semanticDigest);const l=buildPolicyDomainLattice([a]);assert.deepEqual(l.entries[0].policyIds,['p1']);});
test('PAC rejects missing domain',()=>{const r=createPolicyAuthorityCapsule({policyId:'p',version:'1',owner:'o',authorityRef:'a',precedenceDomain:'D',domains:[],appliesToOperations:[],appliesToNodeIds:[],requiredFacts:[],denyOperations:[],obligations:[],evidenceRefs:[],reviewTrigger:'x',status:'ACTIVE'},opts);assert.equal(r.ok,false);});
test('GDA never early-allows unknown or missing mandatory domain',()=>{assert.equal(guardrailDecisionAlgebra({denials:[],unknowns:['x'],conflicts:[],obligations:[],mandatoryDomainCoverageComplete:true}),'BLOCK_UNKNOWN');assert.equal(guardrailDecisionAlgebra({denials:[],unknowns:[],conflicts:[],obligations:[],mandatoryDomainCoverageComplete:false}),'BLOCK_UNKNOWN');});
test('exception warrant is explicit and deterministic',()=>{const p=policy();const a=warrant(p);const b=warrant(p);assert.equal(a.warrantDigest,b.warrantDigest);});
test('unbounded exception warrant fails closed',()=>{const p=policy();const r=createExceptionWarrant({warrantId:'w',approvalRef:'a',policyDigestBindings:[p.semanticDigest],policyIds:[p.policyId],obligationIds:[],domains:[],nodeIds:['n1'],operations:['write'],permittedEffects:['WAIVE_DENY'],compensatingControls:['c'],reviewTrigger:'x',status:'ACTIVE'},opts);assert.equal(r.ok,false);});
test('provenance chain is stable regardless input order',()=>{const a=policy('a');const b=policy('b');assert.deepEqual(buildPolicyProvenanceChain([b,a]),buildPolicyProvenanceChain([a,b]));});
test('applicability witness exposes unknown required fact',()=>{const p=policy('p',{requiredFacts:['approved']});const w=buildApplicabilityWitnessSet([p],op(),{});assert.equal(w.witnesses[0].state,'UNKNOWN');});
test('obligation graph orders dependencies and rejects cycle',()=>{const ok=buildObligationCompositionGraph([obligation('a'),obligation('b','REQUIRE',['a'])],opts);assert.equal(ok.ok,true);assert.deepEqual(ok.value.order,['a','b']);const bad=buildObligationCompositionGraph([obligation('a','REQUIRE',['b']),obligation('b','REQUIRE',['a'])],opts);assert.equal(bad.ok,false);});
test('conflict-preserving join blocks incompatible authority instead of choosing winner',()=>{const a={policyId:'a',obligations:[obligation('x','REQUIRE')],denials:[],unknowns:[],exceptionWarrantIds:[]};const b={policyId:'b',obligations:[obligation('y','FORBID')],denials:[],unknowns:[],exceptionWarrantIds:[]};const j=conflictPreservingPolicyJoin([a,b]);assert.equal(j.conflicts.length,1);});
test('normal obligation evaluation returns ALLOW_WITH_OBLIGATIONS',()=>{const r=evalOne();assert.equal(r.ok,true);assert.equal(r.value.decision,'ALLOW_WITH_OBLIGATIONS');});
test('deny dominates allow',()=>{const p=policy('p',{denyOperations:['write'],obligations:[]});const r=evalOne(p);assert.equal(r.ok,true);assert.equal(r.value.decision,'DENY');});
test('missing mandatory policy domain blocks unknown',()=>{const p=policy();const r=evaluatePolicies({policies:[p],operation:op(),mandatoryDomains:['SOURCE','SECURITY'],facts:{},exceptionWarrants:[]},opts);assert.equal(r.ok,true);assert.equal(r.value.decision,'BLOCK_UNKNOWN');assert.ok(r.value.unknowns.some(x=>x.includes('SECURITY')));});
test('unknown fact blocks instead of permissive fallback',()=>{const p=policy('p',{requiredFacts:['approved']});const r=evalOne(p);assert.equal(r.ok,true);assert.equal(r.value.decision,'BLOCK_UNKNOWN');});
test('order does not resolve conflicting policies',()=>{const a=policy('a',{obligations:[obligation('a','REQUIRE')]});const b=policy('b',{obligations:[obligation('b','FORBID')]});const x=evaluatePolicies({policies:[a,b],operation:op(),mandatoryDomains:['SOURCE'],facts:{},exceptionWarrants:[]},opts);const y=evaluatePolicies({policies:[b,a],operation:op(),mandatoryDomains:['SOURCE'],facts:{},exceptionWarrants:[]},opts);assert.equal(x.value.decision,'BLOCK_UNKNOWN');assert.equal(x.value.receiptDigest,y.value.receiptDigest);});
test('bounded warrant can waive exactly named obligation',()=>{const p=policy();const w=warrant(p);const r=evaluatePolicies({policies:[p],operation:op(),mandatoryDomains:['SOURCE'],facts:{},exceptionWarrants:[w]},opts);assert.equal(r.ok,true);assert.equal(r.value.decision,'ALLOW');assert.deepEqual(r.value.exceptionWarrantIds,['w1']);});
test('warrant cannot leak to another node',()=>{const p=policy();const w=warrant(p);const check=checkExceptionBlastRadius(w,{policyDigest:p.semanticDigest,policyId:p.policyId,obligationId:'ob-write',domain:'SOURCE',nodeId:'n2',operation:'write',effect:'WAIVE_OBLIGATION'});assert.equal(check.ok,false);});
test('explicit deny waiver requires exact WAIVE_DENY warrant',()=>{const p=policy('p',{denyOperations:['write'],obligations:[]});const w=warrant(p,{obligationIds:[],permittedEffects:['WAIVE_DENY']});const r=evaluatePolicies({policies:[p],operation:op(),mandatoryDomains:['SOURCE'],facts:{},exceptionWarrants:[w]},opts);assert.equal(r.ok,true);assert.equal(r.value.decision,'ALLOW');});
test('membrane projects M15 node and blocks mismatched node',()=>{const r=evalOne();const good=enforceGuardrailMembrane(r.value,node(),'write');assert.equal(good.allowed,true);const bad=enforceGuardrailMembrane(r.value,node({instructionId:'n2'}),'write');assert.equal(bad.allowed,false);});
test('membrane blocks DENY decision',()=>{const p=policy('p',{denyOperations:['write'],obligations:[]});const r=evalOne(p);assert.equal(enforceGuardrailMembrane(r.value,node(),'write').allowed,false);});
test('lease requires all obligations satisfied',()=>{const r=evalOne();const projection=enforceGuardrailMembrane(r.value,node(),'write');const bad=issueMutationCapabilityLease(projection,'sha256:'+'a'.repeat(64),'chk',[],'nonce1',opts);assert.equal(bad.ok,false);const ok=issueMutationCapabilityLease(projection,'sha256:'+'a'.repeat(64),'chk',['ob-write'],'nonce1',opts);assert.equal(ok.ok,true);});
test('TOCTOU sentinel rejects policy fingerprint drift',()=>{const r=evalOne();const projection=enforceGuardrailMembrane(r.value,node(),'write');const lease=issueMutationCapabilityLease(projection,'sha256:'+'a'.repeat(64),'chk',['ob-write'],'nonce1',opts).value;assert.equal(checkPolicyToctou(lease,'sha256:'+'b'.repeat(64),r.value.receiptDigest,node(),'write').ok,false);assert.equal(checkPolicyToctou(lease,lease.policyFingerprint,r.value.receiptDigest,node(),'write').ok,true);});
test('fail-closed degradation is BLOCK_UNKNOWN',()=>{assert.equal(failClosedDegradation('policy-store').decision,'BLOCK_UNKNOWN');});
test('policy fingerprint is order invariant',()=>{const a=policy('a');const b=policy('b');const x=computePolicySemanticFingerprint([a,b],[],opts);const y=computePolicySemanticFingerprint([b,a],[],opts);assert.equal(x.value,y.value);});
test('coverage map exposes uncovered mandatory domains',()=>{const c=buildGuardrailCoverageMap([policy()],['SOURCE','SECURITY']);assert.deepEqual(c.uncoveredDomains,['SECURITY']);});
test('exception debt register contains active warrants only',()=>{const p=policy();const active=warrant(p);const revoked=warrant(p,{warrantId:'w2',status:'REVOKED'});const d=buildExceptionDebtRegister([revoked,active],opts);assert.equal(d.ok,true);assert.deepEqual(d.value.entries.map(x=>x.warrantId),['w1']);});
test('regression sentinel detects deny-to-allow',()=>{const deny=evalOne(policy('p',{denyOperations:['write'],obligations:[]})).value;const allow=evaluatePolicies({policies:[policy('p2',{obligations:[]})],operation:op(),mandatoryDomains:['SOURCE'],facts:{},exceptionWarrants:[]},opts).value;const f=detectPolicyRegression(createPolicyRegressionSnapshot(deny,[policy('p',{denyOperations:['write'],obligations:[]})],[]),createPolicyRegressionSnapshot(allow,[policy('p2',{obligations:[]})],[]));assert.ok(f.some(x=>x.kind==='DENY_TO_ALLOW'));});
test('regression sentinel detects obligation loss',()=>{const before=evalOne().value;const p2=policy('p2',{obligations:[]});const after=evalOne(p2).value;const f=detectPolicyRegression(createPolicyRegressionSnapshot(before,[policy()],[]),createPolicyRegressionSnapshot(after,[p2],[]));assert.ok(f.some(x=>x.kind==='OBLIGATION_LOSS'));});
test('regression sentinel detects exception broadening',()=>{const p=policy();const rec=evalOne(p).value;const a=warrant(p);const b=warrant(p,{domains:['SOURCE','SECURITY']});const f=detectPolicyRegression(createPolicyRegressionSnapshot(rec,[p],[a]),createPolicyRegressionSnapshot(rec,[p],[b]));assert.ok(f.some(x=>x.kind==='EXCEPTION_BROADENED'));});
test('continuity binding is deterministic and checkpoint-bound',()=>{const p=policy();const rec=evalOne(p).value;const fp=computePolicySemanticFingerprint([p],[],opts).value;const debt=buildExceptionDebtRegister([],opts).value;const a=buildContinuityPolicyBinding('chk1',fp,rec,debt,[p],opts);const b=buildContinuityPolicyBinding('chk1',fp,rec,debt,[p],opts);assert.equal(a.value.bindingDigest,b.value.bindingDigest);});
test('injected digest capability fails closed on malformed output',()=>{const r=createPolicyAuthorityCapsule({policyId:'p',version:'1',owner:'o',authorityRef:'a',precedenceDomain:'D',domains:['D'],appliesToOperations:[],appliesToNodeIds:[],requiredFacts:[],denyOperations:[],obligations:[],evidenceRefs:[],reviewTrigger:'x',status:'ACTIVE'},{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);});
