import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  createCanonicalContinuationCapsule, buildAuthoritySnapshotIndex, evaluateContinuationInvariants,
  semanticCompareAndSwap, createPromotionFenceToken, createCheckpointPromotionProposal, detectSplitBrainContinuation,
  commitCheckpointPromotion, buildCheckpointDependencyGraph, selectiveContinuationInvalidation,
  createCheckpointRollbackPointer, buildStaleClaimQuarantine, detectContinuityRegression,
  buildContinuationMinimumSufficientState, compactHistoricalPointers, buildCheckpointPortabilityEnvelope,
  buildColdHistoryEvictionMap, assessCheckpointSize, buildCheckpointFreshnessVector,
  buildCheckpointAdmissionReceipt, buildResumeReadinessCertificate, buildContinuationHandoffContract,
} from '../packages/checkpoint-engine/dist/public.js';

const digest={algorithm:'sha256',digest:v=>createHash('sha256').update(v).digest('hex')};
const opts={digest};
const H=c=>`sha256:${c.repeat(64)}`;
function policyBinding(overrides={}){return{checkpointIdentity:'chk-prev',policyFingerprint:H('a'),decisionReceiptDigest:H('b'),exceptionDebtDigest:H('c'),policyIds:['policy-1'],bindingDigest:H('d'),...overrides};}
function binding(id='source',overrides={}){return{bindingId:id,domain:'SOURCE',semanticIdentity:H(id==='source'?'1':'2'),authorityRef:`auth:${id}`,required:true,...overrides};}
function claim(id='claim-1',overrides={}){return{claimId:id,domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['source:file-a'],authorityBindingIds:['source'],evidenceRefs:['ev:1'],...overrides};}
function input(overrides={}){return{schemaVersion:1,projectId:'project-1',moduleId:'GBS-M17',stageId:'IMPLEMENT',lineageId:'lineage-1',predecessorCheckpointDigest:null,admittedWorkOrderIds:['GBS-WO-M17-001'],authorityBindings:[binding()],policyBinding:policyBinding(),claims:[claim()],blockers:[],evidenceRefs:['ev:root'],nextLegalAction:'IMPLEMENT_GBS_M17',requiredCapabilities:['node24'],...overrides};}
function capsule(overrides={},o=opts){const r=createCanonicalContinuationCapsule(input(overrides),o);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}

test('CCC is deterministic under semantic list reordering',()=>{const a=capsule({evidenceRefs:['b','a'],admittedWorkOrderIds:['z','a']});const b=capsule({evidenceRefs:['a','b'],admittedWorkOrderIds:['a','z']});assert.equal(a.checkpointDigest,b.checkpointDigest);});
test('authority snapshot index rejects duplicate binding ids',()=>{const r=buildAuthoritySnapshotIndex([binding(),binding()],opts);assert.equal(r.ok,false);});
test('continuation invariants reject unresolved claim authority reference',()=>{const i=input({claims:[claim('c',{authorityBindingIds:['missing']})]});const a=buildAuthoritySnapshotIndex(i.authorityBindings,opts).value;const r=evaluateContinuationInvariants(i,a,opts);assert.equal(r.ok,true);assert.equal(r.value.admissible,false);});
test('checkpoint cannot manufacture invalid maturity',()=>{const r=createCanonicalContinuationCapsule(input({claims:[claim('c',{maturity:101})]}),opts);assert.equal(r.ok,false);});
test('checkpoint size guard fails closed at construction',()=>{const r=createCanonicalContinuationCapsule(input(),{digest,maxNodes:1,maxReferences:1});assert.equal(r.ok,false);});
test('state vector preserves domain maturity and status',()=>{const c=capsule();assert.equal(c.stateVector.entries.find(x=>x.domain==='BUILD').maturity,50);});
test('semantic CAS returns stale instead of last-writer-wins',()=>{assert.equal(semanticCompareAndSwap(H('1'),H('2')).status,'STALE_BASE');});
test('promotion fence is deterministic and base-bound',()=>{const a=createPromotionFenceToken('lineage-1',H('1'),'nonce-1',opts);const b=createPromotionFenceToken('lineage-1',H('1'),'nonce-1',opts);assert.equal(a.value.tokenDigest,b.value.tokenDigest);});
test('proposal rejects stale fence/base mismatch',()=>{const base=capsule();const next=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'NEXT'});const fence=createPromotionFenceToken(base.lineageId,H('9'),'nonce-1',opts).value;const r=createCheckpointPromotionProposal(base.checkpointDigest,next,fence,'auth:1',opts);assert.equal(r.ok,false);});
test('split brain detector catches divergent successors',()=>{const base=capsule();const a=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'A'});const b=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'B'});assert.equal(detectSplitBrainContinuation(base.checkpointDigest,[a,b]).divergent,true);});
test('promotion transaction commits exact successor with receipt',()=>{const base=capsule();const next=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'NEXT'});const fence=createPromotionFenceToken(base.lineageId,base.checkpointDigest,'nonce-1',opts).value;const proposal=createCheckpointPromotionProposal(base.checkpointDigest,next,fence,'auth:1',opts).value;const r=commitCheckpointPromotion(base,proposal,[],opts);assert.equal(r.ok,true);assert.equal(r.value.status,'COMMITTED');assert.equal(r.value.afterCheckpointDigest,next.checkpointDigest);});
test('promotion blocks when current base changed',()=>{const base=capsule();const newer=capsule({stageId:'NEWER'});const next=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'NEXT'});const fence=createPromotionFenceToken(base.lineageId,base.checkpointDigest,'nonce-1',opts).value;const p=createCheckpointPromotionProposal(base.checkpointDigest,next,fence,'auth:1',opts).value;assert.equal(commitCheckpointPromotion(newer,p,[],opts).ok,false);});
test('promotion blocks known divergent successor',()=>{const base=capsule();const a=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'A'});const b=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'B'});const fence=createPromotionFenceToken(base.lineageId,base.checkpointDigest,'nonce-1',opts).value;const p=createCheckpointPromotionProposal(base.checkpointDigest,a,fence,'auth:1',opts).value;assert.equal(commitCheckpointPromotion(base,p,[b],opts).ok,false);});
test('dependency graph invalidates only directly dependent claims when complete',()=>{const c=capsule({claims:[claim('a'),claim('b',{dependencyKeys:['other']})]});const r=selectiveContinuationInvalidation(c,buildCheckpointDependencyGraph(c,true),['source:file-a']);assert.deepEqual(r.invalidatedClaimIds,['a']);assert.deepEqual(r.preservedClaimIds,['b']);});
test('incomplete dependency knowledge widens invalidation conservatively',()=>{const c=capsule({claims:[claim('a'),claim('b',{dependencyKeys:['other']})]});const r=selectiveContinuationInvalidation(c,buildCheckpointDependencyGraph(c,false),['source:file-a']);assert.equal(r.conservativeWidening,true);assert.deepEqual(r.invalidatedClaimIds,['a','b']);});
test('rollback pointer references predecessor and never rewrites history',()=>{const base=capsule();const next=capsule({predecessorCheckpointDigest:base.checkpointDigest,stageId:'NEXT'});const r=createCheckpointRollbackPointer(next,opts);assert.equal(r.ok,true);assert.equal(r.value.predecessorCheckpointDigest,base.checkpointDigest);});
test('genesis checkpoint has no fabricated rollback pointer',()=>{assert.equal(createCheckpointRollbackPointer(capsule(),opts).ok,false);});
test('stale claim quarantine retains invalid claims for audit',()=>{const c=capsule();const inv={invalidatedClaimIds:['claim-1'],preservedClaimIds:[],conservativeWidening:false};const q=buildStaleClaimQuarantine(c,inv,['source:file-a'],opts);assert.equal(q.ok,true);assert.equal(q.value.entries[0].claim.claimId,'claim-1');});
test('continuity regression detects maturity rollback',()=>{const a=capsule({claims:[claim('c',{maturity:80})]});const b=capsule({claims:[claim('c',{maturity:20})]});assert.ok(detectContinuityRegression(a,b).some(x=>x.kind==='MATURITY_ROLLBACK'));});
test('authorized rollback suppresses maturity regression only',()=>{const a=capsule({claims:[claim('c',{maturity:80})]});const b=capsule({claims:[claim('c',{maturity:20})]});assert.equal(detectContinuityRegression(a,b,true).some(x=>x.kind==='MATURITY_ROLLBACK'),false);});
test('continuity regression detects required authority loss',()=>{const a=capsule();const b=capsule({authorityBindings:[binding('other')],claims:[claim('c',{authorityBindingIds:['other']})]});assert.ok(detectContinuityRegression(a,b).some(x=>x.kind==='AUTHORITY_LOSS'));});
test('CMSS retains next action active claims authority evidence and blockers',()=>{const c=capsule({blockers:['block:1']});const r=buildContinuationMinimumSufficientState(c,opts);assert.equal(r.ok,true);assert.deepEqual(r.value.activeClaimIds,['claim-1']);assert.deepEqual(r.value.blockerRefs,['block:1']);});
test('historical compaction deduplicates while retaining predecessor rollback and evidence pointers',()=>{const p=[{checkpointDigest:H('1'),relation:'PREDECESSOR'},{checkpointDigest:H('1'),relation:'PREDECESSOR'},{checkpointDigest:H('2'),relation:'SUPERSEDED'},{checkpointDigest:H('3'),relation:'EVIDENCE'}];const r=compactHistoricalPointers(p,[H('2')],opts);assert.equal(r.ok,true);assert.equal(r.value.pointers.length,3);});
test('portability envelope reports missing capabilities explicitly',()=>{const c=capsule({requiredCapabilities:['node24','git']});const e=buildCheckpointPortabilityEnvelope(c,['node24'],opts);assert.deepEqual(e.value.unsupportedCapabilities,['git']);});
test('cold history eviction map is deterministic',()=>{const a=buildColdHistoryEvictionMap([{checkpointDigest:H('2'),retainedByRefs:['b','a']},{checkpointDigest:H('1'),retainedByRefs:['c']}],opts);const b=buildColdHistoryEvictionMap([{checkpointDigest:H('1'),retainedByRefs:['c']},{checkpointDigest:H('2'),retainedByRefs:['a','b']}],opts);assert.equal(a.value.mapDigest,b.value.mapDigest);});
test('size assessment reports node and reference pressure',()=>{const s=assessCheckpointSize(capsule(),{digest,maxNodes:1,maxReferences:1});assert.equal(s.withinBudget,false);});
test('freshness vector is binding-based not wall-clock based',()=>{const c=capsule();const f=buildCheckpointFreshnessVector(c,{source:H('1')},opts);assert.equal(f.value.allCurrent,true);assert.equal(f.value.entries[0].state,'CURRENT');});
test('required missing binding is stale for resume readiness',()=>{const c=capsule();const f=buildCheckpointFreshnessVector(c,{},opts).value;const p=buildCheckpointPortabilityEnvelope(c,['node24'],opts).value;const r=buildResumeReadinessCertificate(c,f,p,opts);assert.equal(r.value.ready,false);assert.equal(r.value.validity,'STALE_BINDING');});
test('capability gap yields PARTIAL readiness',()=>{const c=capsule();const f=buildCheckpointFreshnessVector(c,{source:H('1')},opts).value;const p=buildCheckpointPortabilityEnvelope(c,[],opts).value;const r=buildResumeReadinessCertificate(c,f,p,opts);assert.equal(r.value.validity,'PARTIAL');});
test('blockers yield BLOCKED readiness',()=>{const c=capsule({blockers:['approval']});const f=buildCheckpointFreshnessVector(c,{source:H('1')},opts).value;const p=buildCheckpointPortabilityEnvelope(c,['node24'],opts).value;assert.equal(buildResumeReadinessCertificate(c,f,p,opts).value.validity,'BLOCKED');});
test('checkpoint admission receipt binds before after lineage and authority',()=>{const a=capsule();const b=capsule({predecessorCheckpointDigest:a.checkpointDigest,stageId:'NEXT'});const r=buildCheckpointAdmissionReceipt(a,b,opts);assert.equal(r.ok,true);assert.equal(r.value.beforeCheckpointDigest,a.checkpointDigest);});
test('handoff contract binds exact readiness certificate and checkpoint',()=>{const c=capsule();const f=buildCheckpointFreshnessVector(c,{source:H('1')},opts).value;const p=buildCheckpointPortabilityEnvelope(c,['node24'],opts).value;const r=buildResumeReadinessCertificate(c,f,p,opts).value;const h=buildContinuationHandoffContract(c,r,opts);assert.equal(h.ok,true);assert.equal(h.value.checkpointDigest,c.checkpointDigest);});
test('handoff rejects readiness certificate from another checkpoint',()=>{const a=capsule();const b=capsule({stageId:'B'});const f=buildCheckpointFreshnessVector(a,{source:H('1')},opts).value;const p=buildCheckpointPortabilityEnvelope(a,['node24'],opts).value;const r=buildResumeReadinessCertificate(a,f,p,opts).value;assert.equal(buildContinuationHandoffContract(b,r,opts).ok,false);});
test('cancellation is fail-closed',()=>{const r=createCanonicalContinuationCapsule(input(),{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);});
test('malformed digest provider fails closed',()=>{const r=createCanonicalContinuationCapsule(input(),{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);});
