import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createCanonicalContinuationCapsule, verifyCanonicalContinuationCapsule, createPromotionFenceToken, createCheckpointPromotionProposal, commitCheckpointPromotion, buildCheckpointDependencyGraph, selectiveContinuationInvalidation, detectContinuityRegression } from '../packages/checkpoint-engine/dist/public.js';
const digest={algorithm:'sha256',digest:v=>createHash('sha256').update(v).digest('hex')};
const H=c=>`sha256:${c.repeat(64)}`;
const policyBinding={checkpointIdentity:'prev',policyFingerprint:H('a'),decisionReceiptDigest:H('b'),exceptionDebtDigest:H('c'),policyIds:['p'],bindingDigest:H('d')};
function mk(overrides={}){const input={schemaVersion:1,projectId:'p1',moduleId:'m17',stageId:'s1',lineageId:'l1',predecessorCheckpointDigest:null,admittedWorkOrderIds:['wo1'],authorityBindings:[{bindingId:'source',domain:'SOURCE',semanticIdentity:H('1'),authorityRef:'auth:source',required:true}],policyBinding,claims:[{claimId:'a',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['source:x'],authorityBindingIds:['source'],evidenceRefs:['e1']}],blockers:[],evidenceRefs:['root'],nextLegalAction:'next',requiredCapabilities:[],...overrides};const r=createCanonicalContinuationCapsule(input,{digest});assert.equal(r.ok,true);return r.value;}
test('forged checkpoint digest is rejected by trust-anchor verifier',()=>{const c=mk();const forged={...c,checkpointDigest:H('9')};assert.equal(verifyCanonicalContinuationCapsule(forged,{digest}).ok,false);});
test('forged fence token is rejected before proposal admission',()=>{const base=mk();const next=mk({predecessorCheckpointDigest:base.checkpointDigest,stageId:'s2'});const fence=createPromotionFenceToken(base.lineageId,base.checkpointDigest,'n1',{digest}).value;const forged={...fence,tokenDigest:H('8')};assert.equal(createCheckpointPromotionProposal(base.checkpointDigest,next,forged,'auth',{digest}).ok,false);});
test('forged proposal digest is rejected at commit boundary',()=>{const base=mk();const next=mk({predecessorCheckpointDigest:base.checkpointDigest,stageId:'s2'});const fence=createPromotionFenceToken(base.lineageId,base.checkpointDigest,'n1',{digest}).value;const p=createCheckpointPromotionProposal(base.checkpointDigest,next,fence,'auth',{digest}).value;assert.equal(commitCheckpointPromotion(base,{...p,proposalDigest:H('7')},[],{digest}).ok,false);});
test('selective invalidation propagates through claim dependency closure',()=>{const c=mk({claims:[{claimId:'a',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['source:x'],authorityBindingIds:['source'],evidenceRefs:['e1']},{claimId:'b',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['claim:a'],authorityBindingIds:['source'],evidenceRefs:['e2']},{claimId:'c',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['claim:b'],authorityBindingIds:['source'],evidenceRefs:['e3']},{claimId:'z',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['other'],authorityBindingIds:['source'],evidenceRefs:['e4']}]});const r=selectiveContinuationInvalidation(c,buildCheckpointDependencyGraph(c,true),['source:x']);assert.deepEqual(r.invalidatedClaimIds,['a','b','c']);assert.deepEqual(r.preservedClaimIds,['z']);});
test('unresolved claim dependency marks graph incomplete and widens invalidation',()=>{const c=mk({claims:[{claimId:'a',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['claim:missing'],authorityBindingIds:['source'],evidenceRefs:['e1']},{claimId:'b',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:['other'],authorityBindingIds:['source'],evidenceRefs:['e2']}]});const g=buildCheckpointDependencyGraph(c,true);assert.equal(g.complete,false);const r=selectiveContinuationInvalidation(c,g,['source:x']);assert.equal(r.conservativeWidening,true);assert.deepEqual(r.invalidatedClaimIds,['a','b']);});
test('continuity regression detects disappearance of accepted claim',()=>{const before=mk({claims:[{claimId:'a',domain:'BUILD',status:'DONE',maturity:100,dependencyKeys:[],authorityBindingIds:['source'],evidenceRefs:['e1']},{claimId:'b',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:[],authorityBindingIds:['source'],evidenceRefs:['e2']}]});const after=mk({claims:[{claimId:'b',domain:'BUILD',status:'ACTIVE',maturity:50,dependencyKeys:[],authorityBindingIds:['source'],evidenceRefs:['e2']}]});assert.ok(detectContinuityRegression(before,after).some(x=>x.kind==='CLAIM_LOSS'&&x.subject==='a'));});
