import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  createCanonicalContinuationCapsule, buildCheckpointFreshnessVector, buildCheckpointPortabilityEnvelope,
  buildResumeReadinessCertificate, buildContinuationHandoffContract,
} from '../packages/checkpoint-engine/dist/public.js';
import {
  createResumeIntentCapsule, verifyResumeIntentCapsule, verifyContinuationHandoff, proveLineageContinuity,
  enforceResumeAuthorityBoundary, applyConversationIndependence, buildResumeMinimumSufficientContext,
  rehydrateHotState, buildContextTemperatureMap, createNegativeRehydrationCache, buildResumeReadPlan,
  applyNegativeRehydrationCache, buildResumeDriftVector, buildDeltaRehydrationGraph, detectOrphanWork,
  buildResumeConflictQuarantine, evaluateSafeReentry, buildResumeReceipt, verifyResumeReceipt,
  buildResumeSemanticDigest, detectContinuityLoss, buildResumeEfficiencyReceipt, buildSafeHandbackContract,
} from '../packages/resume-engine/dist/public.js';

const digest={algorithm:'sha256',digest:v=>createHash('sha256').update(v).digest('hex')};
const opts={digest};
const H=c=>`sha256:${c.repeat(64)}`;
function policyBinding(overrides={}){return{checkpointIdentity:'checkpoint-prev',policyFingerprint:H('a'),decisionReceiptDigest:H('b'),exceptionDebtDigest:H('c'),policyIds:['policy-1'],bindingDigest:H('d'),...overrides};}
function checkpointInput(overrides={}){return{schemaVersion:1,projectId:'project-1',moduleId:'GBS-M18',stageId:'RESUME',lineageId:'lineage-1',predecessorCheckpointDigest:H('0'),admittedWorkOrderIds:['GBS-WO-M18-001'],authorityBindings:[{bindingId:'source',domain:'SOURCE',semanticIdentity:H('1'),authorityRef:'auth:source',required:true},{bindingId:'policy',domain:'POLICY',semanticIdentity:H('2'),authorityRef:'auth:policy',required:true}],policyBinding:policyBinding(),claims:[{claimId:'claim-a',domain:'BUILD',status:'ACTIVE',maturity:60,dependencyKeys:['source:file-a'],authorityBindingIds:['source','policy'],evidenceRefs:['ev:a']},{claimId:'claim-b',domain:'BUILD',status:'DONE',maturity:100,dependencyKeys:['claim:claim-a'],authorityBindingIds:['source'],evidenceRefs:['ev:b']}],blockers:[],evidenceRefs:['ev:root'],nextLegalAction:'IMPLEMENT_GBS_M18',requiredCapabilities:['node24'],...overrides};}
function checkpoint(overrides={}){const r=createCanonicalContinuationCapsule(checkpointInput(overrides),opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
function canonical(c=checkpoint(),available=['node24']){const freshness=buildCheckpointFreshnessVector(c,{source:H('1'),policy:H('2')},{digest}).value;const portability=buildCheckpointPortabilityEnvelope(c,available,{digest}).value;const readiness=buildResumeReadinessCertificate(c,freshness,portability,{digest}).value;const handoff=buildContinuationHandoffContract(c,readiness,{digest}).value;return{c,freshness,portability,readiness,handoff};}
function intent(c,overrides={}){const r=createResumeIntentCapsule({resumeId:'resume-1',projectId:c.projectId,expectedLineageId:c.lineageId,expectedCheckpointDigest:c.checkpointDigest,requestedNextAction:null,...overrides},opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
function refs(){return[{refId:'checkpoint-core',dependencyKeys:['checkpoint'],mandatory:true,preferredTemperature:'HOT'},{refId:'source-a',dependencyKeys:['source:file-a','claim:claim-a'],mandatory:true,preferredTemperature:'WARM'},{refId:'history-cold',dependencyKeys:['history'],mandatory:false,preferredTemperature:'COLD'}];}
function observation(c,overrides={}){return{projectId:c.projectId,lineageId:c.lineageId,checkpointDigest:c.checkpointDigest,policyBindingDigest:c.policyBinding.bindingDigest,authorityIdentities:{source:H('1'),policy:H('2')},claimStates:{'claim-a':'ACTIVE:60','claim-b':'DONE:100'},...overrides};}
function readyFixture(){const {c,readiness,handoff}=canonical();const i=intent(c);const lineage=proveLineageContinuity(i,c,handoff,opts).value;const authority=enforceResumeAuthorityBoundary(i,c,handoff,opts).value;const conversation=applyConversationIndependence([],{},opts).value;const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const hot=rehydrateHotState([],handoff.handoffDigest,opts).value;const temp=buildContextTemperatureMap(refs(),{'checkpoint-core':100,'source-a':80,'history-cold':10},opts).value;const plan=buildResumeReadPlan(context,hot,temp,opts).value;const drift=buildResumeDriftVector(c,observation(c),opts).value;const orphans=detectOrphanWork(c,[],opts).value;const quarantine=buildResumeConflictQuarantine(drift,orphans,conversation,opts).value;const decision=evaluateSafeReentry(c,lineage,authority,readiness,drift,plan,orphans,opts).value;return{c,i,lineage,authority,conversation,context,hot,temp,plan,drift,orphans,quarantine,decision,handoff,readiness};}

test('resume intent is deterministic and exact-checkpoint-bound',()=>{const c=checkpoint();const a=intent(c),b=intent(c);assert.equal(a.intentDigest,b.intentDigest);assert.equal(a.expectedCheckpointDigest,c.checkpointDigest);});
test('resume intent tampering fails verification',()=>{const c=checkpoint();const i=intent(c);assert.equal(verifyResumeIntentCapsule({...i,projectId:'other'},opts).ok,false);});
test('valid M17 handoff verifies semantically',()=>{const {handoff}=canonical();assert.equal(verifyContinuationHandoff(handoff,opts).ok,true);});
test('forged M17 handoff is rejected',()=>{const {handoff}=canonical();assert.equal(verifyContinuationHandoff({...handoff,nextLegalAction:'FORGED'},opts).ok,false);});
test('lineage proof accepts exact project lineage checkpoint and handoff',()=>{const {c,handoff}=canonical();const p=proveLineageContinuity(intent(c),c,handoff,opts);assert.equal(p.ok,true);assert.equal(p.value.valid,true);});
test('lineage proof classifies project mismatch',()=>{const {c,handoff}=canonical();const i=intent(c,{projectId:'project-2'});assert.equal(proveLineageContinuity(i,c,handoff,opts).value.mismatch,'PROJECT');});
test('lineage proof classifies lineage mismatch',()=>{const {c,handoff}=canonical();const i=intent(c,{expectedLineageId:'lineage-2'});assert.equal(proveLineageContinuity(i,c,handoff,opts).value.mismatch,'LINEAGE');});
test('authority boundary allows only canonical next action',()=>{const {c,handoff}=canonical();const good=enforceResumeAuthorityBoundary(intent(c),c,handoff,opts).value;const bad=enforceResumeAuthorityBoundary(intent(c,{requestedNextAction:'SKIP_TO_RELEASE'}),c,handoff,opts).value;assert.equal(good.authorized,true);assert.equal(bad.authorized,false);});
test('conversation claims remain informational and cannot become authority',()=>{const r=applyConversationIndependence([{claimId:'chat-1',subject:'checkpoint',assertedDigest:H('9')}],{checkpoint:H('1')},opts).value;assert.equal(r.authoritySource,'CANONICAL_CHECKPOINT_ONLY');assert.deepEqual(r.conflictingClaimIds,['chat-1']);});
test('RMSC binds exact checkpoint and handoff',()=>{const {c,handoff}=canonical();const r=buildResumeMinimumSufficientContext(c,handoff,refs(),opts);assert.equal(r.ok,true);assert.equal(r.value.nextLegalAction,c.nextLegalAction);});
test('RMSC rejects duplicate context refs',()=>{const {c,handoff}=canonical();assert.equal(buildResumeMinimumSufficientContext(c,handoff,[refs()[0],refs()[0]],opts).ok,false);});
test('hot state reuses only entries with current validity binding',()=>{const {handoff}=canonical();const r=rehydrateHotState([{refId:'a',contentDigest:H('3'),validityBindingDigest:handoff.handoffDigest},{refId:'b',contentDigest:H('4'),validityBindingDigest:H('9')}],handoff.handoffDigest,opts).value;assert.deepEqual(r.accepted.map(x=>x.refId),['a']);assert.deepEqual(r.rejectedRefIds,['b']);});
test('context temperature is relevance only and deterministic',()=>{const a=buildContextTemperatureMap(refs(),{'source-a':90},opts).value;const b=buildContextTemperatureMap(refs(),{'source-a':90},opts).value;assert.equal(a.mapDigest,b.mapDigest);assert.equal(a.entries.find(x=>x.refId==='source-a').temperature,'HOT');});
test('read plan skips valid hot refs',()=>{const {c,handoff}=canonical();const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const hot=rehydrateHotState([{refId:'checkpoint-core',contentDigest:H('3'),validityBindingDigest:handoff.handoffDigest}],handoff.handoffDigest,opts).value;const temp=buildContextTemperatureMap(refs(),{},opts).value;const plan=buildResumeReadPlan(context,hot,temp,opts).value;assert.equal(plan.steps.some(x=>x.refId==='checkpoint-core'),false);});
test('read budget causes explicit expansion instead of silent truncation',()=>{const {c,handoff}=canonical();const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const hot=rehydrateHotState([],handoff.handoffDigest,opts).value;const temp=buildContextTemperatureMap(refs(),{},opts).value;const plan=buildResumeReadPlan(context,hot,temp,{digest,maxReads:1}).value;assert.equal(plan.steps.length,1);assert.equal(plan.expansionRequired,true);});
test('negative cache is validity-bound',()=>{const {handoff}=canonical();const cache=createNegativeRehydrationCache([{refId:'source-a',absenceProofDigest:H('5'),validityBindingDigest:handoff.handoffDigest}],opts);assert.equal(cache.ok,true);});
test('current negative cache suppresses read and mandatory absence requests expansion',()=>{const {c,handoff}=canonical();const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const plan=buildResumeReadPlan(context,rehydrateHotState([],handoff.handoffDigest,opts).value,buildContextTemperatureMap(refs(),{},opts).value,opts).value;const cache=createNegativeRehydrationCache([{refId:'source-a',absenceProofDigest:H('5'),validityBindingDigest:handoff.handoffDigest}],opts).value;const r=applyNegativeRehydrationCache(plan,cache,handoff.handoffDigest,opts).value;assert.deepEqual(r.cacheHitRefIds,['source-a']);assert.equal(r.plan.expansionRequired,true);});
test('stale negative cache never suppresses reads',()=>{const {c,handoff}=canonical();const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const plan=buildResumeReadPlan(context,rehydrateHotState([],handoff.handoffDigest,opts).value,buildContextTemperatureMap(refs(),{},opts).value,opts).value;const cache=createNegativeRehydrationCache([{refId:'source-a',absenceProofDigest:H('5'),validityBindingDigest:H('9')}],opts).value;const r=applyNegativeRehydrationCache(plan,cache,handoff.handoffDigest,opts).value;assert.equal(r.plan.steps.some(x=>x.refId==='source-a'),true);});
test('clean observations yield no material drift',()=>{const c=checkpoint();const d=buildResumeDriftVector(c,observation(c),opts).value;assert.equal(d.hasMaterialDrift,false);});
test('policy binding drift is material',()=>{const c=checkpoint();const d=buildResumeDriftVector(c,observation(c,{policyBindingDigest:H('9')}),opts).value;assert.equal(d.hasMaterialDrift,true);assert.equal(d.entries.find(x=>x.dimension==='POLICY').state,'CHANGED');});
test('missing required authority is material and unknown',()=>{const c=checkpoint();const d=buildResumeDriftVector(c,observation(c,{authorityIdentities:{policy:H('2')}}),opts).value;assert.equal(d.hasMaterialDrift,true);assert.equal(d.hasUnknown,true);});
test('delta rehydration graph selects only affected dependency closure',()=>{const c=checkpoint();const g=buildDeltaRehydrationGraph(c,refs(),['source:file-a'],true,opts).value;assert.equal(g.nodes.some(x=>x.refId==='source-a'),true);assert.equal(g.nodes.some(x=>x.refId==='history-cold'),false);});
test('incomplete dependency knowledge widens delta rehydration',()=>{const c=checkpoint();const g=buildDeltaRehydrationGraph(c,refs(),['source:file-a'],false,opts).value;assert.equal(g.complete,false);assert.equal(g.nodes.length,refs().length);});
test('orphan work detects project lineage base and claim divergence',()=>{const c=checkpoint();const r=detectOrphanWork(c,[{workId:'work-1',projectId:c.projectId,lineageId:c.lineageId,baseCheckpointDigest:H('9'),claimIds:['unknown']}],opts).value;assert.deepEqual(r.orphanWorkIds,['work-1']);});
test('work based on current checkpoint and known claim is not orphaned',()=>{const c=checkpoint();const r=detectOrphanWork(c,[{workId:'work-1',projectId:c.projectId,lineageId:c.lineageId,baseCheckpointDigest:c.checkpointDigest,claimIds:['claim-a']}],opts).value;assert.deepEqual(r.orphanWorkIds,[]);});
test('conflict quarantine records canonical drift orphan and chat conflicts',()=>{const c=checkpoint();const drift=buildResumeDriftVector(c,observation(c,{policyBindingDigest:H('9')}),opts).value;const orphans=detectOrphanWork(c,[{workId:'w',projectId:'other',lineageId:c.lineageId,baseCheckpointDigest:c.checkpointDigest,claimIds:[]}],opts).value;const conv=applyConversationIndependence([{claimId:'chat',subject:'x',assertedDigest:H('8')}],{x:H('7')},opts).value;const q=buildResumeConflictQuarantine(drift,orphans,conv,opts).value;assert.ok(q.entries.length>=3);});
test('safe re-entry returns READY only on exact clean canonical state',()=>{const f=readyFixture();assert.equal(f.decision.status,'READY');assert.equal(f.decision.nextAction,f.c.nextLegalAction);});
test('safe re-entry returns PROJECT_MISMATCH first',()=>{const {c,readiness,handoff}=canonical();const i=intent(c,{projectId:'other'});const l=proveLineageContinuity(i,c,handoff,opts).value;const a=enforceResumeAuthorityBoundary(i,c,handoff,opts).value;const d=buildResumeDriftVector(c,observation(c),opts).value;const o=detectOrphanWork(c,[],opts).value;const ctx=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const p=buildResumeReadPlan(ctx,rehydrateHotState([],handoff.handoffDigest,opts).value,buildContextTemperatureMap(refs(),{},opts).value,opts).value;assert.equal(evaluateSafeReentry(c,l,a,readiness,d,p,o,opts).value.status,'PROJECT_MISMATCH');});
test('safe re-entry blocks policy drift',()=>{const f=readyFixture();const drift=buildResumeDriftVector(f.c,observation(f.c,{policyBindingDigest:H('9')}),opts).value;assert.equal(evaluateSafeReentry(f.c,f.lineage,f.authority,f.readiness,drift,f.plan,f.orphans,opts).value.status,'POLICY_BLOCKED');});
test('safe re-entry requires replan for orphan work',()=>{const f=readyFixture();const o=detectOrphanWork(f.c,[{workId:'w',projectId:'other',lineageId:f.c.lineageId,baseCheckpointDigest:f.c.checkpointDigest,claimIds:[]}],opts).value;assert.equal(evaluateSafeReentry(f.c,f.lineage,f.authority,f.readiness,f.drift,f.plan,o,opts).value.status,'DRIFT_REQUIRES_REPLAN');});
test('safe re-entry refuses noncanonical requested action',()=>{const {c,readiness,handoff}=canonical();const i=intent(c,{requestedNextAction:'SKIP'});const l=proveLineageContinuity(i,c,handoff,opts).value;const a=enforceResumeAuthorityBoundary(i,c,handoff,opts).value;const d=buildResumeDriftVector(c,observation(c),opts).value;const o=detectOrphanWork(c,[],opts).value;const ctx=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const p=buildResumeReadPlan(ctx,rehydrateHotState([],handoff.handoffDigest,opts).value,buildContextTemperatureMap(refs(),{},opts).value,opts).value;assert.equal(evaluateSafeReentry(c,l,a,readiness,d,p,o,opts).value.status,'INDETERMINATE');});
test('resume receipt is deterministic and checkpoint-bound',()=>{const f=readyFixture();const a=buildResumeReceipt(f.i,f.c,f.handoff,f.decision,f.plan,f.drift,f.orphans,f.quarantine,opts);const b=buildResumeReceipt(f.i,f.c,f.handoff,f.decision,f.plan,f.drift,f.orphans,f.quarantine,opts);assert.equal(a.value.receiptDigest,b.value.receiptDigest);});
test('resume receipt tampering is rejected',()=>{const f=readyFixture();const r=buildResumeReceipt(f.i,f.c,f.handoff,f.decision,f.plan,f.drift,f.orphans,f.quarantine,opts).value;assert.equal(verifyResumeReceipt({...r,nextAction:'FORGED'},opts).ok,false);});
test('resume semantic digest binds verified receipt',()=>{const f=readyFixture();const r=buildResumeReceipt(f.i,f.c,f.handoff,f.decision,f.plan,f.drift,f.orphans,f.quarantine,opts).value;assert.equal(buildResumeSemanticDigest(r,opts).ok,true);});
test('continuity loss sentinel detects authority claim blocker and stale success loss',()=>{const prev=checkpoint({blockers:['approval']});const cur=checkpoint({authorityBindings:[{bindingId:'policy',domain:'POLICY',semanticIdentity:H('2'),authorityRef:'auth:policy',required:true}],claims:[{claimId:'claim-b',domain:'BUILD',status:'DONE',maturity:100,dependencyKeys:[],authorityBindingIds:['policy'],evidenceRefs:['ev:b']}],blockers:[]});const f=readyFixture();const r=buildResumeReceipt(f.i,f.c,f.handoff,f.decision,f.plan,f.drift,f.orphans,f.quarantine,opts).value;const findings=detectContinuityLoss(prev,cur,r,opts).value;assert.ok(findings.some(x=>x.kind==='AUTHORITY_LOSS'));assert.ok(findings.some(x=>x.kind==='CLAIM_LOSS'));assert.ok(findings.some(x=>x.kind==='BLOCKER_LOSS'));assert.ok(findings.some(x=>x.kind==='STALE_SUCCESS_REINTRODUCED'));});
test('efficiency receipt is deterministic and non-authoritative',()=>{const a=buildResumeEfficiencyReceipt(3,2,1,1,opts);const b=buildResumeEfficiencyReceipt(3,2,1,1,opts);assert.equal(a.value.efficiencyDigest,b.value.efficiencyDigest);});
test('safe handback emits exactly canonical action only for READY',()=>{const f=readyFixture();const r=buildResumeReceipt(f.i,f.c,f.handoff,f.decision,f.plan,f.drift,f.orphans,f.quarantine,opts).value;const h=buildSafeHandbackContract(f.decision,r,opts).value;assert.equal(h.nextLegalAction,f.c.nextLegalAction);assert.deepEqual(h.blockers,[]);});
test('safe handback emits no action for blocked resume',()=>{const f=readyFixture();const drift=buildResumeDriftVector(f.c,observation(f.c,{policyBindingDigest:H('9')}),opts).value;const conversation=applyConversationIndependence([],{},opts).value;const quarantine=buildResumeConflictQuarantine(drift,f.orphans,conversation,opts).value;const decision=evaluateSafeReentry(f.c,f.lineage,f.authority,f.readiness,drift,f.plan,f.orphans,opts).value;assert.equal(decision.status,'POLICY_BLOCKED');const r=buildResumeReceipt(f.i,f.c,f.handoff,decision,f.plan,drift,f.orphans,quarantine,opts).value;const h=buildSafeHandbackContract(decision,r,opts).value;assert.equal(h.nextLegalAction,null);assert.deepEqual(h.blockers,['RESUME_POLICY_DRIFT']);});
test('cancellation fails closed before resume intent creation',()=>{const c=checkpoint();const r=createResumeIntentCapsule({resumeId:'r',projectId:c.projectId,expectedLineageId:c.lineageId,expectedCheckpointDigest:c.checkpointDigest,requestedNextAction:null},{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);});
test('malformed digest provider fails closed',()=>{const c=checkpoint();const r=createResumeIntentCapsule({resumeId:'r',projectId:c.projectId,expectedLineageId:c.lineageId,expectedCheckpointDigest:c.checkpointDigest,requestedNextAction:null},{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);});
