import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import {
  createCanonicalContinuationCapsule, buildCheckpointFreshnessVector, buildCheckpointPortabilityEnvelope,
  buildResumeReadinessCertificate, buildContinuationHandoffContract,
} from '../packages/checkpoint-engine/dist/public.js';
import {
  createResumeIntentCapsule, proveLineageContinuity, enforceResumeAuthorityBoundary,
  applyConversationIndependence, buildResumeMinimumSufficientContext, rehydrateHotState,
  buildContextTemperatureMap, buildResumeReadPlan, createNegativeRehydrationCache,
  applyNegativeRehydrationCache, buildResumeDriftVector, detectOrphanWork,
  buildResumeConflictQuarantine, evaluateSafeReentry, buildResumeReceipt,
  buildSafeHandbackContract, buildResumeEfficiencyReceipt, detectContinuityLoss,
} from '../packages/resume-engine/dist/public.js';

const digest={algorithm:'sha256',digest:v=>createHash('sha256').update(v).digest('hex')};
const opts={digest};
const H=c=>`sha256:${c.repeat(64)}`;
const policyBinding={checkpointIdentity:'prev',policyFingerprint:H('a'),decisionReceiptDigest:H('b'),exceptionDebtDigest:H('c'),policyIds:['p'],bindingDigest:H('d')};
function checkpointInput(overrides={}){return{schemaVersion:1,projectId:'project-1',moduleId:'GBS-M18',stageId:'RESUME',lineageId:'lineage-1',predecessorCheckpointDigest:H('0'),admittedWorkOrderIds:['GBS-WO-M18-001'],authorityBindings:[{bindingId:'source',domain:'SOURCE',semanticIdentity:H('1'),authorityRef:'auth:source',required:true},{bindingId:'policy',domain:'POLICY',semanticIdentity:H('2'),authorityRef:'auth:policy',required:true}],policyBinding,claims:[{claimId:'claim-a',domain:'BUILD',status:'ACTIVE',maturity:60,dependencyKeys:['source:file-a'],authorityBindingIds:['source','policy'],evidenceRefs:['ev:a']}],blockers:[],evidenceRefs:['ev:root'],nextLegalAction:'IMPLEMENT_GBS_M18',requiredCapabilities:['node24'],...overrides};}
function checkpoint(overrides={}){const r=createCanonicalContinuationCapsule(checkpointInput(overrides),opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
function canonical(c=checkpoint()){const freshness=buildCheckpointFreshnessVector(c,{source:H('1'),policy:H('2')},opts).value;const portability=buildCheckpointPortabilityEnvelope(c,['node24'],opts).value;const readiness=buildResumeReadinessCertificate(c,freshness,portability,opts).value;const handoff=buildContinuationHandoffContract(c,readiness,opts).value;return{c,readiness,handoff};}
function intent(c,resumeId='resume-1',overrides={}){return createResumeIntentCapsule({resumeId,projectId:c.projectId,expectedLineageId:c.lineageId,expectedCheckpointDigest:c.checkpointDigest,requestedNextAction:null,...overrides},opts).value;}
function refs(){return[{refId:'checkpoint-core',dependencyKeys:['checkpoint'],mandatory:true,preferredTemperature:'HOT'},{refId:'source-a',dependencyKeys:['source:file-a','claim:claim-a'],mandatory:true,preferredTemperature:'WARM'}];}
function observation(c,overrides={}){return{projectId:c.projectId,lineageId:c.lineageId,checkpointDigest:c.checkpointDigest,policyBindingDigest:c.policyBinding.bindingDigest,authorityIdentities:{source:H('1'),policy:H('2')},claimStates:{'claim-a':'ACTIVE:60'},...overrides};}
function readyFixture(){const {c,readiness,handoff}=canonical();const i=intent(c);const lineage=proveLineageContinuity(i,c,handoff,opts).value;const authority=enforceResumeAuthorityBoundary(i,c,handoff,opts).value;const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const hot=rehydrateHotState([],handoff.handoffDigest,opts).value;const temp=buildContextTemperatureMap(refs(),{},opts).value;const plan=buildResumeReadPlan(context,hot,temp,opts).value;const drift=buildResumeDriftVector(c,observation(c),opts).value;const orphans=detectOrphanWork(c,[],opts).value;const conversation=applyConversationIndependence([],{},opts).value;const quarantine=buildResumeConflictQuarantine(drift,orphans,conversation,opts).value;const decision=evaluateSafeReentry(c,lineage,authority,readiness,drift,plan,orphans,opts).value;const receipt=buildResumeReceipt(i,c,handoff,decision,plan,drift,orphans,quarantine,opts).value;return{c,readiness,handoff,i,lineage,authority,context,hot,temp,plan,drift,orphans,quarantine,decision,receipt};}

test('observed project drift is PROJECT_MISMATCH even when intent lineage proof is clean',()=>{const f=readyFixture();const drift=buildResumeDriftVector(f.c,observation(f.c,{projectId:'project-2'}),opts).value;const r=evaluateSafeReentry(f.c,f.lineage,f.authority,f.readiness,drift,f.plan,f.orphans,opts);assert.equal(r.ok,true);assert.equal(r.value.status,'PROJECT_MISMATCH');});
test('observed lineage drift is LINEAGE_MISMATCH',()=>{const f=readyFixture();const drift=buildResumeDriftVector(f.c,observation(f.c,{lineageId:'lineage-2'}),opts).value;assert.equal(evaluateSafeReentry(f.c,f.lineage,f.authority,f.readiness,drift,f.plan,f.orphans,opts).value.status,'LINEAGE_MISMATCH');});
test('work based on predecessor checkpoint is orphaned instead of silently resumed',()=>{const c=checkpoint();const r=detectOrphanWork(c,[{workId:'w1',projectId:c.projectId,lineageId:c.lineageId,baseCheckpointDigest:c.predecessorCheckpointDigest,claimIds:['claim-a']}],opts).value;assert.deepEqual(r.orphanWorkIds,['w1']);assert.ok(r.findings[0].reasons.includes('BASE_NOT_CURRENT'));});
test('mixed lineage and authority proofs from different resume intents fail trust-chain validation',()=>{const {c,readiness,handoff}=canonical();const i1=intent(c,'resume-1');const i2=intent(c,'resume-2');const lineage=proveLineageContinuity(i1,c,handoff,opts).value;const authority=enforceResumeAuthorityBoundary(i2,c,handoff,opts).value;const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const plan=buildResumeReadPlan(context,rehydrateHotState([],handoff.handoffDigest,opts).value,buildContextTemperatureMap(refs(),{},opts).value,opts).value;const drift=buildResumeDriftVector(c,observation(c),opts).value;const orphans=detectOrphanWork(c,[],opts).value;assert.equal(evaluateSafeReentry(c,lineage,authority,readiness,drift,plan,orphans,opts).ok,false);});
test('tampered hot-state artifact cannot suppress canonical reads',()=>{const {c,handoff}=canonical();const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const hot=rehydrateHotState([{refId:'checkpoint-core',contentDigest:H('3'),validityBindingDigest:handoff.handoffDigest}],handoff.handoffDigest,opts).value;const forged={...hot,accepted:[{...hot.accepted[0],validityBindingDigest:H('9')}]};const r=buildResumeReadPlan(context,forged,buildContextTemperatureMap(refs(),{},opts).value,opts);assert.equal(r.ok,false);});
test('tampered minimum context is rejected before read planning',()=>{const f=readyFixture();assert.equal(buildResumeReadPlan({...f.context,nextLegalAction:'SKIP'},f.hot,f.temp,opts).ok,false);});
test('tampered negative cache cannot suppress a planned read',()=>{const {c,handoff}=canonical();const context=buildResumeMinimumSufficientContext(c,handoff,refs(),opts).value;const plan=buildResumeReadPlan(context,rehydrateHotState([],handoff.handoffDigest,opts).value,buildContextTemperatureMap(refs(),{},opts).value,opts).value;const cache=createNegativeRehydrationCache([{refId:'source-a',absenceProofDigest:H('5'),validityBindingDigest:handoff.handoffDigest}],opts).value;const forged={...cache,entries:[{...cache.entries[0],absenceProofDigest:H('6')}]};assert.equal(applyNegativeRehydrationCache(plan,forged,handoff.handoffDigest,opts).ok,false);});
test('tampered safe re-entry decision is rejected before receipt creation',()=>{const f=readyFixture();const forged={...f.decision,nextAction:'SKIP_TO_RELEASE'};assert.equal(buildResumeReceipt(f.i,f.c,f.handoff,forged,f.plan,f.drift,f.orphans,f.quarantine,opts).ok,false);});
test('handback rejects a decision that moved after its receipt was issued',()=>{const f=readyFixture();const forged={...f.decision,nextAction:'SKIP_TO_RELEASE'};assert.equal(buildSafeHandbackContract(forged,f.receipt,opts).ok,false);});
test('receipt binds the exact decision digest',()=>{const f=readyFixture();assert.equal(f.receipt.decisionDigest,f.decision.decisionDigest);});
test('negative-cache efficiency hits cannot exceed planned reads',()=>{assert.equal(buildResumeEfficiencyReceipt(1,5,2,0,opts).ok,false);assert.equal(buildResumeEfficiencyReceipt(2,5,1,0,opts).ok,true);});
test('continuity loss sentinel rejects tampered resume receipt',()=>{const f=readyFixture();assert.equal(detectContinuityLoss(f.c,f.c,{...f.receipt,status:'INDETERMINATE'},opts).ok,false);});
test('valid decision receipt and handback stay canonical',()=>{const f=readyFixture();const h=buildSafeHandbackContract(f.decision,f.receipt,opts);assert.equal(h.ok,true);assert.equal(h.value.status,'READY');assert.equal(h.value.nextLegalAction,f.c.nextLegalAction);});
