import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {
  createRegistryIdentityEnvelope,verifyRegistryIdentityEnvelope,createRegistryProvenanceChain,verifyRegistryProvenanceChain,createProjectRegistryEntry,verifyProjectRegistryEntry,buildRegistryAuthorityBoundary,createRegistryMutationIntent,
  buildProjectRegistryIndex,assessRegistryCollisions,createAliasAdmissionCapsule,buildRegistryQueryPlan,queryProjectRegistry,buildRepositoryKnowledgeMap,createNegativeRegistryKnowledge,negativeRegistryKnowledgeApplies,
  buildRegistrySemanticVersion,compareRegistryVersion,createRegistryPromotionFence,verifyRegistryPromotionFence,detectRegistrySplitBrain,buildRegistryFreshnessVector,quarantineStaleEntries,buildRegistryRepairPlan,createNegativeDiagnosticCache,negativeDiagnosticCacheApplies,createTombstoneLineageRecord,
  assessRegistrySize,buildRegistrySnapshot,verifyRegistrySnapshot,projectRegistryPrivacy,buildRegistryPortabilityEnvelope,verifyRegistryPortabilityEnvelope,validatePortableIdentity,buildRegistryCompactionMap,buildRegistryHandoffContract,buildRegistryIntegrityReceipt,commitRegistryMutation
} from '../packages/project-registry/dist/public.js';

const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')};
const opts={digest};
const H=x=>`sha256:${createHash('sha256').update(x).digest('hex')}`;
const P1='11111111-1111-4111-8111-111111111111';
const P2='22222222-2222-4222-8222-222222222222';

function identity(projectId=P1,lineageId='lineage-a',repo=H('repo-a')){return createRegistryIdentityEnvelope({projectId,lineageId,repositoryIdentityDigest:repo,sourceIdentityDigest:H(`source:${projectId}`)},opts).value;}
function provenance(...xs){return createRegistryProvenanceChain(xs.length?xs:[H('source-doc')],opts).value;}
function entry(overrides={}){const id=overrides.identity??identity(overrides.projectId??P1,overrides.lineageId??'lineage-a',overrides.repo??H('repo-a'));return createProjectRegistryEntry({identity:id,checkpointDigest:overrides.checkpointDigest??H('checkpoint-a'),aliases:overrides.aliases??['alpha'],metadataRefs:overrides.metadataRefs??['meta-a'],knowledgeRefs:overrides.knowledgeRefs??['knowledge-a'],state:overrides.state??'ACTIVE',provenance:overrides.provenance??provenance(H('source-doc')),privateLocatorRef:overrides.privateLocatorRef??'locator-a'},opts).value;}
function snapshot(entries=[entry()]){return buildRegistrySnapshot(entries,[],opts).value;}
function store(initial){let state=initial;return{load(){return state;},compareAndSwap(expected,next){if(state.semanticVersion!==expected)return false;state=next;return true;},snapshot(){return state;}};}

test('identity envelope is M03 UUIDv4-bound and deterministic',()=>{const a=identity();const b=identity();assert.equal(a.envelopeDigest,b.envelopeDigest);assert.equal(verifyRegistryIdentityEnvelope(a,opts).value,true);assert.equal(createRegistryIdentityEnvelope({projectId:'bad',lineageId:'x',repositoryIdentityDigest:H('r'),sourceIdentityDigest:H('s')},opts).ok,false);});
test('provenance chain is order-independent and verified',()=>{const a=provenance(H('b'),H('a'));const b=provenance(H('a'),H('b'));assert.equal(a.chainDigest,b.chainDigest);assert.equal(verifyRegistryProvenanceChain(a,opts).value,true);});
test('registry entry is immutable deterministic and self-verifying',()=>{const a=entry();const b=entry();assert.equal(a.entryDigest,b.entryDigest);assert.equal(Object.isFrozen(a),true);assert.equal(verifyProjectRegistryEntry(a,opts).value,true);});
test('entry rejects duplicate refs and secret-like references',()=>{assert.equal(createProjectRegistryEntry({identity:identity(),checkpointDigest:H('c'),aliases:['a','a'],metadataRefs:[],knowledgeRefs:[],state:'ACTIVE',provenance:provenance()},opts).ok,false);assert.equal(createProjectRegistryEntry({identity:identity(),checkpointDigest:H('c'),aliases:['api_key'],metadataRefs:[],knowledgeRefs:[],state:'ACTIVE',provenance:provenance()},opts).ok,false);});
test('entry verification catches resealed identity-envelope drift',()=>{const e=entry();const forged={...e,identityEnvelopeDigest:H('forged')};const core={projectId:forged.projectId,lineageId:forged.lineageId,repositoryIdentityDigest:forged.repositoryIdentityDigest,sourceIdentityDigest:forged.sourceIdentityDigest,identityEnvelopeDigest:forged.identityEnvelopeDigest,checkpointDigest:forged.checkpointDigest,aliases:forged.aliases,metadataRefs:forged.metadataRefs,knowledgeRefs:forged.knowledgeRefs,state:forged.state,provenanceDigest:forged.provenanceDigest,provenanceSourceDigests:forged.provenanceSourceDigests,privateLocatorRef:forged.privateLocatorRef};forged.entryDigest=H(JSON.stringify(core));assert.equal(verifyProjectRegistryEntry(forged,opts).value,false);});
test('authority boundary is routing-only and cannot create identity/checkpoint',()=>{const b=buildRegistryAuthorityBoundary(entry(),opts).value;assert.equal(b.authoritySource,'EXTERNAL_CANONICAL_ONLY');assert.equal(b.mayCreateIdentity,false);assert.equal(b.mayPromoteCheckpoint,false);});
test('mutation intent binds expected version and operation',()=>{const s=snapshot();const i=createRegistryMutationIntent({mutationId:'mut-1',kind:'ADD',expectedVersion:s.semanticVersion,projectId:P2,proposedEntryDigest:entry({projectId:P2,lineageId:'lineage-b',repo:H('repo-b'),aliases:['beta']}).entryDigest},opts);assert.equal(i.ok,true);});
test('tombstone intent forbids replacement payload',()=>{const s=snapshot();assert.equal(createRegistryMutationIntent({mutationId:'mut-1',kind:'TOMBSTONE',expectedVersion:s.semanticVersion,projectId:P1,proposedEntryDigest:H('x')},opts).ok,false);});

test('index order is deterministic',()=>{const a=entry();const b=entry({projectId:P2,lineageId:'lineage-b',repo:H('repo-b'),aliases:['beta']});const x=buildProjectRegistryIndex([b,a],opts).value;const y=buildProjectRegistryIndex([a,b],opts).value;assert.equal(x.indexDigest,y.indexDigest);});
test('exact project query auto-selects only active unique entry',()=>{const e=entry();const i=buildProjectRegistryIndex([e],opts).value;const r=queryProjectRegistry(i,{projectId:P1},opts).value;assert.equal(r.match,'EXACT');assert.equal(r.selectedEntryDigest,e.entryDigest);});
test('alias-only query is POSSIBLE unless alias capsule is supplied',()=>{const e=entry();const i=buildProjectRegistryIndex([e],opts).value;assert.equal(queryProjectRegistry(i,{alias:'alpha'},opts).value.match,'POSSIBLE');const a=createAliasAdmissionCapsule('alpha',e,opts).value;assert.equal(queryProjectRegistry(i,{alias:'alpha',aliasAdmission:a},opts).value.match,'EXACT');});
test('ambiguous alias becomes CONFLICT, never first-wins',()=>{const a=entry();const b=entry({projectId:P2,lineageId:'lineage-b',repo:H('repo-b'),aliases:['alpha']});const i=buildProjectRegistryIndex([a,b],opts).value;assert.equal(queryProjectRegistry(i,{alias:'alpha'},opts).value.match,'CONFLICT');assert.equal(assessRegistryCollisions(i,opts).value.hasConflict,true);});
test('same repository identity across different project IDs is collision',()=>{const a=entry();const b=entry({projectId:P2,lineageId:'lineage-b',repo:a.repositoryIdentityDigest,aliases:['beta']});const w=assessRegistryCollisions(buildProjectRegistryIndex([a,b],opts).value,opts).value;assert.ok(w.findings.some(x=>x.kind==='REPOSITORY_IDENTITY_COLLISION'));});
test('inactive unique entry is UNKNOWN, not EXACT',()=>{const e=entry({state:'STALE'});const i=buildProjectRegistryIndex([e],opts).value;assert.equal(queryProjectRegistry(i,{projectId:P1},opts).value.match,'UNKNOWN');});
test('query plan is bounded and deterministic',()=>{const a=buildRegistryQueryPlan({projectId:P1,alias:'alpha'},opts).value;const b=buildRegistryQueryPlan({projectId:P1,alias:'alpha'},opts).value;assert.deepEqual(a.indexes,['PROJECT_ID','ALIAS']);assert.equal(a.planDigest,b.planDigest);});
test('knowledge map requires unique IDs and validity binding',()=>{const m=buildRepositoryKnowledgeMap([{knowledgeId:'k1',domain:'scope',refId:'r1',dependencyKeys:['d2','d1'],validityBindingDigest:H('bind')}],H('current'),opts).value;assert.deepEqual(m.items[0].dependencyKeys,['d1','d2']);});
test('negative registry knowledge applies only to current binding',()=>{const k=createNegativeRegistryKnowledge([{keyKind:'CAPABILITY',key:'docker',absenceProofDigest:H('absent'),validityBindingDigest:H('v1')}],opts).value;assert.equal(negativeRegistryKnowledgeApplies(k,'CAPABILITY','docker',H('v1'),opts).value,true);assert.equal(negativeRegistryKnowledgeApplies(k,'CAPABILITY','docker',H('v2'),opts).value,false);});

test('semantic version and fence are deterministic',()=>{const s=snapshot();const v=buildRegistrySemanticVersion(s.snapshotDigest,opts).value;const f=createRegistryPromotionFence(v.version,H('intent'),opts).value;assert.equal(verifyRegistryPromotionFence(f,opts).value,true);assert.equal(compareRegistryVersion(v.version,v.version),'MATCH');});
test('split brain detects divergent successors without newest-wins',()=>{const r=detectRegistrySplitBrain(H('base'),[H('b'),H('a')],opts).value;assert.equal(r.divergent,true);assert.deepEqual(r.successorVersions,[H('a'),H('b')].sort());});
test('freshness is binding-based and flags repository drift',()=>{const e=entry();const v=buildRegistryFreshnessVector(e,{identityEnvelopeDigest:e.identityEnvelopeDigest,repositoryIdentityDigest:H('other'),checkpointDigest:e.checkpointDigest,knowledgeBindingDigest:H('kb')},H('kb'),opts).value;assert.equal(v.repository,'CHANGED');assert.equal(v.stale,true);});
test('freshness unknown fails stale',()=>{const e=entry();const v=buildRegistryFreshnessVector(e,{},H('kb'),opts).value;assert.equal(v.stale,true);assert.equal(v.identity,'UNKNOWN');});
test('stale entries are quarantined, active exact entries remain active',()=>{const a=entry();const b=entry({projectId:P2,lineageId:'lineage-b',repo:H('repo-b'),aliases:['beta']});const va=buildRegistryFreshnessVector(a,{identityEnvelopeDigest:a.identityEnvelopeDigest,repositoryIdentityDigest:a.repositoryIdentityDigest,checkpointDigest:a.checkpointDigest,knowledgeBindingDigest:H('kb')},H('kb'),opts).value;const vb=buildRegistryFreshnessVector(b,{identityEnvelopeDigest:b.identityEnvelopeDigest,repositoryIdentityDigest:H('drift'),checkpointDigest:b.checkpointDigest,knowledgeBindingDigest:H('kb')},H('kb'),opts).value;const q=quarantineStaleEntries([a,b],[va,vb],opts).value;assert.deepEqual(q.activeEntryDigests,[a.entryDigest]);assert.deepEqual(q.quarantinedEntryDigests,[b.entryDigest]);});
test('repair widens conservatively when dependency knowledge incomplete',()=>{const e=entry();const v=buildRegistryFreshnessVector(e,{identityEnvelopeDigest:e.identityEnvelopeDigest,repositoryIdentityDigest:e.repositoryIdentityDigest,checkpointDigest:e.checkpointDigest,knowledgeBindingDigest:H('kb')},H('kb'),opts).value;const r=buildRegistryRepairPlan(e,v,false,opts).value;assert.ok(r.actions.includes('WIDEN_DEPENDENCY_REFRESH'));});
test('negative diagnostic cache is validity-bound',()=>{const c=createNegativeDiagnosticCache([{failureFingerprint:H('failure'),subject:'git-probe',validityBindingDigest:H('v1')}],opts).value;assert.equal(negativeDiagnosticCacheApplies(c,'git-probe',H('failure'),H('v1'),opts).value,true);assert.equal(negativeDiagnosticCacheApplies(c,'git-probe',H('failure'),H('v2'),opts).value,false);});
test('tombstone lineage binds predecessor and mutation intent',()=>{const e=entry();const s=snapshot([e]);const i=createRegistryMutationIntent({mutationId:'drop-1',kind:'TOMBSTONE',expectedVersion:s.semanticVersion,projectId:P1,proposedEntryDigest:null},opts).value;const t=createTombstoneLineageRecord(e,i,opts).value;assert.equal(t.predecessorEntryDigest,e.entryDigest);assert.equal(t.mutationIntentDigest,i.intentDigest);});

test('snapshot is deterministic and verified',()=>{const a=entry();const b=entry({projectId:P2,lineageId:'lineage-b',repo:H('repo-b'),aliases:['beta']});const x=buildRegistrySnapshot([b,a],[],opts).value;const y=buildRegistrySnapshot([a,b],[],opts).value;assert.equal(x.snapshotDigest,y.snapshotDigest);assert.equal(verifyRegistrySnapshot(x,opts).value,true);});
test('size guard fails closed above explicit entry budget',()=>{assert.equal(buildRegistrySnapshot([entry(),entry({projectId:P2,lineageId:'lineage-b',repo:H('repo-b'),aliases:['beta']})],[],{digest,maxEntries:1}).ok,false);});
test('privacy projection removes private locator refs',()=>{const p=projectRegistryPrivacy(snapshot(),opts).value;assert.equal('privateLocatorRef' in p.entries[0],false);assert.equal(JSON.stringify(p).includes('locator-a'),false);});
test('portable envelope reports capability gaps explicitly',()=>{const e=buildRegistryPortabilityEnvelope(snapshot(),['node24','git'],['node24'],opts).value;assert.deepEqual(e.missingCapabilities,['git']);assert.equal(verifyRegistryPortabilityEnvelope(e,opts).value,true);});
test('portable identity mismatch is rejected',()=>{const e=buildRegistryPortabilityEnvelope(snapshot(),[],[],opts).value;assert.equal(validatePortableIdentity(e,{[P1]:{lineageId:'other',repositoryIdentityDigest:H('repo-a')}},opts).value,false);});
test('compaction retains all required refs and records duplicates',()=>{const c=buildRegistryCompactionMap(['a','b','a'],['b'],opts).value;assert.deepEqual(c.retainedRefs,['a','b']);assert.deepEqual(c.droppedDuplicateRefs,['a']);assert.equal(buildRegistryCompactionMap(['a'],['b'],opts).ok,false);});
test('handoff is read-only and exposes unresolved collisions/states',()=>{const a=entry();const b=entry({projectId:P2,lineageId:'lineage-b',repo:a.repositoryIdentityDigest,aliases:['beta']});const h=buildRegistryHandoffContract(buildRegistrySnapshot([a,b],[],opts).value,opts).value;assert.ok(h.unresolved.some(x=>x.startsWith('COLLISION:')));assert.equal('nextAction' in h,false);});
test('integrity receipt detects valid exact snapshot',()=>{const s=snapshot();const r=buildRegistryIntegrityReceipt(s,opts).value;assert.equal(r.valid,true);assert.equal(r.snapshotDigest,s.snapshotDigest);});
test('CAS commit adds entry and returns exact before/after receipt',()=>{const s=buildRegistrySnapshot([],[],opts).value;const e=entry();const i=createRegistryMutationIntent({mutationId:'add-1',kind:'ADD',expectedVersion:s.semanticVersion,projectId:P1,proposedEntryDigest:e.entryDigest},opts).value;const st=store(s);const f=createRegistryPromotionFence(i.expectedVersion,i.intentDigest,opts).value;const r=commitRegistryMutation(st,i,e,f,opts).value;assert.equal(r.beforeVersion,s.semanticVersion);assert.notEqual(r.afterVersion,s.semanticVersion);assert.equal(st.snapshot().entries.length,1);});
test('CAS rejects stale writer without effect',()=>{const s=buildRegistrySnapshot([],[],opts).value;const e=entry();const i=createRegistryMutationIntent({mutationId:'add-1',kind:'ADD',expectedVersion:H('stale'),projectId:P1,proposedEntryDigest:e.entryDigest},opts);assert.equal(i.ok,true);const st=store(s);const f=createRegistryPromotionFence(i.value.expectedVersion,i.value.intentDigest,opts).value;assert.equal(commitRegistryMutation(st,i.value,e,f,opts).ok,false);assert.equal(st.snapshot().entries.length,0);});
test('tombstone commit blocks later resurrection by ADD',()=>{const e=entry();const s=snapshot([e]);const drop=createRegistryMutationIntent({mutationId:'drop-1',kind:'TOMBSTONE',expectedVersion:s.semanticVersion,projectId:P1,proposedEntryDigest:null},opts).value;const st=store(s);const df=createRegistryPromotionFence(drop.expectedVersion,drop.intentDigest,opts).value;assert.equal(commitRegistryMutation(st,drop,null,df,opts).ok,true);const after=st.snapshot();const fresh=entry({aliases:['alpha2']});const add=createRegistryMutationIntent({mutationId:'add-2',kind:'ADD',expectedVersion:after.semanticVersion,projectId:P1,proposedEntryDigest:fresh.entryDigest},opts).value;const af=createRegistryPromotionFence(add.expectedVersion,add.intentDigest,opts).value;assert.equal(commitRegistryMutation(st,add,fresh,af,opts).ok,false);});
test('store exceptions are sanitized into typed failure',()=>{const s=snapshot();const bad={load(){throw new Error('SECRET_VALUE');},compareAndSwap(){return false;},snapshot(){return s;}};const i=createRegistryMutationIntent({mutationId:'x',kind:'TOMBSTONE',expectedVersion:s.semanticVersion,projectId:P1,proposedEntryDigest:null},opts).value;const f=createRegistryPromotionFence(i.expectedVersion,i.intentDigest,opts).value;const r=commitRegistryMutation(bad,i,null,f,opts);assert.equal(r.ok,false);assert.equal(JSON.stringify(r).includes('SECRET_VALUE'),false);});
test('cancellation fails closed before identity construction',()=>{const r=createRegistryIdentityEnvelope({projectId:P1,lineageId:'x',repositoryIdentityDigest:H('r'),sourceIdentityDigest:H('s')},{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);});
test('malformed digest capability fails closed',()=>{const r=createRegistryIdentityEnvelope({projectId:P1,lineageId:'x',repositoryIdentityDigest:H('r'),sourceIdentityDigest:H('s')},{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);});
