import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRegistryIdentityEnvelope,createRegistryProvenanceChain,createProjectRegistryEntry,verifyProjectRegistryEntry,buildProjectRegistryIndex,queryProjectRegistry,createAliasAdmissionCapsule,buildRegistrySnapshot,verifyRegistrySnapshot,buildRegistryPortabilityEnvelope,verifyRegistryPortabilityEnvelope,createRegistryMutationIntent,createRegistryPromotionFence,createNegativeRegistryKnowledge,negativeRegistryKnowledgeApplies,createNegativeDiagnosticCache,negativeDiagnosticCacheApplies,createTombstoneLineageRecord,commitRegistryMutation} from '../packages/project-registry/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')};const opts={digest};const H=x=>`sha256:${createHash('sha256').update(x).digest('hex')}`;const P='11111111-1111-4111-8111-111111111111';
function entry(){const i=createRegistryIdentityEnvelope({projectId:P,lineageId:'lineage-a',repositoryIdentityDigest:H('repo'),sourceIdentityDigest:H('source')},opts).value;const p=createRegistryProvenanceChain([H('doc')],opts).value;return createProjectRegistryEntry({identity:i,checkpointDigest:H('cp'),aliases:['alpha'],metadataRefs:['meta'],knowledgeRefs:['know'],state:'ACTIVE',provenance:p,privateLocatorRef:'loc-ref'},opts).value;}
test('resealed provenance tampering is rejected',()=>{const e=entry();const forged={...e,provenanceDigest:H('other')};assert.equal(verifyProjectRegistryEntry(forged,opts).value,false);});
test('resealed repository identity drift is rejected by identity envelope binding',()=>{const e=entry();const forged={...e,repositoryIdentityDigest:H('other')};assert.equal(verifyProjectRegistryEntry(forged,opts).value,false);});
test('tampered index digest cannot be queried',()=>{const e=entry();const i=buildProjectRegistryIndex([e],opts).value;assert.equal(queryProjectRegistry({...i,indexDigest:H('bad')},{projectId:P},opts).ok,false);});
test('forged alias capsule does not create EXACT match',()=>{const e=entry();const i=buildProjectRegistryIndex([e],opts).value;const a=createAliasAdmissionCapsule('alpha',e,opts).value;const forged={...a,lineageId:'other'};assert.notEqual(queryProjectRegistry(i,{alias:'alpha',aliasAdmission:forged},opts).value.match,'EXACT');});
test('tampered snapshot is rejected by verifier',()=>{const s=buildRegistrySnapshot([entry()],[],opts).value;assert.equal(verifyRegistrySnapshot({...s,semanticVersion:H('bad')},opts).value,false);});
test('tampered portability projection is rejected',()=>{const p=buildRegistryPortabilityEnvelope(buildRegistrySnapshot([entry()],[],opts).value,[],[],opts).value;const forged={...p,projection:{...p.projection,entries:[{...p.projection.entries[0],lineageId:'other'}]}};assert.equal(verifyRegistryPortabilityEnvelope(forged,opts).value,false);});
test('store lying after CAS cannot produce success receipt',()=>{const initial=buildRegistrySnapshot([],[],opts).value;const e=entry();const i=createRegistryMutationIntent({mutationId:'add',kind:'ADD',expectedVersion:initial.semanticVersion,projectId:P,proposedEntryDigest:e.entryDigest},opts).value;const liar={load(){return initial;},compareAndSwap(){return true;},snapshot(){return initial;}};const f=createRegistryPromotionFence(i.expectedVersion,i.intentDigest,opts).value;assert.equal(commitRegistryMutation(liar,i,e,f,opts).ok,false);});
test('UPDATE cannot rebind lineage or repository identity',()=>{const original=entry();const initial=buildRegistrySnapshot([original],[],opts).value;const i2=createRegistryIdentityEnvelope({projectId:P,lineageId:'lineage-b',repositoryIdentityDigest:H('other-repo'),sourceIdentityDigest:H('source')},opts).value;const p2=createRegistryProvenanceChain([H('doc')],opts).value;const changed=createProjectRegistryEntry({identity:i2,checkpointDigest:H('cp2'),aliases:['alpha'],metadataRefs:['meta'],knowledgeRefs:['know'],state:'ACTIVE',provenance:p2},opts).value;const intent=createRegistryMutationIntent({mutationId:'upd',kind:'UPDATE',expectedVersion:initial.semanticVersion,projectId:P,proposedEntryDigest:changed.entryDigest},opts).value;let state=initial;const st={load(){return state;},compareAndSwap(expected,next){if(expected!==state.semanticVersion)return false;state=next;return true;},snapshot(){return state;}};const f=createRegistryPromotionFence(intent.expectedVersion,intent.intentDigest,opts).value;assert.equal(commitRegistryMutation(st,intent,changed,f,opts).ok,false);assert.equal(st.snapshot().snapshotDigest,initial.snapshotDigest);});
test('tampered negative registry knowledge cannot suppress lookup',()=>{const k=createNegativeRegistryKnowledge([{keyKind:'CAPABILITY',key:'docker',absenceProofDigest:H('a'),validityBindingDigest:H('v')}],opts).value;const forged={...k,entries:[{...k.entries[0],key:'git'}]};const r=negativeRegistryKnowledgeApplies(forged,'CAPABILITY','git',H('v'),opts);assert.equal(r.ok,false);});
test('tampered negative diagnostic cache cannot suppress diagnostics',()=>{const c=createNegativeDiagnosticCache([{failureFingerprint:H('f'),subject:'probe',validityBindingDigest:H('v')}],opts).value;const forged={...c,entries:[{...c.entries[0],subject:'other'}]};const r=negativeDiagnosticCacheApplies(forged,'other',H('f'),H('v'),opts);assert.equal(r.ok,false);});
test('tampered tombstone lineage is rejected by snapshot construction',()=>{const e=entry();const s=buildRegistrySnapshot([e],[],opts).value;const i=createRegistryMutationIntent({mutationId:'drop',kind:'TOMBSTONE',expectedVersion:s.semanticVersion,projectId:P,proposedEntryDigest:null},opts).value;const t=createTombstoneLineageRecord(e,i,opts).value;assert.equal(buildRegistrySnapshot([e],[{...t,lineageId:'forged'}],opts).ok,false);});
test('wrong promotion fence blocks commit before store mutation',()=>{const initial=buildRegistrySnapshot([],[],opts).value;const e=entry();const i=createRegistryMutationIntent({mutationId:'add',kind:'ADD',expectedVersion:initial.semanticVersion,projectId:P,proposedEntryDigest:e.entryDigest},opts).value;const wrong=createRegistryPromotionFence(i.expectedVersion,H('different-intent'),opts).value;let calls=0;const st={load(){calls++;return initial;},compareAndSwap(){calls++;return true;},snapshot(){calls++;return initial;}};const r=commitRegistryMutation(st,i,e,wrong,opts);assert.equal(r.ok,false);assert.equal(calls,0);});
test('stale promotion fence blocks before CAS when store version moved',()=>{const initial=buildRegistrySnapshot([],[],opts).value;const e=entry();const i=createRegistryMutationIntent({mutationId:'add',kind:'ADD',expectedVersion:initial.semanticVersion,projectId:P,proposedEntryDigest:e.entryDigest},opts).value;const fence=createRegistryPromotionFence(i.expectedVersion,i.intentDigest,opts).value;const moved=buildRegistrySnapshot([e],[],opts).value;let cas=0;const st={load(){return moved;},compareAndSwap(){cas++;return true;},snapshot(){return moved;}};const r=commitRegistryMutation(st,i,e,fence,opts);assert.equal(r.ok,false);assert.equal(cas,0);});
