import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createSourceBoundFieldClaim,createResponseSchemaEnvelope,createResponseContractCapsule,defaultMetricOwnershipMatrix,createBaselineAvailabilityWitness,createDelegatedMetricClaim,createBlockerProjection,createStateConflictWitness,createNextNecessaryActionCapsule,buildMachineResponseEnvelope,verifyMachineResponseEnvelope,buildHumanResponseProjection,verifyHumanResponseProjection,buildResponseIntegrityReceipt,detectStaleResponse,createConfidenceEnvelope,createUnavailableMetric,checkResponseCompatibility}from'../packages/response-contract/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')};const opts={digest};const H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;const matrix=defaultMetricOwnershipMatrix(opts).value;
const f=(name,value=name,extra={})=>createSourceBoundFieldClaim({field:name,value,ownerDomain:extra.ownerDomain??'checkpoint',subjectId:name,sourceIdentityDigest:extra.sourceIdentityDigest??H(`s:${name}`),validityBindingDigest:extra.validityBindingDigest??H(`v:${name}`),freshness:extra.freshness??'CURRENT'},opts).value;
function cap(extra={}){const fields=extra.fields??[f('phase','PRODUCTION'),f('current_work','M20'),f('completed','M00-M19'),f('remaining','M20-M63')];return createResponseContractCapsule({projectId:'gef-bootstrap',responseKind:'checkpoint',checkpointBindingDigest:extra.checkpoint??H('cp'),resumeBindingDigest:extra.resume??H('resume'),registryBindingDigest:extra.registry??H('registry'),sourceClaims:fields,verdictInputDigest:H('vin'),nextActionSourceDigest:H('nas'),schema:createResponseSchemaEnvelope('standard',['structured'],opts).value},opts).value;}
function metric(){const b=createBaselineAvailabilityWitness('project_completion','M21_PROGRESS',H('base'),H('obs'),opts).value;return createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:32.44,unit:'percent',sourceIdentityDigest:H('ms'),validityBindingDigest:H('mv'),baseline:b,confidence:createConfidenceEnvelope('MEDIUM','MEDIUM',H('conf'),opts).value},matrix,opts).value;}
const action=()=>createNextNecessaryActionCapsule('KNOWN','IMPLEMENT_GBS_M20',H('ns'),H('nv'),opts).value;
function machine(extra={}){return buildMachineResponseEnvelope({capsule:extra.capsule??cap(),metrics:extra.metrics??[metric()],blockers:extra.blockers??[],conflicts:extra.conflicts??[],nextAction:extra.nextAction??action(),requiredFields:['phase','current_work','completed','remaining'],requestedVerdict:extra.requestedVerdict},matrix,extra.options??opts);}
test('resealed field value tamper cannot enter machine response',()=>{const x=f('phase','PRODUCTION');const forged={...x,value:'DONE',claimDigest:H('forged')};assert.equal(machine({capsule:cap({fields:[forged,f('current_work','M20'),f('completed','M00-M19'),f('remaining','M20-M63')]})}).ok,false);});
test('schema digest tampering is rejected',()=>{const c=cap();const bad={...c,schema:{...c.schema,schemaDigest:H('bad')}};assert.equal(machine({capsule:bad}).ok,false);});
test('checkpoint mix-and-match breaks capsule verification',()=>{const c=cap();assert.equal(machine({capsule:{...c,checkpointBindingDigest:H('other')}}).ok,false);});
test('metric value reseal attempt fails verification',()=>{const m=machine().value;const forged={...m,metrics:[{...m.metrics[0],scalarValue:99}]};assert.equal(verifyMachineResponseEnvelope(forged,matrix,opts).value,false);});
test('metric owner cannot be relabeled as M20 or wrong domain',()=>{const u=createUnavailableMetric('eta','M22_ESTIMATION','NOT_YET_BASELINED',H('s'),H('v'),matrix,opts).value;assert.equal(createDelegatedMetricClaim({...u,owner:'M21_PROGRESS'},matrix,opts).ok,false);});
test('confidence envelope digest tamper rejects metric',()=>{const b=createBaselineAvailabilityWitness('project_completion','M21_PROGRESS',H('base'),H('obs'),opts).value;const conf=createConfidenceEnvelope('LOW','LOW',H('c'),opts).value;const bad={...conf,envelopeDigest:H('bad')};assert.equal(createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:1,sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),baseline:b,confidence:bad},matrix,opts).ok,false);});
test('optimistic SUCCESS cannot override recovery blocker',()=>{const b=createBlockerProjection({blockerId:'r',classification:'RECOVERY',disposition:'ACTIVE',sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),freshness:'CURRENT',message:'Recovery is required'},opts).value;assert.equal(machine({blockers:[b],requestedVerdict:'SUCCESS'}).value.verdict.verdict,'RECOVERY_REQUIRED');});
test('optimistic SUCCESS cannot override conflict witness',()=>{const w=createStateConflictWitness('checkpoint',[H('a'),H('b')],opts).value;assert.equal(machine({conflicts:[w],requestedVerdict:'SUCCESS'}).value.verdict.verdict,'CONFLICT');});
test('tampered blocker digest fails machine verification',()=>{const b=createBlockerProjection({blockerId:'b',classification:'BLOCKING',disposition:'ACTIVE',sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),freshness:'CURRENT',message:'Blocked'},opts).value;const m=machine({blockers:[b]}).value;assert.equal(verifyMachineResponseEnvelope({...m,blockers:[{...b,blockerDigest:H('bad')}]},matrix,opts).value,false);});
test('tampered next-action digest fails machine verification',()=>{const m=machine().value;assert.equal(verifyMachineResponseEnvelope({...m,nextAction:{...m.nextAction,capsuleDigest:H('bad')}},matrix,opts).value,false);});
test('secret-like source value blocks public machine envelope',()=>{const fields=[f('phase','PRODUCTION'),f('current_work','api_token=abc'),f('completed','M00-M19'),f('remaining','M20-M63')];assert.equal(machine({capsule:cap({fields})}).ok,false);});
test('private path source value blocks public machine envelope',()=>{const fields=[f('phase','PRODUCTION'),f('current_work','/home/alice/project'),f('completed','M00-M19'),f('remaining','M20-M63')];assert.equal(machine({capsule:cap({fields})}).ok,false);});
test('mandatory truth overflow fails instead of truncating',()=>{assert.equal(machine({options:{digest,maxBytes:256}}).ok,false);});
test('human projection cannot append hidden authority claim',()=>{const m=machine().value,h=buildHumanResponseProjection(m,matrix,opts).value;const forged={...h,materialClaimDigests:[...h.materialClaimDigests,H('hidden')]};assert.equal(verifyHumanResponseProjection(forged,m,matrix,opts).value,false);});
test('human projection cannot rewrite a metric value',()=>{const m=machine().value,h=buildHumanResponseProjection(m,matrix,opts).value;const lines=h.lines.map(x=>x.startsWith('metric.project_completion=')?'metric.project_completion=100 percent':x);assert.equal(verifyHumanResponseProjection({...h,lines},m,matrix,opts).value,false);});
test('integrity receipt marks invalid human mix-and-match false by rejection',()=>{const a=machine().value,b=machine({capsule:cap({checkpoint:H('cp2')})}).value;const hb=buildHumanResponseProjection(b,matrix,opts).value;const r=buildResponseIntegrityReceipt(a,hb,matrix,opts);assert.equal(r.ok,true);assert.equal(r.value.valid,false);});
test('stale sentinel fails closed when field observations are omitted',()=>{const m=machine().value;const r=detectStaleResponse(m,{checkpointBindingDigest:m.checkpointBindingDigest,resumeBindingDigest:m.resumeBindingDigest,registryBindingDigest:m.registryBindingDigest,metricValidityBindings:Object.fromEntries(m.metrics.map(x=>[x.metricKey,x.validityBindingDigest]))},opts).value;assert.equal(r.stale,true);assert.ok(r.staleSubjects.some(x=>x.startsWith('field:')));});
test('stale sentinel fails closed when metric observations are omitted',()=>{const m=machine().value;const r=detectStaleResponse(m,{checkpointBindingDigest:m.checkpointBindingDigest,resumeBindingDigest:m.resumeBindingDigest,registryBindingDigest:m.registryBindingDigest,fieldValidityBindings:Object.fromEntries(m.fields.map(x=>[x.field,x.validityBindingDigest]))},opts).value;assert.equal(r.stale,true);assert.ok(r.staleSubjects.some(x=>x.startsWith('metric:')));});
test('unsupported schema/profile/capability does not silently downgrade',()=>{const s=cap().schema;const r=checkResponseCompatibility(s,{supportedSchemaVersions:[2],supportedProfiles:['legacy'],capabilities:[]},opts).value;assert.equal(r.compatible,false);assert.ok(r.reasons.includes('UNSUPPORTED_SCHEMA_VERSION'));assert.ok(r.reasons.includes('UNSUPPORTED_PROFILE'));assert.ok(r.reasons.includes('MISSING_CAPABILITY'));});
test('cancellation fails closed before claim construction',()=>{assert.equal(createSourceBoundFieldClaim({field:'x',value:'x',ownerDomain:'checkpoint',subjectId:'x',sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),freshness:'CURRENT'},{digest,cancellation:{isCancelled:()=>true}}).ok,false);});
test('non-sha digest provider fails closed',()=>{const bad={algorithm:'sha256',digest:()=> 'abc'};assert.equal(createResponseSchemaEnvelope('standard',[],{digest:bad}).ok,false);});
