import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createSourceBoundFieldClaim,createResponseSchemaEnvelope,createResponseContractCapsule,defaultMetricOwnershipMatrix,createBaselineAvailabilityWitness,createDelegatedMetricClaim,createBlockerProjection,createStateConflictWitness,createNextNecessaryActionCapsule,createResponseVerdictClaim,buildMachineResponseEnvelope,verifyMachineResponseEnvelope,buildHumanResponseProjection,verifyHumanResponseProjection,buildResponseIntegrityReceipt,detectStaleResponse,createConfidenceEnvelope,createUnavailableMetric,checkResponseCompatibility,verifyDelegatedMetricClaim}from'../packages/response-contract/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`,matrix=defaultMetricOwnershipMatrix(opts).value;
const f=(name,value=name,extra={})=>createSourceBoundFieldClaim({field:name,value,ownerDomain:extra.ownerDomain??'checkpoint',subjectId:name,sourceIdentityDigest:extra.sourceIdentityDigest??H(`s:${name}`),validityBindingDigest:extra.validityBindingDigest??H(`v:${name}`),freshness:extra.freshness??'CURRENT'},opts).value;
const verdict=(v='SUCCESS',extra={})=>createResponseVerdictClaim(v,extra.sourceIdentityDigest??H('verdict-source'),extra.validityBindingDigest??H('verdict-valid'),opts).value;
function cap(extra={}){const vc=extra.verdictClaim??verdict(),fields=extra.fields??[f('phase','PRODUCTION'),f('current_work','M20'),f('completed','M00-M19'),f('remaining','M20-M63')];return createResponseContractCapsule({projectId:'gef-bootstrap',responseKind:'checkpoint',checkpointBindingDigest:extra.checkpoint??H('cp'),resumeBindingDigest:extra.resume??H('resume'),registryBindingDigest:extra.registry??H('registry'),sourceClaims:fields,verdictInputDigest:vc.claimDigest,nextActionSourceDigest:H('next-source'),schema:createResponseSchemaEnvelope('standard',['structured'],opts).value},opts).value;}
function metric(){const b=createBaselineAvailabilityWitness('project_completion','M21_PROGRESS',H('base'),H('obs'),opts).value;return createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:32.44,unit:'percent',sourceIdentityDigest:H('ms'),validityBindingDigest:H('mv'),baseline:b,confidence:createConfidenceEnvelope('MEDIUM','MEDIUM',H('conf'),opts).value},matrix,opts).value;}
const action=()=>createNextNecessaryActionCapsule('KNOWN','IMPLEMENT_GBS_M20',H('next-source'),H('nv'),opts).value;
function machine(extra={}){const vc=extra.verdictClaim??verdict();return buildMachineResponseEnvelope({capsule:extra.capsule??cap({verdictClaim:vc}),metrics:extra.metrics??[metric()],blockers:extra.blockers??[],conflicts:extra.conflicts??[],nextAction:extra.nextAction??action(),verdictClaim:vc,requiredFields:['phase','current_work','completed','remaining']},matrix,extra.options??opts);}
const observation=m=>({checkpointBindingDigest:m.checkpointBindingDigest,resumeBindingDigest:m.resumeBindingDigest,registryBindingDigest:m.registryBindingDigest,verdictValidityBinding:m.verdictClaim.validityBindingDigest,fieldValidityBindings:Object.fromEntries(m.fields.map(x=>[x.field,x.validityBindingDigest])),metricValidityBindings:Object.fromEntries(m.metrics.map(x=>[x.metricKey,x.validityBindingDigest]))});

test('resealed field value tamper is rejected at capsule boundary',()=>{const x=f('phase','PRODUCTION'),forged={...x,value:'DONE',claimDigest:H('forged')},vc=verdict();assert.equal(createResponseContractCapsule({projectId:'gef-bootstrap',responseKind:'checkpoint',checkpointBindingDigest:H('cp'),resumeBindingDigest:H('resume'),registryBindingDigest:H('registry'),sourceClaims:[forged,f('current_work','M20'),f('completed','M00-M19'),f('remaining','M20-M63')],verdictInputDigest:vc.claimDigest,nextActionSourceDigest:H('next-source'),schema:createResponseSchemaEnvelope('standard',['structured'],opts).value},opts).ok,false);});
test('schema digest tampering is rejected',()=>{const c=cap();assert.equal(machine({capsule:{...c,schema:{...c.schema,schemaDigest:H('bad')}}}).ok,false);});
test('checkpoint mix-and-match breaks capsule verification',()=>{const c=cap();assert.equal(machine({capsule:{...c,checkpointBindingDigest:H('other')}}).ok,false);});
test('next action source mix-and-match is rejected',()=>{const wrong=createNextNecessaryActionCapsule('KNOWN','IMPLEMENT_GBS_M20',H('other-source'),H('nv'),opts).value;assert.equal(machine({nextAction:wrong}).ok,false);});
test('unbound stronger verdict claim cannot fabricate response state',()=>{const success=verdict('SUCCESS'),recovery=verdict('RECOVERY_REQUIRED');assert.equal(machine({capsule:cap({verdictClaim:success}),verdictClaim:recovery}).ok,false);});
test('tampered verdict claim is rejected by machine verifier',()=>{const m=machine().value;assert.equal(verifyMachineResponseEnvelope({...m,verdictClaim:{...m.verdictClaim,verdict:'RECOVERY_REQUIRED'}},matrix,opts).value,false);});
test('canonical stronger verdict works only when capsule binds its claim',()=>{const vc=verdict('PARTIAL');const m=machine({capsule:cap({verdictClaim:vc}),verdictClaim:vc}).value;assert.equal(m.verdict.verdict,'PARTIAL');});
test('metric value reseal attempt fails verification',()=>{const m=machine().value;assert.equal(verifyMachineResponseEnvelope({...m,metrics:[{...m.metrics[0],scalarValue:99}]},matrix,opts).value,false);});
test('metric owner cannot be relabeled or moved to wrong domain',()=>{const u=createUnavailableMetric('eta','M22_ESTIMATION','NOT_YET_BASELINED',H('s'),H('v'),matrix,opts).value;assert.equal(createDelegatedMetricClaim({...u,owner:'M21_PROGRESS'},matrix,opts).ok,false);});
test('embedded baseline witness tampering invalidates metric claim',()=>{const m=metric(),forged={...m,baseline:{...m.baseline,observationDigest:H('other')}};assert.equal(verifyDelegatedMetricClaim(forged,matrix,opts).value,false);});
test('confidence envelope digest tamper rejects metric',()=>{const b=createBaselineAvailabilityWitness('project_completion','M21_PROGRESS',H('base'),H('obs'),opts).value,conf=createConfidenceEnvelope('LOW','LOW',H('c'),opts).value;assert.equal(createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:1,sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),baseline:b,confidence:{...conf,envelopeDigest:H('bad')}},matrix,opts).ok,false);});
test('canonical SUCCESS cannot override recovery blocker',()=>{const b=createBlockerProjection({blockerId:'r',classification:'RECOVERY',disposition:'ACTIVE',sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),freshness:'CURRENT',message:'Recovery is required'},opts).value;assert.equal(machine({blockers:[b]}).value.verdict.verdict,'RECOVERY_REQUIRED');});
test('canonical SUCCESS cannot override conflict witness',()=>{const w=createStateConflictWitness('checkpoint',[H('a'),H('b')],opts).value;assert.equal(machine({conflicts:[w]}).value.verdict.verdict,'CONFLICT');});
test('same field with divergent canonical values creates conflict witness',()=>{const fields=[f('phase','PRODUCTION',{sourceIdentityDigest:H('s1')}),f('phase','DONE',{sourceIdentityDigest:H('s2')}),f('current_work','M20'),f('completed','M00-M19'),f('remaining','M20-M63')],vc=verdict(),m=machine({capsule:cap({fields,verdictClaim:vc}),verdictClaim:vc}).value;assert.equal(m.verdict.verdict,'CONFLICT');assert.ok(m.conflicts.some(w=>w.subject==='field:phase'&&w.hasConflict));});
test('same text from different authorities is preserved without false conflict',()=>{const fields=[f('phase','PRODUCTION',{sourceIdentityDigest:H('s1')}),f('phase','PRODUCTION',{sourceIdentityDigest:H('s2'),validityBindingDigest:H('v2')}),f('current_work','M20'),f('completed','M00-M19'),f('remaining','M20-M63')],vc=verdict(),m=machine({capsule:cap({fields,verdictClaim:vc}),verdictClaim:vc}).value;assert.equal(m.verdict.verdict,'SUCCESS');assert.equal(m.fields.filter(x=>x.field==='phase').length,2);});
test('tampered blocker digest fails machine verification',()=>{const b=createBlockerProjection({blockerId:'b',classification:'BLOCKING',disposition:'ACTIVE',sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),freshness:'CURRENT',message:'Blocked'},opts).value,m=machine({blockers:[b]}).value;assert.equal(verifyMachineResponseEnvelope({...m,blockers:[{...b,blockerDigest:H('bad')}]},matrix,opts).value,false);});
test('tampered next-action digest fails machine verification',()=>{const m=machine().value;assert.equal(verifyMachineResponseEnvelope({...m,nextAction:{...m.nextAction,capsuleDigest:H('bad')}},matrix,opts).value,false);});
test('secret-like source value blocks public machine envelope',()=>{const fields=[f('phase','PRODUCTION'),f('current_work','api_token=abc'),f('completed','M00-M19'),f('remaining','M20-M63')],vc=verdict();assert.equal(machine({capsule:cap({fields,verdictClaim:vc}),verdictClaim:vc}).ok,false);});
test('private path source value blocks public machine envelope',()=>{const fields=[f('phase','PRODUCTION'),f('current_work','/home/alice/project'),f('completed','M00-M19'),f('remaining','M20-M63')],vc=verdict();assert.equal(machine({capsule:cap({fields,verdictClaim:vc}),verdictClaim:vc}).ok,false);});
test('mandatory truth overflow fails instead of truncating',()=>{assert.equal(machine({options:{digest,maxBytes:256}}).ok,false);});
test('human projection cannot append hidden authority claim',()=>{const m=machine().value,h=buildHumanResponseProjection(m,matrix,opts).value;assert.equal(verifyHumanResponseProjection({...h,materialClaimDigests:[...h.materialClaimDigests,H('hidden')]},m,matrix,opts).value,false);});
test('human projection cannot rewrite a metric value',()=>{const m=machine().value,h=buildHumanResponseProjection(m,matrix,opts).value,lines=h.lines.map(x=>x.startsWith('metric.project_completion=')?'metric.project_completion=100 percent':x);assert.equal(verifyHumanResponseProjection({...h,lines},m,matrix,opts).value,false);});
test('integrity receipt rejects human mix-and-match as invalid',()=>{const a=machine().value,b=machine({capsule:cap({checkpoint:H('cp2')})}).value,hb=buildHumanResponseProjection(b,matrix,opts).value,r=buildResponseIntegrityReceipt(a,hb,matrix,opts);assert.equal(r.ok,true);assert.equal(r.value.valid,false);});
test('stale sentinel fails closed when field observations are omitted',()=>{const m=machine().value,o=observation(m);delete o.fieldValidityBindings;const r=detectStaleResponse(m,o,matrix,opts).value;assert.equal(r.stale,true);assert.ok(r.staleSubjects.some(x=>x.startsWith('field:')));});
test('stale sentinel fails closed when metric observations are omitted',()=>{const m=machine().value,o=observation(m);delete o.metricValidityBindings;const r=detectStaleResponse(m,o,matrix,opts).value;assert.equal(r.stale,true);assert.ok(r.staleSubjects.some(x=>x.startsWith('metric:')));});
test('stale sentinel fails closed when verdict observation is omitted',()=>{const m=machine().value,o=observation(m);delete o.verdictValidityBinding;assert.ok(detectStaleResponse(m,o,matrix,opts).value.staleSubjects.includes('verdict'));});
test('stale sentinel refuses tampered machine response',()=>{const m=machine().value;assert.equal(detectStaleResponse({...m,machineDigest:H('bad')},observation(m),matrix,opts).ok,false);});
test('unsupported schema profile capability does not silently downgrade',()=>{const s=cap().schema,r=checkResponseCompatibility(s,{supportedSchemaVersions:[2],supportedProfiles:['legacy'],capabilities:[]},opts).value;assert.equal(r.compatible,false);assert.ok(r.reasons.includes('UNSUPPORTED_SCHEMA_VERSION'));assert.ok(r.reasons.includes('UNSUPPORTED_PROFILE'));assert.ok(r.reasons.includes('MISSING_CAPABILITY'));});
test('compatibility gate rejects tampered schema before negotiation',()=>{const s=cap().schema;assert.equal(checkResponseCompatibility({...s,schemaDigest:H('bad')},{supportedSchemaVersions:[1],supportedProfiles:['standard'],capabilities:['structured']},opts).ok,false);});
test('cancellation fails closed before claim construction',()=>{assert.equal(createSourceBoundFieldClaim({field:'x',value:'x',ownerDomain:'checkpoint',subjectId:'x',sourceIdentityDigest:H('s'),validityBindingDigest:H('v'),freshness:'CURRENT'},{digest,cancellation:{isCancelled:()=>true}}).ok,false);});
test('non-sha digest provider fails closed',()=>{assert.equal(createResponseSchemaEnvelope('standard',[],{digest:{algorithm:'sha256',digest:()=> 'abc'}}).ok,false);});
