import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {
 createSourceBoundFieldClaim,verifySourceBoundFieldClaim,buildResponseProvenanceIndex,createResponseSchemaEnvelope,verifyResponseSchemaEnvelope,createResponseContractCapsule,verifyResponseContractCapsule,createResponseAuthorityBoundary,
 buildMetricOwnershipMatrix,defaultMetricOwnershipMatrix,createBaselineAvailabilityWitness,verifyBaselineAvailabilityWitness,createConfidenceEnvelope,createDelegatedMetricClaim,verifyDelegatedMetricClaim,createUnavailableMetric,
 createBlockerProjection,projectApplicableBlockers,createStateConflictWitness,createNextNecessaryActionCapsule,deriveResponseVerdict,
 semanticDeduplicateClaims,buildMinimumSufficientResponseFields,assessResponseRedaction,assessResponseSize,
 buildMachineResponseEnvelope,verifyMachineResponseEnvelope,buildHumanResponseProjection,verifyHumanResponseProjection,buildResponseIntegrityReceipt,checkResponseCompatibility,detectStaleResponse
}from'../packages/response-contract/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')};
const opts={digest};
const H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
function field(name,value=name,extra={}){return createSourceBoundFieldClaim({field:name,value,ownerDomain:extra.ownerDomain??'checkpoint',subjectId:extra.subjectId??name,sourceIdentityDigest:extra.sourceIdentityDigest??H(`source:${name}`),validityBindingDigest:extra.validityBindingDigest??H(`valid:${name}`),freshness:extra.freshness??'CURRENT'},opts).value;}
function schema(){return createResponseSchemaEnvelope('standard',['structured'],opts).value;}
function capsule(fields=[field('phase','PRODUCTION'),field('current_work','M20'),field('completed','M00-M19'),field('remaining','M20-M63')]){return createResponseContractCapsule({projectId:'gef-bootstrap',responseKind:'checkpoint',checkpointBindingDigest:H('checkpoint'),resumeBindingDigest:H('resume'),registryBindingDigest:H('registry'),sourceClaims:fields,verdictInputDigest:H('verdict-input'),nextActionSourceDigest:H('next-source'),schema:schema()},opts).value;}
const matrix=defaultMetricOwnershipMatrix(opts).value;
function baseline(key='project_completion',owner='M21_PROGRESS'){return createBaselineAvailabilityWitness(key,owner,H(`baseline:${key}`),H(`observation:${key}`),opts).value;}
function metric(key='project_completion',value=32.44){return createDelegatedMetricClaim({metricKey:key,owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:value,unit:'percent',precision:2,sourceIdentityDigest:H(`metric-source:${key}`),validityBindingDigest:H(`metric-valid:${key}`),baseline:baseline(key),confidence:createConfidenceEnvelope('HIGH','HIGH',H(`confidence:${key}`),opts).value},matrix,opts).value;}
function blocker(extra={}){return createBlockerProjection({blockerId:extra.blockerId??'b1',classification:extra.classification??'BLOCKING',disposition:extra.disposition??'ACTIVE',sourceIdentityDigest:H(`blocker-source:${extra.blockerId??'b1'}`),validityBindingDigest:H(`blocker-valid:${extra.blockerId??'b1'}`),freshness:extra.freshness??'CURRENT',message:extra.message??'Required gate is not satisfied'},opts).value;}
function next(state='KNOWN'){return createNextNecessaryActionCapsule(state,state==='KNOWN'?'IMPLEMENT_GBS_M20':null,H('next-source'),H('next-valid'),opts).value;}
function machine(extra={}){return buildMachineResponseEnvelope({capsule:extra.capsule??capsule(),metrics:extra.metrics??[metric()],blockers:extra.blockers??[],conflicts:extra.conflicts??[],nextAction:extra.nextAction??next(),requiredFields:extra.requiredFields??['phase','current_work','completed','remaining'],partial:extra.partial,indeterminate:extra.indeterminate,requestedVerdict:extra.requestedVerdict},matrix,extra.options??opts).value;}

test('source-bound field claim is deterministic immutable and verified',()=>{const a=field('phase','PRODUCTION');const b=field('phase','PRODUCTION');assert.equal(a.claimDigest,b.claimDigest);assert.equal(Object.isFrozen(a),true);assert.equal(verifySourceBoundFieldClaim(a,opts).value,true);});
test('field claim tampering is detected',()=>{const a=field('phase','PRODUCTION');assert.equal(verifySourceBoundFieldClaim({...a,value:'DONE'},opts).value,false);});
test('provenance index is order independent',()=>{const a=field('a'),b=field('b');assert.equal(buildResponseProvenanceIndex([b,a],opts).value.indexDigest,buildResponseProvenanceIndex([a,b],opts).value.indexDigest);});
test('schema envelope is explicit and self verifying',()=>{const s=schema();assert.equal(s.schemaVersion,1);assert.equal(verifyResponseSchemaEnvelope(s,opts).value,true);assert.equal(verifyResponseSchemaEnvelope({...s,schemaVersion:2},opts).value,false);});
test('response capsule is source-order independent and verified',()=>{const a=field('a'),b=field('b');const x=capsule([b,a]),y=capsule([a,b]);assert.equal(x.capsuleDigest,y.capsuleDigest);assert.equal(verifyResponseContractCapsule(x,opts).value,true);});
test('authority boundary cannot create truth or compute owned metrics',()=>{const b=createResponseAuthorityBoundary(capsule(),opts).value;assert.equal(b.authoritySource,'EXTERNAL_CANONICAL_ONLY');assert.equal(b.mayCreateCanonicalFacts,false);assert.equal(b.mayComputeProgress,false);assert.equal(b.mayComputeEta,false);assert.equal(b.mayComputeProjectStatus,false);});
test('metric ownership matrix rejects duplicate owners',()=>{assert.equal(buildMetricOwnershipMatrix([{metricKey:'progress',owner:'M21_PROGRESS'},{metricKey:'progress',owner:'M22_ESTIMATION'}],opts).ok,false);});
test('baseline witness is bound to metric owner and observation',()=>{const b=baseline();assert.equal(verifyBaselineAvailabilityWitness(b,opts).value,true);assert.equal(verifyBaselineAvailabilityWitness({...b,observationDigest:H('other')},opts).value,false);});
test('confidence can be preserved or downgraded but never upgraded',()=>{assert.equal(createConfidenceEnvelope('HIGH','MEDIUM',H('owner'),opts).ok,true);assert.equal(createConfidenceEnvelope('LOW','HIGH',H('owner'),opts).ok,false);assert.equal(createConfidenceEnvelope('UNKNOWN','LOW',H('owner'),opts).ok,false);});
test('numeric delegated metric requires baseline witness',()=>{const r=createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:10,unit:'percent',sourceIdentityDigest:H('s'),validityBindingDigest:H('v')},matrix,opts);assert.equal(r.ok,false);});
test('metric owner mismatch is rejected',()=>{const r=createDelegatedMetricClaim({metricKey:'eta',owner:'M21_PROGRESS',availability:'NOT_YET_BASELINED',sourceIdentityDigest:H('s'),validityBindingDigest:H('v')},matrix,opts);assert.equal(r.ok,false);});
test('unavailable metric algebra carries no fabricated value',()=>{const m=createUnavailableMetric('eta','M22_ESTIMATION','NOT_YET_BASELINED',H('s'),H('v'),matrix,opts).value;assert.equal(m.scalarValue,null);assert.equal(m.rangeValue,null);assert.equal(m.baseline,null);assert.equal(m.baselineDigest,null);assert.equal(verifyDelegatedMetricClaim(m,matrix,opts).value,true);});
test('available delegated metric is verified exactly',()=>{const m=metric();assert.equal(verifyDelegatedMetricClaim(m,matrix,opts).value,true);assert.equal(verifyDelegatedMetricClaim({...m,scalarValue:99},matrix,opts).value,false);});
test('resolved blockers are omitted but active blockers remain',()=>{const a=blocker(),r=blocker({blockerId:'b2',disposition:'RESOLVED'});const p=projectApplicableBlockers([r,a],opts).value;assert.deepEqual(p.map(x=>x.blockerId),['b1']);});
test('conflict witness is deterministic and detects divergence',()=>{const a=createStateConflictWitness('checkpoint',[H('b'),H('a')],opts).value;const b=createStateConflictWitness('checkpoint',[H('a'),H('b')],opts).value;assert.equal(a.witnessDigest,b.witnessDigest);assert.equal(a.hasConflict,true);});
test('next necessary action is singular and typed',()=>{assert.equal(next().actionRef,'IMPLEMENT_GBS_M20');assert.equal(createNextNecessaryActionCapsule('KNOWN',null,H('s'),H('v'),opts).ok,false);assert.equal(createNextNecessaryActionCapsule('NONE','x',H('s'),H('v'),opts).ok,false);});
test('recovery outranks conflict blocking and success',()=>{const v=deriveResponseVerdict([blocker({classification:'BLOCKING'}),blocker({blockerId:'r',classification:'RECOVERY'})],[],{requestedVerdict:'SUCCESS'},opts).value;assert.equal(v.verdict,'RECOVERY_REQUIRED');assert.ok(v.reasons.includes('OPTIMISTIC_OVERRIDE_REJECTED'));});
test('canonical conflict outranks generic success',()=>{const w=createStateConflictWitness('checkpoint',[H('a'),H('b')],opts).value;assert.equal(deriveResponseVerdict([], [w],{requestedVerdict:'SUCCESS'},opts).value.verdict,'CONFLICT');});
test('stale blocker yields indeterminate instead of success',()=>{assert.equal(deriveResponseVerdict([blocker({classification:'WARNING',freshness:'STALE'})],[],{},opts).value.verdict,'INDETERMINATE');});
test('semantic dedup removes identical claim identity only',()=>{const a=field('x','same');const b=field('x','same',{ownerDomain:'resume',sourceIdentityDigest:H('resume-source'),validityBindingDigest:H('resume-valid')});const d=semanticDeduplicateClaims([a,a,b],opts).value;assert.equal(d.claims.length,2);assert.equal(d.map.droppedClaimDigests.length,1);});
test('minimum sufficient fields never silently lose mandatory truth',()=>{assert.equal(buildMinimumSufficientResponseFields([field('phase')],['phase','current_work'],opts).ok,false);});
test('minimum sufficient fields retain non-current claims for safety',()=>{const s=field('note','old',{freshness:'STALE'});const r=buildMinimumSufficientResponseFields([field('phase'),s],['phase'],opts).value;assert.deepEqual(r.map(x=>x.field),['note','phase']);});
test('redaction rejects secret-like material and private paths',()=>{assert.equal(assessResponseRedaction([field('x','api_key=abc')],[],opts).value.safe,false);assert.equal(assessResponseRedaction([field('x','C:\\Users\\alice\\private.txt')],[],opts).value.safe,false);});
test('response size guard returns expansion requirement instead of truncation',()=>{const f=[field('phase','x')];const a=assessResponseSize(f,[],[],0,{x:'1234567890'},{digest,maxBytes:256,maxFields:1,maxRefs:1}).value;assert.equal(a.withinLimits,false);assert.equal(a.disposition,'EXPANSION_REFERENCE_REQUIRED');});
test('machine envelope is deterministic across source enumeration order',()=>{const a=field('phase','PRODUCTION'),b=field('current_work','M20'),c=field('completed','M00-M19'),d=field('remaining','M20-M63');const x=machine({capsule:capsule([d,b,a,c]),metrics:[metric()]});const y=machine({capsule:capsule([a,b,c,d]),metrics:[metric()]});assert.equal(x.machineDigest,y.machineDigest);assert.equal(verifyMachineResponseEnvelope(x,matrix,opts).value,true);});
test('stale mandatory field cannot produce success verdict',()=>{const fs=[field('phase','PRODUCTION',{freshness:'STALE'}),field('current_work','M20'),field('completed','M00-M19'),field('remaining','M20-M63')];assert.equal(machine({capsule:capsule(fs)}).verdict.verdict,'INDETERMINATE');});
test('conflicting field cannot produce success verdict',()=>{const fs=[field('phase','PRODUCTION',{freshness:'CONFLICT'}),field('current_work','M20'),field('completed','M00-M19'),field('remaining','M20-M63')];assert.equal(machine({capsule:capsule(fs)}).verdict.verdict,'CONFLICT');});
test('active blocker produces blocked machine response',()=>{assert.equal(machine({blockers:[blocker()]}).verdict.verdict,'BLOCKED');});
test('human projection is derived only from verified machine semantics',()=>{const m=machine();const h=buildHumanResponseProjection(m,matrix,opts).value;assert.equal(h.semanticDigest,m.semanticDigest);assert.equal(verifyHumanResponseProjection(h,m,matrix,opts).value,true);assert.equal(verifyHumanResponseProjection({...h,lines:[...h.lines,'project_status=DONE']},m,matrix,opts).value,false);});
test('integrity receipt binds machine and human projections',()=>{const m=machine();const h=buildHumanResponseProjection(m,matrix,opts).value;const r=buildResponseIntegrityReceipt(m,h,matrix,opts).value;assert.equal(r.valid,true);assert.equal(r.machineDigest,m.machineDigest);assert.equal(r.humanProjectionDigest,h.projectionDigest);});
test('compatibility gate reports unsupported semantics explicitly',()=>{const s=schema();const ok=checkResponseCompatibility(s,{supportedSchemaVersions:[1],supportedProfiles:['standard'],capabilities:['structured']},opts).value;assert.equal(ok.compatible,true);const bad=checkResponseCompatibility(s,{supportedSchemaVersions:[1],supportedProfiles:['compact'],capabilities:[]},opts).value;assert.equal(bad.compatible,false);assert.ok(bad.reasons.includes('UNSUPPORTED_PROFILE'));assert.deepEqual(bad.missingCapabilities,['structured']);});
test('stale sentinel binds checkpoint resume registry fields and metrics',()=>{const m=machine();const observation={checkpointBindingDigest:m.checkpointBindingDigest,resumeBindingDigest:m.resumeBindingDigest,registryBindingDigest:m.registryBindingDigest,fieldValidityBindings:Object.fromEntries(m.fields.map(f=>[f.field,f.validityBindingDigest])),metricValidityBindings:Object.fromEntries(m.metrics.map(x=>[x.metricKey,x.validityBindingDigest]))};assert.equal(detectStaleResponse(m,observation,matrix,opts).value.stale,false);assert.equal(detectStaleResponse(m,{...observation,checkpointBindingDigest:H('new')},matrix,opts).value.stale,true);});
