import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createSourceBoundFieldClaim,createResponseSchemaEnvelope,createResponseContractCapsule,verifyResponseContractCapsule,defaultMetricOwnershipMatrix,verifyMetricOwnershipMatrix,createUnavailableMetric,createDelegatedMetricClaim,createBaselineAvailabilityWitness,createConfidenceEnvelope,createBlockerProjection,createStateConflictWitness,createNextNecessaryActionCapsule,createResponseVerdictClaim,buildMachineResponseEnvelope,detectStaleResponse,semanticDeduplicateClaims}from'../packages/response-contract/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const matrix=defaultMetricOwnershipMatrix(opts).value;
const field=(name,value=name)=>createSourceBoundFieldClaim({field:name,value,ownerDomain:'checkpoint',subjectId:name,sourceIdentityDigest:H(`source:${name}`),validityBindingDigest:H(`valid:${name}`),freshness:'CURRENT'},opts).value;
const verdict=()=>createResponseVerdictClaim('SUCCESS',H('verdict-source'),H('verdict-valid'),opts).value;
const action=()=>createNextNecessaryActionCapsule('KNOWN','IMPLEMENT_GBS_M20',H('next-source'),H('next-valid'),opts).value;
function capsule(vc=verdict()){return createResponseContractCapsule({projectId:'gef-bootstrap',responseKind:'checkpoint',checkpointBindingDigest:H('checkpoint'),resumeBindingDigest:H('resume'),registryBindingDigest:H('registry'),sourceClaims:[field('phase','PRODUCTION'),field('current_work','M20'),field('completed','M00-M19'),field('remaining','M20-M63')],verdictInputDigest:vc.claimDigest,nextActionSourceDigest:H('next-source'),schema:createResponseSchemaEnvelope('standard',['structured'],opts).value},opts).value;}
function numericMetric(){const b=createBaselineAvailabilityWitness('project_completion','M21_PROGRESS',H('baseline'),H('observation'),opts).value;return createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:32.44,unit:'percent',precision:2,sourceIdentityDigest:H('metric-source'),validityBindingDigest:H('metric-valid'),baseline:b,confidence:createConfidenceEnvelope('MEDIUM','MEDIUM',H('confidence'),opts).value},matrix,opts).value;}
function machine(extra={}){const vc=extra.verdictClaim??verdict();return buildMachineResponseEnvelope({capsule:extra.capsule??capsule(vc),metrics:extra.metrics??[numericMetric()],blockers:extra.blockers??[],conflicts:extra.conflicts??[],nextAction:extra.nextAction??action(),verdictClaim:vc,requiredFields:['phase','current_work','completed','remaining']},matrix,opts);}
function observation(m){return{checkpointBindingDigest:m.checkpointBindingDigest,resumeBindingDigest:m.resumeBindingDigest,registryBindingDigest:m.registryBindingDigest,verdictValidityBinding:m.verdictClaim.validityBindingDigest,nextActionValidityBindingDigest:m.nextAction.validityBindingDigest,fieldValidityBindings:Object.fromEntries(m.fields.map(x=>[x.field,x.validityBindingDigest])),metricValidityBindings:Object.fromEntries(m.metrics.map(x=>[x.metricKey,x.validityBindingDigest])),blockerValidityBindings:Object.fromEntries(m.blockers.map(x=>[x.blockerId,x.validityBindingDigest])),conflictWitnessDigests:Object.fromEntries(m.conflicts.map(x=>[x.subject,x.witnessDigest]))};}

test('capsule rejects provenance binding tamper even when index digest is left unchanged',()=>{const c=capsule();const bad={...c,provenanceIndex:{...c.provenanceIndex,bindings:[{field:'phase',claimDigests:[H('wrong-claim')]}]}};assert.equal(verifyResponseContractCapsule(bad,opts).value,false);});
test('metric ownership matrix tamper is rejected before delegated metric admission',()=>{const bad={...matrix,entries:matrix.entries.map(e=>e.metricKey==='project_completion'?{...e,owner:'M22_ESTIMATION'}:e)};assert.equal(verifyMetricOwnershipMatrix(bad,opts).value,false);assert.equal(createUnavailableMetric('project_completion','M22_ESTIMATION','NOT_YET_BASELINED',H('source'),H('valid'),bad,opts).ok,false);});
test('portable machine response rejects secret-like text metric values',()=>{const m=createDelegatedMetricClaim({metricKey:'status_note',owner:'EXTERNAL_CANONICAL',availability:'AVAILABLE',scalarValue:'api_token=abc123',unit:'text',sourceIdentityDigest:H('source'),validityBindingDigest:H('valid')},matrix,opts).value;assert.equal(machine({metrics:[m]}).ok,false);});
test('portable machine response rejects secret-like metric units',()=>{const b=createBaselineAvailabilityWitness('project_completion','M21_PROGRESS',H('baseline'),H('observation'),opts).value;const m=createDelegatedMetricClaim({metricKey:'project_completion',owner:'M21_PROGRESS',availability:'AVAILABLE',scalarValue:32.44,unit:'api_token',sourceIdentityDigest:H('source'),validityBindingDigest:H('valid'),baseline:b},matrix,opts).value;assert.equal(machine({metrics:[m]}).ok,false);});
test('compactness API rejects tampered source claims instead of deduplicating them',()=>{const f=field('phase','PRODUCTION');assert.equal(semanticDeduplicateClaims([{...f,value:'DONE'}],opts).ok,false);});
test('stale sentinel requires next-action validity evidence',()=>{const m=machine().value,o=observation(m);delete o.nextActionValidityBindingDigest;const r=detectStaleResponse(m,o,matrix,opts).value;assert.equal(r.stale,true);assert.ok(r.staleSubjects.includes('next_action'));});
test('stale sentinel requires blocker validity evidence',()=>{const b=createBlockerProjection({blockerId:'gate',classification:'BLOCKING',disposition:'ACTIVE',sourceIdentityDigest:H('blocker-source'),validityBindingDigest:H('blocker-valid'),freshness:'CURRENT',message:'Gate blocked'},opts).value,m=machine({blockers:[b]}).value,o=observation(m);assert.equal(detectStaleResponse(m,o,matrix,opts).value.stale,false);delete o.blockerValidityBindings;const r=detectStaleResponse(m,o,matrix,opts).value;assert.ok(r.staleSubjects.includes('blocker:gate'));});
test('stale sentinel requires conflict witness evidence',()=>{const w=createStateConflictWitness('checkpoint',[H('a'),H('b')],opts).value,m=machine({conflicts:[w]}).value,o=observation(m);assert.equal(detectStaleResponse(m,o,matrix,opts).value.stale,false);delete o.conflictWitnessDigests;const r=detectStaleResponse(m,o,matrix,opts).value;assert.ok(r.staleSubjects.includes('conflict:checkpoint'));});
