import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createDenominatorIntegrityManifest,verifyDenominatorIntegrityManifest,createProgressBaselineCapsule,createEvidenceAcceptanceBinding,createWeightedCreditUnit,createWeightedProgressVector,verifyWeightedProgressVector,createHierarchicalProgressGraph,createProgressSnapshot,verifyProgressSnapshotCapsule,createCreditDependencyGraph,verifyCreditDependencyGraph,createProgressInvalidationVector,verifyProgressInvalidationVector,createStaleCreditQuarantine,verifyStaleCreditQuarantine,retractCredits,createCreditRetractionTransaction,verifyCreditRetractionTransaction,createProgressRegressionReceipt,verifyProgressRegressionReceipt,createProgressIntegrityReceipt,verifyProgressIntegrityReceipt,createDelegatedProgressMetricHandoff,verifyDelegatedProgressMetricHandoff,createEstimationBaselineHandoff,verifyEstimationBaselineHandoff,createStatusProgressHandoff,verifyStatusProgressHandoff,detectProgressStaleness,verifyProgressStalenessReport,createDenominatorMutationWitness,guardDenominatorDrift,rollupProgress,createPartialCreditAllocation,projectPresentationPercentage}from'../packages/progress-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
function makeManifest(weights=[3,5,7,11],epoch='e1'){return createDenominatorIntegrityManifest({projectId:'p',lineageDigest:H('l'),epochId:epoch,scopeDigest:H('s'),dodDigest:H('d'),policyDigest:H('policy'),units:weights.map((w,i)=>({unitId:`u${i}`,moduleId:`M${Math.floor(i/2)}`,areaId:`A${Math.floor(i/4)}`,phaseId:'P',maxWeight:w,dependencyDigests:[H(`dep${i}`)]})),excludedUnitIds:['optional']},opts).value;}
function makeCredits(m,accepted=()=>true){return m.units.map(u=>{const i=Number(u.unitId.slice(1));return createWeightedCreditUnit(u,createEvidenceAcceptanceBinding({unitId:u.unitId,owner:'M24_EVIDENCE',state:accepted(i)?'ACCEPTED':'REJECTED',sourceIdentityDigest:H(`src${i}`),validityBindingDigest:H(`valid${i}`)},opts).value,opts).value;});}
function snap(m,cs,evidence='evidence',pred=null){const base=createProgressBaselineCapsule(m,opts).value,vector=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value,graph=createHierarchicalProgressGraph(m,opts).value;return createProgressSnapshot({baseline:base,vector,graph,credits:cs,evidenceSetDigest:H(evidence),...(pred?{predecessorSemanticDigest:pred}:{})},m,opts).value;}

test('manifest tamper cannot change total weight or unit semantics',()=>{const m=makeManifest();assert.equal(verifyDenominatorIntegrityManifest({...m,totalWeight:m.totalWeight+1},opts).value,false);assert.equal(verifyDenominatorIntegrityManifest({...m,units:m.units.map((u,i)=>i?u:{...u,maxWeight:u.maxWeight+1})},opts).value,false);});
test('over-credit reseal attempt is rejected by vector boundary',()=>{const m=makeManifest(),cs=makeCredits(m),bad={...cs[0],earnedWeight:cs[0].maxWeight+1};assert.equal(createWeightedProgressVector(m,[bad,...cs.slice(1)],{kind:'PROJECT',refId:null},opts).ok,false);});
test('negative denominator weight is rejected',()=>{assert.equal(createDenominatorIntegrityManifest({projectId:'p',lineageDigest:H('l'),epochId:'e',scopeDigest:H('s'),dodDigest:H('d'),policyDigest:H('p'),units:[{unitId:'u',moduleId:'M',areaId:'A',phaseId:'P',maxWeight:-1}]},opts).ok,false);});
test('missing credit never shrinks the canonical denominator',()=>{const m=makeManifest(),cs=makeCredits(m).slice(0,2),v=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value;assert.equal(v.exact.denominator,m.totalWeight);assert.equal(v.completeness.state,'PARTIAL_OBSERVATION');});
test('tampered progress vector is rejected even when exact fraction looks plausible',()=>{const m=makeManifest(),cs=makeCredits(m),v=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value;assert.equal(verifyWeightedProgressVector({...v,creditDigests:v.creditDigests.slice(1)},m,cs,opts).value,false);});
test('diamond-style duplicate unit requests cannot inflate subset rollup',()=>{const m=makeManifest(),cs=makeCredits(m),r=rollupProgress(m,cs,{kind:'PROJECT',refId:null},['u0','u1','u0','u1','u0'],opts).value;assert.equal(r.exact.numerator,8);assert.equal(r.exact.denominator,8);assert.deepEqual(r.antiDoubleCount.duplicateUnitIds,['u0','u1']);});
test('rollup refuses a unit outside its query scope',()=>{const m=makeManifest(),cs=makeCredits(m);assert.equal(rollupProgress(m,cs,{kind:'MODULE',refId:'M0'},['u0','u2'],opts).ok,false);});
test('partial allocation refuses duplicate subunit and overflow',()=>{assert.equal(createPartialCreditAllocation('M',10,[{unitId:'a',maxWeight:5},{unitId:'a',maxWeight:5}],opts).ok,false);assert.equal(createPartialCreditAllocation('M',10,[{unitId:'a',maxWeight:6},{unitId:'b',maxWeight:5}],opts).ok,false);});
test('presentation rounding cannot mutate exact numerator or denominator',()=>{const a=projectPresentationPercentage({numerator:2,denominator:3},0,'DOWN',opts).value,b=projectPresentationPercentage({numerator:2,denominator:3},4,'HALF_UP',opts).value;assert.deepEqual([a.numerator,a.denominator,b.numerator,b.denominator],[2,3,2,3]);assert.notEqual(a.text,b.text);});
test('property oracle conserves numerator and denominator across randomized partitions',()=>{let seed=0x21c0ffee;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;};for(let round=0;round<160;round++){const count=1+(rnd()%24),weights=Array.from({length:count},()=>1+(rnd()%50)),m=makeManifest(weights,`e${round}`),mask=Array.from({length:count},()=>Boolean(rnd()&1)),cs=makeCredits(m,i=>mask[i]),v=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value;const oracleDen=weights.reduce((a,b)=>a+b,0),oracleNum=weights.reduce((sum,w,i)=>sum+(mask[i]?w:0),0);assert.equal(v.exact.denominator,oracleDen);assert.equal(v.exact.numerator,oracleNum);assert.equal(v.completeness.state,'COMPLETE');}});
test('property permutation never changes denominator manifest or project vector identity',()=>{for(let n=2;n<30;n++){const weights=Array.from({length:n},(_,i)=>i+1),m=makeManifest(weights,`perm${n}`),rev=createDenominatorIntegrityManifest({projectId:m.projectId,lineageDigest:m.lineageDigest,epochId:m.epochId,scopeDigest:m.scopeDigest,dodDigest:m.dodDigest,policyDigest:m.policyDigest,units:[...m.units].reverse().map(u=>({unitId:u.unitId,moduleId:u.moduleId,areaId:u.areaId,phaseId:u.phaseId,maxWeight:u.maxWeight,dependencyDigests:u.dependencyDigests})),excludedUnitIds:m.excludedUnitIds},opts).value;assert.equal(rev.manifestDigest,m.manifestDigest);const cs=makeCredits(m,i=>i%2===0),a=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value,b=createWeightedProgressVector(m,[...cs].reverse(),{kind:'PROJECT',refId:null},opts).value;assert.equal(a.vectorDigest,b.vectorDigest);}});
test('dependency graph tamper cannot redirect invalidation',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,bad={...g,entries:g.entries.map((e,i)=>i?e:{...e,dependencyDigests:[H('forged')]})};assert.equal(verifyCreditDependencyGraph(bad,opts).value,false);});
test('invalidation vector is bound to exact dependency graph',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,bad={...v,affectedUnitIds:['u1']};assert.equal(verifyProgressInvalidationVector(bad,g,opts).value,false);});
test('tampered invalidation vector cannot drive quarantine or retraction',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,bad={...v,affectedUnitIds:['u1']};assert.equal(createStaleCreditQuarantine(cs,bad,g,opts).ok,false);assert.equal(retractCredits(cs,bad,g,opts).ok,false);});
test('quarantine receipt detects entry tampering',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,q=createStaleCreditQuarantine(cs,v,g,opts).value,bad={...q,entries:q.entries.map((e,i)=>i?e:{...e,unitId:'u1'})};assert.equal(verifyStaleCreditQuarantine(bad,opts).value,false);});
test('retraction is idempotent after the unit is already quarantined',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,a=retractCredits(cs,v,g,opts).value,b=retractCredits(a,v,g,opts).value;assert.deepEqual(a,b);});
test('retraction transaction tamper and replay delta are detectable',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,t=createCreditRetractionTransaction(m,cs,{kind:'PROJECT',refId:null},v,g,opts).value;assert.equal(verifyCreditRetractionTransaction(t,opts).value,true);assert.equal(verifyCreditRetractionTransaction({...t,retractedUnitIds:['u1']},opts).value,false);});
test('wrong epoch mutation witness cannot authorize progress comparison',()=>{const m=makeManifest(),cs=makeCredits(m),s=snap(m,cs),after=makeManifest([3,5,7,11,13],'e2'),wrongBefore=makeManifest([3,5,7,11],'wrong'),w=createDenominatorMutationWitness(wrongBefore,after,H('auth'),opts).value,d=guardDenominatorDrift(s,after,w,opts).value;assert.equal(d.comparisonAllowed,false);assert.equal(d.snapshotReusable,false);});
test('tampered denominator witness cannot authorize epoch transition',()=>{const m=makeManifest(),cs=makeCredits(m),s=snap(m,cs),after=makeManifest([3,5,7,11,13],'e2'),w=createDenominatorMutationWitness(m,after,H('auth'),opts).value,d=guardDenominatorDrift(s,after,{...w,afterTotalWeight:w.afterTotalWeight+1},opts).value;assert.equal(d.comparisonAllowed,false);});
test('snapshot mix-and-match graph fails at construction boundary',()=>{const m=makeManifest(),cs=makeCredits(m),base=createProgressBaselineCapsule(m,opts).value,v=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value,g=createHierarchicalProgressGraph(m,opts).value,bad={...g,graphDigest:H('other')};assert.equal(createProgressSnapshot({baseline:base,vector:v,graph:bad,credits:cs,evidenceSetDigest:H('e')},m,opts).ok,false);});
test('resealed snapshot semantic field tamper is detected',()=>{const m=makeManifest(),cs=makeCredits(m),s=snap(m,cs);assert.equal(verifyProgressSnapshotCapsule({...s,evidenceSetDigest:H('other')},opts).value,false);});
test('integrity receipt self-verifier detects exact-fraction tamper',()=>{const m=makeManifest(),cs=makeCredits(m),s=snap(m,cs),r=createProgressIntegrityReceipt(s,m,cs,{kind:'PROJECT',refId:null},opts).value;assert.equal(verifyProgressIntegrityReceipt(r,opts).value,true);assert.equal(verifyProgressIntegrityReceipt({...r,valid:false},opts).value,false);});
test('delegated M20 handoff cannot be relabeled or rebound',()=>{const m=makeManifest(),cs=makeCredits(m),s=snap(m,cs),h=createDelegatedProgressMetricHandoff(s,H('source'),H('valid'),opts).value;assert.equal(verifyDelegatedProgressMetricHandoff(h,opts).value,true);assert.equal(verifyDelegatedProgressMetricHandoff({...h,owner:'M22_ESTIMATION'},opts).value,false);assert.equal(verifyDelegatedProgressMetricHandoff({...h,validityBindingDigest:H('new')},opts).value,false);});
test('M22 handoff rejects incomplete snapshot and detects tampering',()=>{const m=makeManifest(),cs=makeCredits(m).slice(0,-1),s=snap(m,cs);assert.equal(createEstimationBaselineHandoff([s],opts).ok,false);const full=snap(m,makeCredits(m)),h=createEstimationBaselineHandoff([full],opts).value;assert.equal(verifyEstimationBaselineHandoff(h,opts).value,true);assert.equal(verifyEstimationBaselineHandoff({...h,snapshotDigests:[H('forged')]},opts).value,false);});
test('M23 handoff cannot change regression fact without invalidating receipt',()=>{const m=makeManifest(),s=snap(m,makeCredits(m)),h=createStatusProgressHandoff(s,false,opts).value;assert.equal(verifyStatusProgressHandoff(h,opts).value,true);assert.equal(verifyStatusProgressHandoff({...h,regressionObserved:true},opts).value,false);});
test('staleness report is snapshot bound',()=>{const m=makeManifest(),s=snap(m,makeCredits(m)),obs={projectId:s.projectId,lineageDigest:s.lineageDigest,manifestDigest:s.manifestDigest,epochId:s.epochId,scopeDigest:s.scopeDigest,dodDigest:s.dodDigest,evidenceSetDigest:s.evidenceSetDigest},r=detectProgressStaleness(s,obs,opts).value;assert.equal(verifyProgressStalenessReport(r,opts).value,true);assert.equal(verifyProgressStalenessReport({...r,snapshotDigest:H('other')},opts).value,false);});
test('regression receipt cannot be fabricated from a non-regression',()=>{const m=makeManifest(),cs=makeCredits(m),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,t=createCreditRetractionTransaction(m,cs,{kind:'PROJECT',refId:null},v,g,opts).value,before=snap(m,cs),afterCredits=retractCredits(cs,v,g,opts).value,after=snap(m,afterCredits,'e2',before.semanticDigest),r=createProgressRegressionReceipt(before,after,t,['STALE_PROOF'],opts).value;assert.equal(verifyProgressRegressionReceipt(r,opts).value,true);assert.equal(createProgressRegressionReceipt(after,before,t,['STALE_PROOF'],opts).ok,false);assert.equal(verifyProgressRegressionReceipt({...r,transactionDigest:H('fake')},opts).value,false);});
test('graph budgets fail closed instead of returning partial authoritative graph',()=>{const m=makeManifest(Array.from({length:20},()=>1));assert.equal(createHierarchicalProgressGraph(m,{digest,maxNodes:3}).ok,false);});
test('query/credit operations honor cancellation under HIGH_ASSURANCE',()=>{const m=makeManifest(),cs=makeCredits(m),o={digest,cancellation:{isCancelled:()=>true}};assert.equal(createCreditDependencyGraph(m,cs,{},true,o).ok,false);assert.equal(createProgressInvalidationVector(createCreditDependencyGraph(m,cs,{},true,opts).value,[H('x')],['STALE'],o).ok,false);});
