import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createDenominatorIntegrityManifest,createProgressBaselineCapsule,createEvidenceAcceptanceBinding,createWeightedCreditUnit,createWeightedProgressVector,createHierarchicalProgressGraph,createProgressSnapshot,createCreditDependencyGraph,createProgressInvalidationVector,retractCredits,createCreditRetractionTransaction,createProgressRegressionReceipt,createAntiDoubleCountLedger}from'../packages/progress-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
function manifest(epoch='e1'){return createDenominatorIntegrityManifest({projectId:'p',lineageDigest:H('lineage'),epochId:epoch,scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:[{unitId:'a',moduleId:'M1',areaId:'A1',phaseId:'P1',maxWeight:4},{unitId:'b',moduleId:'M1',areaId:'A1',phaseId:'P1',maxWeight:6}]},opts).value;}
function credits(m){return m.units.map(u=>createWeightedCreditUnit(u,createEvidenceAcceptanceBinding({unitId:u.unitId,owner:'M24_EVIDENCE',state:'ACCEPTED',sourceIdentityDigest:H(`src:${u.unitId}`),validityBindingDigest:H(`valid:${u.unitId}`)},opts).value,opts).value);}
function snapshot(m,cs,query={kind:'PROJECT',refId:null},pred=null,evidence='e'){const base=createProgressBaselineCapsule(m,opts).value,vector=createWeightedProgressVector(m,cs,query,opts).value,graph=createHierarchicalProgressGraph(m,opts).value;return createProgressSnapshot({baseline:base,vector,graph,credits:cs,evidenceSetDigest:H(evidence),...(pred?{predecessorSemanticDigest:pred}:{})},m,opts).value;}

test('M21 cannot self-issue evidence acceptance authority',()=>{const r=createEvidenceAcceptanceBinding({unitId:'a',owner:'M21_PROGRESS',state:'ACCEPTED',sourceIdentityDigest:H('src'),validityBindingDigest:H('valid')},opts);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'SELF_AUTHORITY_FORBIDDEN');});

test('anti-double-count ledger is invariant to semantically equivalent input ordering',()=>{const a=createAntiDoubleCountLedger(['b','a','b','c'],opts).value,b=createAntiDoubleCountLedger(['c','b','b','a'],opts).value;assert.deepEqual(a.requestedUnitIds,['a','b','b','c']);assert.deepEqual(b.requestedUnitIds,a.requestedUnitIds);assert.equal(a.ledgerDigest,b.ledgerDigest);assert.deepEqual(a.duplicateUnitIds,['b']);});

test('regression receipt requires exact same project denominator epoch and query with direct predecessor',()=>{const m=manifest(),cs=credits(m),before=snapshot(m,cs),graph=createCreditDependencyGraph(m,cs,{},true,opts).value,iv=createProgressInvalidationVector(graph,[cs[0].validityBindingDigest],['STALE_PROOF'],opts).value,tx=createCreditRetractionTransaction(m,cs,{kind:'PROJECT',refId:null},iv,graph,opts).value,afterCredits=retractCredits(cs,iv,graph,opts).value,after=snapshot(m,afterCredits,{kind:'PROJECT',refId:null},before.semanticDigest,'e2');assert.equal(createProgressRegressionReceipt(before,after,tx,['STALE_PROOF'],opts).ok,true);
const wrongPred=snapshot(m,afterCredits,{kind:'PROJECT',refId:null},null,'e3');const rp=createProgressRegressionReceipt(before,wrongPred,tx,['STALE_PROOF'],opts);assert.equal(rp.ok,false);assert.equal(rp.diagnostics[0].code,'REGRESSION_PREDECESSOR_MISMATCH');
const moduleAfter=snapshot(m,afterCredits,{kind:'MODULE',refId:'M1'},before.semanticDigest,'e4');const rq=createProgressRegressionReceipt(before,moduleAfter,tx,['STALE_PROOF'],opts);assert.equal(rq.ok,false);assert.equal(rq.diagnostics[0].code,'REGRESSION_QUERY_MISMATCH');
const m2=manifest('e2'),cs2=credits(m2),graph2=createCreditDependencyGraph(m2,cs2,{},true,opts).value,iv2=createProgressInvalidationVector(graph2,[cs2[0].validityBindingDigest],['STALE_PROOF'],opts).value,after2=snapshot(m2,retractCredits(cs2,iv2,graph2,opts).value,{kind:'PROJECT',refId:null},before.semanticDigest,'e5');const re=createProgressRegressionReceipt(before,after2,tx,['STALE_PROOF'],opts);assert.equal(re.ok,false);assert.equal(re.diagnostics[0].code,'REGRESSION_EPOCH_MISMATCH');});
