import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createDenominatorIntegrityManifest,createProgressBaselineCapsule,verifyProgressBaselineCapsule,createEvidenceAcceptanceBinding,createWeightedCreditUnit,createWeightedProgressVector,createHierarchicalProgressGraph,createProgressSnapshot,verifyProgressSnapshotCapsule,createProgressIntegrityReceipt,createDelegatedProgressMetricHandoff,createEstimationBaselineHandoff,createStatusProgressHandoff}from'../packages/progress-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v,seal=v=>H(JSON.stringify(canon(v)));
function fx(){const m=createDenominatorIntegrityManifest({projectId:'p',lineageDigest:H('l'),epochId:'e1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:[{unitId:'a',moduleId:'M1',areaId:'A1',phaseId:'P1',maxWeight:4},{unitId:'b',moduleId:'M1',areaId:'A1',phaseId:'P1',maxWeight:6}]},opts).value;const base=createProgressBaselineCapsule(m,opts).value,bindings=m.units.map(u=>createEvidenceAcceptanceBinding({unitId:u.unitId,owner:'M24_EVIDENCE',state:'ACCEPTED',sourceIdentityDigest:H(`src:${u.unitId}`),validityBindingDigest:H(`v:${u.unitId}`)},opts).value),credits=m.units.map((u,i)=>createWeightedCreditUnit(u,bindings[i],opts).value),graph=createHierarchicalProgressGraph(m,opts).value;return{m,base,credits,graph};}
function snapshotFor(query,creditsOverride){const f=fx(),credits=creditsOverride??f.credits,vector=createWeightedProgressVector(f.m,credits,query,opts).value,snapshot=createProgressSnapshot({baseline:f.base,vector,graph:f.graph,credits,evidenceSetDigest:H('evidence')},f.m,opts).value;return{...f,credits,vector,snapshot};}

test('self-consistent baseline resealed to another policy is rejected by snapshot boundary',()=>{const f=fx(),body={projectId:f.base.projectId,lineageDigest:f.base.lineageDigest,epochId:f.base.epochId,manifestDigest:f.base.manifestDigest,scopeDigest:f.base.scopeDigest,dodDigest:f.base.dodDigest,policyDigest:H('other-policy')},forged={...body,capsuleDigest:seal(body)};assert.equal(verifyProgressBaselineCapsule(forged,opts).value,true);const vector=createWeightedProgressVector(f.m,f.credits,{kind:'PROJECT',refId:null},opts).value;assert.equal(createProgressSnapshot({baseline:forged,vector,graph:f.graph,credits:f.credits,evidenceSetDigest:H('evidence')},f.m,opts).ok,false);});
test('module snapshot cannot be delegated as project completion to M20',()=>{const f=snapshotFor({kind:'MODULE',refId:'M1'});assert.equal(f.snapshot.query.kind,'MODULE');assert.equal(createDelegatedProgressMetricHandoff(f.snapshot,H('source'),H('valid'),opts).ok,false);});
test('module snapshot cannot seed overall ETA baseline in M22',()=>{const f=snapshotFor({kind:'MODULE',refId:'M1'});assert.equal(createEstimationBaselineHandoff([f.snapshot],opts).ok,false);});
test('module snapshot cannot drive overall project status in M23',()=>{const f=snapshotFor({kind:'MODULE',refId:'M1'});assert.equal(createStatusProgressHandoff(f.snapshot,false,opts).ok,false);});
test('integrity receipt refuses query substitution',()=>{const f=snapshotFor({kind:'MODULE',refId:'M1'});assert.equal(createProgressIntegrityReceipt(f.snapshot,f.m,f.credits,{kind:'PROJECT',refId:null},opts).ok,false);});
test('resealed completeness cannot claim COMPLETE while a unit is missing',()=>{const f=fx(),credits=[f.credits[0]],vector=createWeightedProgressVector(f.m,credits,{kind:'PROJECT',refId:null},opts).value,s=createProgressSnapshot({baseline:f.base,vector,graph:f.graph,credits,evidenceSetDigest:H('evidence')},f.m,opts).value;assert.equal(s.completeness.state,'PARTIAL_OBSERVATION');const completeness={...s.completeness,state:'COMPLETE'},cbody={state:completeness.state,requiredUnitCount:completeness.requiredUnitCount,observedUnitCount:completeness.observedUnitCount,missingUnitIds:[...completeness.missingUnitIds].sort(),quarantinedUnitIds:[...completeness.quarantinedUnitIds].sort()};completeness.envelopeDigest=seal(cbody);const core={projectId:s.projectId,lineageDigest:s.lineageDigest,manifestDigest:s.manifestDigest,epochId:s.epochId,scopeDigest:s.scopeDigest,dodDigest:s.dodDigest,query:s.query,evidenceSetDigest:s.evidenceSetDigest,exact:s.exact,completeness,creditDigests:[...s.creditDigests].sort(),graphDigest:s.graphDigest,predecessorSemanticDigest:s.predecessorSemanticDigest};const semanticDigest=seal(core),forged={...core,semanticDigest,snapshotDigest:seal({...core,semanticDigest})};assert.equal(verifyProgressSnapshotCapsule(forged,opts).value,false);});
