import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createDenominatorIntegrityManifest,verifyDenominatorIntegrityManifest,createProgressBaselineCapsule,verifyProgressBaselineCapsule,createProgressAuthorityBoundary,createScopeDodBinding,createEvidenceAcceptanceBinding,createWeightedCreditUnit,evaluateCreditEligibility,createDenominatorMutationWitness,verifyDenominatorMutationWitness,createProgressQueryPlan,createWeightedProgressVector,createHierarchicalProgressGraph,createAntiDoubleCountLedger,rollupProgress,createPartialCreditAllocation,projectPresentationPercentage,createCreditDependencyGraph,createProgressInvalidationVector,createStaleCreditQuarantine,retractCredits,createCreditRetractionTransaction,detectProgressDrift,guardDenominatorDrift,createProgressSplitBrainWitness,createProgressRegressionReceipt,createProgressSnapshot,verifyProgressSnapshotCapsule,createProgressIntegrityReceipt,createDelegatedProgressMetricHandoff,createEstimationBaselineHandoff,createStatusProgressHandoff,detectProgressStaleness}from'../packages/progress-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const units=[{unitId:'m19',moduleId:'M19',areaId:'area-e',phaseId:'construction',maxWeight:14,dependencyDigests:[H('m19-dep')]},{unitId:'m20',moduleId:'M20',areaId:'area-e',phaseId:'construction',maxWeight:13},{unitId:'m21-a',moduleId:'M21',areaId:'area-f',phaseId:'construction',maxWeight:8},{unitId:'m21-b',moduleId:'M21',areaId:'area-f',phaseId:'construction',maxWeight:10}];
function manifest(epoch='epoch-1',overrides={}){return createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:epoch,scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:overrides.units??units,excludedUnitIds:overrides.excluded??['m39']},opts).value;}
function binding(unitId,state='ACCEPTED',suffix=''){return createEvidenceAcceptanceBinding({unitId,owner:'M24_EVIDENCE',state,sourceIdentityDigest:H(`src:${unitId}:${suffix}`),validityBindingDigest:H(`valid:${unitId}:${suffix}`)},opts).value;}
function credits(m=manifest(),states={}){return m.units.map(u=>createWeightedCreditUnit(u,binding(u.unitId,states[u.unitId]??'ACCEPTED'),opts).value);}
function fixture(states={}){const m=manifest(),bs=m.units.map(u=>binding(u.unitId,states[u.unitId]??'ACCEPTED')),cs=m.units.map((u,i)=>createWeightedCreditUnit(u,bs[i],opts).value),base=createProgressBaselineCapsule(m,opts).value,vector=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value,graph=createHierarchicalProgressGraph(m,opts).value,snapshot=createProgressSnapshot({baseline:base,vector,graph,credits:cs,evidenceSetDigest:H('evidence-set')},m,opts).value;return{m,bs,cs,base,vector,graph,snapshot};}

test('denominator manifest is deterministic and order independent',()=>{const a=manifest(),b=createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:[...units].reverse(),excludedUnitIds:['m39']},opts).value;assert.equal(a.manifestDigest,b.manifestDigest);assert.equal(a.totalWeight,45);assert.equal(verifyDenominatorIntegrityManifest(a,opts).value,true);});
test('duplicate denominator units fail closed',()=>{assert.equal(createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:[units[0],units[0]]},opts).ok,false);});
test('optional excluded unit cannot contaminate production denominator',()=>{assert.equal(createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:[...units,{unitId:'m39',moduleId:'M39',areaId:'optional',phaseId:'optional',maxWeight:16}],excludedUnitIds:['m39']},opts).ok,false);});
test('baseline and authority boundary preserve calculation-only ownership',()=>{const m=manifest(),b=createProgressBaselineCapsule(m,opts).value,a=createProgressAuthorityBoundary(b,opts).value;assert.equal(verifyProgressBaselineCapsule(b,opts).value,true);assert.equal(a.authority,'CALCULATION_ONLY');assert.equal(a.mayDecideEvidence,false);assert.equal(a.mayEstimateEta,false);assert.equal(a.mayComputeProjectStatus,false);});
test('scope and DoD binding is explicit',()=>{const b=createScopeDodBinding(H('scope'),H('dod'),opts).value;assert.match(b.bindingDigest,/^sha256:/);});
test('accepted rejected and stale evidence project distinct credit states',()=>{const m=manifest(),u=m.units[0];const accepted=createWeightedCreditUnit(u,binding(u.unitId,'ACCEPTED'),opts).value,rejected=createWeightedCreditUnit(u,binding(u.unitId,'REJECTED'),opts).value,stale=createWeightedCreditUnit(u,binding(u.unitId,'STALE'),opts).value;assert.deepEqual([accepted.earnedWeight,rejected.earnedWeight,stale.earnedWeight],[14,0,0]);assert.deepEqual([accepted.state,rejected.state,stale.state],['EARNED','ZERO','QUARANTINED']);});
test('eligibility exposes missing and rejected units rather than inventing credit',()=>{const m=manifest(),r=evaluateCreditEligibility(m,[binding('m19'),binding('m20','REJECTED')],opts).value;assert.deepEqual(r.missingUnitIds,['m21-a','m21-b']);assert.deepEqual(r.rejectedUnitIds,['m20']);assert.equal(r.credits.reduce((n,c)=>n+c.earnedWeight,0),14);});
test('evidence outside denominator is rejected',()=>{const m=manifest();assert.equal(evaluateCreditEligibility(m,[binding('m39')],opts).ok,false);});
test('denominator mutation requires a new epoch and records exact delta',()=>{const before=manifest(),after=manifest('epoch-2',{units:[...units,{unitId:'m22',moduleId:'M22',areaId:'area-f',phaseId:'construction',maxWeight:15}]});const w=createDenominatorMutationWitness(before,after,H('denominator-auth'),opts).value;assert.deepEqual(w.addedUnitIds,['m22']);assert.equal(w.beforeTotalWeight,45);assert.equal(w.afterTotalWeight,60);assert.equal(verifyDenominatorMutationWitness(w,before,after,opts).value,true);});
test('same-epoch denominator mutation is forbidden',()=>{const before=manifest(),after=createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units:[...units,{unitId:'m22',moduleId:'M22',areaId:'area-f',phaseId:'construction',maxWeight:15}],excludedUnitIds:['m39']},opts).value;assert.equal(createDenominatorMutationWitness(before,after,H('auth'),opts).ok,false);});
test('query plan selects minimum module denominator units',()=>{const m=manifest(),q=createProgressQueryPlan(m,{kind:'MODULE',refId:'M21'},opts).value;assert.deepEqual(q.selectedUnitIds,['m21-a','m21-b']);assert.equal(q.expansionRequired,false);});
test('weighted vector keeps exact full denominator when observation is incomplete',()=>{const m=manifest(),cs=credits(m).slice(0,3),v=createWeightedProgressVector(m,cs,{kind:'PROJECT',refId:null},opts).value;assert.equal(v.exact.numerator,35);assert.equal(v.exact.denominator,45);assert.equal(v.completeness.state,'PARTIAL_OBSERVATION');assert.deepEqual(v.completeness.missingUnitIds,['m21-b']);});
test('hierarchical graph has one parent chain per atomic unit',()=>{const m=manifest(),g=createHierarchicalProgressGraph(m,opts).value;assert.ok(g.nodes.some(n=>n.nodeId==='project:gef-bootstrap'));assert.ok(g.edges.some(e=>e.parentNodeId==='module:M21'&&e.childNodeId==='unit:m21-a'));});
test('anti-double-count ledger exposes duplicate attempts',()=>{const l=createAntiDoubleCountLedger(['m21-a','m21-a','m21-b'],opts).value;assert.deepEqual(l.uniqueUnitIds,['m21-a','m21-b']);assert.deepEqual(l.duplicateUnitIds,['m21-a']);});
test('subset rollup is complete for the requested subset and counts each unit once',()=>{const m=manifest(),cs=credits(m),r=rollupProgress(m,cs,{kind:'MODULE',refId:'M21'},['m21-a','m21-a'],opts).value;assert.equal(r.exact.numerator,8);assert.equal(r.exact.denominator,8);assert.equal(r.completeness.state,'COMPLETE');assert.deepEqual(r.antiDoubleCount.duplicateUnitIds,['m21-a']);});
test('partial credit allocation must be explicit and conserved',()=>{const a=createPartialCreditAllocation('M21',18,[{unitId:'m21-a',maxWeight:8},{unitId:'m21-b',maxWeight:10}],opts).value;assert.equal(a.allocatedWeight,18);assert.equal(a.remainingWeight,0);assert.equal(createPartialCreditAllocation('M21',18,[{unitId:'x',maxWeight:10},{unitId:'y',maxWeight:9}],opts).ok,false);});
test('presentation rounding is separate from exact credit authority',()=>{const p=projectPresentationPercentage({numerator:1,denominator:3},2,'HALF_UP',opts).value;assert.equal(p.text,'33.33');assert.deepEqual([p.numerator,p.denominator],[1,3]);});
test('dependency graph binds credit evidence and validity',()=>{const {m,cs}=fixture(),g=createCreditDependencyGraph(m,cs,{},true,opts).value,e=g.entries.find(x=>x.unitId==='m19');assert.ok(e.dependencyDigests.includes(cs[0].evidenceBindingDigest));assert.ok(e.dependencyDigests.includes(cs[0].validityBindingDigest));});
test('selective invalidation affects only dependent credit with complete knowledge',()=>{const {m,cs}=fixture(),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['EVIDENCE_STALE'],opts).value;assert.deepEqual(v.affectedUnitIds,['m19']);assert.equal(v.widened,false);});
test('incomplete dependency knowledge widens invalidation conservatively',()=>{const {m,cs}=fixture(),g=createCreditDependencyGraph(m,cs,{},false,opts).value,v=createProgressInvalidationVector(g,[H('unknown-change')],['KNOWLEDGE_INCOMPLETE'],opts).value;assert.deepEqual(v.affectedUnitIds,['m19','m20','m21-a','m21-b']);assert.equal(v.widened,true);});
test('quarantine retains prior credit identity while removing active contribution',()=>{const {m,cs}=fixture(),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['EVIDENCE_STALE'],opts).value,q=createStaleCreditQuarantine(cs,v,g,opts).value,next=retractCredits(cs,v,g,opts).value;assert.equal(q.entries[0].priorCreditDigest,cs[0].creditDigest);assert.equal(next.find(x=>x.unitId==='m19').earnedWeight,0);assert.equal(next.find(x=>x.unitId==='m19').state,'QUARANTINED');});
test('credit retraction transaction preserves exact before and after fractions',()=>{const {m,cs}=fixture(),g=createCreditDependencyGraph(m,cs,{},true,opts).value,v=createProgressInvalidationVector(g,[cs[0].validityBindingDigest],['EVIDENCE_STALE'],opts).value,t=createCreditRetractionTransaction(m,cs,{kind:'PROJECT',refId:null},v,g,opts).value;assert.deepEqual([t.beforeExact.numerator,t.afterExact.numerator,t.beforeExact.denominator],[45,31,45]);assert.deepEqual(t.retractedUnitIds,['m19']);});
test('progress drift is binding based rather than clock based',()=>{const {snapshot}=fixture(),r=detectProgressDrift(snapshot,{projectId:snapshot.projectId,lineageDigest:snapshot.lineageDigest,manifestDigest:snapshot.manifestDigest,epochId:snapshot.epochId,scopeDigest:snapshot.scopeDigest,dodDigest:snapshot.dodDigest,evidenceSetDigest:H('new-evidence-set')},opts).value;assert.equal(r.state,'STALE');assert.deepEqual(r.staleSubjects,['evidence-set']);});
test('governed denominator epoch transition permits comparison but never stale snapshot reuse',()=>{const {m,snapshot}=fixture(),after=manifest('epoch-2',{units:[...units,{unitId:'m22',moduleId:'M22',areaId:'area-f',phaseId:'construction',maxWeight:15}]}),w=createDenominatorMutationWitness(m,after,H('denominator-auth'),opts).value,d=guardDenominatorDrift(snapshot,after,w,opts).value;assert.equal(d.sameEpoch,false);assert.equal(d.comparisonAllowed,true);assert.equal(d.snapshotReusable,false);assert.equal(d.reason,'GOVERNED_EPOCH_TRANSITION');});
test('snapshot is self-verifying and integrity receipt independently recomputes progress',()=>{const {m,cs,snapshot}=fixture(),r=createProgressIntegrityReceipt(snapshot,m,cs,{kind:'PROJECT',refId:null},opts).value;assert.equal(verifyProgressSnapshotCapsule(snapshot,opts).value,true);assert.equal(r.valid,true);assert.deepEqual(r.recomputedExact,snapshot.exact);});
test('M20 handoff is owner labelled and carries exact fraction',()=>{const {snapshot}=fixture(),h=createDelegatedProgressMetricHandoff(snapshot,H('m21-source'),H('m21-valid'),opts).value;assert.equal(h.owner,'M21_PROGRESS');assert.deepEqual([h.exactNumerator,h.exactDenominator],[45,45]);assert.equal(h.presentationBasisPoints,10000);});
test('M22 baseline handoff does not estimate ETA',()=>{const {snapshot}=fixture(),h=createEstimationBaselineHandoff([snapshot],opts).value;assert.equal(h.consumer,'M22_ESTIMATION');assert.equal(Object.hasOwn(h,'eta'),false);});
test('M23 status handoff carries progress facts without deciding overall status',()=>{const {snapshot}=fixture(),h=createStatusProgressHandoff(snapshot,false,opts).value;assert.equal(h.consumer,'M23_PROJECT_STATUS');assert.equal(Object.hasOwn(h,'projectStatus'),false);});
test('staleness sentinel rejects scope drift explicitly',()=>{const {snapshot}=fixture(),r=detectProgressStaleness(snapshot,{projectId:snapshot.projectId,lineageDigest:snapshot.lineageDigest,manifestDigest:snapshot.manifestDigest,epochId:snapshot.epochId,scopeDigest:H('other-scope'),dodDigest:snapshot.dodDigest,evidenceSetDigest:snapshot.evidenceSetDigest},opts).value;assert.equal(r.stale,true);assert.deepEqual(r.staleSubjects,['scope']);});
test('legitimate evidence invalidation creates lower snapshot and regression receipt',()=>{const {m,cs,base,graph,snapshot}=fixture(),dg=createCreditDependencyGraph(m,cs,{},true,opts).value,iv=createProgressInvalidationVector(dg,[cs[0].validityBindingDigest],['EVIDENCE_STALE'],opts).value,tr=createCreditRetractionTransaction(m,cs,{kind:'PROJECT',refId:null},iv,dg,opts).value,nextCredits=retractCredits(cs,iv,dg,opts).value,nextVector=createWeightedProgressVector(m,nextCredits,{kind:'PROJECT',refId:null},opts).value,next=createProgressSnapshot({baseline:base,vector:nextVector,graph,credits:nextCredits,evidenceSetDigest:H('evidence-set-2'),predecessorSemanticDigest:snapshot.semanticDigest},m,opts).value,rr=createProgressRegressionReceipt(snapshot,next,tr,['EVIDENCE_STALE'],opts).value;assert.equal(next.exact.numerator,31);assert.equal(rr.beforeExact.numerator,45);assert.equal(rr.afterExact.numerator,31);});
test('split brain detects divergent successors sharing predecessor',()=>{const f=fixture(),pred=H('common-predecessor'),a=createProgressSnapshot({baseline:f.base,vector:f.vector,graph:f.graph,credits:f.cs,evidenceSetDigest:H('e1'),predecessorSemanticDigest:pred},f.m,opts).value,b=createProgressSnapshot({baseline:f.base,vector:f.vector,graph:f.graph,credits:f.cs,evidenceSetDigest:H('e2'),predecessorSemanticDigest:pred},f.m,opts).value,w=createProgressSplitBrainWitness(a,b,opts).value;assert.equal(w.samePredecessor,true);assert.equal(w.divergent,true);});
test('cancellation fails closed before manifest construction',()=>{assert.equal(createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units}, {digest,cancellation:{isCancelled:()=>true}}).ok,false);});
test('malformed digest capability fails closed',()=>{assert.equal(createDenominatorIntegrityManifest({projectId:'gef-bootstrap',lineageDigest:H('lineage'),epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units},{digest:{algorithm:'sha256',digest:()=> 'bad'}}).ok,false);});
