import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import*as E from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const H=v=>'sha256:'+createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canon(v))).digest('hex');
function fixture(asOfEpochMs=1000){const snaps=Array.from({length:4},(_,i)=>({projectId:'P',lineageDigest:H('L'),epochId:'E',snapshotDigest:H('s'+i),semanticDigest:H('m'+i),predecessorSemanticDigest:i?H('m'+(i-1)):null,exactNumerator:i,exactDenominator:10,completeness:'COMPLETE'}));const body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:snaps.map(s=>s.snapshotDigest),semanticDigests:snaps.map(s=>s.semanticDigest)},handoff={...body,handoffDigest:H(body)},authority={owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},admission=E.admitProgressBaseline(handoff,snaps,authority,opts).value,obs=[],samples=[];for(let i=0;i<3;i++){const o=E.createTemporalObservation({observationId:'o'+i,owner:'EXTERNAL_CANONICAL',projectId:'P',lineageDigest:H('L'),epochId:'E',fromSnapshotDigest:snaps[i].snapshotDigest,toSnapshotDigest:snaps[i+1].snapshotDigest,elapsedMs:1000,sourceIdentityDigest:H('src'+i),validityBindingDigest:H('val'+i)},opts).value;obs.push(o);samples.push(E.createTemporalProgressSample(admission,snaps[i],snaps[i+1],o,authority,opts).value);}const index=E.createTemporalObservationAuthorityIndex(admission,obs,opts).value,window=E.createThroughputWindow(samples,H('wp'),opts).value,model=E.createRobustThroughputModel(window,samples,opts).value,remaining=E.createRemainingWorkVector(admission,snaps.at(-1),authority,opts).value,duration=E.createDurationProjection(remaining,model,opts).value,risk=E.createRiskAdjustmentVector([],opts).value,interval=E.createForecastInterval(duration,'AVAILABLE',risk,null,opts).value,scenarios=E.createScenarioTriad(interval,opts).value,receipts=[],bias=E.createCalibrationBiasSentinel(receipts,opts).value,drift=E.createModelDriftSentinel(model,model,{denominatorEpochChanged:false,observationPolicyChanged:false,biasState:bias.state,stale:false,conflict:false},opts).value,epoch=E.createRecalibrationEpoch('C',null,window.windowDigest,H('cp'),[H('trigger')],opts).value,binding=E.createEstimationBindingManifest(admission,index,H('ep'),risk.vectorDigest,epoch.epochDigest,opts).value,snapshot=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs,availability:'AVAILABLE',throughputModel:model,interval,scenarios,riskVectorDigest:risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:receipts,bias,drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts).value;return snapshot;}
function semanticBody(v){return{projectId:v.projectId,lineageDigest:v.lineageDigest,baselineAdmissionDigest:v.baselineAdmissionDigest,bindingManifestDigest:v.bindingManifestDigest,asOfEpochMs:v.asOfEpochMs,availability:v.availability,confidence:v.confidence,throughputModelDigest:v.throughputModelDigest,interval:v.interval,scenarios:v.scenarios,riskVectorDigest:v.riskVectorDigest,reserveDigest:v.reserveDigest,calibrationEpochDigest:v.calibrationEpochDigest,calibrationReceiptDigests:[...v.calibrationReceiptDigests].sort(),biasDigest:v.biasDigest,driftDigest:v.driftDigest,estimationPolicyDigest:v.estimationPolicyDigest,predecessorSnapshotDigest:v.predecessorSnapshotDigest};}
function resealSnapshot(core){const semanticDigest=H(semanticBody(core)),snapshotDigest=H({...semanticBody(core),semanticDigest});return{...core,semanticDigest,snapshotDigest};}
test('Correction 02: unavailable snapshot cannot be resealed with HIGH confidence',()=>{const s=fixture(),confidence={availability:'STALE',confidence:'HIGH',reasonCodes:['FORGED'],stateDigest:H({availability:'STALE',confidence:'HIGH',reasonCodes:['FORGED']})},bad=resealSnapshot({...s,availability:'STALE',confidence,throughputModelDigest:null,interval:null,scenarios:null});assert.equal(E.verifyEstimationSnapshot(bad,opts).value,false);});
test('Correction 02: integrity receipt must bind the exact snapshot',()=>{const s=fixture(1000),other=fixture(2000),r=E.createEstimationIntegrityReceipt(s,opts).value;assert.equal(E.verifyEstimationIntegrityReceipt(r,opts).value,true);assert.equal(E.verifyEstimationIntegrityReceiptAgainstSnapshot(r,s,opts).value,true);assert.equal(E.verifyEstimationIntegrityReceiptAgainstSnapshot(r,other,opts).value,false);});
test('Correction 02: unavailable handoff cannot retain HIGH confidence after reseal',()=>{const s=fixture(),h=E.createDelegatedEstimationMetricHandoff(s,H('src'),H('valid'),opts).value,body={owner:h.owner,consumer:h.consumer,snapshotDigest:h.snapshotDigest,availability:'STALE',confidence:'HIGH',lowerMs:null,baseMs:null,upperMs:null,sourceIdentityDigest:h.sourceIdentityDigest,validityBindingDigest:h.validityBindingDigest},bad={...body,handoffDigest:H(body)};assert.equal(E.verifyDelegatedEstimationMetricHandoff(bad,opts).value,false);});
