import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createEstimationIntentCapsule,createTemporalObservation,createTemporalProgressSample,createTemporalObservationAuthorityIndex,evaluateBaselineSufficiency,createThroughputWindow,createThroughputModel,createForecastIntervalEnvelope,createEstimationConfidenceState,createDelegatedEstimationMetricHandoff,verifyDelegatedEstimationMetricHandoff}from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const progressAuthority={verifySnapshot:()=>({ok:true,value:true})};
function sample(id,n,d=1000){const before={projectId:'p',lineageDigest:H('l'),snapshotDigest:H(`b${id}`),semanticDigest:H(`bs${id}`),manifestDigest:H('m'),epochId:'e',queryKind:'PROJECT',completeness:'COMPLETE',numerator:n,denominator:100};const after={...before,snapshotDigest:H(`a${id}`),semanticDigest:H(`as${id}`),numerator:n+10};const obs=createTemporalObservation({observationId:id,owner:'EXTERNAL_CANONICAL',elapsedMs:d,sourceIdentityDigest:H(`s${id}`),validityBindingDigest:H(`v${id}`)},opts).value;return createTemporalProgressSample(before,after,obs,progressAuthority,opts).value;}
test('M20 handoff verifier accepts a valid canonical interval and rejects tamper',()=>{const ss=[sample('a',10),sample('b',20),sample('c',30),sample('d',40),sample('e',50)];const idx=createTemporalObservationAuthorityIndex(ss.map(s=>s.observation),opts).value;assert.equal(evaluateBaselineSufficiency(ss,idx,opts).value.state,'AVAILABLE');const w=createThroughputWindow(ss,10,opts).value,m=createThroughputModel(w,opts).value;const f=createForecastIntervalEnvelope({availability:'AVAILABLE',remainingWorkNumerator:40,remainingWorkDenominator:100,model:m,policyDigest:H('p')},opts).value;const c=createEstimationConfidenceState({availability:'AVAILABLE',sampleCount:5,model:m,calibrationReceipts:[],activeConflict:false,activeDrift:false,activeBias:false},opts).value;const h=createDelegatedEstimationMetricHandoff({snapshotDigest:H('snap'),semanticDigest:H('sem'),interval:f,confidence:c,sourceIdentityDigest:H('src'),validityBindingDigest:H('valid')},opts).value;assert.equal(verifyDelegatedEstimationMetricHandoff(h,opts).value,true);assert.equal(verifyDelegatedEstimationMetricHandoff({...h,lowerDurationMs:h.upperDurationMs+1},opts).value,false);});
