import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import*as E from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const H=v=>'sha256:'+createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canon(v))).digest('hex');
function forecast(id='F'){return{snapshotDigest:H(id),semanticDigest:H(id+'S'),lowerMs:900,baseMs:1000,upperMs:1100};}
test('Correction 04: tampered ActualOutcome cannot mint calibration receipt',()=>{const f=forecast(),a=E.createActualOutcome({actualId:'A',owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:f.snapshotDigest,actualDurationMs:1000,sourceIdentityDigest:H('src'),validityBindingDigest:H('valid')},opts).value,bad={...a,actualDurationMs:1050};assert.equal(E.createForecastActualVarianceReceipt(f,bad,opts).ok,false);});
test('Correction 04: variance receipt exact-source verifier rejects another actual outcome',()=>{const f=forecast(),a=E.createActualOutcome({actualId:'A',owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:f.snapshotDigest,actualDurationMs:1000,sourceIdentityDigest:H('src'),validityBindingDigest:H('valid')},opts).value,r=E.createForecastActualVarianceReceipt(f,a,opts).value,other=E.createActualOutcome({actualId:'B',owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:f.snapshotDigest,actualDurationMs:1000,sourceIdentityDigest:H('src2'),validityBindingDigest:H('valid2')},opts).value;assert.equal(E.verifyForecastActualVarianceReceiptAgainstActual(r,a,opts).value,true);assert.equal(E.verifyForecastActualVarianceReceiptAgainstActual(r,other,opts).value,false);});
test('Correction 04: valid revision predecessor chain is admitted',()=>{const r1=E.createForecastRevisionReceipt({snapshotDigest:H('s0'),intervalDigest:H('i0')},{snapshotDigest:H('s1'),intervalDigest:H('i1')},null,['MODEL_DRIFT'],opts).value,r2=E.createForecastRevisionReceipt({snapshotDigest:H('s1'),intervalDigest:H('i1')},{snapshotDigest:H('s2'),intervalDigest:H('i2')},r1.receiptDigest,['RECALIBRATION'],opts).value;assert.equal(E.createRevisionReplayGuard([], [r2,r1],opts).ok,true);});
test('Correction 04: orphan or discontinuous revision predecessor is rejected',()=>{const orphan=E.createForecastRevisionReceipt({snapshotDigest:H('s1'),intervalDigest:H('i1')},{snapshotDigest:H('s2'),intervalDigest:H('i2')},H('missing'),['RECALIBRATION'],opts).value;assert.equal(E.createRevisionReplayGuard([], [orphan],opts).ok,false);const r1=E.createForecastRevisionReceipt({snapshotDigest:H('s0'),intervalDigest:H('i0')},{snapshotDigest:H('s1'),intervalDigest:H('i1')},null,['MODEL_DRIFT'],opts).value,bad=E.createForecastRevisionReceipt({snapshotDigest:H('wrong'),intervalDigest:H('iw')},{snapshotDigest:H('s2'),intervalDigest:H('i2')},r1.receiptDigest,['RECALIBRATION'],opts).value;assert.equal(E.createRevisionReplayGuard([], [r1,bad],opts).ok,false);});
