import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import*as E from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const H=v=>'sha256:'+createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canon(v))).digest('hex');
function fixture(){const snaps=Array.from({length:9},(_,i)=>({projectId:'P',lineageDigest:H('L'),epochId:'E',snapshotDigest:H('s'+i),semanticDigest:H('m'+i),predecessorSemanticDigest:i?H('m'+(i-1)):null,exactNumerator:i,exactDenominator:10,completeness:'COMPLETE'}));const body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:snaps.map(s=>s.snapshotDigest),semanticDigests:snaps.map(s=>s.semanticDigest)},handoff={...body,handoffDigest:H(body)},authority={owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},admission=E.admitProgressBaseline(handoff,snaps,authority,opts).value;const obs=[],samples=[];for(let i=0;i<8;i++){const o=E.createTemporalObservation({observationId:'o'+i,owner:'EXTERNAL_CANONICAL',projectId:'P',lineageDigest:H('L'),epochId:'E',fromSnapshotDigest:snaps[i].snapshotDigest,toSnapshotDigest:snaps[i+1].snapshotDigest,elapsedMs:1000,sourceIdentityDigest:H('src'+i),validityBindingDigest:H('val'+i)},opts).value;obs.push(o);samples.push(E.createTemporalProgressSample(admission,snaps[i],snaps[i+1],o,authority,opts).value);}const index=E.createTemporalObservationAuthorityIndex(admission,obs,opts).value,window=E.createThroughputWindow(samples,H('wp'),opts).value,model=E.createRobustThroughputModel(window,samples,opts).value,remaining=E.createRemainingWorkVector(admission,snaps.at(-1),authority,opts).value,duration=E.createDurationProjection(remaining,model,opts).value,risk=E.createRiskAdjustmentVector([],opts).value,interval=E.createForecastInterval(duration,'AVAILABLE',risk,null,opts).value,scenarios=E.createScenarioTriad(interval,opts).value,receipts=[];for(let i=0;i<5;i++){const forecast={snapshotDigest:H('forecast'+i),semanticDigest:H('fsem'+i),lowerMs:900,baseMs:1000,upperMs:1100},actual=E.createActualOutcome({actualId:'a'+i,owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:forecast.snapshotDigest,actualDurationMs:1000,sourceIdentityDigest:H('as'+i),validityBindingDigest:H('av'+i)},opts).value;receipts.push(E.createForecastActualVarianceReceipt(forecast,actual,opts).value);}const bias=E.createCalibrationBiasSentinel(receipts,opts).value,drift=E.createModelDriftSentinel(model,model,{denominatorEpochChanged:false,observationPolicyChanged:false,biasState:bias.state,stale:false,conflict:false},opts).value,epoch=E.createRecalibrationEpoch('C',null,window.windowDigest,H('cp'),[H('trigger')],opts).value,binding=E.createEstimationBindingManifest(admission,index,H('ep'),risk.vectorDigest,epoch.epochDigest,opts).value,snapshot=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:model,interval,scenarios,riskVectorDigest:risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:receipts,bias,drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts).value;return{snapshot};}
test('Correction 01: M20 handoff verifier accepts canonical handoff and rejects interval tamper',()=>{const{snapshot}=fixture(),h=E.createDelegatedEstimationMetricHandoff(snapshot,H('src'),H('valid'),opts).value;assert.equal(E.verifyDelegatedEstimationMetricHandoff(h,snapshot,opts).value,true);assert.equal(E.verifyDelegatedEstimationMetricHandoff({...h,lowerMs:h.upperMs+1},snapshot,opts).value,false);});
