import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';
import*as E from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const H=v=>'sha256:'+createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canon(v))).digest('hex');
function makeHistory(sampleCount=3,elapsed){const snaps=[];for(let i=0;i<=sampleCount;i++)snaps.push({projectId:'P',lineageDigest:H('lineage'),epochId:'E1',snapshotDigest:H('snap'+i),semanticDigest:H('sem'+i),predecessorSemanticDigest:i===0?null:H('sem'+(i-1)),exactNumerator:i,exactDenominator:10,completeness:'COMPLETE'});const body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:snaps.map(s=>s.snapshotDigest),semanticDigests:snaps.map(s=>s.semanticDigest)};const handoff={...body,handoffDigest:H(body)};const verified=new Set(snaps.map(s=>s.snapshotDigest)),authority={owner:'M21_PROGRESS',verifyProjectSnapshot:s=>verified.has(s.snapshotDigest)};const admission=E.admitProgressBaseline(handoff,snaps,authority,opts);assert.equal(admission.ok,true);const observations=[],samples=[];for(let i=0;i<sampleCount;i++){const o=E.createTemporalObservation({observationId:'obs'+i,owner:'EXTERNAL_CANONICAL',projectId:'P',lineageDigest:H('lineage'),epochId:'E1',fromSnapshotDigest:snaps[i].snapshotDigest,toSnapshotDigest:snaps[i+1].snapshotDigest,elapsedMs:elapsed?.[i]??1000,sourceIdentityDigest:H('source'+i),validityBindingDigest:H('valid'+i)},opts);assert.equal(o.ok,true);observations.push(o.value);const s=E.createTemporalProgressSample(admission.value,snaps[i],snaps[i+1],o.value,authority,opts);assert.equal(s.ok,true);samples.push(s.value);}const index=E.createTemporalObservationAuthorityIndex(admission.value,observations,opts);assert.equal(index.ok,true);const window=E.createThroughputWindow(samples,H('window-policy'),opts);assert.equal(window.ok,true);const model=sampleCount>=3?E.createRobustThroughputModel(window.value,samples,opts):null;if(model)assert.equal(model.ok,true);return{snaps,handoff,authority,admission:admission.value,observations,samples,index:index.value,window:window.value,model:model?.value};}
function makeForecast(sampleCount=3,elapsed){const f=makeHistory(sampleCount,elapsed),current=f.snaps.at(-1);const remaining=E.createRemainingWorkVector(f.admission,current,f.authority,opts);assert.equal(remaining.ok,true);const duration=E.createDurationProjection(remaining.value,f.model,opts);assert.equal(duration.ok,true);const risk=E.createRiskAdjustmentVector([],opts);assert.equal(risk.ok,true);const interval=E.createForecastInterval(duration.value,'AVAILABLE',risk.value,null,opts);assert.equal(interval.ok,true);const scenarios=E.createScenarioTriad(interval.value,opts);assert.equal(scenarios.ok,true);const bias=E.createCalibrationBiasSentinel([],opts);assert.equal(bias.ok,true);const drift=E.createModelDriftSentinel(f.model,f.model,{denominatorEpochChanged:false,observationPolicyChanged:false,biasState:'NONE',stale:false,conflict:false},opts);assert.equal(drift.ok,true);const epoch=E.createRecalibrationEpoch('C1',null,f.window.windowDigest,H('cal-policy'),[H('initial')],opts);assert.equal(epoch.ok,true);const binding=E.createEstimationBindingManifest(f.admission,f.index,H('est-policy'),risk.value.vectorDigest,epoch.value.epochDigest,opts);assert.equal(binding.ok,true);return{...f,current,remaining:remaining.value,duration:duration.value,risk:risk.value,interval:interval.value,scenarios:scenarios.value,bias:bias.value,drift:drift.value,epoch:epoch.value,binding:binding.value};}

test('M21 baseline handoff verifies exact digest',()=>{const f=makeHistory();assert.equal(E.verifyM21EstimationBaselineHandoff(f.handoff,opts).value,true);});
test('tampered M21 baseline handoff is rejected',()=>{const f=makeHistory(),bad={...f.handoff,snapshotDigests:[H('other'),...f.handoff.snapshotDigests.slice(1)]};assert.equal(E.verifyM21EstimationBaselineHandoff(bad,opts).value,false);});
test('baseline admission requires direct predecessor chain',()=>{const f=makeHistory(),s=[...f.snaps];s[2]={...s[2],predecessorSemanticDigest:H('wrong')};assert.equal(E.admitProgressBaseline(f.handoff,s,f.authority,opts).ok,false);});
test('baseline admission rejects cross lineage',()=>{const f=makeHistory(),s=[...f.snaps];s[1]={...s[1],lineageDigest:H('other')};assert.equal(E.admitProgressBaseline(f.handoff,s,{owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},opts).ok,false);});
test('baseline admission rejects incomplete snapshot',()=>{const f=makeHistory(),s=[...f.snaps];s[1]={...s[1],completeness:'STALE'};assert.equal(E.admitProgressBaseline(f.handoff,s,{owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},opts).ok,false);});
test('intent uses injected asOf and no ambient clock',()=>{const f=makeHistory(),i=E.createEstimationIntent('P',H('lineage'),f.handoff.handoffDigest,123456,opts);assert.equal(i.ok,true);assert.equal(i.value.asOfEpochMs,123456);});
test('authority boundary forbids progress/status/telemetry ownership',()=>{const f=makeHistory(),i=E.createEstimationIntent('P',H('lineage'),f.handoff.handoffDigest,1,opts).value,b=E.createEstimationAuthorityBoundary(i,opts).value;assert.equal(b.mayComputeProgress,false);assert.equal(b.mayCollectTelemetry,false);assert.equal(b.mayTreatWeightAsTime,false);});
test('temporal observation requires positive safe milliseconds',()=>{const f=makeHistory(),x={...f.observations[0],elapsedMs:0};assert.equal(E.createTemporalObservation(x,opts).ok,false);});
test('observation index rejects divergent duplicate ID',()=>{const f=makeHistory(),o=f.observations[0],other={...o,elapsedMs:o.elapsedMs+1};const rebuilt=E.createTemporalObservation(other,opts).value;assert.equal(E.createTemporalObservationAuthorityIndex(f.admission,[o,rebuilt],opts).ok,false);});
test('two independent samples remain NOT_YET_BASELINED',()=>{const f=makeHistory(2),g=E.evaluateBaselineSufficiency(f.samples.map(s=>s.sampleDigest),{stale:false,conflict:false,indeterminate:false},opts).value;assert.equal(g.availability,'NOT_YET_BASELINED');});
test('three independent samples become AVAILABLE',()=>{const f=makeHistory(3),g=E.evaluateBaselineSufficiency(f.samples.map(s=>s.sampleDigest),{stale:false,conflict:false,indeterminate:false},opts).value;assert.equal(g.availability,'AVAILABLE');});
test('duplicates cannot manufacture baseline',()=>{const f=makeHistory(2),ds=[f.samples[0].sampleDigest,f.samples[0].sampleDigest,f.samples[1].sampleDigest];assert.equal(E.evaluateBaselineSufficiency(ds,{stale:false,conflict:false,indeterminate:false},opts).value.availability,'NOT_YET_BASELINED');});
test('temporal sample computes exact work-per-ms',()=>{const f=makeHistory(3,[1000,2000,4000]);assert.deepEqual([f.samples[0].throughput.numerator,f.samples[0].throughput.denominator],[1,10000]);});
test('progress regression is not converted into negative productivity',()=>{const f=makeHistory(),o=f.observations[0];assert.equal(E.createTemporalProgressSample(f.admission,f.snaps[1],f.snaps[0],{...o,fromSnapshotDigest:f.snaps[1].snapshotDigest,toSnapshotDigest:f.snaps[0].snapshotDigest},f.authority,opts).ok,false);});
test('sample normalization deduplicates replay',()=>{const f=makeHistory(),w=E.createSampleNormalizationWitness([f.samples[0],f.samples[0],f.samples[1]],opts).value;assert.equal(w.acceptedSampleDigests.length,2);assert.equal(w.duplicateSampleDigests.length,1);});
test('robust model uses exact nearest-rank quartiles',()=>{const f=makeHistory(3,[1000,2000,4000]);assert.deepEqual([f.model.q1.denominator,f.model.median.denominator,f.model.q3.denominator],[40000,20000,10000]);});
test('throughput model is permutation invariant',()=>{const f=makeHistory(3,[1000,2000,4000]),w=E.createThroughputWindow([...f.samples].reverse(),H('window-policy'),opts).value,m=E.createRobustThroughputModel(w,[...f.samples].reverse(),opts).value;assert.equal(m.modelDigest,f.model.modelDigest);});
test('tampered throughput model is rejected',()=>{const f=makeHistory(),bad={...f.model,sampleCount:99};assert.equal(E.verifyThroughputModel(bad,opts).value,false);});
test('remaining work comes from current M21 progress',()=>{const f=makeHistory(),r=E.createRemainingWorkVector(f.admission,f.snaps.at(-1),f.authority,opts).value;assert.deepEqual([r.remaining.numerator,r.remaining.denominator],[7,10]);});
test('duration direction reverses throughput quartiles conservatively',()=>{const f=makeForecast(3,[1000,2000,4000]);assert.deepEqual([f.duration.lowerMs,f.duration.baseMs,f.duration.upperMs],[7000,14000,28000]);});
test('unknown reserve must be monotonic',()=>{assert.equal(E.createUnknownWorkReserve({reserveId:'R',owner:'EXTERNAL_CANONICAL',lowerBps:1000,baseBps:500,upperBps:2000,rationaleDigest:H('r')},opts).ok,false);});
test('risk vector is order invariant',()=>{const a=E.createRiskModifier({riskId:'a',owner:'EXTERNAL_CANONICAL',basisPoints:100,sourceIdentityDigest:H('s1'),validityBindingDigest:H('v1')},opts).value,b=E.createRiskModifier({riskId:'b',owner:'M43_TELEMETRY',basisPoints:200,sourceIdentityDigest:H('s2'),validityBindingDigest:H('v2')},opts).value;assert.equal(E.createRiskAdjustmentVector([a,b],opts).value.vectorDigest,E.createRiskAdjustmentVector([b,a],opts).value.vectorDigest);});
test('forecast interval remains ordered with explicit reserve',()=>{const f=makeForecast(),r=E.createUnknownWorkReserve({reserveId:'R',owner:'EXTERNAL_CANONICAL',lowerBps:0,baseBps:1000,upperBps:3000,rationaleDigest:H('r')},opts).value,i=E.createForecastInterval(f.duration,'AVAILABLE',f.risk,r,opts).value;assert.ok(i.lowerMs<=i.baseMs&&i.baseMs<=i.upperMs);});
test('scenario triad binds exact interval',()=>{const f=makeForecast(),s=E.createScenarioTriad(f.interval,opts).value;assert.equal(s.intervalDigest,f.interval.intervalDigest);});
test('LOW confidence blocks scalar precision',()=>{const d=E.createFalsePrecisionDecision('AVAILABLE','LOW',opts).value;assert.equal(d.scalarPresentationAllowed,false);});
test('deadline comparison cannot alter forecast interval',()=>{const f=makeForecast(),before=f.interval.intervalDigest,d=E.compareDeadline(f.interval,100000,120000,opts).value;assert.equal(f.interval.intervalDigest,before);assert.equal(d.deadlineEpochMs,120000);});
