import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{M22_MECHANISMS,estimateProject,createForecastVsActualVarianceReceipt,createRecalibrationEpoch,createForecastRevisionReceipt,guardRevisionReplay,createEstimationIntegrityReceipt,deriveEstimationConfidence,verifyEstimationSnapshotCapsule,verifyDelegatedEstimationMetricHandoff,verifyStatusEstimationHandoff}from'../packages/estimation-engine/dist/public.js';

const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')};
const opts={digest};
const H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const seal=v=>`sha256:${createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex')}`;
const lineage=H('lineage'),manifest=H('manifest');
function history(values=[0,10,30,60,80],epoch='epoch-1'){
 return values.map((numerator,sequence)=>({snapshotDigest:H(`snap-${epoch}-${sequence}-${numerator}`),semanticDigest:H(`sem-${epoch}-${sequence}-${numerator}`),projectId:'gef-bootstrap',lineageDigest:lineage,epochId:epoch,manifestDigest:manifest,sequence,numerator,denominator:100,completeness:'COMPLETE'}));
}
function handoff(h){const body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:h.map(x=>x.snapshotDigest),semanticDigests:h.map(x=>x.semanticDigest)};return{...body,handoffDigest:seal(body)};}
function observations(h,elapsed=[1000,1000,1500,2000],asOf=1_000_000){return elapsed.map((elapsedMs,i)=>({observationId:`obs-${i}`,owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,epochId:h[i].epochId,beforeSnapshotDigest:h[i].snapshotDigest,afterSnapshotDigest:h[i+1].snapshotDigest,elapsedMs,observedAtEpochMs:asOf-10_000+i*1000,sourceIdentityDigest:H(`obs-source-${i}`)}));}
function input({values=[0,10,30,60,80],elapsed=[1000,1000,1500,2000],obsCount=elapsed.length,requireRiskInputs=false,riskModifiers=[],unknownReserve=null,deadlineEpochMs,calibrationReceipts=[],epoch='epoch-1'}={}){
 const h=history(values,epoch),bh=handoff(h),asOf=1_000_000,obs=observations(h,elapsed,asOf).slice(0,obsCount);return{intent:{projectId:'gef-bootstrap',lineageDigest:lineage,horizon:'PROJECT_COMPLETION',baselineHandoffDigest:bh.handoffDigest,asOfEpochMs:asOf,requestedOutput:'HANDOFFS'},baselineHandoff:bh,progressHistory:h,observations:obs,policy:{maxWindowSamples:64,staleAfterMs:100_000,requireRiskInputs,calibrationWindow:20,policyVersion:'m22-v1'},riskModifiers,unknownReserve,calibrationReceipts,...(deadlineEpochMs===undefined?{}:{deadlineEpochMs})};
}
function revisionBindings(before,after,overrides={}){return{beforeBindingManifestDigest:before.value.binding.manifestDigest,afterBindingManifestDigest:after.value.binding.manifestDigest,beforeModelDigest:before.value.model?.modelDigest??null,afterModelDigest:after.value.model?.modelDigest??null,beforeCalibrationEpochId:before.value.binding.calibrationEpochId,afterCalibrationEpochId:after.value.binding.calibrationEpochId,...overrides};}

test('all 30 frozen M22 mechanisms are represented',()=>{assert.equal(M22_MECHANISMS.length,30);assert.equal(new Set(M22_MECHANISMS).size,30);});
test('empirical throughput produces exact conservative interval',()=>{const r=estimateProject(input(),opts);assert.equal(r.ok,true);assert.equal(r.value.sufficiency.state,'AVAILABLE');assert.equal(r.value.model.sampleCount,4);assert.deepEqual([r.value.duration.lowerMs,r.value.duration.baseMs,r.value.duration.upperMs],[1000,2000,2000]);assert.equal(r.value.confidence.confidence,'LOW');assert.equal(r.value.integrityReceipt.valid,true);});
test('2 samples cannot fabricate an ETA',()=>{const r=estimateProject(input({obsCount:2}),opts);assert.equal(r.ok,true);assert.equal(r.value.sufficiency.state,'NOT_YET_BASELINED');assert.equal(r.value.envelope.baseDurationMs,null);assert.equal(r.value.delegatedHandoff.availability,'NOT_YET_BASELINED');assert.equal(r.value.confidence.confidence,'UNKNOWN');});
test('3 independent positive samples cross availability gate',()=>{const r=estimateProject(input({obsCount:3}),opts);assert.equal(r.ok,true);assert.equal(r.value.sufficiency.independentSampleCount,3);assert.equal(r.value.sufficiency.state,'AVAILABLE');assert.notEqual(r.value.envelope.baseDurationMs,null);});
test('observation permutation cannot alter canonical estimation truth',()=>{const a=input(),b=input();b.observations=[...b.observations].reverse();const ra=estimateProject(a,opts),rb=estimateProject(b,opts);assert.equal(ra.ok,true);assert.equal(rb.ok,true);assert.equal(ra.value.observationIndex.indexDigest,rb.value.observationIndex.indexDigest);assert.equal(ra.value.snapshot.semanticDigest,rb.value.snapshot.semanticDigest);});
test('duplicate observation id cannot increase independent count',()=>{const x=input();x.observations=[...x.observations,{...x.observations[0]}];const r=estimateProject(x,opts);assert.equal(r.ok,true);assert.equal(r.value.sufficiency.independentSampleCount,4);assert.deepEqual(r.value.observationIndex.duplicateObservationIds,['obs-0']);});
test('resealed duplicate observation identity fails closed as conflict',()=>{const x=input();x.observations=[...x.observations,{...x.observations[0],elapsedMs:9999}];const r=estimateProject(x,opts);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OAI22_DUPLICATE_CONFLICT');});
test('replayed progress pair is visible and does not count twice',()=>{const x=input();x.observations=[...x.observations,{...x.observations[0],observationId:'obs-replay',sourceIdentityDigest:H('replay')}];const r=estimateProject(x,opts);assert.equal(r.ok,true);assert.equal(r.value.sufficiency.independentSampleCount,4);assert.equal(r.value.normalization.exclusions.some(e=>e.reason==='REPLAY'),true);});
test('progress regression is preserved as correction event, not negative throughput',()=>{const x=input({values:[0,20,10,40,70],elapsed:[1000,1000,1000,1000]});const r=estimateProject(x,opts);assert.equal(r.ok,true);assert.equal(r.value.sufficiency.independentSampleCount,3);assert.equal(r.value.normalization.regressions.length,1);assert.equal(r.value.normalization.exclusions.some(e=>e.reason==='PROGRESS_REGRESSION'),true);assert.equal(r.value.model.sampleCount,3);});
test('observation with incompatible denominator epoch fails closed',()=>{const x=input();x.observations=[...x.observations];x.observations[0]={...x.observations[0],epochId:'epoch-2'};const r=estimateProject(x,opts);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OAI22_EPOCH_MISMATCH');});
test('baseline history cannot silently pool denominator epochs',()=>{const x=input();x.progressHistory=[...x.progressHistory];x.progressHistory[2]={...x.progressHistory[2],epochId:'epoch-2'};const body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:x.progressHistory.map(v=>v.snapshotDigest),semanticDigests:x.progressHistory.map(v=>v.semanticDigest)};x.baselineHandoff={...body,handoffDigest:seal(body)};x.intent={...x.intent,baselineHandoffDigest:x.baselineHandoff.handoffDigest};const r=estimateProject(x,opts);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'PBA22_EPOCH_CONFLICT');});
test('required risk knowledge cannot be silently assumed safe',()=>{const r=estimateProject(input({requireRiskInputs:true}),opts);assert.equal(r.ok,true);assert.equal(r.value.envelope.availability,'INDETERMINATE');assert.equal(r.value.confidence.confidence,'UNKNOWN');});
test('explicit unknown-work reserve only widens conservative forecast',()=>{const base=estimateProject(input(),opts);const reserve={owner:'EXTERNAL_CANONICAL',reserveId:'reserve-1',projectId:'gef-bootstrap',lineageDigest:lineage,numerator:10,denominator:100,rationaleCode:'UNKNOWN_WORK',sourceIdentityDigest:H('reserve-source')};const widened=estimateProject(input({unknownReserve:reserve}),opts);assert.equal(base.ok,true);assert.equal(widened.ok,true);assert.equal(widened.value.envelope.lowerDurationMs,base.value.envelope.lowerDurationMs);assert.equal(widened.value.envelope.baseDurationMs,base.value.envelope.baseDurationMs);assert.ok(widened.value.envelope.upperDurationMs>base.value.envelope.upperDurationMs);});
test('deadline comparison cannot bend forecast model or snapshot',()=>{const a=estimateProject(input(),opts),b=estimateProject(input({deadlineEpochMs:1_100_000}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(a.value.envelope.envelopeDigest,b.value.envelope.envelopeDigest);assert.equal(a.value.snapshot.snapshotDigest,b.value.snapshot.snapshotDigest);assert.notEqual(b.value.statusHandoff.deadlineComparison,null);});
test('ambient system clock is not consulted by semantic workflow',()=>{const original=Date.now;Date.now=()=>{throw new Error('ambient clock forbidden');};try{const r=estimateProject(input(),opts);assert.equal(r.ok,true);}finally{Date.now=original;}});
test('invalid digest capability fails closed',()=>{const r=estimateProject(input(),{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_OUTPUT_INVALID');});
test('cancellation is honored',()=>{const r=estimateProject(input(),{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_CANCELLED');});
test('bounded work budget is enforced',()=>{const r=estimateProject(input(),{digest,maxUnits:1});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_BUDGET_EXCEEDED');});

test('8 calibrated stable samples can earn HIGH confidence',()=>{const values=[0,10,20,30,40,50,60,70,80],elapsed=Array(8).fill(1000);const first=estimateProject(input({values,elapsed}),opts);assert.equal(first.ok,true);const receipts=[];for(let i=0;i<5;i++){const rr=createForecastVsActualVarianceReceipt(first.value.envelope,{actualId:`actual-${i}`,owner:'EXTERNAL_CANONICAL',forecastEnvelopeDigest:first.value.envelope.envelopeDigest,elapsedMs:first.value.envelope.baseDurationMs,observedAtEpochMs:2_000_000+i,sourceIdentityDigest:H(`actual-source-${i}`)},opts);assert.equal(rr.ok,true);receipts.push(rr.value);}const second=estimateProject(input({values,elapsed,calibrationReceipts:receipts}),opts);assert.equal(second.ok,true);assert.equal(second.value.model.sampleCount,8);assert.equal(second.value.confidence.confidence,'HIGH');});
test('systematic optimism is detected and prevents confidence upgrade',()=>{const values=[0,10,20,30,40,50,60,70,80],elapsed=Array(8).fill(1000);const first=estimateProject(input({values,elapsed}),opts);const receipts=[];for(let i=0;i<5;i++)receipts.push(createForecastVsActualVarianceReceipt(first.value.envelope,{actualId:`late-${i}`,owner:'EXTERNAL_CANONICAL',forecastEnvelopeDigest:first.value.envelope.envelopeDigest,elapsedMs:first.value.envelope.upperDurationMs+1000,observedAtEpochMs:2_000_000+i,sourceIdentityDigest:H(`late-source-${i}`)},opts).value);const second=estimateProject(input({values,elapsed,calibrationReceipts:receipts}),opts);assert.equal(second.ok,true);assert.equal(second.value.bias.state,'OPTIMISTIC_BIAS');assert.equal(second.value.drift.state,'DRIFTED');assert.equal(second.value.confidence.confidence,'LOW');});
test('snapshot tampering is detected by independent semantic recomputation',()=>{const r=estimateProject(input(),opts);assert.equal(r.ok,true);const tampered={...r.value.snapshot,forecastEnvelope:{...r.value.snapshot.forecastEnvelope,baseDurationMs:r.value.snapshot.forecastEnvelope.baseDurationMs+1}};const receipt=createEstimationIntegrityReceipt(tampered,opts);assert.equal(receipt.ok,true);assert.equal(receipt.value.valid,false);});
test('recalibration requires a governed drift or bias trigger',()=>{const r=estimateProject(input(),opts);const denied=createRecalibrationEpoch('RCE22-INITIAL','RCE22-2',r.value.drift,r.value.bias,r.value.window.windowDigest,r.value.policy.policyDigest,opts);assert.equal(denied.ok,false);});
test('forecast revisions preserve before/after identities and replay is visible',()=>{const a=estimateProject(input(),opts);const risk={modifierId:'risk-1',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:100,conservativeAddedMs:500,sourceIdentityDigest:H('risk-1')};const b=estimateProject(input({riskModifiers:[risk]}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);const rev=createForecastRevisionReceipt('rev-1',a.value.envelope,b.value.envelope,revisionBindings(a,b),['RISK_INPUT_CHANGED'],opts);assert.equal(rev.ok,true);const guard=guardRevisionReplay([rev.value,rev.value],[],64,opts);assert.equal(guard.ok,true);assert.equal(guard.value.state,'CLEAR');assert.equal(guard.value.acceptedRevisionDigests.length,1);assert.equal(guard.value.duplicateRevisionDigests.length,1);});

test('compatible denominator epoch transition may reuse explicitly witnessed history',()=>{
 const manifest2=H('manifest-2'),asOf=1_000_000,vals=[0,10,20,30,40,50,60];const h=vals.map((numerator,sequence)=>({snapshotDigest:H(`mx-snap-${sequence}`),semanticDigest:H(`mx-sem-${sequence}`),projectId:'gef-bootstrap',lineageDigest:lineage,epochId:sequence<=2?'epoch-1':'epoch-2',manifestDigest:sequence<=2?manifest:manifest2,sequence,numerator,denominator:100,completeness:'COMPLETE'}));const bh=handoff(h);const witness={witnessId:'epoch-transition-1',owner:'M21_PROGRESS',projectId:'gef-bootstrap',lineageDigest:lineage,fromEpochId:'epoch-1',toEpochId:'epoch-2',fromManifestDigest:manifest,toManifestDigest:manifest2,translationDigest:H('translation'),sourceIdentityDigest:H('m21-transition-source')};
 const pairs=[[0,1],[1,2],[3,4],[4,5],[5,6]];const obs=pairs.map(([a,b],i)=>({observationId:`mx-obs-${i}`,owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,epochId:h[a].epochId,beforeSnapshotDigest:h[a].snapshotDigest,afterSnapshotDigest:h[b].snapshotDigest,elapsedMs:1000,observedAtEpochMs:asOf-5000+i*500,sourceIdentityDigest:H(`mx-source-${i}`)}));const x={intent:{projectId:'gef-bootstrap',lineageDigest:lineage,horizon:'PROJECT_COMPLETION',baselineHandoffDigest:bh.handoffDigest,asOfEpochMs:asOf,requestedOutput:'HANDOFFS'},baselineHandoff:bh,progressHistory:h,epochCompatibilityWitnesses:[witness],observations:obs,policy:{maxWindowSamples:64,staleAfterMs:100_000,requireRiskInputs:false,calibrationWindow:20,policyVersion:'m22-v1'}};const r=estimateProject(x,opts);assert.equal(r.ok,true);assert.equal(r.value.baseline.epochId,'epoch-2');assert.equal(r.value.baseline.epochCompatibilityWitnessDigests.length,1);assert.equal(r.value.sufficiency.independentSampleCount,5);assert.equal(r.value.model.sampleCount,5);
});

test('snapshot and handoff verifiers reject stale or mix-and-match authority',()=>{const a=estimateProject(input(),opts);const risk={modifierId:'risk-verify',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:20,conservativeAddedMs:40,sourceIdentityDigest:H('risk-verify')};const b=estimateProject(input({riskModifiers:[risk]}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(verifyEstimationSnapshotCapsule(a.value.snapshot,a.value.binding,a.value.observationIndex.indexDigest,a.value.model.modelDigest,opts).value,true);assert.equal(verifyEstimationSnapshotCapsule(a.value.snapshot,b.value.binding,a.value.observationIndex.indexDigest,a.value.model.modelDigest,opts).value,false);assert.equal(verifyDelegatedEstimationMetricHandoff(a.value.delegatedHandoff,a.value.snapshot,opts).value,true);assert.equal(verifyDelegatedEstimationMetricHandoff(a.value.delegatedHandoff,b.value.snapshot,opts).value,false);assert.equal(verifyStatusEstimationHandoff(a.value.statusHandoff,b.value.snapshot,opts).value,false);});

test('snapshotDigest tampering also fails integrity receipt',()=>{const r=estimateProject(input(),opts);const tampered={...r.value.snapshot,snapshotDigest:H('forged-snapshot')};const receipt=createEstimationIntegrityReceipt(tampered,opts);assert.equal(receipt.ok,true);assert.equal(receipt.value.valid,false);});

function rat(n,d){return{numerator:String(n),denominator:String(d),rationalDigest:H(`r-${n}-${d}`)};}
function model(count,q1,q2,q3){return{q1,q2,q3,sampleCount:count,modelDigest:H(`model-${count}-${q1.numerator}-${q3.numerator}`)};}
const suff={state:'AVAILABLE',independentSampleCount:8,reasonCodes:[],gateDigest:H('gate')};
const noBias={state:'NONE',resolvedCount:5,containedCount:5,reasonCodes:[],sentinelDigest:H('bias-none')};
const currentDrift={state:'CURRENT',reasonCodes:[],sentinelDigest:H('drift-current')};
function calibrationReceipts(contained=5){return Array.from({length:5},(_,i)=>({actualId:`cal-${i}`,actualOwner:'EXTERNAL_CANONICAL',forecastEnvelopeDigest:H('forecast'),elapsedMs:1000,observedAtEpochMs:10_000+i,sourceIdentityDigest:H(`cal-source-${i}`),outcome:i<contained?'WITHIN_INTERVAL':'ABOVE_INTERVAL',signedBaseVarianceMs:0,receiptDigest:H(`cal-receipt-${contained}-${i}`)}));}

test('confidence boundary 4 -> 5 upgrades only to MEDIUM with sufficient calibration',()=>{const receipts=calibrationReceipts(5).slice(0,3);const m4=model(4,rat(1,10),rat(3,20),rat(1,5)),m5=model(5,rat(1,10),rat(3,20),rat(1,5));assert.equal(deriveEstimationConfidence({...suff,independentSampleCount:4},m4,receipts,noBias,currentDrift,opts).value.confidence,'LOW');assert.equal(deriveEstimationConfidence({...suff,independentSampleCount:5},m5,receipts,noBias,currentDrift,opts).value.confidence,'MEDIUM');});
test('confidence boundary 7 -> 8 and exact dispersion 3/2 governs HIGH',()=>{const receipts=calibrationReceipts(4),q1=rat(1,5),q2=rat(1,4),q3=rat(3,10);assert.equal(deriveEstimationConfidence({...suff,independentSampleCount:7},model(7,q1,q2,q3),receipts,noBias,currentDrift,opts).value.confidence,'MEDIUM');assert.equal(deriveEstimationConfidence(suff,model(8,q1,q2,q3),receipts,noBias,currentDrift,opts).value.confidence,'HIGH');});
test('HIGH confidence requires at least 4/5 recent interval coverage',()=>{const q1=rat(1,5),q2=rat(1,4),q3=rat(3,10);assert.equal(deriveEstimationConfidence(suff,model(8,q1,q2,q3),calibrationReceipts(3),noBias,currentDrift,opts).value.confidence,'MEDIUM');});
test('dispersion above 3/2 but at or below 2 caps confidence at MEDIUM',()=>{const q1=rat(1,5),q2=rat(3,10),q3=rat(2,5);assert.equal(deriveEstimationConfidence(suff,model(8,q1,q2,q3),calibrationReceipts(5),noBias,currentDrift,opts).value.confidence,'MEDIUM');});

test('FRR22 seals exact input/model/epoch bindings and interval impact',()=>{const a=estimateProject(input(),opts),risk={modifierId:'risk-bindings',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:125,conservativeAddedMs:375,sourceIdentityDigest:H('risk-bindings')},b=estimateProject(input({riskModifiers:[risk]}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);const bindings=revisionBindings(a,b),rev=createForecastRevisionReceipt('rev-bindings',a.value.envelope,b.value.envelope,bindings,['RISK_INPUT_CHANGED'],opts);assert.equal(rev.ok,true);assert.equal(rev.value.beforeBindingManifestDigest,a.value.binding.manifestDigest);assert.equal(rev.value.afterBindingManifestDigest,b.value.binding.manifestDigest);assert.equal(rev.value.bindingImpact.bindingManifestChanged,true);assert.equal(rev.value.bindingImpact.modelChanged,false);assert.equal(rev.value.intervalImpact.baseDurationDeltaMs,b.value.envelope.baseDurationMs-a.value.envelope.baseDurationMs);assert.equal(rev.value.intervalImpact.upperDurationDeltaMs,b.value.envelope.upperDurationMs-a.value.envelope.upperDurationMs);});

test('RPG22 makes recalibration replay idempotent and visible',()=>{const drift={state:'DRIFTED',reasonCodes:['TEST_DRIFT'],sentinelDigest:H('drift-replay')},bias={state:'OPTIMISTIC_BIAS',resolvedCount:5,containedCount:0,reasonCodes:['REPEATED_ABOVE_INTERVAL'],sentinelDigest:H('bias-replay')};const epoch=createRecalibrationEpoch('RCE22-INITIAL','RCE22-2',drift,bias,H('window-replay'),H('policy-replay'),opts);assert.equal(epoch.ok,true);const guard=guardRevisionReplay([], [epoch.value,epoch.value],64,opts);assert.equal(guard.ok,true);assert.equal(guard.value.state,'CLEAR');assert.equal(guard.value.acceptedRecalibrationEpochDigests.length,1);assert.equal(guard.value.duplicateRecalibrationEpochDigests.length,1);});

test('RPG22 detects forecast split-brain and branch-mix histories',()=>{const a=estimateProject(input(),opts),riskB={modifierId:'risk-b',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:100,conservativeAddedMs:200,sourceIdentityDigest:H('risk-b')},riskC={modifierId:'risk-c',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:300,conservativeAddedMs:600,sourceIdentityDigest:H('risk-c')},b=estimateProject(input({riskModifiers:[riskB]}),opts),c=estimateProject(input({riskModifiers:[riskC]}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(c.ok,true);const r1=createForecastRevisionReceipt('rev-a-b',a.value.envelope,b.value.envelope,revisionBindings(a,b),['RISK_INPUT_CHANGED'],opts),r2=createForecastRevisionReceipt('rev-a-c',a.value.envelope,c.value.envelope,revisionBindings(a,c),['RISK_INPUT_CHANGED'],opts),r3=createForecastRevisionReceipt('rev-b-c',b.value.envelope,c.value.envelope,revisionBindings(b,c),['RISK_INPUT_CHANGED'],opts);assert.equal(r1.ok,true);assert.equal(r2.ok,true);assert.equal(r3.ok,true);const guard=guardRevisionReplay([r1.value,r2.value,r3.value],[],64,opts);assert.equal(guard.ok,true);assert.equal(guard.value.state,'CONFLICT');assert.deepEqual(guard.value.splitBrainBeforeEnvelopeDigests,[a.value.envelope.envelopeDigest]);assert.deepEqual(guard.value.branchMixAfterEnvelopeDigests,[c.value.envelope.envelopeDigest]);});

test('RPG22 rejects unproven recalibration epoch mix',()=>{const a=estimateProject(input(),opts),risk={modifierId:'risk-epoch-mix',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:50,conservativeAddedMs:100,sourceIdentityDigest:H('risk-epoch-mix')},b=estimateProject(input({riskModifiers:[risk]}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);const drift={state:'DRIFTED',reasonCodes:['TEST_DRIFT'],sentinelDigest:H('drift-epoch')},bias={state:'OPTIMISTIC_BIAS',resolvedCount:5,containedCount:0,reasonCodes:['REPEATED_ABOVE_INTERVAL'],sentinelDigest:H('bias-epoch')},epoch=createRecalibrationEpoch('RCE22-INITIAL','RCE22-2',drift,bias,H('window-epoch'),H('policy-epoch'),opts);assert.equal(epoch.ok,true);const bindings=revisionBindings(a,b,{beforeCalibrationEpochId:'RCE22-INITIAL',afterCalibrationEpochId:'RCE22-3'}),rev=createForecastRevisionReceipt('rev-epoch-mix',a.value.envelope,b.value.envelope,bindings,['RECALIBRATION_CHANGED'],opts);assert.equal(rev.ok,true);const guard=guardRevisionReplay([rev.value],[epoch.value],64,opts);assert.equal(guard.ok,true);assert.equal(guard.value.state,'CONFLICT');assert.deepEqual(guard.value.epochMixRevisionIds,['rev-epoch-mix']);});

test('RPG22 exposes bounded-history truncation instead of claiming complete evidence',()=>{const a=estimateProject(input(),opts),riskB={modifierId:'risk-trunc-b',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:25,conservativeAddedMs:50,sourceIdentityDigest:H('risk-trunc-b')},riskC={modifierId:'risk-trunc-c',owner:'EXTERNAL_CANONICAL',projectId:'gef-bootstrap',lineageDigest:lineage,baseAddedMs:75,conservativeAddedMs:150,sourceIdentityDigest:H('risk-trunc-c')},b=estimateProject(input({riskModifiers:[riskB]}),opts),c=estimateProject(input({riskModifiers:[riskC]}),opts);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(c.ok,true);const r1=createForecastRevisionReceipt('rev-trunc-1',a.value.envelope,b.value.envelope,revisionBindings(a,b),['RISK_INPUT_CHANGED'],opts),r2=createForecastRevisionReceipt('rev-trunc-2',b.value.envelope,c.value.envelope,revisionBindings(b,c),['RISK_INPUT_CHANGED'],opts);assert.equal(r1.ok,true);assert.equal(r2.ok,true);const guard=guardRevisionReplay([r1.value,r2.value],[],1,opts);assert.equal(guard.ok,true);assert.equal(guard.value.state,'TRUNCATED');assert.equal(guard.value.historyTruncated,true);assert.equal(guard.value.processedRevisionCount,1);assert.equal(guard.value.totalRevisionCount,2);});