import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import*as E from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;
const H=v=>'sha256:'+createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canon(v))).digest('hex');
function fixture(){const times=[1000,2000,4000],snaps=Array.from({length:4},(_,i)=>({projectId:'P',lineageDigest:H('L'),epochId:'E',snapshotDigest:H('s'+i),semanticDigest:H('m'+i),predecessorSemanticDigest:i?H('m'+(i-1)):null,exactNumerator:i,exactDenominator:10,completeness:'COMPLETE'})),body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:snaps.map(s=>s.snapshotDigest),semanticDigests:snaps.map(s=>s.semanticDigest)},handoff={...body,handoffDigest:H(body)},authority={owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},admission=E.admitProgressBaseline(handoff,snaps,authority,opts).value,samples=[];for(let i=0;i<3;i++){const o=E.createTemporalObservation({observationId:'o'+i,owner:'EXTERNAL_CANONICAL',projectId:'P',lineageDigest:H('L'),epochId:'E',fromSnapshotDigest:snaps[i].snapshotDigest,toSnapshotDigest:snaps[i+1].snapshotDigest,elapsedMs:times[i],sourceIdentityDigest:H('src'+i),validityBindingDigest:H('val'+i)},opts).value;samples.push(E.createTemporalProgressSample(admission,snaps[i],snaps[i+1],o,authority,opts).value);}const window=E.createThroughputWindow(samples,H('wp'),opts).value,model=E.createRobustThroughputModel(window,samples,opts).value,remaining=E.createRemainingWorkVector(admission,snaps.at(-1),authority,opts).value,duration=E.createDurationProjection(remaining,model,opts).value,risk=E.createRiskAdjustmentVector([],opts).value,interval=E.createForecastIntervalAgainstSources(duration,remaining,model,'AVAILABLE',risk,null,opts).value,scenarios=E.createScenarioTriad(interval,opts).value;return{remaining,model,duration,risk,interval,scenarios};}
test('Correction 03: resealed duration cannot pass exact-source verification',()=>{const f=fixture(),body={modelDigest:f.duration.modelDigest,remainingWorkDigest:f.duration.remainingWorkDigest,lowerMs:f.duration.lowerMs,baseMs:f.duration.baseMs+1,upperMs:f.duration.upperMs},bad={...body,projectionDigest:H(body)};assert.equal(E.verifyDurationProjection(bad,opts).value,true);assert.equal(E.verifyDurationProjectionAgainstSources(bad,f.remaining,f.model,opts).value,false);assert.equal(E.createForecastIntervalAgainstSources(bad,f.remaining,f.model,'AVAILABLE',f.risk,null,opts).ok,false);});
test('Correction 03: scenario creation rejects interval tamper',()=>{const f=fixture(),bad={...f.interval,upperMs:f.interval.upperMs+1};assert.equal(E.createScenarioTriad(bad,opts).ok,false);assert.equal(E.compareDeadline(bad,1000,999999,opts).ok,false);});
test('Correction 03: scenario proof binds the exact interval identity',()=>{const f=fixture(),other=E.createForecastIntervalAgainstSources(f.duration,f.remaining,f.model,'AVAILABLE',f.risk,E.createUnknownWorkReserve({reserveId:'R',owner:'EXTERNAL_CANONICAL',lowerBps:0,baseBps:100,upperBps:200,rationaleDigest:H('r')},opts).value,opts).value;assert.equal(E.verifyScenarioTriadAgainstInterval(f.scenarios,f.interval,opts).value,true);assert.equal(E.verifyScenarioTriadAgainstInterval(f.scenarios,other,opts).value,false);});
