import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';import*as E from'../packages/estimation-engine/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};const canon=v=>Array.isArray(v)?v.map(canon):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])])):v;const H=v=>'sha256:'+createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canon(v))).digest('hex');
function history(n=8,times=[]){const snaps=Array.from({length:n+1},(_,i)=>({projectId:'P',lineageDigest:H('L'),epochId:'E',snapshotDigest:H('s'+i),semanticDigest:H('m'+i),predecessorSemanticDigest:i?H('m'+(i-1)):null,exactNumerator:i,exactDenominator:10,completeness:'COMPLETE'}));const body={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:snaps.map(s=>s.snapshotDigest),semanticDigests:snaps.map(s=>s.semanticDigest)},handoff={...body,handoffDigest:H(body)},authority={owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},admission=E.admitProgressBaseline(handoff,snaps,authority,opts).value;const obs=[],samples=[];for(let i=0;i<n;i++){const o=E.createTemporalObservation({observationId:'o'+i,owner:'EXTERNAL_CANONICAL',projectId:'P',lineageDigest:H('L'),epochId:'E',fromSnapshotDigest:snaps[i].snapshotDigest,toSnapshotDigest:snaps[i+1].snapshotDigest,elapsedMs:times[i]??1000,sourceIdentityDigest:H('src'+i),validityBindingDigest:H('val'+i)},opts).value;obs.push(o);samples.push(E.createTemporalProgressSample(admission,snaps[i],snaps[i+1],o,authority,opts).value);}const index=E.createTemporalObservationAuthorityIndex(admission,obs,opts).value,window=E.createThroughputWindow(samples,H('wp'),opts).value,model=E.createRobustThroughputModel(window,samples,opts).value,remaining=E.createRemainingWorkVector(admission,snaps.at(-1),authority,opts).value,duration=E.createDurationProjection(remaining,model,opts).value,risk=E.createRiskAdjustmentVector([],opts).value,interval=E.createForecastInterval(duration,'AVAILABLE',risk,null,opts).value,scenarios=E.createScenarioTriad(interval,opts).value;return{snaps,admission,index,window,model,remaining,duration,risk,interval,scenarios};}
function calibration(model,count=5,outsideLast=false){const receipts=[];for(let i=0;i<count;i++){const forecast={snapshotDigest:H('forecast'+i),semanticDigest:H('fsem'+i),lowerMs:900,baseMs:1000,upperMs:1100};const actual=E.createActualOutcome({actualId:'a'+i,owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:forecast.snapshotDigest,actualDurationMs:outsideLast&&i===count-1?1200:1000,sourceIdentityDigest:H('as'+i),validityBindingDigest:H('av'+i)},opts).value;receipts.push(E.createForecastActualVarianceReceipt(forecast,actual,opts).value);}const bias=E.createCalibrationBiasSentinel(receipts,opts).value,drift=E.createModelDriftSentinel(model,model,{denominatorEpochChanged:false,observationPolicyChanged:false,biasState:bias.state,stale:false,conflict:false},opts).value;return{receipts,bias,drift};}

test('forecast-vs-actual receipt binds historical forecast identity',()=>{const f=history(),forecast={snapshotDigest:H('F'),semanticDigest:H('FS'),lowerMs:900,baseMs:1000,upperMs:1100},a=E.createActualOutcome({actualId:'A',owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:forecast.snapshotDigest,actualDurationMs:1050,sourceIdentityDigest:H('S'),validityBindingDigest:H('V')},opts).value,r=E.createForecastActualVarianceReceipt(forecast,a,opts).value;assert.equal(r.contained,true);assert.equal(r.signedErrorMs,50);});
test('systematic optimism is detected',()=>{const f=history(),receipts=[];for(let i=0;i<3;i++){const forecast={snapshotDigest:H('F'+i),semanticDigest:H('FS'+i),lowerMs:100,baseMs:200,upperMs:300},a=E.createActualOutcome({actualId:'A'+i,owner:'EXTERNAL_CANONICAL',forecastSnapshotDigest:forecast.snapshotDigest,actualDurationMs:500,sourceIdentityDigest:H('S'+i),validityBindingDigest:H('V'+i)},opts).value;receipts.push(E.createForecastActualVarianceReceipt(forecast,a,opts).value);}assert.equal(E.createCalibrationBiasSentinel(receipts,opts).value.state,'OPTIMISTIC');});
test('same throughput model has no drift',()=>{const f=history(),d=E.createModelDriftSentinel(f.model,f.model,{denominatorEpochChanged:false,observationPolicyChanged:false,biasState:'NONE',stale:false,conflict:false},opts).value;assert.equal(d.state,'CURRENT');});
test('denominator transition forces drift',()=>{const f=history(),d=E.createModelDriftSentinel(f.model,f.model,{denominatorEpochChanged:true,observationPolicyChanged:false,biasState:'NONE',stale:false,conflict:false},opts).value;assert.equal(d.state,'DRIFTED');});
test('recalibration epoch requires explicit trigger',()=>{const f=history();assert.equal(E.createRecalibrationEpoch('C',null,f.window.windowDigest,H('p'),[],opts).ok,false);});
test('forecast revision preserves before and after identities',()=>{const r=E.createForecastRevisionReceipt({snapshotDigest:H('b'),intervalDigest:H('bi')},{snapshotDigest:H('a'),intervalDigest:H('ai')},null,['MODEL_DRIFT'],opts).value;assert.notEqual(r.beforeSnapshotDigest,r.afterSnapshotDigest);});
test('revision replay guard detects split brain',()=>{const r1=E.createForecastRevisionReceipt({snapshotDigest:H('b'),intervalDigest:H('bi')},{snapshotDigest:H('a1'),intervalDigest:H('ai1')},null,['X'],opts).value,r2=E.createForecastRevisionReceipt({snapshotDigest:H('b'),intervalDigest:H('bi')},{snapshotDigest:H('a2'),intervalDigest:H('ai2')},null,['Y'],opts).value;assert.equal(E.createRevisionReplayGuard([], [r1,r2],opts).value.splitBrain,true);});
test('3 samples with no calibration remain LOW confidence',()=>{const f=history(3),c=calibration(f.model,0),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'LOW');});
test('5 samples plus 3 calibrated receipts reach MEDIUM',()=>{const f=history(5),c=calibration(f.model,3),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'MEDIUM');});
test('8 samples and 4-of-5 interval coverage reach HIGH',()=>{const f=history(8),c=calibration(f.model,5,true),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'HIGH');});
test('non-available estimation always has UNKNOWN confidence',()=>{const f=history(),c=calibration(f.model,5),s=E.deriveEstimationConfidence('STALE',null,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'UNKNOWN');});
test('snapshot binds model interval calibration and risk',()=>{const f=history(),c=calibration(f.model,5),epoch=E.createRecalibrationEpoch('C',null,f.window.windowDigest,H('cp'),[H('t')],opts).value,binding=E.createEstimationBindingManifest(f.admission,f.index,H('ep'),f.risk.vectorDigest,epoch.epochDigest,opts).value,s=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:f.admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:f.model,interval:f.interval,scenarios:f.scenarios,riskVectorDigest:f.risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:c.receipts,bias:c.bias,drift:c.drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts);assert.equal(s.ok,true);assert.equal(E.verifyEstimationSnapshot(s.value,opts).value,true);});
test('snapshot rejects risk mix-and-match',()=>{const f=history(),c=calibration(f.model,5),epoch=E.createRecalibrationEpoch('C',null,f.window.windowDigest,H('cp'),[H('t')],opts).value,binding=E.createEstimationBindingManifest(f.admission,f.index,H('ep'),f.risk.vectorDigest,epoch.epochDigest,opts).value,s=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:f.admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:f.model,interval:f.interval,scenarios:f.scenarios,riskVectorDigest:H('wrong'),reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:c.receipts,bias:c.bias,drift:c.drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts);assert.equal(s.ok,false);});
test('integrity receipt independently recomputes semantic digest',()=>{const f=history(),c=calibration(f.model,5),epoch=E.createRecalibrationEpoch('C',null,f.window.windowDigest,H('cp'),[H('t')],opts).value,binding=E.createEstimationBindingManifest(f.admission,f.index,H('ep'),f.risk.vectorDigest,epoch.epochDigest,opts).value,s=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:f.admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:f.model,interval:f.interval,scenarios:f.scenarios,riskVectorDigest:f.risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:c.receipts,bias:c.bias,drift:c.drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts).value,r=E.createEstimationIntegrityReceipt(s,opts).value;assert.equal(r.valid,true);assert.equal(r.semanticDigest,r.recomputedSemanticDigest);});
test('M20 handoff preserves availability and confidence',()=>{const f=history(),c=calibration(f.model,5),epoch=E.createRecalibrationEpoch('C',null,f.window.windowDigest,H('cp'),[H('t')],opts).value,binding=E.createEstimationBindingManifest(f.admission,f.index,H('ep'),f.risk.vectorDigest,epoch.epochDigest,opts).value,s=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:f.admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:f.model,interval:f.interval,scenarios:f.scenarios,riskVectorDigest:f.risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:c.receipts,bias:c.bias,drift:c.drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts).value,h=E.createDelegatedEstimationMetricHandoff(s,H('src'),H('valid'),opts).value;assert.equal(h.owner,'M22_ESTIMATION');assert.equal(h.consumer,'M20_RESPONSE');assert.equal(h.confidence,'HIGH');});
test('staleness report catches changed baseline binding',()=>{const f=history(),c=calibration(f.model,5),epoch=E.createRecalibrationEpoch('C',null,f.window.windowDigest,H('cp'),[H('t')],opts).value,binding=E.createEstimationBindingManifest(f.admission,f.index,H('ep'),f.risk.vectorDigest,epoch.epochDigest,opts).value,s=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:f.admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:f.model,interval:f.interval,scenarios:f.scenarios,riskVectorDigest:f.risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:c.receipts,bias:c.bias,drift:c.drift,estimationPolicyDigest:H('ep'),predecessorSnapshotDigest:null},opts).value,r=E.detectEstimationStaleness(s,{baselineAdmissionDigest:H('changed'),bindingManifestDigest:binding.bindingDigest,calibrationEpochDigest:epoch.epochDigest,estimationPolicyDigest:H('ep'),riskVectorDigest:f.risk.vectorDigest,reserveDigest:null},opts).value;assert.equal(r.stale,true);assert.deepEqual(r.staleSubjects,['baseline']);});

function snapshotFixture(n=8,times=[],calCount=5,outside=false){const f=history(n,times),c=calibration(f.model,calCount,outside),epoch=E.createRecalibrationEpoch('C'+n,null,f.window.windowDigest,H('cp'+n),[H('trigger'+n)],opts).value,binding=E.createEstimationBindingManifest(f.admission,f.index,H('ep'+n),f.risk.vectorDigest,epoch.epochDigest,opts).value,snapshot=E.createEstimationSnapshot({projectId:'P',lineageDigest:H('L'),baselineAdmissionDigest:f.admission.admissionDigest,bindingManifestDigest:binding.bindingDigest,asOfEpochMs:1000,availability:'AVAILABLE',throughputModel:f.model,interval:f.interval,scenarios:f.scenarios,riskVectorDigest:f.risk.vectorDigest,reserveDigest:null,calibrationEpochDigest:epoch.epochDigest,calibrationReceipts:c.receipts,bias:c.bias,drift:c.drift,estimationPolicyDigest:H('ep'+n),predecessorSnapshotDigest:null},opts).value;return{...f,...c,epoch,binding,snapshot};}

test('4 samples stay LOW even with three calibration receipts',()=>{const f=history(4),c=calibration(f.model,3),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'LOW');});
test('7 samples cannot reach HIGH even with clean five-receipt calibration',()=>{const f=history(7,[1500,1500,1500,1200,1100,1000,1000]),c=calibration(f.model,5),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'MEDIUM');});
test('dispersion exactly two qualifies for MEDIUM',()=>{const f=history(5,[2000,2000,1500,1000,1000]),c=calibration(f.model,3),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'MEDIUM');});
test('dispersion just above two remains LOW',()=>{const f=history(5,[2001,2001,1500,1000,1000]),c=calibration(f.model,3),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'LOW');});
test('dispersion exactly three-halves can qualify for HIGH',()=>{const f=history(8,[1500,1500,1500,1200,1100,1000,1000,1000]),c=calibration(f.model,5),s=E.deriveEstimationConfidence('AVAILABLE',f.model,c.receipts,c.bias,c.drift,opts).value;assert.equal(s.confidence,'HIGH');});
test('throughput window cancellation fails closed',()=>{const r=E.createThroughputWindow([],H('wp'),{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'ESTIMATION_CANCELLED');});
test('throughput window enforces configured sample budget',()=>{const f=history(3);const samples=[];for(let i=0;i<3;i++){const o=f.index.observations.find(x=>x.observationId==='o'+i);samples.push(E.createTemporalProgressSample(f.admission,f.snaps[i],f.snaps[i+1],o,{owner:'M21_PROGRESS',verifyProjectSnapshot:()=>true},opts).value);}assert.equal(E.createThroughputWindow(samples,H('wp2'),{digest,maxSamples:2}).ok,false);});
test('digest capability returning non-SHA hex fails closed',()=>{const r=E.createEstimationIntent('P',H('L'),H('B'),1,{digest:{algorithm:'sha256',digest:()=> 'not-a-digest'}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_INVALID');});
test('digest capability exception is sanitized and fails closed',()=>{const r=E.createEstimationIntent('P',H('L'),H('B'),1,{digest:{algorithm:'sha256',digest:()=>{throw new Error('secret backend detail')}}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_FAILED');assert.equal(JSON.stringify(r).includes('secret backend detail'),false);});
test('unsafe injected asOf is rejected instead of rounded',()=>{assert.equal(E.createEstimationIntent('P',H('L'),H('B'),Number.MAX_SAFE_INTEGER+1,opts).ok,false);});
test('risk owner spoofing is rejected',()=>{const r=E.createRiskModifier({riskId:'R',owner:'M21_PROGRESS',basisPoints:100,sourceIdentityDigest:H('s'),validityBindingDigest:H('v')},opts);assert.equal(r.ok,false);});
test('tampered calibration receipt cannot influence bias or confidence',()=>{const f=history(5),c=calibration(f.model,3),bad={...c.receipts[0],actualDurationMs:c.receipts[0].actualDurationMs+1};assert.equal(E.createCalibrationBiasSentinel([bad,...c.receipts.slice(1)],opts).ok,false);});
test('M20 handoff verifier rejects confidence upgrade or duration tamper',()=>{const f=snapshotFixture(),h=E.createDelegatedEstimationMetricHandoff(f.snapshot,H('src'),H('valid'),opts).value;assert.equal(E.verifyDelegatedEstimationMetricHandoff(h,opts).value,true);assert.equal(E.verifyDelegatedEstimationMetricHandoff({...h,confidence:'LOW'},opts).value,false);assert.equal(E.verifyDelegatedEstimationMetricHandoff({...h,upperMs:h.upperMs+1},opts).value,false);});
test('M23 handoff verifier rejects owner and revision tamper',()=>{const f=snapshotFixture(),h=E.createStatusEstimationHandoff(f.snapshot,false,opts).value;assert.equal(E.verifyStatusEstimationHandoff(h,opts).value,true);assert.equal(E.verifyStatusEstimationHandoff({...h,owner:'M21_PROGRESS'},opts).value,false);assert.equal(E.verifyStatusEstimationHandoff({...h,revisionObserved:true},opts).value,false);});
test('integrity receipt verifier rejects resealed validity toggle',()=>{const f=snapshotFixture(),r=E.createEstimationIntegrityReceipt(f.snapshot,opts).value;assert.equal(E.verifyEstimationIntegrityReceipt(r,opts).value,true);assert.equal(E.verifyEstimationIntegrityReceipt({...r,valid:false},opts).value,false);});
