import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{
 createCanonicalContinuationCapsule,buildCheckpointFreshnessVector,buildCheckpointPortabilityEnvelope,buildResumeReadinessCertificate,buildContinuationHandoffContract,
}from'../packages/checkpoint-engine/dist/public.js';
import{
 createDenominatorIntegrityManifest,createProgressBaselineCapsule,createEvidenceAcceptanceBinding,createWeightedCreditUnit,createWeightedProgressVector,createHierarchicalProgressGraph,createProgressSnapshot,createStatusProgressHandoff,
}from'../packages/progress-engine/dist/public.js';
import{estimateProject}from'../packages/estimation-engine/dist/public.js';
import{
 M23_MECHANISMS,createStatusIntentCapsule,createStatusAuthorityBoundary,createCompletionOutcome,createStatusCondition,createResolutionDigestGate,createStatusReopenWitness,createStatusTransitionRecord,guardStatusHistory,createProjectStatusIntegrityReceipt,createStatusFreshnessGate,evaluateProjectStatus,
}from'../packages/project-status-engine/dist/public.js';

const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')};
const opts={digest};
const H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const seal=v=>`sha256:${createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex')}`;
const PROJECT='gef-bootstrap',LINEAGE_ID='lineage-1',PROGRESS_LINEAGE=H('progress-lineage');

function policyBinding(){return{checkpointIdentity:'chk-prev',policyFingerprint:H('a'),decisionReceiptDigest:H('b'),exceptionDebtDigest:H('c'),policyIds:['policy-1'],bindingDigest:H('d')};}
function cpBinding(){return{bindingId:'source',domain:'SOURCE',semanticIdentity:H('1'),authorityRef:'auth:source',required:true};}
function cpClaim(status='ACTIVE'){return{claimId:'claim-1',domain:'BUILD',status,maturity:50,dependencyKeys:['source:file-a'],authorityBindingIds:['source'],evidenceRefs:['ev:1']};}
function checkpointFixture({claimStatus='ACTIVE',blockers=[],availableCapabilities=['node24'],nextLegalAction='IMPLEMENT_GBS_M23'}={}){
 const checkpoint=createCanonicalContinuationCapsule({schemaVersion:1,projectId:PROJECT,moduleId:'GBS-M23',stageId:'IMPLEMENT',lineageId:LINEAGE_ID,predecessorCheckpointDigest:null,admittedWorkOrderIds:['GBS-WO-M23-001'],authorityBindings:[cpBinding()],policyBinding:policyBinding(),claims:[cpClaim(claimStatus)],blockers,evidenceRefs:['ev:root'],nextLegalAction,requiredCapabilities:['node24']},opts).value;
 const observedAuthorityIdentities={source:H('1')};
 const freshness=buildCheckpointFreshnessVector(checkpoint,observedAuthorityIdentities,opts).value;
 const portability=buildCheckpointPortabilityEnvelope(checkpoint,availableCapabilities,opts).value;
 const readiness=buildResumeReadinessCertificate(checkpoint,freshness,portability,opts).value;
 const handoff=buildContinuationHandoffContract(checkpoint,readiness,opts).value;
 return{checkpoint,observedAuthorityIdentities,availableCapabilities,readiness,handoff};
}

function progressFixture(state='FULL'){
 const units=[{unitId:'u-a',moduleId:'M23A',areaId:'area-f',phaseId:'construction',maxWeight:5},{unitId:'u-b',moduleId:'M23B',areaId:'area-f',phaseId:'construction',maxWeight:5}];
 const manifest=createDenominatorIntegrityManifest({projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units},opts).value;
 const bs=units.map((u,i)=>createEvidenceAcceptanceBinding({unitId:u.unitId,owner:'M24_EVIDENCE',state:state==='FULL'?'ACCEPTED':state==='ZERO'?'REJECTED':i===0?'ACCEPTED':'REJECTED',sourceIdentityDigest:H(`src-${u.unitId}`),validityBindingDigest:H(`valid-${u.unitId}`)},opts).value);
 const credits=units.map((u,i)=>createWeightedCreditUnit(manifest.units[i],bs[i],opts).value);
 const baseline=createProgressBaselineCapsule(manifest,opts).value;
 const vector=createWeightedProgressVector(manifest,credits,{kind:'PROJECT',refId:null},opts).value;
 const graph=createHierarchicalProgressGraph(manifest,opts).value;
 const snapshot=createProgressSnapshot({baseline,vector,graph,credits,evidenceSetDigest:H(`evidence-${state}`)},manifest,opts).value;
 const handoff=createStatusProgressHandoff(snapshot,false,opts).value;
 const currentBinding={projectId:snapshot.projectId,lineageDigest:snapshot.lineageDigest,manifestDigest:snapshot.manifestDigest,epochId:snapshot.epochId,scopeDigest:snapshot.scopeDigest,dodDigest:snapshot.dodDigest,evidenceSetDigest:snapshot.evidenceSetDigest};
 return{snapshot,handoff,currentBinding};
}

function estimationFixture(deadlineEpochMs=undefined){
 const values=[0,10,30,60,80],asOf=1_000_000;
 const history=values.map((numerator,sequence)=>({snapshotDigest:H(`m22-snap-${sequence}`),semanticDigest:H(`m22-sem-${sequence}`),projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,epochId:'epoch-1',manifestDigest:H('m22-manifest'),sequence,numerator,denominator:100,completeness:'COMPLETE'}));
 const handoffBody={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:history.map(x=>x.snapshotDigest),semanticDigests:history.map(x=>x.semanticDigest)};
 const baselineHandoff={...handoffBody,handoffDigest:seal(handoffBody)};
 const observations=[1000,1000,1500,2000].map((elapsedMs,i)=>({observationId:`obs-${i}`,owner:'EXTERNAL_CANONICAL',projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,epochId:'epoch-1',beforeSnapshotDigest:history[i].snapshotDigest,afterSnapshotDigest:history[i+1].snapshotDigest,elapsedMs,observedAtEpochMs:asOf-10_000+i*1000,sourceIdentityDigest:H(`obs-source-${i}`)}));
 const input={intent:{projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,horizon:'PROJECT_COMPLETION',baselineHandoffDigest:baselineHandoff.handoffDigest,asOfEpochMs:asOf,requestedOutput:'HANDOFFS'},baselineHandoff,progressHistory:history,observations,policy:{maxWindowSamples:64,staleAfterMs:100_000,requireRiskInputs:false,calibrationWindow:20,policyVersion:'m22-v1'},...(deadlineEpochMs===undefined?{}:{deadlineEpochMs})};
 const r=estimateProject(input,opts);assert.equal(r.ok,true,JSON.stringify(r));return{snapshot:r.value.snapshot,binding:r.value.binding,currentObservationIndexDigest:r.value.observationIndex.indexDigest,currentThroughputModelDigest:r.value.model?.modelDigest??null,handoff:r.value.statusHandoff};
}

function resumeFixture(checkpointDigest,nextAction,status='READY'){
 const body={resumeId:'resume-1',status,projectId:PROJECT,lineageId:LINEAGE_ID,checkpointDigest,handoffDigest:H('resume-handoff'),nextAction:status==='READY'?nextAction:null,decisionDigest:H('decision'),readPlanDigest:H('plan'),driftVectorDigest:H('drift'),orphanReportDigest:H('orphan'),quarantineDigest:H('quarantine')};
 const receipt={...body,receiptDigest:seal(body)};
 const blockers=status==='READY'?[]:[`RESUME_${status}`];
 const hbody={status,checkpointDigest,nextLegalAction:status==='READY'?nextAction:null,blockers,receiptDigest:receipt.receiptDigest};
 return{receipt,handback:{...hbody,handbackDigest:seal(hbody)}};
}

function condition(checkpointDigest,className='BLOCKING',state='ACTIVE',extra={}){return createStatusCondition({conditionId:extra.conditionId??'cond-1',owner:extra.owner??'EXTERNAL_CANONICAL',projectId:PROJECT,lineageId:LINEAGE_ID,checkpointDigest,class:className,state,reasonCode:extra.reasonCode??'TEST',sourceIdentityDigest:H(extra.source??'condition-source'),validityBindingDigest:H(extra.validity??'condition-validity'),supersedesConditionDigest:extra.supersedesConditionDigest??null},opts);}
function completion(progress,extra={}){return createCompletionOutcome({outcomeId:extra.outcomeId??'completion-1',owner:extra.owner??'EXTERNAL_CANONICAL',projectId:PROJECT,lineageId:LINEAGE_ID,progressSnapshotDigest:progress.snapshot.snapshotDigest,state:extra.state??'ACCEPTED',sourceIdentityDigest:H(extra.source??'completion-source'),validityBindingDigest:H(extra.validity??'completion-validity')},opts);}

function makeInput({cp=checkpointFixture(),progress=progressFixture('PARTIAL'),estimation=null,resume=null,completionOutcome=null,conditions=[],previousConditionIndex=null,schedule=false,statusId='status-1',continuationSource=true,progressSource=true}={}){
 const intent=createStatusIntentCapsule({statusId,projectId:PROJECT,lineageId:LINEAGE_ID,requestedDimensions:schedule?['LIFECYCLE','READINESS','SCHEDULE']:['LIFECYCLE','READINESS'],asOfEpochMs:schedule?(estimation?.snapshot.asOfEpochMs??1_000_000):null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:progress.handoff.handoffDigest,estimationHandoffDigest:estimation?.handoff.handoffDigest??null,resumeHandbackDigest:resume?.handback.handbackDigest??null,completionOutcomeDigest:completionOutcome?.outcomeDigest??null,conditionDigests:conditions.map(c=>c.conditionDigest),previousConditionIndexDigest:previousConditionIndex?.indexDigest??null}},opts);assert.equal(intent.ok,true,JSON.stringify(intent));
 return{intent:intent.value,continuationSource:continuationSource?cp:null,resumeSource:resume,progressSource:progressSource?progress:null,estimationSource:estimation,completionOutcome,currentConditions:conditions,previousConditionIndex};
}
function evaluate(input,predecessor=null,o=opts){const r=evaluateProjectStatus(input,predecessor,o);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}

test('all 30 frozen M23 mechanisms are represented',()=>{assert.equal(M23_MECHANISMS.length,30);assert.equal(new Set(M23_MECHANISMS).size,30);});
test('status intent is deterministic under dimension and condition order',()=>{const cp=checkpointFixture(),p=progressFixture(),a=createStatusIntentCapsule({statusId:'s',projectId:PROJECT,lineageId:LINEAGE_ID,requestedDimensions:['READINESS','LIFECYCLE'],asOfEpochMs:null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:p.handoff.handoffDigest,estimationHandoffDigest:null,resumeHandbackDigest:null,completionOutcomeDigest:null,conditionDigests:[H('b'),H('a')],previousConditionIndexDigest:null}},opts),b=createStatusIntentCapsule({statusId:'s',projectId:PROJECT,lineageId:LINEAGE_ID,requestedDimensions:['LIFECYCLE','READINESS'],asOfEpochMs:null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:p.handoff.handoffDigest,estimationHandoffDigest:null,resumeHandbackDigest:null,completionOutcomeDigest:null,conditionDigests:[H('a'),H('b')],previousConditionIndexDigest:null}},opts);assert.equal(a.value.intentDigest,b.value.intentDigest);});
test('schedule intent requires explicit as-of value',()=>{const cp=checkpointFixture(),p=progressFixture();const r=createStatusIntentCapsule({statusId:'s',projectId:PROJECT,lineageId:LINEAGE_ID,requestedDimensions:['SCHEDULE'],asOfEpochMs:null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:p.handoff.handoffDigest,estimationHandoffDigest:null,resumeHandbackDigest:null,completionOutcomeDigest:null,conditionDigests:[],previousConditionIndexDigest:null}},opts);assert.equal(r.ok,false);});
test('authority boundary is project-status-only',()=>{const input=makeInput();const a=createStatusAuthorityBoundary(input.intent,opts).value;assert.equal(a.authority,'PROJECT_STATUS_ONLY');assert.equal(a.mayCalculateProgress,false);assert.equal(a.mayEstimateEta,false);assert.equal(a.mayPromoteCheckpoint,false);});
test('100 percent without acceptance is awaiting acceptance',()=>{const p=progressFixture('FULL');const r=evaluate(makeInput({progress:p}));assert.equal(r.snapshot.lifecycleStatus,'AWAITING_ACCEPTANCE');assert.equal(r.snapshot.continuationReadiness,'WAITING');});
test('accepted full progress becomes COMPLETE and readiness is NOT_APPLICABLE',()=>{const p=progressFixture('FULL'),c=completion(p).value;const r=evaluate(makeInput({progress:p,completionOutcome:c}));assert.equal(r.snapshot.lifecycleStatus,'COMPLETE');assert.equal(r.snapshot.continuationReadiness,'NOT_APPLICABLE');});
test('future M27 completion owner is unavailable before M27 exists',()=>{const p=progressFixture('FULL');assert.equal(completion(p,{owner:'M27_ASSURANCE'}).ok,false);});
test('native-owner impersonation is rejected for generic completion input',()=>{const p=progressFixture('FULL');const r=createCompletionOutcome({outcomeId:'x',owner:'M21_PROGRESS',projectId:PROJECT,lineageId:LINEAGE_ID,progressSnapshotDigest:p.snapshot.snapshotDigest,state:'ACCEPTED',sourceIdentityDigest:H('x'),validityBindingDigest:H('y')},opts);assert.equal(r.ok,false);});
test('zero progress without ACTIVE or DONE work is NOT_STARTED',()=>{const cp=checkpointFixture({claimStatus:'PLANNED'}),p=progressFixture('ZERO');const r=evaluate(makeInput({cp,progress:p}));assert.equal(r.snapshot.lifecycleStatus,'NOT_STARTED');});
test('zero progress with ACTIVE work is IN_PROGRESS',()=>{const p=progressFixture('ZERO');assert.equal(evaluate(makeInput({progress:p})).snapshot.lifecycleStatus,'IN_PROGRESS');});
test('active blocking condition dominates lifecycle',()=>{const cp=checkpointFixture(),p=progressFixture(),c=condition(cp.checkpoint.checkpointDigest).value;const r=evaluate(makeInput({cp,progress:p,conditions:[c]}));assert.equal(r.snapshot.lifecycleStatus,'BLOCKED');assert.equal(r.snapshot.continuationReadiness,'BLOCKED');});
test('omitted blocker remains active until exact resolution',()=>{const cp=checkpointFixture(),p=progressFixture(),c=condition(cp.checkpoint.checkpointDigest).value;const first=evaluate(makeInput({cp,progress:p,conditions:[c],statusId:'first'}));const second=evaluate(makeInput({cp,progress:p,conditions:[],previousConditionIndex:first.decision.conditionIndex,statusId:'second'}));assert.equal(second.snapshot.lifecycleStatus,'BLOCKED');assert.deepEqual(second.decision.conditionIndex.carriedForwardConditionIds,['cond-1']);});
test('exact supersession resolves prior blocker',()=>{const cp=checkpointFixture(),p=progressFixture(),active=condition(cp.checkpoint.checkpointDigest).value;const first=evaluate(makeInput({cp,progress:p,conditions:[active],statusId:'first'}));const resolved=condition(cp.checkpoint.checkpointDigest,'BLOCKING','RESOLVED',{supersedesConditionDigest:active.conditionDigest,source:'resolved-source',validity:'resolved-valid'}).value;const second=evaluate(makeInput({cp,progress:p,conditions:[resolved],previousConditionIndex:first.decision.conditionIndex,statusId:'second'}));assert.equal(second.snapshot.lifecycleStatus,'IN_PROGRESS');const gate=createResolutionDigestGate(first.decision.conditionIndex,second.decision.conditionIndex,'cond-1',opts).value;assert.equal(gate.resolved,true);assert.equal(gate.priorConditionDigest,active.conditionDigest);assert.equal(gate.resolutionConditionDigest,resolved.conditionDigest);});
test('bogus resolution becomes explicit conflict',()=>{const cp=checkpointFixture(),p=progressFixture(),active=condition(cp.checkpoint.checkpointDigest).value;const first=evaluate(makeInput({cp,progress:p,conditions:[active],statusId:'first'}));const bad=condition(cp.checkpoint.checkpointDigest,'BLOCKING','RESOLVED',{supersedesConditionDigest:H('wrong'),source:'bad-source',validity:'bad-valid'}).value;const second=evaluate(makeInput({cp,progress:p,conditions:[bad],previousConditionIndex:first.decision.conditionIndex,statusId:'second'}));assert.equal(second.snapshot.lifecycleStatus,'CONFLICT');});
test('recovery condition outranks blocker',()=>{const cp=checkpointFixture(),p=progressFixture(),b=condition(cp.checkpoint.checkpointDigest,'BLOCKING','ACTIVE',{conditionId:'block'}).value,r=condition(cp.checkpoint.checkpointDigest,'RECOVERY','ACTIVE',{conditionId:'recover',source:'r',validity:'r'}).value;assert.equal(evaluate(makeInput({cp,progress:p,conditions:[b,r]})).snapshot.lifecycleStatus,'RECOVERY_REQUIRED');});
test('explicit conflict condition outranks recovery',()=>{const cp=checkpointFixture(),p=progressFixture(),r=condition(cp.checkpoint.checkpointDigest,'RECOVERY','ACTIVE',{conditionId:'recover'}).value,c=condition(cp.checkpoint.checkpointDigest,'CONFLICT','ACTIVE',{conditionId:'conflict',source:'c',validity:'c'}).value;assert.equal(evaluate(makeInput({cp,progress:p,conditions:[r,c]})).snapshot.lifecycleStatus,'CONFLICT');});
test('warning condition does not block lifecycle',()=>{const cp=checkpointFixture(),p=progressFixture(),w=condition(cp.checkpoint.checkpointDigest,'WARNING').value;assert.equal(evaluate(makeInput({cp,progress:p,conditions:[w]})).snapshot.lifecycleStatus,'IN_PROGRESS');});
test('missing mandatory continuation source yields INDETERMINATE rather than fabricated status',()=>{const r=evaluate(makeInput({continuationSource:false}));assert.equal(r.snapshot.lifecycleStatus,'INDETERMINATE');assert.equal(r.snapshot.continuationReadiness,'UNKNOWN');});
test('missing mandatory progress source yields INDETERMINATE',()=>{const r=evaluate(makeInput({progressSource:false}));assert.equal(r.snapshot.lifecycleStatus,'INDETERMINATE');});
test('stale progress binding fails closed at admission',()=>{const p=progressFixture();p.currentBinding={...p.currentBinding,scopeDigest:H('other-scope')};const r=evaluateProjectStatus(makeInput({progress:p}),null,opts);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'PHG23_STALE');});
test('schedule not requested is NOT_APPLICABLE even when estimation exists',()=>{const e=estimationFixture(1_003_000),r=evaluate(makeInput({estimation:e,schedule:false}));assert.equal(r.snapshot.scheduleHealth,'NOT_APPLICABLE');});
test('requested schedule with missing estimation is UNKNOWN, not BLOCKED',()=>{const r=evaluate(makeInput({schedule:true}));assert.equal(r.snapshot.scheduleHealth,'UNKNOWN');assert.notEqual(r.snapshot.lifecycleStatus,'BLOCKED');});
test('deadline after conservative bound is ON_TRACK',()=>{const e=estimationFixture(1_003_000),r=evaluate(makeInput({estimation:e,schedule:true}));assert.equal(r.snapshot.scheduleHealth,'ON_TRACK');});
test('deadline before optimistic bound is LATE',()=>{const e=estimationFixture(1_000_500),r=evaluate(makeInput({estimation:e,schedule:true}));assert.equal(r.snapshot.scheduleHealth,'LATE');assert.equal(r.snapshot.lifecycleStatus,'IN_PROGRESS');});
test('deadline inside forecast interval is AT_RISK',()=>{const e=estimationFixture(1_001_500),r=evaluate(makeInput({estimation:e,schedule:true}));assert.equal(r.snapshot.scheduleHealth,'AT_RISK');});
test('resume drift requires replan without rewriting M17 next action',()=>{const cp=checkpointFixture(),resume=resumeFixture(cp.checkpoint.checkpointDigest,cp.checkpoint.nextLegalAction,'DRIFT_REQUIRES_REPLAN'),r=evaluate(makeInput({cp,resume}));assert.equal(r.snapshot.continuationReadiness,'REPLAN_REQUIRED');assert.equal(r.snapshot.nextLegalAction,null);});
test('READY resume action disagreement is explicit conflict',()=>{const cp=checkpointFixture(),resume=resumeFixture(cp.checkpoint.checkpointDigest,'OTHER_ACTION','READY'),r=evaluate(makeInput({cp,resume}));assert.equal(r.snapshot.continuationReadiness,'CONFLICT');});
test('resume from another checkpoint cannot constrain current readiness silently',()=>{const cp=checkpointFixture(),resume=resumeFixture(H('other-checkpoint'),cp.checkpoint.nextLegalAction,'READY'),r=evaluate(makeInput({cp,resume}));assert.equal(r.snapshot.continuationReadiness,'CONFLICT');});
test('capability gap blocks readiness without manufacturing lifecycle blocker',()=>{const cp=checkpointFixture({availableCapabilities:[]}),r=evaluate(makeInput({cp}));assert.equal(r.snapshot.continuationReadiness,'BLOCKED');assert.equal(r.snapshot.lifecycleStatus,'IN_PROGRESS');});
test('COMPLETE cannot reopen silently',()=>{const pFull=progressFixture('FULL'),c=completion(pFull).value,first=evaluate(makeInput({progress:pFull,completionOutcome:c,statusId:'complete'}));const pPartial=progressFixture('PARTIAL'),second=evaluate(makeInput({progress:pPartial,statusId:'reopen'}),first.snapshot.snapshotDigest);const t=createStatusTransitionRecord(first.snapshot,second.snapshot,null,opts);assert.equal(t.ok,false);assert.equal(t.diagnostics[0].code,'STR23_REOPEN_WITNESS_REQUIRED');});
test('explicit reopen witness authorizes COMPLETE regression',()=>{const pFull=progressFixture('FULL'),c=completion(pFull).value,first=evaluate(makeInput({progress:pFull,completionOutcome:c,statusId:'complete'}));const pPartial=progressFixture('PARTIAL'),second=evaluate(makeInput({progress:pPartial,statusId:'reopen'}),first.snapshot.snapshotDigest);const w=createStatusReopenWitness({witnessId:'reopen-1',owner:'EXTERNAL_CANONICAL',priorCompleteSnapshotDigest:first.snapshot.snapshotDigest,authorizationFactDigest:H('reopen-auth'),reasonCode:'EVIDENCE_INVALIDATED'},opts).value;const t=createStatusTransitionRecord(first.snapshot,second.snapshot,w,opts);assert.equal(t.ok,true);});
test('future M27 reopen authority is unavailable before M27 exists',()=>{assert.equal(createStatusReopenWitness({witnessId:'r',owner:'M27_ASSURANCE',priorCompleteSnapshotDigest:H('p'),authorizationFactDigest:H('a'),reasonCode:'X'},opts).ok,false);});
test('history replay is idempotent and duplicate visible',()=>{const a=evaluate(makeInput({statusId:'a'}));const b=evaluate(makeInput({statusId:'b'}),a.snapshot.snapshotDigest);const t=createStatusTransitionRecord(a.snapshot,b.snapshot,null,opts).value;const g=guardStatusHistory([t,t],opts).value;assert.equal(g.state,'CLEAR');assert.equal(g.acceptedTransitionDigests.length,1);assert.equal(g.duplicateTransitionDigests.length,1);});
test('divergent successors sharing predecessor expose split brain',()=>{const base=evaluate(makeInput({statusId:'base'}));const one=evaluate(makeInput({progress:progressFixture('PARTIAL'),statusId:'one'}),base.snapshot.snapshotDigest);const two=evaluate(makeInput({progress:progressFixture('ZERO'),statusId:'two'}),base.snapshot.snapshotDigest);const t1=createStatusTransitionRecord(base.snapshot,one.snapshot,null,opts).value,t2=createStatusTransitionRecord(base.snapshot,two.snapshot,null,opts).value;const g=guardStatusHistory([t1,t2],opts).value;assert.equal(g.state,'CONFLICT');assert.deepEqual(g.splitBrainPredecessorDigests,[base.snapshot.snapshotDigest]);});
test('bounded history reports truncation explicitly',()=>{const a=evaluate(makeInput({statusId:'a'})),b=evaluate(makeInput({statusId:'b'}),a.snapshot.snapshotDigest),c=evaluate(makeInput({statusId:'c'}),b.snapshot.snapshotDigest);const t1=createStatusTransitionRecord(a.snapshot,b.snapshot,null,opts).value,t2=createStatusTransitionRecord(b.snapshot,c.snapshot,null,opts).value;const g=guardStatusHistory([t1,t2],{digest,maxHistory:1}).value;assert.equal(g.state,'TRUNCATED');assert.equal(g.historyTruncated,true);assert.equal(g.processedTransitionCount,1);assert.equal(g.totalTransitionCount,2);});
test('integrity receipt independently detects snapshot tampering',()=>{const input=makeInput(),r=evaluate(input),tampered={...r.snapshot,lifecycleStatus:'BLOCKED'};const receipt=createProjectStatusIntegrityReceipt(tampered,input,opts).value;assert.equal(receipt.valid,false);});
test('freshness gate rejects stale source identities',()=>{const r=evaluate(makeInput());const current={checkpointDigest:r.snapshot.checkpointDigest,progressSnapshotDigest:r.snapshot.progressSnapshotDigest,estimationSnapshotDigest:r.snapshot.estimationSnapshotDigest,completionOutcomeDigest:r.snapshot.completionOutcomeDigest,conditionIndexDigest:H('changed-conditions')};const gate=createStatusFreshnessGate(r.snapshot,current,opts).value;assert.equal(gate.reusable,false);assert.deepEqual(gate.staleSubjects,['conditions']);});
test('ambient system clock is never consulted',()=>{const original=Date.now;Date.now=()=>{throw new Error('clock forbidden');};try{const r=evaluateProjectStatus(makeInput(),null,opts);assert.equal(r.ok,true);}finally{Date.now=original;}});
test('cancellation fails closed',()=>{const r=evaluateProjectStatus(makeInput(),null,{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_CANCELLED');});
test('invalid digest provider fails closed',()=>{const r=evaluateProjectStatus(makeInput(),null,{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_OUTPUT_INVALID');});
test('condition owner spoofing is rejected',()=>{const cp=checkpointFixture();const r=createStatusCondition({conditionId:'x',owner:'M21_PROGRESS',projectId:PROJECT,lineageId:LINEAGE_ID,checkpointDigest:cp.checkpoint.checkpointDigest,class:'BLOCKING',state:'ACTIVE',reasonCode:'X',sourceIdentityDigest:H('x'),validityBindingDigest:H('y'),supersedesConditionDigest:null},opts);assert.equal(r.ok,false);});
