import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createCanonicalContinuationCapsule,buildCheckpointFreshnessVector,buildCheckpointPortabilityEnvelope,buildResumeReadinessCertificate,buildContinuationHandoffContract}from'../packages/checkpoint-engine/dist/public.js';
import{createDenominatorIntegrityManifest,createProgressBaselineCapsule,createEvidenceAcceptanceBinding,createWeightedCreditUnit,createWeightedProgressVector,createHierarchicalProgressGraph,createProgressSnapshot,createStatusProgressHandoff}from'../packages/progress-engine/dist/public.js';
import{estimateProject}from'../packages/estimation-engine/dist/public.js';
import{M23_MECHANISMS,createStatusIntentCapsule,createStatusAuthorityBoundary,createCompletionOutcome,createStatusCondition,createResolutionDigestGate,createStatusReopenWitness,createStatusTransitionRecord,guardStatusHistory,createProjectStatusIntegrityReceipt,createDelegatedProjectStatusHandoff,createStatusFreshnessGate,evaluateProjectStatus}from'../packages/project-status-engine/dist/public.js';

const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest};
const H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const seal=v=>`sha256:${createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex')}`;
const PROJECT='gef-bootstrap',LINEAGE_ID='lineage-1',PROGRESS_LINEAGE=H('progress-lineage');
function policyBinding(){return{checkpointIdentity:'chk-prev',policyFingerprint:H('a'),decisionReceiptDigest:H('b'),exceptionDebtDigest:H('c'),policyIds:['policy-1'],bindingDigest:H('d')};}
function cpBinding(){return{bindingId:'source',domain:'SOURCE',semanticIdentity:H('1'),authorityRef:'auth:source',required:true};}
function cpClaim(status='ACTIVE'){return{claimId:'claim-1',domain:'BUILD',status,maturity:50,dependencyKeys:['source:file-a'],authorityBindingIds:['source'],evidenceRefs:['ev:1']};}
function checkpointFixture({claimStatus='ACTIVE',blockers=[],availableCapabilities=['node24'],nextLegalAction='IMPLEMENT_GBS_M23'}={}){const checkpoint=createCanonicalContinuationCapsule({schemaVersion:1,projectId:PROJECT,moduleId:'GBS-M23',stageId:'IMPLEMENT',lineageId:LINEAGE_ID,predecessorCheckpointDigest:null,admittedWorkOrderIds:['GBS-WO-M23-001'],authorityBindings:[cpBinding()],policyBinding:policyBinding(),claims:[cpClaim(claimStatus)],blockers,evidenceRefs:['ev:root'],nextLegalAction,requiredCapabilities:['node24']},opts).value,observedAuthorityIdentities={source:H('1')},freshness=buildCheckpointFreshnessVector(checkpoint,observedAuthorityIdentities,opts).value,portability=buildCheckpointPortabilityEnvelope(checkpoint,availableCapabilities,opts).value,readiness=buildResumeReadinessCertificate(checkpoint,freshness,portability,opts).value,handoff=buildContinuationHandoffContract(checkpoint,readiness,opts).value;return{checkpoint,observedAuthorityIdentities,availableCapabilities,readiness,handoff};}
function progressFixture(state='PARTIAL'){const units=[{unitId:'u-a',moduleId:'M23A',areaId:'area-f',phaseId:'construction',maxWeight:5},{unitId:'u-b',moduleId:'M23B',areaId:'area-f',phaseId:'construction',maxWeight:5}],manifest=createDenominatorIntegrityManifest({projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,epochId:'epoch-1',scopeDigest:H('scope'),dodDigest:H('dod'),policyDigest:H('policy'),units},opts).value,bs=units.map((u,i)=>createEvidenceAcceptanceBinding({unitId:u.unitId,owner:'M24_EVIDENCE',state:state==='FULL'?'ACCEPTED':state==='ZERO'?'REJECTED':i===0?'ACCEPTED':'REJECTED',sourceIdentityDigest:H(`src-${u.unitId}`),validityBindingDigest:H(`valid-${u.unitId}`)},opts).value),credits=units.map((u,i)=>createWeightedCreditUnit(manifest.units[i],bs[i],opts).value),baseline=createProgressBaselineCapsule(manifest,opts).value,vector=createWeightedProgressVector(manifest,credits,{kind:'PROJECT',refId:null},opts).value,graph=createHierarchicalProgressGraph(manifest,opts).value,snapshot=createProgressSnapshot({baseline,vector,graph,credits,evidenceSetDigest:H(`evidence-${state}`)},manifest,opts).value,handoff=createStatusProgressHandoff(snapshot,false,opts).value,currentBinding={projectId:snapshot.projectId,lineageDigest:snapshot.lineageDigest,manifestDigest:snapshot.manifestDigest,epochId:snapshot.epochId,scopeDigest:snapshot.scopeDigest,dodDigest:snapshot.dodDigest,evidenceSetDigest:snapshot.evidenceSetDigest};return{snapshot,handoff,currentBinding};}
function estimationFixture(deadlineEpochMs=undefined){const values=[0,10,30,60,80],asOf=1_000_000,history=values.map((numerator,sequence)=>({snapshotDigest:H(`m22-snap-${sequence}`),semanticDigest:H(`m22-sem-${sequence}`),projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,epochId:'epoch-1',manifestDigest:H('m22-manifest'),sequence,numerator,denominator:100,completeness:'COMPLETE'})),handoffBody={owner:'M21_PROGRESS',consumer:'M22_ESTIMATION',snapshotDigests:history.map(x=>x.snapshotDigest),semanticDigests:history.map(x=>x.semanticDigest)},baselineHandoff={...handoffBody,handoffDigest:seal(handoffBody)},observations=[1000,1000,1500,2000].map((elapsedMs,i)=>({observationId:`obs-${i}`,owner:'EXTERNAL_CANONICAL',projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,epochId:'epoch-1',beforeSnapshotDigest:history[i].snapshotDigest,afterSnapshotDigest:history[i+1].snapshotDigest,elapsedMs,observedAtEpochMs:asOf-10_000+i*1000,sourceIdentityDigest:H(`obs-source-${i}`)})),input={intent:{projectId:PROJECT,lineageDigest:PROGRESS_LINEAGE,horizon:'PROJECT_COMPLETION',baselineHandoffDigest:baselineHandoff.handoffDigest,asOfEpochMs:asOf,requestedOutput:'HANDOFFS'},baselineHandoff,progressHistory:history,observations,policy:{maxWindowSamples:64,staleAfterMs:100_000,requireRiskInputs:false,calibrationWindow:20,policyVersion:'m22-v1'},...(deadlineEpochMs===undefined?{}:{deadlineEpochMs})},r=estimateProject(input,opts);assert.equal(r.ok,true,JSON.stringify(r));return{snapshot:r.value.snapshot,binding:r.value.binding,currentObservationIndexDigest:r.value.observationIndex.indexDigest,currentThroughputModelDigest:r.value.model?.modelDigest??null,handoff:r.value.statusHandoff};}
function resumeFixture(checkpointDigest,nextAction,status='READY'){const body={resumeId:'resume-1',status,projectId:PROJECT,lineageId:LINEAGE_ID,checkpointDigest,handoffDigest:H('resume-handoff'),nextAction:status==='READY'?nextAction:null,decisionDigest:H('decision'),readPlanDigest:H('plan'),driftVectorDigest:H('drift'),orphanReportDigest:H('orphan'),quarantineDigest:H('quarantine')},receipt={...body,receiptDigest:seal(body)},blockers=status==='READY'?[]:[`RESUME_${status}`],hbody={status,checkpointDigest,nextLegalAction:status==='READY'?nextAction:null,blockers,receiptDigest:receipt.receiptDigest};return{receipt,handback:{...hbody,handbackDigest:seal(hbody)}};}
function condition(checkpointDigest,className='BLOCKING',state='ACTIVE',extra={}){return createStatusCondition({conditionId:extra.conditionId??'cond-1',owner:extra.owner??'EXTERNAL_CANONICAL',projectId:PROJECT,lineageId:LINEAGE_ID,checkpointDigest,class:className,state,reasonCode:extra.reasonCode??'TEST',sourceIdentityDigest:H(extra.source??'condition-source'),validityBindingDigest:H(extra.validity??'condition-validity'),supersedesConditionDigest:extra.supersedesConditionDigest??null},opts);}
function completion(progress,extra={}){return createCompletionOutcome({outcomeId:extra.outcomeId??'completion-1',owner:extra.owner??'EXTERNAL_CANONICAL',projectId:PROJECT,lineageId:LINEAGE_ID,progressSnapshotDigest:progress.snapshot.snapshotDigest,state:extra.state??'ACCEPTED',sourceIdentityDigest:H(extra.source??'completion-source'),validityBindingDigest:H(extra.validity??'completion-validity')},opts);}
function makeInput({cp=checkpointFixture(),progress=progressFixture(),estimation=null,resume=null,completionOutcome=null,conditions=[],previousConditionIndex=null,schedule=false,statusId='status-1',continuationSource=true,progressSource=true}={}){const intent=createStatusIntentCapsule({statusId,projectId:PROJECT,lineageId:LINEAGE_ID,requestedDimensions:schedule?['LIFECYCLE','READINESS','SCHEDULE']:['LIFECYCLE','READINESS'],asOfEpochMs:schedule?(estimation?.snapshot.asOfEpochMs??1_000_000):null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:progress.handoff.handoffDigest,estimationHandoffDigest:estimation?.handoff.handoffDigest??null,resumeHandbackDigest:resume?.handback.handbackDigest??null,completionOutcomeDigest:completionOutcome?.outcomeDigest??null,conditionDigests:conditions.map(c=>c.conditionDigest),previousConditionIndexDigest:previousConditionIndex?.indexDigest??null}},opts);assert.equal(intent.ok,true,JSON.stringify(intent));return{intent:intent.value,continuationSource:continuationSource?cp:null,resumeSource:resume,progressSource:progressSource?progress:null,estimationSource:estimation,completionOutcome,currentConditions:conditions,previousConditionIndex};}
function evaluate(input,predecessor=null,o=opts){const r=evaluateProjectStatus(input,predecessor,o);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
function freshnessOf(s){return{checkpointDigest:s.checkpointDigest,checkpointReadinessCertificateDigest:s.checkpointReadinessCertificateDigest,continuationHandoffDigest:s.continuationHandoffDigest,resumeHandbackDigest:s.resumeHandbackDigest,progressHandoffDigest:s.progressHandoffDigest,estimationHandoffDigest:s.estimationHandoffDigest,completionOutcomeDigest:s.completionOutcomeDigest,conditionIndexDigest:s.conditionIndexDigest};}

test('all 30 frozen M23 mechanisms are represented',()=>{assert.equal(M23_MECHANISMS.length,30);assert.equal(new Set(M23_MECHANISMS).size,30);});
test('status intent is deterministic under dimension and condition order',()=>{const cp=checkpointFixture(),p=progressFixture(),base={statusId:'s',projectId:PROJECT,lineageId:LINEAGE_ID,asOfEpochMs:null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:p.handoff.handoffDigest,estimationHandoffDigest:null,resumeHandbackDigest:null,completionOutcomeDigest:null,conditionDigests:[H('b'),H('a')],previousConditionIndexDigest:null}},a=createStatusIntentCapsule({...base,requestedDimensions:['READINESS','LIFECYCLE']},opts),b=createStatusIntentCapsule({...base,requestedDimensions:['LIFECYCLE','READINESS'],expected:{...base.expected,conditionDigests:[H('a'),H('b')]}},opts);assert.equal(a.value.intentDigest,b.value.intentDigest);});
test('schedule intent requires explicit as-of value',()=>{const cp=checkpointFixture(),p=progressFixture(),r=createStatusIntentCapsule({statusId:'s',projectId:PROJECT,lineageId:LINEAGE_ID,requestedDimensions:['SCHEDULE'],asOfEpochMs:null,expected:{checkpointDigest:cp.checkpoint.checkpointDigest,progressHandoffDigest:p.handoff.handoffDigest,estimationHandoffDigest:null,resumeHandbackDigest:null,completionOutcomeDigest:null,conditionDigests:[],previousConditionIndexDigest:null}},opts);assert.equal(r.ok,false);});
test('authority boundary is project-status-only',()=>{const a=createStatusAuthorityBoundary(makeInput().intent,opts).value;assert.equal(a.authority,'PROJECT_STATUS_ONLY');assert.equal(a.mayCalculateProgress,false);assert.equal(a.mayEstimateEta,false);assert.equal(a.mayPromoteCheckpoint,false);});
test('100 percent without acceptance is awaiting acceptance',()=>{const p=progressFixture('FULL'),r=evaluate(makeInput({progress:p}));assert.equal(r.snapshot.lifecycleStatus,'AWAITING_ACCEPTANCE');assert.equal(r.snapshot.continuationReadiness,'WAITING');});
test('accepted full progress becomes COMPLETE and readiness NOT_APPLICABLE',()=>{const p=progressFixture('FULL'),c=completion(p).value,r=evaluate(makeInput({progress:p,completionOutcome:c}));assert.equal(r.snapshot.lifecycleStatus,'COMPLETE');assert.equal(r.snapshot.continuationReadiness,'NOT_APPLICABLE');assert.equal(r.snapshot.completionOutcomeState,'ACCEPTED');});
test('future M27 completion owner unavailable before M27',()=>{const p=progressFixture('FULL');assert.equal(completion(p,{owner:'M27_ASSURANCE'}).ok,false);});
test('native-owner impersonation rejected for generic completion',()=>{const p=progressFixture('FULL'),r=createCompletionOutcome({outcomeId:'x',owner:'M21_PROGRESS',projectId:PROJECT,lineageId:LINEAGE_ID,progressSnapshotDigest:p.snapshot.snapshotDigest,state:'ACCEPTED',sourceIdentityDigest:H('x'),validityBindingDigest:H('y')},opts);assert.equal(r.ok,false);});
test('zero progress without active/done is NOT_STARTED',()=>{const cp=checkpointFixture({claimStatus:'PLANNED'}),p=progressFixture('ZERO');assert.equal(evaluate(makeInput({cp,progress:p})).snapshot.lifecycleStatus,'NOT_STARTED');});
test('zero progress with ACTIVE work is IN_PROGRESS',()=>{assert.equal(evaluate(makeInput({progress:progressFixture('ZERO')})).snapshot.lifecycleStatus,'IN_PROGRESS');});
test('active blocking condition dominates lifecycle',()=>{const cp=checkpointFixture(),c=condition(cp.checkpoint.checkpointDigest).value,r=evaluate(makeInput({cp,conditions:[c]}));assert.equal(r.snapshot.lifecycleStatus,'BLOCKED');assert.equal(r.snapshot.continuationReadiness,'BLOCKED');});
test('omitted blocker remains active until exact resolution',()=>{const cp=checkpointFixture(),c=condition(cp.checkpoint.checkpointDigest).value,first=evaluate(makeInput({cp,conditions:[c],statusId:'first'})),second=evaluate(makeInput({cp,conditions:[],previousConditionIndex:first.decision.conditionIndex,statusId:'second'}));assert.equal(second.snapshot.lifecycleStatus,'BLOCKED');assert.deepEqual(second.decision.conditionIndex.carriedForwardConditionIds,['cond-1']);});
test('exact supersession resolves prior blocker',()=>{const cp=checkpointFixture(),active=condition(cp.checkpoint.checkpointDigest).value,first=evaluate(makeInput({cp,conditions:[active],statusId:'first'})),resolved=condition(cp.checkpoint.checkpointDigest,'BLOCKING','RESOLVED',{supersedesConditionDigest:active.conditionDigest,source:'resolved-source',validity:'resolved-valid'}).value,second=evaluate(makeInput({cp,conditions:[resolved],previousConditionIndex:first.decision.conditionIndex,statusId:'second'})),gate=createResolutionDigestGate(first.decision.conditionIndex,second.decision.conditionIndex,'cond-1',opts).value;assert.equal(second.snapshot.lifecycleStatus,'IN_PROGRESS');assert.equal(gate.resolved,true);assert.equal(gate.priorConditionDigest,active.conditionDigest);assert.equal(gate.resolutionConditionDigest,resolved.conditionDigest);});
test('bogus resolution becomes explicit conflict',()=>{const cp=checkpointFixture(),active=condition(cp.checkpoint.checkpointDigest).value,first=evaluate(makeInput({cp,conditions:[active],statusId:'first'})),bad=condition(cp.checkpoint.checkpointDigest,'BLOCKING','RESOLVED',{supersedesConditionDigest:H('wrong'),source:'bad-source',validity:'bad-valid'}).value,second=evaluate(makeInput({cp,conditions:[bad],previousConditionIndex:first.decision.conditionIndex,statusId:'second'}));assert.equal(second.snapshot.lifecycleStatus,'CONFLICT');});
test('recovery outranks blocker',()=>{const cp=checkpointFixture(),b=condition(cp.checkpoint.checkpointDigest,'BLOCKING','ACTIVE',{conditionId:'block'}).value,r=condition(cp.checkpoint.checkpointDigest,'RECOVERY','ACTIVE',{conditionId:'recover',source:'r',validity:'r'}).value;assert.equal(evaluate(makeInput({cp,conditions:[b,r]})).snapshot.lifecycleStatus,'RECOVERY_REQUIRED');});
test('conflict outranks recovery',()=>{const cp=checkpointFixture(),r=condition(cp.checkpoint.checkpointDigest,'RECOVERY','ACTIVE',{conditionId:'recover'}).value,c=condition(cp.checkpoint.checkpointDigest,'CONFLICT','ACTIVE',{conditionId:'conflict',source:'c',validity:'c'}).value;assert.equal(evaluate(makeInput({cp,conditions:[r,c]})).snapshot.lifecycleStatus,'CONFLICT');});
test('warning does not block lifecycle and is retained in reason trace',()=>{const cp=checkpointFixture(),w=condition(cp.checkpoint.checkpointDigest,'WARNING').value,r=evaluate(makeInput({cp,conditions:[w]}));assert.equal(r.snapshot.lifecycleStatus,'IN_PROGRESS');assert.equal(r.snapshot.reasonCodeTrace.some(x=>x.includes('CONDITION:cond-1:WARNING:ACTIVE:TEST')),true);});
test('missing continuation gives INDETERMINATE not fabricated status',()=>{const r=evaluate(makeInput({continuationSource:false}));assert.equal(r.snapshot.lifecycleStatus,'INDETERMINATE');assert.equal(r.snapshot.continuationReadiness,'UNKNOWN');});
test('missing progress gives INDETERMINATE',()=>{assert.equal(evaluate(makeInput({progressSource:false})).snapshot.lifecycleStatus,'INDETERMINATE');});
test('stale progress binding fails closed',()=>{const p=progressFixture();p.currentBinding={...p.currentBinding,scopeDigest:H('other-scope')};const r=evaluateProjectStatus(makeInput({progress:p}),null,opts);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'PHG23_STALE');});
test('schedule not requested is NOT_APPLICABLE',()=>{const e=estimationFixture(1_003_000);assert.equal(evaluate(makeInput({estimation:e})).snapshot.scheduleHealth,'NOT_APPLICABLE');});
test('requested schedule without estimation is UNKNOWN not BLOCKED',()=>{const r=evaluate(makeInput({schedule:true}));assert.equal(r.snapshot.scheduleHealth,'UNKNOWN');assert.notEqual(r.snapshot.lifecycleStatus,'BLOCKED');});
test('deadline conservative bound ON_TRACK',()=>{const e=estimationFixture(1_003_000);assert.equal(evaluate(makeInput({estimation:e,schedule:true})).snapshot.scheduleHealth,'ON_TRACK');});
test('deadline optimistic bound after target is LATE without lifecycle block',()=>{const e=estimationFixture(1_000_500),r=evaluate(makeInput({estimation:e,schedule:true}));assert.equal(r.snapshot.scheduleHealth,'LATE');assert.equal(r.snapshot.lifecycleStatus,'IN_PROGRESS');});
test('deadline straddle is AT_RISK',()=>{const e=estimationFixture(1_001_500);assert.equal(evaluate(makeInput({estimation:e,schedule:true})).snapshot.scheduleHealth,'AT_RISK');});
test('resume drift requires replan without rewriting M17 action',()=>{const cp=checkpointFixture(),resume=resumeFixture(cp.checkpoint.checkpointDigest,cp.checkpoint.nextLegalAction,'DRIFT_REQUIRES_REPLAN'),r=evaluate(makeInput({cp,resume}));assert.equal(r.snapshot.continuationReadiness,'REPLAN_REQUIRED');assert.equal(r.snapshot.nextLegalAction,null);});
test('READY resume action disagreement is conflict',()=>{const cp=checkpointFixture(),resume=resumeFixture(cp.checkpoint.checkpointDigest,'OTHER_ACTION','READY');assert.equal(evaluate(makeInput({cp,resume})).snapshot.continuationReadiness,'CONFLICT');});
test('resume another checkpoint cannot constrain silently',()=>{const cp=checkpointFixture(),resume=resumeFixture(H('other-checkpoint'),cp.checkpoint.nextLegalAction,'READY');assert.equal(evaluate(makeInput({cp,resume})).snapshot.continuationReadiness,'CONFLICT');});
test('capability gap blocks readiness without lifecycle blocker',()=>{const cp=checkpointFixture({availableCapabilities:[]}),r=evaluate(makeInput({cp}));assert.equal(r.snapshot.continuationReadiness,'BLOCKED');assert.equal(r.snapshot.lifecycleStatus,'IN_PROGRESS');});
test('snapshot binds exact upstream handoffs, readiness and reason trace',()=>{const e=estimationFixture(1_003_000),r=evaluate(makeInput({estimation:e,schedule:true}));assert.equal(r.snapshot.checkpointReadinessCertificateDigest,r.continuation.readinessCertificateDigest);assert.equal(r.snapshot.continuationHandoffDigest,r.continuation.handoffDigest);assert.equal(r.snapshot.progressHandoffDigest,r.progress.handoffDigest);assert.equal(r.snapshot.estimationHandoffDigest,r.estimation.handoffDigest);assert.ok(r.snapshot.reasonCodeTrace.length>0);assert.match(r.snapshot.validityBindingDigest,/^sha256:/);});
test('DPH carries semantic digest reason trace and validity binding',()=>{const r=evaluate(makeInput()),h=createDelegatedProjectStatusHandoff(r.snapshot,opts).value;assert.equal(h.owner,'M23_PROJECT_STATUS');assert.equal(h.semanticDigest,r.snapshot.semanticDigest);assert.deepEqual(h.reasonCodes,r.snapshot.reasonCodeTrace);assert.equal(h.validityBindingDigest,r.snapshot.validityBindingDigest);});
test('integrity receipt detects lifecycle label tamper',()=>{const input=makeInput(),r=evaluate(input),receipt=createProjectStatusIntegrityReceipt({...r.snapshot,lifecycleStatus:'BLOCKED'},input,opts).value;assert.equal(receipt.valid,false);});
test('integrity receipt detects reason-trace tamper',()=>{const input=makeInput(),r=evaluate(input),receipt=createProjectStatusIntegrityReceipt({...r.snapshot,reasonCodeTrace:['FORGED']},input,opts).value;assert.equal(receipt.valid,false);});
test('integrity receipt detects upstream handoff mix-and-match',()=>{const input=makeInput(),r=evaluate(input),receipt=createProjectStatusIntegrityReceipt({...r.snapshot,progressHandoffDigest:H('forged')},input,opts).value;assert.equal(receipt.valid,false);});
test('historical snapshot binds predecessor semantic digest',()=>{const a=evaluate(makeInput({statusId:'a'})),b=evaluate(makeInput({statusId:'b'}),a.snapshot);assert.equal(b.snapshot.predecessorSnapshotDigest,a.snapshot.snapshotDigest);assert.equal(b.snapshot.predecessorSemanticDigest,a.snapshot.semanticDigest);});
test('COMPLETE cannot reopen silently',()=>{const p=progressFixture('FULL'),c=completion(p).value,first=evaluate(makeInput({progress:p,completionOutcome:c,statusId:'complete'})),second=evaluate(makeInput({progress:progressFixture('PARTIAL'),statusId:'reopen'}),first.snapshot),t=createStatusTransitionRecord(first.snapshot,second.snapshot,null,opts);assert.equal(t.ok,false);assert.equal(t.diagnostics[0].code,'STR23_REOPEN_WITNESS_REQUIRED');});
test('explicit reopen witness authorizes COMPLETE regression',()=>{const p=progressFixture('FULL'),c=completion(p).value,first=evaluate(makeInput({progress:p,completionOutcome:c,statusId:'complete'})),second=evaluate(makeInput({progress:progressFixture('PARTIAL'),statusId:'reopen'}),first.snapshot),w=createStatusReopenWitness({witnessId:'reopen-1',owner:'EXTERNAL_CANONICAL',priorCompleteSnapshotDigest:first.snapshot.snapshotDigest,authorizationFactDigest:H('reopen-auth'),reasonCode:'EVIDENCE_INVALIDATED'},opts).value,t=createStatusTransitionRecord(first.snapshot,second.snapshot,w,opts);assert.equal(t.ok,true);assert.ok(t.value.changedDimensions.includes('LIFECYCLE'));assert.ok(t.value.changedSourceIdentities.includes('PROGRESS'));assert.ok(t.value.reasonCodes.length>0);});
test('future M27 reopen unavailable before M27',()=>{assert.equal(createStatusReopenWitness({witnessId:'r',owner:'M27_ASSURANCE',priorCompleteSnapshotDigest:H('p'),authorizationFactDigest:H('a'),reasonCode:'X'},opts).ok,false);});
test('transition records schedule/readiness/source changes',()=>{const a=evaluate(makeInput({statusId:'a'})),e=estimationFixture(1_000_500),b=evaluate(makeInput({statusId:'b',estimation:e,schedule:true}),a.snapshot),t=createStatusTransitionRecord(a.snapshot,b.snapshot,null,opts).value;assert.ok(t.changedDimensions.includes('SCHEDULE'));assert.ok(t.changedSourceIdentities.includes('ESTIMATION'));assert.equal(t.predecessorSemanticDigest,a.snapshot.semanticDigest);});
test('history replay idempotent duplicate visible',()=>{const a=evaluate(makeInput({statusId:'a'})),b=evaluate(makeInput({statusId:'b'}),a.snapshot),t=createStatusTransitionRecord(a.snapshot,b.snapshot,null,opts).value,g=guardStatusHistory([t,t],opts).value;assert.equal(g.state,'CLEAR');assert.equal(g.acceptedTransitionDigests.length,1);assert.equal(g.duplicateTransitionDigests.length,1);});
test('divergent successors expose split brain',()=>{const base=evaluate(makeInput({statusId:'base'})),one=evaluate(makeInput({progress:progressFixture('PARTIAL'),statusId:'one'}),base.snapshot),two=evaluate(makeInput({progress:progressFixture('ZERO'),statusId:'two'}),base.snapshot),t1=createStatusTransitionRecord(base.snapshot,one.snapshot,null,opts).value,t2=createStatusTransitionRecord(base.snapshot,two.snapshot,null,opts).value,g=guardStatusHistory([t1,t2],opts).value;assert.equal(g.state,'CONFLICT');assert.deepEqual(g.splitBrainPredecessorDigests,[base.snapshot.snapshotDigest]);});
test('bounded history explicitly TRUNCATED',()=>{const a=evaluate(makeInput({statusId:'a'})),b=evaluate(makeInput({statusId:'b'}),a.snapshot),c=evaluate(makeInput({statusId:'c'}),b.snapshot),t1=createStatusTransitionRecord(a.snapshot,b.snapshot,null,opts).value,t2=createStatusTransitionRecord(b.snapshot,c.snapshot,null,opts).value,g=guardStatusHistory([t1,t2],{digest,maxHistory:1}).value;assert.equal(g.state,'TRUNCATED');assert.equal(g.historyTruncated,true);assert.equal(g.processedTransitionCount,1);assert.equal(g.totalTransitionCount,2);});
test('freshness CURRENT for exact identities',()=>{const r=evaluate(makeInput()),g=createStatusFreshnessGate(r.snapshot,freshnessOf(r.snapshot),opts).value;assert.equal(g.state,'CURRENT');assert.equal(g.reusable,true);});
test('freshness STALE when mandatory/condition identity changes',()=>{const r=evaluate(makeInput()),cur={...freshnessOf(r.snapshot),conditionIndexDigest:H('changed')},g=createStatusFreshnessGate(r.snapshot,cur,opts).value;assert.equal(g.state,'STALE');assert.equal(g.reusable,false);assert.deepEqual(g.staleSubjects,['conditions']);});
test('freshness CONFLICT for contradictory applicable optional source',()=>{const e=estimationFixture(1_003_000),r=evaluate(makeInput({estimation:e,schedule:true})),cur={...freshnessOf(r.snapshot),estimationHandoffDigest:H('other-estimation')},g=createStatusFreshnessGate(r.snapshot,cur,opts).value;assert.equal(g.state,'CONFLICT');assert.deepEqual(g.conflictSubjects,['estimation']);});
test('freshness INDETERMINATE when mandatory current identity missing',()=>{const r=evaluate(makeInput()),cur={...freshnessOf(r.snapshot),progressHandoffDigest:null},g=createStatusFreshnessGate(r.snapshot,cur,opts).value;assert.equal(g.state,'INDETERMINATE');assert.deepEqual(g.indeterminateSubjects,['progress']);});
test('ambient system clock never consulted',()=>{const original=Date.now;Date.now=()=>{throw new Error('clock forbidden');};try{assert.equal(evaluateProjectStatus(makeInput(),null,opts).ok,true);}finally{Date.now=original;}});
test('cancellation fails closed',()=>{const r=evaluateProjectStatus(makeInput(),null,{digest,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_CANCELLED');});
test('invalid digest provider fails closed',()=>{const r=evaluateProjectStatus(makeInput(),null,{digest:{algorithm:'sha256',digest:()=> 'bad'}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_OUTPUT_INVALID');});
test('condition owner spoofing rejected',()=>{const cp=checkpointFixture(),r=createStatusCondition({conditionId:'x',owner:'M21_PROGRESS',projectId:PROJECT,lineageId:LINEAGE_ID,checkpointDigest:cp.checkpoint.checkpointDigest,class:'BLOCKING',state:'ACTIVE',reasonCode:'X',sourceIdentityDigest:H('x'),validityBindingDigest:H('y'),supersedesConditionDigest:null},opts);assert.equal(r.ok,false);});
