import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{M24_MECHANISMS,createEvidenceIntentCapsule,createEvidenceAuthorityBoundary,createAuthorityRoot,createAuthorityRootSet,createProducerAuthorityEntry,createSourceAuthorityIndex,authorizeProducer,createSubjectStateBinding,applyEvidencePrivacyMembrane,createMachineEvidenceItem,verifyMachineEvidenceItem,createMachineEvidenceManifest,createBindingIntegrityCertificate,createCompatibilityWitness,createDigestAlgorithmBoundary,createMixAndMatchSpliceWitness,createEvidenceFreshnessGate,createEvidenceCompletenessGate,detectDependencyInvalidation,evaluateEvidence,createEvidenceReceiptSet,createReceiptReplayGuard,createEvidenceRejectionReceipt,createEvidenceSplitBrainWitness,createEvidenceAcceptanceContract,createDownstreamProofContextHandoff,validateDodEvidenceReferences}from'../packages/evidence-engine/dist/public.js';

const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`;
const PROJECT='gef-bootstrap',LINEAGE='lineage-24';
function subject(extra={}){const base={projectId:PROJECT,lineageId:LINEAGE,subjectKind:'WORK_ORDER',subjectId:'GBS-WO-M24-001',moduleId:'M24',workOrderId:'GBS-WO-M24-001',checkpointDigest:H('checkpoint'),baseRevision:{domain:'GIT_COMMIT',algorithm:null,value:'base-sha'},headRevision:{domain:'GIT_COMMIT',algorithm:null,value:'head-sha'},treeRevision:{domain:'GIT_TREE',algorithm:null,value:'tree-sha'},runtimeIdentity:{domain:'RUNTIME',algorithm:null,value:'node24'},platformIdentity:{domain:'PLATFORM',algorithm:null,value:'linux'},policyDigest:H('policy'),dependencyDigests:[H('dep-a')]};const r=createSubjectStateBinding({...base,...extra},opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
function authority({producer='TEST_RUNNER',kinds=['TEST'],claims=['REQ'],rootId='root-1'}={}){const root=createAuthorityRoot({rootId,rootClass:'MODULE_GOVERNANCE',owner:'MODULE_GOVERNANCE',projectId:PROJECT,lineageId:LINEAGE,semanticIdentity:H(`root:${rootId}`),validityBindingDigest:H(`root-valid:${rootId}`),sourceRef:`root:${rootId}`,allowedProducerIds:[producer],allowedEvidenceKinds:kinds,allowedClaimPrefixes:claims},opts);assert.equal(root.ok,true,JSON.stringify(root));const roots=createAuthorityRootSet(PROJECT,LINEAGE,[root.value],opts);assert.equal(roots.ok,true,JSON.stringify(roots));const entry=createProducerAuthorityEntry({authorityId:`auth:${producer}`,producerId:producer,rootId,evidenceKinds:kinds,claimPrefixes:claims,sourceIdentityDigest:H(`auth-src:${producer}`)},roots.value,opts);assert.equal(entry.ok,true,JSON.stringify(entry));const index=createSourceAuthorityIndex(roots.value,[entry.value],opts);assert.equal(index.ok,true,JSON.stringify(index));return{root:root.value,roots:roots.value,entry:entry.value,index:index.value};}
function item(a,s=subject(),extra={}){const r=createMachineEvidenceItem({evidenceId:extra.evidenceId??'ev-1',kind:extra.kind??'TEST',producerId:extra.producerId??a.entry.producerId,subject:s,observation:extra.observation??'PASS',sourceIdentityDigest:extra.sourceIdentityDigest??H('source-1'),validityBindingDigest:extra.validityBindingDigest??H('validity-1'),claimIds:extra.claimIds??['REQ:1'],refs:extra.refs??[{refId:'artifact:1',kind:'ARTIFACT_ID',contentDigest:H('artifact-1')}]},opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
function fixture(extra={}){const a=authority(),s=subject(extra.subject??{}),i=item(a,s,extra.item??{}),m=createMachineEvidenceManifest(a.roots,a.index,[i],opts);assert.equal(m.ok,true,JSON.stringify(m));const intent=createEvidenceIntentCapsule({intentId:'intent-1',projectId:PROJECT,lineageId:LINEAGE,subjectKind:s.subjectKind,subjectId:s.subjectId,claimIds:i.claimIds,requestedKinds:[i.kind]},opts);assert.equal(intent.ok,true,JSON.stringify(intent));const current=extra.current??s, freshness=extra.freshness??{rootSetDigest:a.roots.rootSetDigest,authorityIndexDigest:a.index.indexDigest,subjectBindingDigest:current.bindingDigest,sourceIdentityDigest:i.sourceIdentityDigest,validityBindingDigest:i.validityBindingDigest,conflictSubjects:[]};return{...a,s,i,m:m.value,intent:intent.value,current,freshness};}
function evaluate(f,witness=null){const r=evaluateEvidence({intent:f.intent,rootSet:f.roots,authorityIndex:f.index,manifest:f.m,evidenceId:f.i.evidenceId,currentSubject:f.current,currentFreshness:f.freshness,compatibilityWitness:witness},opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}

test('all 32 frozen M24 mechanisms are represented exactly once',()=>{assert.equal(M24_MECHANISMS.length,32);assert.equal(new Set(M24_MECHANISMS).size,32);});
test('authority boundary cannot mint producer truth or downstream authority',()=>{const f=fixture(),b=createEvidenceAuthorityBoundary(f.intent,opts).value;assert.equal(b.authority,'EVIDENCE_VALIDATION_AND_ACCEPTANCE_ONLY');assert.equal(b.mayCreateProducerTruth,false);assert.equal(b.mayCalculateProgress,false);assert.equal(b.mayComputeProof,false);assert.equal(b.mayDecideAssurance,false);});
test('M24 cannot self-issue an authority root',()=>{const r=createAuthorityRoot({rootId:'self',rootClass:'MODULE_GOVERNANCE',owner:'M24_EVIDENCE',projectId:PROJECT,lineageId:LINEAGE,semanticIdentity:H('x'),validityBindingDigest:H('y'),sourceRef:'root:self',allowedProducerIds:['P'],allowedEvidenceKinds:['TEST'],allowedClaimPrefixes:['REQ']},opts);assert.equal(r.ok,false);});
test('authority root scope prevents evidence-kind escalation',()=>{const a=authority(),r=createProducerAuthorityEntry({authorityId:'bad',producerId:'TEST_RUNNER',rootId:a.root.rootId,evidenceKinds:['SECURITY'],claimPrefixes:['REQ'],sourceIdentityDigest:H('bad')},a.roots,opts);assert.equal(r.ok,false);});
test('unknown producer cannot become authorized by owner string alone',()=>{const a=authority(),r=authorizeProducer(a.index,a.roots,'ROGUE','TEST',['REQ:1'],opts);assert.equal(r.ok,true);assert.equal(r.value.authorized,false);});
test('conflicting canonical roots are preserved and cannot authorize producer',()=>{const a=createAuthorityRoot({rootId:'same',rootClass:'MODULE_GOVERNANCE',owner:'MODULE_GOVERNANCE',projectId:PROJECT,lineageId:LINEAGE,semanticIdentity:H('a'),validityBindingDigest:H('v1'),sourceRef:'root:a',allowedProducerIds:['P'],allowedEvidenceKinds:['TEST'],allowedClaimPrefixes:['REQ']},opts).value,b=createAuthorityRoot({rootId:'same',rootClass:'MODULE_GOVERNANCE',owner:'MODULE_GOVERNANCE',projectId:PROJECT,lineageId:LINEAGE,semanticIdentity:H('b'),validityBindingDigest:H('v2'),sourceRef:'root:b',allowedProducerIds:['P'],allowedEvidenceKinds:['TEST'],allowedClaimPrefixes:['REQ']},opts).value,r=createAuthorityRootSet(PROJECT,LINEAGE,[a,b],opts);assert.equal(r.ok,true);assert.deepEqual(r.value.conflictingRootIds,['same']);});
test('portable evidence membrane rejects private paths and traversal refs',()=>{const r=applyEvidencePrivacyMembrane([{refId:'../secret',kind:'OPAQUE',contentDigest:H('x')},{refId:'/home/user/token',kind:'OPAQUE',contentDigest:H('y')}],opts);assert.equal(r.ok,true);assert.equal(r.value.safe,false);});
test('machine evidence tamper is detected',()=>{const f=fixture(),r=verifyMachineEvidenceItem({...f.i,semanticDigest:H('forged')},opts);assert.equal(r.ok,true);assert.equal(r.value,false);});
test('manifest identity is deterministic under evidence permutation',()=>{const a=authority(),s=subject(),i1=item(a,s,{evidenceId:'ev-a',sourceIdentityDigest:H('a')}),i2=item(a,s,{evidenceId:'ev-b',sourceIdentityDigest:H('b')}),m1=createMachineEvidenceManifest(a.roots,a.index,[i1,i2],opts),m2=createMachineEvidenceManifest(a.roots,a.index,[i2,i1],opts);assert.equal(m1.value.manifestDigest,m2.value.manifestDigest);});
test('divergent duplicate evidence IDs become explicit ledger conflict',()=>{const a=authority(),s=subject(),i1=item(a,s,{evidenceId:'same',sourceIdentityDigest:H('a')}),i2=item(a,s,{evidenceId:'same',sourceIdentityDigest:H('b')}),m=createMachineEvidenceManifest(a.roots,a.index,[i1,i2],opts);assert.equal(m.ok,true);assert.deepEqual(m.value.bindingLedger.conflictingEvidenceIds,['same']);});
test('exact subject binding certifies current evidence',()=>{const f=fixture(),c=createBindingIntegrityCertificate(f.i,f.current,null,opts);assert.equal(c.value.exact,true);assert.equal(c.value.translated,false);});
test('head change invalidates exact binding without compatibility witness',()=>{const f=fixture(),current=subject({headRevision:{domain:'GIT_COMMIT',algorithm:null,value:'other-head'}}),c=createBindingIntegrityCertificate(f.i,current,null,opts);assert.equal(c.value.exact,false);assert.equal(c.value.translated,false);assert.equal(c.value.mismatchedDimensions.includes('headRevision'),true);});
test('explicit external compatibility witness can translate same-project binding',()=>{const f=fixture(),current=subject({runtimeIdentity:{domain:'RUNTIME',algorithm:null,value:'node24.1'}}),w=createCompatibilityWitness({witnessId:'w1',owner:'EXTERNAL_CANONICAL',projectId:PROJECT,lineageId:LINEAGE,fromBindingDigest:f.i.subject.bindingDigest,toBindingDigest:current.bindingDigest,claimIds:f.i.claimIds,authorizationDigest:H('compat-auth')},opts);assert.equal(w.ok,true);const c=createBindingIntegrityCertificate(f.i,current,w.value,opts);assert.equal(c.value.exact,false);assert.equal(c.value.translated,true);});
test('digest domain boundary separates M24 semantic SHA from opaque Git identity',()=>{const a=createDigestAlgorithmBoundary({domain:'M24_SEMANTIC',algorithm:'sha256',value:H('semantic')},opts),b=createDigestAlgorithmBoundary({domain:'GIT_COMMIT',algorithm:null,value:'deadbeef'},opts);assert.equal(a.value.valid,true);assert.equal(b.value.valid,true);assert.notEqual(a.value.boundaryDigest,b.value.boundaryDigest);});
test('mix-and-match witness detects cross-lineage splice',()=>{const a=authority(),i1=item(a,subject(),{evidenceId:'a'}),i2=item(a,subject({lineageId:'other-lineage'}),{evidenceId:'b'}),w=createMixAndMatchSpliceWitness([i1,i2],opts);assert.equal(w.value.spliceDetected,true);assert.equal(w.value.mixedLineage,true);});
test('freshness gate is CURRENT only when every observed binding matches',()=>{const f=fixture(),g=createEvidenceFreshnessGate(f.i,f.roots,f.index,f.current.bindingDigest,f.freshness,opts);assert.equal(g.value.state,'CURRENT');});
test('freshness mismatch becomes STALE and missing observation becomes INDETERMINATE',()=>{const f=fixture(),stale=createEvidenceFreshnessGate(f.i,f.roots,f.index,f.current.bindingDigest,{...f.freshness,validityBindingDigest:H('changed')},opts),unknown=createEvidenceFreshnessGate(f.i,f.roots,f.index,f.current.bindingDigest,{...f.freshness,validityBindingDigest:null},opts);assert.equal(stale.value.state,'STALE');assert.equal(unknown.value.state,'INDETERMINATE');});
test('current authorized PASS evaluates to ACCEPTED',()=>{const r=evaluate(fixture());assert.equal(r.acceptanceState,'ACCEPTED');assert.equal(r.decisionReceipt.state,'ACCEPTED');});
test('producer FAIL evaluates to REJECTED',()=>{const r=evaluate(fixture({item:{observation:'FAIL'}}));assert.equal(r.acceptanceState,'REJECTED');assert.equal(r.decisionReceipt.state,'REJECTED');});
test('inconclusive evidence stays UNKNOWN rather than fabricating rejection or acceptance',()=>{const r=evaluate(fixture({item:{observation:'INCONCLUSIVE'}}));assert.equal(r.acceptanceState,'UNKNOWN');assert.equal(r.decisionReceipt,null);});
test('stale evidence produces immutable STALE receipt',()=>{const f=fixture();f.freshness={...f.freshness,sourceIdentityDigest:H('new-source')};const r=evaluate(f);assert.equal(r.acceptanceState,'STALE');assert.equal(r.decisionReceipt.state,'STALE');});
test('receipt replay is visible and does not create independent support',()=>{const r=evaluate(fixture()),g=createReceiptReplayGuard([r.decisionReceipt,r.decisionReceipt],opts),s=createEvidenceReceiptSet([r.decisionReceipt,r.decisionReceipt],opts);assert.equal(g.value.duplicateReceiptDigests.length,1);assert.equal(g.value.state,'CLEAR');assert.equal(s.value.receiptDigests.length,1);});
test('receipt history truncation is explicit',()=>{const r=evaluate(fixture()),g=createReceiptReplayGuard([r.decisionReceipt,r.decisionReceipt],{...opts,maxHistory:1});assert.equal(g.value.state,'TRUNCATED');assert.equal(g.value.historyTruncated,true);assert.equal(g.value.processedCount,1);assert.equal(g.value.totalCount,2);});
test('incomplete dependency knowledge widens invalidation conservatively',()=>{const f=fixture(),entries=[{evidenceId:'ev-1',claimIds:['REQ:1'],dependencyDigests:[H('dep-a')]},{evidenceId:'ev-2',claimIds:['REQ:2'],dependencyDigests:[H('dep-b')]}],d=detectDependencyInvalidation(entries,[H('dep-a')],false,opts);assert.equal(d.value.widened,true);assert.deepEqual(d.value.affectedEvidenceIds,['ev-1','ev-2']);});
test('completeness distinguishes complete partial conflict and truncation without claiming proof',()=>{assert.equal(createEvidenceCompletenessGate(['a'],['a'],false,false,false,opts).value.state,'COMPLETE');assert.equal(createEvidenceCompletenessGate(['a','b'],['a'],false,false,false,opts).value.state,'PARTIAL');assert.equal(createEvidenceCompletenessGate(['a'],['a'],true,false,false,opts).value.state,'TRUNCATED');assert.equal(createEvidenceCompletenessGate(['a'],['a'],false,true,false,opts).value.state,'CONFLICT');});
test('EAC24 projects M24 acceptance to M21 without weight or progress authority',()=>{const f=fixture(),r=evaluate(f),c=createEvidenceAcceptanceContract('unit-1',f.i,r.decisionReceipt,opts);assert.equal(c.ok,true);assert.equal(c.value.binding.owner,'M24_EVIDENCE');assert.equal(c.value.binding.state,'ACCEPTED');assert.equal('earnedWeight'in c.value,false);assert.equal('percentage'in c.value,false);});
test('DPC24 preserves evidence facts and explicitly denies proof/assurance authority',()=>{const f=fixture(),r=evaluate(f),h=createDownstreamProofContextHandoff(f.m.manifestDigest,f.m.claimMapping.mappingDigest,[r.decisionReceipt],[f.i],'M25_PROOF',opts);assert.equal(h.ok,true);assert.equal(h.value.owner,'M24_EVIDENCE');assert.equal(h.value.mayComputeProof,false);assert.equal(h.value.mayDecideAssurance,false);assert.deepEqual(h.value.acceptedEvidenceDigests,[f.i.semanticDigest]);});
test('M12 integration validates refs without rewriting criterion status',()=>{const f=fixture(),r=evaluate(f),criteria=[{criterionId:'dod-1',required:true,applicable:true,status:'SATISFIED',sourceRefs:[],evidenceRefs:['ev-1']}],ctx=validateDodEvidenceReferences(criteria,[r.decisionReceipt],opts);assert.equal(ctx.ok,true);assert.equal(ctx.value.entries[0].originalStatus,'SATISFIED');assert.equal(criteria[0].status,'SATISFIED');assert.equal(ctx.value.entries[0].state,'CURRENT');});
test('operation budget fails closed on oversized root-set traversal',()=>{const roots=['a','b'].map(id=>createAuthorityRoot({rootId:id,rootClass:'MODULE_GOVERNANCE',owner:'MODULE_GOVERNANCE',projectId:PROJECT,lineageId:LINEAGE,semanticIdentity:H(id),validityBindingDigest:H(`v:${id}`),sourceRef:`root:${id}`,allowedProducerIds:['P'],allowedEvidenceKinds:['TEST'],allowedClaimPrefixes:['REQ']},opts).value),r=createAuthorityRootSet(PROJECT,LINEAGE,roots,{...opts,maxUnits:1});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_BUDGET_EXCEEDED');});
