import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createSubjectStateBinding,createAuthorityRoot,createAuthorityRootSet,createProducerAuthorityEntry,createSourceAuthorityIndex,createMachineEvidenceItem,createMachineEvidenceManifest,createEvidenceIntentCapsule,createDownstreamProofContextHandoff}from'../packages/evidence-engine/dist/public.js';
import{createCanonicalClaimIdentity,createProofObligationDeclaration,createProofNamespaceSeal,createProofIdentityManifest,createProofDependencyGraph,createProofSnapshotCapsule,createCarryForwardCandidate,createCarryForwardDecision}from'../packages/proof-graph/dist/public.js';
const digest={algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')},opts={digest},H=s=>`sha256:${createHash('sha256').update(s).digest('hex')}`,P='gef-bootstrap',L='lineage-25',POL=H('proof-policy');
function evidence(){const subject=createSubjectStateBinding({projectId:P,lineageId:L,subjectKind:'WORK_ORDER',subjectId:'GBS-WO-M25-001',moduleId:'M25',workOrderId:'GBS-WO-M25-001',checkpointDigest:H('checkpoint'),baseRevision:{domain:'GIT_COMMIT',algorithm:null,value:'base'},headRevision:{domain:'GIT_COMMIT',algorithm:null,value:'head'},treeRevision:{domain:'GIT_TREE',algorithm:null,value:'tree'},runtimeIdentity:{domain:'RUNTIME',algorithm:null,value:'node24'},platformIdentity:{domain:'PLATFORM',algorithm:null,value:'linux'},policyDigest:H('policy'),dependencyDigests:[H('dep')]},opts).value,root=createAuthorityRoot({rootId:'r25',rootClass:'MODULE_GOVERNANCE',owner:'MODULE_GOVERNANCE',projectId:P,lineageId:L,semanticIdentity:H('root'),validityBindingDigest:H('root-valid'),sourceRef:'root:r25',allowedProducerIds:['T'],allowedEvidenceKinds:['TEST'],allowedClaimPrefixes:['REQ']},opts).value,roots=createAuthorityRootSet(P,L,[root],opts).value,trusted={...opts,trustedAuthorityRootDigests:[root.rootDigest]},entry=createProducerAuthorityEntry({authorityId:'a25',producerId:'T',rootId:root.rootId,evidenceKinds:['TEST'],claimPrefixes:['REQ'],sourceIdentityDigest:H('auth')},roots,opts).value,index=createSourceAuthorityIndex(roots,[entry],opts).value,item=createMachineEvidenceItem({evidenceId:'ev-1',kind:'TEST',producerId:'T',subject,observation:'PASS',sourceIdentityDigest:H('ev-src'),validityBindingDigest:H('ev-valid'),claimIds:['REQ:1'],refs:[{refId:'artifact:1',kind:'ARTIFACT_ID',contentDigest:H('artifact')}]},trusted).value,manifest=createMachineEvidenceManifest(roots,index,[item],trusted).value,intent=createEvidenceIntentCapsule({intentId:'intent-25',projectId:P,lineageId:L,subjectKind:subject.subjectKind,subjectId:subject.subjectId,claimIds:['REQ:1'],requestedKinds:['TEST']},trusted).value,freshness={rootSetDigest:roots.rootSetDigest,authorityIndexDigest:index.indexDigest,subjectBindingDigest:subject.bindingDigest,sourceIdentityDigest:item.sourceIdentityDigest,validityBindingDigest:item.validityBindingDigest,conflictSubjects:[]},evaluation={intent,rootSet:roots,authorityIndex:index,manifest,evidenceId:'ev-1',currentSubject:subject,currentFreshness:freshness,compatibilityWitness:null},handoff=createDownstreamProofContextHandoff([evaluation],'M25_PROOF',trusted).value;return{trusted,m24:{evaluations:[evaluation],handoff,options:trusted}};}
function computation(m24,source){const claim=createCanonicalClaimIdentity({claimId:'REQ:1',ownerId:'M12_DOD',sourceIdentityDigest:H(`claim:${source}`),projectId:P,lineageId:L,proofPolicyDigest:POL},opts).value,obligation=createProofObligationDeclaration({obligationId:'obl-1',claimId:'REQ:1',ownerId:'M12_DOD',sourceIdentityDigest:H(`obl:${source}`),projectId:P,lineageId:L,proofPolicyDigest:POL,mode:'ALL',threshold:null,dependencies:[{kind:'EVIDENCE',id:'ev-1'}],applicable:true,required:true,validityDependencyDigests:[H('validity')]},opts).value,ns=createProofNamespaceSeal(P,L,POL,opts).value,manifest=createProofIdentityManifest(ns,[claim],[obligation],opts).value,graph=createProofDependencyGraph(manifest,['REQ:1'],opts).value;return{graph,manifest,claims:[claim],m24};}
test('carry-forward source authority change invalidates full reuse',()=>{const e=evidence(),prior=computation(e.m24,'A'),current=computation(e.m24,'B'),snapshot=createProofSnapshotCapsule({snapshotId:'source-prior',computation:prior,fingerprintDigests:[],invalidationVectorDigest:null,predecessorSemanticDigest:null},e.trusted,opts);assert.equal(snapshot.ok,true,JSON.stringify(snapshot));const candidate=createCarryForwardCandidate('source-change',snapshot.value,prior,current,'REQ:1',true,[],opts);assert.equal(candidate.ok,true,JSON.stringify(candidate));assert.notEqual(candidate.value.priorCompatibilityKeyDigest,candidate.value.currentCompatibilityKeyDigest);const decision=createCarryForwardDecision(candidate.value,[],['CLAIM:REQ:1'],false,opts);assert.equal(decision.ok,true,JSON.stringify(decision));assert.equal(decision.value.decision,'RECOMPUTE');});
