import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{
 M26_MECHANISMS,createHedsIntent,createHedsAuthorityBoundary,createBaselineSemanticIdentity,createCandidateSemanticIdentity,sealReviewSourceProjection,createCrossLineageWitness,createDeltaChangeInventory,
 createSourceCoverageManifest,createSourceBindingGate,createAuthorityConsistencyGate,createDependencyProjection,verifyM25ProofHandoff,createValidityContextGate,createSourceGapWitness,createMixAndMatchWitness,
 createSemanticDeltaMatrix,createImpactFrontier,createOwnershipReviewFilter,createReviewCandidateIndex,createReviewCarryForward,createSemanticFinding,createDeltaTraceReceipt,
 evaluateReviewGates,evaluateArtifactReviewGates,createHedsFindingRegister,createHedsVerdictCapsule,verifyHedsVerdictCapsule,createHedsTransitionReceipt,createHedsReplayGuard,createHedsPredecessorReviewIdentity,createHedsSplitBrainWitness,createDownstreamHedsHandoff
}from'../packages/heds-delta-review/dist/public.js';
const raw=s=>createHash('sha256').update(s).digest('hex'),sha=s=>`sha256:${raw(s)}`,digest={algorithm:'sha256',digest:raw},options={digest,maxUnits:20000,maxHistory:1000};
const unwrap=r=>{assert.equal(r.ok,true,r.ok?'':JSON.stringify(r.diagnostics));return r.value;};
function stable(v){if(v===null||typeof v==='number'||typeof v==='boolean'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;}
function src(subject,semantic,{owner='OWNER',sourceId=`SOURCE-${subject}`,validity=`valid-${subject}`,deps=[],project='PROJECT',lineage='LINEAGE'}={}){return unwrap(sealReviewSourceProjection({subjectId:subject,sourceId,ownerId:owner,projectId:project,lineageId:lineage,semanticDigest:sha(semantic),validityBindingDigest:sha(validity),dependencyDigests:deps},options));}
const current=p=>({subjectId:p.subjectId,sourceId:p.sourceId,ownerId:p.ownerId,projectId:p.projectId,lineageId:p.lineageId,semanticDigest:p.semanticDigest,validityBindingDigest:p.validityBindingDigest});
function proofHandoff({fingerprints=[sha('fp')],unresolved=['A'],consumer='M26_DELTA_REVIEW',tamper=false}={}){const base={owner:'M25_PROOF',consumer,snapshotDigest:sha('snap'),proofStates:unresolved.map(claimId=>({claimId,state:'UNPROVEN'})),selectedSupportIds:[],proofFingerprintDigests:fingerprints,invalidationVectorDigest:sha('iv'),unresolvedClaimIds:unresolved,mayPerformDeltaReview:false,mayDecideAssurance:false,mayMutateDod:false,mayCalculateProgress:false,mayPromoteCheckpoint:false};const handoffDigest=`sha256:${raw(`DPH25\n${stable(base)}`)}`;return{...base,handoffDigest:tamper?sha('forged'):handoffDigest};}
function identityPair(before,after){return{baseline:unwrap(createBaselineSemanticIdentity('BASE','PROJECT','LINEAGE',sha('coverage-base'),before.map(x=>x.projectionDigest),options)),candidate:unwrap(createCandidateSemanticIdentity('CANDIDATE','PROJECT','LINEAGE',sha('coverage-candidate'),after.map(x=>x.projectionDigest),options))};}
function intentFor(subjects){return unwrap(createHedsIntent({intentId:'INTENT',projectId:'PROJECT',lineageId:'LINEAGE',baselineId:'BASE',candidateId:'CANDIDATE',reviewPolicyDigest:sha('policy'),requestedSubjectIds:subjects,purpose:'semantic-review'},options));}
function artifactInput({before,after,proof=null,findings=[],priorFindings=[],priorVerdict=null,baselineCoverage='COMPLETE',candidateCoverage='COMPLETE',dependencyKnowledgeComplete=true,knownExternalDependencyDigests=[],allKnownSubjectIds=null,materializationState='COMPLETE',currentSourceIdentities=null}){const ids=identityPair(before,after),intent=intentFor([...new Set([...before,...after].map(x=>x.subjectId))]);return{intent,...ids,baselineSources:before,candidateSources:after,currentSourceIdentities:currentSourceIdentities??after.map(current),baselineCoverage,candidateCoverage,dependencyKnowledgeComplete,knownExternalDependencyDigests,proofHandoff:proof,allKnownSubjectIds:allKnownSubjectIds??[...new Set([...before,...after].map(x=>x.subjectId))],priorFindings,findings,priorVerdict,materializationState};}
function reviewedContext(args){const input=artifactInput(args),gates=unwrap(evaluateArtifactReviewGates(input,options)),verdict=unwrap(createHedsVerdictCapsule('VERDICT',input,options));return{input,gates,verdict};}

test('registry covers exactly 40 frozen mechanisms',()=>{assert.equal(M26_MECHANISMS.length,40);assert.equal(new Set(M26_MECHANISMS).size,40);for(const id of ['HIC26','HAB26','BSI26','CSI26','RSP26','SDL26','DCI26','XLG26','SCM26','SBG26','ACG26','DPG26','PBG26','VCG26','SGW26','MMW26','SDM26','IFP26','ORF26','RCI26','RCF26','SFC26','SFS26','DTR26','BCG26','SCG26','PIG26','FCG26','ZHG26','AAG26','BMG26','VAG26','HVC26','HIR26','HSD26','HFR26','HTR26','HRG26','HSW26','DHH26'])assert.ok(M26_MECHANISMS.includes(id));});
test('HIC26 requested subject order is semantic-order independent',()=>{assert.equal(intentFor(['B','A']).intentDigest,intentFor(['A','B']).intentDigest);});
test('HAB26 explicitly denies adjacent authorities',()=>{const b=unwrap(createHedsAuthorityBoundary(intentFor(['A']),options));assert.equal(b.mayDecideAssurance,false);assert.equal(b.maySelectTests,false);assert.equal(b.mayOperateGit,false);});
test('BSI26 and CSI26 are domain-separated identities',()=>{const a=src('A','x'),b=unwrap(createBaselineSemanticIdentity('STATE','PROJECT','LINEAGE',sha('c'),[a.projectionDigest],options)),c=unwrap(createCandidateSemanticIdentity('STATE','PROJECT','LINEAGE',sha('c'),[a.projectionDigest],options));assert.notEqual(b.semanticDigest,c.semanticDigest);});
test('RSP26 dependency enumeration is deterministic',()=>{assert.equal(src('A','x',{deps:[sha('z'),sha('a')]}).projectionDigest,src('A','x',{deps:[sha('a'),sha('z')]}).projectionDigest);});
test('stable subject semantic mutation is MODIFIED',()=>{const a=src('A','old'),b=src('A','new'),ids=identityPair([a],[b]),e=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[b],true,options)).entries[0];assert.equal(e.changeClass,'MODIFIED');assert.equal(e.semanticChanged,true);});
test('owner-only mutation remains visible',()=>{const a=src('A','same',{owner:'ONE'}),b=src('A','same',{owner:'TWO'}),ids=identityPair([a],[b]),e=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[b],true,options)).entries[0];assert.equal(e.authorityChanged,true);});
test('new subject is ADDED',()=>{const b=src('B','new'),ids=identityPair([],[b]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[],[b],true,options)).entries[0].changeClass,'ADDED');});
test('removal requires complete coverage',()=>{const a=src('A','old'),ids=identityPair([a],[]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[],true,options)).entries[0].changeClass,'REMOVED');const r=createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[],false,options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DCI26_REMOVAL_UNPROVEN');});
test('cross-lineage comparison fails closed',()=>{const a=src('A','a'),b=src('A','b',{lineage:'OTHER'}),baseline=unwrap(createBaselineSemanticIdentity('BASE','PROJECT','LINEAGE',sha('cb'),[a.projectionDigest],options)),candidate=unwrap(createCandidateSemanticIdentity('CANDIDATE','PROJECT','OTHER',sha('cc'),[b.projectionDigest],options)),r=createDeltaChangeInventory(baseline,candidate,[a],[b],true,options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DCI26_LINEAGE_MISMATCH');});
test('SCM26 rejects duplicate subject projections',()=>{const a=src('A','a'),r=createSourceCoverageManifest('PROJECT','LINEAGE',[a,a],[a],'COMPLETE','COMPLETE',true,options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'SCM26_DUPLICATE_SUBJECT');});
test('SBG26 accepts exact current full identity',()=>{const a=src('A','a');assert.equal(unwrap(createSourceBindingGate([a],[current(a)],options)).valid,true);});
test('SBG26 exposes owner spoof as conflict',()=>{const a=src('A','a'),g=unwrap(createSourceBindingGate([a],[{...current(a),ownerId:'ATTACKER'}],options));assert.equal(g.valid,false);assert.deepEqual(g.conflictingSubjectIds,['A']);});
test('SBG26 exposes stale semantic identity',()=>{const a=src('A','a'),g=unwrap(createSourceBindingGate([a],[{...current(a),semanticDigest:sha('other')}],options));assert.equal(g.valid,false);assert.deepEqual(g.staleSubjectIds,['A']);});
test('ACG26 preserves divergent authority',()=>{const a=src('A','a',{owner:'ONE'}),b=src('A','a',{owner:'TWO'}),g=unwrap(createAuthorityConsistencyGate([a,b],options));assert.equal(g.valid,false);});
test('DPG26 cannot accept orphan dependency as complete',()=>{const dep=sha('orphan'),p=unwrap(createDependencyProjection([src('A','a',{deps:[dep]})],true,options));assert.equal(p.complete,false);assert.deepEqual(p.unknownDependencyDigests,[dep]);});
test('DPG26 accepts explicitly known external dependency',()=>{const dep=sha('external'),p=unwrap(createDependencyProjection([src('A','a',{deps:[dep]})],true,options,[dep]));assert.equal(p.complete,true);});
test('PBG26 explicit empty proof context is valid',()=>{const p=unwrap(verifyM25ProofHandoff(null,options));assert.equal(p.valid,true);assert.deepEqual(p.proofFingerprintDigests,[]);});
test('PBG26 verifies DPH25 fingerprints/unresolved claims',()=>{const p=unwrap(verifyM25ProofHandoff(proofHandoff(),options));assert.equal(p.valid,true);assert.deepEqual(p.proofFingerprintDigests,[sha('fp')]);assert.deepEqual(p.unresolvedClaimIds,['A']);});
test('PBG26 forged digest is rejected',()=>{assert.equal(unwrap(verifyM25ProofHandoff(proofHandoff({tamper:true}),options)).valid,false);});
test('PBG26 wrong consumer fails closed',()=>{const r=verifyM25ProofHandoff(proofHandoff({consumer:'M27_ASSURANCE'}),options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'PBG26_OWNER_CONSUMER_INVALID');});
test('VCG26 binds intent and exact manifest',()=>{const a=src('A','a'),m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'COMPLETE','COMPLETE',true,options)),baseline=unwrap(createBaselineSemanticIdentity('BASE','PROJECT','LINEAGE',sha('coverage-base'),m.baselineProjectionDigests,options)),candidate=unwrap(createCandidateSemanticIdentity('CANDIDATE','PROJECT','LINEAGE',sha('coverage-candidate'),m.candidateProjectionDigests,options)),binding=unwrap(createSourceBindingGate([a],[current(a)],options));assert.equal(unwrap(createValidityContextGate(intentFor(['A']),baseline,candidate,m,binding,options)).valid,true);});
test('VCG26 rejects baseline/candidate reversal',()=>{const a=src('A','a'),m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'COMPLETE','COMPLETE',true,options)),baseline=unwrap(createBaselineSemanticIdentity('CANDIDATE','PROJECT','LINEAGE',sha('coverage-base'),m.baselineProjectionDigests,options)),candidate=unwrap(createCandidateSemanticIdentity('BASE','PROJECT','LINEAGE',sha('coverage-candidate'),m.candidateProjectionDigests,options)),binding=unwrap(createSourceBindingGate([a],[current(a)],options)),v=unwrap(createValidityContextGate(intentFor(['A']),baseline,candidate,m,binding,options));assert.equal(v.valid,false);});
test('SGW26 exposes incomplete source knowledge',()=>{const a=src('A','a'),m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'PARTIAL','COMPLETE',false,options)),b=unwrap(createSourceBindingGate([a],[current(a)],options)),g=unwrap(createAuthorityConsistencyGate([a],options)),w=unwrap(createSourceGapWitness(['B'],b,g,m,options));assert.equal(w.incompleteCoverage,true);assert.equal(w.incompleteDependencies,true);});
test('MMW26 is explicit',()=>{assert.equal(unwrap(createMixAndMatchWitness(false,true,false,options)).mixed,true);});
test('SDM26 proof invalidation comes from verified PBG26',()=>{const a=src('A','same'),ids=identityPair([a],[a]),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[a],true,options)),proof=unwrap(verifyM25ProofHandoff(proofHandoff(),options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options));assert.equal(m.rows[0].proofInvalidated,true);});
test('IFP26 propagates changed semantic digest to dependent',()=>{const oldA=src('A','old'),newA=src('A','new'),b=src('B','b',{deps:[oldA.semanticDigest]}),ids=identityPair([oldA,b],[newA,b]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[oldA,b],[newA,b],true,options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([oldA,newA,b],true,options)),f=unwrap(createImpactFrontier(m,inv,dep,['A','B'],options));assert.deepEqual(f.transitivelyImpactedSubjectIds,['A','B']);});
test('IFP26 diamond impact de-duplicates subjects',()=>{const oldA=src('A','old'),newA=src('A','new'),b=src('B','b',{deps:[oldA.semanticDigest]}),c=src('C','c',{deps:[oldA.semanticDigest]}),ids=identityPair([oldA,b,c],[newA,b,c]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[oldA,b,c],[newA,b,c],true,options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([oldA,newA,b,c],true,options)),f=unwrap(createImpactFrontier(m,inv,dep,['A','B','C'],options));assert.deepEqual(f.transitivelyImpactedSubjectIds,['A','B','C']);});
test('IFP26 keeps unrelated subject isolated when dependency knowledge complete',()=>{const a=src('A','old'),aa=src('A','new'),z=src('Z','z'),ids=identityPair([a,z],[aa,z]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a,z],[aa,z],true,options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([a,aa,z],true,options)),f=unwrap(createImpactFrontier(m,inv,dep,['A','Z'],options));assert.deepEqual(f.transitivelyImpactedSubjectIds,['A']);});
test('IFP26 incomplete knowledge widens to all known subjects',()=>{const a=src('A','old'),aa=src('A','new'),z=src('Z','z'),ids=identityPair([a,z],[aa,z]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a,z],[aa,z],true,options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([a,aa,z],false,options)),f=unwrap(createImpactFrontier(m,inv,dep,['A','Z'],options));assert.equal(f.widened,true);assert.deepEqual(f.transitivelyImpactedSubjectIds,['A','Z']);});
test('ORF26 routes changed dimensions and denies owner-truth mutation',()=>{const a=src('A','old',{owner:'OWNER-A'}),aa=src('A','new',{owner:'OWNER-A'}),ids=identityPair([a],[aa]),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[aa],true,options)),f=unwrap(createOwnershipReviewFilter(inv,[a],[aa],options));assert.equal(f.routes[0].ownerId,'OWNER-A');assert.equal(f.routes[0].mayDecideOwnerTruth,false);});
test('RCI26 binds verified proof fingerprints',()=>{const a=src('A','old'),aa=src('A','new'),ids=identityPair([a],[aa]),proof=unwrap(verifyM25ProofHandoff(proofHandoff({unresolved:[]}),options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[aa],true,options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([a,aa],true,options)),front=unwrap(createImpactFrontier(m,inv,dep,['A'],options)),idx=unwrap(createReviewCandidateIndex(inv,front,[aa],proof,options));assert.deepEqual(idx.candidates[0].proofFingerprintDigests,[sha('fp')]);});
test('RCF26 exact source/proof/policy compatibility permits reuse',()=>{const a=src('A','a'),proof=unwrap(verifyM25ProofHandoff(proofHandoff({unresolved:[]}),options)),first=unwrap(createReviewCarryForward('A',a,proof,sha('policy'),sha('prior'),sha('wrong'),options)),second=unwrap(createReviewCarryForward('A',a,proof,sha('policy'),sha('prior'),first.currentCompatibilityDigest,options));assert.equal(second.state,'REUSE');});
test('RCF26 proof fingerprint change invalidates reuse',()=>{const a=src('A','a'),p1=unwrap(verifyM25ProofHandoff(proofHandoff({fingerprints:[sha('one')],unresolved:[]}),options)),p2=unwrap(verifyM25ProofHandoff(proofHandoff({fingerprints:[sha('two')],unresolved:[]}),options)),old=unwrap(createReviewCarryForward('A',a,p1,sha('policy'),sha('prior'),sha('x'),options)),next=unwrap(createReviewCarryForward('A',a,p2,sha('policy'),sha('prior'),old.currentCompatibilityDigest,options));assert.equal(next.state,'REVIEW');});
test('SFC26 resolved finding requires lineage',()=>{const r=createSemanticFinding({findingId:'F',subjectId:'A',severity:'HIGH',state:'RESOLVED',ruleId:'RULE',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options);assert.equal(r.ok,false);});
test('DTR26 seals inventory/frontier/candidates',()=>{const a=src('A','old'),aa=src('A','new'),ids=identityPair([a],[aa]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[aa],true,options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([a,aa],true,options)),front=unwrap(createImpactFrontier(m,inv,dep,['A'],options)),idx=unwrap(createReviewCandidateIndex(inv,front,[aa],proof,options)),t=unwrap(createDeltaTraceReceipt(ids.baseline.semanticDigest,ids.candidate.semanticDigest,inv,front,idx,[],options));assert.equal(t.inventoryDigest,inv.inventoryDigest);});
test('diagnostic boolean gates are non-artifact-bound',()=>{const g=unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:true,findingClosureValid:true,authorityConflict:false,truncated:false,indeterminate:false,findings:[]},options));assert.equal(g.artifactBound,false);});
test('HVC26 rejects tampered/resealed intent by recomputing context',()=>{const a=src('A','same'),input=artifactInput({before:[a],after:[a]}),forged={...input,intent:{...input.intent,intentDigest:sha('forged')}};const r=createHedsVerdictCapsule('V',forged,options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'VAG26_INTENT_TAMPERED');});
test('complete artifact review admits APPROVED',()=>{const a=src('A','same'),c=reviewedContext({before:[a],after:[a]});assert.equal(c.gates.artifactBound,true);assert.equal(c.gates.verdictAdmission.state,'PASS');assert.equal(c.verdict.verdict,'APPROVED');});
test('orphan dependency forces INDETERMINATE despite caller complete flag',()=>{const a=src('A','a',{deps:[sha('orphan')]}),g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[a],after:[a],dependencyKnowledgeComplete:true}),options));assert.equal(g.sourceCompleteness.state,'INDETERMINATE');});
test('open HIGH finding yields CORRECTION_REQUIRED',()=>{const a=src('A','same'),f=unwrap(createSemanticFinding({findingId:'FH',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'RULE',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:a.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),c=reviewedContext({before:[a],after:[a],findings:[f]});assert.equal(c.verdict.verdict,'CORRECTION_REQUIRED');});
test('materialization truncation outranks ordinary gates',()=>{const a=src('A','same'),c=reviewedContext({before:[a],after:[a],materializationState:'TRUNCATED'});assert.equal(c.verdict.verdict,'TRUNCATED');});
test('prior HEDS branch mix is BLOCKED',()=>{const a=src('A','same'),prior=reviewedContext({before:[a],after:[a]}).verdict,g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[a],after:[a],priorVerdict:{...prior,candidateIdentityDigest:sha('wrong')}}),options));assert.equal(g.baselineContinuity.state,'BLOCKED');});
test('unreviewed M25 unresolved subject prevents approval',()=>{const a=src('A','same'),g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[a],after:[a],proof:proofHandoff({unresolved:['MISSING']}),allKnownSubjectIds:['A','MISSING']}),options));assert.equal(g.proofInvalidation.state,'FAIL');});
test('HIR26 detects inventory tamper by recomputing review',()=>{const a=src('A','same'),c=reviewedContext({before:[a],after:[a]}),r=unwrap(verifyHedsVerdictCapsule({...c.verdict,inventoryDigest:sha('wrong')},c.input,options));assert.equal(r.valid,false);});
test('HIR26 detects verdict-label tamper',()=>{const a=src('A','same'),c=reviewedContext({before:[a],after:[a]}),r=unwrap(verifyHedsVerdictCapsule({...c.verdict,verdict:'BLOCKED'},c.input,options));assert.equal(r.valid,false);assert.equal(r.expectedVerdict,'APPROVED');});
test('HFR26 rejects silent disappearance',()=>{const prior=unwrap(createSemanticFinding({findingId:'FOPEN',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),r=createHedsFindingRegister([],[prior],options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'HFR26_SILENT_DISAPPEARANCE');});
test('HFR26 accepts exact resolution lineage',()=>{const prior=unwrap(createSemanticFinding({findingId:'FOPEN',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),resolved=unwrap(createSemanticFinding({findingId:'FDONE',subjectId:'A',severity:'HIGH',state:'RESOLVED',ruleId:'R',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('fixed'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:prior.findingDigest},options));assert.deepEqual(unwrap(createHedsFindingRegister([resolved],[prior],options)).retainedFindingDigests,[prior.findingDigest]);});
test('HFR26 detects tampered finding payload',()=>{const f=unwrap(createSemanticFinding({findingId:'F',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),r=createHedsFindingRegister([{...f,severity:'LOW'}],[],options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'HFR26_FINDING_TAMPERED');});
test('HTR26 binds predecessor/successor frontier',()=>{const a=src('A','old'),aa=src('A','new'),first=reviewedContext({before:[a],after:[a]}).verdict,second=reviewedContext({before:[a],after:[aa]}).verdict,r=unwrap(createHedsTransitionReceipt(first,second,[],['A'],['UPSTREAM_CHANGE'],options));assert.equal(r.predecessorFrontierDigest,first.frontierDigest);assert.equal(r.successorFrontierDigest,second.frontierDigest);});
test('HRG26 duplicate replay is visible/idempotent',()=>{const a=src('A','same'),v=reviewedContext({before:[a],after:[a]}).verdict,g=unwrap(createHedsReplayGuard([v,v],options));assert.equal(g.state,'CLEAR');assert.deepEqual(g.duplicateVerdictDigests,[v.verdictDigest]);});
test('HRG26 detects same-id divergent semantics',()=>{const a=src('A','same'),v=reviewedContext({before:[a],after:[a]}).verdict,g=unwrap(createHedsReplayGuard([v,{...v,semanticDigest:sha('other'),verdictDigest:sha('other-v')}],options));assert.equal(g.state,'CONFLICT');});
test('HRG26 bounded history reports TRUNCATED',()=>{const a=src('A','same'),v=reviewedContext({before:[a],after:[a]}).verdict,g=unwrap(createHedsReplayGuard([v,{...v,verdictId:'V2',semanticDigest:sha('s2'),verdictDigest:sha('v2')}],{...options,maxHistory:1}));assert.equal(g.state,'TRUNCATED');assert.equal(g.totalCount,2);});
test('HSW26 detects divergent successors under same recomputed predecessor identity',()=>{const a=src('A','same'),v=reviewedContext({before:[a],after:[a]}).verdict,p=unwrap(createHedsPredecessorReviewIdentity(v,options)),x={...v,verdictId:'VX',semanticDigest:sha('different'),verdictDigest:sha('different-v')};assert.equal(unwrap(createHedsSplitBrainWitness(p,[v,x],options)).splitBrain,true);});
test('HSW26 rejects branch-mixed successors',()=>{const a=src('A','same'),v=reviewedContext({before:[a],after:[a]}).verdict,p=unwrap(createHedsPredecessorReviewIdentity(v,options)),x={...v,candidateIdentityDigest:sha('other'),semanticDigest:sha('different'),verdictDigest:sha('different-v')},r=createHedsSplitBrainWitness(p,[v,x],options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'HSW26_BRANCH_MIX');});
test('DHH26 recomputes review and carries source/delta/impact identities',()=>{const a=src('A','old'),aa=src('A','new'),c=reviewedContext({before:[a],after:[aa]}),h=unwrap(createDownstreamHedsHandoff(c.verdict,c.input,'M27_ASSURANCE',options));assert.equal(h.sourceManifestDigest,c.verdict.sourceManifestDigest);assert.equal(h.inventoryDigest,c.verdict.inventoryDigest);assert.equal(h.frontierDigest,c.verdict.frontierDigest);assert.deepEqual(h.impactedSubjectIds,['A']);assert.equal(h.mayDecideAssurance,false);assert.equal(h.maySelectTests,false);});
test('DHH26 refuses tampered verdict',()=>{const a=src('A','same'),c=reviewedContext({before:[a],after:[a]}),r=createDownstreamHedsHandoff({...c.verdict,semanticDigest:sha('tamper')},c.input,'M28_TEST_IMPACT',options);assert.equal(r.ok,false);});
test('safe review is deterministic under source permutation',()=>{const a=src('A','a'),b=src('B','b'),x=reviewedContext({before:[a,b],after:[a,b]}),y=reviewedContext({before:[b,a],after:[b,a]});assert.equal(x.gates.gateSetDigest,y.gates.gateSetDigest);assert.equal(x.verdict.semanticDigest,y.verdict.semanticDigest);});
