import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{
 M26_MECHANISMS,createHedsIntent,createHedsAuthorityBoundary,createSemanticStateIdentity,sealReviewSourceProjection,createCrossLineageWitness,createDeltaChangeInventory,
 createSourceCoverageManifest,createSourceBindingGate,createAuthorityConsistencyGate,createDependencyProjection,verifyM25ProofHandoff,createSourceGapWitness,createMixAndMatchWitness,
 createSemanticDeltaMatrix,createImpactFrontier,createReviewCandidateIndex,createReviewCarryForward,createSemanticFinding,createDeltaTraceReceipt,evaluateReviewGates,
 createHedsVerdictCapsule,verifyHedsVerdictCapsule,createHedsFindingRegister,createHedsTransitionReceipt,createHedsReplayGuard,createHedsSplitBrainWitness,createDownstreamHedsHandoff
}from'../packages/heds-delta-review/dist/public.js';

const raw=s=>createHash('sha256').update(s).digest('hex');
const sha=s=>`sha256:${raw(s)}`;
const digest={algorithm:'sha256',digest:raw};
const options={digest,maxUnits:10000,maxHistory:100};
function stable(v){if(v===null||typeof v==='number'||typeof v==='boolean'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;const r=v;return`{${Object.keys(r).sort().map(k=>`${JSON.stringify(k)}:${stable(r[k])}`).join(',')}}`;}
const domain=(kind,payload)=>sha(`${kind}\n${stable(payload)}`);
const unwrap=r=>{assert.equal(r.ok,true,r.ok?'':JSON.stringify(r.diagnostics));return r.value;};
const src=(subject,semantic,{owner='OWNER',source='SOURCE',validity=`valid-${subject}`,deps=[]}={})=>unwrap(sealReviewSourceProjection({subjectId:subject,sourceId:source,ownerId:owner,projectId:'PROJECT',lineageId:'LINEAGE',semanticDigest:sha(semantic),validityBindingDigest:sha(validity),dependencyDigests:deps},options));
function states(b,c){const bi=unwrap(createSemanticStateIdentity('BASE','PROJECT','LINEAGE',sha('coverage-b'),b.map(x=>x.projectionDigest),options));const ci=unwrap(createSemanticStateIdentity('CANDIDATE','PROJECT','LINEAGE',sha('coverage-c'),c.map(x=>x.projectionDigest),options));return[bi,ci];}
function cleanGates(findings=[]){return unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:true,findingClosureValid:true,authorityConflict:false,truncated:false,indeterminate:false,findings},options));}
function verdict(gates=cleanGates(),findings=[]){return unwrap(createHedsVerdictCapsule('VERDICT','PROJECT','LINEAGE',sha('base'),sha('cand'),sha('policy'),sha('inventory'),sha('frontier'),gates,findings,options));}
function validProofHandoff(){const body={owner:'M25_PROOF',consumer:'M26_DELTA_REVIEW',snapshotDigest:sha('snap'),proofStates:[{claimId:'CLAIM',state:'PROVEN'}],selectedSupportIds:['SUPPORT'],proofFingerprintDigests:[sha('fp')],invalidationVectorDigest:sha('inv'),unresolvedClaimIds:[],mayPerformDeltaReview:false,mayDecideAssurance:false,mayMutateDod:false,mayCalculateProgress:false,mayPromoteCheckpoint:false};return{...body,handoffDigest:domain('DPH25',body)};}

test('all 40 frozen M26 mechanisms are unique',()=>{assert.equal(M26_MECHANISMS.length,40);assert.equal(new Set(M26_MECHANISMS).size,40);});
test('HEDS intent is deterministic under requested-subject permutation',()=>{const a=unwrap(createHedsIntent({intentId:'I',projectId:'PROJECT',lineageId:'LINEAGE',baselineId:'BASE',candidateId:'CANDIDATE',reviewPolicyDigest:sha('p'),requestedSubjectIds:['B','A'],purpose:'semantic-review'},options));const b=unwrap(createHedsIntent({...a,requestedSubjectIds:['A','B']},options));assert.equal(a.intentDigest,b.intentDigest);});
test('authority boundary denies upstream and downstream authority',()=>{const i=unwrap(createHedsIntent({intentId:'I',projectId:'PROJECT',lineageId:'LINEAGE',baselineId:'BASE',candidateId:'CANDIDATE',reviewPolicyDigest:sha('p'),requestedSubjectIds:['A'],purpose:'review'},options));const b=unwrap(createHedsAuthorityBoundary(i,options));assert.equal(b.authority,'SEMANTIC_DELTA_REVIEW_ONLY');assert.equal(b.mayDecideProof,false);assert.equal(b.mayDecideAssurance,false);assert.equal(b.maySelectTests,false);assert.equal(b.mayOperateGit,false);});
test('source projection canonicalizes dependency order',()=>{const a=src('A','a',{deps:[sha('z'),sha('x')]});const b=src('A','a',{deps:[sha('x'),sha('z')]});assert.equal(a.projectionDigest,b.projectionDigest);});
test('unchanged semantics are explicitly UNCHANGED',()=>{const a=src('A','same');const[b,c]=states([a],[a]);const inv=unwrap(createDeltaChangeInventory(b,c,[a],[a],true,options));assert.equal(inv.entries[0].changeClass,'UNCHANGED');});
test('semantic mutation is MODIFIED and binds old/new dependency identities',()=>{const before=src('A','old'),after=src('A','new');const[b,c]=states([before],[after]);const e=unwrap(createDeltaChangeInventory(b,c,[before],[after],true,options)).entries[0];assert.equal(e.changeClass,'MODIFIED');assert.equal(e.semanticChanged,true);assert.ok(e.changedDependencyDigests.includes(before.semanticDigest));assert.ok(e.changedDependencyDigests.includes(after.semanticDigest));});
test('authority-only mutation remains a semantic review delta',()=>{const before=src('A','same',{owner:'OWNER1'}),after=src('A','same',{owner:'OWNER2'});const[b,c]=states([before],[after]);const e=unwrap(createDeltaChangeInventory(b,c,[before],[after],true,options)).entries[0];assert.equal(e.changeClass,'MODIFIED');assert.equal(e.semanticChanged,false);assert.equal(e.authorityChanged,true);});
test('complete coverage can prove removal',()=>{const a=src('A','a');const[b,c]=states([a],[]);assert.equal(unwrap(createDeltaChangeInventory(b,c,[a],[],true,options)).entries[0].changeClass,'REMOVED');});
test('partial coverage cannot fabricate removal',()=>{const a=src('A','a');const[b,c]=states([a],[]);const r=createDeltaChangeInventory(b,c,[a],[],false,options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DCI26_REMOVAL_UNPROVEN');});
test('cross-lineage comparison fails closed',()=>{const a=src('A','a');const b=unwrap(createSemanticStateIdentity('BASE','PROJECT','LINEAGE',sha('c'),[a.projectionDigest],options));const c=unwrap(createSemanticStateIdentity('CANDIDATE','PROJECT','OTHER',sha('d'),[a.projectionDigest],options));assert.equal(unwrap(createCrossLineageWitness(b,c,options)).comparisonAdmissible,false);assert.equal(createDeltaChangeInventory(b,c,[a],[a],true,options).ok,false);});
test('source coverage manifest preserves complete versus partial truth',()=>{const a=src('A','a');const m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'COMPLETE','PARTIAL',false,options));assert.equal(m.baselineCoverage,'COMPLETE');assert.equal(m.candidateCoverage,'PARTIAL');assert.equal(m.dependencyKnowledgeComplete,false);});
test('source binding gate exposes stale validity',()=>{const a=src('A','a');const g=unwrap(createSourceBindingGate([a],[{subjectId:'A',validityBindingDigest:sha('other')}],options));assert.equal(g.valid,false);assert.deepEqual(g.staleSubjectIds,['A']);});
test('authority consistency gate preserves divergent owners',()=>{const a=src('A','a',{owner:'ONE'}),b=src('A','a',{owner:'TWO'});const g=unwrap(createAuthorityConsistencyGate([a,b],options));assert.equal(g.valid,false);assert.deepEqual(g.conflictingSubjectIds,['A']);});
test('dependency projection is deterministic',()=>{const dep=sha('dep');const a=src('A','a',{deps:[dep]}),b=src('B','b',{deps:[dep]});const x=unwrap(createDependencyProjection([b,a],true,options));const y=unwrap(createDependencyProjection([a,b],true,options));assert.equal(x.projectionDigest,y.projectionDigest);assert.deepEqual(x.reverseEdges[0].subjectIds,['A','B']);});
test('current M25 DPH25 handoff is independently verified',()=>{const g=unwrap(verifyM25ProofHandoff(validProofHandoff(),options));assert.equal(g.valid,true);assert.equal(g.snapshotDigest,sha('snap'));});
test('forged M25 DPH25 digest cannot enter HEDS proof context',()=>{const h={...validProofHandoff(),handoffDigest:sha('forged')};assert.equal(unwrap(verifyM25ProofHandoff(h,options)).valid,false);});
test('wrong DPH25 consumer fails closed',()=>{const h={...validProofHandoff(),consumer:'M27_ASSURANCE'};const r=verifyM25ProofHandoff(h,options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'PBG26_OWNER_CONSUMER_INVALID');});
test('source gap witness exposes incomplete coverage and dependency knowledge',()=>{const a=src('A','a');const m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'COMPLETE','PARTIAL',false,options));const b=unwrap(createSourceBindingGate([a],[{subjectId:'A',validityBindingDigest:a.validityBindingDigest}],options));const g=unwrap(createAuthorityConsistencyGate([a],options));const w=unwrap(createSourceGapWitness(['B'],b,g,m,options));assert.equal(w.incompleteCoverage,true);assert.equal(w.incompleteDependencies,true);assert.deepEqual(w.missingSubjectIds,['B']);});
test('mix-and-match witness is explicit',()=>{assert.equal(unwrap(createMixAndMatchWitness(false,true,false,options)).mixed,true);});
test('proof invalidation marks unchanged subject directly impacted',()=>{const a=src('A','same');const[b,c]=states([a],[a]);const inv=unwrap(createDeltaChangeInventory(b,c,[a],[a],true,options));const m=unwrap(createSemanticDeltaMatrix(inv,['A'],options));assert.equal(m.rows[0].proofInvalidated,true);});
test('semantic digest change propagates to declared dependent',()=>{const beforeA=src('A','old'),afterA=src('A','new');const beforeB=src('B','b',{deps:[beforeA.semanticDigest]}),afterB=src('B','b',{deps:[beforeA.semanticDigest]});const[b,c]=states([beforeA,beforeB],[afterA,afterB]);const inv=unwrap(createDeltaChangeInventory(b,c,[beforeA,beforeB],[afterA,afterB],true,options));const matrix=unwrap(createSemanticDeltaMatrix(inv,[],options));const deps=unwrap(createDependencyProjection([afterA,afterB],true,options));const f=unwrap(createImpactFrontier(matrix,inv,deps,['A','B'],options));assert.deepEqual(f.directlyImpactedSubjectIds,['A']);assert.deepEqual(f.transitivelyImpactedSubjectIds,['A','B']);});
test('incomplete dependency knowledge widens impact to all known subjects',()=>{const a=src('A','old'),aa=src('A','new'),b=src('B','b');const[s1,s2]=states([a,b],[aa,b]);const inv=unwrap(createDeltaChangeInventory(s1,s2,[a,b],[aa,b],true,options));const matrix=unwrap(createSemanticDeltaMatrix(inv,[],options));const deps=unwrap(createDependencyProjection([aa,b],false,options));const f=unwrap(createImpactFrontier(matrix,inv,deps,['A','B','C'],options));assert.equal(f.widened,true);assert.deepEqual(f.transitivelyImpactedSubjectIds,['A','B','C']);});
test('review candidate index is deterministic',()=>{const a=src('A','old'),aa=src('A','new');const[b,c]=states([a],[aa]);const inv=unwrap(createDeltaChangeInventory(b,c,[a],[aa],true,options));const matrix=unwrap(createSemanticDeltaMatrix(inv,[],options));const deps=unwrap(createDependencyProjection([aa],true,options));const f=unwrap(createImpactFrontier(matrix,inv,deps,['A'],options));const x=unwrap(createReviewCandidateIndex(inv,f,[aa],[sha('z'),sha('a')],options));const y=unwrap(createReviewCandidateIndex(inv,f,[aa],[sha('a'),sha('z')],options));assert.equal(x.indexDigest,y.indexDigest);});
test('first review cannot fabricate carry-forward reuse',()=>{const a=src('A','a');const r=unwrap(createReviewCarryForward('A',a,[sha('fp')],sha('policy'),null,null,options));assert.equal(r.state,'REVIEW');});
test('exact compatible review can be reused',()=>{const a=src('A','a');const first=unwrap(createReviewCarryForward('A',a,[sha('fp')],sha('policy'),sha('prior'),sha('wrong'),options));const second=unwrap(createReviewCarryForward('A',a,[sha('fp')],sha('policy'),sha('prior'),first.currentCompatibilityDigest,options));assert.equal(second.state,'REUSE');});
test('source authority change invalidates review carry-forward',()=>{const a=src('A','a',{owner:'ONE'}),b=src('A','a',{owner:'TWO'});const old=unwrap(createReviewCarryForward('A',a,[sha('fp')],sha('policy'),sha('prior'),sha('x'),options));const next=unwrap(createReviewCarryForward('A',b,[sha('fp')],sha('policy'),sha('prior'),old.currentCompatibilityDigest,options));assert.equal(next.state,'REVIEW');assert.notEqual(next.currentCompatibilityDigest,old.currentCompatibilityDigest);});
test('HIGH finding is immutable and owner-bound by digest',()=>{const f=unwrap(createSemanticFinding({findingId:'F1',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'RULE',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[sha('p')],supersedesFindingDigest:null},options));assert.equal(f.severity,'HIGH');assert.ok(Object.isFrozen(f));});
test('resolved finding requires exact lineage reference',()=>{const r=createSemanticFinding({findingId:'F2',subjectId:'A',severity:'HIGH',state:'RESOLVED',ruleId:'RULE',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'SFC26_LINEAGE_REQUIRED');});
test('delta trace binds inventory frontier candidates and findings',()=>{const a=src('A','old'),aa=src('A','new');const[b,c]=states([a],[aa]);const inv=unwrap(createDeltaChangeInventory(b,c,[a],[aa],true,options));const matrix=unwrap(createSemanticDeltaMatrix(inv,[],options));const dep=unwrap(createDependencyProjection([aa],true,options));const front=unwrap(createImpactFrontier(matrix,inv,dep,['A'],options));const idx=unwrap(createReviewCandidateIndex(inv,front,[aa],[],options));const t=unwrap(createDeltaTraceReceipt(b.semanticDigest,c.semanticDigest,inv,front,idx,[],options));assert.equal(t.inventoryDigest,inv.inventoryDigest);});
test('open HIGH finding prevents verdict admission',()=>{const f=unwrap(createSemanticFinding({findingId:'FH',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options));const g=unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:true,findingClosureValid:true,authorityConflict:false,truncated:false,indeterminate:false,findings:[f]},options));assert.equal(g.zeroHighCritical.state,'FAIL');assert.equal(g.verdictAdmission.state,'FAIL');});
test('truncation outranks ordinary correction gate',()=>{const g=unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:false,findingClosureValid:true,authorityConflict:false,truncated:true,indeterminate:false,findings:[]},options));assert.equal(g.verdictAdmission.state,'TRUNCATED');});
test('authority conflict yields BLOCKED',()=>{const g=unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:true,findingClosureValid:true,authorityConflict:true,truncated:false,indeterminate:false,findings:[]},options));assert.equal(g.verdictAdmission.state,'BLOCKED');});
test('missing mandatory source truth yields INDETERMINATE',()=>{const g=unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:false,allInvalidatedProofItemsReviewed:true,findingClosureValid:true,authorityConflict:false,truncated:false,indeterminate:false,findings:[]},options));assert.equal(g.verdictAdmission.state,'INDETERMINATE');});
test('clean complete review gate set is PASS',()=>{assert.equal(cleanGates().verdictAdmission.state,'PASS');});
test('clean gates produce APPROVED HEDS verdict',()=>{assert.equal(verdict().verdict,'APPROVED');});
test('failed semantic gate produces CORRECTION_REQUIRED',()=>{const g=unwrap(evaluateReviewGates({baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:false,findingClosureValid:true,authorityConflict:false,truncated:false,indeterminate:false,findings:[]},options));assert.equal(verdict(g).verdict,'CORRECTION_REQUIRED');});
test('integrity receipt detects verdict label tampering',()=>{const g=cleanGates(),v=verdict(g);const forged={...v,verdict:'BLOCKED'};assert.equal(unwrap(verifyHedsVerdictCapsule(forged,g,[],options)).valid,false);});
test('finding register detects divergent stable finding id',()=>{const a=unwrap(createSemanticFinding({findingId:'F',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options));const b=unwrap(createSemanticFinding({...a,severity:'HIGH'},options));const r=createHedsFindingRegister([a,b],[],options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'HFR26_FINDING_CONFLICT');});
test('transition receipt preserves predecessor successor and changed subjects',()=>{const a=verdict(),b={...a,verdictId:'VERDICT2',verdictDigest:sha('v2'),semanticDigest:sha('s2')};const r=unwrap(createHedsTransitionReceipt(a,b,[],['A'],['UPSTREAM_CHANGE'],options));assert.equal(r.predecessorVerdictDigest,a.verdictDigest);assert.deepEqual(r.changedSubjectIds,['A']);});
test('replay guard exposes duplicate verdict replay',()=>{const v=verdict();const g=unwrap(createHedsReplayGuard([v,v],options));assert.equal(g.state,'CLEAR');assert.deepEqual(g.duplicateVerdictDigests,[v.verdictDigest]);});
test('replay guard exposes same-id divergent semantic history',()=>{const v=verdict();const other={...v,semanticDigest:sha('other'),verdictDigest:sha('other-v')};const g=unwrap(createHedsReplayGuard([v,other],options));assert.equal(g.state,'CONFLICT');assert.deepEqual(g.conflictingVerdictIds,['VERDICT']);});
test('bounded history reports TRUNCATED instead of complete review history',()=>{const v=verdict();const g=unwrap(createHedsReplayGuard([v,{...v,verdictId:'V2',verdictDigest:sha('2'),semanticDigest:sha('s2')}],{...options,maxHistory:1}));assert.equal(g.state,'TRUNCATED');assert.equal(g.historyTruncated,true);assert.equal(g.processedCount,1);assert.equal(g.totalCount,2);});
test('split-brain witness exposes divergent successors',()=>{const v=verdict(),x={...v,verdictId:'X',semanticDigest:sha('x'),verdictDigest:sha('vx')};const w=unwrap(createHedsSplitBrainWitness(sha('pred'),[v,x],options));assert.equal(w.splitBrain,true);});
test('downstream handoff is read-only and authority-denying',()=>{const g=cleanGates(),v=verdict(g);const h=unwrap(createDownstreamHedsHandoff(v,g,[],['A'],'M27_ASSURANCE',options));assert.equal(h.owner,'M26_HEDS');assert.equal(h.mayDecideAssurance,false);assert.equal(h.maySelectTests,false);assert.equal(h.mayOperateGit,false);});
test('tampered verdict cannot create downstream handoff',()=>{const g=cleanGates(),v=verdict(g);const r=createDownstreamHedsHandoff({...v,semanticDigest:sha('tamper')},g,[],['A'],'M28_TEST_IMPACT',options);assert.equal(r.ok,false);});
test('cancellation and digest capability fail closed',()=>{const r=createHedsIntent({intentId:'I',projectId:'PROJECT',lineageId:'LINEAGE',baselineId:'BASE',candidateId:'CANDIDATE',reviewPolicyDigest:sha('p'),requestedSubjectIds:['A'],purpose:'review'},{digest:{algorithm:'sha256',digest:()=>{throw new Error('secret');}}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_CAPABILITY_FAILED');});
