import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{createHedsIntent,sealReviewSourceProjection,createSourceCoverageManifest,createDeltaChangeInventory,createBaselineSemanticIdentity,createCandidateSemanticIdentity,createDependencyProjection,createSemanticFinding,createHedsFindingRegister}from'../packages/heds-delta-review/dist/public.js';
const raw=s=>createHash('sha256').update(s).digest('hex'),sha=s=>`sha256:${raw(s)}`,digest={algorithm:'sha256',digest:raw},options={digest,maxUnits:100,maxHistory:100};
const unwrap=r=>{assert.equal(r.ok,true,r.ok?'':JSON.stringify(r.diagnostics));return r.value;};
const source=(subject,semantic,deps=[])=>unwrap(sealReviewSourceProjection({subjectId:subject,sourceId:`SOURCE-${subject}`,ownerId:'OWNER',projectId:'PROJECT',lineageId:'LINEAGE',semanticDigest:sha(semantic),validityBindingDigest:sha(`valid-${subject}`),dependencyDigests:deps},options));
function intentBase(){const a=source('A','a'),baseline=unwrap(createBaselineSemanticIdentity('BASE','PROJECT','LINEAGE',sha('cb'),[a.projectionDigest],options)),candidate=unwrap(createCandidateSemanticIdentity('CANDIDATE','PROJECT','LINEAGE',sha('cc'),[a.projectionDigest],options));return{intentId:'I',projectId:'PROJECT',lineageId:'LINEAGE',baselineId:'BASE',candidateId:'CANDIDATE',baselineIdentityDigest:baseline.semanticDigest,candidateIdentityDigest:candidate.semanticDigest,reviewPolicyDigest:sha('policy'),requestedSubjectIds:['A'],purpose:'review'};}

test('HIC26 ignores undeclared JavaScript fields when sealing intent',()=>{const base=intentBase(),a=unwrap(createHedsIntent(base,options)),b=unwrap(createHedsIntent({...base,attackerControlled:'noise'},options));assert.equal(a.intentDigest,b.intentDigest);assert.equal('attackerControlled'in b,false);});
test('RSP26 ignores undeclared provider transport fields',()=>{const base={subjectId:'A',sourceId:'SOURCE-A',ownerId:'OWNER',projectId:'PROJECT',lineageId:'LINEAGE',semanticDigest:sha('semantic'),validityBindingDigest:sha('valid'),dependencyDigests:[]},a=unwrap(sealReviewSourceProjection(base,options)),b=unwrap(sealReviewSourceProjection({...base,transportNoise:{provider:'x'}},options));assert.equal(a.projectionDigest,b.projectionDigest);assert.equal('transportNoise'in b,false);});
test('SFC26 ignores undeclared presentation fields',()=>{const base={findingId:'F1',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'RULE',beforeSemanticDigest:sha('before'),afterSemanticDigest:sha('after'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},a=unwrap(createSemanticFinding(base,options)),b=unwrap(createSemanticFinding({...base,uiLabel:'forged'},options));assert.equal(a.findingDigest,b.findingDigest);assert.equal('uiLabel'in b,false);});
test('source traversal enforces one-over-budget fail closed',()=>{const sources=[source('A','a'),source('B','b')],r=createSourceCoverageManifest('PROJECT','LINEAGE',sources,sources,'COMPLETE','COMPLETE',true,{digest,maxUnits:3});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_BUDGET_EXCEEDED');});
test('source traversal honors cancellation',()=>{const a=source('A','a'),r=createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'COMPLETE','COMPLETE',true,{digest,maxUnits:100,cancellation:{isCancelled:()=>true}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_CANCELLED');});
test('delta inventory traversal enforces budget',()=>{const a=source('A','a'),b=source('B','b'),base=unwrap(createBaselineSemanticIdentity('BASE','PROJECT','LINEAGE',sha('cb'),[a.projectionDigest,b.projectionDigest],options)),cand=unwrap(createCandidateSemanticIdentity('CANDIDATE','PROJECT','LINEAGE',sha('cc'),[a.projectionDigest,b.projectionDigest],options)),r=createDeltaChangeInventory(base,cand,[a,b],[a,b],true,{digest,maxUnits:2});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_BUDGET_EXCEEDED');});
test('dependency traversal enforces budget',()=>{const dep=sha('known'),a=source('A','a',[dep]),b=source('B','b',[dep]),r=createDependencyProjection([a,b],true,{digest,maxUnits:1},[dep]);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_BUDGET_EXCEEDED');});
test('finding history traversal enforces budget',()=>{const a=unwrap(createSemanticFinding({findingId:'F1',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),b=unwrap(createSemanticFinding({findingId:'F2',subjectId:'B',severity:'LOW',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),r=createHedsFindingRegister([a,b],[],{digest,maxUnits:1});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'OPERATION_BUDGET_EXCEEDED');});
test('unknown finding resolution lineage fails closed',()=>{const resolved=unwrap(createSemanticFinding({findingId:'FRES',subjectId:'A',severity:'HIGH',state:'RESOLVED',ruleId:'R',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:sha('unknown')},options)),r=createHedsFindingRegister([resolved],[],options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'HFR26_LINEAGE_UNKNOWN');});
test('injected digest capability failure is typed and secret-free',()=>{const r=createHedsIntent(intentBase(),{digest:{algorithm:'sha256',digest:()=>{throw new Error('secret-value');}}});assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'DIGEST_CAPABILITY_FAILED');assert.equal(JSON.stringify(r).includes('secret-value'),false);});
