import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{
 M26_MECHANISMS,createHedsIntent,createHedsAuthorityBoundary,createBaselineSemanticIdentity,createCandidateSemanticIdentity,sealReviewSourceProjection,createCrossLineageWitness,createDeltaChangeInventory,
 createSourceCoverageManifest,createSourceBindingGate,createAuthorityConsistencyGate,createDependencyProjection,verifyM25ProofHandoff,createValidityContextGate,createSourceGapWitness,createMixAndMatchWitness,
 createSemanticDeltaMatrix,createImpactFrontier,createOwnershipReviewFilter,createReviewCandidateIndex,createReviewCarryForward,createSemanticFinding,createDeltaTraceReceipt,
 evaluateReviewGates,evaluateArtifactReview,evaluateArtifactReviewGates,createHedsFindingRegister,createHedsVerdictCapsule,verifyHedsVerdictCapsule,createHedsTransitionReceipt,createHedsReplayGuard,createHedsPredecessorReviewIdentity,createHedsSplitBrainWitness,createDownstreamHedsHandoff
}from'../packages/heds-delta-review/dist/public.js';

const raw=s=>createHash('sha256').update(s).digest('hex');
const sha=s=>`sha256:${raw(s)}`;
const digest={algorithm:'sha256',digest:raw};
const options={digest,maxUnits:20000,maxHistory:1000};
const unwrap=r=>{assert.equal(r.ok,true,r.ok?'':JSON.stringify(r.diagnostics));return r.value;};
function stable(v){if(v===null||typeof v==='number'||typeof v==='boolean'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`;}
function src(subject,semantic,{owner='OWNER',sourceId=`SOURCE-${subject}`,validity=`valid-${subject}`,deps=[],project='PROJECT',lineage='LINEAGE'}={}){return unwrap(sealReviewSourceProjection({subjectId:subject,sourceId,ownerId:owner,projectId:project,lineageId:lineage,semanticDigest:sha(semantic),validityBindingDigest:sha(validity),dependencyDigests:deps},options));}
const current=p=>({subjectId:p.subjectId,sourceId:p.sourceId,ownerId:p.ownerId,projectId:p.projectId,lineageId:p.lineageId,semanticDigest:p.semanticDigest,validityBindingDigest:p.validityBindingDigest});
function proofHandoff({fingerprints=[sha('fp')],unresolved=[],consumer='M26_DELTA_REVIEW',tamper=false}={}){const base={owner:'M25_PROOF',consumer,snapshotDigest:sha('snap'),proofStates:unresolved.map(claimId=>({claimId,state:'UNPROVEN'})),selectedSupportIds:[],proofFingerprintDigests:fingerprints,invalidationVectorDigest:sha('iv'),unresolvedClaimIds:unresolved,mayPerformDeltaReview:false,mayDecideAssurance:false,mayMutateDod:false,mayCalculateProgress:false,mayPromoteCheckpoint:false};const handoffDigest=`sha256:${raw(`DPH25\n${stable(base)}`)}`;return{...base,handoffDigest:tamper?sha('forged'):handoffDigest};}
function coverage(items){return sha(`coverage:${[...items.map(x=>x.projectionDigest)].sort().join('|')}`);}
function identities(before,after,{project='PROJECT',lineage='LINEAGE',baselineId='BASE',candidateId='CANDIDATE'}={}){return{baseline:unwrap(createBaselineSemanticIdentity(baselineId,project,lineage,coverage(before),before.map(x=>x.projectionDigest),options)),candidate:unwrap(createCandidateSemanticIdentity(candidateId,project,lineage,coverage(after),after.map(x=>x.projectionDigest),options))};}
function intentFor(ids,subjects,{project='PROJECT',lineage='LINEAGE',intentId='INTENT'}={}){return unwrap(createHedsIntent({intentId,projectId:project,lineageId:lineage,baselineId:ids.baseline.stateId,candidateId:ids.candidate.stateId,baselineIdentityDigest:ids.baseline.semanticDigest,candidateIdentityDigest:ids.candidate.semanticDigest,reviewPolicyDigest:sha('policy'),requestedSubjectIds:subjects,purpose:'semantic-review'},options));}
function artifactInput({before,after,proof=null,findings=[],priorFindings=[],priorVerdict=null,baselineCoverage='COMPLETE',candidateCoverage='COMPLETE',dependencyKnowledgeComplete=true,knownExternalDependencyDigests=[],allKnownSubjectIds=null,materializationState='COMPLETE',currentSourceIdentities=null,baselineId='BASE',candidateId='CANDIDATE'}){const ids=identities(before,after,{baselineId,candidateId}),subjects=[...new Set([...before,...after].map(x=>x.subjectId))],intent=intentFor(ids,subjects);return{intent,...ids,baselineSources:before,candidateSources:after,currentSourceIdentities:currentSourceIdentities??after.map(current),baselineCoverage,candidateCoverage,dependencyKnowledgeComplete,knownExternalDependencyDigests,proofHandoff:proof,allKnownSubjectIds:allKnownSubjectIds??subjects,priorFindings,findings,priorVerdict,materializationState};}
function cleanContext(verdictId='VERDICT'){const a=src('A','old'),b=src('A','new'),input=artifactInput({before:[a],after:[b]}),review=unwrap(evaluateArtifactReview(input,options)),verdict=unwrap(createHedsVerdictCapsule(verdictId,input,options));return{a,b,input,review,verdict};}
function lowFindingContext(verdictId='VERDICT'){const a=src('A','old'),b=src('A','new'),f=unwrap(createSemanticFinding({findingId:'LOW-F',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'R-LOW',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:b.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),input=artifactInput({before:[a],after:[b],findings:[f]}),verdict=unwrap(createHedsVerdictCapsule(verdictId,input,options));return{a,b,f,input,verdict};}

// S01 — identity and delta
test('registry covers exactly 40 frozen M26 mechanisms',()=>{assert.equal(M26_MECHANISMS.length,40);assert.equal(new Set(M26_MECHANISMS).size,40);});
test('HIC26 binds exact identities and canonical subject order',()=>{const a=src('A','a'),b=src('B','b'),ids=identities([a,b],[a,b]);assert.equal(intentFor(ids,['B','A']).intentDigest,intentFor(ids,['A','B']).intentDigest);const moved={baseline:ids.baseline,candidate:{...ids.candidate,semanticDigest:sha('other')}};assert.notEqual(intentFor(moved,['A','B']).intentDigest,intentFor(ids,['A','B']).intentDigest);});
test('HAB26 denies adjacent authorities',()=>{const a=src('A','a'),ids=identities([a],[a]),b=unwrap(createHedsAuthorityBoundary(intentFor(ids,['A']),options));assert.equal(b.authority,'SEMANTIC_DELTA_REVIEW_ONLY');assert.equal(b.mayValidateEvidence,false);assert.equal(b.mayDecideProof,false);assert.equal(b.mayDecideAssurance,false);assert.equal(b.maySelectTests,false);assert.equal(b.mayOperateGit,false);assert.equal(b.mayPromoteCheckpoint,false);});
test('BSI26 and CSI26 share role-neutral semantic identity while HIC preserves roles',()=>{const a=src('A','a'),b=unwrap(createBaselineSemanticIdentity('BASE-X','PROJECT','LINEAGE',coverage([a]),[a.projectionDigest],options)),c=unwrap(createCandidateSemanticIdentity('CAND-X','PROJECT','LINEAGE',coverage([a]),[a.projectionDigest],options)),i=intentFor({baseline:b,candidate:c},['A']);assert.equal(b.semanticDigest,c.semanticDigest);assert.equal(i.baselineId,'BASE-X');assert.equal(i.candidateId,'CAND-X');});
test('RSP26 dependency order is canonical',()=>{assert.equal(src('A','x',{deps:[sha('z'),sha('a')]}).projectionDigest,src('A','x',{deps:[sha('a'),sha('z')]}).projectionDigest);});
test('SDL/DCI classify semantic authority add remove and unchanged changes',()=>{const old=src('A','old'),same=src('A','old'),mod=src('A','new'),owner=src('A','old',{owner:'OTHER'}),added=src('B','b');let ids=identities([old],[same]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[old],[same],true,options)).entries[0].changeClass,'UNCHANGED');ids=identities([old],[mod]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[old],[mod],true,options)).entries[0].changeClass,'MODIFIED');ids=identities([],[added]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[],[added],true,options)).entries[0].changeClass,'ADDED');ids=identities([old],[]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[old],[],true,options)).entries[0].changeClass,'REMOVED');assert.equal(createDeltaChangeInventory(ids.baseline,ids.candidate,[old],[],false,options).ok,false);ids=identities([old],[owner]);assert.equal(unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[old],[owner],true,options)).entries[0].authorityChanged,true);});
test('XLG26 rejects cross-lineage comparison',()=>{const a=src('A','a'),b=src('A','b',{lineage:'OTHER'}),base=unwrap(createBaselineSemanticIdentity('BASE','PROJECT','LINEAGE',coverage([a]),[a.projectionDigest],options)),cand=unwrap(createCandidateSemanticIdentity('CANDIDATE','PROJECT','OTHER',coverage([b]),[b.projectionDigest],options)),w=unwrap(createCrossLineageWitness(base,cand,options));assert.equal(w.comparisonAdmissible,false);assert.equal(createDeltaChangeInventory(base,cand,[a],[b],true,options).ok,false);});

// S02 — source and proof trust
test('SCM26 rejects duplicate subject and tampered projection',()=>{const a=src('A','a');assert.equal(createSourceCoverageManifest('PROJECT','LINEAGE',[a,a],[a],'COMPLETE','COMPLETE',true,options).ok,false);assert.equal(createSourceCoverageManifest('PROJECT','LINEAGE',[{...a,semanticDigest:sha('forged')}],[a],'COMPLETE','COMPLETE',true,options).ok,false);});
test('SBG26 verifies projection and current source identity',()=>{const a=src('A','a');assert.equal(unwrap(createSourceBindingGate([a],[current(a)],options)).valid,true);assert.equal(unwrap(createSourceBindingGate([a],[{...current(a),ownerId:'ATTACKER'}],options)).valid,false);assert.equal(unwrap(createSourceBindingGate([a],[{...current(a),semanticDigest:sha('other')}],options)).valid,false);const r=createSourceBindingGate([{...a,validityBindingDigest:sha('forged')}],[current(a)],options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'SBG26_PROJECTION_TAMPERED');});
test('ACG26 preserves divergent authority',()=>{const a=src('A','a',{owner:'ONE'}),b=src('A','a',{owner:'TWO'});assert.equal(unwrap(createAuthorityConsistencyGate([a,b],options)).valid,false);});
test('DPG26 detects orphan dependency and accepts declared external endpoint',()=>{const dep=sha('external'),a=src('A','a',{deps:[dep]});let p=unwrap(createDependencyProjection([a],true,options));assert.equal(p.complete,false);assert.deepEqual(p.unknownDependencyDigests,[dep]);p=unwrap(createDependencyProjection([a],true,options,[dep]));assert.equal(p.complete,true);});
test('PBG26 independently verifies M25 handoff and consumer',()=>{assert.equal(unwrap(verifyM25ProofHandoff(null,options)).valid,true);const p=unwrap(verifyM25ProofHandoff(proofHandoff(),options));assert.equal(p.valid,true);assert.deepEqual(p.proofFingerprintDigests,[sha('fp')]);assert.equal(unwrap(verifyM25ProofHandoff(proofHandoff({tamper:true}),options)).valid,false);assert.equal(verifyM25ProofHandoff(proofHandoff({consumer:'M27_ASSURANCE'}),options).ok,false);});
test('VCG26 binds HIC to exact baseline candidate and manifest',()=>{const a=src('A','a'),ids=identities([a],[a]),intent=intentFor(ids,['A']),m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'COMPLETE','COMPLETE',true,options)),b=unwrap(createSourceBindingGate([a],[current(a)],options));assert.equal(unwrap(createValidityContextGate(intent,ids.baseline,ids.candidate,m,b,options)).valid,true);const forged=unwrap(createHedsIntent({...intent,baselineIdentityDigest:sha('wrong')},options)),v=unwrap(createValidityContextGate(forged,ids.baseline,ids.candidate,m,b,options));assert.equal(v.valid,false);assert.ok(v.reasonCodes.includes('BASELINE_INTENT_DIGEST_MISMATCH'));});
test('SGW26 and MMW26 preserve gaps and mix',()=>{const a=src('A','a'),m=unwrap(createSourceCoverageManifest('PROJECT','LINEAGE',[a],[a],'PARTIAL','COMPLETE',false,options)),b=unwrap(createSourceBindingGate([a],[current(a)],options)),g=unwrap(createAuthorityConsistencyGate([a],options)),w=unwrap(createSourceGapWitness(['B'],b,g,m,options));assert.equal(w.incompleteCoverage,true);assert.equal(w.incompleteDependencies,true);assert.equal(unwrap(createMixAndMatchWitness(false,true,false,options)).mixed,true);});

// S03 — semantic review
test('SDM26 widens proof invalidation without confusing claim IDs with subjects',()=>{const a=src('A','a'),b=src('B','b'),ids=identities([a,b],[a,b]),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a,b],[a,b],true,options)),proof=unwrap(verifyM25ProofHandoff(proofHandoff({unresolved:['CLAIM-123']}),options)),m=unwrap(createSemanticDeltaMatrix(inv,proof,options));assert.deepEqual(m.rows.map(r=>r.proofInvalidated),[true,true]);});
test('IFP26 propagates semantic impact and de-duplicates diamond',()=>{const oldA=src('A','old'),newA=src('A','new'),b=src('B','b',{deps:[oldA.semanticDigest]}),c=src('C','c',{deps:[oldA.semanticDigest]}),ids=identities([oldA,b,c],[newA,b,c]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[oldA,b,c],[newA,b,c],true,options)),matrix=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([oldA,newA,b,c],true,options)),front=unwrap(createImpactFrontier(matrix,inv,dep,['A','B','C'],options));assert.deepEqual(front.transitivelyImpactedSubjectIds,['A','B','C']);});
test('IFP26 widens when dependency knowledge incomplete',()=>{const oldA=src('A','old'),newA=src('A','new'),z=src('Z','z'),ids=identities([oldA,z],[newA,z]),proof=unwrap(verifyM25ProofHandoff(null,options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[oldA,z],[newA,z],true,options)),matrix=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([oldA,newA,z],false,options)),front=unwrap(createImpactFrontier(matrix,inv,dep,['A','Z'],options));assert.equal(front.widened,true);assert.deepEqual(front.transitivelyImpactedSubjectIds,['A','Z']);});
test('ORF26 routes changed dimensions but cannot decide owner truth',()=>{const a=src('A','old',{owner:'DOMAIN'}),b=src('A','new',{owner:'DOMAIN'}),ids=identities([a],[b]),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[b],true,options)),f=unwrap(createOwnershipReviewFilter(inv,[a],[b],options));assert.equal(f.routes[0].ownerId,'DOMAIN');assert.equal(f.routes[0].mayDecideOwnerTruth,false);assert.ok(f.routes[0].dimensions.includes('SEMANTIC_PAYLOAD'));});
test('RCI26 is proof-fingerprint bound',()=>{const a=src('A','old'),b=src('A','new'),ids=identities([a],[b]),proof=unwrap(verifyM25ProofHandoff(proofHandoff(),options)),inv=unwrap(createDeltaChangeInventory(ids.baseline,ids.candidate,[a],[b],true,options)),matrix=unwrap(createSemanticDeltaMatrix(inv,proof,options)),dep=unwrap(createDependencyProjection([a,b],true,options)),front=unwrap(createImpactFrontier(matrix,inv,dep,['A'],options)),i=unwrap(createReviewCandidateIndex(inv,front,[b],proof,options));assert.deepEqual(i.candidates[0].proofFingerprintDigests,[sha('fp')]);});
test('RCF26 reuses only exact compatible source proof and policy',()=>{const a=src('A','a',{owner:'ONE'}),proof=unwrap(verifyM25ProofHandoff(proofHandoff(),options)),first=unwrap(createReviewCarryForward('A',a,proof,sha('policy'),sha('prior'),sha('wrong'),options)),second=unwrap(createReviewCarryForward('A',a,proof,sha('policy'),sha('prior'),first.currentCompatibilityDigest,options)),moved=src('A','a',{owner:'TWO'}),third=unwrap(createReviewCarryForward('A',moved,proof,sha('policy'),sha('prior'),first.currentCompatibilityDigest,options));assert.equal(first.state,'REVIEW');assert.equal(second.state,'REUSE');assert.equal(third.state,'REVIEW');});
test('SFC26 seals finding and requires resolution lineage',()=>{const f=unwrap(createSemanticFinding({findingId:'F1',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options));assert.ok(Object.isFrozen(f));assert.equal(createSemanticFinding({...f,state:'RESOLVED',supersedesFindingDigest:null},options).ok,false);});
test('DTR26 binds state inventory frontier candidates and findings',()=>{const{a,b,input,review}=cleanContext(),f=unwrap(createSemanticFinding({findingId:'F',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'R',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:b.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),r=unwrap(createDeltaTraceReceipt(input.baseline.semanticDigest,input.candidate.semanticDigest,review.inventory,review.frontier,review.candidates,[f],options));assert.equal(r.inventoryDigest,review.inventory.inventoryDigest);assert.deepEqual(r.findingDigests,[f.findingDigest]);});

// S04 — fail-closed gates
test('diagnostic VAG precedence is truncated blocked indeterminate fail pass',()=>{const base={baselineContinuity:true,sourceCoverageSufficient:true,allInvalidatedProofItemsReviewed:true,findingClosureValid:true,authorityConflict:false,truncated:false,indeterminate:false,findings:[]};assert.equal(unwrap(evaluateReviewGates(base,options)).verdictAdmission.state,'PASS');assert.equal(unwrap(evaluateReviewGates({...base,allInvalidatedProofItemsReviewed:false},options)).verdictAdmission.state,'FAIL');assert.equal(unwrap(evaluateReviewGates({...base,sourceCoverageSufficient:false},options)).verdictAdmission.state,'INDETERMINATE');assert.equal(unwrap(evaluateReviewGates({...base,authorityConflict:true},options)).verdictAdmission.state,'BLOCKED');assert.equal(unwrap(evaluateReviewGates({...base,truncated:true,authorityConflict:true},options)).verdictAdmission.state,'TRUNCATED');});
test('clean artifact-bound review passes with all internal bindings',()=>{const{review}=cleanContext();assert.equal(review.gates.artifactBound,true);assert.equal(review.gates.verdictAdmission.state,'PASS');for(const k of ['sourceManifestDigest','validityContextGateDigest','proofBindingGateDigest','dependencyProjectionDigest','findingRegisterDigest','inventoryDigest','matrixDigest','frontierDigest','candidateIndexDigest','ownershipFilterDigest'])assert.ok(review.gates[k]);});
test('partial coverage orphan dependency and unresolved M25 proof cannot approve',()=>{const a=src('A','old'),b=src('A','new');let g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[a],after:[b],candidateCoverage:'PARTIAL'}),options));assert.equal(g.verdictAdmission.state,'INDETERMINATE');const dep=sha('unknown'),x=src('A','old',{deps:[dep]}),y=src('A','new',{deps:[dep]});g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[x],after:[y]}),options));assert.equal(g.verdictAdmission.state,'INDETERMINATE');g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[a],after:[b],proof:proofHandoff({unresolved:['CLAIM-9']})}),options));assert.equal(g.proofInvalidation.state,'FAIL');assert.ok(g.proofInvalidation.reasonCodes.includes('M25_UNRESOLVED_PROOF_CLAIMS'));});
test('open HIGH finding prevents approval',()=>{const a=src('A','old'),b=src('A','new'),f=unwrap(createSemanticFinding({findingId:'HIGH1',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:b.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),g=unwrap(evaluateArtifactReviewGates(artifactInput({before:[a],after:[b],findings:[f]}),options));assert.equal(g.zeroHighCritical.state,'FAIL');assert.equal(g.verdictAdmission.state,'FAIL');});
test('tampered HIC and wrong baseline binding fail closed',()=>{const a=src('A','old'),b=src('A','new'),input=artifactInput({before:[a],after:[b]}),r=evaluateArtifactReview({...input,intent:{...input.intent,intentDigest:sha('forged')}},options);assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'VAG26_INTENT_TAMPERED');const wrong=unwrap(createHedsIntent({...input.intent,baselineIdentityDigest:sha('wrong')},options)),g=unwrap(evaluateArtifactReviewGates({...input,intent:wrong},options));assert.equal(g.verdictAdmission.state,'BLOCKED');});
test('prior verdict from another branch blocks continuity',()=>{const first=cleanContext(),nextA=src('A','next'),next=artifactInput({before:first.input.candidateSources,after:[nextA],priorVerdict:{...first.verdict,candidateIdentityDigest:sha('branch')}}),g=unwrap(evaluateArtifactReviewGates(next,options));assert.equal(g.baselineContinuity.state,'BLOCKED');});

// S05 — findings, verdict, history, handoff
test('HFR26 rejects silent disappearance conflicting ID and payload tamper',()=>{const f=unwrap(createSemanticFinding({findingId:'F',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options));assert.equal(createHedsFindingRegister([],[f],options).ok,false);const divergent=unwrap(createSemanticFinding({findingId:'F',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'R2',beforeSemanticDigest:null,afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options));assert.equal(createHedsFindingRegister([f,divergent],[],options).ok,false);assert.equal(createHedsFindingRegister([{...f,severity:'LOW'}],[],options).ok,false);});
test('HFR26 accepts explicit resolution lineage and retains predecessor',()=>{const f=unwrap(createSemanticFinding({findingId:'F',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:null,afterSemanticDigest:sha('a'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),resolved=unwrap(createSemanticFinding({findingId:'F-R',subjectId:'A',severity:'HIGH',state:'RESOLVED',ruleId:'R',beforeSemanticDigest:sha('a'),afterSemanticDigest:sha('b'),evidenceDigests:[],proofDigests:[],supersedesFindingDigest:f.findingDigest},options)),reg=unwrap(createHedsFindingRegister([resolved],[f],options));assert.deepEqual(reg.retainedFindingDigests,[f.findingDigest]);});
test('HVC26 approval is recomputed and HIR26 detects tamper',()=>{const{input,verdict}=cleanContext();assert.equal(verdict.verdict,'APPROVED');assert.equal(unwrap(verifyHedsVerdictCapsule(verdict,input,options)).valid,true);assert.equal(unwrap(verifyHedsVerdictCapsule({...verdict,verdict:'BLOCKED'},input,options)).valid,false);assert.equal(unwrap(verifyHedsVerdictCapsule({...verdict,semanticDigest:sha('tamper')},input,options)).valid,false);});
test('HVC26 cannot approve open HIGH or unresolved M25 claim',()=>{const a=src('A','old'),b=src('A','new'),f=unwrap(createSemanticFinding({findingId:'H',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:b.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options));assert.equal(unwrap(createHedsVerdictCapsule('VH',artifactInput({before:[a],after:[b],findings:[f]}),options)).verdict,'CORRECTION_REQUIRED');assert.equal(unwrap(createHedsVerdictCapsule('VP',artifactInput({before:[a],after:[b],proof:proofHandoff({unresolved:['CLAIM-X']})}),options)).verdict,'CORRECTION_REQUIRED');});
test('HVC26 is permutation deterministic for equivalent finding order',()=>{const a=src('A','old'),b=src('A','new'),f1=unwrap(createSemanticFinding({findingId:'F1',subjectId:'A',severity:'LOW',state:'OPEN',ruleId:'R1',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:b.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),f2=unwrap(createSemanticFinding({findingId:'F2',subjectId:'A',severity:'INFO',state:'OPEN',ruleId:'R2',beforeSemanticDigest:a.semanticDigest,afterSemanticDigest:b.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),v1=unwrap(createHedsVerdictCapsule('VP',artifactInput({before:[a],after:[b],findings:[f1,f2]}),options)),v2=unwrap(createHedsVerdictCapsule('VP',artifactInput({before:[a],after:[b],findings:[f2,f1]}),options));assert.equal(v1.semanticDigest,v2.semanticDigest);assert.equal(v1.verdictDigest,v2.verdictDigest);});
test('HTR26 accepts exact continuity, receipts verdict regression and rejects branch mix',()=>{const first=cleanContext(),c=src('A','newer'),high=unwrap(createSemanticFinding({findingId:'REG-HIGH',subjectId:'A',severity:'HIGH',state:'OPEN',ruleId:'R-REG',beforeSemanticDigest:first.b.semanticDigest,afterSemanticDigest:c.semanticDigest,evidenceDigests:[],proofDigests:[],supersedesFindingDigest:null},options)),nextInput=artifactInput({before:first.input.candidateSources,after:[c],priorVerdict:first.verdict,findings:[high],baselineId:'NEXT-BASE',candidateId:'NEXT-CAND'}),next=unwrap(createHedsVerdictCapsule('V2',nextInput,options));assert.equal(first.verdict.verdict,'APPROVED');assert.equal(next.verdict,'CORRECTION_REQUIRED');assert.equal(next.baselineIdentityDigest,first.verdict.candidateIdentityDigest);const r=unwrap(createHedsTransitionReceipt(first.verdict,next,[high],['A'],['UPSTREAM_CHANGE'],options));assert.equal(r.predecessorVerdictDigest,first.verdict.verdictDigest);assert.equal(r.successorFrontierDigest,next.frontierDigest);assert.deepEqual(r.changedFindingDigests,[high.findingDigest]);const branchBefore=src('A','branch'),branchInput=artifactInput({before:[branchBefore],after:[c],baselineId:'BAD-BASE',candidateId:'BAD-CAND'}),branchVerdict=unwrap(createHedsVerdictCapsule('VB',branchInput,options)),bad=createHedsTransitionReceipt(first.verdict,branchVerdict,[],['A'],['UPSTREAM_CHANGE'],options);assert.equal(bad.ok,false);assert.equal(bad.diagnostics[0].code,'HTR26_PREDECESSOR_MISMATCH');});
test('HTR26 HRG26 and HSW26 reject tampered serialized verdict envelopes',()=>{const{verdict}=cleanContext(),tampered={...verdict,semanticDigest:sha('fake'),verdictDigest:sha('fake-v')};for(const r of [createHedsTransitionReceipt(verdict,tampered,[],['A'],['CHANGE'],options),createHedsReplayGuard([verdict,tampered],options),createHedsPredecessorReviewIdentity(tampered,options)]){assert.equal(r.ok,false);assert.equal(r.diagnostics[0].code,'HVC26_ENVELOPE_TAMPERED');}});
test('HRG26 exposes authenticated duplicate conflict and truncation',()=>{const first=cleanContext('VERDICT'),variant=lowFindingContext('VERDICT');let g=unwrap(createHedsReplayGuard([first.verdict,first.verdict],options));assert.deepEqual(g.duplicateVerdictDigests,[first.verdict.verdictDigest]);g=unwrap(createHedsReplayGuard([first.verdict,variant.verdict],options));assert.equal(g.state,'CONFLICT');const second=lowFindingContext('V2');g=unwrap(createHedsReplayGuard([first.verdict,second.verdict],{...options,maxHistory:1}));assert.equal(g.state,'TRUNCATED');});
test('HSW26 detects authenticated split brain and rejects branch mix',()=>{const first=cleanContext('V1'),variant=lowFindingContext('V2'),pred=unwrap(createHedsPredecessorReviewIdentity(first.verdict,options)),w=unwrap(createHedsSplitBrainWitness(pred,[first.verdict,variant.verdict],options));assert.equal(w.splitBrain,true);const otherA=src('A','other'),otherInput=artifactInput({before:[src('A','old')],after:[otherA]}),other=unwrap(createHedsVerdictCapsule('V3',otherInput,options)),mixed=createHedsSplitBrainWitness(pred,[first.verdict,other],options);assert.equal(mixed.ok,false);assert.equal(mixed.diagnostics[0].code,'HSW26_BRANCH_MIX');});
test('DHH26 is verified read-only and rejects tampered verdict',()=>{const{input,verdict}=cleanContext(),h=unwrap(createDownstreamHedsHandoff(verdict,input,'M28_TEST_IMPACT',options));assert.equal(h.owner,'M26_HEDS');assert.equal(h.consumer,'M28_TEST_IMPACT');assert.equal(h.mayDecideAssurance,false);assert.equal(h.maySelectTests,false);assert.equal(h.mayOperateGit,false);assert.deepEqual(h.impactedSubjectIds,['A']);assert.equal(createDownstreamHedsHandoff({...verdict,semanticDigest:sha('tamper')},input,'M27_ASSURANCE',options).ok,false);});
