import test from'node:test';
import assert from'node:assert/strict';
import{createHash}from'node:crypto';
import{M27_MECHANISMS,createAssuranceIntentCapsule,createAssuranceRiskProfile,classifyAssurance,createAssuranceBudgetGuard,compileAssuranceRequirementProfile,createProofHandoffGate,createHedsHandoffGate,createEvidenceAdmissionGate,createHedsSemanticGate,createAssuranceFinding,evaluateAssurance,createAssuranceVerdictCapsule,verifyAssuranceVerdictCapsule,createAssuranceTransitionReceipt,createAssuranceReopenWitness,createAssuranceReplayGuard,createAssuranceSplitBrainWitness,createDownstreamAssuranceHandoff}from'../packages/assurance-pipeline/dist/public.js';

const digest={algorithm:'sha256',digest(input){return createHash('sha256').update(input).digest('hex')}};
const baseOptions={digest,maxUnits:10000,maxHistory:100};
const cp=(a,b)=>a<b?-1:a>b?1:0;
function stable(v){if(v===null||typeof v==='number'||typeof v==='boolean'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;const r=v;return`{${Object.keys(r).sort(cp).map(k=>`${JSON.stringify(k)}:${stable(r[k])}`).join(',')}}`;}
const seal=(kind,payload)=>`sha256:${createHash('sha256').update(`${kind}\n${stable(payload)}`).digest('hex')}`;
const sha=x=>`sha256:${createHash('sha256').update(x).digest('hex')}`;
const su=a=>[...new Set(a)].sort(cp);
const allCategories=['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT','INTEGRATION','E2E','PLATFORM_RUNTIME','SECURITY','RECOVERY_INTEGRITY','EXACT_CANDIDATE_SWEEP','INDEPENDENT_REVIEW','STARTUP_PURITY','BOUNDED_CANCELLABLE'];

function intent(requestedClass='MAX_ASSURANCE',candidateSemanticDigest=sha('candidate')){const r=createAssuranceIntentCapsule({intentId:'INTENT-27',projectId:'PROJECT',lineageId:'LINEAGE',workOrderId:'GBS-WO-M27-001',candidateId:'CANDIDATE',candidateSemanticDigest,configDigest:sha('config'),runtimeDigest:sha('runtime'),toolchainDigest:sha('toolchain'),requestedClass,purpose:'assure candidate',policyDigest:sha('policy')},baseOptions);assert.equal(r.ok,true);return r.value;}
function signal(signalId,kind,level='LOW',truthState='KNOWN'){return{signalId,kind,ownerId:'RISK_OWNER',truthState,level,semanticDigest:sha(`${signalId}:${kind}:${level}:${truthState}`)}}
function risk(i=intent(),signals=[signal('R1','CRITICAL_DATA_INTEGRITY','CRITICAL')],complete=true){const r=createAssuranceRiskProfile(i.projectId,i.lineageId,i.candidateSemanticDigest,i.policyDigest,signals,complete,baseOptions);assert.equal(r.ok,true);return r.value;}
function riskOptions(r){return{...baseOptions,trustedRiskProfileDigests:[r.profileDigest],trustedUpstreamContextBindingDigests:[],trustedValidationBindingDigests:[]};}
function evidenceHandoff(label=''){const body={owner:'M24_EVIDENCE',consumer:'M27_ASSURANCE',manifestDigest:sha(`m24-manifest${label}`),acceptedEvidenceDigests:[sha(`ev-pass${label}`)],rejectedEvidenceDigests:[],staleEvidenceDigests:[],conflictEvidenceDigests:[],unknownEvidenceDigests:[],claimMappingDigest:sha(`claims${label}`),receiptSetDigest:sha(`receipts${label}`),unresolvedClaimIds:[],mayComputeProof:false,mayDecideAssurance:false};return{...body,handoffDigest:seal('DPC24',body)}}
function proofHandoff(label=''){const body={owner:'M25_PROOF',consumer:'M27_ASSURANCE',snapshotDigest:sha(`m25-snapshot${label}`),proofStates:[{claimId:'CLAIM-1',state:'PROVEN'}],selectedSupportIds:['SUPPORT-1'],proofFingerprintDigests:[sha(`proof-fp${label}`)],invalidationVectorDigest:null,unresolvedClaimIds:[],mayPerformDeltaReview:false,mayDecideAssurance:false,mayMutateDod:false,mayCalculateProgress:false,mayPromoteCheckpoint:false};return{...body,handoffDigest:seal('DPH25',body)}}
function hedsHandoff(verdict='APPROVED',blockingFindingDigests=[],label=''){const body={owner:'M26_HEDS',consumer:'M27_ASSURANCE',verdictDigest:sha(`heds-verdict-${verdict}${label}`),semanticDigest:sha(`heds-sem-${verdict}${label}`),verdict,sourceManifestDigest:sha(`source-manifest${label}`),inventoryDigest:sha(`inventory${label}`),frontierDigest:sha(`frontier${label}`),gateSetDigest:sha(`heds-gates${label}`),impactedSubjectIds:['SUBJECT-1'],blockingFindingDigests:su(blockingFindingDigests),reviewPolicyDigest:sha(`review-policy${label}`),mayDecideAssurance:false,maySelectTests:false,mayOperateGit:false,mayPromoteCheckpoint:false};return{...body,handoffDigest:seal('DHH26',body)}}
function validationBinding(i,e,findings=[],over={}){const categoryEvidence=su(allCategories).filter(c=>!(over.omitCategories??[]).includes(c)).map(category=>({category,evidenceDigests:su(over.evidenceByCategory?.[category]??e.acceptedEvidenceDigests)}));const body={owner:'EXTERNAL_CANONICAL',projectId:over.projectId??i.projectId,lineageId:over.lineageId??i.lineageId,candidateSemanticDigest:over.candidateSemanticDigest??i.candidateSemanticDigest,configDigest:over.configDigest??i.configDigest,runtimeDigest:over.runtimeDigest??i.runtimeDigest,toolchainDigest:over.toolchainDigest??i.toolchainDigest,policyDigest:over.policyDigest??i.policyDigest,categoryEvidence,platformIds:su(over.platformIds??['ubuntu','windows','macos']),reachedLadderLevel:over.reachedLadderLevel??5,materializationState:over.materializationState??'COMPLETE',truncated:over.truncated??false,indeterminate:over.indeterminate??false,findingSetDigest:seal('ASSURANCE_FINDING_SET27',{findingDigests:su(findings.map(f=>f.findingDigest))})};return{...body,bindingDigest:seal('M27_VALIDATION_BINDING_V1',body)}}
function upstreamBinding(i,r,e,p,h,v,over={}){const body={owner:'EXTERNAL_CANONICAL',projectId:over.projectId??i.projectId,lineageId:over.lineageId??i.lineageId,candidateSemanticDigest:over.candidateSemanticDigest??i.candidateSemanticDigest,configDigest:over.configDigest??i.configDigest,runtimeDigest:over.runtimeDigest??i.runtimeDigest,toolchainDigest:over.toolchainDigest??i.toolchainDigest,policyDigest:over.policyDigest??i.policyDigest,riskProfileDigest:over.riskProfileDigest??r.profileDigest,dodDigest:over.dodDigest??sha('dod'),dodCriterionIds:su(over.dodCriterionIds??['DOD-1']),evidenceHandoffDigest:over.evidenceHandoffDigest??e.handoffDigest,proofHandoffDigest:over.proofHandoffDigest??p.handoffDigest,hedsHandoffDigest:over.hedsHandoffDigest??h.handoffDigest,validationBindingDigest:over.validationBindingDigest??v.bindingDigest};return{...body,bindingDigest:seal('M27_UPSTREAM_CONTEXT_BINDING_V1',body)}}
function trustedOptions(r,u,v){return{...baseOptions,trustedRiskProfileDigests:[r.profileDigest],trustedUpstreamContextBindingDigests:[u.bindingDigest],trustedValidationBindingDigests:[v.bindingDigest]};}
function context(over={}){const i=over.intent??intent(over.requestedClass??'MAX_ASSURANCE',over.candidateSemanticDigest??sha('candidate'));const r=over.riskProfile??risk(i,over.signals??[signal('R1','CRITICAL_DATA_INTEGRITY','CRITICAL')],over.riskComplete??true);const e=over.evidenceHandoff??evidenceHandoff(over.evidenceLabel??'');const p=over.proofHandoff??proofHandoff(over.proofLabel??'');const h=over.hedsHandoff??hedsHandoff(over.hedsVerdict??'APPROVED',over.hedsBlocking??[],over.hedsLabel??'');const findings=over.findings??[];const v=validationBinding(i,e,findings,over.validation??{});const u=upstreamBinding(i,r,e,p,h,v,over.upstream??{});const options=trustedOptions(r,u,v);const input={intent:i,riskProfile:r,currentPolicyDigest:over.currentPolicyDigest??i.policyDigest,budget:over.budget??{tokenBudget:1,searchBudget:1,fileBudget:1,testBudget:1,latencyBudgetMs:1},dodDigest:over.dodDigest??sha('dod'),dodCriterionIds:over.dodCriterionIds??['DOD-1'],evidenceHandoff:e,currentEvidenceManifestDigest:over.currentEvidenceManifestDigest??e.manifestDigest,proofHandoff:p,currentProofSnapshotDigest:over.currentProofSnapshotDigest??p.snapshotDigest,hedsHandoff:h,currentHedsVerdictDigest:over.currentHedsVerdictDigest??h.verdictDigest,findings,validationBinding:v,upstreamContextBinding:u,validation:{reachedLadderLevel:v.reachedLadderLevel,completedCategories:allCategories,acceptedEvidenceDigests:e.acceptedEvidenceDigests,exactCandidateSemanticDigest:i.candidateSemanticDigest,configDigest:i.configDigest,runtimeDigest:i.runtimeDigest,toolchainDigest:i.toolchainDigest,platformIds:v.platformIds,securitySatisfied:true,independentReviewSatisfied:true,truncated:v.truncated,indeterminate:v.indeterminate},materializationState:v.materializationState};return{input,options,intent:i,risk:r,evidence:e,proof:p,heds:h,validation:v,upstream:u};}

test('registry freezes all 40 M27 mechanisms',()=>{assert.equal(M27_MECHANISMS.length,40);assert.equal(new Set(M27_MECHANISMS).size,40)});
test('critical minority signal forces MAX_ASSURANCE despite STANDARD request',()=>{const i=intent('STANDARD'),r=risk(i,[signal('LOW-1','PUBLIC_CONTRACT','LOW'),signal('CRIT-1','SIGNING','CRITICAL'),signal('LOW-2','CROSS_BOUNDARY_STATE','LOW')]);const c=classifyAssurance(i,r,riskOptions(r));assert.equal(c.ok,true);assert.equal(c.value.derivedFloor,'MAX_ASSURANCE');assert.equal(c.value.effectiveClass,'MAX_ASSURANCE');assert.deepEqual(c.value.highSignalIds,['CRIT-1'])});
test('caller may raise but never lower assurance',()=>{const i=intent('MAX_ASSURANCE'),r=risk(i,[signal('LOW','PUBLIC_CONTRACT','LOW')]);const c=classifyAssurance(i,r,riskOptions(r));assert.equal(c.ok,true);assert.equal(c.value.derivedFloor,'STANDARD_PLUS');assert.equal(c.value.effectiveClass,'MAX_ASSURANCE')});
test('unknown risk truth is fail-closed and cannot default STANDARD',()=>{const i=intent('STANDARD'),r=risk(i,[signal('U','UNCERTAINTY','LOW','UNKNOWN')],false);const c=classifyAssurance(i,r,riskOptions(r));assert.equal(c.ok,true);assert.equal(c.value.state,'INDETERMINATE');assert.ok(['HIGH_ASSURANCE','MAX_ASSURANCE'].includes(c.value.effectiveClass))});
test('budget pressure never downgrades classification',()=>{const i=intent(),r=risk(i),c=classifyAssurance(i,r,riskOptions(r));assert.equal(c.ok,true);const g=createAssuranceBudgetGuard(c.value,{tokenBudget:0,searchBudget:0,fileBudget:0,testBudget:0,latencyBudgetMs:0},baseOptions);assert.equal(g.ok,true);assert.equal(g.value.assurancePreserved,true)});
test('requirement matrix is monotonic',()=>{const low=intent('STANDARD'),lr=risk(low,[signal('L','UNCERTAINTY','NONE')]),lc=classifyAssurance(low,lr,riskOptions(lr));assert.equal(lc.ok,true);const lp=compileAssuranceRequirementProfile(low,lc.value,baseOptions);assert.equal(lp.ok,true);const high=intent('MAX_ASSURANCE'),hr=risk(high,[signal('L','UNCERTAINTY','NONE')]),hc=classifyAssurance(high,hr,riskOptions(hr));assert.equal(hc.ok,true);const hp=compileAssuranceRequirementProfile(high,hc.value,baseOptions);assert.equal(hp.ok,true);for(const x of lp.value.requiredCategories)assert.ok(hp.value.requiredCategories.includes(x))});
test('DPH25 handoff tamper is rejected',()=>{const p=proofHandoff(),bad={...p,unresolvedClaimIds:['FORGED']};const g=createProofHandoffGate(bad,p.snapshotDigest,baseOptions);assert.equal(g.ok,true);assert.equal(g.value.valid,false)});
test('stale DPH25 snapshot is explicit',()=>{const p=proofHandoff(),g=createProofHandoffGate(p,sha('new-snapshot'),baseOptions);assert.equal(g.ok,true);assert.equal(g.value.current,false);assert.equal(g.value.valid,false)});
test('DHH26 correction remains corrective failure',()=>{const h=hedsHandoff('CORRECTION_REQUIRED'),hg=createHedsHandoffGate(h,h.verdictDigest,baseOptions);assert.equal(hg.ok,true);const sg=createHedsSemanticGate(hg.value,baseOptions);assert.equal(sg.ok,true);assert.equal(sg.value.state,'FAIL')});
test('DPC24 handoff tamper is rejected',()=>{const e=evidenceHandoff(),bad={...e,acceptedEvidenceDigests:[sha('forged')]};const g=createEvidenceAdmissionGate(bad,e.manifestDigest,baseOptions);assert.equal(g.ok,true);assert.equal(g.value.valid,false)});
test('fully current MAX_ASSURANCE context is ASSURED',()=>{const c=context(),ev=evaluateAssurance(c.input,c.options);assert.equal(ev.ok,true);assert.equal(ev.value.classification.effectiveClass,'MAX_ASSURANCE');assert.equal(ev.value.gates.verdictAdmission.state,'PASS');const v=createAssuranceVerdictCapsule('VERDICT-1',c.input,null,c.options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'ASSURED')});
test('untrusted risk profile is rejected before classification can assure',()=>{const c=context(),o={...c.options,trustedRiskProfileDigests:[sha('other-risk')]};const ev=evaluateAssurance(c.input,o);assert.equal(ev.ok,false);assert.equal(ev.diagnostics[0].code,'ACF27_RISK_PROFILE_UNTRUSTED')});
test('cross-context valid handoff splice is blocked by external binding',()=>{const c=context(),foreign=proofHandoff('-foreign');c.input.proofHandoff=foreign;c.input.currentProofSnapshotDigest=foreign.snapshotDigest;const ev=evaluateAssurance(c.input,c.options);assert.equal(ev.ok,true);assert.equal(ev.value.gates.verdictAdmission.state,'BLOCKED');const v=createAssuranceVerdictCapsule('VERDICT-SPLICE',c.input,null,c.options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'BLOCKED')});
test('stopping below ladder floor cannot assure',()=>{const c=context({validation:{reachedLadderLevel:3}}),v=createAssuranceVerdictCapsule('VERDICT-LADDER',c.input,null,c.options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'CORRECTION_REQUIRED')});
test('missing exact-candidate evidence cannot assure',()=>{const c=context({validation:{omitCategories:['EXACT_CANDIDATE_SWEEP']}}),v=createAssuranceVerdictCapsule('VERDICT-STALE',c.input,null,c.options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'CORRECTION_REQUIRED')});
test('stale proof truth yields INDETERMINATE rather than fake correction',()=>{const p=proofHandoff(),c=context({proofHandoff:p,currentProofSnapshotDigest:sha('new-proof')}),v=createAssuranceVerdictCapsule('VERDICT-PROOF-STALE',c.input,null,c.options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'INDETERMINATE')});
test('open HIGH finding blocks assurance with finding-set binding',()=>{const f=createAssuranceFinding({findingId:'F-HIGH',severity:'HIGH',state:'OPEN',ownerId:'SECURITY_OWNER',ruleId:'RULE-HIGH',sourceDigest:sha('finding-source'),supersedesFindingDigest:null},baseOptions);assert.equal(f.ok,true);const c=context({findings:[f.value]}),v=createAssuranceVerdictCapsule('VERDICT-BLOCKED',c.input,null,c.options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'BLOCKED')});
test('verdict integrity detects field tamper',()=>{const c=context(),v=createAssuranceVerdictCapsule('VERDICT-TAMPER',c.input,null,c.options);assert.equal(v.ok,true);const check=verifyAssuranceVerdictCapsule({...v.value,assuranceClass:'STANDARD'},c.input,c.options);assert.equal(check.ok,true);assert.equal(check.value.valid,false)});
test('replay guard records exact duplicate without conflict',()=>{const c=context(),v=createAssuranceVerdictCapsule('VERDICT-REPLAY',c.input,null,c.options);assert.equal(v.ok,true);const g=createAssuranceReplayGuard([v.value,v.value],baseOptions);assert.equal(g.ok,true);assert.equal(g.value.state,'CLEAR');assert.equal(g.value.duplicateVerdictDigests.length,1)});
test('silent regression from ASSURED requires reopen witness',()=>{const a=context(),pred=createAssuranceVerdictCapsule('VERDICT-PRED',a.input,null,a.options);assert.equal(pred.ok,true);const b=context({validation:{reachedLadderLevel:0}}),succ=createAssuranceVerdictCapsule('VERDICT-SUCC',b.input,pred.value.verdictDigest,b.options);assert.equal(succ.ok,true);const tr=createAssuranceTransitionReceipt(pred.value,succ.value,null,['VALIDATION'],['REGRESSION'],baseOptions);assert.equal(tr.ok,false);const rw=createAssuranceReopenWitness(pred.value,succ.value.candidateSemanticDigest,'ASSURANCE_OWNER',sha('authorization'),['REVALIDATION_REQUIRED'],baseOptions);assert.equal(rw.ok,true);const tr2=createAssuranceTransitionReceipt(pred.value,succ.value,rw.value,['VALIDATION'],['REGRESSION'],baseOptions);assert.equal(tr2.ok,true)});
test('split brain detects divergent authenticated successors',()=>{const a=context(),pred=createAssuranceVerdictCapsule('PRED',a.input,null,a.options);assert.equal(pred.ok,true);const same=context(),va=createAssuranceVerdictCapsule('A',same.input,pred.value.verdictDigest,same.options);assert.equal(va.ok,true);const different=context({validation:{reachedLadderLevel:0}}),vb=createAssuranceVerdictCapsule('B',different.input,pred.value.verdictDigest,different.options);assert.equal(vb.ok,true);const w=createAssuranceSplitBrainWitness(pred.value.verdictDigest,[va.value,vb.value],baseOptions);assert.equal(w.ok,true);assert.equal(w.value.splitBrain,true)});
test('downstream handoff grants no M28/Git/CI/checkpoint/release authority',()=>{const c=context(),v=createAssuranceVerdictCapsule('VERDICT-HANDOFF',c.input,null,c.options);assert.equal(v.ok,true);const h=createDownstreamAssuranceHandoff(v.value,c.input,'M28_TEST_IMPACT',c.options);assert.equal(h.ok,true);assert.equal(h.value.owner,'M27_ASSURANCE');assert.equal(h.value.maySelectTests,false);assert.equal(h.value.mayOperateGit,false);assert.equal(h.value.mayOperateCi,false);assert.equal(h.value.mayPromoteCheckpoint,false);assert.equal(h.value.mayRelease,false)});