import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';
import{M27_MECHANISMS,createAssuranceIntentCapsule,createAssuranceRiskProfile,classifyAssurance,createAssuranceBudgetGuard,compileAssuranceRequirementProfile,createProofHandoffGate,createHedsHandoffGate,createEvidenceAdmissionGate,createHedsSemanticGate,createAssuranceFinding,evaluateAssurance,createAssuranceVerdictCapsule,verifyAssuranceVerdictCapsule,createAssuranceTransitionReceipt,createAssuranceReopenWitness,createAssuranceReplayGuard,createAssuranceSplitBrainWitness,createDownstreamAssuranceHandoff}from'../packages/assurance-pipeline/dist/public.js';
const digest={algorithm:'sha256',digest(input){return createHash('sha256').update(input).digest('hex')}};const options={digest,maxUnits:10000,maxHistory:100};
const cp=(a,b)=>a<b?-1:a>b?1:0;function stable(v){if(v===null||typeof v==='number'||typeof v==='boolean'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(',')}]`;const r=v;return`{${Object.keys(r).sort(cp).map(k=>`${JSON.stringify(k)}:${stable(r[k])}`).join(',')}}`;};const seal=(kind,payload)=>`sha256:${createHash('sha256').update(`${kind}\n${stable(payload)}`).digest('hex')}`;const sha=x=>`sha256:${createHash('sha256').update(x).digest('hex')}`;const su=a=>[...new Set(a)].sort(cp);
function intent(requestedClass='MAX_ASSURANCE',candidateSemanticDigest=sha('candidate')){const r=createAssuranceIntentCapsule({intentId:'INTENT-27',projectId:'PROJECT',lineageId:'LINEAGE',workOrderId:'GBS-WO-M27-001',candidateId:'CANDIDATE',candidateSemanticDigest,configDigest:sha('config'),runtimeDigest:sha('runtime'),toolchainDigest:sha('toolchain'),requestedClass,purpose:'assure candidate',policyDigest:sha('policy')},options);assert.equal(r.ok,true);return r.value;}
function signal(signalId,kind,level='LOW',truthState='KNOWN'){return{signalId,kind,ownerId:'RISK_OWNER',truthState,level,semanticDigest:sha(`${signalId}:${kind}:${level}:${truthState}`)}}
function risk(i=intent(),signals=[signal('R1','CRITICAL_DATA_INTEGRITY','CRITICAL')],complete=true){const r=createAssuranceRiskProfile(i.projectId,i.lineageId,i.candidateSemanticDigest,i.policyDigest,signals,complete,options);assert.equal(r.ok,true);return r.value;}
function evidenceHandoff(label=''){const body={owner:'M24_EVIDENCE',consumer:'M27_ASSURANCE',manifestDigest:sha(`m24-manifest${label}`),acceptedEvidenceDigests:[sha(`ev-pass${label}`)],rejectedEvidenceDigests:[],staleEvidenceDigests:[],conflictEvidenceDigests:[],unknownEvidenceDigests:[],claimMappingDigest:sha(`claims${label}`),receiptSetDigest:sha(`receipts${label}`),unresolvedClaimIds:[],mayComputeProof:false,mayDecideAssurance:false};return{...body,handoffDigest:seal('DPC24',body)}}
function proofHandoff(label=''){const body={owner:'M25_PROOF',consumer:'M27_ASSURANCE',snapshotDigest:sha(`m25-snapshot${label}`),proofStates:[{claimId:'CLAIM-1',state:'PROVEN'}],selectedSupportIds:['SUPPORT-1'],proofFingerprintDigests:[sha(`proof-fp${label}`)],invalidationVectorDigest:null,unresolvedClaimIds:[],mayPerformDeltaReview:false,mayDecideAssurance:false,mayMutateDod:false,mayCalculateProgress:false,mayPromoteCheckpoint:false};return{...body,handoffDigest:seal('DPH25',body)}}
function hedsHandoff(verdict='APPROVED',blockingFindingDigests=[],label=''){const body={owner:'M26_HEDS',consumer:'M27_ASSURANCE',verdictDigest:sha(`heds-verdict-${verdict}${label}`),semanticDigest:sha(`heds-sem-${verdict}${label}`),verdict,sourceManifestDigest:sha(`source-manifest${label}`),inventoryDigest:sha(`inventory${label}`),frontierDigest:sha(`frontier${label}`),gateSetDigest:sha(`heds-gates${label}`),impactedSubjectIds:['SUBJECT-1'],blockingFindingDigests:su(blockingFindingDigests),reviewPolicyDigest:sha(`review-policy${label}`),mayDecideAssurance:false,maySelectTests:false,mayOperateGit:false,mayPromoteCheckpoint:false};return{...body,handoffDigest:seal('DHH26',body)}}
function upstreamBinding(i,e,p,h){const body={owner:'EXTERNAL_CANONICAL',projectId:i.projectId,lineageId:i.lineageId,candidateSemanticDigest:i.candidateSemanticDigest,policyDigest:i.policyDigest,evidenceHandoffDigest:e.handoffDigest,proofHandoffDigest:p.handoffDigest,hedsHandoffDigest:h.handoffDigest,authorizationDigest:sha('upstream-context-authorization')};return{...body,bindingDigest:seal('M27_UPSTREAM_CONTEXT_BINDING_V1',body)}}
const allCategories=['SOURCE_CONTEXT','EVIDENCE','PROOF','SEMANTIC_REVIEW','STATIC','UNIT_COMPONENT','INTEGRATION','E2E','PLATFORM_RUNTIME','SECURITY','RECOVERY_INTEGRITY','EXACT_CANDIDATE_SWEEP','INDEPENDENT_REVIEW','STARTUP_PURITY','BOUNDED_CANCELLABLE'];
function evaluationInput(over={}){const i=over.intent??intent(),e=over.evidenceHandoff??evidenceHandoff(),p=over.proofHandoff??proofHandoff(),h=over.hedsHandoff??hedsHandoff(),binding=over.upstreamContextBinding??upstreamBinding(i,e,p,h);return{intent:i,riskProfile:over.riskProfile??risk(i),currentPolicyDigest:over.currentPolicyDigest??i.policyDigest,budget:over.budget??{tokenBudget:1,searchBudget:1,fileBudget:1,testBudget:1,latencyBudgetMs:1},dodDigest:sha('dod'),dodCriterionIds:['DOD-1'],evidenceHandoff:e,currentEvidenceManifestDigest:over.currentEvidenceManifestDigest??e.manifestDigest,proofHandoff:p,currentProofSnapshotDigest:over.currentProofSnapshotDigest??p.snapshotDigest,hedsHandoff:h,currentHedsVerdictDigest:over.currentHedsVerdictDigest??h.verdictDigest,upstreamContextBinding:binding,findings:over.findings??[],validation:over.validation??{reachedLadderLevel:5,completedCategories:allCategories,acceptedEvidenceDigests:[sha('accepted-validation')],exactCandidateSemanticDigest:i.candidateSemanticDigest,configDigest:i.configDigest,runtimeDigest:i.runtimeDigest,toolchainDigest:i.toolchainDigest,platformIds:['ubuntu','windows','macos'],securitySatisfied:true,independentReviewSatisfied:true,truncated:false,indeterminate:false},materializationState:over.materializationState??'COMPLETE'};}

test('registry freezes all 40 M27 mechanisms',()=>{assert.equal(M27_MECHANISMS.length,40);assert.equal(new Set(M27_MECHANISMS).size,40)});
test('critical minority signal forces MAX_ASSURANCE despite STANDARD request',()=>{const i=intent('STANDARD'),r=risk(i,[signal('LOW-1','PUBLIC_CONTRACT','LOW'),signal('CRIT-1','SIGNING','CRITICAL'),signal('LOW-2','CROSS_BOUNDARY_STATE','LOW')]);const c=classifyAssurance(i,r,options);assert.equal(c.ok,true);assert.equal(c.value.derivedFloor,'MAX_ASSURANCE');assert.equal(c.value.effectiveClass,'MAX_ASSURANCE');assert.deepEqual(c.value.highSignalIds,['CRIT-1'])});
test('caller may raise but never lower assurance',()=>{const i=intent('MAX_ASSURANCE'),r=risk(i,[signal('LOW','PUBLIC_CONTRACT','LOW')]);const c=classifyAssurance(i,r,options);assert.equal(c.ok,true);assert.equal(c.value.derivedFloor,'STANDARD_PLUS');assert.equal(c.value.effectiveClass,'MAX_ASSURANCE')});
test('unknown risk truth is fail-closed and cannot default STANDARD',()=>{const i=intent('STANDARD'),r=risk(i,[signal('U','UNCERTAINTY','LOW','UNKNOWN')],false);const c=classifyAssurance(i,r,options);assert.equal(c.ok,true);assert.equal(c.value.state,'INDETERMINATE');assert.ok(['HIGH_ASSURANCE','MAX_ASSURANCE'].includes(c.value.effectiveClass))});
test('budget pressure never downgrades classification',()=>{const i=intent(),c=classifyAssurance(i,risk(i),options);assert.equal(c.ok,true);const g=createAssuranceBudgetGuard(c.value,{tokenBudget:0,searchBudget:0,fileBudget:0,testBudget:0,latencyBudgetMs:0},options);assert.equal(g.ok,true);assert.equal(g.value.assurancePreserved,true)});
test('requirement matrix is monotonic',()=>{const low=intent('STANDARD'),lc=classifyAssurance(low,risk(low,[signal('L','UNCERTAINTY','NONE')]),options);assert.equal(lc.ok,true);const lp=compileAssuranceRequirementProfile(low,lc.value,options);assert.equal(lp.ok,true);const high=intent('MAX_ASSURANCE'),hc=classifyAssurance(high,risk(high,[signal('L','UNCERTAINTY','NONE')]),options);assert.equal(hc.ok,true);const hp=compileAssuranceRequirementProfile(high,hc.value,options);assert.equal(hp.ok,true);for(const x of lp.value.requiredCategories)assert.ok(hp.value.requiredCategories.includes(x))});
test('DPH25 handoff tamper is rejected',()=>{const p=proofHandoff(),bad={...p,unresolvedClaimIds:['FORGED']};const g=createProofHandoffGate(bad,p.snapshotDigest,options);assert.equal(g.ok,true);assert.equal(g.value.valid,false)});
test('stale DPH25 snapshot is explicit',()=>{const p=proofHandoff(),g=createProofHandoffGate(p,sha('new-snapshot'),options);assert.equal(g.ok,true);assert.equal(g.value.current,false);assert.equal(g.value.valid,false)});
test('DHH26 correction remains corrective failure',()=>{const h=hedsHandoff('CORRECTION_REQUIRED'),hg=createHedsHandoffGate(h,h.verdictDigest,options);assert.equal(hg.ok,true);const sg=createHedsSemanticGate(hg.value,options);assert.equal(sg.ok,true);assert.equal(sg.value.state,'FAIL')});
test('DPC24 handoff tamper is rejected',()=>{const e=evidenceHandoff(),bad={...e,acceptedEvidenceDigests:[sha('forged')]};const g=createEvidenceAdmissionGate(bad,e.manifestDigest,options);assert.equal(g.ok,true);assert.equal(g.value.valid,false)});
test('fully current MAX_ASSURANCE context is ASSURED',()=>{const ev=evaluateAssurance(evaluationInput(),options);assert.equal(ev.ok,true);assert.equal(ev.value.classification.effectiveClass,'MAX_ASSURANCE');assert.equal(ev.value.gates.verdictAdmission.state,'PASS');const v=createAssuranceVerdictCapsule('VERDICT-1',evaluationInput(),null,options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'ASSURED')});
test('cross-context valid handoff splice is blocked by external binding',()=>{const input=evaluationInput(),foreign=proofHandoff('-foreign');input.proofHandoff=foreign;input.currentProofSnapshotDigest=foreign.snapshotDigest;const ev=evaluateAssurance(input,options);assert.equal(ev.ok,true);assert.equal(ev.value.gates.verdictAdmission.state,'BLOCKED');const v=createAssuranceVerdictCapsule('VERDICT-SPLICE',input,null,options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'BLOCKED')});
test('stopping below ladder floor cannot assure',()=>{const input=evaluationInput();input.validation={...input.validation,reachedLadderLevel:3};const v=createAssuranceVerdictCapsule('VERDICT-LADDER',input,null,options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'CORRECTION_REQUIRED')});
test('exact candidate drift invalidates final sweep',()=>{const input=evaluationInput();input.validation={...input.validation,exactCandidateSemanticDigest:sha('older-candidate')};const v=createAssuranceVerdictCapsule('VERDICT-STALE',input,null,options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'CORRECTION_REQUIRED')});
test('stale proof truth yields INDETERMINATE rather than fake correction',()=>{const p=proofHandoff(),input=evaluationInput({proofHandoff:p,currentProofSnapshotDigest:sha('new-proof')});const v=createAssuranceVerdictCapsule('VERDICT-PROOF-STALE',input,null,options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'INDETERMINATE')});
test('open HIGH finding blocks assurance',()=>{const f=createAssuranceFinding({findingId:'F-HIGH',severity:'HIGH',state:'OPEN',ownerId:'SECURITY_OWNER',ruleId:'RULE-HIGH',sourceDigest:sha('finding-source'),supersedesFindingDigest:null},options);assert.equal(f.ok,true);const v=createAssuranceVerdictCapsule('VERDICT-BLOCKED',evaluationInput({findings:[f.value]}),null,options);assert.equal(v.ok,true);assert.equal(v.value.verdict,'BLOCKED')});
test('verdict integrity detects field tamper',()=>{const input=evaluationInput(),v=createAssuranceVerdictCapsule('VERDICT-TAMPER',input,null,options);assert.equal(v.ok,true);const check=verifyAssuranceVerdictCapsule({...v.value,assuranceClass:'STANDARD'},input,options);assert.equal(check.ok,true);assert.equal(check.value.valid,false)});
test('replay guard records exact duplicate without conflict',()=>{const v=createAssuranceVerdictCapsule('VERDICT-REPLAY',evaluationInput(),null,options);assert.equal(v.ok,true);const g=createAssuranceReplayGuard([v.value,v.value],options);assert.equal(g.ok,true);assert.equal(g.value.state,'CLEAR');assert.equal(g.value.duplicateVerdictDigests.length,1)});
test('silent regression from ASSURED requires reopen witness',()=>{const baseInput=evaluationInput(),pred=createAssuranceVerdictCapsule('VERDICT-PRED',baseInput,null,options);assert.equal(pred.ok,true);const nextInput=evaluationInput();nextInput.validation={...nextInput.validation,reachedLadderLevel:0};const succ=createAssuranceVerdictCapsule('VERDICT-SUCC',nextInput,pred.value.verdictDigest,options);assert.equal(succ.ok,true);const tr=createAssuranceTransitionReceipt(pred.value,succ.value,null,['VALIDATION'],['REGRESSION'],options);assert.equal(tr.ok,false);const rw=createAssuranceReopenWitness(pred.value,succ.value.candidateSemanticDigest,'ASSURANCE_OWNER',sha('authorization'),['REVALIDATION_REQUIRED'],options);assert.equal(rw.ok,true);const tr2=createAssuranceTransitionReceipt(pred.value,succ.value,rw.value,['VALIDATION'],['REGRESSION'],options);assert.equal(tr2.ok,true)});
test('split brain detects divergent authenticated successors',()=>{const pred=createAssuranceVerdictCapsule('PRED',evaluationInput(),null,options);assert.equal(pred.ok,true);const a=createAssuranceVerdictCapsule('A',evaluationInput(),pred.value.verdictDigest,options);assert.equal(a.ok,true);const inputB=evaluationInput();inputB.validation={...inputB.validation,reachedLadderLevel:0};const b=createAssuranceVerdictCapsule('B',inputB,pred.value.verdictDigest,options);assert.equal(b.ok,true);const w=createAssuranceSplitBrainWitness(pred.value.verdictDigest,[a.value,b.value],options);assert.equal(w.ok,true);assert.equal(w.value.splitBrain,true)});
test('downstream handoff grants no M28/Git/CI/checkpoint/release authority',()=>{const input=evaluationInput(),v=createAssuranceVerdictCapsule('VERDICT-HANDOFF',input,null,options);assert.equal(v.ok,true);const h=createDownstreamAssuranceHandoff(v.value,input,'M28_TEST_IMPACT',options);assert.equal(h.ok,true);assert.equal(h.value.owner,'M27_ASSURANCE');assert.equal(h.value.maySelectTests,false);assert.equal(h.value.mayOperateGit,false);assert.equal(h.value.mayOperateCi,false);assert.equal(h.value.mayPromoteCheckpoint,false);assert.equal(h.value.mayRelease,false)});
