import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{M28_MECHANISMS,buildTestMap,selectImpactedTests,createReuseReceipt,validateReuse,progressiveValidationLevel,createTestImpactResult,createTestImpactHandoff,deniesMutationAuthority}from'../packages/test-impact-engine/dist/public.js';
const H=s=>'sha256:'+createHash('sha256').update(s).digest('hex');const options={digest:{algorithm:'sha256',digest:s=>createHash('sha256').update(s).digest('hex')}};
const sources=[{id:'src:a',fingerprint:H('a')},{id:'src:b',fingerprint:H('b'),dependsOn:['src:a']}];const tests=[{id:'test:a',fingerprint:H('ta'),sources:['src:a']},{id:'test:b',fingerprint:H('tb'),sources:['src:b'],dependsOn:['test:a'],platforms:['linux']}];
test('registry contains 32 unique frozen mechanisms',()=>{assert.equal(M28_MECHANISMS.length,32);assert.equal(new Set(M28_MECHANISMS).size,32)});
test('map and impact are deterministic across input permutation',()=>{const a=buildTestMap(sources,tests,options),b=buildTestMap([...sources].reverse(),[...tests].reverse(),options);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.equal(a.value.digest,b.value.digest);const assurance={requiredLevel:'L2',policyDigest:H('p'),profileDigest:H('q')};const x=selectImpactedTests(a.value,['src:a'],'linux',assurance,options);assert.equal(x.ok,true);assert.deepEqual(x.value.tests,['test:a','test:b']);assert.equal(x.value.level,'L2')});
test('unknown source widens to L4 and selects platform-relevant suite',()=>{const m=buildTestMap(sources,tests,options);const x=selectImpactedTests(m.value,['src:unknown'],'linux',{requiredLevel:'L1',policyDigest:H('p'),profileDigest:H('q')},options);assert.equal(x.value.level,'L4');assert.deepEqual(x.value.tests,['test:a','test:b']);assert.equal(x.value.uncertainty,'UNKNOWN')});
test('proof reuse requires exact bindings and current failure dominates',()=>{const base={testId:'test:a',testFingerprint:H('t'),sourceDigest:H('s'),dependencyDigest:H('d'),configDigest:H('c'),fixtureDigest:H('f'),toolchainDigest:H('tc'),runtimeDigest:H('r'),platform:'linux',policyDigest:H('p'),candidateDigest:H('cand')};const r=createReuseReceipt({...base,evidenceId:'ev:1',acceptedPass:true},options);assert.equal(validateReuse(r.value,base,options).value.state,'REUSABLE');const stale={...base,configDigest:H('changed')};assert.equal(validateReuse(r.value,stale,options).value.state,'STALE_CONFIG');const failed=createReuseReceipt({...base,evidenceId:'ev:2',acceptedPass:true,currentFailure:true},options);assert.equal(validateReuse(failed.value,base,options).value.state,'CURRENT_FAILURE')});
test('validation ladder never downgrades assurance floor',()=>{assert.equal(progressiveValidationLevel({direct:true,assuranceFloor:'L4'}),'L4');assert.equal(progressiveValidationLevel({assuranceFloor:'L2',uncertainty:'UNKNOWN'}),'L4');assert.equal(progressiveValidationLevel({assuranceFloor:'L5',uncertainty:'NONE'}),'L5')});
test('result handoff is read only',()=>{const m=buildTestMap(sources,tests,options),s=selectImpactedTests(m.value,['src:a'],'linux',{requiredLevel:'L2',policyDigest:H('p'),profileDigest:H('q')},options),r=createTestImpactResult({selection:s.value},options),h=createTestImpactHandoff('m32',H('cand'),r.value,options);assert.equal(h.ok,true);assert.equal(deniesMutationAuthority(h.value),true);assert.equal(h.value.authority,'READ_ONLY_TEST_IMPACT')});
