import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(resolve(ROOT,p),"utf8");
const cp = JSON.parse(read(".engineering/CHECKPOINT.json"));
const lock = JSON.parse(read(".engineering/context-locks/GBS-V11-WO-009-PROMOTION.json"));
const human = read(".engineering/CHECKPOINT.md");
const evidence = read(".engineering/evidence/GBS-V11-WO-009-PROMOTION-EVIDENCE.md");
test("WO-009 promotion preserves accepted V1 and next-admits only WO-010 planning",()=>{
  assert.equal(cp.status,"GBS_V1_PRODUCTION_ACCEPTED");
  assert.equal(cp.earnedProductionWeight,1088);
  assert.equal(cp.mainProductionDenominatorWeight,1088);
  assert.equal(cp.stopState,"GBS_V1_PRODUCTION_ACCEPTED_1088_OF_1088");
  assert.equal(cp.v11.status,"GBS_V11_WO_009_OWNER_AUDIT_APPROVED_MERGED_WO_010_ADMISSION_NEXT");
  assert.equal(cp.v11.stopState,"GBS_V11_WO_009_OWNER_AUDIT_APPROVED_MERGED_READY_FOR_WO_010_ADMISSION");
  assert.equal(cp.v11.activeWorkOrder,"NONE");
  assert.equal(cp.v11.nextLegalAction,"PLAN_AND_ADMIT_GBS_V11_WO_010");
  assert.equal(cp.v11.nextWorkOrder,"GBS-V11-WO-010");
  assert.ok(human.includes("### Completed V1.1 increment — WO-009"));
  assert.ok(human.includes("V1.1 STOP CONDITION: \`GBS_V11_WO_009_OWNER_AUDIT_APPROVED_MERGED_READY_FOR_WO_010_ADMISSION\`"));
});
test("WO-009 exact-head owner audit and resolved CodeQL HIGH bind promotion",()=>{
  const w=cp.v11.completedWorkOrders["GBS-V11-WO-009"];
  assert.equal(w.status,"OWNER_AUDIT_APPROVED_MERGED");
  assert.equal(w.implementationPr,316);
  assert.equal(w.auditedHead,"a04a6b239ccc81c9662830cd9074c70381c84b4e");
  assert.equal(w.objectiveAudit,"OWNER_APPROVED");
  assert.equal(w.auditIndependence,"NOT_INDEPENDENT");
  assert.equal(w.objectiveReview,5889695018);
  assert.equal(w.implementationMerge,"cb6cf5cf4f27d9d717921aa833ee342863f0d172");
  assert.equal(w.criticalFindings,0);
  assert.equal(w.highFindings,0);
  assert.equal(w.exactHeadChecks.count,20);
  assert.equal(w.matrixResults.windows.pass,1594);
  assert.equal(w.matrixResults.windows.fail,0);
  assert.equal(w.securityPrerequisite.alertId,2);
  assert.equal(w.securityPrerequisite.disposition,"fixed");
  assert.deepEqual(w.securityResiduals.codeQLMediumAlertOpen,[1]);
  assert.deepEqual(w.securityResiduals.scorecardHighOnMainOpen,[14,13,3]);
  assert.ok(evidence.includes("36563282570"));
  assert.ok(evidence.includes("NOT_INDEPENDENT"));
});
test("promotion lock forbids main, tags, publication and WO-010 implementation",()=>{
  assert.equal(lock.workOrder,"GBS-V11-WO-009-PROMOTION");
  assert.equal(lock.baseSha,"cb6cf5cf4f27d9d717921aa833ee342863f0d172");
  assert.equal(lock.productionShaAtLock,"e23311e77d79b84f3c70671072a22a6f8896d13d");
  assert.equal(lock.v100TagObjectAtLock,"aac89f9c3f0c884474958025bf14828bc338b5ee");
  assert.ok(lock.canonicalSources.every(x=>/^[0-9a-f]{40}$/.test(x.baseBlobSha)));
  for(const s of ["main","tag:v1.0.0","release publication","WO-010 implementation"])assert.ok(lock.forbiddenWriteSurface.includes(s));
});
