import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const WORKFLOW = readFileSync(resolve(ROOT, ".github/workflows/v11-publish.yml"), "utf8");
const RELEASE_ASSURANCE = readFileSync(resolve(ROOT, ".github/workflows/v11-release-assurance.yml"), "utf8");
const ARTIFACT_SMOKE = readFileSync(resolve(ROOT, "tests/v11-wo-010-artifact-smoke.mjs"), "utf8");
const PACKAGE_PREPARER = readFileSync(resolve(ROOT, "packages/cli/scripts/prepare-package.mjs"), "utf8");
const UNPRIVILEGED_VALIDATION = readFileSync(resolve(ROOT, ".github/scripts/run-v11-unprivileged-validation.ps1"), "utf8");

test("WO-010 manual branch dispatch verifies a candidate but only an exact pushed tag can publish", () => {
  assert.match(WORKFLOW, /push:\s*\n\s+tags:\s*\["v1\.1\.0", "v1\.1\.1", "v1\.1\.2"\]/);
  assert.match(WORKFLOW, /workflow_dispatch:\s*\n\s+inputs:\s*\n\s+mode:\s*\n\s+description:[\s\S]*?options:[\s\S]*?- CANDIDATE[\s\S]*?- RECOVERY/);
  assert.match(WORKFLOW, /if:\s*github\.ref == 'refs\/tags\/v1\.1\.0' \|\| \(github\.event_name == 'workflow_dispatch' && github\.ref_type == 'branch' && inputs\.mode != 'RECOVERY'\)/);
  assert.doesNotMatch(WORKFLOW, /^\s+pull_request:/m);
  assert.doesNotMatch(WORKFLOW, /^\s+branches:/m);
  assert.match(WORKFLOW, /Require manual branch dispatch to test this exact candidate[\s\S]*?test "\$GITHUB_REF_TYPE" = "branch"[\s\S]*?git rev-parse HEAD/);
  assert.match(WORKFLOW, /test "\$GITHUB_REF_TYPE" = "tag"/);
  assert.match(WORKFLOW, /test "\$GITHUB_REF_NAME" = "v1\.1\.0"/);
  assert.match(WORKFLOW, /git merge-base --is-ancestor/);
  const recoveryJob = WORKFLOW.split("\n  recovery:")[1].split("\n  cross-platform-artifact-smoke:")[0];
  assert.match(recoveryJob, /if: github\.event_name == 'workflow_dispatch' && github\.ref == 'refs\/heads\/main' && inputs\.mode == 'RECOVERY'/);
  assert.match(recoveryJob, /ref: v1\.1\.0/);
  assert.match(recoveryJob, /EXPECTED_RELEASE_COMMIT: fb2a2e6d41086e82ba03f307dc6ada18a52458ea/);
  assert.match(recoveryJob, /git rev-parse HEAD[\s\S]*?test "\$source_commit" = "\$EXPECTED_RELEASE_COMMIT"/);
  assert.match(recoveryJob, /node-version: "22\.17\.0"/);
  assert.match(recoveryJob, /npm ci --ignore-scripts[\s\S]*?npm run build[\s\S]*?npm run validate[\s\S]*?npm audit --audit-level=high/);
  assert.match(recoveryJob, /prepare-package\.mjs --pack[\s\S]*?sha256sum/);
  assert.doesNotMatch(recoveryJob, /sha1sum|sha-?1|dist\.shasum/i);
  assert.match(recoveryJob, /npm view @gef-bootstrap\/cli@1\.1\.0 version[\s\S]*?dist\.integrity[\s\S]*?repository\.url/);
  assert.match(recoveryJob, /npm view @gef-bootstrap\/cli@1\.1\.0 dist\.integrity --registry=https:\/\/registry\.npmjs\.org\//);
  assert.match(recoveryJob, /node --input-type=module - "\$tarball" <<'SRI'[\s\S]*?createHash\("sha512"\)[\s\S]*?digest\("base64"\)[\s\S]*?SRI/);
  assert.match(recoveryJob, /process\.stdout\.write\(`sha512-\$\{createHash\("sha512"\)/);
  assert.match(recoveryJob, /published_integrity"\s*!=\s*"\$tarball_integrity"/);
  assert.match(recoveryJob, /if \[ "\$published_repository" != "\$expected_repository" \]; then[\s\S]*?exit 1[\s\S]*?fi/);
  assert.match(recoveryJob, /GBS_V11_WO_010_RELEASE_INCIDENT_PACKAGE_MISMATCH/);
  assert.match(recoveryJob, /npm install @gef-bootstrap\/cli@1\.1\.0 --ignore-scripts --no-audit --no-fund --registry=https:\/\/registry\.npmjs\.org\//);
  assert.match(recoveryJob, /requiredPackages = \["contracts", "kernel", "preflight", "config", "project-identity"\]/);
  assert.match(recoveryJob, /Inspected bundled runtime directory[\s\S]*?isRealDirectory\(packageRoot\)[\s\S]*?containsRealFile\(distPath\)[\s\S]*?GBS_V11_WO_010_RELEASE_INCIDENT_BUNDLED_RUNTIME_MISSING/);
  assert.match(recoveryJob, /GBS_V11_WO_010_RELEASE_INCIDENT_RUNTIME_SMOKE_FAILED/);
  assert.match(recoveryJob, /gef --version[\s\S]*?gef --help[\s\S]*?processExitCodeFor[\s\S]*?gef status --target[\s\S]*?JSON\.parse/);
  assert.match(recoveryJob, /npm view @gef-bootstrap\/cli@1\.1\.0 dist\.signatures --json[\s\S]*?npm view @gef-bootstrap\/cli@1\.1\.0 dist\.attestations --json[\s\S]*?PROVENANCE_NOT_CLAIMED_FOR_BOOTSTRAP_1_1_0/);
  assert.doesNotMatch(recoveryJob, /npm audit signatures/);
  assert.doesNotMatch(recoveryJob, /npm publish|id-token:\s*write|NPM_TOKEN|NODE_AUTH_TOKEN|git tag|git push/);
  assert.doesNotMatch(WORKFLOW, /node-version:\s*"(?!22\.17\.0)[^"]+"/);
  const publishJob = WORKFLOW.split("\n  publish:")[1].split("\n  post-publish:")[0];
  const postPublishJob = WORKFLOW.split("\n  post-publish:")[1];
  assert.match(publishJob, /needs: \[verify, cross-platform-artifact-smoke\]/);
  assert.match(publishJob, /if: github\.event_name == 'push' && github\.ref == 'refs\/tags\/v1\.1\.0'/);
  assert.match(postPublishJob, /if: github\.event_name == 'push' && github\.ref == 'refs\/tags\/v1\.1\.0'/);
});

test("WO-010 publisher uses short-lived OIDC with least privilege and no publish token", () => {
  const jobs = WORKFLOW.split("  publish:")[1];
  assert.ok(jobs, "publish job must be present");
  const publishJob = jobs.split("\n  post-publish:")[0];
  assert.match(publishJob, /environment:\s*\n\s+name: npm-publish/);
  assert.match(publishJob, /id-token:\s*write/);
  assert.match(publishJob, /actions:\s*read/);
  assert.match(publishJob, /contents:\s*read/);
  assert.doesNotMatch(WORKFLOW.split("  verify:")[1].split("\n  publish:")[0], /id-token:\s*write/);
  assert.doesNotMatch(WORKFLOW.split("  post-publish:")[1].split("\n  verify-1-1-1:")[0], /id-token:\s*write/);
  assert.doesNotMatch(WORKFLOW, /NPM_TOKEN|NODE_AUTH_TOKEN|npm_[A-Za-z0-9]{20,}/);
  assert.match(WORKFLOW, /npm install --global --ignore-scripts --no-audit --no-fund npm@11\.5\.1/);
  assert.match(WORKFLOW, /test "\$\(npm --version\)" = "11\.5\.1"/);
  const publishJobSection = WORKFLOW.split("\n  publish:")[1].split("\n  post-publish:")[0];
  assert.equal((WORKFLOW.match(/id-token:\s*write/g) ?? []).length, 3, "only v1.1.0, v1.1.1 and v1.1.2 publish jobs may request OIDC identity");
  const publish111Job = WORKFLOW.split("\n  publish-1-1-1:")[1].split("\n  post-publish-1-1-1:")[0];
  assert.match(publish111Job, /if: github\.event_name == 'push' && github\.ref == 'refs\/tags\/v1\.1\.1'/);
  assert.match(publish111Job, /id-token:\s*write/);
  const publish112Job = WORKFLOW.split("\n  publish-1-1-2:")[1].split("\n  post-publish-1-1-2:")[0];
  assert.match(publish112Job, /if: github\.event_name == 'push' && github\.ref == 'refs\/tags\/v1\.1\.2'/);
  assert.match(publish112Job, /environment:\s*\n\s+name: npm-publish/);
  assert.match(publish112Job, /id-token:\s*write/);
  assert.match(publishJobSection, /needs: \[verify, cross-platform-artifact-smoke\]/);
});

test("WO-010 publisher validates, inspects and smokes the exact tarball before publishing", () => {
  assert.match(WORKFLOW, /npm run build/);
  assert.match(WORKFLOW, /npm run validate/);
  assert.match(WORKFLOW, /npm audit --audit-level=high/);
  assert.match(WORKFLOW, /prepare-package\.mjs --pack/);
  assert.match(WORKFLOW, /tar -tzf/);
  assert.match(WORKFLOW, /const expectedFiles = \['LICENSE', 'README\.md', 'bin', 'dist', 'schemas', 'vendor'\]/);
  assert.match(WORKFLOW, /const expectedBundles = \['@gef-bootstrap\/config', '@gef-bootstrap\/contracts', '@gef-bootstrap\/kernel', '@gef-bootstrap\/preflight', '@gef-bootstrap\/project-identity', '@koromix\/koffi-darwin-arm64', '@koromix\/koffi-darwin-x64', '@koromix\/koffi-linux-x64', '@koromix\/koffi-win32-x64', 'koffi'\]/);
  assert.match(WORKFLOW, /const expectedNativeBundles = \['@koromix\/koffi-linux-x64', '@koromix\/koffi-darwin-x64', '@koromix\/koffi-darwin-arm64', '@koromix\/koffi-win32-x64'\]/);
  assert.match(WORKFLOW, /entry\.endsWith\('\/koffi\.node'\)/);
  assert.match(WORKFLOW, /for \(const entry of entries\)/);
  assert.match(WORKFLOW, /archive path is outside the reviewed allowlist/);
  assert.match(WORKFLOW, /sensitiveFilename\.test\(normalized\)/);
  assert.match(WORKFLOW, /npm install --package-lock-only --ignore-scripts --offline/);
  assert.match(WORKFLOW, /test -s package-lock\.json\r?\n\s+npm ci --ignore-scripts --offline --no-audit --no-fund/);
  assert.doesNotMatch(WORKFLOW, /npm init -y --prefix/);
  assert.match(WORKFLOW, /cd "\$consumer"\r?\n\s+npm init -y\r?\n\s+npm install --package-lock-only --ignore-scripts --offline/);
  assert.match(WORKFLOW, /cd "\$consumer"\r?\n\s+npm init -y\r?\n\s+npm install --package-lock-only --ignore-scripts --no-audit --no-fund @gef-bootstrap\/cli@1\.1\.0/);
  assert.match(WORKFLOW, /test -s package-lock\.json\r?\n\s+npm ci --ignore-scripts --no-audit --no-fund/);
  assert.match(PACKAGE_PREPARER, /function systemTarExecutable\(\)[\s\S]*?process\.platform === "win32"[\s\S]*?SystemRoot[\s\S]*?"System32", "tar\.exe"[\s\S]*?: "\/usr\/bin\/tar"/);
  assert.match(PACKAGE_PREPARER, /!isAbsolute\(executable\) \|\| !existsSync\(executable\)/);
  assert.doesNotMatch(PACKAGE_PREPARER, /spawnSync\(\s*["']tar["']/);
  assert.equal((PACKAGE_PREPARER.match(/spawnSync\(systemTarExecutable\(\),/g) ?? []).length, 2);
  assert.match(PACKAGE_PREPARER, /function comparePackageNames\(left, right\)[\s\S]*?left < right[\s\S]*?left > right/);
  assert.match(PACKAGE_PREPARER, /bundleDependencies = \[\.\.\.bundleDependencies\]\.sort\(comparePackageNames\)/);
  assert.match(WORKFLOW, /actions\/upload-artifact@/);
  assert.match(WORKFLOW, /GBS-V11-WO-010-RELEASE-MANIFEST\.json/);
  assert.match(WORKFLOW, /provenance/);
  assert.match(WORKFLOW, /node "\$bin" --help/);
  assert.match(WORKFLOW, /node "\$bin" --version/);
  assert.match(WORKFLOW, /node "\$bin" doctor/);
  assert.match(WORKFLOW, /node "\$bin" status/);
  assert.match(WORKFLOW, /npm publish "\$tarball" --access public --provenance --ignore-scripts/);
  const postPublishJob = WORKFLOW.split("\n  post-publish:")[1];
  assert.match(postPublishJob, /npm audit signatures @gef-bootstrap\/cli@1\.1\.0/);
});

test("WO-010 installs and exercises the same checksum-bound run artifact on Ubuntu, Windows and macOS", () => {
  const matrixJob = WORKFLOW.split("\n  cross-platform-artifact-smoke:")[1].split("\n  publish:")[0];
  assert.match(matrixJob, /os: \[ubuntu-latest, windows-latest, macos-latest\]/);
  assert.match(matrixJob, /actions\/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093/);
  assert.match(matrixJob, /name: gef-v1\.1\.0-package-\$\{\{ github\.run_id \}\}/);
  assert.match(matrixJob, /receipt\.sourceCommit !== process\.env\.EXPECTED_SOURCE_COMMIT/);
  assert.match(matrixJob, /receipt\.tarball\.sha256 !== actual/);
  assert.match(matrixJob, /ref: \$\{\{ github\.sha \}\}/);
  assert.match(matrixJob, /node tests\/v11-wo-010-artifact-smoke\.mjs/);
  assert.match(ARTIFACT_SMOKE, /\["install", "--package-lock-only", "--ignore-scripts", "--offline"/);
  assert.match(ARTIFACT_SMOKE, /\["ci", "--ignore-scripts", "--offline"/);
  assert.match(ARTIFACT_SMOKE, /@koromix.*koffi-/);
  assert.match(ARTIFACT_SMOKE, /load installed Koffi native prebuild without lifecycle scripts/);
  assert.match(ARTIFACT_SMOKE, /\["uninstall", "--no-audit", "--no-fund", "@gef-bootstrap\/cli"\]/);
  assert.match(ARTIFACT_SMOKE, /doctor/);
  assert.match(ARTIFACT_SMOKE, /status/);
  assert.match(ARTIFACT_SMOKE, /upgrade.*--target/);
  assert.match(ARTIFACT_SMOKE, /applied\.document\.sourceVersion, "1\.0\.0"/);
  assert.match(ARTIFACT_SMOKE, /legacy\.stateBytes/);
  assert.doesNotMatch(matrixJob, /id-token:\s*write/);
});

test("WO-010 pre-merge assurance runs its one exact-head tarball on all three platforms", () => {
  const producer = RELEASE_ASSURANCE.split("\n  exact-head-package-candidate:")[1].split("\n  exact-head-package-platform-smoke:")[0];
  const matrixJob = RELEASE_ASSURANCE.split("\n  exact-head-package-platform-smoke:")[1].split("\n  release-assurance:")[0];
  assert.match(producer, /ref: \$\{\{ github\.event\.pull_request\.head\.sha \|\| github\.sha \}\}/);
  assert.match(producer, /test "\$\(git rev-parse HEAD\)" = "\$GEF_CANDIDATE_SHA"/);
  assert.match(producer, /prepare-package\.mjs --pack/);
  assert.match(producer, /sourceCommit/);
  assert.match(producer, /createHash\('sha256'\)/);
  assert.match(producer, /actions\/upload-artifact@/);
  assert.match(PACKAGE_PREPARER, /KOFFI_NATIVE_PREBUILDS = \[/);
  assert.match(PACKAGE_PREPARER, /RUNTIME_PACKAGES = \["contracts", "kernel", "preflight", "config", "project-identity"\]/);
  assert.match(PACKAGE_PREPARER, /verifyNativePackageIntegrity/);
  assert.match(PACKAGE_PREPARER, /function updateStagedKoffiOptionalDependencies[\s\S]*?koffiManifest\.optionalDependencies = optionalDependencies/);
  assert.match(PACKAGE_PREPARER, /cpSync\(koffiSource, koffiTarget, \{ recursive: true \}\);\r?\n\s+updateStagedKoffiOptionalDependencies\(koffiTarget, packageLock\)/);
  assert.match(PACKAGE_PREPARER, /optionalDependencies\[nativePackage\.name\]/);
  assert.match(WORKFLOW, /const expectedNativeBundles = \[/);
  assert.match(WORKFLOW, /lockfile-pinned Koffi prebuild is missing/);
  assert.match(matrixJob, /needs: exact-head-package-candidate/);
  assert.match(matrixJob, /os: \[ubuntu-latest, windows-latest, macos-latest\]/);
  assert.match(matrixJob, /actions\/download-artifact@/);
  assert.match(matrixJob, /name: gef-v\$\{\{ needs\.exact-head-package-candidate\.outputs\.package_version \}\}-exact-head-package-\$\{\{ github\.run_id \}\}/);
  assert.match(matrixJob, /if: runner\.os != 'Windows'[\s\S]*?node tests\/v11-wo-010-artifact-smoke\.mjs/);
  assert.match(matrixJob, /if: runner\.os == 'Windows'[\s\S]*?run: \.\/\.github\/scripts\/run-v11-unprivileged-validation\.ps1 -ReleaseArtifactSmoke/);
  assert.match(UNPRIVILEGED_VALIDATION, /\[switch\] \$ReleaseArtifactSmoke/);
  assert.match(UNPRIVILEGED_VALIDATION, /Add-LocalGroupMember -Group "Users"/);
  assert.match(UNPRIVILEGED_VALIDATION, /The temporary validation identity unexpectedly belongs to Administrators/);
  assert.match(UNPRIVILEGED_VALIDATION, /Copy-Item -LiteralPath[\s\S]*?GEF_EXPECTED_SOURCE_COMMIT/);
  assert.match(UNPRIVILEGED_VALIDATION, /GEF_RELEASE_RECEIPT_DIR/);
  assert.match(UNPRIVILEGED_VALIDATION, /GEF_EXPECTED_EVENT/);
  assert.match(UNPRIVILEGED_VALIDATION, /GEF_EXPECTED_REF/);
  assert.match(UNPRIVILEGED_VALIDATION, /artifact-smoke-environment\.json/);
  assert.match(UNPRIVILEGED_VALIDATION, /for \(const key of Object\.keys\(process\.env\)\) delete process\.env\[key\]/);
  assert.match(UNPRIVILEGED_VALIDATION, /Object\.assign\(process\.env, environment\)/);
  assert.match(UNPRIVILEGED_VALIDATION, /await import\(pathToFileURL\(smokeScript\)\.href\)/);
  assert.match(UNPRIVILEGED_VALIDATION, /Invoke-UserProcess "same-artifact-smoke"/);
  assert.match(UNPRIVILEGED_VALIDATION, /npmArgs = .* run validate/);
  assert.doesNotMatch(matrixJob, /id-token:\s*write/);
});

test("WO-010 publisher refuses private, renamed or wrong-version package metadata", () => {
  assert.match(WORKFLOW, /manifest\.name !== '@gef-bootstrap\/cli'/);
  assert.match(WORKFLOW, /manifest\.version !== '1\.1\.0'/);
  assert.match(WORKFLOW, /manifest\.private !== false/);
});
