import * as core from "./index.js";
import type { OperationOptions, ProfileResult, ProfileSnapshot, ComposedProfileSnapshot, SelectedProfileSnapshot, M07ProfileBindingCandidate, SelectionRequest, ProjectProfile } from "./index.js";
export * from "./index.js";
const issued=new WeakSet<object>();
function fail<T>(code:string,message:string):ProfileResult<T>{return{ok:false,error:Object.freeze({code,message})};}
function validOptions(o:unknown):o is OperationOptions{return !!o&&typeof o==="object"&&!!(o as OperationOptions).digest&&typeof (o as OperationOptions).digest.algorithm==="string"&&typeof (o as OperationOptions).digest.digest==="function";}
function opts(o:unknown):ProfileResult<OperationOptions>{return validOptions(o)?{ok:true,value:o}:{ok:false,error:Object.freeze({code:"PROFILE_DIGEST_PROVIDER_REQUIRED",message:"digest provider is required"})};}
export function validateProfile(input:unknown,options?:OperationOptions):ProfileResult<ProfileSnapshot>{const o=opts(options);if(!o.ok)return o;try{return core.validateProfile(input,o.value);}catch{return fail("PROFILE_SCHEMA_INVALID","profile validation failed safely");}}
export function createProfileRegistry(additional:readonly unknown[]=[],options?:OperationOptions):ProfileResult<ReadonlyMap<string,ProfileSnapshot>>{const o=opts(options);if(!o.ok)return o;const clean:ProjectProfile[]=[];for(const raw of additional){const v=validateProfile(raw,o.value);if(!v.ok)return v;clean.push(v.value.profile);}try{return core.createProfileRegistry(clean,o.value);}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry creation failed safely");}}
export function builtinRegistry(options?:OperationOptions):ProfileResult<ReadonlyMap<string,ProfileSnapshot>>{return createProfileRegistry([],options);}
function verified(snapshot:unknown,o:OperationOptions):ProfileResult<ProfileSnapshot>{if(!snapshot||typeof snapshot!=="object")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","snapshot shape is invalid");const s=snapshot as ProfileSnapshot;if(!s.profile||typeof s.nativeProfileSemanticDigest!=="string")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","snapshot shape is invalid");const v=validateProfile(s.profile,o);if(!v.ok)return v;return v.value.nativeProfileSemanticDigest===s.nativeProfileSemanticDigest?v:fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","snapshot digest mismatch");}
function registry(value:unknown,o:OperationOptions):ProfileResult<ReadonlyMap<string,ProfileSnapshot>>{if(!(value instanceof Map))return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry must be a Map");const clean=new Map<string,ProfileSnapshot>();for(const [id,raw] of value.entries()){if(typeof id!=="string")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry key invalid");const v=verified(raw,o);if(!v.ok)return v;if(v.value.profile.profileId!==id)return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry key mismatch");if(id in core.BUILTIN_PROFILES){const official=validateProfile(core.BUILTIN_PROFILES[id as keyof typeof core.BUILTIN_PROFILES],o);if(!official.ok)return official;if(official.value.nativeProfileSemanticDigest!==v.value.nativeProfileSemanticDigest)return fail("PROFILE_AMBIGUOUS","product-owned profile was shadowed");}clean.set(id,v.value);}return{ok:true,value:clean};}
export function composeProfile(snapshot:unknown,reg:unknown,options?:OperationOptions):ProfileResult<ComposedProfileSnapshot>{const o=opts(options);if(!o.ok)return o;const s=verified(snapshot,o.value);if(!s.ok)return s;const r=registry(reg,o.value);if(!r.ok)return r;try{const out=core.composeProfile(s.value,r.value,o.value);if(out.ok)issued.add(out.value);return out;}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","composition failed safely");}}
export function selectProfile(request:unknown,reg:unknown,options?:OperationOptions):ProfileResult<SelectedProfileSnapshot>{const o=opts(options);if(!o.ok)return o;if(!request||typeof request!=="object")return fail("PROFILE_SCHEMA_INVALID","selection request invalid");const r=registry(reg,o.value);if(!r.ok)return r;try{const out=core.selectProfile(request as SelectionRequest,r.value,o.value);if(out.ok)issued.add(out.value);return out;}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","selection failed safely");}}
export function projectProfileBindings(snapshot:unknown,bindingId:unknown):ProfileResult<readonly M07ProfileBindingCandidate[]>{if(!snapshot||typeof snapshot!=="object"||!issued.has(snapshot as object)||typeof bindingId!=="string")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","projection requires issued snapshot");try{return core.projectProfileBindings(snapshot as ComposedProfileSnapshot,bindingId);}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","projection failed safely");}}
