import * as core from "./index.js";
import type { OperationOptions, ProfileBudgets, ProfileResult, ProfileSnapshot, ComposedProfileSnapshot, SelectedProfileSnapshot, M07ProfileBindingCandidate, SelectionRequest, ProjectProfile } from "./index.js";
export * from "./index.js";
const issued=new WeakSet<object>();
const REQUEST_KEYS=new Set(["mode","profileId","expectedProfileVersion","expectedProfileDigest"]);
function fail<T>(code:string,message:string):ProfileResult<T>{return{ok:false,error:Object.freeze({code,message})};}
function record(v:unknown):v is Record<string,unknown>{return v!==null&&typeof v==="object"&&!Array.isArray(v);}
function capped(v:unknown,f:number):number{return v===undefined?f:(typeof v==="number"&&Number.isSafeInteger(v)&&v>=0?Math.min(v,f):0);}
function options(raw:unknown):ProfileResult<OperationOptions>{if(!record(raw)||!record(raw.digest)||typeof raw.digest.algorithm!=="string"||typeof raw.digest.digest!=="function")return fail("PROFILE_DIGEST_PROVIDER_REQUIRED","digest provider is required");const b=record(raw.budgets)?raw.budgets:{};return{ok:true,value:{digest:raw.digest as unknown as OperationOptions["digest"],...(raw.signal===undefined?{}:{signal:raw.signal as AbortSignal}),budgets:{maxProfiles:capped(b.maxProfiles,core.DEFAULT_PROFILE_BUDGETS.maxProfiles),maxDepth:capped(b.maxDepth,core.DEFAULT_PROFILE_BUDGETS.maxDepth),maxTemplateBindings:capped(b.maxTemplateBindings,core.DEFAULT_PROFILE_BUDGETS.maxTemplateBindings),maxVariableBindings:capped(b.maxVariableBindings,core.DEFAULT_PROFILE_BUDGETS.maxVariableBindings),maxStringBytes:capped(b.maxStringBytes,core.DEFAULT_PROFILE_BUDGETS.maxStringBytes)}}};}
function limits(o:OperationOptions):ProfileBudgets{return{...core.DEFAULT_PROFILE_BUDGETS,...o.budgets};}
function inertBounded(v:unknown,l:ProfileBudgets):boolean{if(v===undefined)return true;const stack:Array<{v:unknown,d:number}>=[{v,d:0}];const seen=new WeakSet<object>();let nodes=0,bytes=0;while(stack.length){const x=stack.pop()!;if(++nodes>l.maxVariableBindings||x.d>l.maxDepth)return false;const n=x.v;if(typeof n==="string"){bytes+=new TextEncoder().encode(n).byteLength;if(bytes>l.maxStringBytes)return false;continue;}if(n===null||typeof n==="boolean"||(typeof n==="number"&&Number.isFinite(n)))continue;if(typeof n!=="object"||seen.has(n as object))return false;seen.add(n as object);if(Array.isArray(n)){for(const q of n)stack.push({v:q,d:x.d+1});continue;}if(!record(n))return false;for(const[k,q]of Object.entries(n)){if(k==="__proto__"||k==="constructor"||k==="prototype")return false;bytes+=new TextEncoder().encode(k).byteLength;if(bytes>l.maxStringBytes)return false;stack.push({v:q,d:x.d+1});}}return true;}
function variableCount(p:unknown):number{if(!record(p)||!Array.isArray(p.templateBindings))return 0;let n=0;for(const b of p.templateBindings)if(record(b)&&Array.isArray(b.variableBindings))n+=b.variableBindings.length;return n;}
export function validateProfile(input:unknown,raw?:OperationOptions):ProfileResult<ProfileSnapshot>{const o=options(raw);if(!o.ok)return o;const l=limits(o.value);if(record(input)){if(!inertBounded(input.displayMetadata,l)||!inertBounded(input.extensions,l))return fail("PROFILE_BUDGET_EXCEEDED","inert metadata or extensions exceeded limits");if(variableCount(input)>l.maxVariableBindings)return fail("PROFILE_BUDGET_EXCEEDED","aggregate variable binding limit exceeded");}try{return core.validateProfile(input,o.value);}catch{return fail("PROFILE_SCHEMA_INVALID","profile validation failed safely");}}
function verified(snapshot:unknown,o:OperationOptions):ProfileResult<ProfileSnapshot>{if(!record(snapshot)||!record(snapshot.profile)||typeof snapshot.nativeProfileSemanticDigest!=="string")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","snapshot shape is invalid");const v=validateProfile(snapshot.profile,o);if(!v.ok)return v;return v.value.nativeProfileSemanticDigest===snapshot.nativeProfileSemanticDigest?v:fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","snapshot digest mismatch");}
function registry(value:unknown,o:OperationOptions):ProfileResult<ReadonlyMap<string,ProfileSnapshot>>{if(!(value instanceof Map))return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry must be a Map");if(value.size>limits(o).maxProfiles)return fail("PROFILE_BUDGET_EXCEEDED","registry size limit exceeded");const clean=new Map<string,ProfileSnapshot>();for(const[id,raw]of value.entries()){if(typeof id!=="string")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry key invalid");const v=verified(raw,o);if(!v.ok)return v;if(v.value.profile.profileId!==id)return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry key mismatch");if(Object.prototype.hasOwnProperty.call(core.BUILTIN_PROFILES,id)){const official=validateProfile(core.BUILTIN_PROFILES[id as keyof typeof core.BUILTIN_PROFILES],o);if(!official.ok)return official;if(official.value.nativeProfileSemanticDigest!==v.value.nativeProfileSemanticDigest)return fail("PROFILE_AMBIGUOUS","product-owned profile was shadowed");}clean.set(id,v.value);}return{ok:true,value:clean};}
function chain(start:ProfileSnapshot,r:ReadonlyMap<string,ProfileSnapshot>,o:OperationOptions):ProfileResult<true>{const seen=new Set<string>();let cur:ProfileSnapshot|undefined=start,depth=0,tb=0,vb=0;const l=limits(o);while(cur){if(o.signal?.aborted)return fail("PROFILE_INHERITANCE_CANCELLED","operation cancelled");if(seen.has(cur.profile.profileId))return fail("PROFILE_INHERITANCE_CYCLE","inheritance cycle detected");seen.add(cur.profile.profileId);if(depth>l.maxDepth)return fail("PROFILE_INHERITANCE_DEPTH_EXCEEDED","inheritance depth exceeded");tb+=(cur.profile.templateBindings??[]).length;vb+=variableCount(cur.profile);if(tb>l.maxTemplateBindings||vb>l.maxVariableBindings)return fail("PROFILE_INHERITANCE_BUDGET_EXCEEDED","aggregate inheritance limit exceeded");const ref=cur.profile.parentProfile;if(!ref)break;const parent=r.get(ref.profileId);if(!parent)return fail("PROFILE_PARENT_NOT_FOUND","parent profile not found");cur=parent;depth++;}return{ok:true,value:true};}
export function createProfileRegistry(additional:readonly unknown[]=[],raw?:OperationOptions):ProfileResult<ReadonlyMap<string,ProfileSnapshot>>{const o=options(raw);if(!o.ok)return o;if(!Array.isArray(additional))return fail("PROFILE_SCHEMA_INVALID","additional profiles must be an array");if(additional.length+4>limits(o.value).maxProfiles)return fail("PROFILE_BUDGET_EXCEEDED","profile count limit exceeded");const clean:ProjectProfile[]=[];for(const p of additional){const v=validateProfile(p,o.value);if(!v.ok)return v;clean.push(v.value.profile);}try{return core.createProfileRegistry(clean,o.value);}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","registry creation failed safely");}}
export function builtinRegistry(raw?:OperationOptions):ProfileResult<ReadonlyMap<string,ProfileSnapshot>>{return createProfileRegistry([],raw);}
export function composeProfile(snapshot:unknown,reg:unknown,raw?:OperationOptions):ProfileResult<ComposedProfileSnapshot>{const o=options(raw);if(!o.ok)return o;const s=verified(snapshot,o.value);if(!s.ok)return s;const r=registry(reg,o.value);if(!r.ok)return r;const c=chain(s.value,r.value,o.value);if(!c.ok)return c;try{const out=core.composeProfile(s.value,r.value,o.value);if(out.ok)issued.add(out.value);return out;}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","composition failed safely");}}
export function selectProfile(request:unknown,reg:unknown,raw?:OperationOptions):ProfileResult<SelectedProfileSnapshot>{const o=options(raw);if(!o.ok)return o;if(!record(request)||Object.keys(request).some(k=>!REQUEST_KEYS.has(k))||!(request.mode==="DEFAULT_GENERIC"||request.mode==="EXPLICIT_PROFILE"))return fail("PROFILE_SCHEMA_INVALID","selection request invalid");const r=registry(reg,o.value);if(!r.ok)return r;const id=request.mode==="DEFAULT_GENERIC"?"generic":request.profileId;if(typeof id!=="string")return fail("PROFILE_ID_INVALID","explicit profile id invalid");const start=r.value.get(id);if(start){const c=chain(start,r.value,o.value);if(!c.ok)return c;}try{const out=core.selectProfile(request as unknown as SelectionRequest,r.value,o.value);if(out.ok)issued.add(out.value);return out;}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","selection failed safely");}}
export function projectProfileBindings(snapshot:unknown,bindingId:unknown):ProfileResult<readonly M07ProfileBindingCandidate[]>{if(!snapshot||typeof snapshot!=="object"||!issued.has(snapshot as object)||typeof bindingId!=="string")return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","projection requires issued snapshot");try{return core.projectProfileBindings(snapshot as ComposedProfileSnapshot,bindingId);}catch{return fail("PROFILE_INTERNAL_CONTRACT_VIOLATION","projection failed safely");}}
