import type{BlockerProjection,BlockerProjectionInput,NextNecessaryActionCapsule,NextActionState,OperationOptions,ResponseVerdict,Result,StateConflictWitness,VerdictDecision}from'./types.js';
import{cancelled,compareCodePoint,deepFreeze,fail,isSha256,sha,sortedUnique,validId}from'./utils.js';
const CLASSIFICATIONS=new Set(['INFO','WARNING','BLOCKING','RECOVERY','CONFLICT']);
const DISPOSITIONS=new Set(['ACTIVE','RESOLVED','UNKNOWN']);
const FRESHNESS=new Set(['CURRENT','STALE','CONFLICT','UNKNOWN']);
const VERDICTS=new Set<ResponseVerdict>(['SUCCESS','PARTIAL','BLOCKED','INDETERMINATE','RECOVERY_REQUIRED','CONFLICT']);
const precedence:Record<ResponseVerdict,number>={SUCCESS:0,PARTIAL:1,INDETERMINATE:2,BLOCKED:3,CONFLICT:4,RECOVERY_REQUIRED:5};
export function createBlockerProjection(input:BlockerProjectionInput,options:OperationOptions):Result<BlockerProjection>{const c=cancelled(options);if(c)return c;if(!validId(input.blockerId)||!CLASSIFICATIONS.has(input.classification)||!DISPOSITIONS.has(input.disposition)||!FRESHNESS.has(input.freshness))return fail('BLOCKER_INVALID','Blocker identity/classification/disposition/freshness is invalid',input.blockerId);if(!isSha256(input.sourceIdentityDigest)||!isSha256(input.validityBindingDigest))return fail('BLOCKER_BINDING_INVALID','Blocker authority bindings must be SHA-256',input.blockerId);if(input.message.length===0||input.message.length>2048)return fail('BLOCKER_MESSAGE_INVALID','Blocker message must be present and bounded',input.blockerId);const body={...input};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,blockerDigest:d.value})};}
export function verifyBlockerProjection(blocker:BlockerProjection,options:OperationOptions):Result<boolean>{const r=createBlockerProjection({blockerId:blocker.blockerId,classification:blocker.classification,disposition:blocker.disposition,sourceIdentityDigest:blocker.sourceIdentityDigest,validityBindingDigest:blocker.validityBindingDigest,freshness:blocker.freshness,message:blocker.message},options);if(!r.ok)return r;return{ok:true,value:r.value.blockerDigest===blocker.blockerDigest};}
export function projectApplicableBlockers(blockers:readonly BlockerProjection[],options:OperationOptions):Result<readonly BlockerProjection[]>{const c=cancelled(options);if(c)return c;const out:BlockerProjection[]=[];for(const b of blockers){const v=verifyBlockerProjection(b,options);if(!v.ok)return v;if(!v.value)return fail('BLOCKER_TAMPERED','Blocker projection failed verification',b.blockerId);if(b.disposition!=='RESOLVED')out.push(b);}out.sort((a,b)=>compareCodePoint(a.blockerId,b.blockerId)||compareCodePoint(a.blockerDigest,b.blockerDigest));return{ok:true,value:deepFreeze(out)};}
export function createStateConflictWitness(subject:string,sourceDigests:readonly string[],options:OperationOptions):Result<StateConflictWitness>{const c=cancelled(options);if(c)return c;if(!validId(subject)||!sourceDigests.every(isSha256))return fail('CONFLICT_WITNESS_INVALID','Conflict witness subject/source identities are invalid',subject);const sources=sortedUnique(sourceDigests);const body={subject,sourceDigests:deepFreeze(sources),hasConflict:sources.length>1};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,witnessDigest:d.value})};}
export function verifyStateConflictWitness(w:StateConflictWitness,options:OperationOptions):Result<boolean>{const r=createStateConflictWitness(w.subject,w.sourceDigests,options);if(!r.ok)return r;return{ok:true,value:r.value.hasConflict===w.hasConflict&&r.value.witnessDigest===w.witnessDigest};}
export function createNextNecessaryActionCapsule(state:NextActionState,actionRef:string|null,sourceIdentityDigest:string,validityBindingDigest:string,options:OperationOptions):Result<NextNecessaryActionCapsule>{const c=cancelled(options);if(c)return c;if(!['KNOWN','NONE','UNKNOWN'].includes(state)||!isSha256(sourceIdentityDigest)||!isSha256(validityBindingDigest))return fail('NEXT_ACTION_INVALID','Next-action state/source binding is invalid');if(state==='KNOWN'&&(actionRef===null||!validId(actionRef)))return fail('NEXT_ACTION_REQUIRED','KNOWN next action requires exactly one bounded canonical action reference');if(state!=='KNOWN'&&actionRef!==null)return fail('NEXT_ACTION_FORBIDDEN','NONE/UNKNOWN next action cannot carry an action reference');const body={state,actionRef,sourceIdentityDigest,validityBindingDigest};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,capsuleDigest:d.value})};}
export function verifyNextNecessaryActionCapsule(a:NextNecessaryActionCapsule,options:OperationOptions):Result<boolean>{const r=createNextNecessaryActionCapsule(a.state,a.actionRef,a.sourceIdentityDigest,a.validityBindingDigest,options);if(!r.ok)return r;return{ok:true,value:r.value.capsuleDigest===a.capsuleDigest};}
export interface VerdictFlags{readonly partial?:boolean|undefined;readonly indeterminate?:boolean|undefined;readonly requestedVerdict?:ResponseVerdict|undefined;}
export function deriveResponseVerdict(blockers:readonly BlockerProjection[],conflicts:readonly StateConflictWitness[],flags:VerdictFlags,options:OperationOptions):Result<VerdictDecision>{const c=cancelled(options);if(c)return c;const projected=projectApplicableBlockers(blockers,options);if(!projected.ok)return projected;for(const w of conflicts){const v=verifyStateConflictWitness(w,options);if(!v.ok)return v;if(!v.value)return fail('CONFLICT_WITNESS_TAMPERED','State conflict witness failed verification',w.subject);}const reasons:string[]=[];let verdict:ResponseVerdict='SUCCESS';const active=projected.value;if(active.some(b=>b.classification==='RECOVERY'&&b.disposition==='ACTIVE')){verdict='RECOVERY_REQUIRED';reasons.push('ACTIVE_RECOVERY_CONDITION');}else if(conflicts.some(w=>w.hasConflict)||active.some(b=>b.classification==='CONFLICT'&&b.disposition==='ACTIVE')||active.some(b=>b.freshness==='CONFLICT')){verdict='CONFLICT';reasons.push('CANONICAL_STATE_CONFLICT');}else if(active.some(b=>b.classification==='BLOCKING'&&b.disposition==='ACTIVE'&&b.freshness==='CURRENT')){verdict='BLOCKED';reasons.push('ACTIVE_BLOCKER');}else if(active.some(b=>b.disposition==='UNKNOWN'||b.freshness==='STALE'||b.freshness==='UNKNOWN')){verdict='INDETERMINATE';reasons.push('BLOCKER_STATE_INDETERMINATE');}else if(flags.indeterminate){verdict='INDETERMINATE';reasons.push('INPUT_INDETERMINATE');}else if(flags.partial){verdict='PARTIAL';reasons.push('PARTIAL_RESULT');}if(flags.requestedVerdict!==undefined){if(!VERDICTS.has(flags.requestedVerdict))return fail('VERDICT_INVALID','Requested response verdict is invalid');if(precedence[flags.requestedVerdict]<precedence[verdict])reasons.push('OPTIMISTIC_OVERRIDE_REJECTED');else if(precedence[flags.requestedVerdict]>precedence[verdict]&&flags.requestedVerdict!=='SUCCESS'){verdict=flags.requestedVerdict;reasons.push('STRONGER_INPUT_VERDICT_PRESERVED');}}const normalized=sortedUnique(reasons);const d=sha(options,{verdict,reasons:normalized});if(!d.ok)return d;return{ok:true,value:deepFreeze({verdict,reasons:normalized,verdictDigest:d.value})};}
