import type{BlockerProjection,CompatibilityDecision,CompatibilityRequirement,DelegatedMetricClaim,HumanResponseProjection,MachineResponseEnvelope,MetricOwnershipMatrix,NextNecessaryActionCapsule,OperationOptions,ResponseBindingObservation,ResponseContractCapsule,ResponseIntegrityReceipt,ResponseVerdictClaim,Result,SourceBoundFieldClaim,StaleResponseReport,StateConflictWitness,VerdictDecision}from'./types.js';
import{cancelled,compareCodePoint,deepFreeze,fail,isSha256,sha,sortedUnique,validId}from'./utils.js';
import{buildResponseProvenanceIndex,verifyResponseContractCapsule,verifyResponseProvenanceIndex,verifyResponseSchemaEnvelope,verifySourceBoundFieldClaim}from'./s01-envelope.js';
import{verifyDelegatedMetricClaim,verifyMetricOwnershipMatrix}from'./s02-metrics.js';
import{createStateConflictWitness,deriveResponseVerdict,projectApplicableBlockers,verifyBlockerProjection,verifyNextNecessaryActionCapsule,verifyResponseVerdictClaim,verifyStateConflictWitness}from'./s03-verdict.js';
import{assessResponseRedaction,assessResponseSize,buildMinimumSufficientResponseFields}from'./s04-compactness.js';

const verdictRank:Record<VerdictDecision['verdict'],number>={SUCCESS:0,PARTIAL:1,INDETERMINATE:2,BLOCKED:3,CONFLICT:4,RECOVERY_REQUIRED:5};
function metricSort(a:DelegatedMetricClaim,b:DelegatedMetricClaim){return compareCodePoint(a.metricKey,b.metricKey)||compareCodePoint(a.claimDigest,b.claimDigest);}
function blockerSort(a:BlockerProjection,b:BlockerProjection){return compareCodePoint(a.blockerId,b.blockerId)||compareCodePoint(a.blockerDigest,b.blockerDigest);}
function conflictSort(a:StateConflictWitness,b:StateConflictWitness){return compareCodePoint(a.subject,b.subject)||compareCodePoint(a.witnessDigest,b.witnessDigest);}
function freshnessFloor(fields:readonly SourceBoundFieldClaim[]):VerdictDecision['verdict']|null{if(fields.some(f=>f.freshness==='CONFLICT'))return'CONFLICT';if(fields.some(f=>f.freshness==='STALE'||f.freshness==='UNKNOWN'))return'INDETERMINATE';return null;}
function hasFieldValueConflict(fields:readonly SourceBoundFieldClaim[]){const values=new Map<string,Set<string>>();for(const f of fields){const s=values.get(f.field)??new Set<string>();s.add(f.valueDigest);values.set(f.field,s);}return[...values.values()].some(v=>v.size>1);}
function fieldConflictWitnesses(fields:readonly SourceBoundFieldClaim[],options:OperationOptions):Result<readonly StateConflictWitness[]>{const groups=new Map<string,SourceBoundFieldClaim[]>();for(const f of fields){const a=groups.get(f.field)??[];a.push(f);groups.set(f.field,a);}const out:StateConflictWitness[]=[];for(const[field,claims]of groups){if(new Set(claims.map(c=>c.valueDigest)).size<2)continue;const w=createStateConflictWitness(`field:${field}`,claims.map(c=>c.claimDigest),options);if(!w.ok)return w;out.push(w.value);}return{ok:true,value:deepFreeze(out.sort(conflictSort))};}
function applyFieldSafetyFloor(decision:VerdictDecision,claim:ResponseVerdictClaim,fields:readonly SourceBoundFieldClaim[],options:OperationOptions):Result<VerdictDecision>{let floor=freshnessFloor(fields);if(hasFieldValueConflict(fields))floor='CONFLICT';if(!floor||verdictRank[decision.verdict]>=verdictRank[floor])return{ok:true,value:decision};const reasons=sortedUnique([...decision.reasons,floor==='CONFLICT'?'FIELD_STATE_CONFLICT':'FIELD_STATE_INDETERMINATE','OPTIMISTIC_OVERRIDE_REJECTED']);const verdict=floor;const d=sha(options,{verdict,reasons,verdictClaimDigest:claim.claimDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({verdict,reasons,verdictDigest:d.value})};}
function sameDecision(a:VerdictDecision,b:VerdictDecision){return a.verdict===b.verdict&&a.verdictDigest===b.verdictDigest&&JSON.stringify(a.reasons)===JSON.stringify(b.reasons);}
function metricPortableText(m:DelegatedMetricClaim){const out:string[]=[];if(typeof m.scalarValue==='string')out.push(m.scalarValue);if(m.unit!==null)out.push(m.unit);return out;}

export interface BuildMachineResponseInput{readonly capsule:ResponseContractCapsule;readonly metrics:readonly DelegatedMetricClaim[];readonly blockers:readonly BlockerProjection[];readonly conflicts:readonly StateConflictWitness[];readonly nextAction:NextNecessaryActionCapsule;readonly verdictClaim:ResponseVerdictClaim;readonly requiredFields:readonly string[];}
export function buildMachineResponseEnvelope(input:BuildMachineResponseInput,matrix:MetricOwnershipMatrix,options:OperationOptions):Result<MachineResponseEnvelope>{
 const c=cancelled(options);if(c)return c;const mm=verifyMetricOwnershipMatrix(matrix,options);if(!mm.ok)return mm;if(!mm.value)return fail('METRIC_OWNERSHIP_MATRIX_TAMPERED','Machine response requires a verified metric ownership matrix');const cv=verifyResponseContractCapsule(input.capsule,options);if(!cv.ok)return cv;if(!cv.value)return fail('RESPONSE_CAPSULE_TAMPERED','Machine response cannot be built from an invalid capsule');
 const vc=verifyResponseVerdictClaim(input.verdictClaim,options);if(!vc.ok)return vc;if(!vc.value)return fail('VERDICT_CLAIM_TAMPERED','Machine response verdict claim is invalid');if(input.verdictClaim.claimDigest!==input.capsule.verdictInputDigest)return fail('VERDICT_SOURCE_MISMATCH','Verdict claim does not bind the capsule canonical verdict input');
 const fr=buildMinimumSufficientResponseFields(input.capsule.sourceClaims,input.requiredFields,options);if(!fr.ok)return fr;const fields=fr.value;
 const metrics=[...input.metrics].sort(metricSort);for(const m of metrics){const v=verifyDelegatedMetricClaim(m,matrix,options);if(!v.ok)return v;if(!v.value)return fail('METRIC_CLAIM_TAMPERED','Machine response contains an invalid metric claim',m.metricKey);}
 const projected=projectApplicableBlockers(input.blockers,options);if(!projected.ok)return projected;const blockers=[...projected.value].sort(blockerSort);
 const fc=fieldConflictWitnesses(fields,options);if(!fc.ok)return fc;const conflicts=[...input.conflicts,...fc.value].sort(conflictSort);for(const w of conflicts){const v=verifyStateConflictWitness(w,options);if(!v.ok)return v;if(!v.value)return fail('CONFLICT_WITNESS_TAMPERED','Machine response contains an invalid conflict witness',w.subject);}
 const nv=verifyNextNecessaryActionCapsule(input.nextAction,options);if(!nv.ok)return nv;if(!nv.value)return fail('NEXT_ACTION_TAMPERED','Machine response next-action capsule is invalid');if(input.nextAction.sourceIdentityDigest!==input.capsule.nextActionSourceDigest)return fail('NEXT_ACTION_SOURCE_MISMATCH','Next action does not bind the capsule canonical next-action source');
 const portableText=[...blockers.map(b=>b.message),...metrics.flatMap(metricPortableText)];const red=assessResponseRedaction(fields,portableText,options);if(!red.ok)return red;if(!red.value.safe)return fail('RESPONSE_REDACTION_REQUIRED','Portable response contains secret-like or private locator material',red.value.rejectedFields.join(','));
 const baseVerdict=deriveResponseVerdict(blockers,conflicts,input.verdictClaim,options);if(!baseVerdict.ok)return baseVerdict;const verdict=applyFieldSafetyFloor(baseVerdict.value,input.verdictClaim,fields,options);if(!verdict.ok)return verdict;
 const pi=buildResponseProvenanceIndex(fields,options);if(!pi.ok)return pi;const semanticBody={schemaDigest:input.capsule.schema.schemaDigest,projectId:input.capsule.projectId,responseKind:input.capsule.responseKind,checkpointBindingDigest:input.capsule.checkpointBindingDigest,resumeBindingDigest:input.capsule.resumeBindingDigest,registryBindingDigest:input.capsule.registryBindingDigest,fields,metrics,blockers,conflicts,nextAction:input.nextAction,verdictClaim:input.verdictClaim,verdict:verdict.value,provenanceIndex:pi.value};
 const size=assessResponseSize(fields,metrics,blockers,pi.value.bindings.reduce((n,b)=>n+b.claimDigests.length,0),semanticBody,options);if(!size.ok)return size;if(!size.value.withinLimits)return fail('EXPANSION_REFERENCE_REQUIRED','Response exceeds configured semantic size limits');const sd=sha(options,semanticBody);if(!sd.ok)return sd;const md=sha(options,{...semanticBody,semanticDigest:sd.value});if(!md.ok)return md;
 return{ok:true,value:deepFreeze({schema:input.capsule.schema,projectId:input.capsule.projectId,responseKind:input.capsule.responseKind,checkpointBindingDigest:input.capsule.checkpointBindingDigest,resumeBindingDigest:input.capsule.resumeBindingDigest,registryBindingDigest:input.capsule.registryBindingDigest,fields,metrics,blockers,conflicts,nextAction:input.nextAction,verdictClaim:input.verdictClaim,verdict:verdict.value,provenanceIndex:pi.value,semanticDigest:sd.value,machineDigest:md.value})};
}
export function verifyMachineResponseEnvelope(machine:MachineResponseEnvelope,matrix:MetricOwnershipMatrix,options:OperationOptions):Result<boolean>{
 const mm=verifyMetricOwnershipMatrix(matrix,options);if(!mm.ok)return mm;if(!mm.value)return{ok:true,value:false};const sv=verifyResponseSchemaEnvelope(machine.schema,options);if(!sv.ok)return sv;if(!sv.value||!validId(machine.projectId)||!validId(machine.responseKind)||![machine.checkpointBindingDigest,machine.resumeBindingDigest,machine.registryBindingDigest,machine.semanticDigest,machine.machineDigest].every(isSha256))return{ok:true,value:false};
 for(const f of machine.fields){const v=verifySourceBoundFieldClaim(f,options);if(!v.ok)return v;if(!v.value)return{ok:true,value:false};}for(const m of machine.metrics){const v=verifyDelegatedMetricClaim(m,matrix,options);if(!v.ok)return v;if(!v.value)return{ok:true,value:false};}for(const b of machine.blockers){const v=verifyBlockerProjection(b,options);if(!v.ok)return v;if(!v.value)return{ok:true,value:false};}for(const w of machine.conflicts){const v=verifyStateConflictWitness(w,options);if(!v.ok)return v;if(!v.value)return{ok:true,value:false};}
 const nv=verifyNextNecessaryActionCapsule(machine.nextAction,options);if(!nv.ok||!nv.value)return nv.ok?{ok:true,value:false}:nv;const vc=verifyResponseVerdictClaim(machine.verdictClaim,options);if(!vc.ok||!vc.value)return vc.ok?{ok:true,value:false}:vc;
 const expectedBase=deriveResponseVerdict(machine.blockers,machine.conflicts,machine.verdictClaim,options);if(!expectedBase.ok)return expectedBase;const expected=applyFieldSafetyFloor(expectedBase.value,machine.verdictClaim,machine.fields,options);if(!expected.ok)return expected;if(!sameDecision(machine.verdict,expected.value))return{ok:true,value:false};if(hasFieldValueConflict(machine.fields)&&!machine.conflicts.some(w=>w.subject.startsWith('field:')&&w.hasConflict))return{ok:true,value:false};
 const pv=verifyResponseProvenanceIndex(machine.provenanceIndex,machine.fields,options);if(!pv.ok)return pv;if(!pv.value)return{ok:true,value:false};const red=assessResponseRedaction(machine.fields,[...machine.blockers.map(b=>b.message),...machine.metrics.flatMap(metricPortableText)],options);if(!red.ok)return red;if(!red.value.safe)return{ok:true,value:false};const semanticBody={schemaDigest:machine.schema.schemaDigest,projectId:machine.projectId,responseKind:machine.responseKind,checkpointBindingDigest:machine.checkpointBindingDigest,resumeBindingDigest:machine.resumeBindingDigest,registryBindingDigest:machine.registryBindingDigest,fields:machine.fields,metrics:machine.metrics,blockers:machine.blockers,conflicts:machine.conflicts,nextAction:machine.nextAction,verdictClaim:machine.verdictClaim,verdict:machine.verdict,provenanceIndex:machine.provenanceIndex};const sd=sha(options,semanticBody);if(!sd.ok)return sd;if(sd.value!==machine.semanticDigest)return{ok:true,value:false};const md=sha(options,{...semanticBody,semanticDigest:sd.value});if(!md.ok)return md;return{ok:true,value:md.value===machine.machineDigest};
}
function metricLine(m:DelegatedMetricClaim){if(m.availability!=='AVAILABLE')return`metric.${m.metricKey}=${m.availability}`;if(m.rangeValue)return`metric.${m.metricKey}=${m.rangeValue.min}..${m.rangeValue.max}${m.unit?` ${m.unit}`:''}`;return`metric.${m.metricKey}=${String(m.scalarValue)}${m.unit?` ${m.unit}`:''}`;}
export function buildHumanResponseProjection(machine:MachineResponseEnvelope,matrix:MetricOwnershipMatrix,options:OperationOptions):Result<HumanResponseProjection>{const mv=verifyMachineResponseEnvelope(machine,matrix,options);if(!mv.ok)return mv;if(!mv.value)return fail('MACHINE_RESPONSE_TAMPERED','Human projection requires a verified machine response');const lines:string[]=[];for(const f of machine.fields)lines.push(`${f.field}=${f.value}`);lines.push(`verdict=${machine.verdict.verdict}`);for(const b of machine.blockers)lines.push(`blocker.${b.blockerId}=${b.message}`);for(const m of machine.metrics)lines.push(metricLine(m));lines.push(`next_action=${machine.nextAction.state==='KNOWN'?machine.nextAction.actionRef:machine.nextAction.state}`);const red=assessResponseRedaction(machine.fields,lines,options);if(!red.ok)return red;if(!red.value.safe)return fail('HUMAN_PROJECTION_REDACTION_REQUIRED','Human response would expose secret/private material',red.value.rejectedFields.join(','));const claims=sortedUnique([...machine.fields.map(f=>f.claimDigest),...machine.metrics.map(m=>m.claimDigest),...machine.blockers.map(b=>b.blockerDigest),machine.nextAction.capsuleDigest,machine.verdictClaim.claimDigest,machine.verdict.verdictDigest]);const body={semanticDigest:machine.semanticDigest,lines,materialClaimDigests:claims};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,projectionDigest:d.value})};}
export function verifyHumanResponseProjection(human:HumanResponseProjection,machine:MachineResponseEnvelope,matrix:MetricOwnershipMatrix,options:OperationOptions):Result<boolean>{const rebuilt=buildHumanResponseProjection(machine,matrix,options);if(!rebuilt.ok)return rebuilt;return{ok:true,value:human.semanticDigest===machine.semanticDigest&&human.projectionDigest===rebuilt.value.projectionDigest&&JSON.stringify(human.lines)===JSON.stringify(rebuilt.value.lines)&&JSON.stringify(human.materialClaimDigests)===JSON.stringify(rebuilt.value.materialClaimDigests)};}
export function buildResponseIntegrityReceipt(machine:MachineResponseEnvelope,human:HumanResponseProjection|null,matrix:MetricOwnershipMatrix,options:OperationOptions):Result<ResponseIntegrityReceipt>{const mv=verifyMachineResponseEnvelope(machine,matrix,options);if(!mv.ok)return mv;let valid=mv.value;if(human){const hv=verifyHumanResponseProjection(human,machine,matrix,options);if(!hv.ok)return hv;valid=valid&&hv.value;}const body={schemaDigest:machine.schema.schemaDigest,semanticDigest:machine.semanticDigest,machineDigest:machine.machineDigest,humanProjectionDigest:human?.projectionDigest??null,sourceClaimDigests:machine.fields.map(f=>f.claimDigest).sort(compareCodePoint),metricClaimDigests:machine.metrics.map(m=>m.claimDigest).sort(compareCodePoint),blockerDigests:machine.blockers.map(b=>b.blockerDigest).sort(compareCodePoint),valid};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,receiptDigest:d.value})};}
export function checkResponseCompatibility(schema:MachineResponseEnvelope['schema'],requirement:CompatibilityRequirement,options:OperationOptions):Result<CompatibilityDecision>{const c=cancelled(options);if(c)return c;const sv=verifyResponseSchemaEnvelope(schema,options);if(!sv.ok)return sv;if(!sv.value)return fail('RESPONSE_SCHEMA_TAMPERED','Compatibility cannot be evaluated against a tampered response schema');const reasons:string[]=[];if(!requirement.supportedSchemaVersions.includes(schema.schemaVersion))reasons.push('UNSUPPORTED_SCHEMA_VERSION');if(!requirement.supportedProfiles.includes(schema.profile))reasons.push('UNSUPPORTED_PROFILE');const caps=new Set(requirement.capabilities);const missing=schema.requiredCapabilities.filter(c=>!caps.has(c)).sort(compareCodePoint);if(missing.length)reasons.push('MISSING_CAPABILITY');const body={compatible:reasons.length===0,missingCapabilities:missing,reasons:sortedUnique(reasons)};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,decisionDigest:d.value})};}
export function detectStaleResponse(machine:MachineResponseEnvelope,observation:ResponseBindingObservation,matrix:MetricOwnershipMatrix,options:OperationOptions):Result<StaleResponseReport>{const c=cancelled(options);if(c)return c;const mv=verifyMachineResponseEnvelope(machine,matrix,options);if(!mv.ok)return mv;if(!mv.value)return fail('MACHINE_RESPONSE_TAMPERED','Stale-response evaluation requires a verified machine envelope');const stale:string[]=[];if(observation.checkpointBindingDigest!==machine.checkpointBindingDigest)stale.push('checkpoint');if(observation.resumeBindingDigest!==machine.resumeBindingDigest)stale.push('resume');if(observation.registryBindingDigest!==machine.registryBindingDigest)stale.push('registry');if(observation.verdictValidityBinding!==machine.verdictClaim.validityBindingDigest)stale.push('verdict');if(observation.nextActionValidityBindingDigest!==machine.nextAction.validityBindingDigest)stale.push('next_action');if(machine.fields.length){if(!observation.fieldValidityBindings)stale.push(...machine.fields.map(f=>`field:${f.field}`));else for(const f of machine.fields)if(observation.fieldValidityBindings[f.field]!==f.validityBindingDigest)stale.push(`field:${f.field}`);}if(machine.metrics.length){if(!observation.metricValidityBindings)stale.push(...machine.metrics.map(m=>`metric:${m.metricKey}`));else for(const m of machine.metrics)if(observation.metricValidityBindings[m.metricKey]!==m.validityBindingDigest)stale.push(`metric:${m.metricKey}`);}if(machine.blockers.length){if(!observation.blockerValidityBindings)stale.push(...machine.blockers.map(b=>`blocker:${b.blockerId}`));else for(const b of machine.blockers)if(observation.blockerValidityBindings[b.blockerId]!==b.validityBindingDigest)stale.push(`blocker:${b.blockerId}`);}if(machine.conflicts.length){if(!observation.conflictWitnessDigests)stale.push(...machine.conflicts.map(w=>`conflict:${w.subject}`));else for(const w of machine.conflicts)if(observation.conflictWitnessDigests[w.subject]!==w.witnessDigest)stale.push(`conflict:${w.subject}`);}const normalized=sortedUnique(stale);const body={stale:normalized.length>0,staleSubjects:normalized};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,reportDigest:d.value})};}
