import { isCanonicalProjectId } from '@gef-bootstrap/project-identity';
import type { AliasAdmissionCapsule, NegativeRegistryKnowledge, NegativeRegistryKnowledgeEntry, OperationOptions, ProjectRegistryEntry, ProjectRegistryIndex, RegistryCollisionFinding, RegistryCollisionWitness, RegistryIndexBucket, RegistryQuery, RegistryQueryPlan, RegistryQueryResult, RepositoryKnowledgeItem, RepositoryKnowledgeMap, Result } from './types.js';
import { cancelled, compareCodePoint, deepFreeze, fail, isSha256, sha, sortedUnique, validId, validateRefs } from './utils.js';
import { verifyProjectRegistryEntry } from './s01-model.js';

function buckets(entries:readonly ProjectRegistryEntry[],selector:(entry:ProjectRegistryEntry)=>readonly string[]):readonly RegistryIndexBucket[]{const m=new Map<string,string[]>();for(const e of entries)for(const key of selector(e)){const list=m.get(key)??[];list.push(e.entryDigest);m.set(key,list);}return [...m.entries()].sort(([a],[b])=>compareCodePoint(a,b)).map(([key,ds])=>({key,entryDigests:sortedUnique(ds)}));}
function bucketLookup(bs:readonly RegistryIndexBucket[],key:string){return bs.find(x=>x.key===key)?.entryDigests??[];}

export function buildProjectRegistryIndex(entries:readonly ProjectRegistryEntry[],options:OperationOptions):Result<ProjectRegistryIndex>{
 const c=cancelled(options);if(c)return c;const max=Math.max(1,Math.min(options.maxEntries??4096,10000));if(entries.length>max)return fail('REGISTRY_ENTRY_BUDGET_EXCEEDED','Registry entry budget exceeded');
 const seen=new Set<string>();for(const e of entries){const v=verifyProjectRegistryEntry(e,options);if(!v.ok)return v as Result<ProjectRegistryIndex>;if(!v.value)return fail('REGISTRY_ENTRY_TAMPERED','Invalid entry cannot enter registry index',e.projectId);if(seen.has(e.entryDigest))continue;seen.add(e.entryDigest);}
 const canonical=[...entries].filter((e,i,a)=>a.findIndex(x=>x.entryDigest===e.entryDigest)===i).sort((a,b)=>compareCodePoint(a.projectId,b.projectId)||compareCodePoint(a.lineageId,b.lineageId)||compareCodePoint(a.entryDigest,b.entryDigest));
 const byProjectId=buckets(canonical,e=>[e.projectId]);const byLineageId=buckets(canonical,e=>[e.lineageId]);const byRepositoryIdentity=buckets(canonical,e=>[e.repositoryIdentityDigest]);const byAlias=buckets(canonical,e=>e.aliases);
 const d=sha(options,{entryDigests:canonical.map(x=>x.entryDigest),byProjectId,byLineageId,byRepositoryIdentity,byAlias});if(!d.ok)return d;return{ok:true,value:deepFreeze({entries:canonical,byProjectId,byLineageId,byRepositoryIdentity,byAlias,indexDigest:d.value})};
}

export function assessRegistryCollisions(index:ProjectRegistryIndex,options:OperationOptions):Result<RegistryCollisionWitness>{
 const rebuilt=buildProjectRegistryIndex(index.entries,options);if(!rebuilt.ok)return rebuilt as Result<RegistryCollisionWitness>;if(rebuilt.value.indexDigest!==index.indexDigest)return fail('REGISTRY_INDEX_TAMPERED','Index digest mismatch');
 const f:RegistryCollisionFinding[]=[];
 for(const b of index.byProjectId)if(b.entryDigests.length>1){const es=index.entries.filter(x=>b.entryDigests.includes(x.entryDigest));if(new Set(es.map(x=>x.lineageId)).size>1||new Set(es.map(x=>x.repositoryIdentityDigest)).size>1)f.push({kind:'PROJECT_ID_CONFLICT',key:b.key,entryDigests:b.entryDigests});}
 for(const b of index.byLineageId)if(b.entryDigests.length>1){const es=index.entries.filter(x=>b.entryDigests.includes(x.entryDigest));if(new Set(es.map(x=>x.projectId)).size>1)f.push({kind:'LINEAGE_CONFLICT',key:b.key,entryDigests:b.entryDigests});}
 for(const b of index.byRepositoryIdentity)if(b.entryDigests.length>1){const es=index.entries.filter(x=>b.entryDigests.includes(x.entryDigest));if(new Set(es.map(x=>x.projectId)).size>1)f.push({kind:'REPOSITORY_IDENTITY_COLLISION',key:b.key,entryDigests:b.entryDigests});}
 for(const b of index.byAlias)if(b.entryDigests.length>1)f.push({kind:'ALIAS_AMBIGUITY',key:b.key,entryDigests:b.entryDigests});
 f.sort((a,b)=>compareCodePoint(a.kind,b.kind)||compareCodePoint(a.key,b.key));const d=sha(options,{findings:f});if(!d.ok)return d;return{ok:true,value:deepFreeze({findings:f,hasConflict:f.length>0,witnessDigest:d.value})};
}

export function createAliasAdmissionCapsule(alias:string,entry:ProjectRegistryEntry,options:OperationOptions):Result<AliasAdmissionCapsule>{
 if(!validId(alias)||!entry.aliases.includes(alias))return fail('REGISTRY_ALIAS_NOT_ADMITTED','Alias must already be admitted on the canonical registry entry');
 const v=verifyProjectRegistryEntry(entry,options);if(!v.ok)return v as Result<AliasAdmissionCapsule>;if(!v.value)return fail('REGISTRY_ENTRY_TAMPERED','Cannot bind alias to invalid entry');
 const core={alias,projectId:entry.projectId,lineageId:entry.lineageId,repositoryIdentityDigest:entry.repositoryIdentityDigest};const d=sha(options,core);if(!d.ok)return d;return{ok:true,value:deepFreeze({...core,capsuleDigest:d.value})};
}
function verifyAliasCapsule(c:AliasAdmissionCapsule,options:OperationOptions){const d=sha(options,{alias:c.alias,projectId:c.projectId,lineageId:c.lineageId,repositoryIdentityDigest:c.repositoryIdentityDigest});return d.ok&&d.value===c.capsuleDigest;}

export function buildRegistryQueryPlan(query:RegistryQuery,options:OperationOptions):Result<RegistryQueryPlan>{
 if(query.projectId!==undefined&&!isCanonicalProjectId(query.projectId))return fail('REGISTRY_QUERY_PROJECT_ID_INVALID','Project query key must be canonical M03 UUIDv4');if(query.lineageId!==undefined&&!validId(query.lineageId))return fail('REGISTRY_QUERY_LINEAGE_INVALID','Lineage query key is invalid');if(query.repositoryIdentityDigest!==undefined&&!isSha256(query.repositoryIdentityDigest))return fail('REGISTRY_QUERY_REPOSITORY_DIGEST_INVALID','Repository identity query must be SHA-256');if(query.alias!==undefined&&!validId(query.alias))return fail('REGISTRY_QUERY_ALIAS_INVALID','Alias query key is invalid');
 const indexes:('PROJECT_ID'|'LINEAGE_ID'|'REPOSITORY_IDENTITY'|'ALIAS')[]=[];if(query.projectId)indexes.push('PROJECT_ID');if(query.lineageId)indexes.push('LINEAGE_ID');if(query.repositoryIdentityDigest)indexes.push('REPOSITORY_IDENTITY');if(query.alias)indexes.push('ALIAS');if(indexes.length===0)return fail('REGISTRY_QUERY_EMPTY','At least one registry query key is required');const d=sha(options,{indexes});if(!d.ok)return d;return{ok:true,value:deepFreeze({indexes,bounded:true,planDigest:d.value})};
}

export function queryProjectRegistry(index:ProjectRegistryIndex,query:RegistryQuery,options:OperationOptions):Result<RegistryQueryResult>{
 const c=cancelled(options);if(c)return c;const plan=buildRegistryQueryPlan(query,options);if(!plan.ok)return plan as Result<RegistryQueryResult>;const rebuilt=buildProjectRegistryIndex(index.entries,options);if(!rebuilt.ok)return rebuilt as Result<RegistryQueryResult>;if(rebuilt.value.indexDigest!==index.indexDigest)return fail('REGISTRY_INDEX_TAMPERED','Index digest mismatch');
 let candidates=index.entries.map(x=>x.entryDigest);const intersect=(next:readonly string[])=>{const s=new Set(next);candidates=candidates.filter(x=>s.has(x));};
 if(query.projectId)intersect(bucketLookup(index.byProjectId,query.projectId));if(query.lineageId)intersect(bucketLookup(index.byLineageId,query.lineageId));if(query.repositoryIdentityDigest)intersect(bucketLookup(index.byRepositoryIdentity,query.repositoryIdentityDigest));if(query.alias)intersect(bucketLookup(index.byAlias,query.alias));candidates=sortedUnique(candidates);
 const reasons:string[]=[];let match:RegistryQueryResult['match'];let selected:string|null=null;
 if(candidates.length===0){match='ABSENT';reasons.push('NO_MATCH');}
 else {const es=index.entries.filter(x=>candidates.includes(x.entryDigest));const active=es.filter(x=>x.state==='ACTIVE');const unresolved=es.filter(x=>x.state!=='ACTIVE');if(candidates.length>1){match='CONFLICT';reasons.push('MULTIPLE_CANDIDATES');}else if(unresolved.length>0){match='UNKNOWN';reasons.push(`ENTRY_${unresolved[0]?.state??'UNKNOWN'}`);}else {const strong=Boolean(query.projectId||query.repositoryIdentityDigest);let aliasBound=false;if(query.alias&&query.aliasAdmission&&verifyAliasCapsule(query.aliasAdmission,options)){const e=active[0];aliasBound=Boolean(e&&query.aliasAdmission.alias===query.alias&&query.aliasAdmission.projectId===e.projectId&&query.aliasAdmission.lineageId===e.lineageId&&query.aliasAdmission.repositoryIdentityDigest===e.repositoryIdentityDigest);}if(strong||aliasBound){match='EXACT';selected=active[0]?.entryDigest??null;reasons.push(strong?'STRONG_IDENTITY_MATCH':'ADMITTED_ALIAS_MATCH');}else{match='POSSIBLE';reasons.push('WEAK_KEY_ONLY');}}}
 const core={match,entryDigests:candidates,selectedEntryDigest:selected,reasons:sortedUnique(reasons)};const d=sha(options,core);if(!d.ok)return d;return{ok:true,value:deepFreeze({...core,resultDigest:d.value})};
}

export function buildRepositoryKnowledgeMap(items:readonly RepositoryKnowledgeItem[],currentBindingDigest:string,options:OperationOptions):Result<RepositoryKnowledgeMap>{
 if(!isSha256(currentBindingDigest))return fail('REGISTRY_KNOWLEDGE_BINDING_INVALID','Knowledge map requires current SHA-256 binding');if(items.length>(options.maxRefs??32768))return fail('REGISTRY_REFERENCE_BUDGET_EXCEEDED','Knowledge map reference budget exceeded');const ids=new Set<string>();for(const i of items){if(!validId(i.knowledgeId)||!validId(i.domain)||!validId(i.refId)||!isSha256(i.validityBindingDigest)||!validateRefs(i.dependencyKeys)||ids.has(i.knowledgeId))return fail('REGISTRY_KNOWLEDGE_ITEM_INVALID','Knowledge map item is invalid or duplicated');ids.add(i.knowledgeId);}const canonical=[...items].map(i=>({...i,dependencyKeys:sortedUnique(i.dependencyKeys)})).sort((a,b)=>compareCodePoint(a.knowledgeId,b.knowledgeId));const d=sha(options,{items:canonical,currentBindingDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({items:canonical,currentBindingDigest,mapDigest:d.value})};
}

export function createNegativeRegistryKnowledge(entries:readonly NegativeRegistryKnowledgeEntry[],options:OperationOptions):Result<NegativeRegistryKnowledge>{
 const seen=new Set<string>();for(const e of entries){const k=`${e.keyKind}:${e.key}`;if(!validId(e.key)||!isSha256(e.absenceProofDigest)||!isSha256(e.validityBindingDigest)||seen.has(k))return fail('REGISTRY_NEGATIVE_KNOWLEDGE_INVALID','Negative registry knowledge entry invalid or duplicated');seen.add(k);}const canonical=[...entries].sort((a,b)=>compareCodePoint(a.keyKind,b.keyKind)||compareCodePoint(a.key,b.key));const d=sha(options,{entries:canonical});if(!d.ok)return d;return{ok:true,value:deepFreeze({entries:canonical,knowledgeDigest:d.value})};
}
export function verifyNegativeRegistryKnowledge(knowledge:NegativeRegistryKnowledge,options:OperationOptions):Result<boolean>{const r=createNegativeRegistryKnowledge(knowledge.entries,options);return r.ok?{ok:true,value:r.value.knowledgeDigest===knowledge.knowledgeDigest}:r;}
export function negativeRegistryKnowledgeApplies(knowledge:NegativeRegistryKnowledge,keyKind:NegativeRegistryKnowledgeEntry['keyKind'],key:string,currentBindingDigest:string,options:OperationOptions):Result<boolean>{const v=verifyNegativeRegistryKnowledge(knowledge,options);if(!v.ok)return v;if(!v.value)return fail('REGISTRY_NEGATIVE_KNOWLEDGE_TAMPERED','Negative knowledge digest mismatch');return{ok:true,value:knowledge.entries.some(e=>e.keyKind===keyKind&&e.key===key&&e.validityBindingDigest===currentBindingDigest)};}
