import { isCanonicalProjectId } from '@gef-bootstrap/project-identity';
import type { NegativeDiagnosticCache, NegativeDiagnosticCacheEntry, OperationOptions, ProjectRegistryEntry, RegistryFreshnessObservation, RegistryFreshnessVector, RegistryPromotionFence, RegistryRepairPlan, RegistrySemanticVersion, RegistrySplitBrainReport, Result, StaleEntryQuarantine, TombstoneLineageRecord, RegistryMutationIntent } from './types.js';
import { cancelled, compareCodePoint, deepFreeze, fail, isSha256, sha, sortedUnique, validId } from './utils.js';
import { verifyProjectRegistryEntry, verifyRegistryMutationIntent } from './s01-model.js';

export function buildRegistrySemanticVersion(snapshotDigest:string,options:OperationOptions):Result<RegistrySemanticVersion>{if(!isSha256(snapshotDigest))return fail('REGISTRY_SNAPSHOT_DIGEST_INVALID','Semantic version requires a snapshot SHA-256 digest');const d=sha(options,{schemaVersion:1,snapshotDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({snapshotDigest,version:d.value})};}
export function compareRegistryVersion(expectedVersion:string,currentVersion:string){return expectedVersion===currentVersion?'MATCH' as const:'STALE' as const;}
export function createRegistryPromotionFence(expectedVersion:string,intentDigest:string,options:OperationOptions):Result<RegistryPromotionFence>{if(!isSha256(expectedVersion)||!isSha256(intentDigest))return fail('REGISTRY_FENCE_INPUT_INVALID','Fence requires exact SHA-256 version and intent bindings');const d=sha(options,{expectedVersion,intentDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({expectedVersion,intentDigest,fenceDigest:d.value})};}
export function verifyRegistryPromotionFence(value:RegistryPromotionFence,options:OperationOptions):Result<boolean>{const r=createRegistryPromotionFence(value.expectedVersion,value.intentDigest,options);return r.ok?{ok:true,value:r.value.fenceDigest===value.fenceDigest}:r;}

export function detectRegistrySplitBrain(baseVersion:string,successorVersions:readonly string[],options:OperationOptions):Result<RegistrySplitBrainReport>{if(!isSha256(baseVersion)||successorVersions.some(x=>!isSha256(x)))return fail('REGISTRY_SPLIT_BRAIN_INPUT_INVALID','Split-brain detector requires SHA-256 versions');const succ=sortedUnique(successorVersions);const divergent=succ.length>1;const d=sha(options,{baseVersion,successorVersions:succ,divergent});if(!d.ok)return d;return{ok:true,value:deepFreeze({baseVersion,successorVersions:succ,divergent,reportDigest:d.value})};}
function state(expected:string|null,observed:string|null|undefined):RegistryFreshnessVector['identity']{if(observed===undefined)return'UNKNOWN';if(observed===null)return expected===null?'SAME':'MISSING';return observed===expected?'SAME':'CHANGED';}
function validFreshnessState(value:unknown){return value==='SAME'||value==='CHANGED'||value==='MISSING'||value==='UNKNOWN';}
export function buildRegistryFreshnessVector(entry:ProjectRegistryEntry,observation:RegistryFreshnessObservation,knowledgeBindingDigest:string,options:OperationOptions):Result<RegistryFreshnessVector>{const v=verifyProjectRegistryEntry(entry,options);if(!v.ok)return v as Result<RegistryFreshnessVector>;if(!v.value)return fail('REGISTRY_ENTRY_TAMPERED','Freshness cannot be computed from invalid entry');if(!isSha256(knowledgeBindingDigest))return fail('REGISTRY_KNOWLEDGE_BINDING_INVALID','Freshness requires knowledge binding digest');const identity=state(entry.identityEnvelopeDigest,observation.identityEnvelopeDigest);const repository=state(entry.repositoryIdentityDigest,observation.repositoryIdentityDigest);const checkpoint=state(entry.checkpointDigest,observation.checkpointDigest);const knowledge=state(knowledgeBindingDigest,observation.knowledgeBindingDigest);const stale=[identity,repository,checkpoint,knowledge].some(x=>x!=='SAME');const core={projectId:entry.projectId,identity,repository,checkpoint,knowledge,stale};const d=sha(options,core);if(!d.ok)return d;return{ok:true,value:deepFreeze({...core,vectorDigest:d.value})};}
export function verifyRegistryFreshnessVector(vector:RegistryFreshnessVector,options:OperationOptions):Result<boolean>{if(!isCanonicalProjectId(vector.projectId)||!validFreshnessState(vector.identity)||!validFreshnessState(vector.repository)||!validFreshnessState(vector.checkpoint)||!validFreshnessState(vector.knowledge)||!isSha256(vector.vectorDigest))return{ok:true,value:false};const expectedStale=[vector.identity,vector.repository,vector.checkpoint,vector.knowledge].some(x=>x!=='SAME');if(vector.stale!==expectedStale)return{ok:true,value:false};const d=sha(options,{projectId:vector.projectId,identity:vector.identity,repository:vector.repository,checkpoint:vector.checkpoint,knowledge:vector.knowledge,stale:vector.stale});return d.ok?{ok:true,value:d.value===vector.vectorDigest}:d;}
export function quarantineStaleEntries(entries:readonly ProjectRegistryEntry[],vectors:readonly RegistryFreshnessVector[],options:OperationOptions):Result<StaleEntryQuarantine>{const vectorMap=new Map<string,RegistryFreshnessVector>();for(const vector of vectors){const vv=verifyRegistryFreshnessVector(vector,options);if(!vv.ok)return vv as Result<StaleEntryQuarantine>;if(!vv.value)return fail('REGISTRY_FRESHNESS_VECTOR_TAMPERED','Freshness vector is malformed or tampered',vector.projectId);if(vectorMap.has(vector.projectId))return fail('REGISTRY_FRESHNESS_VECTOR_DUPLICATE','Multiple freshness vectors exist for one project',vector.projectId);vectorMap.set(vector.projectId,vector);}const active:string[]=[];const quarantined:string[]=[];for(const entry of entries){const ev=verifyProjectRegistryEntry(entry,options);if(!ev.ok)return ev as Result<StaleEntryQuarantine>;if(!ev.value)return fail('REGISTRY_ENTRY_TAMPERED','Quarantine cannot process invalid registry entry',entry.projectId);const vector=vectorMap.get(entry.projectId);if(entry.state==='ACTIVE'&&vector!==undefined&&!vector.stale)active.push(entry.entryDigest);else quarantined.push(entry.entryDigest);}const activeEntryDigests=sortedUnique(active);const quarantinedEntryDigests=sortedUnique(quarantined);const d=sha(options,{activeEntryDigests,quarantinedEntryDigests});if(!d.ok)return d;return{ok:true,value:deepFreeze({activeEntryDigests,quarantinedEntryDigests,quarantineDigest:d.value})};}
export function buildRegistryRepairPlan(entry:ProjectRegistryEntry,vector:RegistryFreshnessVector,dependencyKnowledgeComplete:boolean,options:OperationOptions):Result<RegistryRepairPlan>{const ev=verifyProjectRegistryEntry(entry,options);if(!ev.ok)return ev as Result<RegistryRepairPlan>;if(!ev.value)return fail('REGISTRY_ENTRY_TAMPERED','Repair cannot process invalid registry entry',entry.projectId);const vv=verifyRegistryFreshnessVector(vector,options);if(!vv.ok)return vv as Result<RegistryRepairPlan>;if(!vv.value||vector.projectId!==entry.projectId)return fail('REGISTRY_FRESHNESS_VECTOR_INVALID','Repair requires a valid freshness vector for the same project');const actions:string[]=[];if(vector.identity!=='SAME')actions.push('REFRESH_CANONICAL_IDENTITY');if(vector.repository!=='SAME')actions.push('REFRESH_REPOSITORY_IDENTITY');if(vector.checkpoint!=='SAME')actions.push('REFRESH_CHECKPOINT_POINTER');if(vector.knowledge!=='SAME')actions.push('REBUILD_KNOWLEDGE_BINDINGS');if(!dependencyKnowledgeComplete)actions.push('WIDEN_DEPENDENCY_REFRESH');const requiresCanonicalRefresh=actions.length>0;const core={projectId:entry.projectId,actions:sortedUnique(actions),requiresCanonicalRefresh};const d=sha(options,core);if(!d.ok)return d;return{ok:true,value:deepFreeze({...core,planDigest:d.value})};}
export function createNegativeDiagnosticCache(entries:readonly NegativeDiagnosticCacheEntry[],options:OperationOptions):Result<NegativeDiagnosticCache>{const c=cancelled(options);if(c)return c;const keys=new Set<string>();for(const e of entries){if(!isSha256(e.failureFingerprint)||!validId(e.subject)||!isSha256(e.validityBindingDigest)){return fail('REGISTRY_DIAGNOSTIC_CACHE_INVALID','Diagnostic cache entry invalid');}const k=`${e.subject}:${e.failureFingerprint}`;if(keys.has(k))return fail('REGISTRY_DIAGNOSTIC_CACHE_DUPLICATE','Duplicate diagnostic cache entry');keys.add(k);}const canonical=[...entries].sort((a,b)=>compareCodePoint(a.subject,b.subject)||compareCodePoint(a.failureFingerprint,b.failureFingerprint));const d=sha(options,{entries:canonical});if(!d.ok)return d;return{ok:true,value:deepFreeze({entries:canonical,cacheDigest:d.value})};}
export function verifyNegativeDiagnosticCache(cache:NegativeDiagnosticCache,options:OperationOptions):Result<boolean>{const r=createNegativeDiagnosticCache(cache.entries,options);return r.ok?{ok:true,value:r.value.cacheDigest===cache.cacheDigest}:r;}
export function negativeDiagnosticCacheApplies(cache:NegativeDiagnosticCache,subject:string,failureFingerprint:string,currentBindingDigest:string,options:OperationOptions):Result<boolean>{const v=verifyNegativeDiagnosticCache(cache,options);if(!v.ok)return v;if(!v.value)return fail('REGISTRY_DIAGNOSTIC_CACHE_TAMPERED','Diagnostic cache digest mismatch');return{ok:true,value:cache.entries.some(e=>e.subject===subject&&e.failureFingerprint===failureFingerprint&&e.validityBindingDigest===currentBindingDigest)};}
export function createTombstoneLineageRecord(entry:ProjectRegistryEntry,intent:RegistryMutationIntent,options:OperationOptions):Result<TombstoneLineageRecord>{const ev=verifyProjectRegistryEntry(entry,options);if(!ev.ok)return ev as Result<TombstoneLineageRecord>;if(!ev.value)return fail('REGISTRY_ENTRY_TAMPERED','Tombstone cannot bind invalid entry');const iv=verifyRegistryMutationIntent(intent,options);if(!iv.ok)return iv as Result<TombstoneLineageRecord>;if(!iv.value||intent.kind!=='TOMBSTONE'||intent.projectId!==entry.projectId)return fail('REGISTRY_TOMBSTONE_INTENT_INVALID','Tombstone intent must be valid and project-bound');const core={projectId:entry.projectId,lineageId:entry.lineageId,predecessorEntryDigest:entry.entryDigest,mutationIntentDigest:intent.intentDigest,provenanceDigest:entry.provenanceDigest};const d=sha(options,core);if(!d.ok)return d;return{ok:true,value:deepFreeze({...core,tombstoneDigest:d.value})};}

export function verifyTombstoneLineageRecord(value:TombstoneLineageRecord,options:OperationOptions):Result<boolean>{if(!isCanonicalProjectId(value.projectId)||!isSha256(value.predecessorEntryDigest)||!isSha256(value.mutationIntentDigest)||!isSha256(value.provenanceDigest)||!isSha256(value.tombstoneDigest)||!validId(value.lineageId))return{ok:true,value:false};const d=sha(options,{projectId:value.projectId,lineageId:value.lineageId,predecessorEntryDigest:value.predecessorEntryDigest,mutationIntentDigest:value.mutationIntentDigest,provenanceDigest:value.provenanceDigest});return d.ok?{ok:true,value:d.value===value.tombstoneDigest}:d;}
