import type{CreditEligibilityResult,DenominatorIntegrityManifest,DenominatorManifestInput,DenominatorMutationWitness,DenominatorUnit,DenominatorUnitInput,EvidenceAcceptanceBinding,EvidenceAcceptanceBindingInput,OperationOptions,ProgressAuthorityBoundary,ProgressBaselineCapsule,Result,ScopeDodBinding,WeightedCreditUnit}from'./types.js';
import{addSafe,allSha,cancelled,compareCodePoint,deepFreeze,fail,isSha256,positiveWeight,sha,sortedUnique,stableJson,validId}from'./utils.js';

function buildUnit(input:DenominatorUnitInput,options:OperationOptions):Result<DenominatorUnit>{if(!validId(input.unitId)||!validId(input.moduleId)||!validId(input.areaId)||!validId(input.phaseId))return fail('UNIT_ID_INVALID','Denominator unit identifiers are invalid',input.unitId);if(!positiveWeight(input.maxWeight))return fail('UNIT_WEIGHT_INVALID','Denominator unit weight must be a positive safe integer',input.unitId);const deps=sortedUnique(input.dependencyDigests??[]);if(!allSha(deps))return fail('UNIT_DEPENDENCY_INVALID','Unit dependency bindings must be SHA-256 digests',input.unitId);const body={unitId:input.unitId,moduleId:input.moduleId,areaId:input.areaId,phaseId:input.phaseId,maxWeight:input.maxWeight,dependencyDigests:deps};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,unitDigest:d.value})};}

export function createDenominatorIntegrityManifest(input:DenominatorManifestInput,options:OperationOptions):Result<DenominatorIntegrityManifest>{const c=cancelled(options);if(c)return c;if(!validId(input.projectId)||!validId(input.epochId))return fail('MANIFEST_ID_INVALID','Project and epoch identifiers must be bounded opaque identifiers');if(!allSha([input.lineageDigest,input.scopeDigest,input.dodDigest,input.policyDigest]))return fail('MANIFEST_BINDING_INVALID','Manifest authority bindings must be SHA-256 digests');if(input.units.length===0)return fail('DENOMINATOR_EMPTY','Production denominator cannot be empty');const built:DenominatorUnit[]=[];const ids=new Set<string>();for(const raw of input.units){const unit=buildUnit(raw,options);if(!unit.ok)return unit;if(ids.has(unit.value.unitId))return fail('DUPLICATE_UNIT','Denominator unit IDs must be unique',unit.value.unitId);ids.add(unit.value.unitId);built.push(unit.value);}const excluded=sortedUnique(input.excludedUnitIds??[]);if(!excluded.every(validId))return fail('EXCLUDED_ID_INVALID','Excluded unit IDs must be bounded identifiers');if(excluded.some(id=>ids.has(id)))return fail('EXCLUDED_UNIT_IN_DENOMINATOR','Excluded unit cannot also be a production denominator unit');const units=[...built].sort((a,b)=>compareCodePoint(a.unitId,b.unitId));const total=addSafe(units.map(u=>u.maxWeight));if(!total.ok)return total;if(total.value<=0)return fail('DENOMINATOR_ZERO','Production denominator must be greater than zero');const body={projectId:input.projectId,lineageDigest:input.lineageDigest,epochId:input.epochId,scopeDigest:input.scopeDigest,dodDigest:input.dodDigest,policyDigest:input.policyDigest,units,excludedUnitIds:excluded,totalWeight:total.value};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,manifestDigest:d.value})};}

export function verifyDenominatorIntegrityManifest(value:DenominatorIntegrityManifest,options:OperationOptions):Result<boolean>{const rebuilt=createDenominatorIntegrityManifest({projectId:value.projectId,lineageDigest:value.lineageDigest,epochId:value.epochId,scopeDigest:value.scopeDigest,dodDigest:value.dodDigest,policyDigest:value.policyDigest,units:value.units.map(u=>({unitId:u.unitId,moduleId:u.moduleId,areaId:u.areaId,phaseId:u.phaseId,maxWeight:u.maxWeight,dependencyDigests:u.dependencyDigests})),excludedUnitIds:value.excludedUnitIds},options);if(!rebuilt.ok)return rebuilt;return{ok:true,value:stableJson(rebuilt.value)===stableJson(value)};}

export function createProgressBaselineCapsule(manifest:DenominatorIntegrityManifest,options:OperationOptions):Result<ProgressBaselineCapsule>{const v=verifyDenominatorIntegrityManifest(manifest,options);if(!v.ok||!v.value)return v.ok?fail('MANIFEST_TAMPERED','Progress baseline requires a verified denominator manifest'):v;const body={projectId:manifest.projectId,lineageDigest:manifest.lineageDigest,epochId:manifest.epochId,manifestDigest:manifest.manifestDigest,scopeDigest:manifest.scopeDigest,dodDigest:manifest.dodDigest,policyDigest:manifest.policyDigest};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,capsuleDigest:d.value})};}
export function verifyProgressBaselineCapsule(value:ProgressBaselineCapsule,options:OperationOptions):Result<boolean>{if(!validId(value.projectId)||!validId(value.epochId)||!allSha([value.lineageDigest,value.manifestDigest,value.scopeDigest,value.dodDigest,value.policyDigest]))return{ok:true,value:false};const d=sha(options,{projectId:value.projectId,lineageDigest:value.lineageDigest,epochId:value.epochId,manifestDigest:value.manifestDigest,scopeDigest:value.scopeDigest,dodDigest:value.dodDigest,policyDigest:value.policyDigest});return d.ok?{ok:true,value:d.value===value.capsuleDigest}:d;}

export function createProgressAuthorityBoundary(baseline:ProgressBaselineCapsule,options:OperationOptions):Result<ProgressAuthorityBoundary>{const v=verifyProgressBaselineCapsule(baseline,options);if(!v.ok||!v.value)return v.ok?fail('BASELINE_TAMPERED','Authority boundary requires verified baseline'):v;const body={baselineDigest:baseline.capsuleDigest,mayMintScope:false as const,mayDecideEvidence:false as const,mayEstimateEta:false as const,mayComputeProjectStatus:false as const,authority:'CALCULATION_ONLY' as const};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,boundaryDigest:d.value})};}

export function createScopeDodBinding(scopeDigest:string,dodDigest:string,options:OperationOptions):Result<ScopeDodBinding>{if(!allSha([scopeDigest,dodDigest]))return fail('SCOPE_DOD_BINDING_INVALID','Scope and DoD identities must be SHA-256 digests');const d=sha(options,{scopeDigest,dodDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({scopeDigest,dodDigest,bindingDigest:d.value})};}

export function createEvidenceAcceptanceBinding(input:EvidenceAcceptanceBindingInput,options:OperationOptions):Result<EvidenceAcceptanceBinding>{const c=cancelled(options);if(c)return c;if(!validId(input.unitId)||!validId(input.owner))return fail('EVIDENCE_BINDING_ID_INVALID','Evidence acceptance binding identifiers are invalid');if(input.owner==='M21_PROGRESS')return fail('SELF_AUTHORITY_FORBIDDEN','Progress Engine cannot mint its own evidence acceptance authority',input.unitId);if(!['ACCEPTED','REJECTED','STALE','CONFLICT','UNKNOWN'].includes(input.state))return fail('EVIDENCE_STATE_INVALID','Evidence acceptance state is invalid',input.unitId);if(!allSha([input.sourceIdentityDigest,input.validityBindingDigest]))return fail('EVIDENCE_BINDING_DIGEST_INVALID','Evidence binding identities must be SHA-256 digests',input.unitId);const d=sha(options,input);if(!d.ok)return d;return{ok:true,value:deepFreeze({...input,bindingDigest:d.value})};}
export function verifyEvidenceAcceptanceBinding(value:EvidenceAcceptanceBinding,options:OperationOptions):Result<boolean>{const rebuilt=createEvidenceAcceptanceBinding({unitId:value.unitId,owner:value.owner,state:value.state,sourceIdentityDigest:value.sourceIdentityDigest,validityBindingDigest:value.validityBindingDigest},options);return rebuilt.ok?{ok:true,value:rebuilt.value.bindingDigest===value.bindingDigest}:rebuilt;}

export function createWeightedCreditUnit(unit:DenominatorUnit,binding:EvidenceAcceptanceBinding,options:OperationOptions):Result<WeightedCreditUnit>{const vb=verifyEvidenceAcceptanceBinding(binding,options);if(!vb.ok||!vb.value)return vb.ok?fail('EVIDENCE_BINDING_TAMPERED','Weighted credit requires verified evidence binding',unit.unitId):vb;if(binding.unitId!==unit.unitId)return fail('UNIT_BINDING_MISMATCH','Evidence binding belongs to another unit',unit.unitId);let state:'EARNED'|'ZERO'|'QUARANTINED'='ZERO';let earnedWeight=0;if(binding.state==='ACCEPTED'){state='EARNED';earnedWeight=unit.maxWeight;}else if(binding.state==='STALE'||binding.state==='CONFLICT'||binding.state==='UNKNOWN')state='QUARANTINED';const body={unitId:unit.unitId,moduleId:unit.moduleId,areaId:unit.areaId,phaseId:unit.phaseId,maxWeight:unit.maxWeight,earnedWeight,state,evidenceBindingDigest:binding.bindingDigest,validityBindingDigest:binding.validityBindingDigest};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,creditDigest:d.value})};}
export function verifyWeightedCreditUnit(value:WeightedCreditUnit,manifest:DenominatorIntegrityManifest,bindings:readonly EvidenceAcceptanceBinding[],options:OperationOptions):Result<boolean>{const unit=manifest.units.find(u=>u.unitId===value.unitId);const binding=bindings.find(b=>b.unitId===value.unitId);if(!unit||!binding)return{ok:true,value:false};const rebuilt=createWeightedCreditUnit(unit,binding,options);return rebuilt.ok?{ok:true,value:stableJson(rebuilt.value)===stableJson(value)}:rebuilt;}

export function evaluateCreditEligibility(manifest:DenominatorIntegrityManifest,bindings:readonly EvidenceAcceptanceBinding[],options:OperationOptions):Result<CreditEligibilityResult>{const c=cancelled(options);if(c)return c;const vm=verifyDenominatorIntegrityManifest(manifest,options);if(!vm.ok||!vm.value)return vm.ok?fail('MANIFEST_TAMPERED','Credit eligibility requires verified denominator manifest'):vm;const byUnit=new Map<string,EvidenceAcceptanceBinding>();for(const b of bindings){const vb=verifyEvidenceAcceptanceBinding(b,options);if(!vb.ok||!vb.value)return vb.ok?fail('EVIDENCE_BINDING_TAMPERED','Credit eligibility rejected tampered evidence binding',b.unitId):vb;if(byUnit.has(b.unitId))return fail('DUPLICATE_EVIDENCE_BINDING','Only one current evidence binding per unit is allowed',b.unitId);if(manifest.excludedUnitIds.includes(b.unitId))return fail('EXCLUDED_UNIT_CREDIT_ATTEMPT','Excluded unit cannot contribute to production progress',b.unitId);if(!manifest.units.some(u=>u.unitId===b.unitId))return fail('UNKNOWN_CREDIT_UNIT','Evidence binding references unit outside denominator',b.unitId);byUnit.set(b.unitId,b);}const credits:WeightedCreditUnit[]=[];const missing:string[]=[];const rejected:string[]=[];for(const unit of manifest.units){const b=byUnit.get(unit.unitId);if(!b){missing.push(unit.unitId);continue;}const credit=createWeightedCreditUnit(unit,b,options);if(!credit.ok)return credit;credits.push(credit.value);if(b.state==='REJECTED')rejected.push(unit.unitId);}credits.sort((a,b)=>compareCodePoint(a.unitId,b.unitId));const body={credits,missingUnitIds:missing.sort(compareCodePoint),rejectedUnitIds:rejected.sort(compareCodePoint)};const d=sha(options,{creditDigests:credits.map(x=>x.creditDigest),missingUnitIds:body.missingUnitIds,rejectedUnitIds:body.rejectedUnitIds,manifestDigest:manifest.manifestDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,gateDigest:d.value})};}

export function createDenominatorMutationWitness(before:DenominatorIntegrityManifest,after:DenominatorIntegrityManifest,authorizationDigest:string,options:OperationOptions):Result<DenominatorMutationWitness>{const vb=verifyDenominatorIntegrityManifest(before,options);if(!vb.ok||!vb.value)return vb.ok?fail('BEFORE_MANIFEST_TAMPERED','Mutation witness requires verified before manifest'):vb;const va=verifyDenominatorIntegrityManifest(after,options);if(!va.ok||!va.value)return va.ok?fail('AFTER_MANIFEST_TAMPERED','Mutation witness requires verified after manifest'):va;if(before.projectId!==after.projectId||before.lineageDigest!==after.lineageDigest)return fail('DENOMINATOR_PROJECT_MISMATCH','Denominator mutation cannot cross project or lineage');if(before.epochId===after.epochId)return fail('DENOMINATOR_EPOCH_REUSED','Denominator mutation requires a new epoch');if(!isSha256(authorizationDigest))return fail('DENOMINATOR_AUTH_INVALID','Denominator mutation requires governed authorization digest');const bm=new Map(before.units.map(u=>[u.unitId,u]));const am=new Map(after.units.map(u=>[u.unitId,u]));const added=[...am.keys()].filter(id=>!bm.has(id)).sort(compareCodePoint);const removed=[...bm.keys()].filter(id=>!am.has(id)).sort(compareCodePoint);const reweighted=[...bm.keys()].filter(id=>{const x=bm.get(id),y=am.get(id);return x&&y&&stableJson({moduleId:x.moduleId,areaId:x.areaId,phaseId:x.phaseId,maxWeight:x.maxWeight,dependencyDigests:x.dependencyDigests})!==stableJson({moduleId:y.moduleId,areaId:y.areaId,phaseId:y.phaseId,maxWeight:y.maxWeight,dependencyDigests:y.dependencyDigests});}).sort(compareCodePoint);const body={beforeManifestDigest:before.manifestDigest,afterManifestDigest:after.manifestDigest,beforeEpochId:before.epochId,afterEpochId:after.epochId,authorizationDigest,addedUnitIds:added,removedUnitIds:removed,reweightedUnitIds:reweighted,beforeTotalWeight:before.totalWeight,afterTotalWeight:after.totalWeight};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,witnessDigest:d.value})};}
export function verifyDenominatorMutationWitness(value:DenominatorMutationWitness,before:DenominatorIntegrityManifest,after:DenominatorIntegrityManifest,options:OperationOptions):Result<boolean>{const rebuilt=createDenominatorMutationWitness(before,after,value.authorizationDigest,options);return rebuilt.ok?{ok:true,value:stableJson(rebuilt.value)===stableJson(value)}:rebuilt;}
