import type{CreditDependencyEntry,CreditDependencyGraph,CreditRetractionTransaction,DenominatorDriftDecision,DenominatorIntegrityManifest,DenominatorMutationWitness,OperationOptions,ProgressBindingObservation,ProgressDriftReport,ProgressInvalidationVector,ProgressQuery,ProgressRegressionReceipt,ProgressSnapshotCapsule,ProgressSplitBrainWitness,Result,StaleCreditQuarantine,StaleCreditQuarantineEntry,WeightedCreditUnit}from'./types.js';
import{allSha,cancelled,compareCodePoint,deepFreeze,fail,isSha256,limits,sha,sortedUnique,stableJson,validId}from'./utils.js';
import{verifyDenominatorIntegrityManifest,verifyDenominatorMutationWitness}from'./s01-baseline.js';
import{createWeightedProgressVector}from'./s02-rollup.js';

function quarantineCredit(credit:WeightedCreditUnit,options:OperationOptions):Result<WeightedCreditUnit>{const body={unitId:credit.unitId,moduleId:credit.moduleId,areaId:credit.areaId,phaseId:credit.phaseId,maxWeight:credit.maxWeight,earnedWeight:0,state:'QUARANTINED' as const,evidenceBindingDigest:credit.evidenceBindingDigest,validityBindingDigest:credit.validityBindingDigest};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,creditDigest:d.value})};}

export function createCreditDependencyGraph(manifest:DenominatorIntegrityManifest,credits:readonly WeightedCreditUnit[],extraDependencies:Readonly<Record<string,readonly string[]>>,completeKnowledge:boolean,options:OperationOptions):Result<CreditDependencyGraph>{const c=cancelled(options);if(c)return c;const vm=verifyDenominatorIntegrityManifest(manifest,options);if(!vm.ok||!vm.value)return vm.ok?fail('MANIFEST_TAMPERED','Credit dependency graph requires verified manifest'):vm;const creditMap=new Map(credits.map(x=>[x.unitId,x]));if(creditMap.size!==credits.length)return fail('DUPLICATE_CREDIT','Credit dependency graph rejects duplicate credit units');const entries:CreditDependencyEntry[]=[];for(const unit of manifest.units){const credit=creditMap.get(unit.unitId);const extra=extraDependencies[unit.unitId]??[];if(!allSha(extra))return fail('DEPENDENCY_DIGEST_INVALID','Credit dependencies must be SHA-256 digests',unit.unitId);const deps=sortedUnique([manifest.manifestDigest,manifest.scopeDigest,manifest.dodDigest,manifest.policyDigest,...unit.dependencyDigests,...extra,...(credit?.evidenceBindingDigest?[credit.evidenceBindingDigest]:[]),...(credit?.validityBindingDigest?[credit.validityBindingDigest]:[])]);const d=sha(options,{unitId:unit.unitId,dependencyDigests:deps});if(!d.ok)return d;entries.push({unitId:unit.unitId,dependencyDigests:deps,entryDigest:d.value});}entries.sort((a,b)=>compareCodePoint(a.unitId,b.unitId));if(entries.length>limits(options).nodes)return fail('DEPENDENCY_GRAPH_BUDGET_EXCEEDED','Credit dependency graph exceeds node budget');const d=sha(options,{entries:entries.map(e=>e.entryDigest),completeKnowledge});if(!d.ok)return d;return{ok:true,value:deepFreeze({entries,completeKnowledge,graphDigest:d.value})};}

export function verifyCreditDependencyGraph(value:CreditDependencyGraph,options:OperationOptions):Result<boolean>{if(value.entries.some(e=>!validId(e.unitId)||!allSha(e.dependencyDigests)||!isSha256(e.entryDigest)))return{ok:true,value:false};for(const e of value.entries){const d=sha(options,{unitId:e.unitId,dependencyDigests:sortedUnique(e.dependencyDigests)});if(!d.ok)return d;if(d.value!==e.entryDigest)return{ok:true,value:false};}const entries=[...value.entries].sort((a,b)=>compareCodePoint(a.unitId,b.unitId));const d=sha(options,{entries:entries.map(e=>e.entryDigest),completeKnowledge:value.completeKnowledge});return d.ok?{ok:true,value:d.value===value.graphDigest}:d;}

export function createProgressInvalidationVector(graph:CreditDependencyGraph,changedBindingDigests:readonly string[],reasonCodes:readonly string[],options:OperationOptions):Result<ProgressInvalidationVector>{const c=cancelled(options);if(c)return c;const vg=verifyCreditDependencyGraph(graph,options);if(!vg.ok||!vg.value)return vg.ok?fail('DEPENDENCY_GRAPH_TAMPERED','Invalidation requires verified dependency graph'):vg;const changed=sortedUnique(changedBindingDigests);if(!allSha(changed))return fail('INVALIDATION_BINDING_INVALID','Changed bindings must be SHA-256 digests');const reasons=sortedUnique(reasonCodes);if(reasons.length===0||!reasons.every(validId))return fail('INVALIDATION_REASON_REQUIRED','Invalidation requires bounded reason codes');const affected=graph.completeKnowledge?graph.entries.filter(e=>e.dependencyDigests.some(d=>changed.includes(d))).map(e=>e.unitId):graph.entries.map(e=>e.unitId);const body={changedBindingDigests:changed,affectedUnitIds:sortedUnique(affected),widened:!graph.completeKnowledge,reasonCodes:reasons};const d=sha(options,{graphDigest:graph.graphDigest,...body});if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,vectorDigest:d.value})};}

export function createStaleCreditQuarantine(credits:readonly WeightedCreditUnit[],invalidation:ProgressInvalidationVector,options:OperationOptions):Result<StaleCreditQuarantine>{const c=cancelled(options);if(c)return c;const entries:StaleCreditQuarantineEntry[]=[];for(const id of invalidation.affectedUnitIds){const credit=credits.find(x=>x.unitId===id);if(!credit)continue;const body={unitId:id,priorCreditDigest:credit.creditDigest,reasonCodes:invalidation.reasonCodes};const d=sha(options,body);if(!d.ok)return d;entries.push({...body,entryDigest:d.value});}entries.sort((a,b)=>compareCodePoint(a.unitId,b.unitId));const d=sha(options,{entries:entries.map(e=>e.entryDigest),vectorDigest:invalidation.vectorDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({entries,quarantineDigest:d.value})};}

export function retractCredits(credits:readonly WeightedCreditUnit[],invalidation:ProgressInvalidationVector,options:OperationOptions):Result<readonly WeightedCreditUnit[]>{const affected=new Set(invalidation.affectedUnitIds);const out:WeightedCreditUnit[]=[];for(const credit of credits){if(!affected.has(credit.unitId)||credit.state==='QUARANTINED'){out.push(credit);continue;}const q=quarantineCredit(credit,options);if(!q.ok)return q;out.push(q.value);}out.sort((a,b)=>compareCodePoint(a.unitId,b.unitId));return{ok:true,value:deepFreeze(out)};}

export function createCreditRetractionTransaction(manifest:DenominatorIntegrityManifest,credits:readonly WeightedCreditUnit[],query:ProgressQuery,invalidation:ProgressInvalidationVector,options:OperationOptions):Result<CreditRetractionTransaction>{const before=createWeightedProgressVector(manifest,credits,query,options);if(!before.ok)return before;const afterCredits=retractCredits(credits,invalidation,options);if(!afterCredits.ok)return afterCredits;const after=createWeightedProgressVector(manifest,afterCredits.value,query,options);if(!after.ok)return after;const retracted=invalidation.affectedUnitIds.filter(id=>{const b=credits.find(c=>c.unitId===id);return b?.earnedWeight!==0;}).sort(compareCodePoint);const body={beforeVectorDigest:before.value.vectorDigest,afterVectorDigest:after.value.vectorDigest,retractedUnitIds:retracted,beforeExact:before.value.exact,afterExact:after.value.exact};const d=sha(options,{...body,invalidationDigest:invalidation.vectorDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,transactionDigest:d.value})};}

export function detectProgressDrift(snapshot:ProgressSnapshotCapsule,current:ProgressBindingObservation,options:OperationOptions):Result<ProgressDriftReport>{const stale:string[]=[];if(snapshot.projectId!==current.projectId)stale.push('project');if(snapshot.lineageDigest!==current.lineageDigest)stale.push('lineage');if(snapshot.manifestDigest!==current.manifestDigest)stale.push('denominator');if(snapshot.epochId!==current.epochId)stale.push('epoch');if(snapshot.scopeDigest!==current.scopeDigest)stale.push('scope');if(snapshot.dodDigest!==current.dodDigest)stale.push('dod');if(snapshot.evidenceSetDigest!==current.evidenceSetDigest)stale.push('evidence-set');const state=stale.length===0?'CURRENT' as const:'STALE' as const;const body={state,staleSubjects:stale.sort(compareCodePoint)};const d=sha(options,{snapshotDigest:snapshot.snapshotDigest,...body});if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,reportDigest:d.value})};}

export function guardDenominatorDrift(snapshot:ProgressSnapshotCapsule,current:DenominatorIntegrityManifest,witness:DenominatorMutationWitness|null,options:OperationOptions):Result<DenominatorDriftDecision>{const vm=verifyDenominatorIntegrityManifest(current,options);if(!vm.ok||!vm.value)return vm.ok?fail('MANIFEST_TAMPERED','Denominator drift guard requires verified current manifest'):vm;if(snapshot.manifestDigest===current.manifestDigest&&snapshot.epochId===current.epochId){const body={sameEpoch:true,comparisonAllowed:true,snapshotReusable:true,reason:'CURRENT_EPOCH'};const d=sha(options,{snapshotDigest:snapshot.snapshotDigest,currentManifestDigest:current.manifestDigest,...body});return d.ok?{ok:true,value:deepFreeze({...body,decisionDigest:d.value})}:d;}let compatible=false;if(witness&&witness.beforeManifestDigest===snapshot.manifestDigest&&witness.afterManifestDigest===current.manifestDigest&&witness.beforeEpochId===snapshot.epochId&&witness.afterEpochId===current.epochId){const beforeStub={...current,manifestDigest:snapshot.manifestDigest,epochId:snapshot.epochId} as DenominatorIntegrityManifest;const vw=verifyDenominatorMutationWitness(witness,beforeStub,current,options);compatible=vw.ok&&vw.value;}const body={sameEpoch:false,comparisonAllowed:compatible,snapshotReusable:false,reason:compatible?'GOVERNED_EPOCH_TRANSITION':'DENOMINATOR_DRIFT_UNBOUND'};const d=sha(options,{snapshotDigest:snapshot.snapshotDigest,currentManifestDigest:current.manifestDigest,witnessDigest:witness?.witnessDigest??null,...body});return d.ok?{ok:true,value:deepFreeze({...body,decisionDigest:d.value})}:d;}

export function createProgressSplitBrainWitness(a:ProgressSnapshotCapsule,b:ProgressSnapshotCapsule,options:OperationOptions):Result<ProgressSplitBrainWitness>{const samePredecessor=a.predecessorSemanticDigest===b.predecessorSemanticDigest;const divergent=samePredecessor&&a.semanticDigest!==b.semanticDigest;const snapshots=[a.snapshotDigest,b.snapshotDigest].sort(compareCodePoint);const body={samePredecessor,divergent,snapshotDigests:snapshots};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,witnessDigest:d.value})};}

function less(a:{numerator:number;denominator:number},b:{numerator:number;denominator:number}){return BigInt(a.numerator)*BigInt(b.denominator)<BigInt(b.numerator)*BigInt(a.denominator);}
export function createProgressRegressionReceipt(before:ProgressSnapshotCapsule,after:ProgressSnapshotCapsule,transaction:CreditRetractionTransaction,reasonCodes:readonly string[],options:OperationOptions):Result<ProgressRegressionReceipt>{const reasons=sortedUnique(reasonCodes);if(reasons.length===0||!reasons.every(validId))return fail('REGRESSION_REASON_REQUIRED','Progress regression requires bounded reason codes');if(!less(after.exact,before.exact))return fail('NOT_A_REGRESSION','Regression receipt requires after progress to be lower than before');if(stableJson(transaction.beforeExact)!==stableJson(before.exact)||stableJson(transaction.afterExact)!==stableJson(after.exact))return fail('REGRESSION_TRANSACTION_MISMATCH','Retraction transaction does not match snapshot fractions');const body={beforeSnapshotDigest:before.snapshotDigest,afterSnapshotDigest:after.snapshotDigest,beforeExact:before.exact,afterExact:after.exact,retractedUnitIds:transaction.retractedUnitIds,reasonCodes:reasons};const d=sha(options,{...body,transactionDigest:transaction.transactionDigest});if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,receiptDigest:d.value})};}
