import type{DependencyClosureFingerprint,EvidenceValidityFingerprint,FingerprintConflictWitness,FingerprintIntegrityReceipt,FreshnessState,ObligationBindingFingerprint,OperationOptions,ProofFreshnessWitness,ProofObligationDeclaration,ProofSemanticFingerprint,Result,ValidityCompatibilityGate}from'./types.js';
import{deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,validId}from'./utils.js';

export function createEvidenceValidityFingerprint(evidenceId:string,evidenceSemanticDigest:string,validityBindingDigest:string,sourceIdentityDigest:string,options:OperationOptions):Result<EvidenceValidityFingerprint>{if(!validId(evidenceId)||![evidenceSemanticDigest,validityBindingDigest,sourceIdentityDigest].every(isSha256))return fail('EVF25_INPUT_INVALID','Evidence fingerprint input invalid.',evidenceId);const body={evidenceId,evidenceSemanticDigest,validityBindingDigest,sourceIdentityDigest};const d=digestValue(options,'EVF25',body);if(!d.ok)return d;return ok(deepFreeze({...body,fingerprint:d.value}));}
export function createObligationBindingFingerprint(obligation:ProofObligationDeclaration,options:OperationOptions):Result<ObligationBindingFingerprint>{const body={obligationId:obligation.obligationId,obligationDigest:obligation.obligationDigest,ownerId:obligation.ownerId,sourceIdentityDigest:obligation.sourceIdentityDigest,proofPolicyDigest:obligation.proofPolicyDigest};const d=digestValue(options,'OBF25',body);if(!d.ok)return d;return ok(deepFreeze({...body,fingerprint:d.value}));}
export function createDependencyClosureFingerprint(claimId:string,reachableNodeIds:readonly string[],selectedSupportIds:readonly string[],options:OperationOptions):Result<DependencyClosureFingerprint>{if(!validId(claimId)||reachableNodeIds.some(x=>!validId(x))||selectedSupportIds.some(x=>!validId(x)))return fail('DCF25_INPUT_INVALID','Dependency closure fingerprint input invalid.',claimId);const body={claimId,reachableNodeIds:sortedUnique(reachableNodeIds),selectedSupportIds:sortedUnique(selectedSupportIds)};const d=digestValue(options,'DCF25',body);if(!d.ok)return d;return ok(deepFreeze({...body,fingerprint:d.value}));}
export function createProofSemanticFingerprint(claimId:string,obligationFingerprint:string,dependencyClosureFingerprint:string,selectedSupportIds:readonly string[],proofPolicyDigest:string,namespaceDigest:string,options:OperationOptions):Result<ProofSemanticFingerprint>{if(!validId(claimId)||![obligationFingerprint,dependencyClosureFingerprint,proofPolicyDigest,namespaceDigest].every(isSha256))return fail('PSF25_INPUT_INVALID','Proof semantic fingerprint input invalid.',claimId);const body={claimId,obligationFingerprint,dependencyClosureFingerprint,selectedSupportIds:sortedUnique(selectedSupportIds),proofPolicyDigest,namespaceDigest};const d=digestValue(options,'PSF25',body);if(!d.ok)return d;return ok(deepFreeze({...body,fingerprint:d.value}));}
export function createValidityCompatibilityGate(priorFingerprint:string|null,currentFingerprint:string|null,completeKnowledge:boolean,changedSubjects:readonly string[],missingSubjects:readonly string[],options:OperationOptions):Result<ValidityCompatibilityGate>{if((priorFingerprint!==null&&!isSha256(priorFingerprint))||(currentFingerprint!==null&&!isSha256(currentFingerprint))||changedSubjects.some(x=>!validId(x))||missingSubjects.some(x=>!validId(x)))return fail('VCG25_INPUT_INVALID','Validity compatibility gate input invalid.');let state:FreshnessState;if(changedSubjects.length>1&&new Set(changedSubjects).size!==changedSubjects.length)state='CONFLICT';else if(!completeKnowledge||priorFingerprint===null||currentFingerprint===null||missingSubjects.length>0)state='INDETERMINATE';else if(changedSubjects.length>0||priorFingerprint!==currentFingerprint)state='STALE';else state='CURRENT';const compatible=state==='CURRENT';const body={priorFingerprint,currentFingerprint,completeKnowledge,compatible,state,changedSubjects:sortedUnique(changedSubjects),missingSubjects:sortedUnique(missingSubjects)};const d=digestValue(options,'VCG25',body);if(!d.ok)return d;return ok(deepFreeze({...body,gateDigest:d.value}));}
export function createProofFreshnessWitness(claimId:string,gate:ValidityCompatibilityGate,options:OperationOptions):Result<ProofFreshnessWitness>{if(!validId(claimId))return fail('PFW25_CLAIM_INVALID','Freshness witness requires valid claim.',claimId);const body={claimId,state:gate.state,changedSubjects:gate.changedSubjects,missingSubjects:gate.missingSubjects};const d=digestValue(options,'PFW25',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}
export function createFingerprintConflictWitness(governedId:string,fingerprints:readonly string[],options:OperationOptions):Result<FingerprintConflictWitness>{if(!validId(governedId)||fingerprints.length===0||fingerprints.some(x=>!isSha256(x)))return fail('FCW25_INPUT_INVALID','Fingerprint conflict witness input invalid.',governedId);const values=sortedUnique(fingerprints),body={governedId,fingerprints:values,conflict:values.length>1};const d=digestValue(options,'FCW25',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}
export function createFingerprintIntegrityReceipt(subjectId:string,componentFingerprints:readonly string[],gate:ValidityCompatibilityGate,options:OperationOptions):Result<FingerprintIntegrityReceipt>{if(!validId(subjectId)||componentFingerprints.length===0||componentFingerprints.some(x=>!isSha256(x)))return fail('FIR25_INPUT_INVALID','Fingerprint integrity receipt input invalid.',subjectId);const body={subjectId,componentFingerprints:sortedUnique(componentFingerprints),compatibilityGateDigest:gate.gateDigest};const d=digestValue(options,'FIR25',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}
