import type{CompletionInvalidationGraph,M24EvidenceFact,OperationOptions,ProofComputationInput,ProofInvalidationVector,ReopenCandidateProjection,Result,TargetedInvalidationSelector,UnknownDependencyWidening}from'./types.js';
import type{TrustedOperationOptions}from'@gef-bootstrap/evidence-engine';
import{compareCodePoint,deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,validId}from'./utils.js';
import{evaluateProofGraph}from'./s02-safe-evaluation.js';
import{verifyM24ProofContext}from'./s01-identity.js';
function addReverse(map:Map<string,Set<string>>,dependencyId:string,affectedNodeId:string){const set=map.get(dependencyId)??new Set<string>();set.add(affectedNodeId);map.set(dependencyId,set);}
function addEvidenceBindings(map:Map<string,Set<string>>,fact:M24EvidenceFact){const node=`EVIDENCE:${fact.evidenceId}`;for(const dep of [fact.semanticDigest,fact.validityBindingDigest,fact.sourceIdentityDigest,fact.decisionReceiptDigest])addReverse(map,dep,node);}
export function createCompletionInvalidationGraph(computation:ProofComputationInput,completeKnowledge:boolean,m24Options:TrustedOperationOptions,options:OperationOptions):Result<CompletionInvalidationGraph>{const evaluation=evaluateProofGraph(computation,m24Options,options);if(!evaluation.ok)return evaluation;const verifiedM24=verifyM24ProofContext(computation.m24,m24Options);if(!verifiedM24.ok)return verifiedM24;const map=new Map<string,Set<string>>();for(const e of computation.graph.edges)addReverse(map,e.toNodeId,e.fromNodeId);for(const fact of verifiedM24.value.facts)addEvidenceBindings(map,fact);for(const o of computation.manifest.obligations){const node=`OBLIGATION:${o.obligationId}`;for(const dep of [o.obligationDigest,o.sourceIdentityDigest,o.proofPolicyDigest,...o.validityDependencyDigests])addReverse(map,dep,node);}for(const root of computation.graph.rootClaimIds){addReverse(map,computation.manifest.namespaceDigest,`CLAIM:${root}`);addReverse(map,computation.manifest.proofPolicyDigest,`CLAIM:${root}`);}const reverseDependencies=[...map.entries()].map(([dependencyId,set])=>({dependencyId,affectedNodeIds:sortedUnique([...set])})).sort((a,b)=>compareCodePoint(a.dependencyId,b.dependencyId));const body={proofGraphDigest:computation.graph.graphDigest,reverseDependencies,completeKnowledge};const d=digestValue(options,'CIG25',body);return d.ok?ok(deepFreeze({...body,graphDigest:d.value})):d;}
export function createProofInvalidationVector(graph:CompletionInvalidationGraph,changedDependencyDigests:readonly string[],options:OperationOptions):Result<ProofInvalidationVector>{if(changedDependencyDigests.length===0||changedDependencyDigests.some(x=>!isSha256(x)))return fail('PIV25_CHANGED_INVALID','Changed dependency digests invalid.');const changed=new Set(changedDependencyDigests),direct=new Set<string>();for(const row of graph.reverseDependencies)if(changed.has(row.dependencyId))for(const n of row.affectedNodeIds)direct.add(n);const affected=new Set(direct),queue=[...direct];while(queue.length){const id=queue.shift();if(!id)continue;for(const row of graph.reverseDependencies)if(row.dependencyId===id)for(const n of row.affectedNodeIds)if(!affected.has(n)){affected.add(n);queue.push(n);}}const widened=!graph.completeKnowledge;if(widened)for(const row of graph.reverseDependencies)for(const n of row.affectedNodeIds)affected.add(n);const body={changedDependencyDigests:sortedUnique(changedDependencyDigests),directlyAffectedNodeIds:sortedUnique([...direct]),transitivelyAffectedNodeIds:sortedUnique([...affected]),widened};const d=digestValue(options,'PIV25',body);return d.ok?ok(deepFreeze({...body,vectorDigest:d.value})):d;}
export function createTargetedInvalidationSelector(allNodeIds:readonly string[],vector:ProofInvalidationVector,options:OperationOptions):Result<TargetedInvalidationSelector>{if(allNodeIds.some(x=>!validId(x)))return fail('TIS25_NODE_INVALID','Targeted invalidation node IDs invalid.');const affected=new Set(vector.transitivelyAffectedNodeIds),body={preservedNodeIds:sortedUnique(allNodeIds.filter(x=>!affected.has(x))),invalidatedNodeIds:sortedUnique(allNodeIds.filter(x=>affected.has(x)))};const d=digestValue(options,'TIS25',body);return d.ok?ok(deepFreeze({...body,selectorDigest:d.value})):d;}
export function createUnknownDependencyWidening(originalAffectedNodeIds:readonly string[],safeKnownAncestorNodeIds:readonly string[],completeKnowledge:boolean,options:OperationOptions):Result<UnknownDependencyWidening>{if([...originalAffectedNodeIds,...safeKnownAncestorNodeIds].some(x=>!validId(x)))return fail('UDW25_NODE_INVALID','Widening node IDs invalid.');const widened=!completeKnowledge,body={widened,originalAffectedNodeIds:sortedUnique(originalAffectedNodeIds),widenedAffectedNodeIds:widened?sortedUnique([...originalAffectedNodeIds,...safeKnownAncestorNodeIds]):sortedUnique(originalAffectedNodeIds),reasonCodes:widened?['DEPENDENCY_KNOWLEDGE_INCOMPLETE']:['TARGETING_SAFE']};const d=digestValue(options,'UDW25',body);return d.ok?ok(deepFreeze({...body,witnessDigest:d.value})):d;}
export function createReopenCandidateProjection(affectedClaimIds:readonly string[],affectedCriterionIds:readonly string[],affectedCompletionIds:readonly string[],options:OperationOptions):Result<ReopenCandidateProjection>{if([...affectedClaimIds,...affectedCriterionIds,...affectedCompletionIds].some(x=>!validId(x)))return fail('RCP25_ID_INVALID','Reopen candidate IDs invalid.');const body={affectedClaimIds:sortedUnique(affectedClaimIds),affectedCriterionIds:sortedUnique(affectedCriterionIds),affectedCompletionIds:sortedUnique(affectedCompletionIds),mayMutateOwnerState:false as const};const d=digestValue(options,'RCP25',body);return d.ok?ok(deepFreeze({...body,projectionDigest:d.value})):d;}
