import type{OperationOptions,ProofComputationInput,ProofEvaluation,ProofIntegrityReceipt,ProofSnapshotCapsule,Result}from'./types.js';
import type{TrustedOperationOptions}from'@gef-bootstrap/evidence-engine';
import{deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,stableStringify,validId}from'./utils.js';
import{evaluateProofGraph}from'./s02-graph.js';
function resultDigests(evaluation:ProofEvaluation,options:OperationOptions):Result<readonly string[]>{const out:string[]=[];for(const r of evaluation.results){const d=digestValue(options,'PSC25_RESULT',r);if(!d.ok)return d;out.push(d.value);}return ok(sortedUnique(out));}
function rebuild(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput,m24Options:TrustedOperationOptions,options:OperationOptions){return createProofSnapshotCapsule({snapshotId:snapshot.snapshotId,computation,fingerprintDigests:snapshot.fingerprintDigests,invalidationVectorDigest:snapshot.invalidationVectorDigest,predecessorSemanticDigest:snapshot.predecessorSemanticDigest},m24Options,options);}
export function createProofSnapshotCapsule(input:{readonly snapshotId:string;readonly computation:ProofComputationInput;readonly fingerprintDigests:readonly string[];readonly invalidationVectorDigest:string|null;readonly predecessorSemanticDigest:string|null},m24Options:TrustedOperationOptions,options:OperationOptions):Result<ProofSnapshotCapsule>{const c=input.computation,projectId=c.manifest.projectId,lineageId=c.manifest.lineageId,proofPolicyDigest=c.manifest.proofPolicyDigest,namespaceDigest=c.manifest.namespaceDigest,graphDigest=c.graph.graphDigest;if(!validId(input.snapshotId)||![proofPolicyDigest,namespaceDigest,graphDigest].every(isSha256)||input.fingerprintDigests.some(x=>!isSha256(x))||(input.invalidationVectorDigest!==null&&!isSha256(input.invalidationVectorDigest))||(input.predecessorSemanticDigest!==null&&!isSha256(input.predecessorSemanticDigest)))return fail('PSC25_INPUT_INVALID','Proof snapshot input invalid.',input.snapshotId);const evaluation=evaluateProofGraph(c,m24Options,options);if(!evaluation.ok)return evaluation;const rd=resultDigests(evaluation.value,options);if(!rd.ok)return rd;const semanticBody={projectId,lineageId,proofPolicyDigest,namespaceDigest,graphDigest,evaluationDigest:evaluation.value.evaluationDigest,m24ContextDigest:evaluation.value.m24ContextDigest,resultDigests:rd.value,fingerprintDigests:sortedUnique(input.fingerprintDigests),invalidationVectorDigest:input.invalidationVectorDigest,predecessorSemanticDigest:input.predecessorSemanticDigest};const sem=digestValue(options,'PSC25_SEMANTIC',semanticBody);if(!sem.ok)return sem;const body={snapshotId:input.snapshotId,...semanticBody,semanticDigest:sem.value};const snap=digestValue(options,'PSC25',body);return snap.ok?ok(deepFreeze({...body,snapshotDigest:snap.value})):snap;}
export function verifyProofSnapshotCapsule(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput,m24Options:TrustedOperationOptions,options:OperationOptions):Result<boolean>{const r=rebuild(snapshot,computation,m24Options,options);return r.ok?ok(stableStringify(r.value)===stableStringify(snapshot)):r;}
export function createProofIntegrityReceipt(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput,m24Options:TrustedOperationOptions,options:OperationOptions):Result<ProofIntegrityReceipt>{const r=rebuild(snapshot,computation,m24Options,options);if(!r.ok)return r;const valid=stableStringify(r.value)===stableStringify(snapshot),body={snapshotDigest:snapshot.snapshotDigest,recomputedSemanticDigest:r.value.semanticDigest,valid};const d=digestValue(options,'PIR25',body);return d.ok?ok(deepFreeze({...body,receiptDigest:d.value})):d;}
