import type{OperationOptions,ProofComputationInput,ProofEvaluation,ProofIntegrityReceipt,ProofSnapshotCapsule,Result}from'./types.js';
import type{TrustedOperationOptions}from'@gef-bootstrap/evidence-engine';
import{deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,stableStringify,validId}from'./utils.js';
import{evaluateProofGraph}from'./s02-safe-evaluation.js';
import{createCompletionInvalidationGraph,createProofInvalidationVector}from'./s05a-invalidation.js';
type SnapshotInvalidationInput={readonly completeKnowledge:boolean;readonly changedDependencyDigests:readonly string[]};
type SnapshotInput={readonly snapshotId:string;readonly computation:ProofComputationInput;readonly fingerprintDigests:readonly string[];readonly invalidation?:SnapshotInvalidationInput|null;readonly invalidationVectorDigest?:string|null;readonly predecessorSemanticDigest:string|null};
function resultDigests(evaluation:ProofEvaluation,options:OperationOptions):Result<readonly string[]>{const out:string[]=[];for(const r of evaluation.results){const d=digestValue(options,'PSC25_RESULT',r);if(!d.ok)return d;out.push(d.value);}return ok(sortedUnique(out));}
function snapshotInputFromStored(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput):SnapshotInput{return{snapshotId:snapshot.snapshotId,computation,fingerprintDigests:snapshot.fingerprintDigests,invalidation:snapshot.invalidationVectorDigest===null?null:{completeKnowledge:snapshot.invalidationKnowledgeComplete===true,changedDependencyDigests:snapshot.invalidationChangedDependencyDigests},predecessorSemanticDigest:snapshot.predecessorSemanticDigest};}
function rebuild(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput,m24Options:TrustedOperationOptions,options:OperationOptions){return createProofSnapshotCapsule(snapshotInputFromStored(snapshot,computation),m24Options,options);}
export function createProofSnapshotCapsule(input:SnapshotInput,m24Options:TrustedOperationOptions,options:OperationOptions):Result<ProofSnapshotCapsule>{const c=input.computation,projectId=c.manifest.projectId,lineageId=c.manifest.lineageId,proofPolicyDigest=c.manifest.proofPolicyDigest,namespaceDigest=c.manifest.namespaceDigest,graphDigest=c.graph.graphDigest;if(!validId(input.snapshotId)||![proofPolicyDigest,namespaceDigest,graphDigest].every(isSha256)||input.fingerprintDigests.some(x=>!isSha256(x))||(input.predecessorSemanticDigest!==null&&!isSha256(input.predecessorSemanticDigest)))return fail('PSC25_INPUT_INVALID','Proof snapshot input invalid.',input.snapshotId);if(input.invalidation===undefined&&input.invalidationVectorDigest!==undefined&&input.invalidationVectorDigest!==null)return fail('PSC25_OPAQUE_INVALIDATION_FORBIDDEN','Snapshot cannot accept a non-recomputable invalidation digest.',input.snapshotId);if(input.invalidation!==undefined&&input.invalidation!==null&&input.invalidation.changedDependencyDigests.length===0)return fail('PSC25_INVALIDATION_EMPTY','Recomputable invalidation requires changed dependency digests.',input.snapshotId);const evaluation=evaluateProofGraph(c,m24Options,options);if(!evaluation.ok)return evaluation;const rd=resultDigests(evaluation.value,options);if(!rd.ok)return rd;let invalidationVectorDigest:string|null=null,invalidationChangedDependencyDigests:readonly string[]=[],invalidationKnowledgeComplete:boolean|null=null;if(input.invalidation!==undefined&&input.invalidation!==null){const ig=createCompletionInvalidationGraph(c,input.invalidation.completeKnowledge,m24Options,options);if(!ig.ok)return ig;const iv=createProofInvalidationVector(ig.value,input.invalidation.changedDependencyDigests,options);if(!iv.ok)return iv;invalidationVectorDigest=iv.value.vectorDigest;invalidationChangedDependencyDigests=iv.value.changedDependencyDigests;invalidationKnowledgeComplete=input.invalidation.completeKnowledge;}const semanticBody={projectId,lineageId,proofPolicyDigest,namespaceDigest,graphDigest,evaluationDigest:evaluation.value.evaluationDigest,sourceAuthorityDigest:evaluation.value.sourceAuthorityDigest,m24ContextDigest:evaluation.value.m24ContextDigest,resultDigests:rd.value,fingerprintDigests:sortedUnique(input.fingerprintDigests),invalidationVectorDigest,invalidationChangedDependencyDigests,invalidationKnowledgeComplete,predecessorSemanticDigest:input.predecessorSemanticDigest};const sem=digestValue(options,'PSC25_SEMANTIC',semanticBody);if(!sem.ok)return sem;const body={snapshotId:input.snapshotId,...semanticBody,semanticDigest:sem.value};const snap=digestValue(options,'PSC25',body);return snap.ok?ok(deepFreeze({...body,snapshotDigest:snap.value})):snap;}
export function verifyProofSnapshotCapsule(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput,m24Options:TrustedOperationOptions,options:OperationOptions):Result<boolean>{if(snapshot.invalidationVectorDigest===null&&(snapshot.invalidationChangedDependencyDigests.length>0||snapshot.invalidationKnowledgeComplete!==null))return ok(false);if(snapshot.invalidationVectorDigest!==null&&(snapshot.invalidationKnowledgeComplete===null||snapshot.invalidationChangedDependencyDigests.length===0))return ok(false);const r=rebuild(snapshot,computation,m24Options,options);return r.ok?ok(stableStringify(r.value)===stableStringify(snapshot)):r;}
export function createProofIntegrityReceipt(snapshot:ProofSnapshotCapsule,computation:ProofComputationInput,m24Options:TrustedOperationOptions,options:OperationOptions):Result<ProofIntegrityReceipt>{const r=rebuild(snapshot,computation,m24Options,options);if(!r.ok)return r;const valid=stableStringify(r.value)===stableStringify(snapshot),body={snapshotDigest:snapshot.snapshotDigest,recomputedSemanticDigest:r.value.semanticDigest,valid};const d=digestValue(options,'PIR25',body);return d.ok?ok(deepFreeze({...body,receiptDigest:d.value})):d;}
