import type{ProofState,CarryForwardDecisionState,ShadowAssuranceState,ReplayGuardState}from'./types-base.js';
export interface ProofCompatibilityKey{readonly claimId:string;readonly obligationId:string;readonly proofPolicyDigest:string;readonly namespaceDigest:string;readonly proofSemanticFingerprint:string;readonly keyDigest:string;}
export interface CarryForwardCandidate{readonly candidateId:string;readonly predecessorSnapshotDigest:string;readonly priorClaimId:string;readonly priorProofState:ProofState;readonly currentProofState:ProofState;readonly priorProofContextDigest:string;readonly currentProofContextDigest:string;readonly priorCompatibilityKeyDigest:string;readonly currentCompatibilityKeyDigest:string;readonly dependencyKnowledgeComplete:boolean;readonly invalidatedDependencyDigests:readonly string[];readonly candidateDigest:string;}
export interface CarryForwardDecision{readonly candidateId:string;readonly decision:CarryForwardDecisionState;readonly reusableNodeIds:readonly string[];readonly recomputeNodeIds:readonly string[];readonly reasonCodes:readonly string[];readonly decisionDigest:string;}
export interface CarryForwardWitness{readonly candidateId:string;readonly priorKeyDigest:string;readonly currentKeyDigest:string;readonly compatibleDimensions:readonly string[];readonly changedDimensions:readonly string[];readonly witnessDigest:string;}
export interface PartialCarryForwardSelector{readonly preservedChildNodeIds:readonly string[];readonly recomputeAncestorNodeIds:readonly string[];readonly selectorDigest:string;}
export interface ShadowAssuranceRequirement{readonly state:ShadowAssuranceState;readonly policyDigest:string;readonly reasonCodes:readonly string[];readonly requirementDigest:string;}
export interface CarryForwardReceipt{readonly candidateDigest:string;readonly decisionDigest:string;readonly reusedNodeIds:readonly string[];readonly recomputedNodeIds:readonly string[];readonly rejectedNodeIds:readonly string[];readonly receiptDigest:string;}
export interface ProofCarryForwardGraph{readonly predecessorSnapshotDigest:string;readonly candidates:readonly CarryForwardCandidate[];readonly graphDigest:string;}
export interface CompletionInvalidationGraph{readonly proofGraphDigest:string;readonly reverseDependencies:readonly {readonly dependencyId:string;readonly affectedNodeIds:readonly string[]}[];readonly completeKnowledge:boolean;readonly graphDigest:string;}
export interface ProofInvalidationVector{readonly changedDependencyDigests:readonly string[];readonly directlyAffectedNodeIds:readonly string[];readonly transitivelyAffectedNodeIds:readonly string[];readonly widened:boolean;readonly vectorDigest:string;}
export interface TargetedInvalidationSelector{readonly preservedNodeIds:readonly string[];readonly invalidatedNodeIds:readonly string[];readonly selectorDigest:string;}
export interface UnknownDependencyWidening{readonly widened:boolean;readonly originalAffectedNodeIds:readonly string[];readonly widenedAffectedNodeIds:readonly string[];readonly reasonCodes:readonly string[];readonly witnessDigest:string;}
export interface ReopenCandidateProjection{readonly affectedClaimIds:readonly string[];readonly affectedCriterionIds:readonly string[];readonly affectedCompletionIds:readonly string[];readonly mayMutateOwnerState:false;readonly projectionDigest:string;}
export interface ProofSnapshotCapsule{readonly snapshotId:string;readonly projectId:string;readonly lineageId:string;readonly proofPolicyDigest:string;readonly namespaceDigest:string;readonly graphDigest:string;readonly evaluationDigest:string;readonly m24ContextDigest:string;readonly resultDigests:readonly string[];readonly fingerprintDigests:readonly string[];readonly invalidationVectorDigest:string|null;readonly invalidationChangedDependencyDigests:readonly string[];readonly invalidationKnowledgeComplete:boolean|null;readonly predecessorSemanticDigest:string|null;readonly semanticDigest:string;readonly snapshotDigest:string;}
export interface ProofIntegrityReceipt{readonly snapshotDigest:string;readonly recomputedSemanticDigest:string;readonly valid:boolean;readonly receiptDigest:string;}
export interface ProofReplayGuard{readonly state:ReplayGuardState;readonly acceptedSnapshotDigests:readonly string[];readonly duplicateSnapshotDigests:readonly string[];readonly conflictingSnapshotIds:readonly string[];readonly historyTruncated:boolean;readonly processedCount:number;readonly totalCount:number;readonly guardDigest:string;}
export interface ProofSplitStateWitness{readonly predecessorSemanticDigest:string;readonly successorSemanticDigests:readonly string[];readonly splitState:boolean;readonly witnessDigest:string;}
export interface DownstreamProofHandoff{readonly owner:'M25_PROOF';readonly consumer:'M26_DELTA_REVIEW'|'M27_ASSURANCE'|'GOVERNANCE';readonly snapshotDigest:string;readonly proofStates:readonly {readonly claimId:string;readonly state:ProofState}[];readonly selectedSupportIds:readonly string[];readonly proofFingerprintDigests:readonly string[];readonly invalidationVectorDigest:string|null;readonly unresolvedClaimIds:readonly string[];readonly mayPerformDeltaReview:false;readonly mayDecideAssurance:false;readonly mayMutateDod:false;readonly mayCalculateProgress:false;readonly mayPromoteCheckpoint:false;readonly handoffDigest:string;}
