import type{ProofNodeIdentity,ProofEdgeIdentity,ProofState,SufficiencyMode,CanonicalClaimIdentity,ProofIdentityManifest,M24ProofContextInput,FreshnessState}from'./types-base.js';
export interface ProofDependencyGraph{readonly namespaceDigest:string;readonly manifestDigest:string;readonly rootClaimIds:readonly string[];readonly nodes:readonly ProofNodeIdentity[];readonly edges:readonly ProofEdgeIdentity[];readonly graphDigest:string;}
export interface AcyclicityGuard{readonly acyclic:boolean;readonly cycleNodeIds:readonly string[];readonly guardDigest:string;}
export interface EvidenceSupportGate{readonly evidenceId:string;readonly state:ProofState;readonly evidenceSemanticDigest:string|null;readonly reasonCodes:readonly string[];readonly gateDigest:string;}
export interface ClaimSupportGate{readonly claimId:string;readonly state:ProofState;readonly proofSemanticDigest:string|null;readonly reasonCodes:readonly string[];readonly gateDigest:string;}
export interface AntiDoubleCountGuard{readonly originalSupportIds:readonly string[];readonly distinctSupportIds:readonly string[];readonly duplicateSupportIds:readonly string[];readonly guardDigest:string;}
export interface SufficiencyResolution{readonly obligationId:string;readonly mode:SufficiencyMode;readonly threshold:number|null;readonly dependencyStates:readonly {readonly id:string;readonly state:ProofState}[];readonly selectedSupportIds:readonly string[];readonly state:ProofState;readonly reasonCodes:readonly string[];readonly resolutionDigest:string;}
export interface ProofReachability{readonly rootClaimIds:readonly string[];readonly reachableNodeIds:readonly string[];readonly truncated:boolean;readonly processedCount:number;readonly totalCount:number;readonly reachabilityDigest:string;}
export interface DependencyCoverageWitness{readonly obligationId:string;readonly requiredDependencyIds:readonly string[];readonly observedDependencyIds:readonly string[];readonly missingDependencyIds:readonly string[];readonly unusedDependencyIds:readonly string[];readonly truncated:boolean;readonly witnessDigest:string;}
export interface ClaimProofResult{readonly claimId:string;readonly obligationId:string;readonly state:ProofState;readonly selectedSupportIds:readonly string[];readonly dependencyStates:readonly {readonly id:string;readonly state:ProofState}[];readonly coverageDigest:string;readonly proofSemanticDigest:string;readonly reasonCodes:readonly string[];}
export interface ProofComputationInput{readonly graph:ProofDependencyGraph;readonly manifest:ProofIdentityManifest;readonly claims:readonly CanonicalClaimIdentity[];readonly m24:M24ProofContextInput;}
export interface ProofEvaluation{readonly graphDigest:string;readonly m24ContextDigest:string;readonly results:readonly ClaimProofResult[];readonly evaluationDigest:string;}

export interface EvidenceValidityFingerprint{readonly evidenceId:string;readonly evidenceSemanticDigest:string;readonly validityBindingDigest:string;readonly sourceIdentityDigest:string;readonly fingerprint:string;}
export interface ObligationBindingFingerprint{readonly obligationId:string;readonly obligationDigest:string;readonly ownerId:string;readonly sourceIdentityDigest:string;readonly proofPolicyDigest:string;readonly fingerprint:string;}
export interface DependencyClosureFingerprint{readonly claimId:string;readonly reachableNodeIds:readonly string[];readonly selectedSupportIds:readonly string[];readonly fingerprint:string;}
export interface ProofSemanticFingerprint{readonly claimId:string;readonly obligationFingerprint:string;readonly dependencyClosureFingerprint:string;readonly selectedSupportIds:readonly string[];readonly proofPolicyDigest:string;readonly namespaceDigest:string;readonly fingerprint:string;}
export interface ValidityCompatibilityGate{readonly priorFingerprint:string|null;readonly currentFingerprint:string|null;readonly completeKnowledge:boolean;readonly compatible:boolean;readonly state:FreshnessState;readonly changedSubjects:readonly string[];readonly missingSubjects:readonly string[];readonly gateDigest:string;}
export interface ProofFreshnessWitness{readonly claimId:string;readonly state:FreshnessState;readonly changedSubjects:readonly string[];readonly missingSubjects:readonly string[];readonly witnessDigest:string;}
export interface FingerprintConflictWitness{readonly governedId:string;readonly fingerprints:readonly string[];readonly conflict:boolean;readonly witnessDigest:string;}
export interface FingerprintIntegrityReceipt{readonly subjectId:string;readonly componentFingerprints:readonly string[];readonly compatibilityGateDigest:string;readonly receiptDigest:string;}

