import type { AdoptionReceipt, AdoptionReceiptInput, AdoptionRegression, CapabilityRequirement, CapabilityUnlock, GovernanceDeltaReceipt, GovernanceMaturityVector, OperationOptions, ProofNode, ProofNodeInput, ReceiptCurrentBindings, ReceiptValidity, Result, SourceFingerprintBinding } from './types.js';
import { compareCodePoint, deepFreeze, DEFAULT_MAX_DEPTH, DEFAULT_MAX_EDGES, DEFAULT_MAX_NODES, fail, hasSecretLikeKey, safeLimit, sha } from './utils.js';
import { maturitySatisfies } from './policy.js';

export function evaluateCapabilityUnlock(requirement:CapabilityRequirement,vector:GovernanceMaturityVector,blockedDomains:readonly string[]=[]):CapabilityUnlock {
  const blocked=new Set(blockedDomains); const states=new Map(vector.domains.map(d=>[d.domain,d.maturity] as const)); const reasons:string[]=[];
  for(const need of requirement.domains){if(blocked.has(need.domain)){reasons.push(`${need.domain}:BLOCKED`);continue;}const actual=states.get(need.domain);if(!actual)reasons.push(`${need.domain}:MISSING`);else if(!maturitySatisfies(actual,need.minimum))reasons.push(`${need.domain}:${actual}<${need.minimum}`);}
  return deepFreeze({capability:requirement.capability,unlocked:reasons.length===0,reasons:reasons.sort(compareCodePoint)});
}

export function buildAdoptionProofSpine(nodes:readonly ProofNodeInput[],options:OperationOptions):Result<readonly ProofNode[]> {
  if(nodes.length>safeLimit(options.maxNodes,DEFAULT_MAX_NODES))return fail('NODE_BUDGET_EXCEEDED','Adoption Proof Spine node budget exceeded');
  const byId=new Map<string,ProofNodeInput>();let edges=0;
  for(const node of nodes){if(!node.id||!node.payloadDigest)return fail('PROOF_NODE_INVALID','Proof node binding is incomplete',node.id);if(byId.has(node.id))return fail('DUPLICATE_PROOF_NODE','Duplicate proof node',node.id);byId.set(node.id,node);edges+=node.dependencies?.length??0;if(edges>safeLimit(options.maxEdges,DEFAULT_MAX_EDGES))return fail('EDGE_BUDGET_EXCEEDED','Adoption Proof Spine edge budget exceeded');}
  for(const node of nodes)for(const dep of node.dependencies??[])if(!byId.has(dep))return fail('PROOF_DEPENDENCY_MISSING','Proof dependency not found',dep);
  const visiting=new Set<string>(),built=new Map<string,ProofNode>();
  const walk=(id:string,depth:number):Result<ProofNode>=>{if(options.cancellation?.isCancelled())return fail('CANCELLED','Operation cancelled');if(depth>safeLimit(options.maxDepth,DEFAULT_MAX_DEPTH))return fail('DEPTH_BUDGET_EXCEEDED','Adoption Proof Spine depth budget exceeded',id);if(visiting.has(id))return fail('PROOF_SPINE_CYCLE','Proof spine cycle detected',id);const existing=built.get(id);if(existing)return {ok:true,value:existing};visiting.add(id);const node=byId.get(id)!;const depDigests:string[]=[];for(const dep of [...(node.dependencies??[])].sort(compareCodePoint)){const r=walk(dep,depth+1);if(!r.ok)return r;depDigests.push(r.value.digest);}const digest=sha(options,{id,payloadDigest:node.payloadDigest,dependencies:depDigests});if(!digest.ok)return digest;const result=deepFreeze({id,digest:digest.value,dependencies:[...(node.dependencies??[])].sort(compareCodePoint)});visiting.delete(id);built.set(id,result);return {ok:true,value:result};};
  for(const id of [...byId.keys()].sort(compareCodePoint)){const r=walk(id,0);if(!r.ok)return r;}return {ok:true,value:deepFreeze([...built.values()].sort((a,b)=>compareCodePoint(a.id,b.id)))};
}

export function computeProofInvalidation(nodes:readonly ProofNode[],changedIds:readonly string[],unknownDependencyKnowledge=false):readonly string[] {if(unknownDependencyKnowledge)return deepFreeze(nodes.map(n=>n.id).sort(compareCodePoint));const affected=new Set(changedIds.filter(id=>nodes.some(n=>n.id===id)));let moved=true;while(moved){moved=false;for(const node of nodes)if(!affected.has(node.id)&&node.dependencies.some(d=>affected.has(d))){affected.add(node.id);moved=true;}}return deepFreeze([...affected].sort(compareCodePoint));}

export function buildGovernanceDeltaReceipt(input:Omit<GovernanceDeltaReceipt,'semanticIdentity'>,options:OperationOptions):Result<GovernanceDeltaReceipt> {const normalized={...input,frontierMoved:[...input.frontierMoved].sort(compareCodePoint),bridgesAdded:[...input.bridgesAdded].sort(compareCodePoint),bridgesRetired:[...input.bridgesRetired].sort(compareCodePoint),driftChanges:[...input.driftChanges].sort(compareCodePoint),quarantineChanges:[...input.quarantineChanges].sort(compareCodePoint),capabilitiesUnlocked:[...input.capabilitiesUnlocked].sort(compareCodePoint),capabilitiesInvalidated:[...input.capabilitiesInvalidated].sort(compareCodePoint)};const identity=sha(options,normalized);if(!identity.ok)return identity;return {ok:true,value:deepFreeze({...normalized,semanticIdentity:identity.value})};}

function normalizeFingerprints(bindings:readonly SourceFingerprintBinding[]):Result<readonly SourceFingerprintBinding[]> {const sorted=[...bindings].map(b=>({...b})).sort((a,b)=>compareCodePoint(a.id,b.id));for(const binding of sorted)if(!binding.id||!binding.fingerprint)return fail('SOURCE_FINGERPRINT_INVALID','Source fingerprint binding is incomplete',binding.id);for(let i=1;i<sorted.length;i++)if(sorted[i]!.id===sorted[i-1]!.id)return fail('DUPLICATE_SOURCE_FINGERPRINT','Duplicate source fingerprint binding',sorted[i]!.id);return {ok:true,value:sorted};}
function normalizeDomainPartition(input:AdoptionReceiptInput):Result<Readonly<{governedDomains:readonly string[];ungovernedDomains:readonly string[];blockedDomains:readonly string[]}>> {const governed=[...new Set(input.governedDomains)].sort(compareCodePoint),ungoverned=[...new Set(input.ungovernedDomains)].sort(compareCodePoint),blocked=[...new Set(input.blockedDomains)].sort(compareCodePoint);const owner=new Map<string,string>();for(const [label,domains] of [['GOVERNED',governed],['UNGOVERNED',ungoverned],['BLOCKED',blocked]] as const)for(const domain of domains){if(!domain)return fail('ADOPTION_DOMAIN_INVALID','Adoption receipt domain cannot be empty');const previous=owner.get(domain);if(previous)return fail('ADOPTION_DOMAIN_PARTITION_CONFLICT',`Domain appears in both ${previous} and ${label}`,domain);owner.set(domain,label);}return {ok:true,value:{governedDomains:governed,ungovernedDomains:ungoverned,blockedDomains:blocked}};}
function deriveValidity(input:AdoptionReceiptInput):ReceiptValidity {if(input.blockers.length)return 'BLOCKED';if(input.ungovernedDomains.length||input.blockedDomains.length||input.capabilityUnlocks.some(c=>!c.unlocked))return 'PARTIAL';return 'VALID';}

export function buildAdoptionReceipt(input:AdoptionReceiptInput,proofInputs:readonly ProofNodeInput[],options:OperationOptions):Result<AdoptionReceipt> {
  if(hasSecretLikeKey(input))return fail('RECEIPT_SECRET_MATERIAL_FORBIDDEN','Secret-like material is forbidden in adoption receipts');
  if(!input.projectId||!input.sourcePackIdentity||!input.profileIdentity||!input.profileDigest||!input.intentCapsuleIdentity||!input.policyVersion||!input.maturityVectorIdentity||!input.safetyEnvelopeIdentity)return fail('ADOPTION_RECEIPT_BINDING_MISSING','Receipt bindings are incomplete');
  if(input.normalizationFrontier.projectId!==input.projectId)return fail('ADOPTION_RECEIPT_PROJECT_MISMATCH','Normalization Frontier project does not match receipt project');
  const fingerprints=normalizeFingerprints(input.sourceFingerprints);if(!fingerprints.ok)return fingerprints;
  if((input.bridgeIds.length||input.membraneIds.length)&&fingerprints.value.length===0)return fail('ADOPTION_RECEIPT_FINGERPRINTS_MISSING','Legacy bindings require explicit source fingerprints');
  const partition=normalizeDomainPartition(input);if(!partition.ok)return partition;
  const spine=buildAdoptionProofSpine(proofInputs,options);if(!spine.ok)return spine;
  const nextSafeSlice=input.nextSafeSlice?{targetDomains:[...input.nextSafeSlice.targetDomains].sort(compareCodePoint),requiredDomains:[...input.nextSafeSlice.requiredDomains].sort(compareCodePoint),blockedDomains:[...input.nextSafeSlice.blockedDomains].sort(compareCodePoint),optionalCleanup:[...input.nextSafeSlice.optionalCleanup].sort(compareCodePoint)}:undefined;
  const normalized={...input,...partition.value,sourceFingerprints:fingerprints.value,normalizationFrontier:{...input.normalizationFrontier,domains:[...input.normalizationFrontier.domains].sort((a,b)=>compareCodePoint(a.domain,b.domain))},bridgeIds:[...input.bridgeIds].sort(compareCodePoint),membraneIds:[...input.membraneIds].sort(compareCodePoint),driftSummary:[...input.driftSummary].sort(compareCodePoint),quarantineIds:[...input.quarantineIds].sort(compareCodePoint),completedIncrementIds:[...input.completedIncrementIds].sort(compareCodePoint),blockers:[...input.blockers].sort(compareCodePoint),capabilityUnlocks:[...input.capabilityUnlocks].map(c=>({...c,reasons:[...c.reasons].sort(compareCodePoint)})).sort((a,b)=>compareCodePoint(a.capability,b.capability)),...(nextSafeSlice?{nextSafeSlice}:{})};
  const validity=deriveValidity(normalized);const identity=sha(options,{...normalized,validity,proofSpine:spine.value});if(!identity.ok)return identity;return {ok:true,value:deepFreeze({...normalized,semanticIdentity:identity.value,validity,proofSpine:spine.value})};
}

export function evaluateReceiptValidity(receipt:AdoptionReceipt,current:ReceiptCurrentBindings):ReceiptValidity {if(receipt.projectId!==current.projectId)return 'PROJECT_MISMATCH';if(receipt.sourcePackIdentity!==current.sourcePackIdentity)return 'SOURCE_PACK_MISMATCH';if(receipt.policyVersion!==current.policyVersion)return 'POLICY_VERSION_UNSUPPORTED';if(receipt.profileIdentity!==current.profileIdentity||receipt.profileDigest!==current.profileDigest)return 'STALE';const currentFingerprints=new Map(current.sourceFingerprints.map(binding=>[binding.id,binding.fingerprint] as const));for(const binding of receipt.sourceFingerprints){const currentFingerprint=currentFingerprints.get(binding.id);if(currentFingerprint===undefined)return 'INDETERMINATE';if(currentFingerprint!==binding.fingerprint)return 'STALE';}return receipt.validity;}

export function detectAdoptionRegression(previous:AdoptionReceipt,current:AdoptionReceipt):readonly AdoptionRegression[] {const regressions:AdoptionRegression[]=[];const prevFrontier=new Map(previous.normalizationFrontier.domains.map(d=>[d.domain,d.state] as const));const curFrontier=new Map(current.normalizationFrontier.domains.map(d=>[d.domain,d.state] as const));for(const [domain,state] of prevFrontier){const now=curFrontier.get(domain);if(state==='GEF_CANONICAL'&&now!==state)regressions.push({code:'CANONICAL_DOMAIN_REGRESSION',domain,message:`Canonical domain regressed to ${now??'MISSING'}`});}const currentGoverned=new Set(current.governedDomains);for(const domain of previous.governedDomains)if(!currentGoverned.has(domain))regressions.push({code:'GOVERNANCE_DOMAIN_REGRESSION',domain,message:'Previously governed domain is no longer governed'});const prevCaps=new Map(previous.capabilityUnlocks.map(c=>[c.capability,c.unlocked] as const));for(const cap of current.capabilityUnlocks)if(prevCaps.get(cap.capability)===true&&!cap.unlocked)regressions.push({code:'CAPABILITY_REGRESSION',capability:cap.capability,message:'Previously unlocked capability is no longer unlocked'});const currentFingerprints=new Map(current.sourceFingerprints.map(binding=>[binding.id,binding.fingerprint] as const));for(const binding of previous.sourceFingerprints){const now=currentFingerprints.get(binding.id);if(now===undefined)regressions.push({code:'LEGACY_BINDING_MISSING',bindingId:binding.id,message:'Previously bound legacy source fingerprint is missing'});else if(now!==binding.fingerprint)regressions.push({code:'LEGACY_BINDING_STALE',bindingId:binding.id,message:'Legacy source fingerprint changed'});}if(previous.sourcePackIdentity!==current.sourcePackIdentity)regressions.push({code:'SOURCE_PACK_BINDING_CHANGED',message:'Source Pack identity changed'});if(previous.profileIdentity!==current.profileIdentity||previous.profileDigest!==current.profileDigest)regressions.push({code:'PROFILE_BINDING_CHANGED',message:'Profile binding changed'});return deepFreeze(regressions.sort((a,b)=>compareCodePoint(`${a.code}:${a.domain??''}:${a.capability??''}:${a.bindingId??''}`,`${b.code}:${b.domain??''}:${b.capability??''}:${b.bindingId??''}`)));}
