import type { AdoptionReceipt, AdoptionReceiptInput, AdoptionRegression, CapabilityRequirement, CapabilityUnlock, DriftClass, DriftSummaryEntry, GovernanceDeltaReceipt, GovernanceMaturity, GovernanceMaturityVector, OperationOptions, ProofNode, ProofNodeInput, QuarantineSummaryEntry, ReceiptCurrentBindings, ReceiptValidity, Result, SourceFingerprintBinding } from './types.js';
import { compareCodePoint, deepFreeze, DEFAULT_MAX_DEPTH, DEFAULT_MAX_EDGES, DEFAULT_MAX_NODES, fail, hasSecretLikeKey, safeLimit, sha } from './utils.js';
import { buildGovernanceMaturityVector, maturitySatisfies } from './policy.js';

const DRIFT_CLASSES=new Set<DriftClass>(['DRIFT_NONE','DOCUMENTATION_DRIFT','IMPLEMENTATION_DRIFT','TEST_DRIFT','GOVERNANCE_DRIFT','ARCHITECTURAL_DRIFT','INTENT_UNKNOWN','CONFLICTING_INTENT','LEGACY_ACCEPTED']);
const SEVERITIES=new Set(['LOW','MEDIUM','HIGH','CRITICAL']);
const MATURITY_ORDER:Readonly<Record<GovernanceMaturity,number>>={UNOBSERVED:0,OBSERVED:1,MAPPED:2,GOVERNED_PARTIAL:3,GOVERNED_CANONICAL:4,DRIFTED:-1,BLOCKED:-2};

export function evaluateCapabilityUnlock(requirement:CapabilityRequirement,vector:GovernanceMaturityVector,blockedDomains:readonly string[]=[]):CapabilityUnlock {
  const blocked=new Set(blockedDomains); const states=new Map(vector.domains.map(d=>[d.domain,d.maturity] as const)); const reasons:string[]=[];
  if(!requirement.capability)return deepFreeze({capability:'',unlocked:false,reasons:['CAPABILITY_ID_MISSING']});
  for(const need of requirement.domains){if(blocked.has(need.domain)){reasons.push(`${need.domain}:BLOCKED`);continue;}const actual=states.get(need.domain);if(!actual)reasons.push(`${need.domain}:MISSING`);else if(!maturitySatisfies(actual,need.minimum))reasons.push(`${need.domain}:${actual}<${need.minimum}`);}
  return deepFreeze({capability:requirement.capability,unlocked:reasons.length===0,reasons:reasons.sort(compareCodePoint)});
}

export function buildAdoptionProofSpine(nodes:readonly ProofNodeInput[],options:OperationOptions):Result<readonly ProofNode[]> {
  if(nodes.length>safeLimit(options.maxNodes,DEFAULT_MAX_NODES))return fail('NODE_BUDGET_EXCEEDED','Adoption Proof Spine node budget exceeded');
  const byId=new Map<string,ProofNodeInput>();let edges=0;
  for(const node of nodes){if(!node.id||!node.payloadDigest)return fail('PROOF_NODE_INVALID','Proof node binding is incomplete',node.id);if(byId.has(node.id))return fail('DUPLICATE_PROOF_NODE','Duplicate proof node',node.id);byId.set(node.id,node);edges+=node.dependencies?.length??0;if(edges>safeLimit(options.maxEdges,DEFAULT_MAX_EDGES))return fail('EDGE_BUDGET_EXCEEDED','Adoption Proof Spine edge budget exceeded');}
  for(const node of nodes)for(const dep of node.dependencies??[])if(!byId.has(dep))return fail('PROOF_DEPENDENCY_MISSING','Proof dependency not found',dep);
  const visiting=new Set<string>(),built=new Map<string,ProofNode>();
  const walk=(id:string,depth:number):Result<ProofNode>=>{if(options.cancellation?.isCancelled())return fail('CANCELLED','Operation cancelled');if(depth>safeLimit(options.maxDepth,DEFAULT_MAX_DEPTH))return fail('DEPTH_BUDGET_EXCEEDED','Adoption Proof Spine depth budget exceeded',id);if(visiting.has(id))return fail('PROOF_SPINE_CYCLE','Proof spine cycle detected',id);const existing=built.get(id);if(existing)return {ok:true,value:existing};visiting.add(id);const node=byId.get(id)!;const depDigests:string[]=[];for(const dep of [...(node.dependencies??[])].sort(compareCodePoint)){const r=walk(dep,depth+1);if(!r.ok)return r;depDigests.push(r.value.digest);}const digest=sha(options,{id,payloadDigest:node.payloadDigest,dependencies:depDigests});if(!digest.ok)return digest;const result=deepFreeze({id,digest:digest.value,dependencies:[...(node.dependencies??[])].sort(compareCodePoint)});visiting.delete(id);built.set(id,result);return {ok:true,value:result};};
  for(const id of [...byId.keys()].sort(compareCodePoint)){const r=walk(id,0);if(!r.ok)return r;}return {ok:true,value:deepFreeze([...built.values()].sort((a,b)=>compareCodePoint(a.id,b.id)))};
}

export function computeProofInvalidation(nodes:readonly ProofNode[],changedIds:readonly string[],unknownDependencyKnowledge=false):readonly string[] {if(unknownDependencyKnowledge)return deepFreeze(nodes.map(n=>n.id).sort(compareCodePoint));const affected=new Set(changedIds.filter(id=>nodes.some(n=>n.id===id)));let moved=true;while(moved){moved=false;for(const node of nodes)if(!affected.has(node.id)&&node.dependencies.some(d=>affected.has(d))){affected.add(node.id);moved=true;}}return deepFreeze([...affected].sort(compareCodePoint));}

export function buildGovernanceDeltaReceipt(input:Omit<GovernanceDeltaReceipt,'semanticIdentity'>,options:OperationOptions):Result<GovernanceDeltaReceipt> {
  if(!input.projectId||!input.beforeIdentity||!input.afterIdentity)return fail('GOVERNANCE_DELTA_BINDING_MISSING','Governance Delta Receipt identity bindings are incomplete');
  if(input.evidenceBindings.length===0)return fail('GOVERNANCE_DELTA_EVIDENCE_MISSING','Governance Delta Receipt requires exact evidence bindings');
  const normalized={...input,frontierMoved:[...input.frontierMoved].sort(compareCodePoint),bridgesAdded:[...input.bridgesAdded].sort(compareCodePoint),bridgesRetired:[...input.bridgesRetired].sort(compareCodePoint),driftChanges:[...input.driftChanges].sort(compareCodePoint),quarantineChanges:[...input.quarantineChanges].sort(compareCodePoint),capabilitiesUnlocked:[...input.capabilitiesUnlocked].sort(compareCodePoint),capabilitiesInvalidated:[...input.capabilitiesInvalidated].sort(compareCodePoint),evidenceBindings:[...input.evidenceBindings].sort(compareCodePoint)};
  const identity=sha(options,normalized);if(!identity.ok)return identity;return {ok:true,value:deepFreeze({...normalized,semanticIdentity:identity.value})};
}

function normalizeFingerprints(bindings:readonly SourceFingerprintBinding[]):Result<readonly SourceFingerprintBinding[]> {const sorted=[...bindings].map(b=>({...b})).sort((a,b)=>compareCodePoint(a.id,b.id));for(const binding of sorted)if(!binding.id||!binding.fingerprint)return fail('SOURCE_FINGERPRINT_INVALID','Source fingerprint binding is incomplete',binding.id);for(let i=1;i<sorted.length;i++)if(sorted[i]!.id===sorted[i-1]!.id)return fail('DUPLICATE_SOURCE_FINGERPRINT','Duplicate source fingerprint binding',sorted[i]!.id);return {ok:true,value:sorted};}

function normalizeDomainPartition(input:AdoptionReceiptInput):Result<Readonly<{governedDomains:readonly string[];ungovernedDomains:readonly string[];blockedDomains:readonly string[]}>> {
  const governed=[...new Set(input.governedDomains)].sort(compareCodePoint),ungoverned=[...new Set(input.ungovernedDomains)].sort(compareCodePoint),blocked=[...new Set(input.blockedDomains)].sort(compareCodePoint);const owner=new Map<string,string>();
  for(const [label,domains] of [['GOVERNED',governed],['UNGOVERNED',ungoverned],['BLOCKED',blocked]] as const)for(const domain of domains){if(!domain)return fail('ADOPTION_DOMAIN_INVALID','Adoption receipt domain cannot be empty');const previous=owner.get(domain);if(previous)return fail('ADOPTION_DOMAIN_PARTITION_CONFLICT',`Domain appears in both ${previous} and ${label}`,domain);owner.set(domain,label);}
  const vectorDomains=[...input.maturityVector.domains.map(d=>d.domain)].sort(compareCodePoint);const partitionDomains=[...owner.keys()].sort(compareCodePoint);if(vectorDomains.length!==partitionDomains.length||vectorDomains.some((d,i)=>d!==partitionDomains[i]))return fail('ADOPTION_DOMAIN_PARTITION_INCOMPLETE','Receipt domain partition must exactly cover the Governance Maturity Vector');
  const maturity=new Map(input.maturityVector.domains.map(d=>[d.domain,d.maturity] as const));for(const domain of governed)if(!['GOVERNED_PARTIAL','GOVERNED_CANONICAL'].includes(maturity.get(domain)??''))return fail('GOVERNED_DOMAIN_MATURITY_INVALID','Governed receipt domain does not have governed maturity',domain);for(const domain of blocked)if(maturity.get(domain)!=='BLOCKED')return fail('BLOCKED_DOMAIN_MATURITY_INVALID','Blocked receipt domain must have BLOCKED maturity',domain);
  return {ok:true,value:{governedDomains:governed,ungovernedDomains:ungoverned,blockedDomains:blocked}};
}

function normalizeDrift(entries:readonly DriftSummaryEntry[]):Result<readonly DriftSummaryEntry[]> {const sorted=[...entries].map(e=>({...e})).sort((a,b)=>compareCodePoint(`${a.domain}:${a.driftClass}`,`${b.domain}:${b.driftClass}`));for(const entry of sorted){if(!entry.domain||!DRIFT_CLASSES.has(entry.driftClass)||!SEVERITIES.has(entry.severity))return fail('DRIFT_SUMMARY_INVALID','Drift summary entry is invalid',entry.domain);}for(let i=1;i<sorted.length;i++)if(sorted[i]!.domain===sorted[i-1]!.domain&&sorted[i]!.driftClass===sorted[i-1]!.driftClass)return fail('DUPLICATE_DRIFT_SUMMARY','Duplicate drift summary entry',sorted[i]!.domain);return {ok:true,value:sorted};}
function normalizeQuarantine(entries:readonly QuarantineSummaryEntry[]):Result<readonly QuarantineSummaryEntry[]> {const sorted=[...entries].map(e=>({...e})).sort((a,b)=>compareCodePoint(a.id,b.id));for(const entry of sorted)if(!entry.id||!entry.domain||!SEVERITIES.has(entry.severity))return fail('QUARANTINE_SUMMARY_INVALID','Quarantine summary entry is invalid',entry.id);for(let i=1;i<sorted.length;i++)if(sorted[i]!.id===sorted[i-1]!.id)return fail('DUPLICATE_QUARANTINE_SUMMARY','Duplicate quarantine summary entry',sorted[i]!.id);return {ok:true,value:sorted};}
function deriveValidity(input:AdoptionReceiptInput):ReceiptValidity {if(input.blockers.length)return 'BLOCKED';if(input.ungovernedDomains.length||input.blockedDomains.length||input.capabilityUnlocks.some(c=>!c.unlocked))return 'PARTIAL';return 'VALID';}

export function buildAdoptionReceipt(input:AdoptionReceiptInput,proofInputs:readonly ProofNodeInput[],options:OperationOptions):Result<AdoptionReceipt> {
  if(hasSecretLikeKey(input))return fail('RECEIPT_SECRET_MATERIAL_FORBIDDEN','Secret-like material is forbidden in adoption receipts');
  if(!input.projectId||!input.sourcePackIdentity||!input.profileIdentity||!input.profileDigest||!input.intentCapsuleIdentity||!input.policyVersion||!input.maturityVectorIdentity||!input.safetyEnvelopeIdentity)return fail('ADOPTION_RECEIPT_BINDING_MISSING','Receipt bindings are incomplete');
  if(!['NEW_PROJECT','BROWNFIELD_INCREMENTAL','BROWNFIELD_GOVERNED_MIGRATION','OBSERVE_ONLY'].includes(input.mode))return fail('ADOPTION_MODE_UNSUPPORTED','Unsupported adoption mode');
  if(input.normalizationFrontier.projectId!==input.projectId||input.maturityVector.projectId!==input.projectId)return fail('ADOPTION_RECEIPT_PROJECT_MISMATCH','Receipt projections do not match receipt project');
  const rebuiltVector=buildGovernanceMaturityVector(input.projectId,input.maturityVector.domains,options);if(!rebuiltVector.ok)return rebuiltVector;if(rebuiltVector.value.semanticIdentity!==input.maturityVectorIdentity||input.maturityVector.semanticIdentity!==input.maturityVectorIdentity)return fail('MATURITY_VECTOR_BINDING_STALE','Governance Maturity Vector identity does not match receipt binding');
  const fingerprints=normalizeFingerprints(input.sourceFingerprints);if(!fingerprints.ok)return fingerprints;
  if((input.bridgeIds.length||input.membraneIds.length)&&fingerprints.value.length===0)return fail('ADOPTION_RECEIPT_FINGERPRINTS_MISSING','Legacy bindings require explicit source fingerprints');const fingerprintIds=new Set(fingerprints.value.map(binding=>binding.id));for(const id of [...input.bridgeIds,...input.membraneIds])if(!fingerprintIds.has(id))return fail('ADOPTION_RECEIPT_FINGERPRINT_MISSING','Every legacy binding requires its own source fingerprint',id);
  const partition=normalizeDomainPartition(input);if(!partition.ok)return partition;const drift=normalizeDrift(input.driftSummary);if(!drift.ok)return drift;const quarantine=normalizeQuarantine(input.quarantineSummary);if(!quarantine.ok)return quarantine;
  const caps=[...input.capabilityUnlocks].map(c=>({...c,reasons:[...c.reasons].sort(compareCodePoint)})).sort((a,b)=>compareCodePoint(a.capability,b.capability));for(const cap of caps)if(!cap.capability)return fail('CAPABILITY_UNLOCK_AMBIGUOUS','Capability unlock entry requires capability identity');for(let i=1;i<caps.length;i++)if(caps[i]!.capability===caps[i-1]!.capability)return fail('CAPABILITY_UNLOCK_AMBIGUOUS','Duplicate capability unlock entry',caps[i]!.capability);
  const spine=buildAdoptionProofSpine(proofInputs,options);if(!spine.ok)return spine;
  const nextSafeSlice=input.nextSafeSlice?{targetDomains:[...input.nextSafeSlice.targetDomains].sort(compareCodePoint),requiredDomains:[...input.nextSafeSlice.requiredDomains].sort(compareCodePoint),requiredMappings:[...input.nextSafeSlice.requiredMappings].sort(compareCodePoint),unresolvedBlockers:[...input.nextSafeSlice.unresolvedBlockers].sort(compareCodePoint),blockedDomains:[...input.nextSafeSlice.blockedDomains].sort(compareCodePoint),optionalCleanup:[...input.nextSafeSlice.optionalCleanup].sort(compareCodePoint),postAdoptionMaturityDelta:[...input.nextSafeSlice.postAdoptionMaturityDelta].sort((a,b)=>compareCodePoint(a.domain,b.domain)),safetyEnvelopeIdentity:input.nextSafeSlice.safetyEnvelopeIdentity}:undefined;
  const normalized={...input,maturityVector:rebuiltVector.value,...partition.value,sourceFingerprints:fingerprints.value,normalizationFrontier:{...input.normalizationFrontier,domains:[...input.normalizationFrontier.domains].sort((a,b)=>compareCodePoint(a.domain,b.domain))},bridgeIds:[...input.bridgeIds].sort(compareCodePoint),membraneIds:[...input.membraneIds].sort(compareCodePoint),driftSummary:drift.value,quarantineSummary:quarantine.value,completedIncrementIds:[...input.completedIncrementIds].sort(compareCodePoint),blockers:[...input.blockers].sort(compareCodePoint),capabilityUnlocks:caps,...(nextSafeSlice?{nextSafeSlice}:{})};
  const validity=deriveValidity(normalized);const identity=sha(options,{...normalized,validity,proofSpine:spine.value});if(!identity.ok)return identity;return {ok:true,value:deepFreeze({...normalized,semanticIdentity:identity.value,validity,proofSpine:spine.value})};
}

export function evaluateReceiptValidity(receipt:AdoptionReceipt,current:ReceiptCurrentBindings):ReceiptValidity {if(receipt.projectId!==current.projectId)return 'PROJECT_MISMATCH';if(receipt.sourcePackIdentity!==current.sourcePackIdentity)return 'SOURCE_PACK_MISMATCH';if(receipt.policyVersion!==current.policyVersion)return 'POLICY_VERSION_UNSUPPORTED';if(receipt.profileIdentity!==current.profileIdentity||receipt.profileDigest!==current.profileDigest)return 'STALE';const currentFingerprints=new Map<string,string>();for(const binding of current.sourceFingerprints){if(!binding.id||!binding.fingerprint||currentFingerprints.has(binding.id))return 'INDETERMINATE';currentFingerprints.set(binding.id,binding.fingerprint);}for(const binding of receipt.sourceFingerprints){const currentFingerprint=currentFingerprints.get(binding.id);if(currentFingerprint===undefined)return 'INDETERMINATE';if(currentFingerprint!==binding.fingerprint)return 'STALE';}return receipt.validity;}

export function detectAdoptionRegression(previous:AdoptionReceipt,current:AdoptionReceipt):readonly AdoptionRegression[] {
  const regressions:AdoptionRegression[]=[];const prevFrontier=new Map(previous.normalizationFrontier.domains.map(d=>[d.domain,d.state] as const));const curFrontier=new Map(current.normalizationFrontier.domains.map(d=>[d.domain,d.state] as const));for(const [domain,state] of prevFrontier){const now=curFrontier.get(domain);if(state==='GEF_CANONICAL'&&now!==state)regressions.push({code:'CANONICAL_DOMAIN_REGRESSION',domain,message:`Canonical domain regressed to ${now??'MISSING'}`});}
  const prevMaturity=new Map(previous.maturityVector.domains.map(d=>[d.domain,d.maturity] as const));const curMaturity=new Map(current.maturityVector.domains.map(d=>[d.domain,d.maturity] as const));for(const [domain,before] of prevMaturity){const after=curMaturity.get(domain);if(after!==undefined&&(MATURITY_ORDER[after]??-99)<(MATURITY_ORDER[before]??-99))regressions.push({code:'GOVERNANCE_MATURITY_DOWNGRADE',domain,beforeMaturity:before,afterMaturity:after,message:'Governance maturity downgraded'});}
  const currentGoverned=new Set(current.governedDomains);for(const domain of previous.governedDomains)if(!currentGoverned.has(domain))regressions.push({code:'GOVERNANCE_DOMAIN_REGRESSION',domain,message:'Previously governed domain is no longer governed'});const prevCaps=new Map(previous.capabilityUnlocks.map(c=>[c.capability,c.unlocked] as const));for(const cap of current.capabilityUnlocks)if(prevCaps.get(cap.capability)===true&&!cap.unlocked)regressions.push({code:'CAPABILITY_REGRESSION',capability:cap.capability,message:'Previously unlocked capability is no longer unlocked'});
  const prevConflicts=new Set(previous.driftSummary.filter(d=>d.driftClass==='CONFLICTING_INTENT').map(d=>d.domain));for(const drift of current.driftSummary)if(drift.driftClass==='CONFLICTING_INTENT'&&!prevConflicts.has(drift.domain))regressions.push({code:'LEGACY_AUTHORITY_CONFLICT_REGRESSION',domain:drift.domain,message:'A new authority conflict was introduced'});
  const currentFingerprints=new Map(current.sourceFingerprints.map(binding=>[binding.id,binding.fingerprint] as const));for(const binding of previous.sourceFingerprints){const now=currentFingerprints.get(binding.id);if(now===undefined)regressions.push({code:'LEGACY_BINDING_MISSING',bindingId:binding.id,message:'Previously bound legacy source fingerprint is missing'});else if(now!==binding.fingerprint)regressions.push({code:'LEGACY_BINDING_STALE',bindingId:binding.id,message:'Legacy source fingerprint changed'});}if(previous.sourcePackIdentity!==current.sourcePackIdentity)regressions.push({code:'SOURCE_PACK_BINDING_CHANGED',message:'Source Pack identity changed'});if(previous.profileIdentity!==current.profileIdentity||previous.profileDigest!==current.profileDigest)regressions.push({code:'PROFILE_BINDING_CHANGED',message:'Profile binding changed'});return deepFreeze(regressions.sort((a,b)=>compareCodePoint(`${a.code}:${a.domain??''}:${a.capability??''}:${a.bindingId??''}`,`${b.code}:${b.domain??''}:${b.capability??''}:${b.bindingId??''}`)));
}
