import { createHash } from 'node:crypto';
const cmp=(a,b)=>String(a)<String(b)?-1:String(a)>String(b)?1:0;
const stable = value => JSON.stringify(canon(value));
function canon(v){if(Array.isArray(v)) return v.map(canon); if(v&&typeof v==='object'){return Object.fromEntries(Object.keys(v).sort(cmp).map(k=>[k,canon(v[k])]))} return v}
export function digest(domain,value){return createHash('sha256').update(`GEF:${domain}:v1\0${stable(value)}`).digest('hex')}
export const freezeReceipt=(domain,payload)=>Object.freeze({...payload,digest:digest(domain,payload)});
export function classifyThreat({surface='unknown',trusted=false,privileged=false}={}){const known=['filesystem','process','network','scm','ci','secret','supply-chain'];const uncertainty=known.includes(surface)?'NONE':'UNKNOWN';const risk=uncertainty==='UNKNOWN'||(!trusted&&privileged)?'CRITICAL':!trusted?'HIGH':privileged?'HIGH':'STANDARD';return freezeReceipt('M34:THREAT',{surface,trusted,privileged,uncertainty,risk})}
export function redactSecrets(input){const text=String(input);const patterns=[/gh[pousr]_[A-Za-z0-9_]{20,}/g,/AKIA[0-9A-Z]{16}/g,/(?:password|token|secret)\s*[=:]\s*[^\s,;]+/gi];let redacted=text;for(const p of patterns)redacted=redacted.replace(p,'[REDACTED]');return freezeReceipt('M34:SECRET',{redacted,detected:redacted!==text})}
export function dependencySecurity({manifestDigest,lockDigest,auditCritical=0,provenance='verified'}={}){const state=!manifestDigest||!lockDigest?'UNKNOWN':auditCritical>0?'BLOCKED':provenance!=='verified'?'REVIEW':'PASS';return freezeReceipt('M34:DEPENDENCY',{manifestDigest,lockDigest,auditCritical,provenance,state})}
export function githubSecurity({immutableRef=false,untrustedFork=false,writePermission=false}={}){const state=untrustedFork&&writePermission?'BLOCKED':!immutableRef?'REVIEW':'PASS';return freezeReceipt('M34:GITHUB',{immutableRef,untrustedFork,writePermission,state})}
const destructiveRank={NONE:0,REVERSIBLE:1,MUTATING:2,DESTRUCTIVE:3,IRREVERSIBLE:4};
export function safetyDecision({classification='NONE',blastRadius='known',requested='AUTO',restricted=false,capabilities=[]}={}){const cls=classification in destructiveRank?classification:'IRREVERSIBLE';let confirmation=destructiveRank[cls]>=4?'EXPLICIT':destructiveRank[cls]>=3?'POLICY_AUTHORIZED':'AUTO';if(blastRadius!=='known'||restricted)confirmation='FORBIDDEN';const minimum=[...new Set(capabilities)].sort(cmp);return freezeReceipt('M35:SAFETY',{classification:cls,confirmation,requested,restricted,minimum,state:confirmation==='FORBIDDEN'?'BLOCKED':'READY'})}
export function normalizeRestrictedPath(path){const p=String(path).replaceAll('\\','/');const escape=p.split('/').includes('..');const sensitive=/(^|\/)(\.git|\.env|id_rsa|credentials)(\/|$)/i.test(p);return freezeReceipt('M35:PATH',{path:p,escape,sensitive,state:escape||sensitive?'RESTRICTED':'ALLOWED'})}
export function backupManifest(entries=[]){const items=entries.map(e=>({id:String(e.id),digest:String(e.digest)})).sort((a,b)=>cmp(a.id,b.id));return freezeReceipt('M36:BACKUP',{items,verified:items.every(x=>/^[a-f0-9]{64}$/i.test(x.digest))})}
export function recoveryPlan({journal=[],candidateMatches=true,corrupt=false,maxAttempts=3}={}){const last=journal.at(-1)?.state??'NONE';let action='RESTART';if(corrupt)action='QUARANTINE';else if(!candidateMatches)action='BLOCKED';else if(last==='PREPARE')action='ROLLBACK';else if(last==='COMMIT')action='NOOP';else if(last==='INTERRUPTED')action='RESUME';return freezeReceipt('M36:RECOVERY',{last,action,maxAttempts,state:action==='BLOCKED'?'BLOCKED':'READY'})}
export function integritySnapshot(value){return freezeReceipt('M37:INTEGRITY',{root:digest('M37:MERKLE',value),schema:1})}
export function detectDrift(before,after,{authorized=false}={}){const a=digest('M37:STATE',before),b=digest('M37:STATE',after);const changed=a!==b;return freezeReceipt('M37:DRIFT',{before:a,after:b,changed,class:!changed?'NONE':authorized?'EXPECTED':'UNEXPECTED'})}
export function resolveCanonical(sources=[]){const rank={checkpoint:7,decision:6,scope:5,dod:4,architecture:3,requirements:2,other:1};const sorted=[...sources].sort((a,b)=>(rank[b.kind]??0)-(rank[a.kind]??0)||cmp(a.id,b.id));const top=sorted[0];const conflict=!!top&&sorted.some(x=>(rank[x.kind]??0)===(rank[top.kind]??0)&&x.value!==top.value);return freezeReceipt('M37:SOURCE',{selected:conflict?null:top??null,conflict,state:conflict?'CONFLICT':top?'READY':'UNKNOWN'})}
export function capabilityEnvelope(observations=[]){const caps=[],unknown=[];for(const o of observations){if(o?.verified===true&&typeof o.capability==='string')caps.push(o.capability);else unknown.push(o?.capability??'unknown')}return freezeReceipt('M38:CAPABILITY',{capabilities:[...new Set(caps)].sort(cmp),unknown:[...new Set(unknown)].sort(cmp),state:unknown.length?'DEGRADED':'COMPATIBLE'})}
export function compatibility(required=[],envelope){const have=new Set(envelope?.capabilities??[]);const missing=[...new Set(required)].filter(x=>!have.has(x)).sort(cmp);return freezeReceipt('M38:COMPAT',{missing,state:missing.length?'INCOMPATIBLE':'COMPATIBLE'})}
function optionalAdapter(name,observation,map={}){const available=observation?.verified===true&&observation?.identity===name;const capabilities=available?Object.keys(map).filter(k=>map[k]===true).sort(cmp):[];return freezeReceipt(`ADAPTER:${name}`,{name,available,capabilities,state:available?'AVAILABLE':'UNAVAILABLE',coreRequired:false})}
export const uadsAdapter=(observation,map)=>optionalAdapter('uads',observation,map);
export const hiveAdapter=(observation,{contextDigest=null,capabilities={}}={})=>Object.freeze({...optionalAdapter('hive',observation,capabilities),contextDigest:observation?.verified===true?contextDigest:null});
export function chooseOptional(adapter,required=[]){const have=new Set(adapter?.capabilities??[]);const usable=adapter?.available===true&&required.every(x=>have.has(x));return freezeReceipt('OPTIONAL:ROUTE',{adapter:adapter?.name??'unknown',route:usable?'ADAPTER':'CORE',obligationLoss:false})}
