import type{AvailabilityState,DeadlineComparison,DurationProjection,ForecastIntervalEnvelope,OperationOptions,RemainingWorkVector,Result,RiskAdjustmentVector,ScenarioTriad,ThroughputModel,UnknownWorkReserve}from'./types.js';
import{createForecastInterval as weakCreateForecastInterval,verifyForecastInterval as weakVerifyForecastInterval,createScenarioTriad as weakCreateScenarioTriad,verifyScenarioTriad as weakVerifyScenarioTriad,compareDeadline as weakCompareDeadline}from'./s03-uncertainty.js';
import{verifyDurationProjection,verifyDurationProjectionAgainstSources}from'./s02-hardening.js';
import{fail}from'./utils.js';
export function createForecastInterval(duration:DurationProjection|null,availability:AvailabilityState,risk:RiskAdjustmentVector|null,reserve:UnknownWorkReserve|null,options:OperationOptions):Result<ForecastIntervalEnvelope>{if(duration!==null){const vd=verifyDurationProjection(duration,options);if(!vd.ok||!vd.value)return vd.ok?fail('DURATION_PROJECTION_TAMPERED','Forecast interval requires verified duration projection'):vd;}return weakCreateForecastInterval(duration,availability,risk,reserve,options);}
export function createForecastIntervalAgainstSources(duration:DurationProjection,remaining:RemainingWorkVector,model:ThroughputModel,availability:AvailabilityState,risk:RiskAdjustmentVector|null,reserve:UnknownWorkReserve|null,options:OperationOptions):Result<ForecastIntervalEnvelope>{const vd=verifyDurationProjectionAgainstSources(duration,remaining,model,options);if(!vd.ok||!vd.value)return vd.ok?fail('DURATION_SOURCE_MISMATCH','Forecast duration does not bind exact remaining-work and throughput sources'):vd;return createForecastInterval(duration,availability,risk,reserve,options);}
export function verifyForecastInterval(value:ForecastIntervalEnvelope,options:OperationOptions):Result<boolean>{return weakVerifyForecastInterval(value,options);}
export function createScenarioTriad(interval:ForecastIntervalEnvelope,options:OperationOptions):Result<ScenarioTriad>{const vi=verifyForecastInterval(interval,options);if(!vi.ok||!vi.value)return vi.ok?fail('FORECAST_INTERVAL_TAMPERED','Scenario triad requires verified forecast interval'):vi;return weakCreateScenarioTriad(interval,options);}
export function verifyScenarioTriad(value:ScenarioTriad,options:OperationOptions):Result<boolean>{return weakVerifyScenarioTriad(value,options);}
export function verifyScenarioTriadAgainstInterval(value:ScenarioTriad,interval:ForecastIntervalEnvelope,options:OperationOptions):Result<boolean>{const vv=verifyScenarioTriad(value,options);if(!vv.ok||!vv.value)return vv;const vi=verifyForecastInterval(interval,options);if(!vi.ok||!vi.value)return vi;const expected=createScenarioTriad(interval,options);return expected.ok?{ok:true,value:expected.value.scenarioDigest===value.scenarioDigest}:expected;}
export function compareDeadline(interval:ForecastIntervalEnvelope,asOfEpochMs:number,deadlineEpochMs:number,options:OperationOptions):Result<DeadlineComparison>{const vi=verifyForecastInterval(interval,options);if(!vi.ok||!vi.value)return vi.ok?fail('FORECAST_INTERVAL_TAMPERED','Deadline comparison requires verified forecast interval'):vi;return weakCompareDeadline(interval,asOfEpochMs,deadlineEpochMs,options);}
