import type{ActualOutcome,ForecastActualVarianceReceipt,ForecastForCalibration,ForecastRevisionReceipt,OperationOptions,Result,RevisionReplayGuard}from'./types.js';
import{createForecastActualVarianceReceipt as weakCreateVariance,verifyForecastActualVarianceReceipt as weakVerifyVariance,verifyActualOutcome,createRevisionReplayGuard as weakCreateReplay,verifyForecastRevisionReceipt}from'./s04-calibration.js';
import{deepFreeze,fail,sha,sortedUnique}from'./utils.js';

export function createForecastActualVarianceReceipt(forecast:ForecastForCalibration,actual:ActualOutcome,options:OperationOptions):Result<ForecastActualVarianceReceipt>{const va=verifyActualOutcome(actual,options);if(!va.ok||!va.value)return va.ok?fail('ACTUAL_OUTCOME_TAMPERED','Forecast variance receipt requires verified actual outcome'):va;return weakCreateVariance(forecast,actual,options);}
export function verifyForecastActualVarianceReceipt(value:ForecastActualVarianceReceipt,options:OperationOptions):Result<boolean>{return weakVerifyVariance(value,options);}
export function verifyForecastActualVarianceReceiptAgainstActual(value:ForecastActualVarianceReceipt,actual:ActualOutcome,options:OperationOptions):Result<boolean>{const va=verifyActualOutcome(actual,options);if(!va.ok||!va.value)return va;const vr=weakVerifyVariance(value,options);if(!vr.ok||!vr.value)return vr;if(value.actualDigest!==actual.actualDigest||value.actualDurationMs!==actual.actualDurationMs||value.forecastSnapshotDigest!==actual.forecastSnapshotDigest)return{ok:true,value:false};return{ok:true,value:true};}

function validateRevisionLineage(revisions:readonly ForecastRevisionReceipt[],options:OperationOptions):Result<boolean>{const byDigest=new Map<string,ForecastRevisionReceipt>();for(const r of revisions){const vr=verifyForecastRevisionReceipt(r,options);if(!vr.ok||!vr.value)return vr;byDigest.set(r.receiptDigest,r);}for(const r of revisions){const seen=new Set<string>([r.receiptDigest]);let predecessorDigest=r.predecessorRevisionDigest;let requiredAfterSnapshot=r.beforeSnapshotDigest;while(predecessorDigest!==null){if(seen.has(predecessorDigest))return{ok:true,value:false};seen.add(predecessorDigest);const predecessor=byDigest.get(predecessorDigest);if(!predecessor)return{ok:true,value:false};if(predecessor.afterSnapshotDigest!==requiredAfterSnapshot)return{ok:true,value:false};requiredAfterSnapshot=predecessor.beforeSnapshotDigest;predecessorDigest=predecessor.predecessorRevisionDigest;}}
return{ok:true,value:true};}
export function createRevisionReplayGuard(actuals:readonly ActualOutcome[],revisions:readonly ForecastRevisionReceipt[],options:OperationOptions):Result<RevisionReplayGuard>{const lineage=validateRevisionLineage(revisions,options);if(!lineage.ok)return lineage;if(!lineage.value)return fail('REVISION_LINEAGE_INVALID','Revision history contains orphaned, discontinuous or cyclic predecessor lineage');const weak=weakCreateReplay(actuals,revisions,options);if(!weak.ok)return weak;const body={actualDigests:sortedUnique(actuals.map(a=>a.actualDigest)),revisionDigests:sortedUnique(revisions.map(r=>r.receiptDigest)),duplicateActualDigests:weak.value.duplicateActualDigests,duplicateRevisionDigests:weak.value.duplicateRevisionDigests,splitBrain:weak.value.splitBrain};const d=sha(options,body);if(!d.ok)return d;return{ok:true,value:deepFreeze({...body,guardDigest:d.value})};}
