import type{DelegatedEstimationMetricHandoff,EstimationBindingObservation,EstimationIntegrityReceipt,EstimationSnapshotCapsule,EstimationStalenessReport,OperationOptions,Result,StatusEstimationHandoff}from'./types.js';
import{fail,isSha256}from'./utils.js';
import{createEstimationIntegrityReceipt as weakCreateIntegrityReceipt,verifyEstimationIntegrityReceipt as weakVerifyIntegrityReceipt,verifyEstimationSnapshot as weakVerifySnapshot,createDelegatedEstimationMetricHandoff as weakCreateDelegated,verifyDelegatedEstimationMetricHandoff as weakVerifyDelegated,createStatusEstimationHandoff as weakCreateStatus,verifyStatusEstimationHandoff as weakVerifyStatus,detectEstimationStaleness as weakDetectStaleness}from'./s05-snapshot.js';

function invalid():Result<boolean>{return{ok:true,value:false};}
export function verifyEstimationSnapshot(value:EstimationSnapshotCapsule,options:OperationOptions):Result<boolean>{const base=weakVerifySnapshot(value,options);if(!base.ok||!base.value)return base;if(value.confidence.availability!==value.availability)return invalid();if(value.availability==='AVAILABLE'){if(value.confidence.confidence==='UNKNOWN')return invalid();}else if(value.confidence.confidence!=='UNKNOWN')return invalid();if(value.calibrationReceiptDigests.some(d=>!isSha256(d))||new Set(value.calibrationReceiptDigests).size!==value.calibrationReceiptDigests.length)return invalid();return{ok:true,value:true};}
export function createEstimationIntegrityReceipt(snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<EstimationIntegrityReceipt>{const verified=verifyEstimationSnapshot(snapshot,options);if(!verified.ok)return verified;if(!verified.value)return fail('ESTIMATION_SNAPSHOT_TAMPERED','Integrity receipt requires a strictly verified estimation snapshot');return weakCreateIntegrityReceipt(snapshot,options);}
export function verifyEstimationIntegrityReceipt(value:EstimationIntegrityReceipt,snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<boolean>{const sv=verifyEstimationSnapshot(snapshot,options);if(!sv.ok||!sv.value)return sv;const weak=weakVerifyIntegrityReceipt(value,options);if(!weak.ok||!weak.value)return weak;const expected=weakCreateIntegrityReceipt(snapshot,options);if(!expected.ok)return expected;return{ok:true,value:expected.value.receiptDigest===value.receiptDigest&&expected.value.snapshotDigest===value.snapshotDigest&&expected.value.semanticDigest===value.semanticDigest&&expected.value.recomputedSemanticDigest===value.recomputedSemanticDigest&&value.valid===true};}
export function createDelegatedEstimationMetricHandoff(snapshot:EstimationSnapshotCapsule,sourceIdentityDigest:string,validityBindingDigest:string,options:OperationOptions):Result<DelegatedEstimationMetricHandoff>{const sv=verifyEstimationSnapshot(snapshot,options);if(!sv.ok)return sv;if(!sv.value)return fail('ESTIMATION_SNAPSHOT_TAMPERED','M20 handoff requires a strictly verified estimation snapshot');return weakCreateDelegated(snapshot,sourceIdentityDigest,validityBindingDigest,options);}
export function verifyDelegatedEstimationMetricHandoff(value:DelegatedEstimationMetricHandoff,snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<boolean>{const sv=verifyEstimationSnapshot(snapshot,options);if(!sv.ok||!sv.value)return sv;const weak=weakVerifyDelegated(value,options);if(!weak.ok||!weak.value)return weak;const expected=weakCreateDelegated(snapshot,value.sourceIdentityDigest,value.validityBindingDigest,options);return expected.ok?{ok:true,value:expected.value.handoffDigest===value.handoffDigest}:expected;}
export function createStatusEstimationHandoff(snapshot:EstimationSnapshotCapsule,revisionObserved:boolean,options:OperationOptions):Result<StatusEstimationHandoff>{const sv=verifyEstimationSnapshot(snapshot,options);if(!sv.ok)return sv;if(!sv.value)return fail('ESTIMATION_SNAPSHOT_TAMPERED','M23 handoff requires a strictly verified estimation snapshot');return weakCreateStatus(snapshot,revisionObserved,options);}
export function verifyStatusEstimationHandoff(value:StatusEstimationHandoff,snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<boolean>{const sv=verifyEstimationSnapshot(snapshot,options);if(!sv.ok||!sv.value)return sv;const weak=weakVerifyStatus(value,options);if(!weak.ok||!weak.value)return weak;const expected=weakCreateStatus(snapshot,value.revisionObserved,options);return expected.ok?{ok:true,value:expected.value.handoffDigest===value.handoffDigest}:expected;}
export function detectEstimationStaleness(snapshot:EstimationSnapshotCapsule,current:EstimationBindingObservation,options:OperationOptions):Result<EstimationStalenessReport>{const sv=verifyEstimationSnapshot(snapshot,options);if(!sv.ok)return sv;if(!sv.value)return fail('ESTIMATION_SNAPSHOT_TAMPERED','Staleness detection requires a strictly verified estimation snapshot');return weakDetectStaleness(snapshot,current,options);}
