import type{BaselineSufficiencyGate,CalibrationBiasSentinel,DeadlineComparison,DelegatedEstimationMetricHandoff,EstimationBindingManifest,EstimationConfidenceCompletenessState,EstimationIntegrityReceipt,EstimationSnapshotCapsule,ForecastIntervalEnvelope,ForecastVsActualVarianceReceipt,ModelDriftSentinel,OperationOptions,Result,RobustThroughputEstimator,ScenarioTriad,StatusEstimationHandoff}from'./types.js';
import{compareRational,createRational,digestValue,fail,ok}from'./utils.js';

export function deriveEstimationConfidence(sufficiency:BaselineSufficiencyGate,model:RobustThroughputEstimator|null,receipts:readonly ForecastVsActualVarianceReceipt[],bias:CalibrationBiasSentinel,drift:ModelDriftSentinel,options:OperationOptions):Result<EstimationConfidenceCompletenessState>{
 if(sufficiency.state!=='AVAILABLE'||model===null){const body={availability:sufficiency.state,confidence:'UNKNOWN' as const,reasonCodes:[...new Set([...sufficiency.reasonCodes,'ESTIMATION_NOT_AVAILABLE'])].sort()};const digest=digestValue(options.digest,'ECS22',body);if(!digest.ok)return digest;return ok({...body,stateDigest:digest.value});}
 const reasons:string[]=[];const twiceQ1=createRational(BigInt(model.q1.numerator)*2n,BigInt(model.q1.denominator),options,'ECS22_2X_Q1');if(!twiceQ1.ok)return twiceQ1;const threeQ1=createRational(BigInt(model.q1.numerator)*3n,BigInt(model.q1.denominator),options,'ECS22_3X_Q1');if(!threeQ1.ok)return threeQ1;const twiceQ3=createRational(BigInt(model.q3.numerator)*2n,BigInt(model.q3.denominator),options,'ECS22_2X_Q3');if(!twiceQ3.ok)return twiceQ3;
 const dispersionLe2=compareRational(model.q3,twiceQ1.value)<=0;const dispersionLe15=compareRational(twiceQ3.value,threeQ1.value)<=0;const unique=new Map(receipts.map((r)=>[r.actualId,r] as const));const resolved=[...unique.values()].sort((a,b)=>b.observedAtEpochMs-a.observedAtEpochMs||a.actualId.localeCompare(b.actualId));const recent5=resolved.slice(0,5);const coverageRecent=recent5.filter((r)=>r.outcome==='WITHIN_INTERVAL').length;const noActive=bias.state==='NONE'&&drift.state==='CURRENT';
 let confidence:'LOW'|'MEDIUM'|'HIGH'='LOW';
 const high=model.sampleCount>=8&&dispersionLe15&&noActive&&resolved.length>=5&&recent5.length===5&&coverageRecent>=4;
 const medium=model.sampleCount>=5&&dispersionLe2&&noActive&&resolved.length>=3;
 if(high)confidence='HIGH';else if(medium)confidence='MEDIUM';
 if(model.sampleCount<5)reasons.push('SAMPLE_COUNT_LOW');else if(model.sampleCount<8)reasons.push('SAMPLE_COUNT_BELOW_HIGH');if(!dispersionLe2)reasons.push('DISPERSION_ABOVE_2');else if(!dispersionLe15)reasons.push('DISPERSION_ABOVE_3_2');if(resolved.length<3)reasons.push('CALIBRATION_HISTORY_LT_3');else if(resolved.length<5)reasons.push('CALIBRATION_HISTORY_LT_5');if(recent5.length===5&&coverageRecent<4)reasons.push('RECENT_COVERAGE_BELOW_4_5');if(bias.state!=='NONE')reasons.push(`BIAS_${bias.state}`);if(drift.state!=='CURRENT')reasons.push(`DRIFT_${drift.state}`);
 const body={availability:'AVAILABLE' as const,confidence,reasonCodes:[...new Set(reasons)].sort()};const digest=digestValue(options.digest,'ECS22',body);if(!digest.ok)return digest;return ok({...body,stateDigest:digest.value});
}

function semanticBody(input:{projectId:string;lineageDigest:string;asOfEpochMs:number;baselineAdmissionDigest:string;bindingManifestDigest:string;observationIndexDigest:string;throughputModelDigest:string|null;forecastEnvelope:ForecastIntervalEnvelope;scenarioTriad:ScenarioTriad;confidenceState:EstimationConfidenceCompletenessState;calibrationEpochId:string;revisionDigest:string|null}){return input;}
export function createEstimationSemanticDigest(input:Parameters<typeof semanticBody>[0],options:OperationOptions):Result<string>{return digestValue(options.digest,'ESD22',semanticBody(input));}

export function createEstimationSnapshotCapsule(projectId:string,lineageDigest:string,asOfEpochMs:number,baselineAdmissionDigest:string,binding:EstimationBindingManifest,observationIndexDigest:string,model:RobustThroughputEstimator|null,envelope:ForecastIntervalEnvelope,scenarios:ScenarioTriad,confidence:EstimationConfidenceCompletenessState,calibrationEpochId:string,revisionDigest:string|null,options:OperationOptions):Result<EstimationSnapshotCapsule>{
 if(binding.projectId!==projectId||binding.lineageDigest!==lineageDigest||binding.calibrationEpochId!==calibrationEpochId)return fail('ESC22_BINDING_MISMATCH','Snapshot binding manifest does not match project/lineage/calibration epoch.');if(envelope.availability!==confidence.availability||scenarios.availability!==envelope.availability)return fail('ESC22_AVAILABILITY_MISMATCH','Snapshot availability states disagree.');
 const body=semanticBody({projectId,lineageDigest,asOfEpochMs,baselineAdmissionDigest,bindingManifestDigest:binding.manifestDigest,observationIndexDigest,throughputModelDigest:model?.modelDigest??null,forecastEnvelope:envelope,scenarioTriad:scenarios,confidenceState:confidence,calibrationEpochId,revisionDigest});const semantic=createEstimationSemanticDigest(body,options);if(!semantic.ok)return semantic;const digest=digestValue(options.digest,'ESC22',{...body,semanticDigest:semantic.value});if(!digest.ok)return digest;return ok({...body,semanticDigest:semantic.value,snapshotDigest:digest.value});
}

export function verifyEstimationSnapshotCapsule(snapshot:EstimationSnapshotCapsule,binding:EstimationBindingManifest,currentObservationIndexDigest:string,currentThroughputModelDigest:string|null,options:OperationOptions):Result<boolean>{
 if(snapshot.bindingManifestDigest!==binding.manifestDigest||snapshot.baselineAdmissionDigest!==binding.baselineAdmissionDigest||snapshot.observationIndexDigest!==currentObservationIndexDigest||snapshot.throughputModelDigest!==currentThroughputModelDigest||snapshot.projectId!==binding.projectId||snapshot.lineageDigest!==binding.lineageDigest||snapshot.calibrationEpochId!==binding.calibrationEpochId)return ok(false);
 const body=semanticBody({projectId:snapshot.projectId,lineageDigest:snapshot.lineageDigest,asOfEpochMs:snapshot.asOfEpochMs,baselineAdmissionDigest:snapshot.baselineAdmissionDigest,bindingManifestDigest:snapshot.bindingManifestDigest,observationIndexDigest:snapshot.observationIndexDigest,throughputModelDigest:snapshot.throughputModelDigest,forecastEnvelope:snapshot.forecastEnvelope,scenarioTriad:snapshot.scenarioTriad,confidenceState:snapshot.confidenceState,calibrationEpochId:snapshot.calibrationEpochId,revisionDigest:snapshot.revisionDigest});const semantic=createEstimationSemanticDigest(body,options);if(!semantic.ok)return semantic;if(semantic.value!==snapshot.semanticDigest)return ok(false);const expected=digestValue(options.digest,'ESC22',{...body,semanticDigest:semantic.value});if(!expected.ok)return expected;return ok(expected.value===snapshot.snapshotDigest);
}

export function createEstimationIntegrityReceipt(snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<EstimationIntegrityReceipt>{
 const body=semanticBody({projectId:snapshot.projectId,lineageDigest:snapshot.lineageDigest,asOfEpochMs:snapshot.asOfEpochMs,baselineAdmissionDigest:snapshot.baselineAdmissionDigest,bindingManifestDigest:snapshot.bindingManifestDigest,observationIndexDigest:snapshot.observationIndexDigest,throughputModelDigest:snapshot.throughputModelDigest,forecastEnvelope:snapshot.forecastEnvelope,scenarioTriad:snapshot.scenarioTriad,confidenceState:snapshot.confidenceState,calibrationEpochId:snapshot.calibrationEpochId,revisionDigest:snapshot.revisionDigest});const recomputed=createEstimationSemanticDigest(body,options);if(!recomputed.ok)return recomputed;const expectedSnapshot=digestValue(options.digest,'ESC22',{...body,semanticDigest:recomputed.value});if(!expectedSnapshot.ok)return expectedSnapshot;const valid=recomputed.value===snapshot.semanticDigest&&expectedSnapshot.value===snapshot.snapshotDigest;const receiptBody={snapshotDigest:snapshot.snapshotDigest,semanticDigest:snapshot.semanticDigest,recomputedSemanticDigest:recomputed.value,valid};const digest=digestValue(options.digest,'EIR22',receiptBody);if(!digest.ok)return digest;return ok({...receiptBody,receiptDigest:digest.value});
}

export function createDelegatedEstimationMetricHandoff(snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<DelegatedEstimationMetricHandoff>{
 const f=snapshot.forecastEnvelope;const body={owner:'M22_ESTIMATION' as const,consumer:'M20_RESPONSE' as const,snapshotDigest:snapshot.snapshotDigest,availability:snapshot.confidenceState.availability,confidence:snapshot.confidenceState.confidence,lowerDurationMs:f.lowerDurationMs,baseDurationMs:f.baseDurationMs,upperDurationMs:f.upperDurationMs,lowerCompletionEpochMs:f.lowerCompletionEpochMs,baseCompletionEpochMs:f.baseCompletionEpochMs,upperCompletionEpochMs:f.upperCompletionEpochMs};const digest=digestValue(options.digest,'DMH22',body);if(!digest.ok)return digest;return ok({...body,handoffDigest:digest.value});
}

export function createStatusEstimationHandoff(snapshot:EstimationSnapshotCapsule,deadlineComparison:DeadlineComparison|null,options:OperationOptions):Result<StatusEstimationHandoff>{
 if(deadlineComparison!==null&&deadlineComparison.forecastEnvelopeDigest!==snapshot.forecastEnvelope.envelopeDigest)return fail('SEH22_DEADLINE_BINDING_MISMATCH','Deadline comparison does not bind snapshot forecast.');const body={owner:'M22_ESTIMATION' as const,consumer:'M23_PROJECT_STATUS' as const,snapshotDigest:snapshot.snapshotDigest,availability:snapshot.confidenceState.availability,confidence:snapshot.confidenceState.confidence,forecastEnvelopeDigest:snapshot.forecastEnvelope.envelopeDigest,deadlineComparison,revisionDigest:snapshot.revisionDigest};const digest=digestValue(options.digest,'SEH22',body);if(!digest.ok)return digest;return ok({...body,handoffDigest:digest.value});
}

export function verifyDelegatedEstimationMetricHandoff(value:DelegatedEstimationMetricHandoff,snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<boolean>{const expected=createDelegatedEstimationMetricHandoff(snapshot,options);if(!expected.ok)return expected;return ok(JSON.stringify(expected.value)===JSON.stringify(value));}
export function verifyStatusEstimationHandoff(value:StatusEstimationHandoff,snapshot:EstimationSnapshotCapsule,options:OperationOptions):Result<boolean>{const expected=createStatusEstimationHandoff(snapshot,value.deadlineComparison,options);if(!expected.ok)return expected;return ok(JSON.stringify(expected.value)===JSON.stringify(value));}
