export type AvailabilityState='AVAILABLE'|'NOT_YET_BASELINED'|'STALE'|'CONFLICT'|'INDETERMINATE';
export type ConfidenceState='UNKNOWN'|'LOW'|'MEDIUM'|'HIGH';
export type TemporalObservationOwner='M43_TELEMETRY'|'EXTERNAL_CANONICAL';
export type RiskInputOwner='M43_TELEMETRY'|'M45_BENCHMARK'|'M63_EXECUTOR_PERFORMANCE'|'EXTERNAL_CANONICAL';
export type CalibrationBiasState='NONE'|'OPTIMISTIC_BIAS'|'PESSIMISTIC_BIAS'|'UNDERCOVERAGE'|'CONFLICT';
export type DriftState='CURRENT'|'DRIFTED'|'CONFLICT'|'INDETERMINATE';
export type RevisionReplayGuardState='CLEAR'|'CONFLICT'|'TRUNCATED';

export interface DigestPort{readonly algorithm:'sha256';digest(input:string):string;}
export interface CancellationPort{isCancelled():boolean;}
export interface OperationOptions{readonly digest:DigestPort;readonly cancellation?:CancellationPort|undefined;readonly maxUnits?:number|undefined;}
export interface Diagnostic{readonly code:string;readonly message:string;readonly subject?:string|undefined;}
export type Result<T>={readonly ok:true;readonly value:T}|{readonly ok:false;readonly diagnostics:readonly Diagnostic[]};
export interface ExactRational{readonly numerator:string;readonly denominator:string;readonly rationalDigest:string;}

export interface M21EstimationBaselineHandoff{readonly owner:'M21_PROGRESS';readonly consumer:'M22_ESTIMATION';readonly snapshotDigests:readonly string[];readonly semanticDigests:readonly string[];readonly handoffDigest:string;}
export interface ProgressHistoryEntry{readonly snapshotDigest:string;readonly semanticDigest:string;readonly projectId:string;readonly lineageDigest:string;readonly epochId:string;readonly manifestDigest:string;readonly sequence:number;readonly numerator:number;readonly denominator:number;readonly completeness:'COMPLETE'|'PARTIAL_OBSERVATION'|'STALE'|'CONFLICT'|'INDETERMINATE';}
export interface EstimationIntentInput{readonly projectId:string;readonly lineageDigest:string;readonly horizon:'PROJECT_COMPLETION';readonly baselineHandoffDigest:string;readonly asOfEpochMs:number;readonly requestedOutput:'FORECAST_INTERVAL'|'SCENARIOS'|'HANDOFFS';}
export interface EstimationIntentCapsule extends EstimationIntentInput{readonly intentDigest:string;}
export interface EstimationAuthorityBoundary{readonly authority:'ESTIMATION_ONLY';readonly mayCalculateProgress:false;readonly mayComputeProjectStatus:false;readonly mayDecideEvidence:false;readonly mayCollectTelemetry:false;readonly productionWeightIsTime:false;readonly boundaryDigest:string;}
export interface DenominatorEpochCompatibilityWitnessInput{readonly witnessId:string;readonly owner:'M21_PROGRESS';readonly projectId:string;readonly lineageDigest:string;readonly fromEpochId:string;readonly toEpochId:string;readonly fromManifestDigest:string;readonly toManifestDigest:string;readonly translationDigest:string;readonly sourceIdentityDigest:string;}
export interface DenominatorEpochCompatibilityWitness extends DenominatorEpochCompatibilityWitnessInput{readonly witnessDigest:string;}
export interface ProgressBaselineAdmission{readonly projectId:string;readonly lineageDigest:string;readonly epochId:string;readonly manifestDigest:string;readonly handoffDigest:string;readonly epochCompatibilityWitnessDigests:readonly string[];readonly entries:readonly ProgressHistoryEntry[];readonly currentSnapshotDigest:string;readonly currentSemanticDigest:string;readonly currentNumerator:number;readonly currentDenominator:number;readonly currentCompleteness:ProgressHistoryEntry['completeness'];readonly admissionDigest:string;}

export interface TemporalObservationInput{readonly observationId:string;readonly owner:TemporalObservationOwner;readonly projectId:string;readonly lineageDigest:string;readonly epochId:string;readonly beforeSnapshotDigest:string;readonly afterSnapshotDigest:string;readonly elapsedMs:number;readonly observedAtEpochMs:number;readonly sourceIdentityDigest:string;}
export interface TemporalObservation extends TemporalObservationInput{readonly observationDigest:string;}
export interface TemporalObservationAuthorityIndex{readonly projectId:string;readonly lineageDigest:string;readonly observations:readonly TemporalObservation[];readonly duplicateObservationIds:readonly string[];readonly indexDigest:string;}
export interface EstimationPolicyInput{readonly maxWindowSamples:number;readonly staleAfterMs:number;readonly requireRiskInputs:boolean;readonly calibrationWindow:number;readonly policyVersion:string;}
export interface EstimationPolicy extends EstimationPolicyInput{readonly minIndependentSamples:3;readonly policyDigest:string;}
export interface BaselineSufficiencyGate{readonly state:AvailabilityState;readonly independentSampleCount:number;readonly reasonCodes:readonly string[];readonly gateDigest:string;}
export interface EstimationBindingManifest{readonly projectId:string;readonly lineageDigest:string;readonly baselineAdmissionDigest:string;readonly observationIndexDigest:string;readonly denominatorEpochId:string;readonly policyDigest:string;readonly riskInputDigest:string|null;readonly calibrationEpochId:string;readonly manifestDigest:string;}

export interface TemporalProgressSample{readonly observationDigest:string;readonly observationId:string;readonly elapsedMs:number;readonly workDelta:ExactRational;readonly throughput:ExactRational;readonly observedAtEpochMs:number;readonly sampleDigest:string;}
export interface SampleExclusion{readonly observationId:string;readonly observationDigest:string;readonly reason:'DUPLICATE'|'REPLAY'|'PROGRESS_REGRESSION'|'ZERO_PROGRESS'|'EPOCH_MISMATCH'|'STALE'|'INVALID_BINDING';readonly exclusionDigest:string;}
export interface ProgressRegressionEvent{readonly observationId:string;readonly beforeSnapshotDigest:string;readonly afterSnapshotDigest:string;readonly regressionDelta:ExactRational;readonly eventDigest:string;}
export interface SampleNormalizationWitness{readonly acceptedSamples:readonly TemporalProgressSample[];readonly exclusions:readonly SampleExclusion[];readonly regressions:readonly ProgressRegressionEvent[];readonly witnessDigest:string;}
export interface ThroughputWindow{readonly samples:readonly TemporalProgressSample[];readonly excludedSampleDigests:readonly string[];readonly maxWindowSamples:number;readonly windowDigest:string;}
export interface RobustThroughputEstimator{readonly q1:ExactRational;readonly q2:ExactRational;readonly q3:ExactRational;readonly sampleCount:number;readonly modelDigest:string;}
export interface RemainingWorkVector{readonly snapshotDigest:string;readonly epochId:string;readonly remaining:ExactRational;readonly complete:boolean;readonly vectorDigest:string;}
export interface DurationProjection{readonly availability:AvailabilityState;readonly lowerMs:number|null;readonly baseMs:number|null;readonly upperMs:number|null;readonly modelDigest:string|null;readonly projectionDigest:string;}

export interface UnknownWorkReserveInput{readonly owner:RiskInputOwner;readonly reserveId:string;readonly projectId:string;readonly lineageDigest:string;readonly numerator:number;readonly denominator:number;readonly rationaleCode:string;readonly sourceIdentityDigest:string;}
export interface UnknownWorkReserve extends UnknownWorkReserveInput{readonly reserve:ExactRational;readonly reserveDigest:string;}
export interface RiskModifierInput{readonly modifierId:string;readonly owner:RiskInputOwner;readonly projectId:string;readonly lineageDigest:string;readonly baseAddedMs:number;readonly conservativeAddedMs:number;readonly sourceIdentityDigest:string;}
export interface RiskAdjustmentVector{readonly modifiers:readonly RiskModifierInput[];readonly missingRequired:boolean;readonly vectorDigest:string;}
export interface ForecastIntervalEnvelope{readonly availability:AvailabilityState;readonly asOfEpochMs:number;readonly lowerDurationMs:number|null;readonly baseDurationMs:number|null;readonly upperDurationMs:number|null;readonly lowerCompletionEpochMs:number|null;readonly baseCompletionEpochMs:number|null;readonly upperCompletionEpochMs:number|null;readonly envelopeDigest:string;}
export interface ScenarioProjection{readonly label:'OPTIMISTIC'|'BASE'|'CONSERVATIVE';readonly durationMs:number;readonly completionEpochMs:number;readonly scenarioDigest:string;}
export interface ScenarioTriad{readonly availability:AvailabilityState;readonly scenarios:readonly ScenarioProjection[];readonly triadDigest:string;}
export interface FalsePrecisionDecision{readonly scalarEtaAllowed:boolean;readonly reasonCodes:readonly string[];readonly decisionDigest:string;}
export interface DeadlineComparison{readonly deadlineEpochMs:number;readonly lowerDeltaMs:number;readonly baseDeltaMs:number;readonly upperDeltaMs:number;readonly forecastEnvelopeDigest:string;readonly comparisonDigest:string;}

export interface ActualOutcomeInput{readonly actualId:string;readonly owner:TemporalObservationOwner;readonly forecastEnvelopeDigest:string;readonly elapsedMs:number;readonly observedAtEpochMs:number;readonly sourceIdentityDigest:string;}
export interface ForecastVsActualVarianceReceipt{readonly actualId:string;readonly actualOwner:TemporalObservationOwner;readonly forecastEnvelopeDigest:string;readonly elapsedMs:number;readonly observedAtEpochMs:number;readonly sourceIdentityDigest:string;readonly outcome:'BELOW_INTERVAL'|'WITHIN_INTERVAL'|'ABOVE_INTERVAL';readonly signedBaseVarianceMs:number;readonly receiptDigest:string;}
export interface CalibrationBiasSentinel{readonly state:CalibrationBiasState;readonly resolvedCount:number;readonly containedCount:number;readonly reasonCodes:readonly string[];readonly sentinelDigest:string;}
export interface ModelDriftSentinel{readonly state:DriftState;readonly reasonCodes:readonly string[];readonly sentinelDigest:string;}
export interface RecalibrationEpoch{readonly epochId:string;readonly predecessorEpochId:string;readonly triggerDigests:readonly string[];readonly sampleWindowDigest:string;readonly policyDigest:string;readonly epochDigest:string;}
export interface ForecastRevisionBindingInput{readonly beforeBindingManifestDigest:string;readonly afterBindingManifestDigest:string;readonly beforeModelDigest:string|null;readonly afterModelDigest:string|null;readonly beforeCalibrationEpochId:string;readonly afterCalibrationEpochId:string;}
export interface ForecastRevisionBindingImpact{readonly bindingManifestChanged:boolean;readonly modelChanged:boolean;readonly calibrationEpochChanged:boolean;}
export interface ForecastIntervalImpact{readonly availabilityChanged:boolean;readonly lowerDurationDeltaMs:number|null;readonly baseDurationDeltaMs:number|null;readonly upperDurationDeltaMs:number|null;readonly lowerCompletionDeltaMs:number|null;readonly baseCompletionDeltaMs:number|null;readonly upperCompletionDeltaMs:number|null;}
export interface ForecastRevisionReceipt extends ForecastRevisionBindingInput{readonly revisionId:string;readonly beforeEnvelopeDigest:string;readonly afterEnvelopeDigest:string;readonly bindingImpact:ForecastRevisionBindingImpact;readonly intervalImpact:ForecastIntervalImpact;readonly reasonCodes:readonly string[];readonly revisionDigest:string;}
export interface RevisionReplayGuard{readonly state:RevisionReplayGuardState;readonly acceptedRevisionDigests:readonly string[];readonly duplicateRevisionDigests:readonly string[];readonly conflictRevisionIds:readonly string[];readonly acceptedRecalibrationEpochDigests:readonly string[];readonly duplicateRecalibrationEpochDigests:readonly string[];readonly conflictRecalibrationEpochIds:readonly string[];readonly splitBrainBeforeEnvelopeDigests:readonly string[];readonly branchMixAfterEnvelopeDigests:readonly string[];readonly splitBrainPredecessorEpochIds:readonly string[];readonly epochMixRevisionIds:readonly string[];readonly historyTruncated:boolean;readonly processedRevisionCount:number;readonly totalRevisionCount:number;readonly processedRecalibrationCount:number;readonly totalRecalibrationCount:number;readonly guardDigest:string;}

export interface EstimationConfidenceCompletenessState{readonly availability:AvailabilityState;readonly confidence:ConfidenceState;readonly reasonCodes:readonly string[];readonly stateDigest:string;}
export interface EstimationSnapshotCapsule{readonly projectId:string;readonly lineageDigest:string;readonly asOfEpochMs:number;readonly baselineAdmissionDigest:string;readonly bindingManifestDigest:string;readonly observationIndexDigest:string;readonly throughputModelDigest:string|null;readonly forecastEnvelope:ForecastIntervalEnvelope;readonly scenarioTriad:ScenarioTriad;readonly confidenceState:EstimationConfidenceCompletenessState;readonly calibrationEpochId:string;readonly revisionDigest:string|null;readonly semanticDigest:string;readonly snapshotDigest:string;}
export interface EstimationIntegrityReceipt{readonly snapshotDigest:string;readonly semanticDigest:string;readonly recomputedSemanticDigest:string;readonly valid:boolean;readonly receiptDigest:string;}
export interface DelegatedEstimationMetricHandoff{readonly owner:'M22_ESTIMATION';readonly consumer:'M20_RESPONSE';readonly snapshotDigest:string;readonly availability:AvailabilityState;readonly confidence:ConfidenceState;readonly lowerDurationMs:number|null;readonly baseDurationMs:number|null;readonly upperDurationMs:number|null;readonly lowerCompletionEpochMs:number|null;readonly baseCompletionEpochMs:number|null;readonly upperCompletionEpochMs:number|null;readonly handoffDigest:string;}
export interface StatusEstimationHandoff{readonly owner:'M22_ESTIMATION';readonly consumer:'M23_PROJECT_STATUS';readonly snapshotDigest:string;readonly availability:AvailabilityState;readonly confidence:ConfidenceState;readonly forecastEnvelopeDigest:string;readonly deadlineComparison:DeadlineComparison|null;readonly revisionDigest:string|null;readonly handoffDigest:string;}

export interface EstimateProjectInput{readonly intent:EstimationIntentInput;readonly baselineHandoff:M21EstimationBaselineHandoff;readonly progressHistory:readonly ProgressHistoryEntry[];readonly epochCompatibilityWitnesses?:readonly DenominatorEpochCompatibilityWitnessInput[]|undefined;readonly observations:readonly TemporalObservationInput[];readonly policy:EstimationPolicyInput;readonly unknownReserve?:UnknownWorkReserveInput|null|undefined;readonly riskModifiers?:readonly RiskModifierInput[]|undefined;readonly calibrationReceipts?:readonly ForecastVsActualVarianceReceipt[]|undefined;readonly calibrationEpochId?:string|undefined;readonly deadlineEpochMs?:number|undefined;}
export interface EstimateProjectOutput{readonly intent:EstimationIntentCapsule;readonly authority:EstimationAuthorityBoundary;readonly baseline:ProgressBaselineAdmission;readonly observationIndex:TemporalObservationAuthorityIndex;readonly policy:EstimationPolicy;readonly sufficiency:BaselineSufficiencyGate;readonly binding:EstimationBindingManifest;readonly normalization:SampleNormalizationWitness;readonly window:ThroughputWindow;readonly model:RobustThroughputEstimator|null;readonly remaining:RemainingWorkVector;readonly duration:DurationProjection;readonly reserve:UnknownWorkReserve|null;readonly risk:RiskAdjustmentVector;readonly envelope:ForecastIntervalEnvelope;readonly scenarios:ScenarioTriad;readonly falsePrecision:FalsePrecisionDecision;readonly bias:CalibrationBiasSentinel;readonly drift:ModelDriftSentinel;readonly confidence:EstimationConfidenceCompletenessState;readonly snapshot:EstimationSnapshotCapsule;readonly integrityReceipt:EstimationIntegrityReceipt;readonly delegatedHandoff:DelegatedEstimationMetricHandoff;readonly statusHandoff:StatusEstimationHandoff;}