import type{Diagnostic,ExactRational,OperationOptions,Result}from'./types.js';
export function compareCodePoint(a:string,b:string){return a<b?-1:a>b?1:0;}
export function deepFreeze<T>(value:T):T{if(value&&typeof value==='object'){Object.freeze(value);for(const v of Object.values(value as Record<string,unknown>)){if(v&&typeof v==='object'&&!Object.isFrozen(v))deepFreeze(v);}}return value;}
export function fail<T=never>(code:string,message:string,subject?:string):Result<T>{const d:Diagnostic={code,message,...(subject===undefined?{}:{subject})};return{ok:false,diagnostics:[d]};}
export function validId(value:string){return/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value)&&!['__proto__','constructor','prototype'].includes(value);}
export function isSha256(value:string){return/^sha256:[0-9a-f]{64}$/.test(value);}
function canonical(v:unknown):unknown{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object'){const out:Record<string,unknown>={};for(const k of Object.keys(v as Record<string,unknown>).sort(compareCodePoint))out[k]=canonical((v as Record<string,unknown>)[k]);return out;}return v;}
export function stableJson(value:unknown){return JSON.stringify(canonical(value));}
export function sha(options:OperationOptions,value:unknown):Result<string>{try{if(options.digest.algorithm!=='sha256')return fail('DIGEST_ALGORITHM_INVALID','Estimation Engine requires SHA-256');const raw=options.digest.digest(stableJson(value));if(!/^[0-9a-f]{64}$/i.test(raw))return fail('DIGEST_INVALID','Injected digest capability did not return SHA-256 hex');return{ok:true,value:`sha256:${raw.toLowerCase()}`};}catch{return fail('DIGEST_FAILED','Injected digest capability failed');}}
export function cancelled<T=never>(options:OperationOptions):Result<T>|null{return options.cancellation?.isCancelled()?fail('ESTIMATION_CANCELLED','Estimation Engine operation was cancelled'):null;}
export function safeInt(value:number){return Number.isSafeInteger(value);}
export function nonNegative(value:number){return safeInt(value)&&value>=0;}
export function positive(value:number){return safeInt(value)&&value>0;}
export function sortedUnique(values:readonly string[]){return[...new Set(values)].sort(compareCodePoint);}
export function allSha(values:readonly(string|null|undefined)[]){return values.every(v=>v==null||isSha256(v));}
function gcdBig(a:bigint,b:bigint){let x=a<0n?-a:a,y=b<0n?-b:b;while(y!==0n){const r=x%y;x=y;y=r;}return x;}
export function rational(numerator:number,denominator:number,options:OperationOptions):Result<ExactRational>{if(!nonNegative(numerator)||!positive(denominator))return fail('RATIONAL_INVALID','Rational values require non-negative safe numerator and positive safe denominator');const g=gcdBig(BigInt(numerator),BigInt(denominator));const n=Number(BigInt(numerator)/g),d=Number(BigInt(denominator)/g);if(!Number.isSafeInteger(n)||!Number.isSafeInteger(d))return fail('RATIONAL_OVERFLOW','Reduced rational exceeds safe integer range');const h=sha(options,{numerator:n,denominator:d});if(!h.ok)return h;return{ok:true,value:deepFreeze({numerator:n,denominator:d,rationalDigest:h.value})};}
export function verifyRational(value:ExactRational,options:OperationOptions):Result<boolean>{const r=rational(value.numerator,value.denominator,options);return r.ok?{ok:true,value:r.value.rationalDigest===value.rationalDigest}:r;}
export function compareRational(a:ExactRational,b:ExactRational){const left=BigInt(a.numerator)*BigInt(b.denominator),right=BigInt(b.numerator)*BigInt(a.denominator);return left<right?-1:left>right?1:0;}
export function subtractRational(aNum:number,aDen:number,bNum:number,bDen:number,options:OperationOptions):Result<ExactRational>{if(!nonNegative(aNum)||!positive(aDen)||!nonNegative(bNum)||!positive(bDen))return fail('RATIONAL_INPUT_INVALID','Progress fraction inputs are invalid');const n=BigInt(aNum)*BigInt(bDen)-BigInt(bNum)*BigInt(aDen),d=BigInt(aDen)*BigInt(bDen);if(n<0n)return fail('RATIONAL_NEGATIVE','Rational subtraction would be negative');const g=gcdBig(n,d),rn=n/g,rd=d/g;if(rn>BigInt(Number.MAX_SAFE_INTEGER)||rd>BigInt(Number.MAX_SAFE_INTEGER))return fail('RATIONAL_OVERFLOW','Rational subtraction exceeds safe integer range');return rational(Number(rn),Number(rd),options);}
export function divideByInteger(value:ExactRational,divisor:number,options:OperationOptions):Result<ExactRational>{if(!positive(divisor))return fail('DIVISOR_INVALID','Divisor must be a positive safe integer');const d=BigInt(value.denominator)*BigInt(divisor);if(d>BigInt(Number.MAX_SAFE_INTEGER))return fail('RATIONAL_OVERFLOW','Throughput denominator exceeds safe integer range');return rational(value.numerator,Number(d),options);}
export function oneMinus(numerator:number,denominator:number,options:OperationOptions):Result<ExactRational>{if(!nonNegative(numerator)||!positive(denominator)||numerator>denominator)return fail('PROGRESS_FRACTION_INVALID','Progress fraction is invalid');return rational(denominator-numerator,denominator,options);}
export function ceilDuration(work:ExactRational,throughput:ExactRational):Result<number>{if(throughput.numerator<=0)return fail('THROUGHPUT_ZERO','Throughput must be positive for duration projection');const n=BigInt(work.numerator)*BigInt(throughput.denominator),d=BigInt(work.denominator)*BigInt(throughput.numerator);if(d<=0n)return fail('DURATION_DENOMINATOR_INVALID','Duration denominator is invalid');const q=(n+d-1n)/d;if(q>BigInt(Number.MAX_SAFE_INTEGER))return fail('DURATION_OVERFLOW','Projected duration exceeds safe integer range');return{ok:true,value:Number(q)};}
export function ceilScale(value:number,basisPoints:number):Result<number>{if(!nonNegative(value)||!nonNegative(basisPoints))return fail('SCALE_INVALID','Scale inputs must be non-negative safe integers');const n=BigInt(value)*BigInt(10000+basisPoints),q=(n+9999n)/10000n;if(q>BigInt(Number.MAX_SAFE_INTEGER))return fail('SCALE_OVERFLOW','Scaled duration exceeds safe integer range');return{ok:true,value:Number(q)};}
export function addSafe(values:readonly number[]):Result<number>{let total=0;for(const v of values){if(!nonNegative(v))return fail('INTEGER_INVALID','Expected non-negative safe integer');total+=v;if(!Number.isSafeInteger(total))return fail('INTEGER_OVERFLOW','Integer sum overflow');}return{ok:true,value:total};}
export function limits(options:OperationOptions){return{samples:Math.max(1,Math.min(options.maxSamples??4096,65536)),history:Math.max(1,Math.min(options.maxHistory??4096,65536)),refs:Math.max(1,Math.min(options.maxRefs??16384,131072))};}
