import type{EstimateProjectInput,EstimateProjectOutput,OperationOptions,Result,RobustThroughputEstimator}from'./types.js';
import{digestValue,fail,ok}from'./utils.js';
import{admitProgressBaseline,createEstimationAuthorityBoundary,createEstimationBindingManifest,createEstimationIntentCapsule,createEstimationPolicy,createTemporalObservationAuthorityIndex,evaluateBaselineSufficiency}from'./s01-authority.js';
import{createRemainingWorkVector,createRobustThroughputEstimator,createThroughputWindow,normalizeTemporalSamples,projectDuration}from'./s02-model.js';
import{applyFalsePrecisionBlocker,compareDeadline,createForecastIntervalEnvelope,createRiskAdjustmentVector,createScenarioTriad,createUnknownWorkReserve}from'./s03-forecast.js';
import{detectCalibrationBias,detectModelDrift}from'./s04-calibration.js';
import{createDelegatedEstimationMetricHandoff,createEstimationIntegrityReceipt,createEstimationSnapshotCapsule,createStatusEstimationHandoff,deriveEstimationConfidence}from'./s05-snapshot.js';

export function estimateProject(input:EstimateProjectInput,options:OperationOptions):Result<EstimateProjectOutput>{
 const intent=createEstimationIntentCapsule(input.intent,options);if(!intent.ok)return intent;const authority=createEstimationAuthorityBoundary(intent.value,options);if(!authority.ok)return authority;const baseline=admitProgressBaseline(input.baselineHandoff,input.progressHistory,intent.value,options,input.epochCompatibilityWitnesses??[]);if(!baseline.ok)return baseline;const policy=createEstimationPolicy(input.policy,options);if(!policy.ok)return policy;const observationIndex=createTemporalObservationAuthorityIndex(input.observations,baseline.value,options);if(!observationIndex.ok)return observationIndex;
 const normalization=normalizeTemporalSamples(baseline.value,observationIndex.value,policy.value,input.intent.asOfEpochMs,options);if(!normalization.ok)return normalization;const sufficiency=evaluateBaselineSufficiency(baseline.value,observationIndex.value,policy.value,input.intent.asOfEpochMs,options);if(!sufficiency.ok)return sufficiency;
 const window=createThroughputWindow(normalization.value,policy.value,options);if(!window.ok)return window;let model:RobustThroughputEstimator|null=null;if(window.value.samples.length>=3){const built=createRobustThroughputEstimator(window.value,options);if(!built.ok)return built;model=built.value;}
 const remaining=createRemainingWorkVector(baseline.value,options);if(!remaining.ok)return remaining;const duration=projectDuration(remaining.value,model,sufficiency.value,options);if(!duration.ok)return duration;
 let reserve=null;if(input.unknownReserve!==undefined&&input.unknownReserve!==null){const built=createUnknownWorkReserve(input.unknownReserve,baseline.value.projectId,baseline.value.lineageDigest,options);if(!built.ok)return built;reserve=built.value;}
 const risk=createRiskAdjustmentVector(input.riskModifiers??[],baseline.value.projectId,baseline.value.lineageDigest,policy.value,options);if(!risk.ok)return risk;const riskBinding=digestValue(options.digest,'M22_RISK_BINDING',{reserveDigest:reserve?.reserveDigest??null,riskVectorDigest:risk.value.vectorDigest});if(!riskBinding.ok)return riskBinding;const calibrationEpochId=input.calibrationEpochId??'RCE22-INITIAL';const binding=createEstimationBindingManifest(baseline.value,observationIndex.value,policy.value,riskBinding.value,calibrationEpochId,options);if(!binding.ok)return binding;
 const envelope=createForecastIntervalEnvelope(duration.value,reserve,model,risk.value,input.intent.asOfEpochMs,options);if(!envelope.ok)return envelope;const scenarios=createScenarioTriad(envelope.value,options);if(!scenarios.ok)return scenarios;const falsePrecision=applyFalsePrecisionBlocker(sufficiency.value,model,options);if(!falsePrecision.ok)return falsePrecision;const receipts=input.calibrationReceipts??[];const bias=detectCalibrationBias(receipts,policy.value,options);if(!bias.ok)return bias;const drift=detectModelDrift(model,null,bias.value,false,false,options);if(!drift.ok)return drift;const confidenceResult=deriveEstimationConfidence(sufficiency.value,model,receipts,bias.value,drift.value,options);if(!confidenceResult.ok)return confidenceResult;let confidenceValue=confidenceResult.value;
 if(envelope.value.availability!==confidenceValue.availability){
  if(envelope.value.availability==='INDETERMINATE'&&confidenceValue.availability==='AVAILABLE'){
   const c=deriveEstimationConfidence({...sufficiency.value,state:'INDETERMINATE'},model,receipts,bias.value,drift.value,options);if(!c.ok)return c;confidenceValue=c.value;
  }else return fail('WORKFLOW_AVAILABILITY_MISMATCH','Forecast/confidence availability mismatch.');
 }
 const snapshot=createEstimationSnapshotCapsule(baseline.value.projectId,baseline.value.lineageDigest,input.intent.asOfEpochMs,baseline.value.admissionDigest,binding.value,observationIndex.value.indexDigest,model,envelope.value,scenarios.value,confidenceValue,calibrationEpochId,null,options);if(!snapshot.ok)return snapshot;const integrityReceipt=createEstimationIntegrityReceipt(snapshot.value,options);if(!integrityReceipt.ok)return integrityReceipt;if(!integrityReceipt.value.valid)return fail('EIR22_RECOMPUTATION_FAILED','Independent snapshot semantic recomputation failed.');const delegatedHandoff=createDelegatedEstimationMetricHandoff(snapshot.value,options);if(!delegatedHandoff.ok)return delegatedHandoff;
 let deadline=null;if(input.deadlineEpochMs!==undefined&&envelope.value.availability==='AVAILABLE'){const compared=compareDeadline(envelope.value,input.deadlineEpochMs,options);if(!compared.ok)return compared;deadline=compared.value;}const statusHandoff=createStatusEstimationHandoff(snapshot.value,deadline,options);if(!statusHandoff.ok)return statusHandoff;
 return ok({intent:intent.value,authority:authority.value,baseline:baseline.value,observationIndex:observationIndex.value,policy:policy.value,sufficiency:sufficiency.value,binding:binding.value,normalization:normalization.value,window:window.value,model,remaining:remaining.value,duration:duration.value,reserve,risk:risk.value,envelope:envelope.value,scenarios:scenarios.value,falsePrecision:falsePrecision.value,bias:bias.value,drift:drift.value,confidence:confidenceValue,snapshot:snapshot.value,integrityReceipt:integrityReceipt.value,delegatedHandoff:delegatedHandoff.value,statusHandoff:statusHandoff.value});
}
