import type{BlockerAttributionVector,OperationOptions,Result,StatusCondition,StatusConditionIndex,StatusConditionInput}from'./types.js';
import{compareCodePoint,deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,validId}from'./utils.js';

export function createStatusCondition(input:StatusConditionInput,options:OperationOptions):Result<StatusCondition>{
 if(!validId(input.conditionId)||!validId(input.projectId)||!validId(input.lineageId)||!input.reasonCode.trim())return fail('SCI23_ID_INVALID','Status condition requires stable condition/project/lineage ids and reason code.');
 if(input.owner==='M27_ASSURANCE')return fail('SCI23_OWNER_NOT_AVAILABLE','M27_ASSURANCE is reserved until M27 exists.');
 if(input.owner!=='EXTERNAL_CANONICAL')return fail('SCI23_OWNER_INVALID','Status condition owner is not allowed.');
 if(!['WARNING','BLOCKING','RECOVERY','CONFLICT'].includes(input.class)||!['ACTIVE','RESOLVED'].includes(input.state))return fail('SCI23_CLASS_STATE_INVALID','Status condition class/state is invalid.');
 if(!isSha256(input.checkpointDigest)||!isSha256(input.sourceIdentityDigest)||!isSha256(input.validityBindingDigest)||input.supersedesConditionDigest!==null&&!isSha256(input.supersedesConditionDigest))return fail('SCI23_BINDING_INVALID','Status condition bindings must be SHA-256 digests.');
 if(input.state==='RESOLVED'&&input.supersedesConditionDigest===null)return fail('RDG23_SUPERSESSION_REQUIRED','Resolved condition requires exact superseded active-condition digest.');
 const body={conditionId:input.conditionId,owner:input.owner,projectId:input.projectId,lineageId:input.lineageId,checkpointDigest:input.checkpointDigest,class:input.class,state:input.state,reasonCode:input.reasonCode,sourceIdentityDigest:input.sourceIdentityDigest,validityBindingDigest:input.validityBindingDigest,supersedesConditionDigest:input.supersedesConditionDigest};const d=digestValue(options,'SCI23',body);if(!d.ok)return d;return ok(deepFreeze({...body,conditionDigest:d.value}));
}
export function verifyStatusCondition(value:StatusCondition,options:OperationOptions):Result<boolean>{const rebuilt=createStatusCondition(value,options);return rebuilt.ok?ok(rebuilt.value.conditionDigest===value.conditionDigest):rebuilt;}

export function verifyStatusConditionIndex(value:StatusConditionIndex,options:OperationOptions):Result<boolean>{
 if(!validId(value.projectId)||!validId(value.lineageId)||!isSha256(value.checkpointDigest))return ok(false);
 for(const c of value.effectiveConditions){const v=verifyStatusCondition(c,options);if(!v.ok)return v;if(!v.value||c.projectId!==value.projectId||c.lineageId!==value.lineageId)return ok(false);}if(value.resolutions.some(r=>!validId(r.conditionId)||!isSha256(r.priorConditionDigest)||!isSha256(r.resolutionConditionDigest)))return ok(false);
 const body={projectId:value.projectId,lineageId:value.lineageId,checkpointDigest:value.checkpointDigest,effectiveConditions:[...value.effectiveConditions].sort((a,b)=>compareCodePoint(`${a.conditionId}:${a.conditionDigest}`,`${b.conditionId}:${b.conditionDigest}`)),carriedForwardConditionIds:sortedUnique(value.carriedForwardConditionIds),resolvedConditionIds:sortedUnique(value.resolvedConditionIds),resolutions:[...value.resolutions].sort((a,b)=>compareCodePoint(a.conditionId,b.conditionId)),conflictConditionIds:sortedUnique(value.conflictConditionIds)};const d=digestValue(options,'SCI23_INDEX',body);return d.ok?ok(d.value===value.indexDigest):d;
}

export function createStatusConditionIndex(projectId:string,lineageId:string,checkpointDigest:string,currentConditions:readonly StatusCondition[],previous:StatusConditionIndex|null,options:OperationOptions):Result<StatusConditionIndex>{
 if(!validId(projectId)||!validId(lineageId)||!isSha256(checkpointDigest))return fail('SCI23_INDEX_BINDING_INVALID','Condition index requires project/lineage ids and checkpoint digest.');
 if(previous!==null){const pv=verifyStatusConditionIndex(previous,options);if(!pv.ok||!pv.value)return pv.ok?fail('SCI23_PREVIOUS_INDEX_TAMPERED','Previous condition index failed verification.'):pv;if(previous.projectId!==projectId||previous.lineageId!==lineageId)return fail('SCI23_PREVIOUS_LINEAGE_MISMATCH','Previous condition index belongs to another project/lineage.');}
 const byId=new Map<string,StatusCondition[]>();
 for(const c of currentConditions){const v=verifyStatusCondition(c,options);if(!v.ok||!v.value)return v.ok?fail('SCI23_CONDITION_TAMPERED','Current condition failed verification.',c.conditionId):v;if(c.projectId!==projectId||c.lineageId!==lineageId||c.checkpointDigest!==checkpointDigest)return fail('SCI23_CONDITION_BINDING_MISMATCH','Current condition does not bind the current project/lineage/checkpoint.',c.conditionId);const list=byId.get(c.conditionId)??[];list.push(c);byId.set(c.conditionId,list);}
 const conflicts=new Set<string>();const current=new Map<string,StatusCondition>();
 for(const [id,list] of byId){const unique=new Map(list.map(c=>[c.conditionDigest,c] as const));if(unique.size>1){conflicts.add(id);continue;}current.set(id,[...unique.values()][0]!);}
 const effective=new Map<string,StatusCondition>();const carried:string[]=[];const resolved:string[]=[];const resolutions:{conditionId:string;priorConditionDigest:string;resolutionConditionDigest:string}[]=[];
 const priorActive=new Map<string,StatusCondition>((previous?.effectiveConditions??[]).filter(c=>c.state==='ACTIVE').map(c=>[c.conditionId,c] as const));
 for(const [id,prior] of priorActive){const now=current.get(id);if(now===undefined){effective.set(id,prior);carried.push(id);continue;}if(now.state==='RESOLVED'){if(now.supersedesConditionDigest===prior.conditionDigest){resolved.push(id);resolutions.push({conditionId:id,priorConditionDigest:prior.conditionDigest,resolutionConditionDigest:now.conditionDigest});current.delete(id);}else conflicts.add(id);continue;}if(now.supersedesConditionDigest!==prior.conditionDigest){conflicts.add(id);continue;}effective.set(id,now);current.delete(id);}
 for(const [id,now] of current){if(now.state==='RESOLVED'){conflicts.add(id);continue;}if(now.supersedesConditionDigest!==null){conflicts.add(id);continue;}effective.set(id,now);}
 const body={projectId,lineageId,checkpointDigest,effectiveConditions:[...effective.values()].sort((a,b)=>compareCodePoint(`${a.conditionId}:${a.conditionDigest}`,`${b.conditionId}:${b.conditionDigest}`)),carriedForwardConditionIds:sortedUnique(carried),resolvedConditionIds:sortedUnique(resolved),resolutions:resolutions.sort((a,b)=>compareCodePoint(a.conditionId,b.conditionId)),conflictConditionIds:sortedUnique([...conflicts])};const d=digestValue(options,'SCI23_INDEX',body);if(!d.ok)return d;return ok(deepFreeze({...body,indexDigest:d.value}));
}

export function createBlockerAttributionVector(index:StatusConditionIndex,options:OperationOptions):Result<BlockerAttributionVector>{const v=verifyStatusConditionIndex(index,options);if(!v.ok||!v.value)return v.ok?fail('BAV23_INDEX_TAMPERED','Blocker attribution requires verified condition index.'):v;const active=index.effectiveConditions.filter(c=>c.state==='ACTIVE');const body={warningConditionIds:sortedUnique(active.filter(c=>c.class==='WARNING').map(c=>c.conditionId)),blockingConditionIds:sortedUnique(active.filter(c=>c.class==='BLOCKING').map(c=>c.conditionId)),recoveryConditionIds:sortedUnique(active.filter(c=>c.class==='RECOVERY').map(c=>c.conditionId)),conflictConditionIds:sortedUnique([...index.conflictConditionIds,...active.filter(c=>c.class==='CONFLICT').map(c=>c.conditionId)])};const d=digestValue(options,'BAV23',body);if(!d.ok)return d;return ok(deepFreeze({...body,vectorDigest:d.value}));}

export function createStatusConflictWitness(index:StatusConditionIndex,options:OperationOptions):Result<{readonly conflict:boolean;readonly conflictConditionIds:readonly string[];readonly witnessDigest:string}>{const v=verifyStatusConditionIndex(index,options);if(!v.ok||!v.value)return v.ok?fail('SCW23_INDEX_TAMPERED','Conflict witness requires verified condition index.'):v;const ids=sortedUnique([...index.conflictConditionIds,...index.effectiveConditions.filter(c=>c.class==='CONFLICT'&&c.state==='ACTIVE').map(c=>c.conditionId)]);const body={conflict:ids.length>0,conflictConditionIds:ids};const d=digestValue(options,'SCW23',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}

export function createResolutionDigestGate(previous:StatusConditionIndex,current:StatusConditionIndex,conditionId:string,options:OperationOptions):Result<{readonly resolved:boolean;readonly priorConditionDigest:string|null;readonly resolutionConditionDigest:string|null;readonly gateDigest:string}>{const pv=verifyStatusConditionIndex(previous,options),cv=verifyStatusConditionIndex(current,options);if(!pv.ok||!pv.value)return pv.ok?fail('RDG23_PREVIOUS_TAMPERED','Resolution gate requires verified previous index.'):pv;if(!cv.ok||!cv.value)return cv.ok?fail('RDG23_CURRENT_TAMPERED','Resolution gate requires verified current index.'):cv;const prior=previous.effectiveConditions.find(c=>c.conditionId===conditionId&&c.state==='ACTIVE')??null;const resolution=current.resolutions.find(r=>r.conditionId===conditionId)??null;const resolved=prior!==null&&resolution!==null&&resolution.priorConditionDigest===prior.conditionDigest;const body={resolved,priorConditionDigest:prior?.conditionDigest??null,resolutionConditionDigest:resolved?resolution!.resolutionConditionDigest:null};const d=digestValue(options,'RDG23',body);if(!d.ok)return d;return ok(deepFreeze({...body,gateDigest:d.value}));}

export function createBlockerRetentionTracker(index:StatusConditionIndex,options:OperationOptions):Result<{readonly retainedConditionIds:readonly string[];readonly trackerDigest:string}>{const v=verifyStatusConditionIndex(index,options);if(!v.ok||!v.value)return v.ok?fail('BRT23_INDEX_TAMPERED','Retention tracker requires verified condition index.'):v;const retained=sortedUnique(index.effectiveConditions.filter(c=>c.state==='ACTIVE'&&(c.class==='BLOCKING'||c.class==='RECOVERY'||c.class==='CONFLICT')).map(c=>c.conditionId));const body={retainedConditionIds:retained};const d=digestValue(options,'BRT23',body);if(!d.ok)return d;return ok(deepFreeze({...body,trackerDigest:d.value}));}
