import type{
 DelegatedProjectStatusHandoff,OperationOptions,ProjectStatusDecision,ProjectStatusInput,ProjectStatusIntegrityReceipt,ProjectStatusSemanticDigest,ProjectStatusSnapshot,Result,StatusChangedDimension,StatusChangedSource,StatusFreshnessGate,StatusFreshnessObservation,StatusHistoryGuard,StatusReopenWitness,StatusReopenWitnessInput,StatusTransitionRecord,
}from'./types.js';
import{deriveProjectStatusDecision}from'./s04-readiness.js';
import{deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,stableJson,validId,Guard}from'./utils.js';

function reasonTrace(decision:ProjectStatusDecision){return sortedUnique([
 ...decision.lifecycle.reasonCodes.map(x=>`LIFECYCLE:${x}`),
 ...decision.schedule.reasonCodes.map(x=>`SCHEDULE:${x}`),
 ...decision.readiness.reasonCodes.map(x=>`READINESS:${x}`),
 ...decision.conditionIndex.effectiveConditions.map(c=>`CONDITION:${c.conditionId}:${c.class}:${c.state}:${c.reasonCode}`),
 ...decision.conditionIndex.conflictConditionIds.map(id=>`CONDITION_CONFLICT:${id}`),
]);}
function sourceBinding(input:ProjectStatusInput,decision:ProjectStatusDecision){return{
 checkpointDigest:input.continuationSource?.checkpoint.checkpointDigest??null,
 checkpointReadinessCertificateDigest:input.continuationSource?.readiness.certificateDigest??null,
 continuationHandoffDigest:input.continuationSource?.handoff.handoffDigest??null,
 resumeHandbackDigest:input.resumeSource?.handback.handbackDigest??null,
 progressHandoffDigest:input.progressSource?.handoff.handoffDigest??null,
 estimationHandoffDigest:input.estimationSource?.handoff.handoffDigest??null,
 completionOutcomeDigest:input.completionOutcome?.outcomeDigest??null,
 conditionIndexDigest:decision.conditionIndex.indexDigest,
};}
function buildCore(input:ProjectStatusInput,decision:ProjectStatusDecision,predecessor:ProjectStatusSnapshot|null,validityBindingDigest:string){return{
 projectId:input.intent.projectId,lineageId:input.intent.lineageId,intentDigest:input.intent.intentDigest,decisionDigest:decision.decisionDigest,
 checkpointDigest:input.continuationSource?.checkpoint.checkpointDigest??null,checkpointReadinessCertificateDigest:input.continuationSource?.readiness.certificateDigest??null,continuationHandoffDigest:input.continuationSource?.handoff.handoffDigest??null,
 resumeReceiptDigest:input.resumeSource?.receipt.receiptDigest??null,resumeHandbackDigest:input.resumeSource?.handback.handbackDigest??null,
 progressSnapshotDigest:input.progressSource?.snapshot.snapshotDigest??null,progressHandoffDigest:input.progressSource?.handoff.handoffDigest??null,
 estimationSnapshotDigest:input.estimationSource?.snapshot.snapshotDigest??null,estimationHandoffDigest:input.estimationSource?.handoff.handoffDigest??null,
 completionOutcomeDigest:input.completionOutcome?.outcomeDigest??null,completionOutcomeState:input.completionOutcome?.state??'ABSENT' as const,conditionIndexDigest:decision.conditionIndex.indexDigest,
 lifecycleStatus:decision.lifecycle.status,scheduleHealth:decision.schedule.status,continuationReadiness:decision.readiness.status,nextLegalAction:decision.readiness.nextLegalAction,
 blockingConditionIds:decision.blockers.blockingConditionIds,recoveryConditionIds:decision.blockers.recoveryConditionIds,conflictConditionIds:decision.blockers.conflictConditionIds,reasonCodeTrace:reasonTrace(decision),
 predecessorSnapshotDigest:predecessor?.snapshotDigest??null,predecessorSemanticDigest:predecessor?.semanticDigest??null,validityBindingDigest,
};}
function snapshotComparable(snapshot:ProjectStatusSnapshot){return{
 projectId:snapshot.projectId,lineageId:snapshot.lineageId,intentDigest:snapshot.intentDigest,decisionDigest:snapshot.decisionDigest,
 checkpointDigest:snapshot.checkpointDigest,checkpointReadinessCertificateDigest:snapshot.checkpointReadinessCertificateDigest,continuationHandoffDigest:snapshot.continuationHandoffDigest,
 resumeReceiptDigest:snapshot.resumeReceiptDigest,resumeHandbackDigest:snapshot.resumeHandbackDigest,progressSnapshotDigest:snapshot.progressSnapshotDigest,progressHandoffDigest:snapshot.progressHandoffDigest,
 estimationSnapshotDigest:snapshot.estimationSnapshotDigest,estimationHandoffDigest:snapshot.estimationHandoffDigest,completionOutcomeDigest:snapshot.completionOutcomeDigest,completionOutcomeState:snapshot.completionOutcomeState,conditionIndexDigest:snapshot.conditionIndexDigest,
 lifecycleStatus:snapshot.lifecycleStatus,scheduleHealth:snapshot.scheduleHealth,continuationReadiness:snapshot.continuationReadiness,nextLegalAction:snapshot.nextLegalAction,
 blockingConditionIds:snapshot.blockingConditionIds,recoveryConditionIds:snapshot.recoveryConditionIds,conflictConditionIds:snapshot.conflictConditionIds,reasonCodeTrace:snapshot.reasonCodeTrace,
 predecessorSnapshotDigest:snapshot.predecessorSnapshotDigest,predecessorSemanticDigest:snapshot.predecessorSemanticDigest,validityBindingDigest:snapshot.validityBindingDigest,
};}

export function createProjectStatusSnapshot(input:ProjectStatusInput,predecessor:ProjectStatusSnapshot|null,options:OperationOptions):Result<ProjectStatusSnapshot>{
 if(predecessor!==null&&(predecessor.projectId!==input.intent.projectId||predecessor.lineageId!==input.intent.lineageId||!isSha256(predecessor.snapshotDigest)||!isSha256(predecessor.semanticDigest)))return fail('PSS23_PREDECESSOR_INVALID','Status predecessor must be a valid snapshot from the same project/lineage.');
 const decision=deriveProjectStatusDecision(input,options);if(!decision.ok)return decision;
 const validity=digestValue(options,'PSS23_VALIDITY',sourceBinding(input,decision.value));if(!validity.ok)return validity;
 const core=buildCore(input,decision.value,predecessor,validity.value);const semantic=digestValue(options,'PSD23',core);if(!semantic.ok)return semantic;const snapshot=digestValue(options,'PSS23',{...core,semanticDigest:semantic.value});if(!snapshot.ok)return snapshot;return ok(deepFreeze({...core,semanticDigest:semantic.value,snapshotDigest:snapshot.value}));
}

export function createProjectStatusIntegrityReceipt(snapshot:ProjectStatusSnapshot,input:ProjectStatusInput,options:OperationOptions):Result<ProjectStatusIntegrityReceipt>{
 const decision=deriveProjectStatusDecision(input,options);if(!decision.ok)return decision;
 const validity=digestValue(options,'PSS23_VALIDITY',sourceBinding(input,decision.value));if(!validity.ok)return validity;
 const predecessor=snapshot.predecessorSnapshotDigest===null?null:{projectId:snapshot.projectId,lineageId:snapshot.lineageId,snapshotDigest:snapshot.predecessorSnapshotDigest,semanticDigest:snapshot.predecessorSemanticDigest} as ProjectStatusSnapshot|null;
 if(snapshot.predecessorSnapshotDigest!==null&&!isSha256(snapshot.predecessorSemanticDigest))return fail('PSI23_PREDECESSOR_BINDING_INVALID','Historical snapshot must carry predecessor semantic digest.');
 const core=buildCore(input,decision.value,predecessor,validity.value);const semantic=digestValue(options,'PSD23',core);if(!semantic.ok)return semantic;const expected=digestValue(options,'PSS23',{...core,semanticDigest:semantic.value});if(!expected.ok)return expected;
 const valid=semantic.value===snapshot.semanticDigest&&expected.value===snapshot.snapshotDigest&&validity.value===snapshot.validityBindingDigest&&stableJson(core)===stableJson(snapshotComparable(snapshot));
 const body={snapshotDigest:snapshot.snapshotDigest,recomputedDecisionDigest:decision.value.decisionDigest,recomputedSemanticDigest:semantic.value,recomputedValidityBindingDigest:validity.value,valid};const d=digestValue(options,'PSI23',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));
}
export function createProjectStatusSemanticDigest(snapshot:ProjectStatusSnapshot,input:ProjectStatusInput,options:OperationOptions):Result<ProjectStatusSemanticDigest>{const receipt=createProjectStatusIntegrityReceipt(snapshot,input,options);if(!receipt.ok)return receipt;if(!receipt.value.valid)return fail('PSD23_SNAPSHOT_TAMPERED','Semantic digest requires independently verified project-status snapshot.');return ok(deepFreeze({snapshotDigest:snapshot.snapshotDigest,semanticDigest:snapshot.semanticDigest}));}

export function createStatusReopenWitness(input:StatusReopenWitnessInput,options:OperationOptions):Result<StatusReopenWitness>{if(!validId(input.witnessId)||!input.reasonCode.trim()||!isSha256(input.priorCompleteSnapshotDigest)||!isSha256(input.authorizationFactDigest))return fail('SRW23_INPUT_INVALID','Reopen witness requires stable id, reason and SHA-256 prior/authorization facts.');if(input.owner==='M27_ASSURANCE')return fail('SRW23_OWNER_NOT_AVAILABLE','M27_ASSURANCE reopen authority is unavailable before M27 exists.');if(input.owner!=='EXTERNAL_CANONICAL')return fail('SRW23_OWNER_INVALID','Reopen witness owner is not allowed.');const body={witnessId:input.witnessId,owner:input.owner,priorCompleteSnapshotDigest:input.priorCompleteSnapshotDigest,authorizationFactDigest:input.authorizationFactDigest,reasonCode:input.reasonCode};const d=digestValue(options,'SRW23',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}
export function verifyStatusReopenWitness(value:StatusReopenWitness,options:OperationOptions):Result<boolean>{const rebuilt=createStatusReopenWitness(value,options);return rebuilt.ok?ok(rebuilt.value.witnessDigest===value.witnessDigest):rebuilt;}

function changedDimensions(previous:ProjectStatusSnapshot|null,current:ProjectStatusSnapshot):StatusChangedDimension[]{if(previous===null)return['LIFECYCLE','SCHEDULE','READINESS',...(current.nextLegalAction===null?[]:['NEXT_ACTION' as const])];const out:StatusChangedDimension[]=[];if(previous.lifecycleStatus!==current.lifecycleStatus)out.push('LIFECYCLE');if(previous.scheduleHealth!==current.scheduleHealth)out.push('SCHEDULE');if(previous.continuationReadiness!==current.continuationReadiness)out.push('READINESS');if(previous.nextLegalAction!==current.nextLegalAction)out.push('NEXT_ACTION');return out;}
function changedSources(previous:ProjectStatusSnapshot|null,current:ProjectStatusSnapshot):StatusChangedSource[]{const fields:[StatusChangedSource,keyof ProjectStatusSnapshot][]=[['CHECKPOINT','continuationHandoffDigest'],['RESUME','resumeHandbackDigest'],['PROGRESS','progressHandoffDigest'],['ESTIMATION','estimationHandoffDigest'],['COMPLETION','completionOutcomeDigest'],['CONDITIONS','conditionIndexDigest']];return fields.filter(([,key])=>previous===null?current[key]!==null:previous[key]!==current[key]).map(([name])=>name);}

export function createStatusTransitionRecord(previous:ProjectStatusSnapshot|null,current:ProjectStatusSnapshot,reopenWitness:StatusReopenWitness|null,options:OperationOptions):Result<StatusTransitionRecord>{
 if(previous===null){if(current.predecessorSnapshotDigest!==null||current.predecessorSemanticDigest!==null)return fail('STR23_GENESIS_PREDECESSOR_INVALID','Genesis status snapshot cannot declare a predecessor.');if(reopenWitness!==null)return fail('STR23_GENESIS_REOPEN_INVALID','Genesis status snapshot cannot use reopen witness.');}
 else{if(previous.projectId!==current.projectId||previous.lineageId!==current.lineageId)return fail('STR23_LINEAGE_MISMATCH','Status transition cannot cross project/lineage.');if(current.predecessorSnapshotDigest!==previous.snapshotDigest||current.predecessorSemanticDigest!==previous.semanticDigest)return fail('STR23_PREDECESSOR_MISMATCH','Successor snapshot does not bind exact predecessor snapshot and semantic digest.');}
 const reopening=previous?.lifecycleStatus==='COMPLETE'&&current.lifecycleStatus!=='COMPLETE';if(reopening){if(reopenWitness===null)return fail('STR23_REOPEN_WITNESS_REQUIRED','COMPLETE to non-COMPLETE transition requires explicit reopen witness.');const rv=verifyStatusReopenWitness(reopenWitness,options);if(!rv.ok||!rv.value)return rv.ok?fail('STR23_REOPEN_WITNESS_TAMPERED','Reopen witness failed verification.'):rv;if(reopenWitness.priorCompleteSnapshotDigest!==previous!.snapshotDigest)return fail('STR23_REOPEN_BINDING_MISMATCH','Reopen witness does not bind prior COMPLETE snapshot.');}else if(reopenWitness!==null)return fail('STR23_REOPEN_WITNESS_UNEXPECTED','Reopen witness is allowed only for COMPLETE reopen transitions.');
 const body={predecessorSnapshotDigest:previous?.snapshotDigest??null,successorSnapshotDigest:current.snapshotDigest,predecessorSemanticDigest:previous?.semanticDigest??null,successorSemanticDigest:current.semanticDigest,predecessorLifecycle:previous?.lifecycleStatus??null,successorLifecycle:current.lifecycleStatus,predecessorSchedule:previous?.scheduleHealth??null,successorSchedule:current.scheduleHealth,predecessorReadiness:previous?.continuationReadiness??null,successorReadiness:current.continuationReadiness,changedDimensions:changedDimensions(previous,current),reasonCodes:current.reasonCodeTrace,changedSourceIdentities:changedSources(previous,current),reopenWitnessDigest:reopenWitness?.witnessDigest??null};const d=digestValue(options,'STR23',body);if(!d.ok)return d;return ok(deepFreeze({...body,transitionDigest:d.value}));
}
function verifyTransition(t:StatusTransitionRecord,options:OperationOptions):Result<boolean>{const body={predecessorSnapshotDigest:t.predecessorSnapshotDigest,successorSnapshotDigest:t.successorSnapshotDigest,predecessorSemanticDigest:t.predecessorSemanticDigest,successorSemanticDigest:t.successorSemanticDigest,predecessorLifecycle:t.predecessorLifecycle,successorLifecycle:t.successorLifecycle,predecessorSchedule:t.predecessorSchedule,successorSchedule:t.successorSchedule,predecessorReadiness:t.predecessorReadiness,successorReadiness:t.successorReadiness,changedDimensions:t.changedDimensions,reasonCodes:t.reasonCodes,changedSourceIdentities:t.changedSourceIdentities,reopenWitnessDigest:t.reopenWitnessDigest};const d=digestValue(options,'STR23',body);return d.ok?ok(d.value===t.transitionDigest):d;}

export function guardStatusHistory(transitions:readonly StatusTransitionRecord[],options:OperationOptions):Result<StatusHistoryGuard>{const max=Math.max(1,Math.min(options.maxHistory??256,4096));const total=transitions.length;const sorted=[...transitions].sort((a,b)=>a.transitionDigest<b.transitionDigest?-1:a.transitionDigest>b.transitionDigest?1:0);const guard=new Guard({...options,maxUnits:Math.max(options.maxUnits??4096,Math.min(total,max)+1)});const accepted:string[]=[];const dup:string[]=[];const seen=new Set<string>();const byPred=new Map<string,Set<string>>();let processed=0;for(const t of sorted.slice(0,max)){const step=guard.step(t.transitionDigest);if(!step.ok)return step;const v=verifyTransition(t,options);if(!v.ok)return v;if(!v.value)return fail('SHG23_TRANSITION_TAMPERED','Status history contains tampered transition.',t.transitionDigest);processed+=1;if(seen.has(t.transitionDigest)){dup.push(t.transitionDigest);continue;}seen.add(t.transitionDigest);accepted.push(t.transitionDigest);const key=t.predecessorSnapshotDigest??'GENESIS';const set=byPred.get(key)??new Set<string>();set.add(t.successorSnapshotDigest);byPred.set(key,set);}const split=sortedUnique([...byPred.entries()].filter(([,v])=>v.size>1).map(([k])=>k));const truncated=total>max;const state:StatusHistoryGuard['state']=split.length>0?'CONFLICT':truncated?'TRUNCATED':'CLEAR';const body={state,acceptedTransitionDigests:accepted.sort(),duplicateTransitionDigests:sortedUnique(dup),splitBrainPredecessorDigests:split,historyTruncated:truncated,processedTransitionCount:processed,totalTransitionCount:total};const d=digestValue(options,'SHG23',body);if(!d.ok)return d;return ok(deepFreeze({...body,guardDigest:d.value}));}

export function createDelegatedProjectStatusHandoff(snapshot:ProjectStatusSnapshot,options:OperationOptions):Result<DelegatedProjectStatusHandoff>{const body={owner:'M23_PROJECT_STATUS' as const,consumer:'M20_RESPONSE' as const,snapshotDigest:snapshot.snapshotDigest,semanticDigest:snapshot.semanticDigest,lifecycleStatus:snapshot.lifecycleStatus,scheduleHealth:snapshot.scheduleHealth,continuationReadiness:snapshot.continuationReadiness,nextLegalAction:snapshot.nextLegalAction,reasonCodes:snapshot.reasonCodeTrace,validityBindingDigest:snapshot.validityBindingDigest};const d=digestValue(options,'DPH23',body);if(!d.ok)return d;return ok(deepFreeze({...body,handoffDigest:d.value}));}

export function createStatusFreshnessGate(snapshot:ProjectStatusSnapshot,current:StatusFreshnessObservation,options:OperationOptions):Result<StatusFreshnessGate>{
 const stale:string[]=[],conflict:string[]=[],indeterminate:string[]=[];
 const mandatory:[string,string|null,string|null][]=[['checkpoint',snapshot.checkpointDigest,current.checkpointDigest],['readiness',snapshot.checkpointReadinessCertificateDigest,current.checkpointReadinessCertificateDigest],['continuation',snapshot.continuationHandoffDigest,current.continuationHandoffDigest],['progress',snapshot.progressHandoffDigest,current.progressHandoffDigest]];
 for(const [name,before,now]of mandatory){if(before===null||now===null)indeterminate.push(name);else if(before!==now)stale.push(name);}
 const optional:[string,string|null,string|null][]=[['resume',snapshot.resumeHandbackDigest,current.resumeHandbackDigest],['estimation',snapshot.estimationHandoffDigest,current.estimationHandoffDigest],['completion',snapshot.completionOutcomeDigest,current.completionOutcomeDigest]];
 for(const[name,before,now]of optional){if(before===now)continue;if(before!==null&&now===null)indeterminate.push(name);else if(before!==null&&now!==null)conflict.push(name);else stale.push(name);}
 if(current.conditionIndexDigest===null)indeterminate.push('conditions');else if(snapshot.conditionIndexDigest!==current.conditionIndexDigest)stale.push('conditions');
 const state:StatusFreshnessGate['state']=conflict.length>0?'CONFLICT':indeterminate.length>0?'INDETERMINATE':stale.length>0?'STALE':'CURRENT';const body={snapshotDigest:snapshot.snapshotDigest,state,reusable:state==='CURRENT',staleSubjects:sortedUnique(stale),conflictSubjects:sortedUnique(conflict),indeterminateSubjects:sortedUnique(indeterminate)};const d=digestValue(options,'SFG23',body);if(!d.ok)return d;return ok(deepFreeze({...body,gateDigest:d.value}));
}
