import type{
  DelegatedProjectStatusHandoff,
  OperationOptions,
  ProjectStatusDecision,
  ProjectStatusInput,
  ProjectStatusIntegrityReceipt,
  ProjectStatusSemanticDigest,
  ProjectStatusSnapshot,
  Result,
  StatusFreshnessGate,
  StatusFreshnessObservation,
  StatusHistoryGuard,
  StatusReopenWitness,
  StatusReopenWitnessInput,
  StatusTransitionRecord,
}from'./types.js';
import{deriveProjectStatusDecision}from'./s04-readiness.js';
import{deepFreeze,digestValue,fail,isSha256,ok,sortedUnique,stableJson,validId,Guard}from'./utils.js';

function snapshotCore(input:ProjectStatusInput,decision:ProjectStatusDecision,predecessorSnapshotDigest:string|null){return{projectId:input.intent.projectId,lineageId:input.intent.lineageId,intentDigest:input.intent.intentDigest,checkpointDigest:input.continuationSource?.checkpoint.checkpointDigest??null,progressSnapshotDigest:input.progressSource?.snapshot.snapshotDigest??null,estimationSnapshotDigest:input.estimationSource?.snapshot.snapshotDigest??null,completionOutcomeDigest:input.completionOutcome?.outcomeDigest??null,conditionIndexDigest:decision.conditionIndex.indexDigest,lifecycleStatus:decision.lifecycle.status,scheduleHealth:decision.schedule.status,continuationReadiness:decision.readiness.status,nextLegalAction:decision.readiness.nextLegalAction,blockingConditionIds:decision.blockers.blockingConditionIds,recoveryConditionIds:decision.blockers.recoveryConditionIds,conflictConditionIds:decision.blockers.conflictConditionIds,predecessorSnapshotDigest};}

export function createProjectStatusSnapshot(input:ProjectStatusInput,predecessorSnapshotDigest:string|null,options:OperationOptions):Result<ProjectStatusSnapshot>{if(predecessorSnapshotDigest!==null&&!isSha256(predecessorSnapshotDigest))return fail('PSS23_PREDECESSOR_INVALID','Status predecessor must be null or SHA-256 snapshot digest.');const decision=deriveProjectStatusDecision(input,options);if(!decision.ok)return decision;const core=snapshotCore(input,decision.value,predecessorSnapshotDigest);const semantic=digestValue(options,'PSD23',core);if(!semantic.ok)return semantic;const snapshot=digestValue(options,'PSS23',{...core,semanticDigest:semantic.value});if(!snapshot.ok)return snapshot;return ok(deepFreeze({...core,semanticDigest:semantic.value,snapshotDigest:snapshot.value}));}

export function createProjectStatusIntegrityReceipt(snapshot:ProjectStatusSnapshot,input:ProjectStatusInput,options:OperationOptions):Result<ProjectStatusIntegrityReceipt>{const decision=deriveProjectStatusDecision(input,options);if(!decision.ok)return decision;const core=snapshotCore(input,decision.value,snapshot.predecessorSnapshotDigest);const semantic=digestValue(options,'PSD23',core);if(!semantic.ok)return semantic;const expected=digestValue(options,'PSS23',{...core,semanticDigest:semantic.value});if(!expected.ok)return expected;const valid=semantic.value===snapshot.semanticDigest&&expected.value===snapshot.snapshotDigest&&stableJson(core)===stableJson({projectId:snapshot.projectId,lineageId:snapshot.lineageId,intentDigest:snapshot.intentDigest,checkpointDigest:snapshot.checkpointDigest,progressSnapshotDigest:snapshot.progressSnapshotDigest,estimationSnapshotDigest:snapshot.estimationSnapshotDigest,completionOutcomeDigest:snapshot.completionOutcomeDigest,conditionIndexDigest:snapshot.conditionIndexDigest,lifecycleStatus:snapshot.lifecycleStatus,scheduleHealth:snapshot.scheduleHealth,continuationReadiness:snapshot.continuationReadiness,nextLegalAction:snapshot.nextLegalAction,blockingConditionIds:snapshot.blockingConditionIds,recoveryConditionIds:snapshot.recoveryConditionIds,conflictConditionIds:snapshot.conflictConditionIds,predecessorSnapshotDigest:snapshot.predecessorSnapshotDigest});const body={snapshotDigest:snapshot.snapshotDigest,recomputedDecisionDigest:decision.value.decisionDigest,recomputedSemanticDigest:semantic.value,valid};const d=digestValue(options,'PSI23',body);if(!d.ok)return d;return ok(deepFreeze({...body,receiptDigest:d.value}));}

export function createProjectStatusSemanticDigest(snapshot:ProjectStatusSnapshot,input:ProjectStatusInput,options:OperationOptions):Result<ProjectStatusSemanticDigest>{const receipt=createProjectStatusIntegrityReceipt(snapshot,input,options);if(!receipt.ok)return receipt;if(!receipt.value.valid)return fail('PSD23_SNAPSHOT_TAMPERED','Semantic digest requires independently verified project-status snapshot.');return ok(deepFreeze({snapshotDigest:snapshot.snapshotDigest,semanticDigest:snapshot.semanticDigest}));}

export function createStatusReopenWitness(input:StatusReopenWitnessInput,options:OperationOptions):Result<StatusReopenWitness>{if(!validId(input.witnessId)||!input.reasonCode.trim()||!isSha256(input.priorCompleteSnapshotDigest)||!isSha256(input.authorizationFactDigest))return fail('SRW23_INPUT_INVALID','Reopen witness requires stable id, reason and SHA-256 prior/authorization facts.');if(input.owner==='M27_ASSURANCE')return fail('SRW23_OWNER_NOT_AVAILABLE','M27_ASSURANCE reopen authority is unavailable before M27 exists.');if(input.owner!=='EXTERNAL_CANONICAL')return fail('SRW23_OWNER_INVALID','Reopen witness owner is not allowed.');const body={witnessId:input.witnessId,owner:input.owner,priorCompleteSnapshotDigest:input.priorCompleteSnapshotDigest,authorizationFactDigest:input.authorizationFactDigest,reasonCode:input.reasonCode};const d=digestValue(options,'SRW23',body);if(!d.ok)return d;return ok(deepFreeze({...body,witnessDigest:d.value}));}
export function verifyStatusReopenWitness(value:StatusReopenWitness,options:OperationOptions):Result<boolean>{const rebuilt=createStatusReopenWitness(value,options);return rebuilt.ok?ok(rebuilt.value.witnessDigest===value.witnessDigest):rebuilt;}

export function createStatusTransitionRecord(previous:ProjectStatusSnapshot|null,current:ProjectStatusSnapshot,reopenWitness:StatusReopenWitness|null,options:OperationOptions):Result<StatusTransitionRecord>{if(previous===null){if(current.predecessorSnapshotDigest!==null)return fail('STR23_GENESIS_PREDECESSOR_INVALID','Genesis status snapshot cannot declare a predecessor.');if(reopenWitness!==null)return fail('STR23_GENESIS_REOPEN_INVALID','Genesis status snapshot cannot use reopen witness.');const body={predecessorSnapshotDigest:null,successorSnapshotDigest:current.snapshotDigest,predecessorLifecycle:null,successorLifecycle:current.lifecycleStatus,reopenWitnessDigest:null};const d=digestValue(options,'STR23',body);if(!d.ok)return d;return ok(deepFreeze({...body,transitionDigest:d.value}));}
 if(previous.projectId!==current.projectId||previous.lineageId!==current.lineageId)return fail('STR23_LINEAGE_MISMATCH','Status transition cannot cross project/lineage.');if(current.predecessorSnapshotDigest!==previous.snapshotDigest)return fail('STR23_PREDECESSOR_MISMATCH','Successor snapshot does not bind exact predecessor snapshot.');const reopening=previous.lifecycleStatus==='COMPLETE'&&current.lifecycleStatus!=='COMPLETE';if(reopening){if(reopenWitness===null)return fail('STR23_REOPEN_WITNESS_REQUIRED','COMPLETE to non-COMPLETE transition requires explicit reopen witness.');const rv=verifyStatusReopenWitness(reopenWitness,options);if(!rv.ok||!rv.value)return rv.ok?fail('STR23_REOPEN_WITNESS_TAMPERED','Reopen witness failed verification.'):rv;if(reopenWitness.priorCompleteSnapshotDigest!==previous.snapshotDigest)return fail('STR23_REOPEN_BINDING_MISMATCH','Reopen witness does not bind prior COMPLETE snapshot.');}else if(reopenWitness!==null)return fail('STR23_REOPEN_WITNESS_UNEXPECTED','Reopen witness is allowed only for COMPLETE reopen transitions.');const body={predecessorSnapshotDigest:previous.snapshotDigest,successorSnapshotDigest:current.snapshotDigest,predecessorLifecycle:previous.lifecycleStatus,successorLifecycle:current.lifecycleStatus,reopenWitnessDigest:reopenWitness?.witnessDigest??null};const d=digestValue(options,'STR23',body);if(!d.ok)return d;return ok(deepFreeze({...body,transitionDigest:d.value}));}

function verifyTransition(t:StatusTransitionRecord,options:OperationOptions):Result<boolean>{const body={predecessorSnapshotDigest:t.predecessorSnapshotDigest,successorSnapshotDigest:t.successorSnapshotDigest,predecessorLifecycle:t.predecessorLifecycle,successorLifecycle:t.successorLifecycle,reopenWitnessDigest:t.reopenWitnessDigest};const d=digestValue(options,'STR23',body);return d.ok?ok(d.value===t.transitionDigest):d;}

export function guardStatusHistory(transitions:readonly StatusTransitionRecord[],options:OperationOptions):Result<StatusHistoryGuard>{const max=Math.max(1,Math.min(options.maxHistory??256,4096));const total=transitions.length;const sorted=[...transitions].sort((a,b)=>a.transitionDigest<b.transitionDigest?-1:a.transitionDigest>b.transitionDigest?1:0);const guard=new Guard({...options,maxUnits:Math.max(options.maxUnits??4096,Math.min(total,max)+1)});const accepted:string[]=[];const dup:string[]=[];const seen=new Set<string>();const byPred=new Map<string,Set<string>>();let processed=0;for(const t of sorted.slice(0,max)){const step=guard.step(t.transitionDigest);if(!step.ok)return step;const v=verifyTransition(t,options);if(!v.ok)return v;if(!v.value)return fail('SHG23_TRANSITION_TAMPERED','Status history contains tampered transition.',t.transitionDigest);processed+=1;if(seen.has(t.transitionDigest)){dup.push(t.transitionDigest);continue;}seen.add(t.transitionDigest);accepted.push(t.transitionDigest);const key=t.predecessorSnapshotDigest??'GENESIS';const set=byPred.get(key)??new Set<string>();set.add(t.successorSnapshotDigest);byPred.set(key,set);}
 const split=sortedUnique([...byPred.entries()].filter(([,v])=>v.size>1).map(([k])=>k));const truncated=total>max;const state:StatusHistoryGuard['state']=split.length>0?'CONFLICT':truncated?'TRUNCATED':'CLEAR';const body={state,acceptedTransitionDigests:accepted.sort(),duplicateTransitionDigests:sortedUnique(dup),splitBrainPredecessorDigests:split,historyTruncated:truncated,processedTransitionCount:processed,totalTransitionCount:total};const d=digestValue(options,'SHG23',body);if(!d.ok)return d;return ok(deepFreeze({...body,guardDigest:d.value}));}

export function createDelegatedProjectStatusHandoff(snapshot:ProjectStatusSnapshot,options:OperationOptions):Result<DelegatedProjectStatusHandoff>{const body={owner:'M23_PROJECT_STATUS' as const,consumer:'M20_RESPONSE' as const,snapshotDigest:snapshot.snapshotDigest,lifecycleStatus:snapshot.lifecycleStatus,scheduleHealth:snapshot.scheduleHealth,continuationReadiness:snapshot.continuationReadiness,nextLegalAction:snapshot.nextLegalAction};const d=digestValue(options,'DPH23',body);if(!d.ok)return d;return ok(deepFreeze({...body,handoffDigest:d.value}));}

export function createStatusFreshnessGate(snapshot:ProjectStatusSnapshot,current:StatusFreshnessObservation,options:OperationOptions):Result<StatusFreshnessGate>{const stale:string[]=[];if(snapshot.checkpointDigest!==current.checkpointDigest)stale.push('checkpoint');if(snapshot.progressSnapshotDigest!==current.progressSnapshotDigest)stale.push('progress');if(snapshot.estimationSnapshotDigest!==current.estimationSnapshotDigest)stale.push('estimation');if(snapshot.completionOutcomeDigest!==current.completionOutcomeDigest)stale.push('completion');if(snapshot.conditionIndexDigest!==current.conditionIndexDigest)stale.push('conditions');const body={snapshotDigest:snapshot.snapshotDigest,reusable:stale.length===0,staleSubjects:sortedUnique(stale)};const d=digestValue(options,'SFG23',body);if(!d.ok)return d;return ok(deepFreeze({...body,gateDigest:d.value}));}
