import type{Diagnostic,OperationOptions,Result}from'./types.js';
const HEX64=/^[0-9a-f]{64}$/i;
export function ok<T>(value:T):Result<T>{return{ok:true,value};}
export function fail<T>(code:string,message:string,subject?:string):Result<T>{const d:Diagnostic=subject===undefined?{code,message}:{code,message,subject};return{ok:false,diagnostics:[d]};}
export function compareCodePoint(a:string,b:string){return a<b?-1:a>b?1:0;}
export function sortedUnique(values:readonly string[]){return[...new Set(values)].sort(compareCodePoint);}
export function deepFreeze<T>(value:T):T{if(value&&typeof value==='object'){Object.freeze(value);for(const v of Object.values(value as Record<string,unknown>)){if(v&&typeof v==='object'&&!Object.isFrozen(v))deepFreeze(v);}}return value;}
export function validId(value:string){return/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value)&&!['__proto__','constructor','prototype'].includes(value);}
export function isSha256(value:string|null|undefined){return typeof value==='string'&&/^sha256:[0-9a-f]{64}$/.test(value);}
function canonical(value:unknown):unknown{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object'){const out:Record<string,unknown>={};for(const key of Object.keys(value as Record<string,unknown>).sort(compareCodePoint))out[key]=canonical((value as Record<string,unknown>)[key]);return out;}return value;}
export function stableJson(value:unknown){return JSON.stringify(canonical(value));}
export function digestValue(options:OperationOptions,kind:string,payload:unknown):Result<string>{if(options.cancellation?.isCancelled()===true)return fail('OPERATION_CANCELLED','Project Status Engine operation cancelled.',kind);if(options.digest.algorithm!=='sha256')return fail('DIGEST_ALGORITHM_INVALID','Project Status Engine requires SHA-256.',kind);try{const raw=options.digest.digest(`${kind}\n${stableJson(payload)}`);if(!HEX64.test(raw))return fail('DIGEST_OUTPUT_INVALID','Injected digest capability returned a non SHA-256 hex digest.',kind);return ok(`sha256:${raw.toLowerCase()}`);}catch(error){return fail('DIGEST_CAPABILITY_FAILED',error instanceof Error?error.message:'Injected digest capability failed.',kind);}}
export function digestPlain(options:OperationOptions,payload:unknown):Result<string>{if(options.cancellation?.isCancelled()===true)return fail('OPERATION_CANCELLED','Project Status Engine operation cancelled.');if(options.digest.algorithm!=='sha256')return fail('DIGEST_ALGORITHM_INVALID','Project Status Engine requires SHA-256.');try{const raw=options.digest.digest(stableJson(payload));if(!HEX64.test(raw))return fail('DIGEST_OUTPUT_INVALID','Injected digest capability returned a non SHA-256 hex digest.');return ok(`sha256:${raw.toLowerCase()}`);}catch(error){return fail('DIGEST_CAPABILITY_FAILED',error instanceof Error?error.message:'Injected digest capability failed.');}}
export function sameCanonical(a:unknown,b:unknown){return stableJson(a)===stableJson(b);}
export function safeEpoch(value:number|null){return value===null||Number.isSafeInteger(value)&&value>=0;}
export class Guard{private used=0;private readonly max:number;constructor(private readonly options:OperationOptions){this.max=options.maxUnits??4096;}step(subject:string):Result<true>{if(this.options.cancellation?.isCancelled()===true)return fail('OPERATION_CANCELLED','Project Status Engine operation cancelled.',subject);if(!Number.isSafeInteger(this.max)||this.max<=0)return fail('OPERATION_BUDGET_INVALID','maxUnits must be a positive safe integer.',subject);this.used+=1;if(this.used>this.max)return fail('OPERATION_BUDGET_EXCEEDED','Project Status Engine operation budget exceeded.',subject);return ok(true);}}
